### ISSUE TITLE
trainer based on components and ignite

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1]

**Comment by ericspod** [comment]
I had extended ignite.Engine to add a few features that are perhaps optional for at least the MVP:
* methods for converting to and from tensors
* wrapping the forward pass of the network to incorporate optional data parallel invocation
* providing a method to act as the default iteration loop implementation
* basic inference helpers

None of this is strictly necessary as Ignite provides enough through Engine, they are useful helper facilities that other code shouldn't rely on. For now we'll stick with the base Engine.
