### ISSUE TITLE
Different default values for 2D and 3D U-Nets

### ISSUE THREAD

**Issue by aylward** [Project-MONAI/MONAI#101]
This codebase assumes that 3-D U-Nets and 2-D U-Nets should be the same class with different parameters. This makes sense, however they need to find a way to make the default parameters different for 3-D U-Nets and 2-D U-Nets, because the sane defaults for stride, number of filters, etc are different. 

Issue reported by @HastingsGreer @brad-t-moore @floryst

**Comment by wyli** [comment]
I feel the densenet 'factory' example in our codebase is a one possibility to address this issue:
https://github.com/Project-MONAI/MONAI/blob/master/monai/networks/nets/densenet3d.py#L21-L24

any idea? @ericspod (I'm also assigning this ticket to you)

**Comment by ericspod** [comment]
I think the factory way is the method to use. I would suggest the sane defaults depend more on the application area rather than the dimensionality of the network.
