### ISSUE TITLE
Error in citation

### ISSUE THREAD

**Issue by FabianIsensee** [Project-MONAI/MONAI#1013]
Hi,
this architecture seems to be a reimplementation of the dynamic U-net used by nnU-Net:

https://github.com/Project-MONAI/MONAI/blob/74a89f8eb2e1aa376e32b481f1bf5ffe11caca92/monai/networks/nets/nnunet.py#L20

However, the paper you are providing as reference is my BraTS 2018 contribution which has nothing to do with that (it has a rather unfortunate Title, though :-) ):
No New-Net <https://arxiv.org/pdf/1809.10483.pdf>

It would be great if you could cite the correct paper(s): https://arxiv.org/abs/1904.08128, https://arxiv.org/abs/1809.10486

As a side-note: nnU-Net is so much more than the architecture. Automated configuration of the entire pipeline is the key contribution. In fact (and as we attempted to highlight by choosing the name) the architecture is quite irrelevant (as long as it is kind of okay-ish). So naming the dynamic U-Net architecture nnUNet seems misleading. 

Best,
Fabian

**Comment by wyli** [comment]
thanks @FabianIsensee! we'll update those. In general we prefer to cite paper that has gone through peer reviews, I thought this is the most recent one? https://link.springer.com/chapter/10.1007/978-3-030-11726-9_21

**Comment by FabianIsensee** [comment]
Hi,
the link you provided points to the same paper than the one you are currently providing (and which is incorrect). The 'No New Net' paper has nothing to do with nnU-Net, it just has an unfortunate title (it was written before we even knew we would name nnU-Net nnU-Net): The 'No New Net' paper merely describes my participation in BraTS 2018 which was based on a simple static 3D U-Net implementation with BraTS-specific optimizations on top. nnU-Net is a framework that dynamically adapts an entire segmentation pipeline to new datasets and that (by design) cannot do challenge-specific optimizations. nnU-Net is not (yet) published in a peer reviewed journal, so there is no alternative to the arXiv publications :-)
Best,
Fabian

**Comment by Nic-Ma** [comment]
Thanks @FabianIsensee to correct it, will submit a PR to update to cite: https://arxiv.org/abs/1904.08128, https://arxiv.org/abs/1809.10486

**Comment by Nic-Ma** [comment]
I submitted PR #1019 to update the cite paper in NNUNet.
Thanks.

**Comment by FabianIsensee** [comment]
Thanks! There has already been some confusion in the past about the name of this paper and I would like to minimize confusion as much as possible looking forward. This is of course on us for choosing such bad naming :-)

**Comment by wyli** [comment]
a remaining task is to change the network class name of the implementation

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I want to double confirm what's the expected network name? I will update it.
Thanks.

**Comment by Nic-Ma** [comment]
Should we change to `dynUNet` as @tvercaut suggested?
Thanks.

**Comment by Nic-Ma** [comment]
@tvercaut and @FabianIsensee , do you also think we should change the NNUnet network name?
If not necessary, we can keep it for v0.3 release.

Thanks.

**Comment by FabianIsensee** [comment]
Apologies, I did not see this comment. I think it would be better to rename it to dynUNet or something similar. If the implementation was inspired by my `Generic_UNet` then I would be happy if you could still reference nnU-Net in the class description.
Best,
Fabian

**Comment by Nic-Ma** [comment]
OK, thanks for the double confirm, I will try to update the network name to `dynUNet` later.
Thanks.
