### ISSUE TITLE
codebase restructuring (examples and research)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1015]
**Is your feature request related to a problem? Please describe.**
based on the working group discussions, we propose to (full doc in wiki https://github.com/Project-MONAI/MONAI/wiki/proposed-codebase-re-structuring)
- move the current `MONAI/examples` into https://github.com/Project-MONAI/Tutorials repo
- move the current `MONAI/research` to a standalone repo `https://github.com/Project-MONAI/[name-to-be-confirmed].git`

----
- [x] move MONAI/examples to project-monai/tutorials
- [x] move MONAI/research to project-monai/research-contributions
- [x] update the relevant monai.io links
- [x] update the relevant docs.monai.io links
- [x] research repo contributing guidelines
- [x] research contrib. guidelines link on monai.io
- [x] revise the monai.io homepage to highlight the tutorials
- [x] revise the table of content in https://monai.io/start.html
- [x] make a release checklist (for admins; steps to check all sub-repos)

see also https://github.com/Project-MONAI/Tutorials/issues/2

cc @pfjaeger @atbenmurray @rijobro @mibaumgartner

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your summary, I can start from moving examples when the 2D segmentation PR merged.

**Comment by wyli** [comment]
added a release checklist to the project wiki: https://github.com/Project-MONAI/MONAI/wiki/Release-checklist

**Comment by rijobro** [comment]
If we wanted, we could also create an issue from that wiki page with tickboxes as we get close to each release date so that we can be sure everything gets done (potentially by different people).

**Comment by wyli** [comment]
> If we wanted, we could also create an issue from that wiki page with tickboxes as we get close to each release date so that we can be sure everything gets done (potentially by different people).

sounds great! could you help create a ticket?

**Comment by rijobro** [comment]
Sure, but I think it makes sense to do that about a week before releasing. That ok?

**Comment by wyli** [comment]
update: the research repo will be named `Project-MONAI/research_contributions` according to the working group voting

**Comment by Nic-Ma** [comment]
After internal discussion, I will combine `notebooks` and `examples`, then restructure:
3d_segmentation
2d_segmentation
3d_classification
modules
acceleration

And update all the related documents or wiki pages.

Thanks.
