### ISSUE TITLE
fast training tutorial/example

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1017]
**Is your feature request related to a problem? Please describe.**
would be great to combine the new features in a single tutorial/example to show the segmentation efficiencies:
- CacheDataset/SmartCache
- AMP
- Novograd

this ticket requires an integration of novograd  in the core codebase (new notebook tutorial should go to https://github.com/Project-MONAI/Tutorials)

see also: 
- https://github.com/NVIDIA/OpenSeq2Seq/blob/master/open_seq2seq/optimizers/novograd.py
- https://nvidia.github.io/apex/optimizers.html#apex.optimizers.FusedNovoGrad

cc @Nic-Ma

**Comment by Nic-Ma** [comment]
Looks good a topic in MONAI v0.3 release, @yiheng-wang-nv and I will work on it soon.
Thanks.

**Comment by yiheng-wang-nv** [comment]
FYI, a pytorch implementation can be found in:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechRecognition/Jasper/optimizers.py

**Comment by Nic-Ma** [comment]
Implemented tutorial in PR: https://github.com/Project-MONAI/tutorials/pull/22.
Thanks.

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/22 and #1031
