### ISSUE TITLE
Strange behavior of CheckpointSaver with key_metric_n_saved

### ISSUE THREAD

**Issue by ChenglongWang** [Project-MONAI/MONAI#1022]
**Describe the bug**
When setting `key_metric_n_saved` argument, CheckpointSaver crashed.
I noticed that when setting `key_metric_n_saved=4`, the maximum saved model is sometimes less than 4. 
Some models are unexpectedly removed. It may caused the crash.
I’m considering it may be a ignite-related issue.

**To Reproduce**
My validation handler is like:
```
val_handlers = [
            StatsHandler(output_transform=lambda x: None),
            TensorBoardStatsHandler(summary_writer=writer, tag_name="val_acc"),
            CheckpointSaver(save_dir=model_dir, save_dict={"net": net}, save_key_metric=True, key_metric_n_saved=4),
            MyTensorBoardImageHandler(
                summary_writer=writer, 
                batch_transform=lambda x : (None, None),
                output_transform=lambda x: x["image"],
                prefix_name='Val'
            )
        ]
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.7
 - MONAI version [e.g. git commit hash]: 1d2dce719e8adae2fba2df7b58dfb24ca4531c3a
 - CUDA/cuDNN version: 10.2
 - Ignite version: 0.3.0

**Additional context**
Error log:
```
ERROR:ignite.engine.engine.SupervisedTrainer:Exception: [Errno 2] No such file or directory: '/homes/Data/exp/test/Models/Best/net_key_metric=0.5.pth'
Traceback (most recent call last):
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 942, in _internal_run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 607, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 443, in wrapper
    return handler(engine, *args, **kwargs)
  File "/homes/Code/MONAI/monai/handlers/validation_handler.py", line 64, in __call__
    self.validator.run(engine.state.epoch)
  File "/homes/Code/MONAI/monai/engines/evaluator.py", line 91, in run
    super().run()
  File "/homes/Code/MONAI/monai/engines/workflow.py", line 157, in run
    super().run(data=self.data_loader, epoch_length=len(self.data_loader))
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 850, in run
    return self._internal_run()
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 952, in _internal_run
    self._handle_exception(e)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 714, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 607, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/homes/Code/MONAI/monai/handlers/stats_handler.py", line 145, in exception_raised
    raise e
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 942, in _internal_run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 607, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/homes/Code/MONAI/monai/handlers/checkpoint_saver.py", line 195, in metrics_completed
    self._key_metric_checkpoint(engine, self.save_dict)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/handlers/checkpoint.py", line 407, in __call__
    super(ModelCheckpoint, self).__call__(engine)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/handlers/checkpoint.py", line 204, in __call__
    self.save_handler.remove(item.filename)
  File "/homes/.miniconda3/lib/python3.7/site-packages/ignite/handlers/checkpoint.py", line 285, in remove
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/homes/Data/exp/test/Models/Best/net_key_metric=0.5.pth'
```

**Comment by Nic-Ma** [comment]
Hi @ChenglongWang ,

Thanks for your bug report, may I know what's the model name on disk?
It's `net_key_metric=0.5.pth' or `net_key_metric=0.5000.pth'?
And could you please help try `key_metric_n_saved=1`? I never faced this issue before with n_saved=1.
We may need your help to provide a simple program to reproduce the issue.

Thanks.

**Comment by ChenglongWang** [comment]
Dear @Nic-Ma 

Thank you for your reply. I have also never experienced this issue with n_saved=1. 
It's **net_key_metric=0.5.pth** not net_key_metric=0.5000.pth

And I reproduced the error again:
here are some snapshots of saved model during the training, notice that my setting is `key_metric_n_saved=4`: 

Snapshot 1: 
![Annotation 2020-09-11 202441](https://user-images.githubusercontent.com/4251375/92927223-dfb5c400-f46f-11ea-964b-75dbad94941c.png)
Snapshot 2:
![Annotation 2020-09-11 202533](https://user-images.githubusercontent.com/4251375/92927276-f0fed080-f46f-11ea-8f88-988cc832572c.png)

Last snapshot right before crash: 
![Annotation 2020-09-11 202652](https://user-images.githubusercontent.com/4251375/92927829-cf521900-f470-11ea-8b66-ab4882460c4d.png)

Error msg is :
the model `net_key_metric=0.5833.pth` shown in snapshot 2, has already been removed shown in the last snapshot.
FileNotFoundError: [Errno 2] No such file or directory: '/homes/clwang/Data/picc/exp/test/Models/Best/net_key_metric=0.5833.pth'

I'm using the vgg16 architecture in torchvision for simple classification task.
Val metric is the Accuracy from ignite:
```
evaluator = SupervisedEvaluator(
            device=device,
            val_data_loader=test_loader,
            network=net,
            inferer=SimpleInferer(),
            post_transform=train_post_transforms,
            key_val_metric={"val_acc": Accuracy(output_transform=output_onehot_transform,is_multilabel=True)},
            val_handlers=val_handlers,
        )
```

Hope this information could help.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Could you please help take a look at this issue?
I think maybe it's a known issue of ignite v0.3?
If not, I can try to debug it next week.

Thanks.

**Comment by vfdev-5** [comment]
Hi @Nic-Ma yes, may be related to https://github.com/pytorch/ignite/pull/847
it was a bug with v0.3 and was fixed in v0.4.X.

**Comment by ChenglongWang** [comment]
@Nic-Ma and @vfdev-5 Thank you for your help.
BTW, is the current MONAI compatible with v0.4.X ignite? Upgrading ignite maybe a better solution for me.

**Comment by vfdev-5** [comment]
@ChenglongWang I think there are some minor incompabilities between MONAI and Ignite v0.4.X. @Nic-Ma can detail it better than me...

**Comment by Nic-Ma** [comment]
Hi @ChenglongWang ,

Now MONAI only works with ignite v0.3, but we will try to update MONAI and be compatible with ignite v0.4.2 when it's release soon, because as @vfdev-5 said, v0.4.2 will fully support distributed training features.

Thanks.

**Comment by ChenglongWang** [comment]
@vfdev-5 @Nic-Ma Thank you for your kind support. I just fixed the issue according to https://github.com/pytorch/ignite/pull/847 as a temporary solution. Looking forward to seeing the new MONAI.
