### ISSUE TITLE
Deconvolutions improve performance of AH-Net

### ISSUE THREAD

**Issue by mmarcinkiewicz** [Project-MONAI/MONAI#1023]
**Describe the bug**
In the current environment deconvolutions work significantly faster with mixed precision than trilinear interpolation for upsampling. In the current Monai implementation of AH-Net the `upsample_mode` defaults to "trilinear", which is suboptimal.  

**To Reproduce**
Run training with `upsample_mode="trilinear"` and `upsample_mode="transpose"`.

**Expected behavior**
The default `upsample_mode` is changed to `transpose`.

**Screenshots**
Throughput measured on V100 and A100 for a 3D workload.
![image](https://user-images.githubusercontent.com/43240942/92876049-f75a6180-f409-11ea-9bdf-0851fd7dca40.png)

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - Python 3.6
 - MONAI version f1998b72a941d1e5f9578a66dc1c20b01913caab
 - CUDA 11, cuDNN 8.0.3/8.0.4
 - GPUs: V100, A100

**Additional context**
In cuDNN 8.0.3 deconvolutions have Tensor Core support which improves their performance significantly. 
Currently there are issues being tracked for Pytorch and cuDNN which might improve performance. I'll monitor the status and update if needed.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I remember you fixed some determinism issue about the upsampling in AHNet, is it related to this ticket?

Thanks.

**Comment by wyli** [comment]
> Hi @yiheng-wang-nv ,
> 
> I remember you fixed some determinism issue about the upsampling in AHNet, is it related to this ticket?
> 
> Thanks.

that's noted in the docstring
https://github.com/Project-MONAI/MONAI/blob/8fc4f5dd5ea4d3726fdd9e001eacf517263625ac/monai/networks/nets/ahnet.py#L353-L355

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv ,
> 
> I remember you fixed some determinism issue about the upsampling in AHNet, is it related to this ticket?
> 
> Thanks.

FYI, the non-determinism issue is explained in an old [PR](https://github.com/Project-MONAI/MONAI/pull/815). Generally speaking, `torch.nn.functional.interpolate() ` and `torch.nn.MaxPool1d/2d/3d()` use `atomicAdd ` which introduce the non-determinism results. 
This ticket is about the computing speed between `trilinear` and `deconvolution`.
