### ISSUE TITLE
Get started with Dicom Images

### ISSUE THREAD

**Issue by roshnikotian15** [Project-MONAI/MONAI#1032]
Can someone please help me to work with Dicom?

**Comment by Nic-Ma** [comment]
Added example to load DICOM images in MONAI: https://github.com/Project-MONAI/tutorials/pull/23
Thanks.

**Comment by wyli** [comment]
tutorial available at https://github.com/Project-MONAI/tutorials/blob/master/load_medical_images.ipynb

**Comment by function2-llx** [comment]
> tutorial available at https://github.com/Project-MONAI/tutorials/blob/master/load_medical_images.ipynb

this link is unavailable now

**Comment by Nic-Ma** [comment]
Hi @function2-llx ,

Please use this link instead: https://github.com/Project-MONAI/tutorials/blob/master/modules/load_medical_images.ipynb

Thanks.
