### ISSUE TITLE
runtests.sh fails

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1036]
**Describe the bug**
`./runtests.sh --codeformat --coverage` gives the same error both on my local OSX and remote linux.

Output is:

```
/root/MONAI:/root/MONAI
Compiling and installing MONAI cpp extensions...
  File "setup.py", line 29
    print(f"setup.py with torch {torch.__version__}")
                                                   ^
SyntaxError: invalid syntax
```

**To Reproduce**
1. `cd to MONAI root`
2. `./runtests.sh --codeformat --coverage`

**Expected behavior**
Tests should run

**Environment (please complete the following information):**
 - OS: linux and OSX
 - Python version: 3.6.9 (linux) 3.8.5 (OSX)
 - MONAI version: master (fa521a9291405ed8a398a6f8a97ad5a8f7c46e96)

**Comment by rijobro** [comment]
It looks like `runtests.sh` runs `python`, so it's actually running my `python2`, not `python3`. Perhaps the python executable can be passed as argument.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Could you please help try to run python3 instead again?
Thanks.

**Comment by rijobro** [comment]
I manually edited `runtests.sh` such that all occurrences of `python` became `python3` and everything worked fine. But I'm not sure how to get the bash script to use `python3` be default.

**Comment by Nic-Ma** [comment]
I think you can use `sudo update-alternatives --config python` to config your default python path.

Thanks.

**Comment by wyli** [comment]
I'm improving the error message in `runtests.sh`, but I don't think replacing `python3` with `python` is a universal solution...

**Comment by rijobro** [comment]
No, I don't think we should be switching `python` with `python3`, but we could give the user the option to pass the path to their python executable for example.
