### ISSUE TITLE
"Getting started with an end to end Colab tutorial"  gives an error

### ISSUE THREAD

**Issue by FrancescoLR** [Project-MONAI/MONAI#1040]
The User guide "Getting started with an end to end Colab tutorial" (https://colab.research.google.com/drive/1boqy7ENpKrqaJoxFlbHIBnIODAs1Ih1T) gives an error on cell 16 when run on Colab with the default GPU:

AttributeError: Optional import: from ignite.engine import Engine (No module named 'ignite').

Ignite is of course installed and imported in the previous cell.

**Comment by wyli** [comment]
Hi @FrancescoLR  after running the `!pip install`, cell could you try: menu bar -> Runtime -> Restart and run all   apparently colab has some issue with the pip install commands

**Comment by FrancescoLR** [comment]
Thanks @wyli! That works, so it's indeed a colab issue.
