### ISSUE TITLE
Ordered patch using dictionary transform

### ISSUE THREAD

**Issue by kissievendor** [Project-MONAI/MONAI#1048]
**Is your feature request related to a problem? Please describe.**
I want to select patches for 3D segmentation, but I want to make sure that I have either all possible patches, or no overlapping patches. 

**Describe the solution you'd like**
SpatialCropSampled / GridDatasetd. Something that ensures non overlapping patches. 

**Describe alternatives you've considered**
Alternatively. Return e.g. coordinates for the extracted patches.

**Comment by Nic-Ma** [comment]
Hi @kissievendor ,

Thanks for your interest here!
I think you want to get no-overlapping patches in RandSpatialCrop or all the possible patches with no overlap?
That is not supported in MONAI so far, but looks an interesting feature, I will raise a discussion internally soon.
Or if you have interest, welcome to submit a PR for it.

Thanks.

**Comment by wyli** [comment]
related to these? https://github.com/Project-MONAI/MONAI/issues/719 https://github.com/Project-MONAI/MONAI/issues/606

**Comment by Nic-Ma** [comment]
Close this ticket as @wyli already implemented with PR #1087 .

Thanks.
