### ISSUE TITLE
RandHistogramShift dtype inconsistency

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1059]
**Describe the bug**
RandHistogramShift transform doesn't preserve the float32 precision

**To Reproduce**
```py
import numpy as np
from monai.transforms import RandHistogramShift

inputs = np.zeros((2, 2), dtype=np.float32)
result = RandHistogramShift(num_control_points=(5, 20), prob=1.0)(inputs)
print(inputs.dtype)  # float32
print(result.dtype)  # float64
```

**Expected behavior**
result type should be float32 if the input's is

**Environment (please complete the following information):**
MONAI version: 0.3.0rc3+0.g3f4e064.dirty
Python version: 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy version: 1.19.2
Pytorch version: 1.6.0

--
Thanks for reporting the issue @Can-Zhao!

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your finding.
I can update it to keep the same behavior with other float64/float32 transforms.

Thanks.
