### ISSUE TITLE
Transform on/off flag

### ISSUE THREAD

**Issue by ChenglongWang** [Project-MONAI/MONAI#1081]
**Is your feature request related to a problem? Please describe.**
Currently, when I need some conditional transforms in the workflow, I use a dummy transform (Lambda) to turn it on and off. I'm wondering is there any elegant way to make it work. Ex. a on/off flag in the arguments.

Here gives my current solution,
```
if crop_size is None:
    # No cropping
    cropper = Lambdad(keys=["image", "label"], func=lambda x : x)
else:
    cropper = RandSpatialCropd(keys=["image", "label"], roi_size=crop_size, random_size=False)

transforms = Compose([
            LoadNumpyd(keys=["image","label"]),
            AddChanneld(keys=["image", "label"]),
            cropper,
            ToTensord(keys=["image", "label"])
            ])
```

**Describe the solution you'd like**
Add some flag in the transform function. May be it can be derived from Transform class.
```
transforms = Compose([
            LoadNumpyd(keys=["image","label"]),
            AddChanneld(keys=["image", "label"]),
            RandSpatialCropd(keys=["image", "label"], roi_size=crop_size, random_size=False, trigger=crop_size is not None),
            ToTensord(keys=["image", "label"])
            ])
```

**Additional context**

**Comment by ChenglongWang** [comment]
@wyli Thank your for you reply. 
I think my solution has more code reusability, ex:
```
if crop_size is None:
    cropper = Lambdad(keys=["image", "label"], func=lambda x : x)
else:
    cropper = RandSpatialCropd(keys=["image", "label"], roi_size=crop_size, random_size=False)

if phase == 'train':
    transforms = Compose([
            LoadNiftid(keys=["image","label"]),
            AddChanneld(keys=["image", "label"]),
            TransformForTrain(keys=["image","label"]),
            cropper,
            ToTensord(keys=["image", "label"])
    ])
elif phase == 'valid' or phase == 'test':
    transforms = Compose([
            LoadNiftid(keys=["image","label"]),
            AddChanneld(keys=["image", "label"]),
            cropper,
            ToTensord(keys=["image", "label"])
    ])
```
I think adding a on/off flag is still a better solution. Anyway, thank your for your kind help. If possible, I'd like submit a PR for this ticket.

**Comment by wyli** [comment]
sure, there's also an identity transform in monai: https://github.com/Project-MONAI/MONAI/blob/13e2e48c76b139a2b0cbc6187b54f2ff0e451245/monai/transforms/utility/dictionary.py#L46-L49

if we go for this solution there's a tiny overhead for every iteration during validation/test to run a transform that does almost nothing...otherwise it looks fine to me.

I'm closing this ticket for now, thanks @ChenglongWang!
