### ISSUE TITLE
Focal Loss

### ISSUE THREAD

**Issue by shrutishrestha** [Project-MONAI/MONAI#1082]
Can the focal loss be used for the segmentation task or is it only for the classification?

**Comment by shrutishrestha** [comment]
<img width="996" alt="Screen Shot 2020-10-01 at 12 11 08 PM" src="https://user-images.githubusercontent.com/33342277/94775293-43803c80-03df-11eb-860b-d54ab25fbbc6.png">
 error occured while performing segmentation with focal loss. 
Here predicted output shape is [1,1,256,256] and label is also [1,1,256,256]

**Comment by ericspod** [comment]
These device-side problems are not common, they come up when doing custom CUDA operations or using CUDA through other programs. Are you running something else other than this program? If you restart the program/notebook does it reoccur or does it take a few runs before this happens? What hardware are you running on? What's the output from `monai.config.print_config()`?

**Comment by wyli** [comment]
I just tested it with a quick script, I think it's because the contents in `label` are larger than the number of channels in `output`, to reproduce it:
```py
import torch

from monai.losses import FocalLoss

# device = "cpu"
device = "cuda"
output = torch.zeros((1, 1, 256, 256)).to(device=device)
label = torch.ones((1, 1, 256, 256)).to(device=device)
print(f"loss: {FocalLoss()(pred, target)}")
```

output:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-7184b1aba695> in <module>()
      5 # device = "cpu"
      6 device = "cuda"
----> 7 output = torch.zeros((1, 1, 256, 256)).to(device=device)
      8 label = torch.ones((1, 1, 256, 256)).to(device=device)
      9 print(f"loss: {FocalLoss()(pred, target)}")

RuntimeError: CUDA error: device-side assert triggered
```
the error message is slightly better on CPU:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-ca900a764c41> in <module>()
      7 output = torch.zeros((1, 1, 256, 256)).to(device=device)
      8 label = torch.ones((1, 1, 256, 256)).to(device=device)
----> 9 print(f"loss: {FocalLoss()(pred, target)}")

1 frames
/usr/local/lib/python3.6/dist-packages/monai/losses/focal_loss.py in forward(self, input, target)
    102         # Keep only log proba values of the ground truth class for each voxel.
    103         if target.shape[1] == 1:
--> 104             logpt = logpt.gather(1, t.long())  # N,C,H*W => N,1,H*W
    105             logpt = torch.squeeze(logpt, dim=1)  # N,1,H*W => N,H*W
    106 

RuntimeError: index 1 is out of bounds for dimension 1 with size 1
```

if you're doing binary segmentation, `output` should be `output = torch.zeros((1, 2, 256, 256)).to(device=device)` with two channels:
```py
import torch

from monai.losses import FocalLoss

device = "cpu"
# device = "cuda"
output = torch.zeros((1, 2, 256, 256)).to(device=device)
label = torch.ones((1, 1, 256, 256)).to(device=device)
print(f"loss: {FocalLoss()(output, label)}")
>>> loss: 0.1732870638370514
```

**Comment by shrutishrestha** [comment]
Ok then I should use softmax in the last layer of the network before sending it to the loss function right?

**Comment by wyli** [comment]
> Ok then I should use softmax in the last layer of the network before sending it to the loss function right?

no need for a softmax as the loss does it internally:
https://github.com/Project-MONAI/MONAI/blob/13e2e48c76b139a2b0cbc6187b54f2ff0e451245/monai/losses/focal_loss.py#L100-L101

I'll update the docstring and revise the interface
