### ISSUE TITLE
support of pretrained weights

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1089]
**Is your feature request related to a problem? Please describe.**
would be great to support init. from the pretrained models for `SENet` and `DenseNet` (when user specifies `spatial_dims`=2).

**Comment by Nic-Ma** [comment]
Thanks @wyli , sounds good a feature, similar to our AHNet.
Add @yiheng-wang-nv to help on this task.

Thanks.

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/1096
