### ISSUE TITLE
EfficientNets

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1090]
**Is your feature request related to a problem? Please describe.**
this ticket looks for implementation of the EficientNets
(the 2d instance could support initialisation from the pretrained)
e.g. https://github.com/rwightman/gen-efficientnet-pytorch

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Do you know where we can find some reference implementation for 3D EfficientNet?
Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Do you know where we can find some reference implementation for 3D EfficientNet?
> Thanks.

thanks Nic, i don't get your question, wouldn't implementing the 2d version with the factories bring in the 3d support automatically?
there's also a 3D impl. https://github.com/shijianjian/EfficientNet-PyTorch-3D looks interesting

**Comment by masadcv** [comment]
Hi @wyli, 
What kind of support you wish to have with EfficientNets? The original paper at: https://arxiv.org/pdf/1905.11946.pdf has EfficientNet-B0 to EfficientNet-B8 for ImageNet classification task.

**Comment by wyli** [comment]
Hi, thanks for your interest here, might be interesting to have two implementations: a basic one with a few fixed architectures (such as [this hard-coded](https://github.com/Project-MONAI/MONAI/blob/master/monai/networks/nets/basic_unet.py#L209-L231)) to support finetuning from the pre-trained weights; another one with flexible interfaces to support variable configurations (such as [dynamic unet with N blocks](https://github.com/Project-MONAI/MONAI/blob/master/monai/networks/nets/dynunet.py#L69)). @atbenmurray is also looking into the latter

**Comment by masadcv** [comment]
Many thanks @wyli, I can look into the basic ones if no one is already looking into it. It will take me sometime to extract and port relevant ones from https://github.com/rwightman/gen-efficientnet-pytorch . I am thinking of having at least the original proposed ones B0-B7 in the first pass.

**Comment by atbenmurray** [comment]
Yea, my main interest is in how one provides a generic approach performing efficientnet-style architecture search across diverse network architectures

**Comment by masadcv** [comment]
@atbenmurray many thanks! I have started looking into this. 
This repository may be of interest as it is more focused on EfficientNets: https://github.com/lukemelas/EfficientNet-PyTorch

**Comment by masadcv** [comment]
I have started a pull request that covers EfficientNetB0-B7 for spatial_dims \in [1, 2, 3]. It is WIP. The code is based on https://github.com/lukemelas/EfficientNet-PyTorch but extended/refactored to integrate with MONAI's factories.  Pretrained weights from https://github.com/lukemelas/EfficientNet-PyTorch can be used for 2D case.
