### ISSUE TITLE
Using own dataset to get spleen segmentations

### ISSUE THREAD

**Issue by Meddebma** [Project-MONAI/MONAI#1091]
I have been testing some of the interesting tutorials on Monai. They are all functioning as expected.
I am now trying to use some own CT data for some of these tutorials, for example the Spleen Segmentation tutorial, but I am encountering some errors which raises some questions:

I have a dataset of CT-Scans without labels. How can I get segmentations out of the spleen segmentation notebook and using the best metric model I already downloaded ?
Once the segmentations of my own data are done, can I export them as Nifti images? 

Thanks a lot

**Comment by Nic-Ma** [comment]
Hi @Meddebma ,

Thanks for your interest here.
I think you want to run inference on your dataset with pretrained model, right?
You can refer to this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_evaluation_dict.py
Just remove the logic of computing metrics as you don't have labels.

Thanks.
