### ISSUE TITLE
CI errors (not enough memory on the github windows runner?)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1094]
**Describe the bug**
`tests\test_ahnet.py` sometimes raises an out of memory error on github default windows cpu runner
for example https://github.com/Project-MONAI/MONAI/runs/1231403189?check_suite_focus=true#step:9:4886

**Comment by Nic-Ma** [comment]
Add @IsaacYangSLA as the expert for CI details.
Thanks.
