### ISSUE TITLE
Sliding window for multi label segmentation/classification

### ISSUE THREAD

**Issue by saruarlive** [Project-MONAI/MONAI#1103]
Hi, Nic-Ma et al,

Could you kindly explain how to use the Sliding window method for multi-label segmenation problem? What loss function/metric should I use in this regard. I have found a tutorial for that in the spleen segmenation notebook, but it is a binary segmenation problem. 

 What are the criteria for input image size, and ROI size for the Sliding window method? I have tried with different ROI size and image size. I have encountered errors. 

Could you kindly explain with examples using random tensors?

Looking forward to hearing from you.

**Comment by Nic-Ma** [comment]
Hi @saruarlive ,

Thanks for your interest here.
Please take a look at this tutorial:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/brats_segmentation_3d.ipynb
It's a multi-labels task based on Decathlon challenge Task01 dataset.

Thanks.

**Comment by saruarlive** [comment]
Dea Nic-Ma et al, thanks for your reply. I saw the notebook, and the sliding window method was not implemented there. Do you think, it will work there too since tensors are stacked for each label(class) as channels. For example, for 4 class problem (excluding background), the size of the label tensor becomes  (b, 4, h,w,d).  What sort of loss function/metric requires to apply the sliding window method in this regard.

**Comment by Nic-Ma** [comment]
Hi @saruarlive ,

Sorry for the delayed response, I missed this ticket before.
I didn't quite understand your question, I think the `SlidingWindow` is only applied for the `model.forward()` process to gethe predictions, not related to `loss` or `metrics`, right?

Thanks.

**Comment by saruarlive** [comment]
@ I had figured out my problem. Thanks for your reply. So you mean to say that it does not matter whether it is a multilabel or binary or multi-class segmentation problem, the sliding window inference will work well, right?

**Comment by Nic-Ma** [comment]
Yes, please feel free to open a ticket if you have any more questions.
Thanks.
