### ISSUE TITLE
Balanced batch of crops with(out) foreground pixels

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#1108]
Apologies if this feature already exists. I would like to implement a function like "RandCropByPosNegLabeld" taking a balanced set of crops (a) containing at 1 or more foreground pixels (e.g. from segmentation mask) and (b) only background pixels.
The goal is to classify crops from a Nifti volume. The current implementation isn't working for me as there is no guarantee that no foreground pixels are present in the image

**Comment by wyli** [comment]
thanks for the feature request, this looks like a special case of https://github.com/Project-MONAI/MONAI/issues/586

**Comment by Nic-Ma** [comment]
Close this ticket as we are tracking this request in #586 .

Thanks.
