### ISSUE TITLE
import in classification examples

### ISSUE THREAD

**Issue by fahmanali** [Project-MONAI/MONAI#1112]
when run : from monai.apps import download_and_extract
get error: ModuleNotFoundError: No module named 'monai.apps'

**Comment by Nic-Ma** [comment]
Hi @fahmanali ,

Thanks for your interest here.
Have you installed MONAI 0.3.0? Could you please help provide your software versions info?

Thanks.

**Comment by fahmanali** [comment]
OK. Thank you.
It was version 1. Pip don't install v3 directly.

في السبت، ١٧ أكتوبر، ٢٠٢٠ ١:٤٦ م Nic Ma <notifications@github.com> كتب:
