### ISSUE TITLE
Upgrade python version in Docker image

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1119]
**Is your feature request related to a problem? Please describe.**
The python version of our current docker image is slightly outdated at `3.6.10`.

**Describe the solution you'd like**
An updated python version would be good.

**Describe alternatives you've considered**
Our current docker image is based on nvidia's pytorch version `20.08-py3`. I updated this to their most recent tag `20.09-py3`, but unfortunately this uses the same version of python.

**Additional context**
If I need an updated version of python in my scripts, I manually update conda by reinstalling. This probably isn't the best way to do it, but here's my code in case it helps:
```
        conda install anaconda-clean -y
        anaconda-clean -y
        rm -rf ~/.conda ~/.jupyter /opt/conda || true
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        echo "879457af6a0bf5b34b48c12de31d4df0ee2f06a8e68768e5758c3293b2daf688 Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check --status
        bash ./Miniconda3-latest-Linux-x86_64.sh -p /opt/conda -b
        rm Miniconda3-latest-Linux-x86_64.sh
```

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

Could you please help answer this question? I think you are real expert on our environment.
Thanks.

**Comment by wyli** [comment]
I think the base docker image comes with various python packages and are only tested with the specific python version. modifying the python installation is quite risky...
