### ISSUE TITLE
drop pytorch 1.4 support

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1123]
**Is your feature request related to a problem? Please describe.**
this ticket is to propose to drop the pytorch 1.4 support, this will reduce the dev/CI/CD burdens and encourage the use of the newer pytorch features such as AMP

**Comment by Nic-Ma** [comment]
@wyli thanks for raising this ticket and your related PR.
AMP is still not supported in PyTorch 1.5 BTW.
