### ISSUE TITLE
sliding window inference for models that use info other than image

### ISSUE THREAD

**Issue by michalhg** [Project-MONAI/MONAI#1124]
the monai dataset class is able to use extra data other than the image and label. I want to use a network that incorporates an additional  vector as input (which is not the image itself). however, during the inference stage there is no option to add this input vector. it expects only an image type data in the form of NCWH.
please add this support for sliding_window_inference function.

**Comment by wyli** [comment]
hi @michalhg, not sure what exactly the use case is, but could we have a wrapper of the predictor to do it, something like:
```py
image_data, meta_data = # load_from_data_loader


def predictor(x):
    return my_model(x, meta_data)

output_image = SlidingWindowInferer(roi_size=...)(inputs=image_data, network=predictor)

```

**Comment by michalhg** [comment]
yes, sort of.. the predictor should be able to receive the input of the metadata as well, same as the model:
def predictor(x, meta_data):
    return my_model(x, meta_data)

**Comment by michalhg** [comment]
hi @wyli, the metadata is related to the image. could be for instance the age of a patient or the type of scan. this should go in the batch data same as the image to be deployed. this is why it should be implemented **within** the sliding window inferer.

**Comment by wyli** [comment]
I think the recent PR https://github.com/Project-MONAI/MONAI/pull/1257 fixes this issue. but please feel free to reopen it
