### ISSUE TITLE
runtests takes a long time

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1137]
**Describe the bug**
In our PR template, we ask the submitter to run `./runtests.sh --codeformat --coverage`. Running this on the DGX takes >1h. I normally give up along the way, which makes me think that it's not reasonable to ask this for each and every PR. Could we used an accelerated version?

**Comment by wyli** [comment]
`./runtests.sh --quick` skips some integration tests and is much faster. I agree that for non-breaking changes we just need to run the quick tests. I'll update the contributing guide.

**Comment by rijobro** [comment]
Thanks!
