### ISSUE TITLE
Enhance the parameters of NormalizeIntensity transform

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1142]
**Is your feature request related to a problem? Please describe.**
Currently, `NormalizeIntensity` transform only accepts `subtrahend` and `divisor` as numpy array and have same shape as the input data. But in most of the cases, we only need to set different 1 value for the whole image, or set different values for every channel, no need to set exact value for every voxel.

**Describe the solution you'd like**
Enhance the parameters to support shape: `1`, `N` and support python array.

**Comment by wyli** [comment]
Hi @Nic-Ma , it seems what you described here is supported by our current implementation:
```
NormalizeIntensity(subtrahend=1.5, divisor=0.5)(np.ones((1, 2, 2)))
NormalizeIntensity(subtrahend=[1.5], divisor=[0.5], channel_wise=True)(np.ones((1, 2, 2)))
NormalizeIntensity(subtrahend=[1.5, 2], divisor=[0.5, 3], channel_wise=True)(np.ones((2, 2, 2)))
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I saw your PR https://github.com/Project-MONAI/MONAI/pull/1093 fixed this issue.
My local code is not updated to the latest.
Thanks for your PR by the way.
