### ISSUE TITLE
compatibility with pytorch 1.7

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1149]
**Is your feature request related to a problem? Please describe.**
pytorch 1.7 is available, there're some compatibility issues such as https://github.com/Project-MONAI/MONAI/runs/1315919388#step:8:15470

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this topic, let me try to figure out this particular issue.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Thanks for raising this topic, let me try to figure out this particular issue.

I partly fix this issues here: https://github.com/Project-MONAI/MONAI/commits/1149-torch-1-7
the corresponding full test results are here: https://github.com/Project-MONAI/MONAI/runs/1316826365
could you please continue working from that branch

**Comment by Nic-Ma** [comment]
sounds good.

**Comment by rijobro** [comment]
For what it's worth, running `./runtests.sh --quick` with pytorch 1.7 locally, I get a few more errors as well. See [attached](https://github.com/Project-MONAI/MONAI/files/5452052/error.txt) file. Although I haven't checked if all errors are specifically related to pytorch1.7.

**Comment by wyli** [comment]
> For what it's worth, running `./runtests.sh --quick` with pytorch 1.7 locally, I get a few more errors as well. See [attached](https://github.com/Project-MONAI/MONAI/files/5452052/error.txt) file. Although I haven't checked if all errors are specifically related to pytorch1.7.

those are all fixed in https://github.com/Project-MONAI/MONAI/commits/1149-torch-1-7

there are some additional issues 
- on windows for the multiprocess data loading
- some reproducibility issues related to the deterministic seeds
- linux cpu tests took too long (60min+)

**Comment by rijobro** [comment]
Great thanks. Perhaps in the meantime, we should modify [requirements.txt](https://github.com/Project-MONAI/MONAI/blob/master/requirements.txt) from `torch>=1.5` to `torch>=1.5,<1.7`. Otherwise, users will get the problematic 1.7 by default (I do at least).

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please submit all your fix as a PR? I didn't which issue you already fixed and which is not.
Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Could you please submit all your fix as a PR? I didn't which issue you already fixed and which is not.
> Thanks.

you can find the diff here: https://github.com/Project-MONAI/MONAI/compare/1149-torch-1-7
PR will trigger too many github notifications I was trying to avoid that.

**Comment by dzenanz** [comment]
> Great thanks. Perhaps in the meantime, we should modify [requirements.txt](https://github.com/Project-MONAI/MONAI/blob/master/requirements.txt) from `torch>=1.5` to `torch>=1.5,<1.7`. Otherwise, users will get the problematic 1.7 by default (I do at least).

I just got into this situation. I will need to downgrade pytorch.

**Comment by rijobro** [comment]
@dzenanz 
We've merged the temporary fix here: https://github.com/Project-MONAI/MONAI/pull/1151. If you already have pytorch 1.7, you should be able to pip uninstall it and then re-install the correct versions via the `requirements.txt` files.
