### ISSUE TITLE
RandZoomd crashes my notebook without a stack trace

### ISSUE THREAD

**Issue by catskillsresearch** [Project-MONAI/MONAI#1150]
**Describe the bug**
When I apply the commented-out `RandZoomd` transformation in my data load, which mirrors the Spleen 3D segmentation notebook but a slightly different dataset, it crashes the notebook without a stack trace.  Removing the transform allows the load to complete:

```
def transformations():
    train_transforms = Compose(
        [
            LoadNumpyd(keys=["image", "label"]),
            AddChanneld(keys=["image", "label"]),
            RandGaussianNoised(keys=["image"]),
            RandRotated(keys=["image", "label"], range_x=two_degrees, range_y=two_degrees, range_z=two_degrees),
#            RandZoomd(keys=["image", "label"]),
            RandCropByPosNegLabeld(
                keys=["image", "label"],
                label_key="label",
                spatial_size=(20,20,20),
                pos=8,
                neg=1,
                num_samples=4,
                image_key="image",
                image_threshold=0,
            ),
            ToTensord(keys=["image", "label"]),
        ]
    )
    val_transforms = Compose(
        [
            LoadNumpyd(keys=["image", "label"]),
            AddChanneld(keys=["image", "label"]),
            ToTensord(keys=["image", "label"]),
        ]
    )
    return train_transforms, val_transforms
```

**Expected behavior**
If it's going to fail, it shouldn't crash the notebook, it should explain to me what I'm doing wrong.

**Environment (please complete the following information; e.g. using `sh runtests.sh -v`):**
MONAI version: 0.3.0
Python version: 3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]
OS version: Linux (5.4.0-52-generic), Ubuntu 20.04LTS
Numpy version: 1.19.1
Pytorch version: 1.6.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False

Optional dependencies:
Pytorch Ignite version: 0.4.2
Nibabel version: 3.2.0
scikit-image version: 0.16.2
Pillow version: 7.2.0
Tensorboard version: 2.2.0
gdown version: 3.12.2
TorchVision version: 0.7.0
ITK version: 5.1.1
tqdm version: 4.50.2

**Comment by Nic-Ma** [comment]
Hi @catskillsresearch ,

Thanks for your interest here and experiments with MONAI.
Could you please help add `DataStatsd` transform before and after `RandZoomd` to help show some information?
I think we need to figure out where it really crashed first.
If you can play with MONAI source code and add some log, that would be quite helpful, just git clone the master branch and `pip install -e .` at the root folder.

Thanks.

**Comment by catskillsresearch** [comment]
Hi @Nic-Ma, here is a self-contained example.  It doesn't crash my notebook on it's own, so I will try again and see if the problem goes away.  If it doesn't I'll come back with a revision:

```
d0={'image': torch.rand(1086,322,20), 'label': torch.rand(1086,322,20)}
d1=AddChanneld(keys=["image", "label"])(d0)
d2=RandGaussianNoised(keys=["image"])(d1)
d3=RandRotated(keys=["image", "label"], range_x=0.0349, range_y=0.0349, range_z=two_degrees)(d2)
d4=RandZoomd(keys=["image", "label"])(d3)
```
**Question**:  Is there a way to get these transforms to run on the GPU during training?  Using the training loop presented in the tutorial, these happen on the CPU and I need to raise my num_workers up to accomodate.  In fact, using these transforms, very little training time is spent on the GPU.  Most training time is spent on the GPU.  I don't see in principle why the transforms can't just be added to the neural network's compute stack.  I could do that directly, but it would be nicer if moving it to the device was more transparent.  Is there anything about these transforms that is not inherently parallelizable?  These all seem like classic GPU operations.

**Comment by Nic-Ma** [comment]
Hi @catskillsresearch ,

Sound good. And some of the transforms can run on GPU, you can take a look at:
https://github.com/Project-MONAI/tutorials/blob/master/acceleration/transform_speed.ipynb

Thanks.

**Comment by catskillsresearch** [comment]
@Nic-Ma why don't all of the transforms run on GPU?  Most of the examples presented are a stack followed by `ToTensord`.  Most of the transforms are missing the `device=` and  `as_tensor_output=True` arguments.  (Also the docs are ambiguous about whether `True` means "as a tensor" or "as NumPy".)  It seems it would be cleaner to have these two arguments on the `LoadNumPyd` and `LoadNiftid` transforms to get the input into Tensor and on GPU right away, and for all of the remaining transforms to silently operate in GPU and Tensor without needing to say so if they are presented with a tensor on a GPU.  Does this make sense?
