### ISSUE TITLE
randzoom to partly keep the aspect ratio

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1154]
**Is your feature request related to a problem? Please describe.**
currently random zoom supports either different random zoom factors for each dimension or the same factor for all dimensions.
would be great to support the use same random factor for some of the dimensions

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help provide some expected example for this feature request?
I don't quite understand.

Thanks.

**Comment by wyli** [comment]
yes for 3d input, currently we could have either 3 elements or 1 element for `self._zoom` here:
https://github.com/Project-MONAI/MONAI/blob/99f7a439020bac0c70de1a5096bb24aceeaf4ae5/monai/transforms/spatial/array.py#L795-L798

Dong was looking for an option for 2 elements `self._zoom` for 3d, for example, the x-y axes always share the same random factor, but the z axis uses a separate random zoom factor. maybe it's already partly implemented because we have https://github.com/Project-MONAI/MONAI/blob/99f7a439020bac0c70de1a5096bb24aceeaf4ae5/monai/transforms/spatial/array.py#L518
