### ISSUE TITLE
list of todos

### ISSUE THREAD

**Issue by aliechoes** [Project-MONAI/MONAI#1156]
Hi 

I would like to contribute to MONAI. I am wondering if there is any list of open todos which can be implemented?

Cheers

**Comment by wyli** [comment]
Welcome!  tickets labelled 'contribution wanted' and 'feature request' generally need help
- https://github.com/Project-MONAI/MONAI/labels/Contribution%20wanted 
- https://github.com/Project-MONAI/MONAI/labels/Feature%20request

**Comment by aliechoes** [comment]
thanks. Also wondering, in case I developed some stuff which are not part of the feature requests, would it be still possible to send the pull request? I am mostly asking this to know more about the monai general policy

**Comment by wyli** [comment]
> thanks. Also wondering, in case I developed some stuff which are not part of the feature requests, would it be still possible to send the pull request? I am mostly asking this to know more about the monai general policy

Sure, in that case, would be great to create a new ticket first, so that we have enough context for some discussions and tracking the progress

**Comment by aliechoes** [comment]
Awesome! Thanks for the response. I am working on my PhD project and no matter what I am implementing my work on MONAI. I think it would be a nice addition to the currently existing work anyway.

**Comment by wyli** [comment]
> Awesome! Thanks for the response. I am working on my PhD project and no matter what I am implementing my work on MONAI. I think it would be a nice addition to the currently existing work anyway.

thanks! I'm closing this ticket for now
