### ISSUE TITLE
How do I cite this project?

### ISSUE THREAD

**Issue by sumanyumuku98** [Project-MONAI/MONAI#1166]

**Comment by aylward** [comment]
This is a great question!   I've forwarded it to the Community Working Group.    As soon as we have an answer, we will post it here.   In the meantime, referencing the MONAI.IO website is probably best.   Thanks for thinking of this!

**Comment by sumanyumuku98** [comment]
Great! Will reference the website for the time being.

**Comment by wyli** [comment]
the DOI is available: https://doi.org/10.5281/zenodo.4323058

(need to add it to the main readme)

**The MONAI Consortium. (2020). Project MONAI. Zenodo. [http://doi.org/10.5281/zenodo.4323059](http://doi.org/10.5281/zenodo.4323059)**

**Comment by wyli** [comment]
reopening -- need to add this infor to the readme file/webpage

**Comment by aylward** [comment]
I think this should be updated to cite the publication on arXiv.  We can also cite the code, but I think the article should also be featured.  @mjorgecardoso ?

**Comment by wyli** [comment]
Hi @aylward the citation file has been updated https://github.com/Project-MONAI/MONAI/blob/86c7ecdc1225529a379e2cd58c23fe53aa79b0d0/CITATION.cff#L20-L22

the github ui now shows the paper info:
![Screenshot 2023-01-25 at 14 08 29](https://user-images.githubusercontent.com/831580/214585024-caf9f7b1-debb-4a81-8f5b-f7dab5fe9547.png)
