### ISSUE TITLE
Error with compute_hausdorff_distance

### ISSUE THREAD

**Issue by Dale-Black** [Project-MONAI/MONAI#1168]
**Describe the bug**
Unable to import `compute_hausdorff_distance` while using monai==0.3.0. When I git clone and import `compute_hausdorff_distance` that way I am still unable to use `compute_hausdorff_distance` due to size mismatch and/or nonzero entries

**To Reproduce**
1. Go to https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d_lightning.ipynb
2. Reimplement the exact tutorial while adding in the `compute_hausdorff_distance` as a validation metric

**Expected behavior**
I should be able to monitor the hausdorff distance along with the dice score while training

**Screenshots**
<img width="602" alt="image" src="https://user-images.githubusercontent.com/62632960/97795097-542ef880-1bbf-11eb-980b-2e330d1378af.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/62632960/97795104-6315ab00-1bbf-11eb-87f5-fdfcab12778e.png">
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/62632960/97795082-3cf00b00-1bbf-11eb-9cc7-4fc60eb5f722.png">

**Environment (please complete the following information; e.g. using `sh runtests.sh -v`):**
 - MONAI version: 0.3.0
 - Python version: 3.8.0 (default, Jun  6 2020, 14:44:32)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
 - OS version: Linux (3.10.0-1127.19.1.el7.x86_64)
 - CUDA/cuDNN version
 - GPU models and configuration

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Could you please help take look at this question as you developed the `compute_hausdorff_distance` and expert on that?
Thanks in advance.

**Comment by Dale-Black** [comment]
So the problem is that the `val_outputs` is of size=[1, 2, 233, 209, 101] wheres the `val_labels` is of size=[1, 1, 233, 209, 101]. Any idea what might have gone wrong in this process?

**Comment by wyli** [comment]
thanks for the feedback, you can also add a `torch.argmax` to the output, something like:
```py
hd = compute_hausdorff(seg_pred=torch.argmax(outputs, axis=1, keepdims=True), seg_gt=labels...)
```
