### ISSUE TITLE
Guidance for preparing own data

### ISSUE THREAD

**Issue by jnc13** [Project-MONAI/MONAI#1183]
Hey,
I'm not a coding-whizz so thanks for making an approachable implementation.
I've begun attempting 3D segmentation with my own data by following the "Spleen 3D segmentation with MONAI" tutorial but believe I'm running into an issue with how I have prepared my own data.

Could you please provide some clarification/tutorial/code for how to prepare data: images and labels?

Personally I'm getting “ValueError: given numpy array has byte order different from the native byte order. Conversion between byte orders is currently not supported.”
From what I've read this could be because my labels, prepared with itk-SNAP, are not little-endian but am hitting a wall for how to progress! I think my unlabelled images (converted from DICOM to nii.gz) seem to be fine since I can import them as both the "image" and "label" without errors. Any help would be much appreciated.

Thanks,
Jeff.

**Comment by Nic-Ma** [comment]
Hi @jnc13 ,

Thanks for your interest and good experiment with your own data.
Could you please help share your script that converts your label data?
Maybe @thewtex from ITK team could help us and take a quick check?

Thanks in advance.

**Comment by jnc13** [comment]
Hi @Nic-Ma ,
I'm very pleased to say that in fact that taking another look at it in preparation for my reply it is now working! I managed to cut out a preprocessing step and the streamlined approach is now working great. So no need for any further help and I'll close this. Thanks again.
Jeff.
