### ISSUE TITLE
PyTorch 1.6 is not optimized for docker 20.08

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1184]
**Describe the bug**
In order to avoid PyTorch 1.7 CI test errors, we temporarily forced PyTorch version to >=1.5 and < 1.7, it will uninstall the optimized PyTorch in docker 20.08 and install 1.6.0 instead.
According to @IsaacYangSLA 's training test, the training speed is 2x times slower in latest MONAI docker(reinstall 1.6) because the original torch in the docker was optimized by NVIDIA team.

Need to restore the torch of PyTorch 20.08 docker as the base of MONAI docker.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help restore the Dockerfile to use the original torch in docker 20.08?
This can be very important for us to compare the training speed of MONAI with other internal projects.

Thanks in advance.

**Comment by wyli** [comment]
sure I'm working on this. We do need to address https://github.com/Project-MONAI/MONAI/issues/852 to avoid this type of error again.

**Comment by Nic-Ma** [comment]
Thanks @wyli , and yes, we also have ticket https://github.com/Project-MONAI/MONAI/issues/927 for execution time test.
