### ISSUE TITLE
Unify the rotate angle in transforms

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1185]
**Is your feature request related to a problem? Please describe.**
Currently, `Rotate`, `RandRotate`, etc. use the degree to set rotate angle, but `RandAffine`, `Rand3DElastic`, etc. use radian, need to unify them for better user experience.

**Comment by Nic-Ma** [comment]
Hi @wyli and @ericspod ,

I want to unify them in `radian`, if you guys agree, I will submit a PR as soon as possible.
We are developing many training examples based on MONAI, better to finalize APIs ASAP.

Thanks.

**Comment by ericspod** [comment]
Most calculations are done in radians, that's really the default I've seen everywhere in libraries like Numpy. Affine rotation matrices are always going to be in radians as well. In config files we have to specify an odd looking float value but I think it's clear when it's not an integer it's radians.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

OK, that looks reasonable to me.
@wyli do you have any other concern? If you are OK, I will make a quick PR for this thing and update related examples and tutorials.

Thanks.

**Comment by wyli** [comment]
sure I think we can unify to radians
