### ISSUE TITLE
Error using spatial size

### ISSUE THREAD

**Issue by shrutishrestha** [Project-MONAI/MONAI#1196]
I do not understand this error. 
<img width="1291" alt="Screen Shot 2020-11-06 at 9 55 16 AM" src="https://user-images.githubusercontent.com/33342277/98325281-8785e300-2016-11eb-9e36-19fb8dcabd22.png">
    
I used the transforamtion as below:
val_transform = monai.transforms.Compose(
    [
        LoadPNGd(keys = ["image","label"]),
        AsChannelFirstd(keys = ["image","label"], channel_dim = -1), 
        Lambdad(keys=['label'], func=lambda x: x[0:1]*0.2125 + x[1:2]*0.7154 + x[2:3]*0.0721),
        Resized(["image","label"],spatial_size=(256,256)),
        ScaleIntensityd(keys = ["image","label"], minv=0.0, maxv=1.0),
        NormalizeIntensityd(keys=["image"], subtrahend=mean, divisor=std),
        ToTensord(keys = ["image","label"])
    ]
    )

**Comment by JavierBerna** [comment]
Same problem using the `Resized ` function

**Comment by wyli** [comment]
thanks this is a compatibility issue with pytorch1.7, we are working on that. for now please downgrade to use pytorch 1.6. cc @Nic-Ma
