### ISSUE TITLE
Efficient, differentialble bilateral filter

### ISSUE THREAD

**Issue by charliebudd** [Project-MONAI/MONAI#1198]
**Is your feature request related to a problem? Please describe.**
This would be a useful tool to have in the box, both on its own or part of a larger algorithm such as #315

similar issue for more context... 
https://github.com/kornia/kornia/issues/702

**Describe the solution you'd like**
Would be nice to have an implementation which can operate on arbitrary spatial dimensions and channels. 
Due to the high computational load I think dropping down to c++ and cuda could be worth the extra work.

**Comment by faebstn96** [comment]
Thanks @charliebudd  for implementing this layer! Does your implementation also offer a way to backpropagate a loss into the spatial and range (color) parameters sigma? Or do you have a hint how to implement that?
I very much appreciate your help.

**Comment by charliebudd** [comment]
Hi there, the implementation alows for backpropergation of losses into the input tensor, however learning the parameters has not yet been implemented. Feel free to open up a feature request as it is certainly something we should be targeting.

**Comment by faebstn96** [comment]
Thanks for your very quick reply @charliebudd !
