### ISSUE TITLE
Integration test failed but report passed

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1204]
**Describe the bug**
I found an issue in our CI test env, the integration test failed in the log but the final result is "passed".
Take the latest PR for example:
https://github.com/Project-MONAI/MONAI/runs/1368333959#step:7:10824

Thanks.

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA and @wyli ,

I think this is a critical bug in the CI env, could you please help take a look?
Thanks.

**Comment by wyli** [comment]
hi Nic, please don't assign this type of ticket to me without any discussions beforehand.

**Comment by wyli** [comment]
looks like the tests/runner.py is not returning a proper exit code cc @rijobro

**Comment by rijobro** [comment]
Sorry about this, certainly looks my fault.

**Comment by Nic-Ma** [comment]
> Sorry about this, certainly looks my fault.

No problem, could you please hrlp submit a quick PR to fix it?
Don't worry about the CI error about DiceMetric, I fixed in another PR.

Thanks.
