### ISSUE TITLE
CI/CD pull from dockerhub reaches the rate limit

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1209]
**Is your feature request related to a problem? Please describe.**
"/usr/bin/docker pull projectmonai/monai:latest
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"

https://github.com/Project-MONAI/MONAI/runs/1375688986?check_suite_focus=true#step:2:17

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/fcd72ea201e9599be23114023604c4653e80fc56/.github/workflows/setupapp.yml#L137-L138

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA and @YuanTingHsieh ,

Could you please help take a look?
Thanks.
