### ISSUE TITLE
Investigate refactor of setup.py to use torches helper module

### ISSUE THREAD

**Issue by charliebudd** [Project-MONAI/MONAI#1215]
Torch provides a helper module "torch.utils.cpp_extention" which could be used to simplify our build scripting and increase maintainability. 

We should be cautious about backwards compatability with torch 1.5 which we still support.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I remember we used `cpp_extention` but you dropped it due to some compatible reason.
Could you please help share more info about it? I don't remember that clearly.

Thanks.

**Comment by wyli** [comment]
I think the goal here is to further simplify the build logic @Nic-Ma, as we dropped pytorch 1.4, we could now assume the improved version of cpp_extention

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/1320, please reopen if needed
