### ISSUE TITLE
RESUME TRAINING on COVID 19 segmentation baseline model

### ISSUE THREAD

**Issue by massimilianoporzio** [Project-MONAI/MONAI#1216]
I noticed the model have a ChepointSaver to store the best model during the training.
Is it possible to RESUME from the last checkpoint in order to do the training in multi-steps?

**Comment by wyli** [comment]
yes, you can add a CheckpointLoader:
```py
    train_handlers = [
        CheckpointLoader(load_path="runsv2/net_key_metric=0.5819.pt", load_dict={"net": net}),
        ValidationHandler(validator=evaluator, interval=1, epoch_level=True),
        StatsHandler(tag_name="train_loss", output_transform=lambda x: x["loss"]),
    ]
```
there're more examples in the tutorial repo: https://github.com/Project-MONAI/tutorials/search?q=CheckpointLoader

**Comment by massimilianoporzio** [comment]
Thanks!
I will try

Il giorno mar 10 nov 2020 alle ore 21:57 Wenqi Li <notifications@github.com>
ha scritto:

**Comment by wyli** [comment]
this is also related to https://github.com/Project-MONAI/MONAI/issues/1180, any further comments about the usages? @Nic-Ma @ericspod @vfdev-5 thanks!

**Comment by vfdev-5** [comment]
@wyli, if we would like to resume the training, we have to store in addition the states of the optimizer(s), lr_scheduler(s), engine and other stateful objects.

In Ignite we suggest to save checkpoints (of model/optimizer/lr_scheduler/trainer) periodically (e.g. every 1000 iterations) and show examples how to resume from loaded checkpoint:
- [how to save](https://github.com/pytorch/ignite/blob/44f354e5b3fc234432567eb3448f00a1c7010504/examples/contrib/cifar10/main.py#L322)
- [how to restore](https://github.com/pytorch/ignite/blob/44f354e5b3fc234432567eb3448f00a1c7010504/examples/contrib/cifar10/main.py#L340)

Hope this helps.

**Comment by massimilianoporzio** [comment]
> yes, you can add a CheckpointLoader:
> 
> ```python
>     train_handlers = [
>         CheckpointLoader(load_path="runsv2/net_key_metric=0.5819.pt", load_dict={"net": net}),
>         ValidationHandler(validator=evaluator, interval=1, epoch_level=True),
>         StatsHandler(tag_name="train_loss", output_transform=lambda x: x["loss"]),
>     ]
> ```
> 
> there're more examples in the tutorial repo: https://github.com/Project-MONAI/tutorials/search?q=CheckpointLoader

Please can you tell me if using a saver with only the net saved in the dict will suffice...or to resume the training I have to save also the optimizer?
