### ISSUE TITLE
comparing numpy arrays in the normalize intensity test

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1225]
**Describe the bug**
log is at 
https://github.com/Project-MONAI/MONAI/pull/1200/checks?check_run_id=1389793036#step:9:7090

```
======================================================================
FAIL: test_default (tests.test_normalize_intensity.TestNormalizeIntensity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/MONAI/MONAI/tests/test_normalize_intensity.py", line 63, in test_default
    np.testing.assert_allclose(normalized, expected, rtol=1e-6)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=0

Mismatched elements: 568 / 8192 (6.93%)
Max absolute difference: 0.
Max relative difference: 0.
 x: array([[[[-0.714935, -0.714935, -0.714935, ..., -0.714935, -0.714935,
          -0.714935],
         [-0.714935, -0.714935, -0.714935, ..., -0.714935, -0.714935,...
 y: array([[[[-0.714935, -0.714935, -0.714935, ..., -0.714935, -0.714935,
          -0.714935],
         [-0.714935, -0.714935, -0.714935, ..., -0.714935, -0.714935,...

----------------------------------------------------------------------
```
mismatch with a max difference `0.` doesn't make sense. this needs more investigations

**To Reproduce**
the error appears randomly I couldn't find a reliable way to reproduce it.
but it often happens on the ubuntu tests.

**Expected behavior**
no test failure, as the other unit tests and other platforms do

**Environment (please complete the following information; e.g. using `sh runtests.sh -v`):**
please download

**Additional context**
full log:
[test_log_ubuntu.log](https://github.com/Project-MONAI/MONAI/files/5531302/test_log_ubuntu.log)

cc @IsaacYangSLA @YuanTingHsieh @behxyz @yanchengnv

**Comment by behxyz** [comment]
I haven't been able to reproduce this error yet via running the test for over a thousand times.
However, looking at the source code of `numpy`, "Max relative difference: 0." can be expectable in some situation where the desired output is zero since they are being ignored in calculation of `max_rel_error`. On the other hand, I have not been able to find any logic that can reproduce zero absolute error while there is a difference.

@wyli, if you encounter another example of this, please post the log here. I'll dig more into this.

**Comment by wyli** [comment]
thanks @behxyz, this happens once in a while, I'll post more info here if I see it again.

**Comment by wyli** [comment]
couldn't replicate this I'm closing the issue

**Comment by charliebudd** [comment]
potentially related? test ran fine before and after this run...
https://github.com/Project-MONAI/MONAI/pull/1375/checks?check_run_id=1576310468
