### ISSUE TITLE
RuntimeError("affine matrix of all images should be same.")

### ISSUE THREAD

**Issue by anneserious** [Project-MONAI/MONAI#1231]
When loading multiple (DICOM)- images using LoadImage(), this error occurs. MONAI ensures that all images have the same affine matrix. Why?
When loading a sequence of DICOM images, I would not expect them to have the same affine matrix?
Maybe someone can clarify this for me. Thanks!

**Comment by Nic-Ma** [comment]
Hi @anneserious ,

Thanks for using MONAI in your projects.
If you load a list of DICOM images as a batch data for training, you should call `LoadImage` to load them one by one based on PyTorch Dataset.
If calling `LoadImage` to load a list of images, it supposes to load these images and concat them together as 1 multi-channels image, so it expects all the images have the same `affine`.

Thanks.

**Comment by anneserious** [comment]
Hi Nic,

thank you for your reply. I would indeed like all images to be concatenated
in the channel dimenson, since they belong to the same patient. Can this be
achieved?

Thanks and kind regards
Anne


Nic Ma <notifications@github.com> schrieb am Sa., 14. Nov. 2020, 15:07:

**Comment by Nic-Ma** [comment]
Hi @anneserious ,

Do you mean all the images are from 1 patient and for example, they are 1 series of 2D images for 1 3D image?
If that, you can pass the `directory` path to `LoadImage`,refer to this:
https://github.com/Project-MONAI/MONAI/blob/master/monai/data/image_reader.py#L130

Thanks.

**Comment by anneserious** [comment]
Yes. Thanks a lot!

Am So., 15. Nov. 2020 um 10:58 Uhr schrieb Nic Ma <notifications@github.com
