### ISSUE TITLE
How to use TensorBoard?

### ISSUE THREAD

**Issue by Ordgod** [Project-MONAI/MONAI#1233]
I found that monai wraped training via `monai.engines.SupervisedTrainer`. So what should I do if I want to use tensorboard to monitor my training progress?

**Comment by Nic-Ma** [comment]
Hi @Ordgod ,

Thanks for your interest here.
You can refer to this example for how to use the `TensorboardStatsHandler` or `TensorboardImageHandler`:
https://github.com/Project-MONAI/tutorials/blob/master/modules/engines/unet_training_dict.py

Thanks.
