### ISSUE TITLE
Add TorchScript support for DynUNet

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1245]
**Is your feature request related to a problem? Please describe.**
The DynUNet is not currently compatible because it relies on iteration through lists of modules or the ListModule class. These are not currently compatible with Torchscript so a different architecture for this class is needed. It's possible to inherit from the existing UNet which is structured differently for this reason, however Torchscript does also have issues with the super keyword so a little more design thought is needed to account for the variation in the DynUNet.forward method.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Have you got any proposal or plan for this ticket?
Thanks.

**Comment by ericspod** [comment]
I'm working on this right now.
