### ISSUE TITLE
ConfusionMatrix, ROCAUC: TypeError: attach() missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by anneserious** [Project-MONAI/MONAI#1251]
I tried to use the ConfusionMatrix Handler in a SupervisedEvaluator and get above error message. Same for ROCAUC.
I tried to call both handlers without any arguments. 
Am I using them wrong? 

Thanks and kind regards
Anne

**Comment by Nic-Ma** [comment]
Hi @anneserious ,

Thanks for your interest here.
Could you please help share your test program then let's see whether something is wrong?

Thanks.

**Comment by anneserious** [comment]
Hi Nic, 

this is where the error occurs:


```
validator = SupervisedEvaluator(
            device=device,
            val_data_loader=val_loader,
            network=model,
             prepare_batch=lambda x:  [x[0],x[1].float().unsqueeze(1)],
             val_handlers=[ConfusionMatrix()]

     )
```

For comparison,

```
validator = SupervisedEvaluator(
            device=device,
            val_data_loader=val_loader,
            network=model,
             prepare_batch=lambda x:  [x[0],x[1].float().unsqueeze(1)],
             val_handlers=[StatsHandler()]

     )
```
works fine.

Thanks!

**Comment by Nic-Ma** [comment]
OK, I see your problem.
Please update to put the `ConfusionMatrix` metric on `key_train_metric`, refer to:
https://github.com/Project-MONAI/tutorials/blob/master/modules/engines/unet_training_dict.py

Thanks.
