### ISSUE TITLE
persistent dataset to cache first N transforms

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1254]
**Is your feature request related to a problem? Please describe.**
currently the persistent dataset caches the outcome up to the first randomised transform,
would be great to have a more flexible option to cache the first N transforms.

this is useful when we want to fix some of the non-randomised transforms and tune the hyperparameters of the others.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

interest feature, will try to add this support later.
Thanks.
