### ISSUE TITLE
Residual Units question

### ISSUE THREAD

**Issue by kissievendor** [Project-MONAI/MONAI#1258]
I don't completely understand the Residual Units in the UNet. 

In my understanding, the Residual Units are used in place of Skip Connections. 
My network works fine without the Residual Units. But my question is, how do I report the network architecture without the Residual Units? 

Or do the Residual Units serve another purpose? 

Also... Without the Residual Units, the network seems to do only one convolution per layers. 
(See comment below)

Thank you so much!

Best,
Kirsten

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I thin this is a FAQ, could you please help share some info?
Thanks in advance.

**Comment by kissievendor** [comment]
Related to this question I think: 
How it is that the number of parameters is so low in this network?
One would think that Strided convolution would add to parameters in contrast with maxpooling.

**Comment by ericspod** [comment]
Residual units are used to define the layers of the encode and decode path of the network, skip connects are still present and are not substituted in any way. The classical UNet implements each layer as a sequence of convolutions followed by maxpooling in the encode side, and upsampling followed by convolutions in the decode side. With out network with `num_res_units` set to some value great than 0 the encode layers are residual units of however many convolutions `num_res_units` is set to with the first having the given stride (2 in your case). In the decode side the convolution is transposed so the upsampling is done without adding new parameters since it replaces what would otherwise be a convolution. [Here](https://arxiv.org/pdf/2008.13718.pdf) a very similar network is used with 2 residual convolutions and is illustrated in Figure 1.

**Comment by kissievendor** [comment]
> Residual units are used to define the layers of the encode and decode path of the network, skip connects are still present and are not substituted in any way. The classical UNet implements each layer as a sequence of convolutions followed by maxpooling in the encode side, and upsampling followed by convolutions in the decode side. With out network with `num_res_units` set to some value great than 0 the encode layers are residual units of however many convolutions `num_res_units` is set to with the first having the given stride (2 in your case). In the decode side the convolution is transposed so the upsampling is done without adding new parameters since it replaces what would otherwise be a convolution. [Here](https://arxiv.org/pdf/2008.13718.pdf) a very similar network is used with 2 residual convolutions and is illustrated in Figure 1. Also I answered a similar question [here](https://github.com/Project-MONAI/MONAI/issues/464#issuecomment-636980086).

Thank you for your quick and clear response.

But as you can see from the summary, when num_res_units is 0, the network only has one convolution before the number of features is doubled. Whereas with the residual units there are two plus that unit.
And also other networks that work with strided convolutions (e.g. Vnet) there are succesive convolutions.

So is this intentional / does it still constitute as a 3D-Unet?

**Comment by ericspod** [comment]
With `num_res_units` as 0 then the decode layers will have only the transpose convolution, followed by normalization/dropout/activation layers except in the topmost layer which has none of these. Looking at the network `UNet(2,1,1,(2,4,8),(2,2))` this prints:

```
UNet(
  (model): Sequential(
    (0): Convolution(
      (conv): Conv2d(1, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (adn): ADN(
        (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (D): Dropout(p=0.0, inplace=False)
        (A): PReLU(num_parameters=1)
      )
    )
    (1): SkipConnection(
      (submodule): Sequential(
        (0): Convolution(
          (conv): Conv2d(2, 4, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (adn): ADN(
            (N): InstanceNorm2d(4, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            (D): Dropout(p=0.0, inplace=False)
            (A): PReLU(num_parameters=1)
          )
        )
        (1): SkipConnection(
          (submodule): Convolution(
            (conv): Conv2d(4, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (adn): ADN(
              (N): InstanceNorm2d(8, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
              (D): Dropout(p=0.0, inplace=False)
              (A): PReLU(num_parameters=1)
            )
          )
        )
        (2): Convolution(
          (conv): ConvTranspose2d(12, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
          (adn): ADN(
            (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            (D): Dropout(p=0.0, inplace=False)
            (A): PReLU(num_parameters=1)
          )
        )
      )
    )
    (2): Convolution(
      (conv): ConvTranspose2d(4, 1, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    )
  )
)
```

The second-last decode layer is

```
(conv): ConvTranspose2d(12, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
(adn): ADN(
  (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
  (D): Dropout(p=0.0, inplace=False)
  (A): PReLU(num_parameters=1)
)
```

while the final one is just a transpose convolution layer.

**Comment by kissievendor** [comment]
Okay. So without the residual units the network is not equal to a unet?
Because it has only a single convolution per layer?

**Comment by ericspod** [comment]
Structurally it's the same in that it's an autoencoder architecture with skip connections, but yes is not completely equivalent to the original definition.

**Comment by kissievendor** [comment]
Okay, thank you.
Do you perhaps know a paper I could cite for this network (no residual units)?

I would use BasicUnit instead, but I don't think it is working yet.

In any case thank you for the explanation.

**Comment by ericspod** [comment]
Please cite the paper in the UNet docstring, it uses residual  units but we don't have any reference for one that doesn't.

**Comment by kissievendor** [comment]
And what is then the difference between 1 and 2 residual units? 
Is 2 the number to get the 'normal' network they use in the paper in the docstring? 

Because then you have three convolutions per layer I think.

**Comment by ericspod** [comment]
The `num_res_units` value states how many sets of convolution/normalization/dropout/activation layers each residual unit has. In the paper this is 2.

**Comment by kissievendor** [comment]
But isn't there one too many Convolutions per layer? As can be seen in this summary. 
![image](https://user-images.githubusercontent.com/54887561/99819687-11be6300-2b50-11eb-803e-34ed8aae12ab.png)

**Comment by ericspod** [comment]
Here is the output for `UNet(2,1,1,(2,4,8),(2,2),num_res_units=2)`:

```
UNet(
  (model): Sequential(
    (0): ResidualUnit(
      (conv): Sequential(
        (unit0): Convolution(
          (conv): Conv2d(1, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (adn): ADN(
            (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            (D): Dropout(p=0.0, inplace=False)
            (A): PReLU(num_parameters=1)
          )
        )
        (unit1): Convolution(
          (conv): Conv2d(2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (adn): ADN(
            (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            (D): Dropout(p=0.0, inplace=False)
            (A): PReLU(num_parameters=1)
          )
        )
      )
      (residual): Conv2d(1, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    )
    (1): SkipConnection(
      (submodule): Sequential(
        (0): ResidualUnit(
          (conv): Sequential(
            (unit0): Convolution(
              (conv): Conv2d(2, 4, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
              (adn): ADN(
                (N): InstanceNorm2d(4, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
                (D): Dropout(p=0.0, inplace=False)
                (A): PReLU(num_parameters=1)
              )
            )
            (unit1): Convolution(
              (conv): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (adn): ADN(
                (N): InstanceNorm2d(4, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
                (D): Dropout(p=0.0, inplace=False)
                (A): PReLU(num_parameters=1)
              )
            )
          )
          (residual): Conv2d(2, 4, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (1): SkipConnection(
          (submodule): ResidualUnit(
            (conv): Sequential(
              (unit0): Convolution(
                (conv): Conv2d(4, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                (adn): ADN(
                  (N): InstanceNorm2d(8, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
                  (D): Dropout(p=0.0, inplace=False)
                  (A): PReLU(num_parameters=1)
                )
              )
              (unit1): Convolution(
                (conv): Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                (adn): ADN(
                  (N): InstanceNorm2d(8, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
                  (D): Dropout(p=0.0, inplace=False)
                  (A): PReLU(num_parameters=1)
                )
              )
            )
            (residual): Conv2d(4, 8, kernel_size=(1, 1), stride=(1, 1))
          )
        )
        (2): Sequential(
          (0): Convolution(
            (conv): ConvTranspose2d(12, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
            (adn): ADN(
              (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
              (D): Dropout(p=0.0, inplace=False)
              (A): PReLU(num_parameters=1)
            )
          )
          (1): ResidualUnit(
            (conv): Sequential(
              (unit0): Convolution(
                (conv): Conv2d(2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                (adn): ADN(
                  (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
                  (D): Dropout(p=0.0, inplace=False)
                  (A): PReLU(num_parameters=1)
                )
              )
            )
            (residual): Identity()
          )
        )
      )
    )
    (2): Sequential(
      (0): Convolution(
        (conv): ConvTranspose2d(4, 1, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
        (adn): ADN(
          (N): InstanceNorm2d(1, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
          (D): Dropout(p=0.0, inplace=False)
          (A): PReLU(num_parameters=1)
        )
      )
      (1): ResidualUnit(
        (conv): Sequential(
          (unit0): Convolution(
            (conv): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
        )
        (residual): Identity()
      )
    )
  )
)
```

The second-last decode layer is 

```
(0): Convolution(
	(conv): ConvTranspose2d(12, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
	(adn): ADN(
	  (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
	  (D): Dropout(p=0.0, inplace=False)
	  (A): PReLU(num_parameters=1)
	)
  )
  (1): ResidualUnit(
	(conv): Sequential(
	  (unit0): Convolution(
		(conv): Conv2d(2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
		(adn): ADN(
		  (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
		  (D): Dropout(p=0.0, inplace=False)
		  (A): PReLU(num_parameters=1)
		)
	  )
	)
	(residual): Identity()
  )
```

Here we have the transpose convolution followed  by a residual unit with one convolution. I guess this does vary from what I'd said in that the transpose convolution is outside the residual connection, which is needed since the input needs to be upsampled, but each decode layer does have two convolutions only as per the `num_res_units` value.

**Comment by kissievendor** [comment]
Yes. But in the encoding part, there is a additional convolution. This is why the number of parameters is larger when adding one Residual Unit. 
But is the Convolution supposed to be there / does it do anything? Since it has a stride of 2, one would think the input size is downsampled.

**Comment by almalennartsson-dev** [comment]
Hi @ericspod 
I'm currently using the monai unet for my master's thesis. What I don't understand is the bottom layer and the first up layer. For example this line in your previous post:

(conv): ConvTranspose2d(12, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))

Instead of going from the lowest level 8 to the next level 4, the unet goes straight to level 2. This does not seem to be the same as in most other unets, which are symmetric. Is there any reason for this choice?

**Comment by ericspod** [comment]
> Instead of going from the lowest level 8 to the next level 4, the unet goes straight to level 2. This does not seem to be the same as in most other unets, which are symmetric. Is there any reason for this choice?

I think the UNet we have here is doing a few things a little different from other standard definitions. The first input block in the above example will downsample with a strided convolution, which typical implementations don't do, since the first stride value is 2. You can make that 1 to get something closer to other implementations, but in terms of the levels you're mentioning I don't quite follow what the question here is. If we consider a simpler network without residual units `UNet(2,1,1,(2,4,8),(2,2),num_res_units=0)`:

```
UNet(
  (model): Sequential(
    (0): Convolution(
      (conv): Conv2d(1, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (adn): ADN(
        (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (D): Dropout(p=0.0, inplace=False)
        (A): PReLU(num_parameters=1)
      )
    )
    (1): SkipConnection(
      (submodule): Sequential(
        (0): Convolution(
          (conv): Conv2d(2, 4, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (adn): ADN(
            (N): InstanceNorm2d(4, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            (D): Dropout(p=0.0, inplace=False)
            (A): PReLU(num_parameters=1)
          )
        )
        (1): SkipConnection(
          (submodule): Convolution(
            (conv): Conv2d(4, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (adn): ADN(
              (N): InstanceNorm2d(8, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
              (D): Dropout(p=0.0, inplace=False)
              (A): PReLU(num_parameters=1)
            )
          )
        )
        (2): Convolution(
          (conv): ConvTranspose2d(12, 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
          (adn): ADN(
            (N): InstanceNorm2d(2, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            (D): Dropout(p=0.0, inplace=False)
            (A): PReLU(num_parameters=1)
          )
        )
      )
    )
    (2): Convolution(
      (conv): ConvTranspose2d(4, 1, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    )
  )
)
```

The bottom layer is 

```
(1): SkipConnection(
  (submodule): Convolution(
    (conv): Conv2d(4, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (adn): ADN(
      (N): InstanceNorm2d(8, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      (D): Dropout(p=0.0, inplace=False)
      (A): PReLU(num_parameters=1)
    )
  )
)
```

This is a skip connection so the output of the `Convolution` block will be added to the input. This is then the input for the next `Convolution` block (`(2): Convolution(...`) which is the first upsample block. This network has only 2 skip connections so the top-level layer composed of the first `Convolution` block and the final `ConvTranspose` block are just for input/output encoding. I've attempted to draw what this network looks like:

<img width="662" height="310" alt="Image" src="https://github.com/user-attachments/assets/c223045d-f27e-4ff1-91df-3001b1be3533" />
