### ISSUE TITLE
Add utility to scale Dataset for training

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1265]
**Is your feature request related to a problem? Please describe.**
Thanks for Dong Yang's suggestion, need a utility function to scale the loaded datalist for training, for example:
1. If scale_factor < 1.0, randomly pick part of the datalist and set to `Dataset`, useful to quickly test the program.
2. If scale_factor > 1.0, repeat the datalist to enhance the Dataset.

**Describe the solution you'd like**
```py
def scale_dataset(data, factor, random_pick=False, seed=0):
    ... ...
```

**Comment by wyli** [comment]
I think we could achieve this with the cross validation API already, or if not, we need to enhance the cross validation API
for something like:
```
cvdataset = CrossValidation(dataset_cls=MyDataset, nfolds=5, ....)
cvdataset.get_dataset(folds=[1])  # 20% sampling
cvdataset.get_dataset(folds=[1, 2, 3, 4, 5, 1])  # 120% sampling
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Sure, I updated the draft PR to leverage our `partition_dataset` API now.

Thanks.
