### ISSUE TITLE
How to plot mean val dice on tensorboard?

### ISSUE THREAD

**Issue by massimilianoporzio** [Project-MONAI/MONAI#1271]
Please can someone help me in finding the correct way to log the validation mean dice using tensoraboard handler?

**Comment by Nic-Ma** [comment]
Hi @massimilianoporzio ,

Thanks for your interest here.
Please refer to this example: https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/ignite/unet_training_dict.py

Thanks.
