### ISSUE TITLE
Update the Generalized Wasserstein Dice loss

### ISSUE THREAD

**Issue by LucasFidon** [Project-MONAI/MONAI#1272]
The implementation of the Generalized Wasserstein Dice loss that has been merged in MONAI does not correspond exactly to the loss proposed in https://link.springer.com/chapter/10.1007/978-3-319-75238-9_6

I will do the appropriate changes in the MONAI implementation and in the unit tests based on:
https://github.com/LucasFidon/GeneralizedWassersteinDiceLoss

I have used the current implementation from my repo in the BraTS challenge 2020, as an additional test, and it performed very well (and better than the implementation currently in MONAI)
https://arxiv.org/abs/2011.01614

**Comment by Nic-Ma** [comment]
Hi @wyli and @ericspod ,

Could you please help double confirm the implementation of our Generalized Wasserstein Dice loss?

Thanks.

**Comment by LucasFidon** [comment]
Hi @Nic-Ma, 

Thank you for your reply.

I have updated the code (including new unit tests) and I think it is ready to be merged.
I would like to know if I can add the generalized Wasserstein Dice loss to the documentation at the same time?

Thanks

**Comment by Nic-Ma** [comment]
I think you mean the doc-string of this loss function. Please also updated it in your PR.

Thanks.

**Comment by ericspod** [comment]
If you have a PR ready for MONAI with the changes we'll look at that, that way it would be clearer how you think our implementation varies.

**Comment by LucasFidon** [comment]
Hi @ericspod, thank you for offering to review the changes.

Just to clarify, the current implementation in MONAI is also based on my git repo https://github.com/LucasFidon/GeneralizedWassersteinDiceLoss (please see #601).
In the meantime, I have done some changes in my repo and I would like the changes to be reflected in MONAI.

Sorry for the confusion.

**Comment by ericspod** [comment]
No worries, we'll take a look when you're ready. If your code behaviour differs from what's published we need to make a note of it in the documentation of course.
