### ISSUE TITLE
revise the dockerfile

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1276]
this is a follow-up of https://github.com/Project-MONAI/MONAI/issues/1252
dockerfile needs to be reviewed for any further performance optimisations

**Comment by danielschulz** [comment]
I left you a comment in line 28 of:
https://github.com/Project-MONAI/MONAI/pull/1406/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

This COPY command w/ more specific arguments might improve things a little better.
