### ISSUE TITLE
Can not read .mhd files

### ISSUE THREAD

**Issue by Ordgod** [Project-MONAI/MONAI#1278]
**Describe the bug**
The monai can not read .mhd files. I checked the monai code and found that it only has LoadImage, LoadNifti, LoadPNG, and LoadNumpy. I how there should be a LoadITK for .mhd or .mha files. Because .mhd or .mha files are popular file types in medical community.

**Comment by Nic-Ma** [comment]
Hi @Ordgod ,

You can try to use the `LoadImage` or `LoadImaged` transforms.
They use `ITKReader` as the default reader: https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/io/array.py#L62

Thanks.
