### ISSUE TITLE
SegmentationSaver save same name issue

### ISSUE THREAD

**Issue by ChenglongWang** [Project-MONAI/MONAI#1279]
**Is your feature request related to a problem? Please describe.**
Current `SegmentationSaver` class save segmentation result using filename obtained from 'filename_or_obj' attribute. For example, `SegmentationSaver` will produce a segmentation filename like ‘/homes/data/outputs/kits_01_seg.nii.gz’  when processing image data named '/homes/data/kits_01.nii.gz'.  
However, when processing images named '/homes/data/kits_01/imaging.nii.gz' (kits_02, kits_03, etc.), `SegmentationSaver` will produce same segmentation filename like '/homes/data/outputs/imaging_seg.nii.gz' for all images. 

**Describe the solution you'd like**
My current solution is add an option in `SegmentationSaver` such as 'output_name_level' and pass it to the inside `NiftiSaver` and `PNGSaver`. Another temporary solution is change the batch_transform like `batch_transform=lambda x: {"filename_or_obj": list(map(lambda x: os.path.dirname(x), x["image_meta_dict"]["filename_or_obj"]))}`. Personally, I think the former solution is better than the latter one. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @ChenglongWang ,

Thanks for raising this topic, maybe we can add a lambda function option to customize saved filename @wyli .
And for a temporary solution, you can pass metadata = None, then it will use index from 0 as the filename.

Thanks.

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/pull/1890 the `data_root_dir` option
