### ISSUE TITLE
Beginner's question: Segmentation output

### ISSUE THREAD

**Issue by jnc13** [Project-MONAI/MONAI#1280]
Hi,
I've begun implementing UNet based off framework presented in the 3D Spleen Segmentation tutorial and it appears to be doing a reasonable job, thank you!

My background isn't in coding and I'm now a little stuck at the point where I'd like to evaluate the model on a dataset and then save the segmented stack as a .nii.gz (same as the input data). I am sure this isn't complicated, especially since we plot a slice! I have tried amending the for loop as in the Spleen example to include a "nib.save" statement but I get: AttributeError: 'Tensor' object has no attribute 'to_filename'
I can see this makes sense but don't have the experience to correct it. Please how do I now under the "ToTensord" transformation we did before feeding images to the model? Or is there another way?

Is there a MONAI implementation to use to do what I'm looking for? I've looked through the documentation but nothing jumps out as being what I'm looking for.

Thanks in advance!

**Comment by Nic-Ma** [comment]
Hi @jnc13 ,

Thanks for your interest here.
I think you want to write the segmentation output into some Nifiti files, you can refer to this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_evaluation_dict.py

Thanks.

**Comment by jnc13** [comment]
That's perfect thank you @Nic-Ma
