### ISSUE TITLE
Improvements to Convolution

### ISSUE THREAD

**Issue by jbschiratti** [Project-MONAI/MONAI#1284]
**Is your feature request related to a problem? Please describe.**
I'd like the `groups` parameter of Pytorch convolution layers to be explicit in the `monai.networks.blocks.convolutions.Convolution` class. Also, I think that `Convolution` should throw a warning when it is instantiated with `norm=Norm.BATCH, bias=True` since it makes no sense to have `bias=True` in the convolution layer when it's followed by a BN layer.

If these features are relevant to MONAI, I'd happy to submit a PR :-)

**Comment by wyli** [comment]
it seems the groups option is already in the API
https://github.com/Project-MONAI/MONAI/blob/4f2df00ffb820e7a1ff0ceb71a079ca1bf8b547f/monai/networks/blocks/convolutions.py#L81

yes please send a PR, thank you!

**Comment by wyli** [comment]
no progress for 3 weeks I'm closing this for now
