### ISSUE TITLE
RandWeightedCrop binary weight map

### ISSUE THREAD

**Issue by babbu3682** [Project-MONAI/MONAI#1298]
Even though I have a weight map with a value of [0, 1], sometime RandWeightedCrop cut the area with only zero.

![image](https://user-images.githubusercontent.com/48959435/100399310-926fe880-3095-11eb-9079-5a161a643766.png)

**Comment by wyli** [comment]
I couldn't reproduce this issue with this toy example, could you help change it according to your test case?
```py
import matplotlib.pyplot as plt
import numpy as np

from monai.transforms import RandWeightedCropd

label = np.zeros((1, 512, 512))
label[0, 130:170, 60:180] = 1.0
label[0, 160:180, 50:195] = 0.5

num_samples = 5
crop = RandWeightedCropd("label", "w", spatial_size=(256, 256), num_samples=num_samples)
d = {"label": label, "w": (label == label.max()).astype("uint8")}
result = crop(d)

plt.imshow(label[0])
plt.show()

# fig, axs = plt.subplots(1, num_samples)
# for idx in range(num_samples):
#     axs[idx].imshow(result[idx]['label'][0])
# plt.show()
```
label map:
![original](https://user-images.githubusercontent.com/831580/100437805-36a75e80-3099-11eb-9cf7-7daab90e6640.png)
 samples:
![Screenshot 2020-11-27 at 10 14 19](https://user-images.githubusercontent.com/831580/100437870-52126980-3099-11eb-9871-ec0b0c349929.png)

**Comment by babbu3682** [comment]
Here 

![image](https://user-images.githubusercontent.com/48959435/100497156-def21b80-319c-11eb-921d-342563066fb1.png)

**Comment by wyli** [comment]
that's expected, with label==label.max(), the only positive weights will be at the lower right corner, which is not feasible for sampling because the window would be outside of the image. so, in this case, the effective weight map is actually all zeros, it'll use a uniform sampling instead. to verify this you can try `label[0, 450:480, 450:480] = 3`-> `label[0, 447:480, 447:480] = 3`

**Comment by babbu3682** [comment]
Hi @wyli !

If I want to crop the images which have the target class, how can I revise your code? because I want to balance the mask class in cropped images.

**Comment by babbu3682** [comment]
> that's expected, with label==label.max(), the only positive weights will be at the lower right corner, which is not feasible for sampling because the window would be outside of the image. so, in this case, the effective weight map is actually all zeros, it'll use a uniform sampling instead. to verify this you can try `label[0, 450:480, 450:480] = 3`-> `label[0, 447:480, 447:480] = 3`


Hi @wyli !

If I want to crop the images which have the target class, how can I revise your code? because I want to balance the mask class in cropped images.

**Comment by wyli** [comment]
Hi @babbu3682 you can add a tiny value to all the locations in the weight map, something like `w = (label == label.max()) + 1e-2`
