### ISSUE TITLE
Windows performance orders of magnitude lower than Linux's

### ISSUE THREAD

**Issue by aarpon** [Project-MONAI/MONAI#1300]
Hello, everyone

I usually develop and work in Linux, but my users are mostly on Windows. So, I tried my code on 3 different Windows machines today (just in case), and quickly saw that the training performance in Linux is **orders of magnitude** better than in Windows. 

After some checks, I realised that:
* PyTorch says that it uses the GPU, and it ideed seems to do so
* the task manager shows that the GPU memory is indeed filling up
* the GPU has short bursts of utilisation for a second or two that correspond to the actual training, and then idles for almost a minute.

I profiled the code and realised that in two training epochs, **more than 90 seconds (!)** are used by the function `CloudPickler.dump()`. Two training epochs in Linux with the same data (and same code) require around 3 seconds with validation.

I have seen this (or similar) problem  in Windows when (explicitly) using `multiprocessing`: in contrast to Linux, where data is accessed in shared memory, in Windows data is passed across using `pickle`, and this is **extremely** slow. 

Are you guys aware of a solution or a workaround for this? 

Thanks!
Aaron

**Comment by rijobro** [comment]
So just to clarify, you've noticed performance that's orders of magnitude with respect to time, but the results are equivalent (or close)?

**Comment by aarpon** [comment]
I never managed to wait that long. However, this alternative `(Fast)DataLoader` fixes the issue in Windows:

https://github.com/pytorch/pytorch/issues/15849#issuecomment-573921048

There is an indirect link to it via a PyTorch issue from [issue 1240](https://github.com/Project-MONAI/MONAI/issues/1240).

**Comment by aarpon** [comment]
To conclude, with the new `FastDataLoader`, the (time) performance in Windows in now on par with the performance in Linux, and the results are equivalent (visually, they are the same).

**Comment by wyli** [comment]
thanks for the pointers, would setting `persistent_wokers=True` achieve the same effect? https://pytorch.org/docs/stable/data.html

**Comment by aarpon** [comment]
The `persistent_workers=True` argument seems to work well (it requires `PyTorch >= 1.7.0`, though). However, I had to remove the `pin_memory=True` argument to prevent a crash with following error:

```bash
  File "...\envs\deep_tools\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)
```

Without `persistent_workers=True`, `pin_memory` works fine.

**Comment by wyli** [comment]
> The `persistent_workers=True` argument seems to work well (it requires `PyTorch >= 1.7.0`, though). However, I had to remove the `pin_memory=True` argument to prevent a crash with following error:
> 
> ```shell
>   File "...\envs\deep_tools\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 28, in _pin_memory_loop
>     idx, data = r
> ValueError: not enough values to unpack (expected 2, got 0)
> ```
> 
> Without `persistent_workers=True`, `pin_memory` works fine.

 https://github.com/pytorch/pytorch/issues/48370
