### ISSUE TITLE
 RandCropByPosNegLabeld

### ISSUE THREAD

**Issue by jnc13** [Project-MONAI/MONAI#1313]
Hey,

I'm following the Spleen 3D Segmentation workflow with my own code and wonder if I need to include RandCropByPosNegLabeld in my transformations? I have tried to remove it with no luck. From what I can see it is necessary to use RandCropByPosNegLabeld for the dataloader? My code runs fine until it attempts to begin the training. Here is the error:

> ----------
> epoch 1/15
> Traceback (most recent call last):
> 
>   File "C:\Users\jc3456\GitHub\CTPA-PH-tool\train.py", line 294, in <module>
>     for batch_data in train_loader:
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
>     data = self._next_data()
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
>     return self.collate_fn(data)
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\monai\data\utils.py", line 235, in list_data_collate
>     return default_collate(data)
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in default_collate
>     return {key: default_collate([d[key] for d in batch]) for key in elem}
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in <dictcomp>
>     return {key: default_collate([d[key] for d in batch]) for key in elem}
> 
>   File "C:\Users\jc3456\Anaconda3\envs\MONAI\lib\site-packages\torch\utils\data\_utils\collate.py", line 55, in default_collate
>     return torch.stack(batch, 0, out=out)
> 
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 159 and 143 in dimension 2 at C:\Users\builder\AppData\Local\Temp\pip-req-build-e5c8dddg\aten\src\TH/generic/THTensor.cpp:612

If I include the RandCrop transformation there are no problems. The image and label dimensions do seem to match okay:

> Load and cache transformed data:   0%|          | 0/3 [00:00<?, ?it/s]image shape: torch.Size([159, 159, 101]), label shape: torch.Size([159, 159, 101])

I ask because:
1. I'd ideally like to at least try running the code on uncropped full volumes to see the effect
2. I want to begin trying some automated parameter sweeps and am getting some errors when I don't take care in setting the  RandCropByPosNegLabeld dimensions carefully myself. When I included RandCrop in my automated sweep (setting min/max bounds for variables) there were problems where the spatial size was unagreeable, eg (95,80,64) which caused an error. 

Could you please advise if I can run the code successfully without including RandCropByPosNegLabeld?

Thank you

**Comment by Nic-Ma** [comment]
Hi @jnc13 ,

Thanks for your interest and experiments with MONAI.
If you don't want to do any `random` cropping and want to align images size, you can use this transform instead:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/croppad/dictionary.py#L551

Thanks.

**Comment by jnc13** [comment]
Hi @Nic-Ma ,

Thanks, this is perfect! Could you please advise what the requirements are for choosing suitable image dimensions?  I notice that not all values are suitable. Perhaps there is something simple which I am missing eg all dimensions have to be 2^n?

For example for my images:
96,96,64 runs perfectly
144,144,96 runs perfectly
140,140,90 resulted in an error.

Could you please spell out for me what the requirements are for choosing the dimensions?

Thanks,

**Comment by Nic-Ma** [comment]
Hi @wenqi,

Could you please help with this question? I think you are more familiar with it.
Thanks in advance.

**Comment by wyli** [comment]
yes, not all the networks support arbitrary input dimensions, we don't currently have an exhaustive list of the suitable options, you could try different values and please consider using https://github.com/Project-MONAI/MONAI/blob/395fa23758faff0a15ff7e88d60d9fe142268118/monai/transforms/croppad/array.py#L598
or https://github.com/Project-MONAI/MONAI/blob/395fa23758faff0a15ff7e88d60d9fe142268118/monai/transforms/croppad/array.py#L157
to make the workflow robust to different input sizes.  the original issue is addressed, I'm closing this ticket for now
