### ISSUE TITLE
Missing up_modules in AHNet when TorchScript

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1315]
**Describe the bug**
When exporting model in TorchScript, it output error:
```
RuntimeError: 
Module 'PSP' has no attribute 'up_modules' :
  File "/workspace/data/medical/MONAI/monai/networks/nets/ahnet.py", line 290
        if self.upsample_mode == "transpose":
            for (project_module, pool_module, up_module) in zip(
                self.project_modules, self.pool_modules, self.up_modules
                                                         ~~~~~~~~~~~~~~~ <--- HERE
            ):
                output = up_module(project_module(pool_module(x)))
```
I will fix it ASAP.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Our CI test doesn't face this issue because `TorchScript` depends on the parameters of network.
If I change the default model from `transpose` to `nearest`, CI will fail with same error:
```py
    @skip_if_quick
    def test_script(self):
        net = AHNet(spatial_dims=3, upsample_mode="nearest", out_channels=2)
        test_data = torch.randn(1, 1, 128, 64, 32)
        test_script_save(net, test_data)
```

Thanks.

**Comment by Nic-Ma** [comment]
Reopen the issue because we may still have other parameter-related TorchScript issues in other networks, need @ericspod to help double confirm.

Thanks.

**Comment by ericspod** [comment]
Yes there were a few other instances of this I changed earlier but missed this one. All members which Torchscript needs to encode, nn.Module members for the most part, must always be created in the constructor. As a general Pythonic style this should always be the case anyhow, users of a class typically expect a member to always be present in its instances.

**Comment by Nic-Ma** [comment]
Sure, thanks for your explanation.
