### ISSUE TITLE
SegmentationSaver ValueError

### ISSUE THREAD

**Issue by kissievendor** [Project-MONAI/MONAI#1317]
I am getting an error when trying to save the segmentations. 

ValueError: only one element tensors can be converted to Python scalars

I already have to change some things to the meta data to prevent errors. 
The method worked before. If I set resample=False, I don't get the error, and nii are saved. 
However, the images are not loaded properly in FSL eyes. 

Did you perhaps change something in version 0.3? 

Thank you. 

![image](https://user-images.githubusercontent.com/54887561/101026026-ad9b9600-3576-11eb-87a9-63f66df5435f.png)

**Comment by wyli** [comment]
I don't fully understand the issue here but you could try to make sure that `affine` and `original_affine` 4x4 numpy arrays

**Comment by kissievendor** [comment]
The problem is, that it doesn't save the segmentations correctly. 
In the transform, I change the orientation to 'RAS'. 

If I don't do that, I do not get the error. So I think there is an error in coverting the segmentation back to the original orientation.

**Comment by kissievendor** [comment]
I think I may have solved it. 
In your code, you use expand_dims (see below). I think it should be np.squeeze(data, 0)

It works for me now. Thank you. 

![image](https://user-images.githubusercontent.com/54887561/101330594-146cc800-3873-11eb-927a-386d0dfeba19.png)
