### ISSUE TITLE
Question about synchronised img/seg random transforms

### ISSUE THREAD

**Issue by r-gray** [Project-MONAI/MONAI#1322]
Hello,

Just wondering if random transformations applied to img and seg are always in synch... MONAI's nifti_reader.py applies the transformations with

if self.transform is not None:
    if isinstance(self.transform, Randomizable):
        self.transform.set_random_state(seed=self._seed)
    img = apply_transform(self.transform, img)

and then does the same to the segmentations with

if self.seg_transform is not None:
    if isinstance(self.seg_transform, Randomizable):
        self.seg_transform.set_random_state(seed=self._seed)
    seg = apply_transform(self.seg_transform, seg)

Does it matter that even after the

self.seg_transform.set_random_state(seed=self._seed)

command the bit_streams in the MT19937 random number generators of the two transformations in my self.transform = Compose([RandAffine(), Rand3DElastic()]) list are different? I can make them equal by also running

for trans in self.transform .transforms:
        trans.set_random_state(self._seed)

After doing this I noticed a drop in the errors in my model! This change causes a crash if I put certain torchvision transformations inside the list inside Compose though, e.g. torchvision.transforms.RandomDownsample apparently has no random state, so this causes an error...

Is it just that in MONAI's current code the bit_streams are equalised later under the hood & I'm missing it?

Thanks! Robert.

**Comment by Nic-Ma** [comment]
Hi @r-gray ,

MONAI transforms can do random transforming on `image` and `label` in sync.
Suggest you to use `dict` format data and `dict` specific transforms.

Thanks.

**Comment by r-gray** [comment]
OK, I will give that a try instead. Thanks very much for the response!
