### ISSUE TITLE
Can MONAI support multi GPU？

### ISSUE THREAD

**Issue by zhongqiu1245** [Project-MONAI/MONAI#1323]
Thank you for your amazing job!
Does MONAI support multi-GPU training?？
If support, how can I use it?
Thank you!(forgive me my poor English)

**Comment by Nic-Ma** [comment]
Hi @zhongqiu1245 ,

Yes, MONAI can support multi-GPU, you can use the standard PyTorch method to launch your multi-GPU program, we don't make any API above PyTorch multi-GPU API.

Thanks.

**Comment by zhongqiu1245** [comment]
Thank you
