### ISSUE TITLE
Type Error: Data Type not understood

### ISSUE THREAD

**Issue by AmoghJ001** [Project-MONAI/MONAI#1335]
When I am loading the test set for inference after training, I am getting data type not understood error. And I tried searching but I guess no one has faced this issue while segmentation. Please help me @Nic-Ma  as I am a beginner. Thanks! Here’s the main inference code
   
    inferer = get_inferer()
    saver = monai.data.NiftiSaver(output_dir=prediction_folder, mode="nearest")
    with torch.no_grad():
        for infer_data in infer_loader:
            logging.info(f"segmenting {infer_data['image_meta_dict']['filename_or_obj']}")
            preds = inferer(infer_data[keys[0]].to(device), net)
            n = 1.0
            for _ in range(4):
                # test time augmentations
                _img = RandGaussianNoised(keys[0], prob=1.0, std=0.01)(infer_data[keys[0]])
                pred = inferer(_img.to(device), net)
                preds = preds + pred
                n = n + 1.0
                for dims in [[2], [3]]:
                    flip_pred = inferer(torch.flip(_img.to(device), dims=dims), net)
                    pred = torch.flip(flip_pred, dims=dims)
                    preds = preds + pred
                    n = n + 1.0
            preds = preds / n
            preds = (preds.argmax(dim=1, keepdims=True)).float()
            saver.save_batch(preds, infer_data["image_meta_dict"])`
Here’s the transforms applied to test images:
 
   
    def get_xforms(mode="train", keys=("image", "label")):
    """returns a composed transform for train/val/infer."""

    xforms = [
        LoadNiftid(keys),
        AddChanneld(keys),
        Orientationd(keys, axcodes="LPS"),
        Spacingd(keys, pixdim=(1.25, 1.25, 5.0), mode=("bilinear", "nearest")[: len(keys)]),
        ScaleIntensityRanged(keys[0], a_min=-1000.0, a_max=500.0, b_min=0.0, b_max=1.0, clip=True),
    ]
    if mode == "train":
        xforms.extend(
            [
                SpatialPadd(keys, spatial_size=(192, 192, -1), mode="reflect"),  # ensure at least 192x192
                RandAffined(
                    keys,
                    prob=0.15,
                    rotate_range=(-0.05, 0.05),
                    scale_range=(-0.1, 0.1),
                    mode=("bilinear", "nearest"),
                    as_tensor_output=False,
                ),
                RandCropByPosNegLabeld(keys, label_key=keys[1], spatial_size=(192, 192, 16), num_samples=1),
                RandGaussianNoised(keys[0], prob=0.15, std=0.01),
                RandFlipd(keys, spatial_axis=0, prob=0.5),
                RandFlipd(keys, spatial_axis=1, prob=0.5),
                RandFlipd(keys, spatial_axis=2, prob=0.5),
            ]
        )
        dtype = (np.float32, np.uint8)
    if mode == "val":
        dtype = (np.float32, np.uint8)
    if mode == "infer":
        dtype = (np.float32,)
    xforms.extend([CastToTyped(keys, dtype=dtype), ToTensord(keys)])
    return monai.transforms.Compose(xforms)`
Here's the error when I run the inference pipeline:

INFO:root:available model file: /content/COVID-19-20_v2/checkpoint_key_metric=0.4376.pt.
INFO:root:available model file: /content/COVID-19-20_v2/checkpoint_key_metric=0.4497.pt.
INFO:root:available model file: /content/COVID-19-20_v2/final.pt.
INFO:root:----
INFO:root:using /content/COVID-19-20_v2/final.pt.
INFO:root:infer: image (50) folder: /content/COVID-19-20_v2/Validation
INFO:root:segmenting ['/content/COVID-19-20_v2/Validation/volume-covid19-A-0004_ct.nii.gz']
Traceback (most recent call last):
  File "/content/COVID-19-20_v2/run_net2.py", line 317, in <module>
    infer(data_folder=data_folder, model_folder=args.model_folder)
  File "/content/COVID-19-20_v2/run_net2.py", line 267, in infer
    _img = RandGaussianNoised(keys[0], prob=1.0, std=0.01)(infer_data)[keys[0]]
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/intensity/dictionary.py", line 76, in __call__
    d[key] = d[key] + self._noise.astype(d[key].dtype)
TypeError: data type not understood

**Comment by rijobro** [comment]
The problem is during the inference? Try changing `dtype = (np.float32,)` to `dtype = np.float32`.

**Comment by AmoghJ001** [comment]
> 
> 
> The problem is during the inference? Try changing `dtype = (np.float32,)` to `dtype = np.float32`.

Tried that. That doesnt solve the problem. Getting the same error.
RandGaussianNoised being a dict transform expects all the images to be of same shape. This is written on the MONAI transforms page. My test set contains images of varying slices like: (512,512,X).
Is that causing the issue?

**Comment by Nic-Ma** [comment]
Hi @AmoghJ001 and @rijobro ,

The root cause of this issue is that we added Tensor data support  in `RandGaussianNoised ` after MONAI 0.3 release. So if you want to use it for Tensor data, please try to use the latest master code.

Thanks.

**Comment by AmoghJ001** [comment]
> 
> 
> Hi @AmoghJ001 and @rijobro ,
> 
> The root cause of this issue is that we added Tensor data support in `RandGaussianNoised ` after MONAI 0.3 release. So if you want to use it for Tensor data, please try to use the latest master code.
> 
> Thanks.

Hi! Can you please elaborate further as I am a beginner. As you can see, I am converting to Tensors when applying transforms. So I am dealing with tensor data right? And what changes should I make to the above code?

**Comment by Nic-Ma** [comment]
Hi @AmoghJ001 ,

I think the `infer_data` in below line is PyTorch Tensor:
```py
_img = RandGaussianNoised(keys[0], prob=1.0, std=0.01)(infer_data[keys[0]])
```
So the easiest way for you is to uninstall your MONAI and install from the master code as we added support for Tensor in `RandGaussianNoised` transform after v0.3 release.
```
pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
```

Thanks.

**Comment by AmoghJ001** [comment]
> 
> 
> Hi @AmoghJ001 ,
> 
> I think the `infer_data` in below line is PyTorch Tensor:
> 
> ```python
> _img = RandGaussianNoised(keys[0], prob=1.0, std=0.01)(infer_data[keys[0]])
> ```
> 
> So the easiest way for you is to uninstall your MONAI and install from the master code as we added support for Tensor in `RandGaussianNoised` transform after v0.3 release.
> 
> ```
> pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
> ```
> 
> Thanks.

Oh! Sure. Will try that! Thanks!
