### ISSUE TITLE
RandCropByPosNegLabeld

### ISSUE THREAD

**Issue by mikiwang820** [Project-MONAI/MONAI#1342]
**Hello,**
**I want to reproduce spleen_segmentation_3d code on LiTS open source dataset.**
**I tried two ways, but all of these didn't work.**
**Below is my code and error, and I consider these errors maybe come from RandCropByPosNegLabeld or memory is not large enough.**
**However, I can't figure out how should I deal with this problem.**
**Is there any solution for this? I will appreciate it.**

**Firstly, I just change the dataset in spleen_segmentation_3d**
`train_images = sorted(glob.glob(os.path.join(data_dir, "train_2classes","img", "*.nii.gz")))
train_labels = sorted(glob.glob(os.path.join(data_dir, "train_2classes","lab",  "*.nii.gz")))`

**and the error is**
----------
epoch 1/600
1/52, train_loss: 0.5172
2/52, train_loss: 0.5614
3/52, train_loss: 0.5410
4/52, train_loss: 0.5307
5/52, train_loss: 0.5218
6/52, train_loss: 0.4819
7/52, train_loss: 0.4804
8/52, train_loss: 0.4631
9/52, train_loss: 0.5002
10/52, train_loss: 0.5666
11/52, train_loss: 0.5103

RuntimeErrorTraceback (most recent call last)
<ipython-input-18-c050bbb9fb77> in <module>
     14     epoch_loss = 0
     15     step = 0
---> 16     for batch_data in train_loader:
     17         step += 1
     18         inputs, labels = (

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    398 
    399     def __next__(self) -> Any:
--> 400         data = self._next_data()
    401         self._num_yielded += 1
    402         if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
   1012             if len(self._task_info[self._rcvd_idx]) == 2:
   1013                 data = self._task_info.pop(self._rcvd_idx)[1]
-> 1014                 return self._process_data(data)
   1015 
   1016             assert not self._shutdown and self._tasks_outstanding > 0

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1056         self._try_put_index()
   1057         if isinstance(data, ExceptionWrapper):
-> 1058             data.reraise()
   1059         return data
   1060 

/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)
    418             # (https://bugs.python.org/issue2651), so we work around it.
    419             msg = KeyErrorMessage(msg)
--> 420         raise self.exc_type(msg)
    421 
    422 

RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/utils.py", line 364, in apply_transform
    return transform(data)
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/croppad/dictionary.py", line 535, in __call__
    self.randomize(label, fg_indices, bg_indices, image)
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/croppad/dictionary.py", line 525, in randomize
    self.spatial_size, self.num_samples, self.pos_ratio, label.shape[1:], fg_indices_, bg_indices_, self.R
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/utils.py", line 298, in generate_pos_neg_label_crop_centers
    raise ValueError("The proposed roi is larger than the image.")
ValueError: The proposed roi is larger than the image.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/MONAI/tutorials/3d_segmentation/monai/data/dataset.py", line 530, in __getitem__
    data = apply_transform(_transform, data)
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/utils.py", line 366, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.RandCropByPosNegLabeld object at 0x7f16345bdc50>

**The second way is followed tutorial workflow and I just changed some hyper parameters like spatial_size in RandCropByPosNegLabeld.
Here is my code,**

```
import glob
import os
import shutil
import tempfile

import matplotlib.pyplot as plt
import torch

from monai.apps import download_and_extract
from monai.config import print_config
from monai.data import CacheDataset, DataLoader, Dataset
from monai.inferers import sliding_window_inference
from monai.losses import DiceLoss
from monai.metrics import compute_meandice
from monai.networks.layers import Norm
from monai.networks.nets import UNet
from monai.transforms import (
    AsDiscrete,
    AddChanneld,
    Compose,
    CropForegroundd,
    LoadImaged,
    Orientationd,
    RandCropByPosNegLabeld,
    ScaleIntensityRanged,
    Spacingd,
    ToTensord,
)
from monai.utils import first, set_determinism
print_config()

#load data
root_dir = "/data2/open_dataset/lits_1mm"
data_dir = os.path.join(root_dir, "liver_91")
train_images = sorted(glob.glob(os.path.join(data_dir, "train_2classes","img", "*.nii.gz")))
train_labels = sorted(glob.glob(os.path.join(data_dir, "train_2classes","lab",  "*.nii.gz")))
data_dicts = [
    {"image": image_name, "label": label_name}
    for image_name, label_name in zip(train_images, train_labels)
]
train_files = data_dicts
val_images = sorted(glob.glob(os.path.join(data_dir, "val_2classes","img", "*.nii.gz")))
val_labels = sorted(glob.glob(os.path.join(data_dir, "val_2classes","lab",  "*.nii.gz")))
val_data_dicts = [
    {"image": image_name, "label": label_name}
    for image_name, label_name in zip(val_images, val_labels)
]
val_files = val_data_dicts
set_determinism(seed=0)
train_transforms = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        AddChanneld(keys=["image", "label"]),
        Spacingd(keys=["image", "label"], pixdim=(1.0, 1.0, 2.0), mode=("bilinear", "nearest")),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        ScaleIntensityRanged(
            keys=["image"], a_min=-200, a_max=250, b_min=0.0, b_max=1.0, clip=True,
        ),
        CropForegroundd(keys=["image", "label"], source_key="image"),
        RandCropByPosNegLabeld(
            keys=["image", "label"],
            label_key="label",
            spatial_size=(64,64,64),
            pos=1,
            neg=1,
            num_samples=2, #here
            image_key="image",
            image_threshold=0,
        ),
        ToTensord(keys=["image", "label"]),
    ]
)
val_transforms = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        AddChanneld(keys=["image", "label"]),
        Spacingd(keys=["image", "label"], pixdim=(1.0, 1.0, 2.0), mode=("bilinear", "nearest")),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        ScaleIntensityRanged(
            keys=["image"], a_min=-200, a_max=250, b_min=0.0, b_max=1.0, clip=True,
        ),
        CropForegroundd(keys=["image", "label"], source_key="image"),
        ToTensord(keys=["image", "label"]),
    ]
)
train_ds = CacheDataset(data=train_files, transform=train_transforms, cache_rate=1.0, num_workers=4)
train_loader = DataLoader(train_ds, batch_size=1, shuffle=True, num_workers=4) #here batch_size
val_ds = CacheDataset(data=val_files, transform=val_transforms, cache_rate=1.0, num_workers=4) 
val_loader = DataLoader(val_ds, batch_size=1, num_workers=4)
device = torch.device("cuda:0")
model = UNet(
    dimensions=3,
    in_channels=1,
    out_channels=2,
    channels=(16, 32, 64, 128, 256),
    strides=(2, 2, 2, 2),
    num_res_units=2,
    norm=Norm.BATCH,
).to(device)
loss_function = DiceLoss(to_onehot_y=True, softmax=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4)
epoch_num = 1000
val_interval = 2
best_metric = -1
best_metric_epoch = -1
epoch_loss_values = list()
metric_values = list()
post_pred = AsDiscrete(argmax=True, to_onehot=True, n_classes=2)
post_label = AsDiscrete(to_onehot=True, n_classes=2)

for epoch in range(epoch_num):
    print("-" * 10)
    print(f"epoch {epoch + 1}/{epoch_num}")
    model.train()
    epoch_loss = 0
    step = 0
    for batch_data in train_loader:
        step += 1
        inputs, labels = (
            batch_data["image"].to(device),
            batch_data["label"].to(device),
        )
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = loss_function(outputs, labels)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        print(f"{step}/{len(train_ds) // train_loader.batch_size}, train_loss: {loss.item():.4f}")
    epoch_loss /= step
    epoch_loss_values.append(epoch_loss)
    print(f"epoch {epoch + 1} average loss: {epoch_loss:.4f}")

    if (epoch + 1) % val_interval == 0:
        model.eval()
        with torch.no_grad():
            metric_sum = 0.0
            metric_count = 0
            for val_data in val_loader:
                val_inputs, val_labels = (
                    val_data["image"].to(device),
                    val_data["label"].to(device),
                )
                roi_size = (160, 160, 160)
                sw_batch_size = 4
                val_outputs = sliding_window_inference(val_inputs, roi_size, sw_batch_size, model)
                val_outputs = post_pred(val_outputs)
                val_labels = post_label(val_labels)
                value = compute_meandice(
                    y_pred=val_outputs,
                    y=val_labels,
                    include_background=False,
                )
                metric_count += len(value)
                metric_sum += value.sum().item()
            metric = metric_sum / metric_count
            metric_values.append(metric)
            if metric > best_metric:
                best_metric = metric
                best_metric_epoch = epoch + 1
                torch.save(model.state_dict(), os.path.join(root_dir, "best_metric_model.pth"))
                print("saved new best metric model")
            print(
                f"current epoch: {epoch + 1} current mean dice: {metric:.4f}"
                f"\nbest mean dice: {best_metric:.4f} at epoch: {best_metric_epoch}"
            )
plt.figure("train", (12, 6))
plt.subplot(1, 2, 1)
plt.title("Epoch Average Loss")
x = [i + 1 for i in range(len(epoch_loss_values))]
y = epoch_loss_values
plt.xlabel("epoch")
plt.plot(x, y)
plt.subplot(1, 2, 2)
plt.title("Val Mean Dice")
x = [val_interval * (i + 1) for i in range(len(metric_values))]
y = metric_values
plt.xlabel("epoch")
plt.plot(x, y)
plt.show()`
```

**The error is**
----------
epoch 1/1000
1/113, train_loss: 0.4133
2/113, train_loss: 0.5465
3/113, train_loss: 0.5858
4/113, train_loss: 0.5092
5/113, train_loss: 0.6811
6/113, train_loss: 0.5083
7/113, train_loss: 0.5666
8/113, train_loss: 0.4170
9/113, train_loss: 0.5558
10/113, train_loss: 0.6183
11/113, train_loss: 0.4750
12/113, train_loss: 0.3624
13/113, train_loss: 0.5290
14/113, train_loss: 0.6766
15/113, train_loss: 0.6742
16/113, train_loss: 0.4053
17/113, train_loss: 0.4097
18/113, train_loss: 0.3852
19/113, train_loss: 0.5776
20/113, train_loss: 0.6331
21/113, train_loss: 0.5024
22/113, train_loss: 0.4661
23/113, train_loss: 0.5300
24/113, train_loss: 0.3798
25/113, train_loss: 0.3623
26/113, train_loss: 0.5453

RuntimeErrorTraceback (most recent call last)
<ipython-input-18-f40250464d3e> in <module>
     14     epoch_loss = 0
     15     step = 0
---> 16     for batch_data in train_loader:
     17         step += 1
     18         inputs, labels = (

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    398 
    399     def __next__(self) -> Any:
--> 400         data = self._next_data()
    401         self._num_yielded += 1
    402         if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
   1012             if len(self._task_info[self._rcvd_idx]) == 2:
   1013                 data = self._task_info.pop(self._rcvd_idx)[1]
-> 1014                 return self._process_data(data)
   1015 
   1016             assert not self._shutdown and self._tasks_outstanding > 0

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1056         self._try_put_index()
   1057         if isinstance(data, ExceptionWrapper):
-> 1058             data.reraise()
   1059         return data
   1060 

/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)
    418             # (https://bugs.python.org/issue2651), so we work around it.
    419             msg = KeyErrorMessage(msg)
--> 420         raise self.exc_type(msg)
    421 
    422 

RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/utils.py", line 364, in apply_transform
    return transform(data)
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/croppad/dictionary.py", line 535, in __call__
    self.randomize(label, fg_indices, bg_indices, image)
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/croppad/dictionary.py", line 525, in randomize
    self.spatial_size, self.num_samples, self.pos_ratio, label.shape[1:], fg_indices_, bg_indices_, self.R
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/utils.py", line 298, in generate_pos_neg_label_crop_centers
    raise ValueError("The proposed roi is larger than the image.")
ValueError: The proposed roi is larger than the image.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/MONAI/tutorials/3d_segmentation/monai/data/dataset.py", line 530, in __getitem__
    data = apply_transform(_transform, data)
  File "/data/MONAI/tutorials/3d_segmentation/monai/transforms/utils.py", line 366, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.RandCropByPosNegLabeld object at 0x7fda24c419e8>

**Comment by Nic-Ma** [comment]
Hi @mikiwang820 ,

I think maybe some of your images in the dataset is smaller than your crop size `(64,64,64)`?
Could you please try smaller crop size or different `spacing` parameters(now it's `pixdim=(1.0, 1.0, 2.0)`)?
You can also use some resize transform to unify the image size first.

Thanks.

**Comment by mikiwang820** [comment]
Hi @Nic-Ma ,

First of all, thanks for your reply, and I will try it.
However, I have a question about resize transform, is that fine for medical images? 
cause I think the shape.of organ could be fairly different.

**Comment by mikiwang820** [comment]
Hi, @Nic-Ma ,

Thanks for your reply. It works.

**Comment by Ontheroad123** [comment]
when crop size is bigger then image size, why not pad the image make sure the image size is same to roi size, i add code in './monai/transforms/croppad/array.py', 1086
`if any(np.subtract(img.shape[1:], roi_size) < 0):
        pad = SpatialPad(spatial_size=roi_size)
        img = pad(img)
`
then will not appear error, i think the roi size is correlation the model's robustness. If roi size to fit the smallest image size, i think it's not a good way.
