### ISSUE TITLE
highresnet; there is no need to pass the inplace input argument for all activations except ReLU

### ISSUE THREAD

**Issue by mbiparva** [Project-MONAI/MONAI#1346]
Hello guys,

I am using Highresnet in MONAI. There is a minor bug in the code at:

`monai/networks/nets/highresnet.py:79`

The issue is that there is no ```inplace``` input argument for activations other than ReLU such as PReLU.

**Comment by wyli** [comment]
thanks for reporting, indeed the api needs to be enhanced similarly to this https://github.com/Project-MONAI/MONAI/blob/453d40dee43dc8e3723c9ff4ebb92728763d63fe/monai/networks/nets/basic_unet.py#L144-L145
