### ISSUE TITLE
dynunet block: stride is unused but rather upsample_kernel_size is used

### ISSUE THREAD

**Issue by mbiparva** [Project-MONAI/MONAI#1348]
Hello guys,

In the `monai/networks/blocks/dynunet_block.py:183` input argument `stride` is not used and then oddly `upsample_stride = upsample_kernel_size`. I would say you should change it to something like this:

```
        super(UnetUpBlock, self).__init__()
        # upsample_stride = upsample_kernel_size  # This is commented out
        self.transp_conv = get_conv_layer(
            spatial_dims,
            in_channels,
            out_channels,
            kernel_size=upsample_kernel_size,
            # stride=upsample_stride,  # This is commented out
            stride=stride,  # This is added
            conv_only=True,
            is_transposed=True,
        )
```

This is going to lead to issue if the stride at some layer is different than upsample_kernel_size.

**Comment by ChenglongWang** [comment]
Hope this comment may help. https://github.com/Project-MONAI/MONAI/pull/1070#issuecomment-706195760
