### ISSUE TITLE
 I'm going to use AHNet.

### ISSUE THREAD

**Issue by shenao1994** [Project-MONAI/MONAI#1350]
I want to use AHNet for image classification.I read articles about AHNet. He mentioned that 2D images can be used for input, and the correlation between slices can be learned. But I want to know how the network knows that these individual 2D images come from the same lesion when I input 2D images.Or does it learn more about the relationship between slices when inputting 3D images?Thanks！

**Comment by Nic-Ma** [comment]
Hi @shenao1994 ,

Sorry for the delayed response, thanks for your interest here, let me ask the author of AHNet to help answer.
Thanks.

**Comment by Nic-Ma** [comment]
After syncing with internal team:
The AHNet learns about the relation when inputting 3D images, and current version of AHNet is not for classification.

Thanks.
