### ISSUE TITLE
British or American spelling?

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1382]
I searched through the GitHub repository and couldn't see any mention of spelling convention. I guess it should be stated in the [CONTRIBUTING.md](https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md).

Not so important, but I guess we might as well choose one and stick to it. There's a few mixtures of normalise/normalize, visualise/visualize, etc., throughout the codebase.

Partially related: https://github.com/Project-MONAI/MONAI/pull/1381

**Comment by tvercaut** [comment]
PyTorch seems to follow US spelling and MONAI attempts at following PyTorch conventions by default. By transitivity I would thus say that MONAI should use US spelling. It would make sense to clarify the English language and US spelling guidelines in MONAI's contribution guidelines

**Comment by ericspod** [comment]
Software in general seems dominated by US spelling. For example, I see "color" everywhere and only once have seen "colour" used as a type name in a library. US spelling has the advantage of at least being a little more concise.
