### ISSUE TITLE
LoadPNG for datasets with heterogeneous channel dimensions

### ISSUE THREAD

**Issue by stephenbaek** [Project-MONAI/MONAI#1389]
**Is your feature request related to a problem? Please describe.**
There are datasets where some images have different channel dimensions. For instance, the NIH Chest X-Ray dataset has the majority of images with a single channel (grayscale), but some of them are coded in 3 channels (RGB) or 4 channels (RGBA). 

**Describe the solution you'd like**
Wouldn't it be nice if there was a flag in LoadPNG(), something like cv2.IMREAD_COLOR, cv2.IMREAD_GRAYSCALE, and cv2.IMREAD_UNCHANGED flags implemented in cv2.imread() method in OpenCV?

**Describe alternatives you've considered**
Currently, I'm using a simple Lambda transform as a temporary makeshift:
```
transforms = Compose(
    [
        LoadPNGd("image"),
        Lambdad("image", func=lambda x: np.mean(x, axis=2) if len(x.shape) == 3 else x),
        AsChannelFirstd("image"),
        AddChanneld("image"),
        ScaleIntensityd("image"),
    ]
)
```

**Comment by Nic-Ma** [comment]
Hi @stephenbaek ,

Thanks for your interest here.
Now we use `PIL.Image` and `ITK` to load PNG images, is there any potential args in these APIs or the `converter` can satisfy your request?
For example, you can specify PILReader for LoadImage with a `converter`:
```py

loader = LoadImage(PILReader(converter=lambda image: image.convert("LA")))
data, meta = loader(filename)
```

Thanks.

**Comment by stephenbaek** [comment]
@Nic-Ma Thanks for getting back. Using `PIL.Image` and `ITK` sounds better. `converter` should work in my case. I just wanted my transforms to generate something that is compatible with networks. Considering that almost all CNNs expect images of the same number of channels, it sounds almost trivial that load image transforms must return arrays with the same channel dimensions. Perhaps, you may want to consider making grayscale as default (assuming the most common use case would be 2D radiology images), as opposed to asking users to use a lambda function? Or at least, something straightforward, such as `LoadImage(flag="rgb")`,  `LoadImage(flag="gray")`, and `LoadImage(flag=None)` (preserving the original channel dimension for whatever reason), or something along that line. I don't know, just a suggestion. :) Thank you!

**Comment by aylward** [comment]
ITK allows you to specify the pixel type that you want returned by the reader.   It should be possible to pass this to through the MONAI API to the LoadImage function. 

The following demos this for a color RGB image - showing it being read as a greyscale or as a multi-channel image based on the arguments passed to itk.imread().

![RBG-Grey](https://user-images.githubusercontent.com/279727/102693774-fbf19b80-41ea-11eb-81f7-a5e9f6e7da6e.jpg)

**Comment by Nic-Ma** [comment]
Thanks @stephenbaek and @aylward for your suggestions, maybe IO working group can have a further discussion on it.

Thanks.
