### ISSUE TITLE
Quantitaive performance of DynUNet

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [Project-MONAI/MONAI#1396]
Hi,

may I ask if there is a quantitaive performance comparison between the DynUNet and the nnUNet? Thank you.

**Comment by Nic-Ma** [comment]
Hi @wyli and @ericspod ,

Could you please help share some information here?

Thanks in advance.

**Comment by ericspod** [comment]
I can't say myself anything about the two networks for performance, @wyli or @martaranzini or @irme might have some input.
