### ISSUE TITLE
Error in Compose of Array implementation of transforms (Spacing and Orientation)

### ISSUE THREAD

**Issue by architraj29** [Project-MONAI/MONAI#1400]
**Describe the bug**
Compose for Array implemented spacing transform and orientation transform are throwing error.
This is primarily due to the reason that implementation returns more than one output which doesn't work well as input for the next transform.

**To Reproduce**
Code to reproduce the error (the error exists in both MONAI 3.x and 4.x versions):
```
import os
import glob
import numpy as np
import torch
import monai
from monai.transforms import *
from monai.utils import first
root_data_path = '<data path>'
resample_spacing = [1.83723155, 1.83723155, 2.42438879]
patch_size=[128, 128, 128]
train_images = sorted(glob.glob(os.path.join(root_data_path, 'imagesTr', '*.nii.gz')))
train_labels = sorted(glob.glob(os.path.join(root_data_path, 'labelsTr', '*.nii.gz')))
train_image_transform = Compose(
                                [LoadNifti(),  
                                Spacing(resample_spacing, mode='bilinear'), 
                                Orientation(axcodes = "RAS"), 
                                ScaleIntensity(), 
                                AddChannel(), 
                                ToTensor()])
train_label_transform = Compose(
                                [LoadNifti(),  
                                Spacing(resample_spacing, mode='nearest'), 
                                Orientation(axcodes = "RAS"), 
                                AddChannel(), 
                                ToTensor()])
train_files = [{"image": img, "label": seg} for img, seg in zip(train_images, train_labels)]
ds = monai.data.ArrayDataset(img = train_images, img_transform = train_image_transform, seg = train_labels, seg_transform = train_label_transform)
train_ds = monai.data.GridPatchDataset(ds, patch_size = patch_size)
train_loader = torch.utils.data.DataLoader(train_ds, batch_size=2, num_workers=1, pin_memory=torch.cuda.is_available())
im, seg = first(train_loader)
```

**Expected behavior**
This should work seamlessly without throwing any errors. The same set of transform compose is working for dictionary implementation, but not for array implementation. 
This is because the dictionary implementation of [Spacingd](https://docs.monai.io/en/latest/_modules/monai/transforms/spatial/dictionary.html#Spacingd) and [Orientationd](https://docs.monai.io/en/latest/_modules/monai/transforms/spatial/dictionary.html#Orientationd) returns only one variable
While Array implementation of [Spacing](https://docs.monai.io/en/latest/_modules/monai/transforms/spatial/array.html#Spacing) and [Orientation ](https://docs.monai.io/en/latest/_modules/monai/transforms/spatial/array.html#Orientation) returns three arguments leading to the following error as could be seen in the screenshot below.

This required to primarily to generate patches for the datasets. I need to pass sliding window patches even during training as [RandSpatialCrop](https://docs.monai.io/en/latest/_modules/monai/transforms/croppad/array.html#RandSpatialCrop) or [RandCropByPosNegLabel](https://docs.monai.io/en/latest/_modules/monai/transforms/croppad/array.html#RandCropByPosNegLabel) are not performing that well for my problem.
I used the following code based on the tutorial for [patch generation](https://github.com/Project-MONAI/tutorials/blob/7e2ed50505178a0a6e3906fb9cbe4b300baa8635/modules/nifti_read_example.ipynb).

**Screenshots**
![image](https://user-images.githubusercontent.com/35004830/103277733-afc70800-49ef-11eb-9fd6-bde834ce1983.png)

![image](https://user-images.githubusercontent.com/35004830/103276528-d2a3ed00-49ec-11eb-8808-4b294a6b501d.png)

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 0.4.0
Numpy version: 1.19.4
Pytorch version: 1.7.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0563a4467fa602feca92d91c7f47261868d171a1

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: NOT INSTALLED or UNKNOWN VERSION.
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: NOT INSTALLED or UNKNOWN VERSION.
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75']
Info for GPU: 0
        Name: Quadro RTX 5000
        Is integrated: False
        Is multi GPU board: False
        Multi processor count: 48
        Total memory (GB): 15.7
        Cached memory (GB): 0.0
        Allocated memory (GB): 0.0
        CUDA capability (maj.min): 7.5
```

**Comment by Nic-Ma** [comment]
Hi @architraj29 ,

Thanks for your interest and experiments with MONAI.
Could you please help change to use `dict` data and transforms in your task?
The array transforms may be not suitable for your case.

Thanks.

**Comment by architraj29** [comment]
Hi @Nic-Ma 

Thanks for the quick response.
I am trying to use the [GridPatchDataset](https://docs.monai.io/en/latest/_modules/monai/data/grid_dataset.html#GridPatchDataset) Dataloader. 
It would be really helpful if you could share a code snippet on using the above function with `dict`

Thanks.

**Comment by Nic-Ma** [comment]
Hi @architraj29 ,

You are right, the `GridPatchDataset` can't support `dict` data so far, we may need to enhance it later.
For general Dataset, I think you can try below pseudo code:
```py
images = sorted(glob.glob(os.path.join(root_dir, "im*.nii.gz")))
segs = sorted(glob.glob(os.path.join(root_dir, "seg*.nii.gz")))
train_files = [{"img": img, "seg": seg} for img, seg in zip(images[:20], segs[:20])]

train_trans = Compose([
    LoadImaged(keys=["img", "seg"]),
    AddChanneld(keys=["img", "seg"]),
    ScaleIntensityd(keys=["img"]),
    ToTensord(keys=["img", "seg"]),
])
ds = Dataset(data=train_files, transform=train_trans)
dataloader = DataLoader(ds, ...)
```

If you must use `GridPatchDataset` and `Spacing` & `Orientation` transforms, you can define a simple function to execute transforms instead of `Compose` them:
```py
def exec_trans(data):
    img = LoadImage(image_only=True)(data)
    img = AddChannel()(img)
    img, affine = Spacing()(img)
    img = ScaleIntensity()(img)
    return img
...
```

Thanks.

Thanks.

**Comment by architraj29** [comment]
Hi @Nic-Ma,

Thanks for your suggestion! That is indeed a good work around for my problem.
I came across another issue while executing the Spacing APIs as suggested by you.

**Issue**
When using Spacing API, resampling is happening only in 2 dimension not in all 3 dimensions. I am not sure if this is by design or this a bug.
Given medical data are mostly 3D in nature (esp. MRI and CT) so resampling is required in all 3 dimensions.
While in affine x and y are getting modified but that change is visible in y and z component upon printing the size.

I have added a code snippet from MONAI for resampling and corresponding code snippet from Simple ITK, you can verify the change in the output from what is expected to what we observe in case of MONAI.
 
**To Reproduce**
Snippet 1: MONAI Spacing functionality
```
resample_spacing = [1.83723155, 1.83723155, 2.42438879]
patch_size=[128, 128, 128]
train_images = sorted(glob.glob(os.path.join(root_data_path, 'imagesTr', '*.nii.gz')))
train_labels = sorted(glob.glob(os.path.join(root_data_path, 'labelsTr', '*.nii.gz')))

original_img, meta = LoadImage()(train_images[:1])
resampled_img, source_affine, target_affine = Spacing(resample_spacing)(original_img, meta['affine'])
print ("Original Image Shape: ", original_img.shape, "\nResampled Image with input Affine Shape: ", resampled_img.shape)
print ("\nSource Affine:\n", source_affine, "\n\nTarget Affine:\n", target_affine)

resampled_img2, source_affine2, target_affine2 = Spacing(resample_spacing)(original_img)
print ("Original Image Shape: ", original_img.shape, "\nResampled Image without input Affine Shape: ", resampled_img2.shape)
print ("\nSource Affine:\n", source_affine2, "\n\nTarget Affine:\n", target_affine2)
```
Output: 
```
Original Image Shape:  (512, 512, 122)  
Resampled Image with input Affine Shape:  (512, 206, 49)

Source Affine:
 [[-0.736       0.          0.         -0.        ]
 [ 0.         -0.736       0.         -0.        ]
 [ 0.          0.          1.60000002  0.        ]
 [ 0.          0.          0.          1.        ]]

Target Affine:
 [[-1.83723155  0.          0.          0.        ]
 [ 0.         -1.83723155  0.          0.        ]
 [ 0.          0.          1.60000002  0.        ]
 [ 0.          0.          0.          1.        ]]

Original Image Shape:  (512, 512, 122)  
Resampled Image without input Affine Shape:  (512, 279, 67)

Source Affine:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Target Affine:
 [[1.83723155 0.         0.        ]
 [0.          1.83723155 0.        ]
 [0.          0.         1.        ]]
```

Snippet 2: Simple ITK Spacing functionality
```
import SimpleITK as sitk

original_img = sitk.ReadImage(train_images[:1][0])
input_size = np.asarray(original_img.GetSize())
input_spacing = np.asarray(original_img.GetSpacing())
expected_output_size = np.asarray(input_size*input_spacing/resample_spacing).astype(dtype = np.int64).tolist()

resampler = sitk.ResampleImageFilter()
resample.SetOutputDirection(original_img.GetDirection())
resample.SetOutputOrigin(original_img.GetOrigin())
resample.SetOutputDirection(original_img.GetDirection())
resample.SetSize(expected_output_size)
resampled_img = resample.Execute(original_img)
output_size = np.asarray(resampled_img.GetSize())
output_spacing = np.asarray(resampled_img.GetSpacing())

print ("Original Image Size: ", input_size)
print ("Original Image Spacing: ", input_spacing)
print ("Resampled Image Size: ", output_size)
print ("Resampled Image Spacing: ", output_spacing)

```
Output: 
```
Original Image Size:  [512 512 122]
Original Image Spacing:  [0.736      0.736      1.60000002]
Resampled Image Size:  [205 205  80]
Resampled Image Spacing:  [1.83723155 1.83723155 2.42438879]
```

As it can be seen from above that resampling is not as it should be considering ITK or Simple ITK as reference.
Please let me know if I have made any mistakes in calling the MONAI Spacing API.


Thanks.

**Comment by Nic-Ma** [comment]
Hi @architraj29 ,

Almost all the transforms in MONAI expect data shape `CHWD`, so you need to use `AddChannel` transform before `Spacing`.

Thanks.

**Comment by architraj29** [comment]
Thanks @Nic-Ma for all the clarifications provided. 
It was really helpful!

Cheers.
