### ISSUE TITLE
add image dissimilarity loss

### ISSUE THREAD

**Issue by YipengHu** [Project-MONAI/MONAI#1412]
**Is your feature request related to a problem? Please describe.**
Add image dissimilarity measure between a pair of 1D-3D images for registration.

Like deform loss, image loss is reasonably independent for starting to put these in first. It also makes sense to me to add the three "major" ones in one go: squared-difference, cross-correlation-based, mutual-information. 

Reference code:
https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/loss/image.py

@wyli @kate-sann5100 what do you think?

**Comment by kate-sann5100** [comment]
I can do that : )

**Comment by kate-sann5100** [comment]
The squared-difference is just the same as `nn.MSELoss`, do we want to implement that anyway?

**Comment by wyli** [comment]
> The squared-difference is just the same as `nn.MSELoss`, do we want to implement that anyway? @YipengHu @wyli

I feel NMI or LNCC is good enough, also I think we could aim at a working supervised workflow first, expand to more options later

**Comment by YipengHu** [comment]
> The squared-difference is just the same as `nn.MSELoss`, do we want to implement that anyway? @YipengHu @wyli

no - the MSELoss is adequate - just make sure it returns image-pair-wise losses before combined with other losses - it is not the default (see `reduction`)

**Comment by YipengHu** [comment]
> > The squared-difference is just the same as `nn.MSELoss`, do we want to implement that anyway? @YipengHu @wyli
> 
> I feel NMI or LNCC is good enough, also I think we could aim at a working supervised workflow first, expand to more options later

for CT images, believe it or not, sq-difference works really well ;)
