### ISSUE TITLE
Make `spatial_gradient` a transform

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#1417]
**Is your feature request related to a problem? Please describe.**
Being able to compute the spatial gradient of a tensor is an interesting self-contained feature. An nice implementation (from @kate-sann5100 ) is proposed in MONAI but is burried in the deformation loss code:
https://github.com/Project-MONAI/MONAI/blob/db7bf8984712f3e46ed533611a70c9b8cd0293bd/monai/losses/deform.py#L20-L44

This makes it harder to find, extend (e.g. with a Sobel kernel) and embed in other use cases.

Also, it is unclear why the current implementation relies on slicing rather than a simple convolution with a kernel of size 3( x 1s).

**Describe the solution you'd like**
Computing the spatial of a tensor should be easily available as a transform or similar. This is how Gaussian smoothing is available in MONAI:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/intensity/dictionary.py

**Describe alternatives you've considered**
Manually code the convolution kernels and operation for spatial gradients.

**Additional context**
Many application can use a simple central difference scheme but for others, it might be interesting to support other [derivative kernels](https://en.wikipedia.org/wiki/Image_derivatives), e.g.:
- Sobel
- [Gaussian derivative](https://itk.org/Doxygen/html/classitk_1_1DiscreteGaussianDerivativeImageFilter.html)
- etc

For all of this scenarios, a good handling of the border condition is important. Oftentime, central difference is replaced by forward/backward finite differences on the borders.

Additionally, understanding the performance implication of using a slicing based central difference versus an off the shelf convolution would be interesting.

Kornia can be used as an inspiration for this feature request:
https://github.com/kornia/kornia/blob/master/kornia/filters/sobel.py

**Comment by YipengHu** [comment]
sobel vs Gaussian der: with a kernel size of 3 has no difference? any larger kernel could be more expensive.
conv vs slicing: is a performance issue. I recall i did this comparison with tf1 with mixed results, but cpu conv was slower (may not be relevant). @tvercaut

**Comment by tvercaut** [comment]
Yes, Gaussian derivative is more costly but it can be useful in some use cases and the best trade-off is likely application-specific.

**Comment by wyli** [comment]
a related PR merged https://github.com/Project-MONAI/MONAI/issues/4997
