### ISSUE TITLE
release precompiled binaries

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1462]
the monai components implemented in c++/cuda are not enabled by default, and currently require a manual compilation step in the target environment. 

this ticket looks for precompiled wheels for some of the popular platforms (possibly delivered via github release asset https://docs.github.com/en/rest/reference/repos#upload-a-release-asset) so that the relevant users can download and use the components immediately

see also:
- github action release asset https://github.com/actions/upload-release-asset
- the docker image has the compiled components https://github.com/Project-MONAI/MONAI/blob/ec70d9637d7b3be4b3266c0060df25d08e0b6ecd/Dockerfile#L31-L36

**Comment by vikashg** [comment]
completed so closing.
