### ISSUE TITLE
Re-order tests directory

### ISSUE THREAD

**Issue by madil90** [Project-MONAI/MONAI#147]
**Tests directory is getting very big and needs structure.**

**Solution 1:** Tests should follow same structure as the monai src directory.

**Alternative:** Alternative is tests can follow structure of exported methods instead of original src.

**Comment by madil90** [comment]
@wyli @ericspod what are your thoughts?

**Comment by wyli** [comment]
sure we can use the monai/ folder structure for tests/   need to make sure runtest.sh still works after rearranging https://github.com/Project-MONAI/MONAI/blob/master/runtests.sh
