### ISSUE TITLE
TorchScript can't work for AHNet when num_psp=0

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1478]
**Describe the bug**
When set num_psp=0 in AHNet, can't use TorchScript to export the model:
```
RuntimeError: 
Module 'AHNet' has no attribute 'psp' :
  File "/workspace/data/medical/MONAI/monai/networks/nets/ahnet.py", line 514
        d4 = self.dense4(sum4)
        if self.psp_block_num > 0:
            psp = self.psp(d4)
                  ~~~~~~~~ <--- HERE
            x = torch.cat((psp, d4), dim=1)
        else:
```

**Comment by wyli** [comment]
this is still an issue on torch 1.5.0 according to the cron test: https://github.com/Project-MONAI/MONAI/runs/1766459392?check_suite_focus=true#step:5:11867

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this up.
I am curious that we have CI test against PyTorch 1.5 and the tests passed in that PR, what's the difference between the PyTorch 1.5 CI test for PR and the cron test?

Thanks.

**Comment by wyli** [comment]
yes this needs some investigations, cron test is defined here: https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/cron.yml#L16 PR test defined here: https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/pythonapp.yml#L159

**Comment by Nic-Ma** [comment]
Hi @madil90 ,

My previous PR already fixed the TorchScript issue in AHNet with `num_psp_block=0`, and all the CI tests on that PR passed on PyTorch versions. But don't know why the CRON periodical tests failed on PyTorch 1.5...
Did you find any more clues about this bug? And could you please help take look at this ticket?
Maybe you can reproduce the issue locally or update the CICD pipeline.

Thanks in advance.
