### ISSUE TITLE
Paired Dataset

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/MONAI#1487]
**Is your feature request related to a problem? Please describe.**
Current datasets do not support paired input. 

**Describe the solution you'd like**
Build a PairedDataset Object.

**Describe alternatives you've considered**
N/A

**Additional context**
[DeepReg paired dataloading](https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/loader/paired_loader.py)

**Comment by wyli** [comment]
I think this is addressed by providing a demo in https://github.com/Project-MONAI/tutorials/pull/116?
