### ISSUE TITLE
cancel the previous CI/CD unfinished tests if a pull request updated

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1501]
every commit to an existing pull request will create a new set of ci/cd jobs. but normally we just wanted to test the branch's latest version. Any unfinished previous testing jobs could be cancelled immediately when a pull request updated. This will release self-hosted machine resources and improve the overall dev efficiency 

perhaps could use this https://github.com/styfle/cancel-workflow-action

mainly for the per PR self-hosted job: https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/pythonapp.yml#L154

**Comment by rijobro** [comment]
definitely a great thing to sort out!

**Comment by wyli** [comment]
#1502 doesn't work from a forked repo, I'm reopening this ticket
