### ISSUE TITLE
Option to restart certain github workflows?

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1507]
Sometimes a github workflow will fail for an unrelated issue, see: https://github.com/Project-MONAI/MONAI/pull/1454/checks?check_run_id=1768474379.

It would be great if there was a way to restart just a single workflow. I think currently the only way to re-trigger the workflows is to push to the PR. That would restart **all** workflows, which is obviously wasteful.

**Comment by rijobro** [comment]
Think this might only be solvable with an upstream fix: https://github.community/t/manually-restart-actions-and-entire-workflows/16262. Is that correct?

**Comment by wyli** [comment]
> Think this might only be solvable with an upstream fix: https://github.community/t/manually-restart-actions-and-entire-workflows/16262. Is that correct?

yes, I feel there is not much we could do from our side... I'm closing this for now
