### ISSUE TITLE
Shape mismatch ValueError when using RandGaussianNoised with more than one key

### ISSUE THREAD

**Issue by LucasFidon** [Project-MONAI/MONAI#1512]
**Describe the bug**
When using RandGaussianNoised during training with more than one key the error "ValueError: shape mismatch: objects cannot be broadcast to a single shape" is returned.

**To Reproduce**
I have encountered the error when using RandGaussianNoised in my training pipeline for BraTS.

I have in my composition of training transforms:
`RandGaussianNoised(keys=["flair", "t1", "t1ce", "t2"], mean=0., std=0.1, prob=0.15),`

For this example, in https://github.com/Project-MONAI/MONAI/blob/8207e1e2a3555ddc3fe938e058552651900dc951/monai/transforms/intensity/dictionary.py#L113
we obtain `self.mean = (0.,0,0,0)`.

This creates a mismatch between the shape of `self.mean` and `im_shape` in https://github.com/Project-MONAI/MONAI/blob/8207e1e2a3555ddc3fe938e058552651900dc951/monai/transforms/intensity/dictionary.py#L120
where `im_shape=(1,128,128,128)`.

**A Simple Solution**
By replacing https://github.com/Project-MONAI/MONAI/blob/8207e1e2a3555ddc3fe938e058552651900dc951/monai/transforms/intensity/dictionary.py#L113
by `self.mean = mean` the error does not appear anymore.

**Expected behavior**
The reason why the tests pass with the current version of the code is that the test https://github.com/Project-MONAI/MONAI/blob/master/tests/test_rand_gaussian_noised.py only contains examples with `len(keys)==1`.

In addition, in https://github.com/Project-MONAI/MONAI/blob/8207e1e2a3555ddc3fe938e058552651900dc951/monai/transforms/intensity/dictionary.py#L131-L133
the same sample of Gaussian noise is used for all the keys.
I would have expected that different noise samples would be used with different keys.
Is it the intended behavior for this transformation?

I can work on a pull request if you can confirm which behavior you would like to see here.

Thank you,
Lucas

**Comment by saruarlive** [comment]
@LucasFidon,
Based on the bug, so it handles a single dictionary key, right!
If you stack ["flair", "t1", "t1ce", "t2"] images in one tensor, (4, :, : , : ) before, then use the RandGaussianNoised class using one dictionary key, does it raise error then?

**Comment by LucasFidon** [comment]
Hi @saruarlive 
Yes, that seems to be a good workaround.
But I suppose RandGaussianNoised is intended to work with any number of keys so that that does not solve the issue.
