### ISSUE TITLE
MaskIntensityD to support user-specified data field

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1520]
**Describe the bug**
MaskIntensityD supports to use numpy array as a constructor argument for the mask array,
but one of the common use cases is to dynamically set the mask array from a user-specified data key

https://github.com/Project-MONAI/MONAI/blob/50c46597d13c9c44501e60cad0e5cd65c2db7642/monai/transforms/intensity/dictionary.py#L470-L485

**Expected behavior**
the transform should support:
`def __init__(self, keys: KeysCollection, mask_keys: KeysCollection)` where `data[mask_keys]` will be used as the masking array

**Comment by Nic-Ma** [comment]
Good suggestion. I will update it soon.
Thanks for raising it up.
