### ISSUE TITLE
multiscale segmentation loss API

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1525]
**Is your feature request related to a problem? Please describe.**
this ticket looks for a generic wrapper API to compute a given segmentation loss at multiple visual scales. the API should be compatible with the existing single-scale segmentation loss in monai

see also:
deepreg example: https://github.com/DeepRegNet/DeepReg/blob/a182f9d86fbd1ff9e392c511ff89403971be6454/deepreg/loss/label.py#L42-L47

**Comment by kate-sann5100** [comment]
If no one is already implementing this, I would be happy to implement. @wyli @Nic-Ma
