### ISSUE TITLE
'DiceCELoss' object is not callable

### ISSUE THREAD

**Issue by PouriaRouzrokh** [Project-MONAI/MONAI#1526]
Hello.
It seems that there is a bug in calling a DiceCELoss object in the training loop. 
The following code will fail with this error: "TypeError: 'DiceCELoss' object is not callable"

```
loss_function = monai.losses.DiceCELoss() # before the training
# ....
loss = loss_function(outputs, labels) # in the training loop
```
I have installed MONAI from git and the same code works if I simply call DiceLoss instead of DiceCELoss.

**Comment by wyli** [comment]
thanks for reporting this!
