### ISSUE TITLE
static type checks fail since numpy 1.20

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1534]
the recent numpy update (https://github.com/numpy/numpy/releases/tag/v1.20.0) breaks the pull request's type checks https://github.com/Project-MONAI/MONAI/pull/1532/checks?check_run_id=1807350179#step:7:284

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Maybe let fix the numpy version?
I don't see any feature requirements for a newer numpy so far.

Thanks.

**Comment by wyli** [comment]
many of the errors are actually valid points, I'll create a PR on those first
