### ISSUE TITLE
ImageDataset import

### ISSUE THREAD

**Issue by chrisfoulon** [Project-MONAI/MONAI#1543]
Hi! 
I'm trying to use the tutorials for 3d_segmentation (tutorials/3d_segmentation/torch/unet_training_array.py) and 
`from monai.data import ImageDataset` does not work and returns: 
`cannot import name 'ImageDataset' from 'monai.data'`

To be sure I used 
`pip install monai --upgrade`
but I already had the 0.4.0 version 
I'm using python 3.7

**Comment by rijobro** [comment]
Hi, give `pip install monai-weekly` a go, and if that doesn't work we can check through the git blame and figure out when `ImageDataset` was added/last modified.

If it doesn't work, can you paste the output of:

```
import monai
monai.config.print_config()
```

**Comment by Nic-Ma** [comment]
Hi @chrisfoulon ，

Another solution is to use the `tutorials` with 0.4 tag instead of the latest master branch as you are using MONAI v0.4:
https://github.com/Project-MONAI/tutorials/tree/0.4.0

Thanks.

**Comment by chrisfoulon** [comment]
Thank you very much for your quick answers! I used the 0.4.0 tag with the NiftiDataset instead and that worked!
