### ISSUE TITLE
Add DeleteChannelD inverse equivalent of RepeatChannelD

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1567]
In the liver and tumor segmentation model, it's possible to approximate the Brain Segmentation workflow with RepeatChannelD to enable usage of ConvertToMultiChannelBasedOnBratsClassesd. However this results in greater, unnecessary memory usage.

Adding a DeleteChannelD transform would allow the duplicated channels to be pared down before feeding into the network.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this, I think Tam is working on the PR to address it: https://github.com/Project-MONAI/MONAI/pull/1569.

**Comment by wyli** [comment]
sure, he created this issue originally, I just copied the content here
