### ISSUE TITLE
some classes are missing from the autogenerated API docs

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#157]
**Describe the bug**
the autogenerated API docs don't show all the classes defined in monai codebase

**To Reproduce**
visit https://monai.readthedocs.io/en/latest/apidocs/monai.transforms.html#monai-transforms-package

**Expected behavior**
list all class interfaces such as `AddChannel` defined here:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/transforms.py#L30

**Comment by Nic-Ma** [comment]
And I found the doc-string format is changed in web page:
![image](https://user-images.githubusercontent.com/27533405/76166455-a5eec280-6199-11ea-8022-68eb3cd65171.png)
Expected to be:
![image](https://user-images.githubusercontent.com/27533405/76166480-ccacf900-6199-11ea-8db2-c83f8779bfcd.png)

**Comment by wyli** [comment]
@Nic-Ma I think that is a separate docstring style issue

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/158

all docstrings need to be checked to address the formatting style issue.
