### ISSUE TITLE
Add SaveNifti transform to debug transform chain

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1575]
**Is your feature request related to a problem? Please describe.**
Need to add a SaveNifti transform based on the NiftiSaver for debug purpose. May also add SavePNG transform.

**Comment by rijobro** [comment]
Should it be `SaveImage` to mirror `LoadImage`? You could then specify the writer by argument (e.g., `Nifti` and `PNG`).

**Comment by Nic-Ma** [comment]
@rijobro ，

Ideally, it should be `SaveImage`, I am afraid maybe we can't implement it very well, anyway I can have a try later.
Or do you have interest to implement a `SaveImage` transform based on our NiftiSaver and PNGSaver?

Thanks.

**Comment by rijobro** [comment]
Ok, if it's not easy then it's not a high priority. I just thought I would suggest it in case it would save you having to refactor later on.
