### ISSUE TITLE
initial contribution guidelines documentation

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#16]

**Comment by atbenmurray** [comment]
Copying in your original email for completeness; hope that's ok

Hi Ben,
This item was assigned to you and me. I thought that you have done some work along this line, do you mind finishing it up? I’ll be happy to review after that.

Let me know if this is okay with you.

Thanks,
Yan

**Comment by atbenmurray** [comment]
Yep, I'm happy to do that if you want to do the heavy lifting on the documentation

**Comment by pdogra89** [comment]
Guidelines to write unite tests should be part of guidelines. The mechanism for unit tests should be clearly communicated.
