### ISSUE TITLE
update itk requirement to >= 5.2

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1629]
once itk 5.2 is released, requirements.txt needs to be updated and the warning message removed. 

this is a follow up of 
- https://github.com/Project-MONAI/MONAI/issues/1451 
- https://github.com/Project-MONAI/MONAI/pull/1602
- https://github.com/Project-MONAI/MONAI/issues/1357#issuecomment-777055428
- https://github.com/Project-MONAI/MONAI/issues/1713

see also:
https://github.com/InsightSoftwareConsortium/ITK/tags

**Comment by wyli** [comment]
itk 5.2.0 has been released, it is causing some issues:
for example to replicate this (with monai da3240f60c98fee2e067337d388f492e5f1d6692):
```bash
docker run --gpus all --rm -ti --ipc=host --net=host -v ~/Documents/MONAI:/opt/monai nvcr.io/nvidia/pytorch:20.03-py3
# within the docker container run:
python -m pip install --upgrade pip wheel
python -m pip uninstall -y torch torchvision
python -m pip install torch==1.7.1 torchvision==0.8.2
python -m pip install -r requirements-dev.txt
```

outcome:
```
/opt/monai# python -m tests.test_distributed_sampler                                          
/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
./opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
.
----------------------------------------------------------------------
Ran 2 tests in 12.074s

OK

```
example log: https://github.com/Project-MONAI/MONAI/runs/2266945686?check_suite_focus=true
eventually the integration tests become very slow with `UserWarning: semaphore_tracker:`

I had a quick look, the same code works fine with itk 5.1.2. so I suspect it's an issue in the way MONAI using itk

any idea @thewtex ?

**Comment by wyli** [comment]
a smaller example to reproduce (python3 + linux + pytorch 1.7/1.8):
```python
from torch import multiprocessing

try:
    multiprocessing.set_start_method("spawn")
except RuntimeError:
    pass

import itk
import torch

if __name__ == "__main__":
    for d in torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4):
        pass
```
this works fine with itk 5.1.2 but has the warnings with itk5.2.0

perhaps this global RLock is causing the issue https://github.com/InsightSoftwareConsortium/ITK/blob/6dfbc9f0314b5fd64d4b2ae392ae3cc6dda17677/Wrapping/Generators/Python/itk/support/lazy.py#L29

**Comment by thewtex** [comment]
@wyli thanks for the detailed, reproducible report :1st_place_medal: 

I verified that this patch addresses the issue:

https://github.com/InsightSoftwareConsortium/ITK/pull/2552

**Comment by thewtex** [comment]
@wyli this has been addressed in `itk-5.2.0.post3`.

I will help with the remaining issues based on this package in the coming month.

**Comment by wyli** [comment]
thanks @thewtex!

**Comment by wyli** [comment]
it still gives the warning:
```
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 33 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

https://github.com/Project-MONAI/MONAI/runs/2728004520?check_suite_focus=true#step:7:2534
using 5.2.0.post3 PR here: https://github.com/Project-MONAI/MONAI/pull/2274

**Comment by thewtex** [comment]
@wyli thanks for the report. We will keep pushing on this! Tracked in https://github.com/InsightSoftwareConsortium/ITK/issues/2603

**Comment by thewtex** [comment]
Following-up: `itk-5.2.1` contains additional improvements.
