### ISSUE TITLE
DICOM loader

### ISSUE THREAD

**Issue by JumpLK** [Project-MONAI/MONAI#1646]
**Describe the bug**
I am trying to load a list of DICOM images and stack them as 1 training item.
This data are from an open IRCAD dataset available here : https://www.ircad.fr/fr/recherche/3d-ircadb-01-fr/

The problem is that for these data, the slice location is set by a z translation in the affine matrix. Because of that the affine matrix is different for each slice and that isn't allowed by monai's image loader.

**To Reproduce**
1. Download the IRCAD dataset from https://www.ircad.fr/fr/recherche/3d-ircadb-01-fr/
2. Unzip the dataset
3. Run this python script where you unziped the dataset :

import glob
import os
from monai.transforms import LoadImage

ircad_dir = "./"
dicoms = glob.glob(os.path.join(ircad_dir, r"3Dircadb1.1\PATIENT_DICOM", "*"))
data, meta = LoadImage()(dicoms)

**Expected behavior**
The data loader should load the data despite that the affine matrix have different term for the z translation

**Screenshots**
![Capture](https://user-images.githubusercontent.com/44983802/109143154-ff138580-775f-11eb-984b-8ea2a31c69b3.PNG)
![Capture2](https://user-images.githubusercontent.com/44983802/109143180-05096680-7760-11eb-8f82-19269f2feaf4.PNG)

**Environment**
================================
Printing MONAI config...
================================
MONAI version: 0.4.0
Numpy version: 1.19.2
Pytorch version: 1.7.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0563a4467fa602feca92d91c7f47261868d171a1

Optional dependencies:
Pytorch Ignite version: 0.4.2
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.1.0
Tensorboard version: 2.4.1
gdown version: 3.12.2
TorchVision version: 0.8.2
ITK version: 5.1.2
tqdm version: 4.56.0
lmdb version: 1.1.1
psutil version: 5.8.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Win32 edition: Core
Platform: Windows-10-10.0.18362-SP0
Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Machine: AMD64
Python version: 3.8.5
Process name: python.exe
Command: ['C:\\Users\\Camille\\anaconda3\\envs\\kitware\\python.exe', 'c:\\Users\\Camille\\Desktop\\important\\Kitware\\liver-segmentation\\datas\\data_ircad\\ticket.py']
Open files: [popenfile(path='C:\\Program Files\\WindowsApps\\Microsoft.LanguageExperiencePackfr-FR_18362.35.108.0_neutral__8wekyb3d8bbwe\\Windows\\System32\\fr-FR\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Program Files\\WindowsApps\\Microsoft.LanguageExperiencePackfr-FR_18362.35.108.0_neutral__8wekyb3d8bbwe\\Windows\\System32\\fr-FR\\kernel32.dll.mui', fd=-1)]
Num physical CPUs: 6
Num logical CPUs: 12
Num usable CPUs: 12
CPU usage (%): [35.8, 7.8, 33.9, 12.7, 29.0, 6.3, 19.0, 8.1, 3.2, 8.1, 11.1, 61.3]
CPU freq. (MHz): 2208
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 79.0
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 15.9
Available memory (GB): 8.1
Used memory (GB): 7.8

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'compute_37']
Info for GPU: 0
        Name: GeForce GTX 1070 with Max-Q Design
        Is integrated: False
        Is multi GPU board: False
        Multi processor count: 16
        Total memory (GB): 8.0
        Cached memory (GB): 0.0
        Allocated memory (GB): 0.0
        CUDA capability (maj.min): 6.1

**Comment by rijobro** [comment]
For DICOMs, best to give the containing folder: `LoadImage()("PATIENT_DICOM")`. This works fine for me using the dataset you linked above.

**Comment by JumpLK** [comment]
> For DICOMs, best to give the containing folder: `LoadImage()("PATIENT_DICOM")`. This works fine for me using the dataset you linked above.

Thank you for your fast answer, it works for me too.

**Comment by digernes** [comment]
Nice! I had the same problem. 

Perhaps show an example in the load medical images tutorial that it's possible to just give the containing folder. https://github.com/Project-MONAI/tutorials/blob/master/modules/load_medical_images.ipynb 

Right now it's only showing an example giving a list of files.
