### ISSUE TITLE
global net

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/MONAI#1651]
**Is your feature request related to a problem? Please describe.**
The current repository does not include global net model which is useful for image registration.

**Describe the solution you'd like**
Add global net.

**Describe alternatives you've considered**
N/A

**Additional context**
DeepReg implementation of [global net](https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/backbone/global_net.py)

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/1729
