### ISSUE TITLE
AttributeError: module 'monai.visualize' has no attribute 'OcclusionSensitivity'

### ISSUE THREAD

**Issue by kapsner** [Project-MONAI/MONAI#1655]
**Describe the bug**

When importing the class `monai.visualize.OcclusionSensitivity` (as described in [this notebook](https://github.com/Project-MONAI/tutorials/blob/master/modules/interpretability/class_lung_lesion.ipynb)) the following error is thrown:
>AttributeError: module 'monai.visualize' has no attribute 'OcclusionSensitivity'

**To Reproduce**

```python
import monai
occ_sens = monai.visualize.OcclusionSensitivity(
    nn_module=model_3d, mask_size=12, n_batch=1, stride=28
)
```
**Expected behavior**
The error should not occur when importing `monai.visualize.OcclusionSensitivity`

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 0.4.0
Numpy version: 1.19.2
Pytorch version: 1.7.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0563a4467fa602feca92d91c7f47261868d171a1

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.1.0
Tensorboard version: 2.4.1
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.8.2
ITK version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.51.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 0
Has CUDA: False
cuDNN enabled: True
cuDNN version: 7605
```

**Comment by wyli** [comment]
thanks for reporting! please install monai-weekly preview for this latest feature https://docs.monai.io/en/latest/installation.html#weekly-preview-release

otherwise the corresponding tutorial for MONAI v0.4.0 is available here https://github.com/Project-MONAI/tutorials/tree/0.4.0

**Comment by kapsner** [comment]
@wyli thx for your answer. Sry, my fault - did oversee that I was reading the 'latest' api docs (not 0.4.0).
