### ISSUE TITLE
Adjust LocalNet

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/MONAI#1665]
**Is your feature request related to a problem? Please describe.**
To evaluate our performance by comparing with DeepReg, we want to align our LocalNet architecture with DeepReg's.

**Describe the solution you'd like**
Reimplement LocalNet

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/pull/1752
