### ISSUE TITLE
Add AutoAdjustChannel transform

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1673]
**Is your feature request related to a problem? Please describe.**
Now we have `AddChannel` and `AsChannelFirst` transforms, need users to manually select expected transform to convert their data to be "channel-first". Several internal researchers got confused by the wrong transform, especially when their `image` and `label` have different shapes(maybe `image` is 3 channels data and channel last, `label` is single channel data and doesn't have channel dim).
Actually, we can automatically adjust channel dim for most cases based on the `spatial_size` from meta_data. If advanced users really want to do some special logic, they can use `AddChannel` and `AsChannelFirst` directly.

**Comment by rijobro** [comment]
So always assume that the channel dimension is smaller than all the other dimensions? That seems like a reasonable assumption most of the time!

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Thanks for your comments.
I submitted a PR https://github.com/Project-MONAI/MONAI/pull/1675 to address this ticket, will finish it soon.
Actually,  all the existing `image_readers` expect the image to be `channel_last` or `no channel`, so I just added a meta info and then automatically adjust the channel dim based on it.

Thanks.

**Comment by rijobro** [comment]
Ok, do you think the inverse is trivial? I guess it would only require knowing which dimension was the original channel.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Yes, because all the data in MONAI should be `channel_first` and you can get the `original_channel_dim` from meta dict. Then I think you can restore the original channel dim or remove channel dim, right?

Thanks.

**Comment by rijobro** [comment]
Perfect, thanks!
