### ISSUE TITLE
SmartCachedDataset unittest failed: "isAlive" field missing from threading is missing

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#1674]
Hi,
When running the unittest script of SmartCachedDataset I get the same error message as with my training script on `dataset.update_cache()`
```
self._replace_mgr.isAlive()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'Thread' object has no attribute 'isAlive'
```
Debugging into dataset.py>SmartCacheDataset(class)>update_cache(def) this error originates from
```
        if not self._replace_mgr.isAlive():
            self._restart()
```
![image](https://user-images.githubusercontent.com/10415569/109606237-cc8ed180-7b3f-11eb-8189-639071022bb2.png)
Is there an issue with the "threading" library as the field "isAlive" isn't present (anymore?)

**Comment by bartmch** [comment]
Found the issue following the hint in [this StackOverflow post](https://stackoverflow.com/questions/65021939/error-gcloud-crashed-attributeerror-thread-object-has-no-attribute-isaliv). My Python version 3.9 is too new. Reverted to python 3.8.5 and I'm not getting the error again. I'm getting a warning though:
![image](https://user-images.githubusercontent.com/10415569/109607226-5c814b00-7b41-11eb-98c6-268b5687eba1.png)

**Comment by rijobro** [comment]
Glad you managed to solve your problem. Just so that you know, the master branch of MONAI was updated a month ago to change `isAlive` to `is_alive`. So switching to a more recent version of MONAI (e.g., weekly or master) would remove this warning.
