### ISSUE TITLE
in write_nifti an additional dimension is added to the output image

### ISSUE THREAD

**Issue by michalhg** [Project-MONAI/MONAI#1677]
In the write_nifti function that exports the 3D segmentation prediction to a nifty image file, and addition dimension is added (either for channel or batch) which makes it unreadable using ITK-SNAP or Slicer.
I propose the following solution 

 results_img = nib.Nifti1Image(data.squeeze().astype(output_dtype), to_affine_nd(3, target_affine)) # squeeze channel dim

for row 105 in row nifty_writer.py file.

**Comment by rijobro** [comment]
Hi @michalhg, have you looked into `NiftiSaver`, which has the `save_batch` method?

**Comment by rijobro** [comment]
Or if you also want to remove the channel dimension, how about `Compose([SquezeDim, SaveImage])`?

**Comment by michalhg** [comment]
I am using save_batch, but in the end it calls write_nifti without removing the channel dim. 
regarding your solution, should I avoid save_batch, and just call Compose([SquezeDim, SaveImage]) ?

**Comment by rijobro** [comment]
Hi, I looked into this a bit more today, and have suggested [this PR](https://github.com/Project-MONAI/MONAI/pull/1680), allowing the user to squeeze any trailing singleton dimensions, being the channel dimension in your case.

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/pull/1680
