### ISSUE TITLE
Affined is missing

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1704]
**Is your feature request related to a problem? Please describe.**
`Affine` and `RandAffine` exist, but on the dictionary side, there is `RandAffined`, but no `Affined`.

**Describe the solution you'd like**
Add `Affined`.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Thanks for raising this ticket.
I can add the dictionary version `Affined` transform later.

Thanks.
