### ISSUE TITLE
openslide reader not tested/integrated into docker image

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1721]
**Describe the bug**
the openslide installation steps are currently not implemented in the testing and docker building pipelines
https://github.com/Project-MONAI/MONAI/runs/2058917545?check_suite_focus=true#step:10:5509

need to follow https://github.com/openslide/openslide-python#installation

**Comment by wyli** [comment]
need at least `apt-get install python3-openslide` before running any python code. the command might be too heavy to run for each PR commit, but probably need for the nightly test and the dockerfile cc @behxyz @Nic-Ma what do you think?

**Comment by behxyz** [comment]
@wyli, I agree! It's too heavy for each PR and also it requires to configure `tzdata` if it is not already configured on the docker container. Nightly tests only seems to be a fair compromise. Also `apt-get install libopenslide0` has less dependencies than `pytho3-openslide` and should suffice our purposes.

**Comment by behxyz** [comment]
OR we can create another docker image on top of `nvcr.io/nvidia/pytorch:20.03-py3` with all these system dependencies installed, and just install python libraries each time.
