### ISSUE TITLE
Add inverse kwargs

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1748]
If cropping, the inverse is padding. There are multiple options for padding, such as the values used for the padding (constant, reflection, etc.). We should therefore allow the user to parameterise the inverse method. This would be easiest using a dictionary that is only used for the inverse; something like `**inv_kwargs`.

follow-up of #1515

**Comment by wyli** [comment]
this feature request becomes less clear after introducing the metatensor data structure. closing it for now.
