### ISSUE TITLE
Move inverse methods to array classes

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1749]
Inverse methods currently sit in the dictionary transforms. This is because we ideally need the dictionary so that we can keep a track of the applied transforms to be able to apply the inverse in the correct order. 

However, there's no reason that the inverse can't live inside the array class, and each dictionary class calls its relevant inverse.

follow-up of https://github.com/Project-MONAI/MONAI/issues/1515

**Comment by wyli** [comment]
thanks, this feature is now on the dev branch.
