### ISSUE TITLE
add support for dynamic data type in transforms

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#175]
**Is your feature request related to a problem? Please describe.**
Need to make all transforms more flexible to handle different data types.

**Comment by wyli** [comment]
closing this in favour of https://github.com/Project-MONAI/MONAI/issues/2231, see also https://github.com/Project-MONAI/MONAI/blob/8651b622df76b75a9477538e985a14896f827150/monai/utils/type_conversion.py#L26-L36
