### ISSUE TITLE
update to use ignite 0.4.4

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1756]
**Is your feature request related to a problem? Please describe.**
there're some enhancements since 0.4.2 based on monai's feedback.
shall we use the latest for monai v0.5 @Nic-Ma?

https://github.com/pytorch/ignite/releases

**Comment by danieltudosiu** [comment]
It might not be my place, but wouldn't it be a good idea for Monai to sync with Ignite's major and minor version?

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

I submitted several PRs to ignite for MONAI features, so maybe it's better to update the ignite dependency.

Thanks.
