### ISSUE TITLE
Continue training past checkpoint's max epochs

### ISSUE THREAD

**Issue by danieltudosiu** [Project-MONAI/MONAI#1757]
**Is your feature request related to a problem? Please describe.**
Currently, there is no clean way, to continue training past its initial epochs due to the fact that the state of the trained is being loaded by CheckpointLoader.

**Describe the solution you'd like**
A quick solution would be to assume that if this case appears the code of the user will account for those things (aka just gamma decay, etc) and the CheckpointLoader should only modify the max_epochs after loading the checkpoint data and issue a Warning through a logger.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

Thanks for your interest here.
I think you want to continue training from the previous epoch?
You can save the trainer as an item in `CheckpointSaver`:
https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/checkpoint_saver.py#L38
ignite Engine can be part of checkpoint.

Thanks.

**Comment by danieltudosiu** [comment]
Hi Nic,

Yes, but the issue is that a proper checkpoint (aka, one that also saves the trainer state) when loaded it will also set max_epochs. 

If, for example, one prototype is trained for X epochs and a model works well and should be further trained until Y epochs where Y > X this won't be possible due to the trainer state being loaded and overwriting Y with the value of X.

Does that make sense :-?

**Comment by Nic-Ma** [comment]
Oh, I see.
@vfdev-5 , I think this may be a feature request for ignite directly? Could you please help share some comments?

Thanks in advance.

**Comment by vfdev-5** [comment]
Thanks for mentioning @Nic-Ma ! We will be happy to address this feature in ignite directly. I'm just trying to understand better to idea.

> If, for example, one prototype is trained for X epochs and a model works well and should be further trained until Y epochs where Y > X this won't be possible due to the trainer state being loaded and overwriting Y with the value of X.

@danieltudosiu could you please detail your idea with a small code snippet if possible. I was thinking that in ignite we can simply continue the training when we set `max_epoch` arg of `Engine.run` to a larger value than the one in the state...

**Comment by danieltudosiu** [comment]
@vfdev-5 you are right, we can just manually set the max_epoch in Engine.state. 

The problem arises when one automates the checkpoint loading via the MONAI's [CheckpointLoader](https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/checkpoint_loader.py#L27) since now the checkpoint loading will happen at training start [inside the handler](https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/checkpoint_loader.py#L83). The solution would be to scan the self.load_dict of CheckpotLoader for an engine (running under the assumption it is the trainer) and have another argument in the constructor of CheckpoitLoader called max_epochs that will overwrite the max_epochs of the Engine found in the self.load_dict.

Sadly this is not the cleanest solution, but since MONAI gives a user a checkpoint loading handler it should also handle any possible reparametrization that is likely to happen, such as manually increasing the max_epoch.

What is your take on this @vfdev-5 from an Ignite design paradigm? Also, this should be a quick enhancement that can be squeezed in MONAI 0.5, right @Nic-Ma?

**Comment by vfdev-5** [comment]
@danieltudosiu thanks for details, I think I start to understand the problem you are facing.

In Ignite currently we have the following to continue the training:
```python
# (re)start from 0 to 5
engine.run(data, max_epochs=5) -> Engine run starting with max_epochs=5 => state.epoch=5

# continue from 5 to 7
engine.run(data, max_epochs=7) -> Engine run resuming from epoch 5 until 7 epochs => state.epoch=7

# error
engine.run(data, max_epochs=4) -> ValueError: Argument max_epochs should be larger than the start epoch

# forced restart from 0 to 5
# This is subject to change in the future versions
engine.state.max_epochs = None
engine.run(data, max_epochs=5) -> Engine run starting with max_epochs=5 => state.epoch=5
```

Together with ignite's `Checkpoint`, it should for as here: https://github.com/pytorch/ignite/blob/bd4ea8926a405ae06e971ed577602d48bbe3cc24/examples/contrib/cifar10/main.py#L343-L349
which loads the state before running the engine. Then if we set `max_epochs` larger to the one from the saved state engine will run.

In MONAI case, I agree that we need some lazy `max_epochs` setup before loading the state with `CheckpointLoader`. This could be probably hacked internally while loading: to set up max `max_epochs` of current state and `max_epochs` from the state_dict.

**Comment by danieltudosiu** [comment]
Yes, basically a max_epochs set after [this line](https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/checkpoint_loader.py#L83) would do the trick.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 and @danieltudosiu ,

Thanks for the interesting discussion, I will take a look at this feature request soon.

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu and @vfdev-5 ,

I checked this source of ignite engine, I think the best approach is to add the arg `overwrite_max_epochs` in engine.
Then optionally load the value for `max_epochs` here:
https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L538
What do you think?

Thanks.

**Comment by danieltudosiu** [comment]
Hi @Nic-Ma,

I do not think it is a good idea to modify the load_state method as it modifies the expected behavior of such a method and might not fall in line with the PyTorch way. But you and @vfdev-5  are more experienced in this than I.  

My recommendation would be to be integrated in the MONAI checkpoint loader after this line here:
https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/checkpoint_loader.py#L83

The reason is that MONAI wants to deliver a CheckpointLoader Handler while did not do it (either by choice or priority management). Following ignite's tutorials and usual rules of thumbs allows the MONAI codebase to be aligned to already ingrained Ignite paradigms which should make the adoption smoother and faster.

Please keep in mind I am talking from more of a theoretical POV as I do not have practical experience in developing a package.

Cheers!

**Comment by vfdev-5** [comment]
@Nic-Ma I'm not sure to understand where you would like to add `overwrite_max_epochs` ? Thinking more about the loading engine state while it is already running seem not to be a good idea in general. I understand how you are doing things and it is OK.

I also agree with @danieltudosiu on above points.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

OK, so what's your proposal for this ticket?

Thanks.

**Comment by vfdev-5** [comment]
As @danieltudosiu suggested, we can modify `CheckpointLoader`
```python
class CheckpointLoader:
    ....

    def __call__(self, engine: Engine) -> None:
        """
        Args:
            engine: Ignite Engine, it can be a trainer, validator or evaluator.
        """
        checkpoint = torch.load(self.load_path, map_location=self.map_location)

        prior_max_epochs = engine.state.max_epochs
        Checkpoint.load_objects(to_load=self.load_dict, checkpoint=checkpoint)
        if engine.state.max_epochs > prior_max_epochs:
              raise Exception("NOT GOOD")
        engine.state.max_epochs = prior_max_epochs
        self.logger.info(f"Restored all variables from {self.load_path}")
```

What do you think @Nic-Ma ?

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Sounds reasonable, thanks for your draft code.
I will try to submit a PR for more discussion soon.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 and @danieltudosiu ,

I submitted PR https://github.com/Project-MONAI/MONAI/pull/1775 for this ticket.
Could you please help review it?
I changed to use `if engine.state.epoch > prior_max_epochs` instead of `if engine.state.max_epochs > prior_max_epochs` because I think we need to support this case: user set `max_epochs=100` and saved checkpoint at epoch=50 for some exception or ctrl+C or early-stop, then re-start to train and set `max_epochs=60` to just train 10 more epochs. We should compare with `engine.state.epoch`.

Thanks.

**Comment by vfdev-5** [comment]
Yes, @Nic-Ma you are right. I'll be happy to review the PR, thanks for notification !
