### ISSUE TITLE
Potentially insufficient shuffling in SmartCacheDataset

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1807]
**Describe the bug**
By design, in each training epoch, SmartCacheDataset only presents `cache_num` of data points to the data loader where data shuffling is achieved.

There's a potential of insufficient shuffling at the initial training epoches, when `cache_num`/`cache_rate` is small, and the cache replacements are not fast enough.

**Expected behavior**
would be great to have a global data list shuffling before running the training epochs with the cached subsets.

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/466a0bf629cbf98920935dd6cf4512dc5c908a8f/monai/data/dataset.py#L628

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this ticket.
I will take a look next week.

Thanks.
