### ISSUE TITLE
apply_transform better error msg

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1814]
**Is your feature request related to a problem? Please describe.**
follow up of https://github.com/Project-MONAI/MONAI/discussions/1784#discussioncomment-504257 the error message from the `apply_transform` function could be improved
- https://github.com/Project-MONAI/MONAI/blob/70388fa298384f698dfb3ba790e3bedb1ffcb07b/monai/transforms/transform.py#L48

**Describe the solution you'd like**
could use `DataStatsd` to print additional type/shape info before raising the RuntimeError?

**Comment by Nic-Ma** [comment]
OK, I will take a look at this request.

Thanks for raising it.
