### ISSUE TITLE
allows for flexible model "mode" in the evaluators

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1815]
**Is your feature request related to a problem? Please describe.**
provide an option for all the evaluators to be able to switch between "train_mode" and "eval_mode" of the model.
(this is useful for GradCAM inference integration)

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/70388fa298384f698dfb3ba790e3bedb1ffcb07b/monai/engines/evaluator.py#L200

**Comment by Nic-Ma** [comment]
Sounds interesting, I will enhance the SupervisedEvaluator for it.

Thanks.
