### ISSUE TITLE
Image reader rotating images 90 degrees to the left

### ISSUE THREAD

**Issue by NMVRodrigues** [Project-MONAI/MONAI#1818]
Using the provided `monai.transforms.LoadImage` to load Nifti images rotates them 90 degrees to the left.
Is the rotation intended?
Is there any way to overcome this issue and load them without the rotation?

Here is the code showing a slice of the image:

```
from monai.transforms import LoadNifti 
loader = LoadNifti(image_only=True) 
img_array = loader(images[0]) 
plt.figure() 
plt.imshow(img_array[:, :, 0], cmap="gray") 
plt.show()
```

Here is the output image:

![image](https://user-images.githubusercontent.com/26222830/111996541-09802f80-8b12-11eb-9255-df6ffa8f7501.png)

And here is the correct image orientation as seen on ITK Snap:

![image](https://user-images.githubusercontent.com/26222830/111996615-1e5cc300-8b12-11eb-9976-df47c0147ae7.png)

EDIT:

The slices are not the same but they are from the same volume.

**Comment by wyli** [comment]
perhaps you can specify `origin='lower' or origin='upper'` options in `imshow`? I'm converting this into a discussion
