### ISSUE TITLE
SmartCache Wrapper Component

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#1834]
**Is your feature request related to a problem? Please describe.**
To leverage SmartCache, what user need to do is simply wrap a `Dataset` with `SmartCacheDataset` as below. However, it is a repeating task for any `Dataset` in the exact same way.

``` python
class SmartCacheMyDataset(SmartCacheDataset):
    """
    Add SmartCache functionality to MyDataset
    """
    def __init__(
        self,
        data,
        other_parameters,
        transform,
        replace_rate,
        cache_num,
        cache_rate,
        num_init_workers,
        num_replace_workers,
    ):
        extractor = MyDataset(data, other_parameters)
        super().__init__(
            data=extractor,
            transform=transform,
            replace_rate=replace_rate,
            cache_num=cache_num,
            cache_rate=cache_rate,
            num_init_workers=num_init_workers,
            num_replace_workers=num_replace_workers,
        )
```

**Describe the solution you'd like**
It would be nice to have SmartCache wrapper (as a handler, transformer, or anything else) that can be added into the pipeline to leverage SmartCache functionality without the need to write a new dataset. In this way, SmartCache can be turned on and off by just adding or removing this component without changing any other part of the code.

I think the wrapper itself is easy and don't have much more than what I described above but the only challenge is that it should be called either before `DataLoader` or inside it.

**Comment by behxyz** [comment]
@wyli, @Nic-Ma, Any thought?

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

Sounds interesting an idea.
Let me try to think about it and make a PR.

Thanks.

**Comment by wyli** [comment]
agreed, perhaps it's also possible to have a convenient decorator
```
@SmartCache(num_workers=..., cache_num=...)
class MyDataset
```

**Comment by Nic-Ma** [comment]
Hi @wyli and @behxyz ,

I think we don't need to develop a SmartCache decorator and it's not easy to support the args of SmartCache.
You can just define your own `MyDataset` and use it as the `data` arg of `SmartCacheDataset`:
```py
dataset = MyDataset(...)
smdataset = SmartCacheDataset(data=dataset, cache_num=10, replace_rate=...)
```
And the reason we used `SmartCacheMyDataset` is that Clara only supports 1 Dataset object, we can enhance it by supporting a list of datasets later.
What do you think?

Thanks.

**Comment by behxyz** [comment]
Hi @Nic-Ma , I agree, it would be great if we can add this feature request to the Clara Train roadmap.

Thanks

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

Already added to our internal Clara roadmap.

Thanks.
