### ISSUE TITLE
ReduceLROnPlateau can't use validation metrics as parameter in workflows

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1844]
**Is your feature request related to a problem? Please describe.**

Hi @ericspod ,

We implemented the LR scheduler handler with a callable function arg which takes `engine` as input data for `ReduceLROnPlateau`:
https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/lr_schedule_handler.py#L81
But it can't support to use validation metrics as the plateau parameter, because validation metrics are from validator engine instead of trainer engine.
What do you think about how to improve it?

**Comment by Nic-Ma** [comment]
Maybe for this case, we should attach the LrSchedulerHandler to `validator` instead of `trainer`?
Thanks.

**Comment by ericspod** [comment]
Attaching it to the object doing post-epoch evaluation is the way to do it, unless there were metrics being calculated by the training engine at the end of each iteration. If the schedule is based off current loss reduction rate that would work, if off of a computed metric then probably the validator is needed.
