### ISSUE TITLE
Monai equivalent to tio.OneOf transform? (ETA 8/13)

### ISSUE THREAD

**Issue by neuronflow** [Project-MONAI/MONAI#1847]
**Is your feature request related to a problem? Please describe.**
sometimes it is useful to have multiple augmentation paths

**Describe the solution you'd like**
I am a fan of tio.OneOf
https://torchio.readthedocs.io/_modules/torchio/transforms/augmentation/composition.html#OneOf

**Describe alternatives you've considered**
currently I use the tio function
**Additional context**
I find it so useful that I think it should be part of monai core.

**Comment by Nic-Ma** [comment]
Hi @neuronflow ,

May I know what's the usage case of this transform? What's the difference between a list of random transforms with different probabilities?

Thanks.

**Comment by neuronflow** [comment]
@Nic-Ma sorry I missed your response. The difference is that only one of the transforms will be picked from the list. While in the the other case you can end up with `0` to `n` transforms. 

You could use it if you want to run an affine OR elastic  transformation on your data but not both.

**Comment by Nic-Ma** [comment]
Hi @wyli @ericspod @rijobro ,

Sounds interesting, what do you guys think about this feature?
Thanks.

**Comment by ericspod** [comment]
Imgaug uses these sorts of [meta-augments](https://imgaug.readthedocs.io/en/latest/source/overview/meta.html) as does other libraries like albumentations. Adding the meta-transforms for doing a sequence of transforms (sometimes) or selecting from a list (someof or oneof) wouldn't be difficult. These would be treated like any other randomized transform and not cached by dataset classes.

**Comment by neuronflow** [comment]
Yes, OneOf and SomeOf would be highly appreciated :)

**Comment by lyndonboone** [comment]
Hi @wyli , has anybody started working on this yet? If not, would you like me to try to submit a PR?

**Comment by Nic-Ma** [comment]
Hi @lyndonboone ,

Thanks for your interest here, welcome your contribution if you like.
I think maybe you can make it as subclass of `Compose` or another `Compose` mechanism, @wyli @ericspod @rijobro what do you think?

Thanks.

**Comment by lyndonboone** [comment]
@Nic-Ma @wyli great. I'll start to put something together for it.

Thanks!
