### ISSUE TITLE
Add ignite handler to inverse transforms

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1866]
**Is your feature request related to a problem? Please describe.**
I would suggest to develop a ignite handler to inverse spatial transforms, @rijobro what do you think?

follow-up of https://github.com/Project-MONAI/MONAI/issues/1515

**Comment by rijobro** [comment]
Certainly sounds useful!

**Comment by Nic-Ma** [comment]
Assign to @rijobro based on our internal discussion.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

May I know your plan about this handler?
I received several feature request from Clara project that we want to revert spatial transforms before saving model output.
But our workflows are based on ignite, need the handler to execute the inverse logic.

Thanks.

**Comment by rijobro** [comment]
hi @Nic-Ma , I'll look into this early next week

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Thanks very much for your effort here!
As we are preparing for MONAI 0.5 release this week, is it possible to make this handler available in 0.5?

Thanks in advance.
