### ISSUE TITLE
allows for single key in `ConcatItemsd` 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1881]
Hi everyone I'm using `ConcatItemsd` for concatenating the inputs from multi-modalities images. During development sometimes I adjust the number of modalities of inputs, even to single modality. However I found that `ConcatItemsd` in monai currently does not allow this, with an exception raised [here](https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/utility/dictionary.py#L678-L679). 

This restriction is inconvenient for me and personally I can't find the point of this restriction because both `numpy.concatenate` and `torch.cat` work fine with an input list of length 1. I'd like to hear your opinions on this :)

_Originally posted by @function2-llx in https://github.com/Project-MONAI/MONAI/discussions/1880_

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this up, let me try to update it next week.
