### ISSUE TITLE
Loading models with strict=False

### ISSUE THREAD

**Issue by danieltudosiu** [Project-MONAI/MONAI#1891]
**Is your feature request related to a problem? Please describe.**
In some cases we might want to load partial models. this can be done by loading a state_dict with argument strict=False as per: https://pytorch.org/tutorials/beginner/saving_loading_models.html#warmstarting-model-using-parameters-from-a-different-model

**Describe the solution you'd like**
Allow users to pass kwargs to ignite's Checkpoint handlers as per: https://pytorch.org/ignite/handlers.html#ignite.handlers.Checkpoint.load_objects

**Describe alternatives you've considered**
None, as MONAI does not allow alternatives besides using Ignite directly.

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

Thanks for your feature request, I will try to enhance it soon.

**Comment by danieltudosiu** [comment]
If there is no rush I can do it. I already changed the code of the Handler. I just need to write the test.

**Comment by Nic-Ma** [comment]
That's great! Welcome your contribution!

Thanks.

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

I think this is a good feature request, do you want to submit your PR soon?
We plan to release MONAI v0.5 next week, maybe we can add this feature if possible, just pass a `**kwargs` to the loader.

Thanks.
