### ISSUE TITLE
Prepend path to "mask"

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#1947]
**Is your feature request related to a problem? Please describe.**
`decathlon_dataloader.py` only prepend `base_dir` path to "image" and if it's segmentation to "label". However, if we have a "mask" entry it is not prepended by `base_dir`.
https://github.com/Project-MONAI/MONAI/blob/master/monai/data/decathlon_datalist.py#L65-L68

**Describe the solution you'd like**
```
            if k == "image" or k == "mask":
                item[k] = _compute_path(base_dir, v)
            elif is_segmentation and k == "label":
                item[k] = _compute_path(base_dir, v)
```

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

Make sense, a good feature request. I will enhance the API to support all paths.
Thanks.

**Comment by behxyz** [comment]
> Hi @behxyz ,
> 
> Make sense, a good feature request. I will enhance the API to support all paths.
> Thanks.

Thank you, @Nic-Ma! As the pathology use case depends on it, it would be great if you can prepare it before v0.5 release. Thanks.

**Comment by Nic-Ma** [comment]
Submitted PR: https://github.com/Project-MONAI/MONAI/pull/1948 to fix it.
Thanks.

**Comment by behxyz** [comment]
Thanks @Nic-Ma. I'll review it now.
