### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#197]
MONAI needs to follow good practice for its versioning system and release workflow.

Versions should be numbered following [Semantic Versioning (semver)](https://semver.org/spec/v2.0.0.html). [Versioneer](https://github.com/warner/python-versioneer) can help for this. See e.g. how it is used in [NiftyNet](https://github.com/NifTK/NiftyNet)

The package should be published on [pypi](https://pypi.org/).

Documentation for project admins should bee provided. Niftynet has some [example](https://niftynet.readthedocs.io/en/dev/contributing.html#niftynet-admin-tasks) that can use as starting point.

**Comment by pdogra89** [comment]
@IsaacYangSLA  - would work with  NVIDIA team and come up with a proposal.
