### ISSUE TITLE
optional import

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#198]
**Is your feature request related to a problem? Please describe.**
currently monai requires a few external packages, but not all users will need the features provided via the external packages.

would be great to minimise the number of "hard" dependencies, and implement a mechanism to import lazily

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Record a feedback from research team:
Maybe we can also make ignite as optional import if user just calls some functions in MONAI.
Thanks.
