### ISSUE TITLE
Simplify instructions for pip install

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#199]
Instructions to install the latest deveopment version of MONAI shown in the [README](https://github.com/Project-MONAI/MONAI/blob/master/README.md) currently read as:
```bash
git clone https://github.com/Project-MONAI/MONAI.git
pip install -e MONAI/
```

Even for the development version, this could be simplified as:
```bash
pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
```

On the longer run, following resolution of #197, the latest released version should be available with:
```
pip install monai
```

**Comment by mhubii** [comment]
with the setuptools in place, we can already package it for pypi right now, as highlighted in #197. The only requirement is a user account on pypi. This should be done by someone with access to MONAI's email address on https://pypi.org/account/register/

Given the account, I am happy to package monai.

**Comment by wyli** [comment]
> with the setuptools in place, we can already package it for pypi right now, as highlighted in #197. The only requirement is a user account on pypi. This should be done by someone with access to MONAI's email address ([monai.miccai2019@gmail.com](mailto:monai.miccai2019@gmail.com)). The account can be created here https://pypi.org/account/register/
> 
> Given the account, I am happy to package monai. I would probably need access to the pypi account then

many thanks @mhubii ! I send you login credentials on slack

**Comment by tvercaut** [comment]
Making MONAI available on pypi as a one-off thing is maybe OK at this stage but on the longer run, this need to feed in a proper release workflow as per #197

**Comment by mhubii** [comment]
package is now available on PyPi https://pypi.org/project/monai/0.0.1/

It can be installed via `pip install monai`. I'll dig a bit deeper to automate the uploading for stable/nightly builds

**Comment by wyli** [comment]
many thanks @mhubii.  for the nightly build, this GitHub action approach looks very promising https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
MONAI's relevant CI/CD configs are here: https://github.com/Project-MONAI/MONAI/tree/master/.github/workflows

**Comment by mhubii** [comment]
thanks for sharing, ill check it out
