### ISSUE TITLE
deepgrow pytype error

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1996]
**Describe the bug**
Pytype for deepgrow fails locally:

```
[201/202] check monai.apps.deepgrow.interaction
FAILED: /Users/rich/Documents/Code/MONAI/.pytype/pyi/monai/apps/deepgrow/interaction.pyi 
/usr/local/opt/python@3.7/bin/python3.7 -m pytype.single --disable pyi-error --imports_info /Users/rich/Documents/Code/MONAI/.pytype/imports/monai.apps.deepgrow.interaction.imports --module-name monai.apps.deepgrow.interaction -V 3.7 -o /Users/rich/Documents/Code/MONAI/.pytype/pyi/monai/apps/deepgrow/interaction.pyi --analyze-annotated --check-attribute-types --check-container-types --check-parameter-types --check-variable-types --nofail --precise-return --protocols --quick /Users/rich/Documents/Code/MONAI/monai/apps/deepgrow/interaction.py
File "/Users/rich/Documents/Code/MONAI/monai/apps/deepgrow/interaction.py", line 45, in __init__: Built-in function isinstance was called with the wrong arguments [wrong-arg-types]
         Expected: (object, class_or_type_or_tuple: Union[Tuple[Union[Tuple[type, ...], type], ...], type])
  Actually passed: (object, class_or_type_or_tuple: module)
```

I don't understand why, since the line of code looks fine: `if not isinstance(transforms, Compose):`. Does this fail locally for anyone else, or just me? Any idea how to fix?

**Comment by wyli** [comment]
strange, the current CI works fine (with a fresh ubuntu) using these commands:
https://github.com/Project-MONAI/MONAI/blob/b4d8780a546a98fb3274e9a372e89716d14eb02f/.github/workflows/pythonapp.yml#L34-L42

**Comment by wyli** [comment]
perhaps install the latest dev requirements
```bash
./runtests.sh --clean
pip install --upgrade -r requirements-dev.txt
```
would resolve this?

a few of us had this issue locally, but all addressed by `--upgrade`
(but this won't work for macOS because there isn't a release for `cucim` on macOS)

**Comment by rijobro** [comment]
Ok, I understand. I was using macOS, so this explains the problem.
