### ISSUE TITLE
NifTI image reader 2D/3D

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2]

**Comment by Nic-Ma** [comment]
Hi @wyli ,

As you described in Slack channel that we already have this logic.
Could you please help double confirm whether the existing code is already good enough?
Thanks.

**Comment by wyli** [comment]
yes the code works fine. we could have a simple unit test to demonstrate this, and then close this issue.

**Comment by ericspod** [comment]
I am working on a refresh of this, PR to come.

**Comment by wyli** [comment]
#28 resolves this issue.
