### ISSUE TITLE
Missing inverse for `LoadImageD` transform

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2018]
**Describe the bug**
As the `LoadImageD` transform may convert input data and `affine` here:
https://github.com/Project-MONAI/MONAI/blob/master/monai/data/image_reader.py#L389
Need to support inverse operations.
Otherwise, we can't get proper results to compare with the input image if set `as_closest_canonical=True`.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Could you please help take a look at this issue?
Our internal users found that we can't invert prediction properly if set `as_closest_canonical=True`.

Thanks in advance.

**Comment by wyli** [comment]
I feel we should use the `Orientation` transform to achieve this option, now the transform is also invertible
