### ISSUE TITLE
SimpleInferer add roi_size support to pad/unpad

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#2019]
Can we add roi_size input parameter to SimpleInferer. 
https://github.com/Project-MONAI/MONAI/blob/2d8595d5cbf9ae3d4ed3bc694694cda9f50244f8/monai/inferers/inferer.py#L68
The use case would be to do pad image to a larger size (roi_size) and do a single inference and then unpad back to the original.  The roi_size usually would be some "larger than image" size divisible e.g. by 8 (depending on the network)  

Currently, it's already implemented in SlidingWindowInferer to pad/unpad, but not in SimpleInferer
https://github.com/Project-MONAI/MONAI/blob/5e020a8f9d30f5604f5f649eef40de6061913d49/monai/inferers/utils.py#L23

Even better if we can also add a parameter (pad_to_multiplier). And automatically calculate roi_size based on image size (a large size divisible by pad_to_multiplier==8)

Thanks

**Comment by wyli** [comment]
this should be useful, would be great to make this padding step reversible as well

**Comment by Nic-Ma** [comment]
Hi @wyli ,

May I know what's the difference with `DivisiblePad` transform?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> May I know what's the difference with `DivisiblePad` transform?
> 
> Thanks.

this is with torch tensors, and there's no data dict for the extra info...

**Comment by wyli** [comment]
this could now be done with the invertible numpy/torch transforms
