### ISSUE TITLE
issue with LoadNifti & denseNet121 in V.0.5.0 

### ISSUE THREAD

**Issue by naruetep** [Project-MONAI/MONAI#2032]
Previously the following codes was working 
but it showed error messages and could not continue: 

!pip install -q "monai[gdown, nibabel, tqdm]"

from monai.transforms import \
    Compose,  AddChanneld, ScaleIntensityd, ToTensord, RandRotated, RandFlipd, RandZoomd, Spacingd, SpatialPadd, CenterSpatialCropd , LoadNiftid  
from monai.networks.nets import densenet121

Below are the errors:

ImportError: cannot import name 'LoadNiftid' from 'monai.transforms' (/usr/local/lib/python3.7/dist-packages/monai/transforms/__init__.py)

ImportError: cannot import name 'densenet121' from 'monai.networks.nets' (/usr/local/lib/python3.7/dist-packages/monai/networks/nets/__init__.py)

**Comment by naruetep** [comment]
Typo: should have a backslash sign:
from monai.transforms import \

All my codes were working before the new V.0.5.0

**Comment by Nic-Ma** [comment]
Hi @naruetep ,

These are breaking changes in MONAI v0.5.
Please change to `LoadImageD` transform and `DenseNet121` network instead.

Thanks.

**Comment by wyli** [comment]
I received quite a few questions about the same densenet name issue recently. shall we make alias of the classes, for example, `densenet121 = DenseNet121`  cc @yiheng-wang-nv

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Make sense, let's try to add some alias for DenseNet.

Thanks.
