### ISSUE TITLE
CropForeground with divisible-size bounding boxes

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2051]
**Is your feature request related to a problem? Please describe.**
There's a new requirement for extracting foreground ROIs while keeping the ROI size to be divisible by `K`.

**Describe the solution you'd like**
would be great to have a `pad_divisible` option for `CropForeground`. For example,  if `pad_divisible=8`, the ROI 
 extracted would always have a shape divisible by `8`.

**Describe alternatives you've considered**
This could be partly achieved by the CropForeground + DivisiblePad, but the over-cropping + padding introduces artefacts...

from @volcanofly

**Comment by Nic-Ma** [comment]
Sounds interesting a feature request.
Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

About this feature request, I have a question:
If the divisible ROI is bigger than the image size, should we pad it or leave it as the real size?

Thanks.

**Comment by wyli** [comment]
I think we should pad to divisible, the network can be incompatible with the original size
