### ISSUE TITLE
Rician Noise Transform

### ISSUE THREAD

**Issue by lyndonboone** [Project-MONAI/MONAI#2054]
**Is your feature request related to a problem? Please describe.**
Working with augmentation for DL pipelines, it would be nice to have a noise transform that resembles MRI noise more closely.

**Describe the solution you'd like**
Would it be possible to add a transform that models Rician noise, as a complement to the current Gaussian noise transform? Example of a Rician noise transform implemented in DIPY:
https://dipy.org/documentation/1.1.1./reference/dipy.sims/#dipy.sims.voxel.add_noise
https://github.com/dipy/dipy/blob/c846bf5a23b7e95343a9cf231df2653473602456/dipy/sims/voxel.py (line 60)

I'd be more than happy to try and submit a pull request.

**Comment by wyli** [comment]
welcome! please have a look at the contributing doc in case you haven't seen it https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#preparing-pull-requests

**Comment by lyndonboone** [comment]
Thanks for the reply, @wyli ! I just opened up a WIP pull request for the proposed transform ( #2066 )
