### ISSUE TITLE
additional events in the deepgrow interaction engine

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2056]
**Is your feature request related to a problem? Please describe.**
This is a feature request for adding extra engine events within the click simulation loops during the deepgrow model training:
https://github.com/Project-MONAI/MONAI/blob/abad8416153e67aac04417bbd9398f334b9c0912/monai/apps/deepgrow/interaction.py#L61-L77

the main benefit is to have flexible simulation handlers attached to the inner loops

cc @danieltudosiu @diazandr3s @SachidanandAlle

**Comment by Nic-Ma** [comment]
Please refer to the existing `SupervisedTrainer`:
https://github.com/Project-MONAI/MONAI/blob/master/monai/engines/trainer.py#L164

Thanks.

**Comment by diazandr3s** [comment]
Thanks @wyli .
@Nic-Ma in the current SupervisedTrainer implementation can I access the simulated positive and negative points for a single image?

**Comment by Nic-Ma** [comment]
Hi @diazandr3s ,

I mean you can refer to the current SupervisedTrainer to add additional events.

Thanks.

**Comment by diazandr3s** [comment]
Superb! @danieltudosiu and I implemented a couple of engine events called INNER_ITERATION_STARTED and INNER_ITERATION_COMPLETED for a custom Interaction implementation.

            engine.fire_event(DeepEditEvents.INNER_ITERATION_STARTED)

            engine.network.eval()
            with torch.no_grad():
                if engine.amp:
                    with torch.cuda.amp.autocast():
                        predictions = engine.inferer(inputs, engine.network)
                else:
                    predictions = engine.inferer(inputs, engine.network)

            engine.state.batch_data_inner = batchdata
            engine.state.preds_inner = predictions
            engine.state.step_inner = j

            engine.fire_event(DeepEditEvents.INNER_ITERATION_COMPLETED)

It works quite well for my purpose (DeepEdit implementation). Not sure if that's reasonable of other MONAI users

**Comment by SachidanandAlle** [comment]
@diazandr3s can we check if this is good enough solve your requirement for deepedit usecase..

In that case.. we can add a tutorial in monai on how to extend deepgrow app and train a deepedit model..
May be you want to add one specific transform to drop the signals based on percentage into monai
