### ISSUE TITLE
Error doing transforms in some orders 

### ISSUE THREAD

**Issue by ShadowTwin41** [Project-MONAI/MONAI#2073]
When I do:
<train_transforms = Compose([AddChannel(),
                                #Resize(spatial_size  =(32, 32, 20), mode='trilinear', align_corners =False),
                                ResizeWithPadOrCrop(spatial_size =(64, 64, 64), mode='constant'),
                                RandRotate(prob=0.1,range_x=0.052,range_y =0.052,range_z =0.052), 
                                RandFlip(prob=0.1,spatial_axis=0), 
                                RandScaleIntensity(prob=0.1,factors=(0.1)), 
                                RandZoom(prob=0.1,min_zoom =(1.0),max_zoom=(1.1),mode="nearest"), 
                                RandGaussianNoise(prob=0.1,mean=0, std=0.01), 
                                RandAffine(prob=0.1,translate_range=(2,2,0)), 
                                ScaleIntensity(minv=-1.0, maxv=1.0), 
                                ToTensor()])>
I get the following error:
RuntimeError: applying transform <monai.transforms.intensity.array.ScaleIntensity object at 0x7f6bbf782450>
But changing the order of ScaleIntensity with RandAffine everything works.

**Comment by Nic-Ma** [comment]
Hi @ShadowTwin41 ,

Thanks for your interest.
Could you please try to use MONAI v0.5.0 and paste all your error message?

Thanks.

**Comment by ShadowTwin41** [comment]
I updated my MONAI to v0.5.0, and the error message is:
`input data information of the runtime error transform:
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 8353.06640625)
input data information of the runtime error transform:
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 8706.50390625)
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 8272.4912109375)
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 8272.4912109375)
input data information of the runtime error transform:
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 8556.662109375)
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 8556.662109375)
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 7159.95263671875)
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 7159.95263671875)
Data statistics:
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 64, 64, 64])
Value range: (0.0, 7159.95263671875)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-715451d9219c> in <module>
----> 1 real_images = next(iter(train_loader)) #next image
      2 print(real_images.shape)

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    433         if self._sampler_iter is None:
    434             self._reset()
--> 435         data = self._next_data()
    436         self._num_yielded += 1
    437         if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1083             else:
   1084                 del self._task_info[idx]
-> 1085                 return self._process_data(data)
   1086 
   1087     def _try_put_index(self):

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1109         self._try_put_index()
   1110         if isinstance(data, ExceptionWrapper):
-> 1111             data.reraise()
   1112         return data
   1113 

/opt/conda/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    426             # have message field
    427             raise self.exc_type(message=msg)
--> 428         raise self.exc_type(msg)
    429 
    430 

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/transform.py", line 48, in apply_transform
    return transform(data)
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/intensity/array.py", line 272, in __call__
    return np.asarray(rescale_array(img, self.minv, self.maxv, img.dtype))
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/utils.py", line 115, in rescale_array
    arr = arr.astype(dtype)
AttributeError: 'Tensor' object has no attribute 'astype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/transform.py", line 48, in apply_transform
    return transform(data)
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/compose.py", line 144, in __call__
    input_ = apply_transform(_transform, input_)
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/transform.py", line 71, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.intensity.array.ScaleIntensity object at 0x7f78fbcbc3d0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/monai/data/image_dataset.py", line 111, in __getitem__
    img = apply_transform(self.transform, img)
  File "/opt/conda/lib/python3.7/site-packages/monai/transforms/transform.py", line 71, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f78fbcbce10>
`

**Comment by Nic-Ma** [comment]
Hi @ShadowTwin41 ,

Thanks for your log information, the root cause is that `RandAffine` transform ouput PyTorch Tensor by default while `RandScaleIntensity` expects a numpy array.
You can add the arg `as_tensor_output=False` to your `RandAffine` and test again.

Thanks.

**Comment by stevewinger** [comment]
> Hi @ShadowTwin41 ,
> 
> Thanks for your log information, the root cause is that `RandAffine` transform ouput PyTorch Tensor by default while `RandScaleIntensity` expects a numpy array. You can add the arg `as_tensor_output=False` to your `RandAffine` and test again.
> 
> Thanks.

Thank you very much! I met the same problem.
