### ISSUE TITLE
Misaligned labels saved using NiftiSaver and viewed in 3D Slicer

### ISSUE THREAD

**Issue by dianemarquette** [Project-MONAI/MONAI#2090]
**Describe the bug**
I used the `spleen_segmentation_3d.ipynb` tutorial to train a network using a custom dataset (CT scans of hands). When I open the segmentation labels using 3D Slicer, the segments are not aligned with the original scans.

**To Reproduce**
I used the code from the `unet_evaluation_dict.py` script in the 3D segmentation folder and added it to the evaluation cell of the spleen segmentation Jupyter notebook.

`saver = NiftiSaver(output_dir="./output")`
`for val_data in val_loader:`
...
`saver.save_batch(val_outputs, val_data["image_meta_dict"])`

I then load the original scan as a volume and the corresponding labels (NIfTI file) predicted by the model as a segmentation in 3D Slicer. 

**Expected behavior**
See the labels overlap correctly with my scan. 

**Screenshots**
In practice, I see a clear translation. Plus, the boundaries of the labels are really strange. 
<img width="477" alt="Vanilla_tutorial_3" src="https://user-images.githubusercontent.com/60931186/116082607-e4945480-a69b-11eb-8813-a094e0f74772.png">
<img width="478" alt="Vanilla_tutorial_2" src="https://user-images.githubusercontent.com/60931186/116079262-e0fece80-a697-11eb-82fa-43305b9313cd.png">

However, if I disable the resampling done by NiftiSaver (`resample = False`) and load the preprocessed version of the CT scan, everything looks great:
<img width="450" alt="No_resampling_float_1" src="https://user-images.githubusercontent.com/60931186/116079508-2b804b00-a698-11eb-8cea-3b702c616621.png">
<img width="452" alt="No_resampling_float_2" src="https://user-images.githubusercontent.com/60931186/116079564-3aff9400-a698-11eb-9fcb-8c4d887fc8ca.png">

I suspect that the problem comes from the resampling of the labels to match the resolution of the original CT scans. However, when I check the MRML node information in the "Data" module of 3D Slicer, both nodes have the same spacing and the exact same origin. 

**Environment**

================================
Printing MONAI config...
================================
MONAI version: 0.5.0
Numpy version: 1.19.2
Pytorch version: 1.8.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 2707407fed8c78ccb1c18d1e994a68580457219e

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.17.2
Pillow version: 7.2.0
Tensorboard version: 2.4.1
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.59.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.8.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.2 LTS
Platform: Linux-5.8.0-48-generic-x86_64-with-glibc2.31
Processor: x86_64
Machine: x86_64
Python version: 3.9.2
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0]
CPU freq. (MHz): 4799
Load avg. in last 1, 5, 15 mins (%): [0.6, 0.5, 0.1]
Disk usage (%): 33.1
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.1
Available memory (GB): 24.0
Used memory (GB): 6.5

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70']
GPU 0 Name: GeForce RTX 2080 SUPER
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 48
GPU 0 Total memory (GB): 7.8
GPU 0 Cached memory (GB): 0.0
GPU 0 Allocated memory (GB): 0.0
GPU 0 CUDA capability (maj.min): 7.5

**Additional context**
I also tried to set `output_dtype = np.short` when instantiating my NiftiSaver() (as it's the type usually used for labels in 3D Slicer), but it didn't fix the translation issue. It just deteriorated the resampling quality. 
<img width="480" alt="Short_tutorial_1" src="https://user-images.githubusercontent.com/60931186/116081515-a3e80b80-a69a-11eb-95fd-cf628005f373.png">
<img width="479" alt="Short_tutorial_2" src="https://user-images.githubusercontent.com/60931186/116081528-a9455600-a69a-11eb-99b5-dd2f45b5a702.png">

**Comment by Nic-Ma** [comment]
Hi @dianemarquette ,

Thanks for your experiments.
Could you please help update MONAI to 0..5.2 and invert the transforms for the model output and set "resample=False" when saving?
Refer to this tutorial: https://github.com/Project-MONAI/tutorials/blob/master/modules/inverse_transforms_and_test_time_augmentations.ipynb

Thanks.

**Comment by dianemarquette** [comment]
Hi @Nic-Ma,

Thanks for getting back to me. 
I've updated MONAI to 0.5.2 and tried to invert the transforms for the model using the tutorial. 

```
post_pred = AsDiscrete(argmax=True, to_onehot=False, n_classes=3)


def infer_seg(images, model, roi_size=(160, 160, 160), sw_batch_size=4):
    val_outputs = sliding_window_inference(
        images, roi_size, sw_batch_size, model)
    return post_pred(val_outputs)

    
ckp_path =  "/home/diane/Documents/GitHub_Keri/Models/Model2/model_20210408.pth"
model, _, _ = load_ckp(ckp_path, model, optimizer)
model.eval()
with torch.no_grad():
    saver =  NiftiSaver(output_dir = "/home/diane/Documents/Predicted_labels", resample=False, output_dtype = np.short)
    batch_inverter = BatchInverseTransform(val_transforms, val_loader)
    for i, val_data in enumerate(val_loader):
        batch_infer = infer_seg(val_data["image"].to(device), model).detach().cpu()
        segs_dict = {"label": batch_infer,
                     "label_transforms": val_data["label_transforms"]}
        with allow_missing_keys_mode(val_transforms):
            fwd_bck_batch_labels = batch_inverter(segs_dict)
        # saver.save_batch(fwd_bck_batch_labels, val_data["label_meta_dict"])
```

Unfortunately, I get the following error:

input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
input data information of the runtime error transform:
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 254, 254, 250)
Value range: (0.0, 2.0)
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]
label_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 140541227006896, 'orig_size': [512, 512, 750], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.2969,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.2969,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.3120, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64), 'mode': 'nearest', 'padding_mode': 'border', 'align_corners': False}}, {'class': 'Orientationd', 'id': 140541227006944, 'orig_size': [254, 254, 250], 'extra_info': {'meta_data_key': 'label_meta_dict', 'old_affine': tensor([[  -0.6000,    0.0000,    0.0000,   78.4000],
        [   0.0000,    0.6000,    0.0000,  -75.7031],
        [   0.0000,    0.0000,    0.9370, -195.9380],
        [   0.0000,    0.0000,    0.0000,    1.0000]], dtype=torch.float64)}}]

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items)
     47             return [transform(item) for item in data]
---> 48         return transform(data)
     49     except Exception as e:

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/transforms/spatial/dictionary.py in inverse(self, data)
    330             # Create inverse transform
--> 331             meta_data = d[transform[InverseKeys.EXTRA_INFO]["meta_data_key"]]
    332             orig_affine = transform[InverseKeys.EXTRA_INFO]["old_affine"]

KeyError: 'label_meta_dict'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/data/inverse_batch_transform.py in __call__(self, data)
     89         try:
---> 90             return first(inv_loader)
     91         except RuntimeError as re:

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/utils/misc.py in first(iterable, default)
     70     """
---> 71     for i in iterable:
     72         return i

~/miniconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/dataloader.py in __next__(self)
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1

~/miniconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    556         index = self._next_index()  # may raise StopIteration
--> 557         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    558         if self._pin_memory:

~/miniconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:

~/miniconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/data/dataset.py in __getitem__(self, index)
     92             return Subset(dataset=self, indices=index)
---> 93         return self._transform(index)
     94 

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/data/inverse_batch_transform.py in _transform(self, index)
     48             return data
---> 49         return self.invertible_transform.inverse(data)
     50 

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/transforms/compose.py in inverse(self, data)
    153         for t in reversed(invertible_transforms):
--> 154             data = apply_transform(t.inverse, data)
    155         return data

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items)
     70                 _log_stats(data=data)
---> 71         raise RuntimeError(f"applying transform {transform}") from e
     72 

RuntimeError: applying transform <bound method Orientationd.inverse of <monai.transforms.spatial.dictionary.Orientationd object at 0x7fd24de97be0>>

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-40-9c82660eaf64> in <module>
     20                      "label_transforms": val_data["label_transforms"]}
     21         with allow_missing_keys_mode(val_transforms):
---> 22             fwd_bck_batch_labels = batch_inverter(segs_dict)
     23         # saver.save_batch(fwd_bck_batch_labels, val_data["label_meta_dict"])

~/miniconda3/envs/monai/lib/python3.9/site-packages/monai/data/inverse_batch_transform.py in __call__(self, data)
     93             if "equal size" in re_str:
     94                 re_str += "\nMONAI hint: try creating `BatchInverseTransform` with `collate_fn=lambda x: x`."
---> 95             raise RuntimeError(re_str)

RuntimeError: applying transform <bound method Orientationd.inverse of <monai.transforms.spatial.dictionary.Orientationd object at 0x7fd24de97be0>>
```

Any idea what did I miss?

Thanks :)

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Could you please help take a look at this issue?

Thanks in advance.

**Comment by rijobro** [comment]
Hi @dianemarquette, based on the error it seems to be saying the metadata is missing. So perhaps modifying this:

```python
        segs_dict = {"label": batch_infer,
                     "label_transforms": val_data["label_transforms"]}
```

to this:

```python
        segs_dict = {"label": batch_infer,
                     "label_transforms": val_data["label_transforms"]}
                     "label_meta_dict": val_data["label_meta_dict"]
```

will help. If not let me know and we can have another think.

**Comment by dianemarquette** [comment]
Thanks for your suggestion @rijobro! It did the trick :). 

I have a last question if I may. As the tutorial on inverse transforms didn't show how to save the model predictions, I tried to use the `save_batch` method from the `NiftiSaver` class. 
```
model, _, _ = load_ckp(ckp_path, model, optimizer)
model.eval()
with torch.no_grad():
    saver =  NiftiSaver(output_dir = "/home/diane/Documents/Predicted_labels", resample=False, output_dtype = np.short)
    batch_inverter = BatchInverseTransform(val_transforms, val_loader)
    for i, val_data in enumerate(val_loader):
        batch_infer = infer_seg(val_data["image"].to(device), model).detach().cpu()
        segs_dict = {"label": batch_infer,
                     "label_transforms": val_data["label_transforms"],
                     "label_meta_dict": val_data["label_meta_dict"],}
        with allow_missing_keys_mode(val_transforms):
            fwd_bck_batch_labels = batch_inverter(segs_dict)
        saver.save_batch(fwd_bck_batch_labels["label"], fwd_bck_batch_labels["label_meta_dict"])
```
Unfortunately, it gave me the following error as the `batch_labels` returned by the `batch_inverter` are in an iterable. 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-a9337167fdca> in <module>
     24         # for idx, inverted_seg in enumerate(fwd_bck_batch_labels):
     25             # saver.save(inverted_seg["label"], inverted_seg["label_meta_dict"])
---> 26         saver.save_batch(fwd_bck_batch_labels["label"], fwd_bck_batch_labels["label_meta_dict"])

TypeError: list indices must be integers or slices, not str
```

Replacing the last line by:
```
for idx, inverted_seg in enumerate(fwd_bck_batch_labels):
            saver.save(inverted_seg["label"], inverted_seg["label_meta_dict"])
```

made it work, but I was wondering if there was a way to implement the inverted predictions storage by batch using `save_batch`.

Thanks !

**Comment by rijobro** [comment]
@dianemarquette I'll create a new issue to check into using batch inversion combined with batch image saving. It's something I've not looked at yet, but obviously would be great if they worked well together!
