### ISSUE TITLE
coding style

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#21]
(This ticket is originally from the monai-minimal repo)

Would be great to have a good coding style from day one...
e.g.,
Function and variable names should be lowercase, with words separated by underscores as necessary to improve readability.
Class names should normally use the CapWords convention.

To close this ticket, we ensure that on the project running flake8 (with pep8-naming plugin) with config https://github.com/Project-MONAI/MONAI/blob/a106c79b706a72933520aaba4fc43eb85765985e/.flake8
returns no error message.

**Comment by ericspod** [comment]
The flake8 definition is what we should go with, providing a shell script to automatically run black to format the code wouldn't be a bad idea. We should also nail down what format comments should be in, I would suggest Numpy format https://numpydoc.readthedocs.io/en/latest/format.html as a good hybrid of Google docstrings and reStructured Text formats, however Pytorch uses Google docstrings so maybe we should stick to that.

**Comment by wyli** [comment]
the docstrings format issue will be addressed in #12
