### ISSUE TITLE
Batch image saving should be possible after batch transform inversion

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#2117]
**Is your feature request related to a problem? Please describe.**
As requested here https://github.com/Project-MONAI/MONAI/issues/2090#issuecomment-829907157, it would be good if we could perform a batch inversion of transformations and then feed this directly into `NiftiSaver` in batch mode.

**Describe the solution you'd like**
Not looked into it yet, I imagine the solution will be fairly simple.

**Comment by Nic-Ma** [comment]
Yes, I think maybe you can add the `saving` logic into the invert-transform tutorial.

Thanks.
