### ISSUE TITLE
RandAffine/RandAffined skipping the resampling if do_transform is False

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2124]
**Is your feature request related to a problem? Please describe.**
when do_transform is False and the spatial_size isn't set, the resampling step of RandAffine could be skipped for better performance, for example:
https://github.com/Project-MONAI/MONAI/blob/fd9081bb369827f56853d184139408630ba37ea2/monai/transforms/spatial/array.py#L1441-L1444

**Comment by Nic-Ma** [comment]
Thanks for your suggestion, let me try to optimize it later.

**Comment by Nic-Ma** [comment]
Welcome a contribution if anyone is interested.

Thanks.
