### ISSUE TITLE
CuPy <> NumPy

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#2132]
**Is your feature request related to a problem? Please describe.**
There are transformations that rely on cupy ndarray, so it is not working with numpy array or torch tensors.

**Describe the solution you'd like**
Transformers to convert numpy array (and torch tensors) to cupy arrays, and the other way around.

**Comment by rijobro** [comment]
We also have `ToTensor`, etc. In the same way that we have `LoadImage`, perhaps we should have `ConvertImage` which takes input and output types as argument. That avoids having to have `ToTensor`, `ToNumpy`, `ToCupy`, etc.
