### ISSUE TITLE
DenseVNet for Monai

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#2159]
Greetings,

Will you please consider implementing DenseVNet from NiftyNet over to Monai? 

Thank you

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help share some comments for this feature request about NiftyNet?

Thanks in advance.

**Comment by wyli** [comment]
duplicate of https://github.com/Project-MONAI/MONAI/issues/90
