### ISSUE TITLE
Sync up with Allan Ennemark on website CSS and host on GitHub

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#220]

**Comment by tvercaut** [comment]
As mentioned in the meeting, using [GitHub Pages](https://pages.github.com/) sounds like a good way forward.

**Comment by tvercaut** [comment]
It would also make sense to list https://monai.io/ as the website in the GitHub repository "header" (next to the current "AI Toolkit for Healthcare Imaging" description there should be an edit button for the admins)
