### ISSUE TITLE
Example/Tutorial - use MONAI in a PyTorch Lightning workflow

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#221]

**Comment by marksgraham** [comment]
I can work on this if helpful?

**Comment by Nic-Ma** [comment]
> I can work on this if helpful?

Hi @marksgraham ,

Glad to see your help here!
You can refer to https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb
or
https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_tutorial.ipynb
Thanks.
