### ISSUE TITLE
3D transformations crashing jupyter kernels.

### ISSUE THREAD

**Issue by NMVRodrigues** [Project-MONAI/MONAI#2215]
Hello,

I first noticed this issue when running then 3d_image_transforms.ipynb, where the kernel halted reaching either the pacing, Affine, or elastic transforms.

Running this notebook on colab works just fine and produces the intended results, however, when running on two different local machines it halts the notebook and crashes the kernel, when it reaches the spacing transformations. This happens not only in that notebook but whenever I try to use said transformations.

Both machines have all the required packages, so my guess is that it maybe might be a cuda version issue or any other package working in a way that's not intended.

Any idea of what might be causing this?

One of the machines has a NVIDIA 2080TI, and the other has a 1080TI.

This is their `print_config`

```MONAI version: 0.5.2
Numpy version: 1.19.2
Pytorch version: 1.8.0+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: feb3a334b7bbf302b13a6da80e0b022a4cf75a4e

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.1.0
Tensorboard version: 2.4.1
gdown version: 3.12.2
TorchVision version: 0.9.0+cu111
ITK version: 5.1.2
tqdm version: 4.56.0
lmdb version: 1.0.0
psutil version: 5.8.0```

EDIT: corrected the `print_config`

**Comment by rijobro** [comment]
I can't see anything immediately wrong with any of your versions. It might be worth running `pip install --upgrade --user requirements-dev.txt` just to be sure though. 

If that doesn't solve it, could you try running the unit tests for the transformations that don't work? For affine this would be something like: `python -m unittest tests/test_affine.py`. If you've got the time, it might be worth running all the unit tests: `./runtests.sh -u`.

**Comment by NMVRodrigues** [comment]
@rijobro Thanks for the help.
So, I first tried to install the dependencies but it failed.
Moving on to the tests, the affine test detected no problem, but when running all tests it halts out of nowhere and the cmd closes.
Doing a unit test on the `spacingd` transform which was one that was giving problems in jupyter produces the following output.
Could this be the problem? I have no idea how to fix it.

```
(torchgpu) C:\Users\nuno\Desktop\MONAI>python -m unittest tests/test_spacingd.py
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

**Comment by rijobro** [comment]
Perhaps you could try temporarily disabling OpenMP to see if that fixes the problem: `export OMP_NUM_THREADS=1`.

**Comment by rijobro** [comment]
Hi @NMVRodrigues , any luck?

**Comment by wyli** [comment]
Perhaps this is a windows specific issue. All notebooks work fine with our self-hosted LInux instances (https://github.com/Project-MONAI/MONAI/runs/2734761245?check_suite_focus=true). please reopen if there's more information about how to reproduce it.
