### ISSUE TITLE
Inverse Transforms don't seem to give the desired result on 3D data

### ISSUE THREAD

**Issue by devsam19** [Project-MONAI/MONAI#2248]
I created a simple transform like the following
```
check_transforms = Compose([ 
    LoadImaged(keys, reader='NibabelReader', as_closest_canonical=True),
    AsChannelFirstd(keys, channel_dim = -1),
    AddChanneld(keys,),
    Resized(keys, spatial_size=(-1,128,128)),
    Lambdad(keys=['label'], func=lambda x: map_labels(x, TRAIN_MAPPING_FN)),
    ToTensord(keys=['image', 'label'])
])
```

On following the inverse transform tutorial notebook, it still fails to revert the image to their original size.
```

img_dict = {"label": t,
            "label_transforms": t_t}

with allow_missing_keys_mode(check_transforms):
    inverted_img = check_transforms.inverse(img_dict)
```
Any suggestions?

**Comment by rijobro** [comment]
Hi @devsam19

- What is the original spacing/size (1) originally, (2) after the forward transformations, and (3) after the inverse?
- Can you remove the `Lamdad` transformation? I'm not sure what your lambda is doing, but for the sake of testing, let's temporarily remove it.
- Can I see the code that generates `t` and `t_t`?
- The inverse of `Resized` (the only invertible transform in your list) is tested in `test_inverse.py`, and after the inverse the image is back to its original size. Would it be possible to create a self contained example showing your problem? Once I have that I'll be better able to help you debug it.

**Comment by devsam19** [comment]
Hi @rijobro 
Thank you for the quick response.
Here are the details:

- Original Image Size: (19, 384, 384)
- After Transform : (32, 128, 128)
- After Inverse Transform : (32, 128, 128)

Here's the code that generates t and t_t:

```
train_data_dict = df.to_dict('records')
transformed_data = check_transforms(train_data_dict[:1])
t = transformed_data[0]['IMAGE'][0]
t_t = transformed_data[0]["IMAGE_transforms"]
```

Here is a complete example:

```
train_data_dict = df.to_dict('records')
transformed_data = check_transforms(train_data_dict[:1])
t = transformed_data[0]['IMAGE'][0]
t_t = transformed_data[0]["IMAGE_transforms"]

img_dict = {"label": t,
            "label_transforms": t_t}

with allow_missing_keys_mode(check_transforms):
    inverted_img = check_transforms.inverse(img_dict)
print(inverted_img['label'].shape)
```

Thank you for the help!

**Comment by rijobro** [comment]
And what is the definition of `check_transforms`? 

By complete example, I mean would it be possible to create a script that I can run from start to end? You could use `monai.data.create_test_image_3d` to create a test image. That would be really useful
