### ISSUE TITLE
SplitChannel has different behaviour depending on numpy/torch input

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#2275]
**Describe the bug**

```python
import numpy as np
import torch
from monai.transforms import SplitChannel

t = SplitChannel()
_np = np.random.randint(2, size=(3, 3, 4))
_torch = torch.Tensor(_np)

print(t(_np)[0].shape)
print(t(_torch)[0].shape)
```
Output is:
```
(1, 3, 4)
torch.Size([3, 1, 4])
```

I suspect this is because `slice` acts differently on torch and numpy. Is this behaviour to be expected? I'm not sure if it was intentional to let the different modules follow their own behaviour or if we expect the two to give the same result.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

I will update this transform in my PR for `decollate` batch to a list of Tensors.

Thanks.

**Comment by Nic-Ma** [comment]
Already fixed this issue in this PR: https://github.com/Project-MONAI/MONAI/pull/2244.

Thanks.

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/2315
