### ISSUE TITLE
automatic pip packaging and uploading

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#228]
after tagging a release branch, CI should automatically build and test pypi packages and upload them to the testpypi service.

the admin could verify the release via testpypi, and then manually upload the same packages to pypi.

these are enhancements of #199 #197

**Comment by tvercaut** [comment]
As per the [twine](https://pypi.org/project/twine/) documentation, submitting to the test pypi can be done with:
```
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```
