### ISSUE TITLE
Any dictionary-based transform should not use shallow copy

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#2286]
**Describe the bug**

Any dictionary-based transform should not use shallow copy, i.e. every `d = dict(data)` at the first line of their implementation (example [here](https://github.com/Project-MONAI/MONAI/blob/7ee798997305fcf5beb4704a42d63ff403ebb6d0/monai/transforms/spatial/dictionary.py#L339)), this will cause some unexpected modification later.

**To Reproduce**
```python
from copy import deepcopy

import numpy as np
from monai.transforms import *
from monai.data import NiftiSaver

loader = Compose([
    LoadImageD('img'),
    AddChannelD('img'),
])
origin = loader({'img': 'origin.nii.gz'})
save = deepcopy(origin)
trans = OrientationD('img', 'LPI')(origin)
print(np.array_equal(origin['img_meta_dict']['affine'], save['img_meta_dict']['affine']))
```

This will output `False`

**Expected behavior**
output `True`

**Comment by eddyleelin** [comment]
I'm not 100% sure, but does it seem like the [docs](https://docs.monai.io/en/latest/transforms.html#monai.transforms.Transform) seem to indicate that `Transform` (and therefore `MapTransform`, by extension) does not guarantee that `data` will not be modified in place?
> An abstract class of a `Transform`. A transform is callable that processes `data`. It could be stateful and may modify `data` in place...

And then in `MapTransform`, the [doc](https://docs.monai.io/en/latest/transforms.html#monai.transforms.MapTransform) says that it is
> A subclass of `monai.transforms.Transform` with an assumption that the data input of `self.__call__` is a MutableMapping such as `dict`.

**Comment by function2-llx** [comment]
> I'm not 100% sure, but does it seem like the [docs](https://docs.monai.io/en/latest/transforms.html#monai.transforms.Transform) seem to indicate that `Transform` (and therefore `MapTransform`, by extension) does not guarantee that `data` will not be modified in place?
> 
> > An abstract class of a `Transform`. A transform is callable that processes `data`. It could be stateful and may modify `data` in place...
> 
> And then in `MapTransform`, the [doc](https://docs.monai.io/en/latest/transforms.html#monai.transforms.MapTransform) says that it is
> 
> > A subclass of `monai.transforms.Transform` with an assumption that the data input of `self.__call__` is a MutableMapping such as `dict`.

Thanks for the reply, I think you're right. Maybe I'll conduct deepcopy manually when necessary.

**Comment by rijobro** [comment]
Hi @function2-llx, I understand why it would be confusing that some transforms perform deep copies and some shallow. 

Personally I think we should update them to make them all deep, and then we can update the documentation that @eddyleelin referenced.

@wyli @Nic-Ma @ericspod – what do you think?
