### ISSUE TITLE
decollate needs to support non-batch data

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2300]
**Is your feature request related to a problem? Please describe.**
Currently, if we apply `decollate` to a data, every item must have same batch size.
We need to support the case that some items may be `None` or scalar value, like `loss`.

**Comment by Nic-Ma** [comment]
I would suggest to copy the data item if can't decollate, similar logic as our `RandCropByPosNegLabeld` transform.

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/2315
