### ISSUE TITLE
Provide a basic function to load datalist from CSV file (25/June)

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2310]
**Is your feature request related to a problem? Please describe.**
As we discussed in: https://github.com/Project-MONAI/MONAI/discussions/2212
We need to load CSV content and make it as a datalist for dataset.
Then apply transforms for the data items.

**Comment by Nic-Ma** [comment]
After discussion with @wyli , maybe it's better to involve the `pandas` lib to handle CSV for complicated features in the future. I will rewrite the draft code to use pandas DataFrame to support joining tables.
Please feel free to let me know if you have any concerns about optionally importing pandas.

Thanks.

**Comment by wyli** [comment]
Hi @Nic-Ma, the discussion outcome is to make some improvements to the current prototype as our basic module.

the current prototype for your reference:
```py
data_train = MultimodalCSVDataset(csv_file='./test.csv',
                                  variable_groups = [['subject_id'],
                                                     ['label'],
                                                     ['image'],
                                                     ['image_second'],
                                                     ['image_full'],
                                                     ['ehr_%01d'%i for i in range(18)],
                                                     ['meta_%01d'%i for i in range(3)],
                                                     ],
                                  variable_group_names=['subject_id',
                                                        'label',
                                                        'image',
                                                        'image_full',
                                                        'ehr',
                                                        'flags'],
                                  variable_group_types=['str',
                                                        'int',
                                                        'str',
                                                        'str',
                                                        'np.float32',
                                                        'np.float32'],
                                  transform=transforms_train)
```
Enhancements TODOs
- the dataset should support single `csv_file` for the first version
- the dataset should support an additional dictionary for  variable names, types, default for missing values,
for example:
```py
column_types = {  # this could come from some json-based mapping file https://www.w3.org/2013/csvw/wiki/CSV-LD)
    "subject_id": {"type": str}, 
    "label": {"type": int, "default": 0},
    "ehr_0": {"type": float, "default": 0.0, "unit": "year"},
    "ehr_1": {"type": float, "default": 0.0, "unit": "month"},
    "image": {"type": nifti, "default": None},
}
ds = MultimodalCSVDataset(
    csv_file='./test.csv',
    column_types=column_types,
    groups=[['subject_id'], ['label'], ['ehr_01', 'ehr_02'], ['image']],
    output_keys=['suject_id', 'label', 'ehr', 'img'],
    transform=transforms_train,
)
```
ds[0] would be a dictionary of 
```py
{"subject_id": "abcd", 
 "label": 1, 
 "ehr": [0.1, 0.2], 
 "img": "/Volume/file.nii.gz"}
```

cc @csudre @IntegratorBrad

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for providing the reference examples.
I am updating the PR for this feature.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

For this initial feature request, I think the PR https://github.com/Project-MONAI/MONAI/pull/2349 already can support.
The `load_csv_datalist()` API can give a list of dictionaries, then use it in any Dataset, like our CacheDataset, PersistentDataset, etc. Same as our `load_decathlon_datalist()` API.
For example:
```py
result = load_csv_datalist(
  filename=[filepath1, filepath2, filepath3],
  row_indices=[1, 3],  # load row: 1, 3
  col_names=["subject_id", "image", *[f"ehr_{i}" for i in range(11)], "meta_0", "meta_1", "meta_2"],
  col_groups={"ehr": [f"ehr_{i}" for i in range(11)], "meta12": ["meta_1", "meta_2"]},
  )
dataset = CacheDataset(data=result, transform=transforms, cache_rate=1.0)
```
The challenge is to support very big CSV files during training.
What do you think?

Thanks.

**Comment by Nic-Ma** [comment]
CC @ericspod @rijobro to join the discussion.

Thanks.

**Comment by wyli** [comment]
the idea is to have a dataset class instead of a function, so that it'll be able to maintain internal states if needed and be extensible, similar to the `imagedataset` https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_dataset.py#L23

**Comment by Nic-Ma** [comment]
OK, make sense.
Let me update it to a Dataset ASAP.

Thanks.

**Comment by ericspod** [comment]
What is the definition of very large CSV files? When they get to be hundreds of megabytes we start having issue with Pandas,  @atbenmurray and others have been working on a project [ExeTera](https://github.com/KCL-BMEIS/ExeTera/) for loading data from the ZOE Covid Symptoms app. It has its own way of parsing large CSV files because other things were painfully slow for that scale of data. I wouldn't necessarily recommend using this as it's not meant for online training, but it illustrates the challenges of large scale csv data. The alternative approach is of course to break files into smaller ones and cycle between them during training, unloading data from one before moving to the next. Pandas will be able to  handle things at that scale so we can stick to pre-existing solutions.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Thanks very much for your sharing!
In the initial PR #2349 , I tried to provide 2 Datasets, 1 is for regular small CSV files, 1 is for big CSV files and based on IterableDataset of PyTorch. So I think users can decide to use which Dataset based on his data and HW/SW environment.

Thanks.

**Comment by wyli** [comment]
see also https://github.com/Project-MONAI/MONAI/wiki/Minutes-Data-Working-Group-17-Jun-2021
