### ISSUE TITLE
preserving order of the keys when transforming data

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2317]
**Is your feature request related to a problem? Please describe.**

https://github.com/Project-MONAI/tutorials/issues/223

Packages such as Catalyst use the first item of the data dict to infer the batch size. 

`self.batch_size = next(iter(batch.values())).shape[0]`

Our recent updates on the transforms such as

https://github.com/Project-MONAI/MONAI/blob/316449bae1386df3300f1d57f135c1869f602740/monai/transforms/croppad/dictionary.py#L1028-L1030
change the order of the data dict keys and this causes errors

**Describe the solution you'd like**

the transforms should preserve the keys' order whenever possible.

**Describe alternatives you've considered**

could have some other workaround to address the specific issue in the demo, but we may have similar issues  in the future which are potentially difficult to debug

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this up.
Yes, it makes sense to guarantee the dict order epecially Python 3.7 officially supports the dict order as the insertion order:
https://www.reddit.com/r/Python/comments/8cf4rf/til_that_starting_from_37_dicts_are_officially/
I am thinking a draft proposal: everytime when creating new dict, can we use `shallow copy` to create a dict with same order, then use `deepcopy` to copy the real content. For example:
```py
results: List[Dict[Hashable, np.ndarray]] = [dict(data) for _ in range(self.num_samples)]
for i, center in enumerate(self.centers):
    for key in set(data.keys()).difference(set(self.keys)):
        results[i][key] = deepcopy(data[key])
    for key in self.key_iterator(d):
        results[i][key] = cropper(d[key])
```
What do you think?

Thanks.

**Comment by wyli** [comment]
thanks @Nic-Ma, I think that'll be nice, please submit a PR.

**Comment by Nic-Ma** [comment]
Sure, I will submit a PR ASAP next week.

Thanks.
