### ISSUE TITLE
Remove required dependency on scikit-image and scipy

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#232]
`scikit-image` and `scipy` are currently required dependencies of MONAI. However, it looks like these are used to implement a small number of features that can be implemented with PyTorch.

Limiting the number of required dependencies is good practice  and for the particular case at end, replacing these implementations by PyTorch ones may help towards fixing #189

See https://github.com/kornia/kornia/blob/master/kornia/geometry/transform/imgwarp.py#L126 foe examples of replacing `skimage.transform.resize` and `scipy.ndimage.zoom` with PyTorch based code based on `affine_grid` and `grid_sample`. There is related discussion in #112

**Comment by tvercaut** [comment]
This is also linked to #290 where a related issue is highlighted but with cupy

**Comment by wyli** [comment]
this is mostly done -- scipy removed, scikit-image becomes an optional for the connected component analysis  I'm closing this in favour of #554
