### ISSUE TITLE
Refactor Croppad Dictionary Functions to clean up differences in structures

### ISSUE THREAD

**Issue by eddyleelin** [Project-MONAI/MONAI#2320]
**Is your feature request related to a problem? Please describe.**
Sorry, I was looking through the code mentioned in #2317 and had what might be a dumb question! Is there a reason why the structure for creating/returning the list of dictionaries is different between the similar functions? For example, the function [`RandSpatialCropSamplesd`](https://github.com/Project-MONAI/MONAI/blob/316449bae1386df3300f1d57f135c1869f602740/monai/transforms/croppad/dictionary.py#L669-L688) initializes an empty ret list and appends entries like this:
```
ret = []
  for i in range(self.num_samples):
      d = data(dict)
      # cropped created from d
      ret.append(cropped)
return ret
```
while [`RandWeightedCropd`](https://github.com/Project-MONAI/MONAI/blob/316449bae1386df3300f1d57f135c1869f602740/monai/transforms/croppad/dictionary.py#L858-L886) and [`RandCropByPosNegLabeld`](https://github.com/Project-MONAI/MONAI/blob/316449bae1386df3300f1d57f135c1869f602740/monai/transforms/croppad/dictionary.py#L1013-L1043) currently initiate a `results` list of length `self.num_samples` (without shallow copying `data` first, as pointed out in this issue), such as:
```
results: List[Dict[Hashable, np.ndarray]] = [dict(data) for _ in range(self.num_samples)]
  for i in range(self.num_samples):
    # set value of results[i]
return results
```

And even between these last 2 functions (`RandWeightedCropd` and `RandCropByPosNegLabeld`), the order of the for loops are not consistent (despite doing mostly similar things).

**Describe the solution you'd like**
Again, I'm not sure if this is a valid issue or important, but I would definitely be willing to make a PR to refactor this part of the code if it is. My proposal is to do the following:

1. Change the two latter functions to initialize an empty `ret` list and append each dictionary to it, to match that of `RandSpatialCropSamplesd`. This is because it seems like we are only appending one dictionary at a time to`results`, so it would simplify the code to rename `results[i]` to `cropped` or something like the first function, and append it to `ret`.
2. Change the order of the for loops in `RandWeightedCropd` to match those of `RandCropByPosNegLabeld`, as the second one seems to be cleaner while doing performing many of the same functions.
3. I could also submit a second PR (or combine it with this one) with a fix to address the issue #2317 by creating a shallow copy of `data` in each iteration through the loop.

**Describe alternatives you've considered**
I would also be willing to just do one of the first two suggestions, rather than both, if it makes more sense.

**Additional context**
Thanks so much again and sorry for the lengthy question! I'm hoping to make it very clear what I was thinking since this was my first issue here.

**Comment by Nic-Ma** [comment]
Hi @eddyleelin ,

I think we don't have a particular reason to make the transforms slightly different, just due to some historical reason or different developers.
Welcome to submit a PR to `shallow copy` the dict to guarantee the order.
Thanks very much for pointing this!
