### ISSUE TITLE
Set up an explicit backward compatibility policy

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#233]
A discussed in #197, we agreed on following [semver](https://semver.org/) for version numbering. This implicetly means we agree on maintaining backward compatibility until major version changes.

It might be good to make the backward compatibility policy more explicit. By means of example, TensorFlow documents their backwards compatibility policy quite well: https://www.tensorflow.org/guide/versions

For MONAI, enforcing bacward compatibility acording to semver might also mean introducing an "experimental" folder or similar within MONAI where features that are ready for real-world testing but not yet for backward compatibility can be placed.

**Comment by tvercaut** [comment]
A bit of a side question in this issue but note that semver and PEP440 are incompatible when it comes to pre-release numbering (see also https://github.com/semver/semver/issues/483). Given the pythonic ambition of MONAI, having PEP440 prevail over semver for this particular point would probably make sense.

**Comment by IsaacYangSLA** [comment]
Proposed statement on backward compatibility policy:

MONAI versioning policy follows PEP440 as follows
```
X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
X.Y     # Final release
```
The common understanding on backward compatibility applies.

- Backward compatibility across MAJOR (X in the example above) is not guaranteed.
- Backward compatibility in private API across MINOR (Y in the example above) is not guaranteed.

For releases with MAJOR == 0, public API can change at any time.

**Comment by tvercaut** [comment]
Having a third component would make it closer aligned with semver and should remain compatible with PEP440. I would suggest following the  modified semver called "Linux/Python Compatible Semantic Versioning 3.0.0" from openstack:
https://docs.openstack.org/pbr/3.1.1/semver.html

Releases would be tagged with
```
X.Y.Z.aN             # Alpha release
X.Y.Z.aN.devM   # Dev version for an alpha release
X.Y.Z.bN             # Beta release
X.Y.Z.rcN            # Release Candidate
X.Y.Z                   # Final release
X.Y.Z.devM         # Dev version for a final release
```

**Comment by tvercaut** [comment]
Related discussion in #2158

**Comment by rijobro** [comment]
Also related PR: https://github.com/Project-MONAI/MONAI/pull/2171.

**Comment by ericspod** [comment]
Another PR: #2338

**Comment by wyli** [comment]
Here are some discussion points for the potential feature classifications:

Stable
Feature with code, documentation, tutorial ready, available in the milestone releases
- Relatively long-term maintenance (Pin down a few versions of pytorch/cuda for full tests)
- Breaking changes with notice/warnings one milestone release ahead of time
- Maintain an API changelog, migration guides
- Available using “pip install” and “docker image” 
- Have pre-compiled binaries if it’s in c++/cuda? (via [the release page](https://github.com/Project-MONAI/MONAI/releases))

Beta
Feature with code and some documentation, available in the milestone releases
- May not have thorough tests for extensive use cases
- May change in the next release without backward compatibility warnings
- Available using “pip install” and “docker image” 
- May have pre-compiled binaries if it’s in c++/cuda? (via [the release page](https://github.com/Project-MONAI/MONAI/releases))
- May have a separate warning decorator indicating the API is subject to change?

Experimental
on one of the branches other than “dev”, “main”
- With status: Discussion/InProgress/Rejected
- Made available via github (not pypi or milestone docker image)
- Include proposals for significant design changes
- Requires timely review from the core team
- Frequently check the compatibility with the `dev` and/or `main`

**Comment by wyli** [comment]
For making public API breaking changes, using [the deprecation utils in monai](https://github.com/Project-MONAI/MONAI/blob/dev/monai/utils/deprecate_utils.py):
1. discuss the breaking changes during pull requests or in dev meetings with a feature proposal if needed.
2. add a warning message in the upcoming release (version `x.y`), the warning message should include a forecast of removing the deprecated API in:
    - `x+1.0` the next major version if it's a significant change,
    - `x.y+2` the minor version after the next one, if it's a minor API change (this is not consistent with [the semantic versioning](https://semver.org/#if-even-the-tiniest-backwards-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly)).
7. add new test cases by extending the existing unit tests to cover the modified API.
8. collect any feedback from the users during the subsequent few releases, reconsider step 1 if needed.
9. before each release, review the deprecating APIs, clean up removed APIs described in step 2.

cc @Nic-Ma @ericspod @rijobro let's also discuss these at the next dev meeting.

**Comment by rijobro** [comment]
The forecast of removal version is currently an optional argument. Should we make it required so that we always know when we expect something to be removed? I also think that the docstring: 

> removed: version at which the argument was removed and no longer usable.

should be more like:

> remove: version at which the argument **will be** removed and no longer usable.
