### ISSUE TITLE
Utilities for partially loading weights from a state_dict

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2339]
**Is your feature request related to a problem? Please describe.**
A utility function is needed to set a model's state_dict partially from another one.
this is required by https://github.com/Project-MONAI/MONAI/issues/2273 and https://github.com/Project-MONAI/MONAI/discussions/2329

an implementation is already part of the checkpoint loader:
https://github.com/Project-MONAI/MONAI/blob/a5364621712fe6b3de584223a4e28be638bc0fc4/monai/handlers/checkpoint_loader.py#L95-L106

**Comment by Nic-Ma** [comment]
Yes, we can extract this logic to be a utility function.

Thanks.
