### ISSUE TITLE
UpSample module does not support `size` parameter for `nontrainable` mode

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#2342]
The `size` parameter is used to specify the spatial size of the output for `nontrainable` mode ( see: https://pytorch.org/docs/stable/generated/torch.nn.Upsample.html). I think this parameter should be added into our current UpSample module.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Sounds good, could you please help do a PR for it?

Thanks.

**Comment by yiheng-wang-nv** [comment]
In addition, current Upsample module has a bug:
The type for `scale_factor` is `Union[Sequence[float], float]`, but as for `NONTRAINABLE` mode, `scale_factor` cannot have `None` input like `None` or `(None, 3, 3)`.
I will fix this issue in the same PR.
