### ISSUE TITLE
Set up items for MMAR (6/July)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2364]
**Is your feature request related to a problem? Please describe.**
this is part of #2273  to include more MMAR models in the model descriptors:
https://github.com/Project-MONAI/MONAI/blob/c1b5028a201a91adfc2c347ba51a6156926091b6/monai/apps/mmars/model_desc.py#L40-L43
the newly added should be tested with 
https://github.com/Project-MONAI/MONAI/blob/c1b5028a201a91adfc2c347ba51a6156926091b6/monai/apps/mmars/mmars.py#L104-L107

ETA: 7/July

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Is this ticket duplicated to https://github.com/Project-MONAI/MONAI/issues/2365?

Thanks.
