### ISSUE TITLE
Import Error:  monai._C 

### ISSUE THREAD

**Issue by EricZimmermann** [Project-MONAI/MONAI#2366]
Spatial transformer layers (grid grad, pull, push, count) all have optional imports for module monai._C. however, no module is found.

```
from monai.networks.layers import grid_pull
```

There is no documentation on how to install this module. Monai links to https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies with no information regarding ._C

I have reinstalled all - pip install 'monai[all]' as specified in the link above

**Screenshots**
<img width="837" alt="Screen Shot 2021-06-14 at 3 12 52 PM" src="https://user-images.githubusercontent.com/23340179/121946506-ff418c00-cd22-11eb-9861-80b42f8d6a6d.png">

**Environment**

```
MONAI version: 0.5.3
Numpy version: 1.19.5
Pytorch version: 1.8.0+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: d78c669c67e38ddfbe572f6a0438e9df0b8c65d7

Optional dependencies:
Pytorch Ignite version: 0.4.4
Nibabel version: 3.2.1
scikit-image version: 0.17.2
Pillow version: 8.1.2
Tensorboard version: 2.5.0
gdown version: 3.13.0
TorchVision version: 0.9.0+cu111
ITK version: 5.1.2
tqdm version: 4.60.0
lmdb version: 1.2.1
psutil version: 5.8.0

```

**Comment by kirillv-cim** [comment]
Having the same issue, please help

**Comment by wyli** [comment]
Thanks for the report, the modules are not currently released with the PyPI package. To install them you'll have to fetch the source code with `pip install git+` or `git clone` and install from source.  For more details please search for `Cpp/CUDA extensions` in this installation guide https://docs.monai.io/en/latest/installation.html. 

I'm closing this ticket in favour of https://github.com/Project-MONAI/MONAI/issues/1462. If you have further usage questions please create a discussion https://github.com/Project-MONAI/MONAI/discussions

**Comment by EricZimmermann** [comment]
Thank you for the support!
