### ISSUE TITLE
add descriptions for the MedNIST dataset

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#237]
demo based on MedNIST is in place, we still miss the descriptions such as data source and author, if we choose to redistribute the files (~70MB) we need the licensing information.
see also #151 

we may also provide python API such as `monai.data.MedNIST()` to make the dataset accessible.
(maybe related to #88 )

**Comment by tvercaut** [comment]
Note that I created an issue about the MedNIST licence upstream: https://github.com/apolanco3225/Medical-MNIST-Classification/issues/1

**Comment by Nic-Ma** [comment]
> Note that I created an issue about the MedNIST licence upstream: [apolanco3225/Medical-MNIST-Classification#1](https://github.com/apolanco3225/Medical-MNIST-Classification/issues/1)

Hi @tvercaut ,

Thanks for your sharing!
1. I developed a new MONAI tutorial based on the MedNIST dataset, didn't use the tutorial you shared.
2. @pdogra89  is working on the license request, I will add Dataset link and related description to our code when license is ready.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @pdogra89 ,

Do you get any update on the license related things?
I think we may need to add license and dataset link to the tutorial before Alpha release.
Thank.
