### ISSUE TITLE
compatibility with torch 1.9

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2376]
**Is your feature request related to a problem? Please describe.**
pytorch 1.9 is available, there're some compatibility issues such as https://github.com/Project-MONAI/MONAI/runs/2831507688?check_suite_focus=true#step:8:4236

**Comment by Nic-Ma** [comment]
Thanks for raising this issue.
@yiheng-wang-nv , could you please help take a look at the network implementation with PyTorch 1.9?

Thanks in advance.
