### ISSUE TITLE
Add pre-merge pipeline using NVIDIA blossom system (7/July)

### ISSUE THREAD

**Issue by madil90** [Project-MONAI/MONAI#2381]
**Is your feature request related to a problem? Please describe.**
Current CI system uses GitHub based runners and is not scalable as the project grows. NVIDIA's blossom CI system is a scalable solution that uses Kubernetes/Jenkins to launch CI jobs.

**Describe the solution you'd like**
Add the action that connects to blossom system and launches CI jobs on pull request comments.

**Comment by wyli** [comment]
#2382 is not working at the moment.
