### ISSUE TITLE
Add docstring for `not_nans` in metrics

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#2390]
Now `get_not_nans` is added for metrics, but `not_nans` does not have the corresponding descriptions.

**Comment by yiheng-wang-nv** [comment]
In addition, the docsting of `get_not_nans` in class `ConfusionMatrixMetric` is wrong according to its `aggregate` function. Now, if there are two metrics and `get_not_nans` is True, it will return a list like:
```
[metric1_result, metric1_not_nans, metric2_result, metric2_not_nans]
```
Let me also change it into:
```
[(metric1_result, metric1_not_nans), (metric2_result, metric2_not_nans)]
```
and change the docstring as well.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Thanks for raising this.
Sure, please submit a PR for it.

Thanks.
