### ISSUE TITLE
Testing tutorials/demos for the upcoming release v0.6 (14/July)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2396]
**Is your feature request related to a problem? Please describe.**
this ticket tracks the necessary tests of the tutorial repo for v0.6.

while we have regular tests for some of the notebooks, in general many of the scripts need manual verifications.

**Comment by wyli** [comment]
see also https://github.com/Project-MONAI/MONAI/issues/2402

**Comment by zephyrie** [comment]
@wyli I'm out of the office the rest of the week but will start testing next Monday.

**Comment by wyli** [comment]
this is addressed by several recent PRs https://github.com/Project-MONAI/tutorials/pulls, if there are further issues please create new tickets.
