### ISSUE TITLE
update to ignite v0.4.5 (2/July)

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2399]
**Is your feature request related to a problem? Please describe.**
As ignite v0.4.5 is already released, need to update our codebase to align with it and leverage the new metrics APIs.
https://github.com/pytorch/ignite/tree/v0.4.5
CC @vfdev-5

**Comment by Nic-Ma** [comment]
I will update ignite version and test ASAP.

Thanks.

**Comment by vfdev-5** [comment]
Hi Nic, the release is cut but not yet on conda or pypi. We are working on it...

**Comment by Nic-Ma** [comment]
> Hi Nic, the release is cut but not yet on conda or pypi. We are working on it...

Hi @vfdev-5 ,

Thanks for your notification, I will update ASAP when you completed it.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

May I know the ETA of pypi release of ignite v0.4.5? We are closing to MONAI v0.6 release.

Thanks.

**Comment by vfdev-5** [comment]
Hi Nic, we just released it and will announce tomorrow :)  
- https://pypi.org/project/pytorch-ignite/
- https://anaconda.org/pytorch/ignite

**Comment by Nic-Ma** [comment]
That's really cool!! Congratulations!

Thanks.

**Comment by vfdev-5** [comment]
Thanks, Nic and sorry for delay ! Meanwhile we fixed more small issues/bugs and could finally upload to anaconda and pypi...
Hope this unblocks your work.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 , I will try to update ignite in MONAI as soon as possible.

Thanks.

**Comment by deepib** [comment]
add another set of tests for 0.4.5
code base should support both versions
