### ISSUE TITLE
Update all the examples & notebooks to use new APIs (14/July)

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2402]
**Describe the bug**
As we unified metrics APIs, @yiheng-wang-nv will simplify all the tutorials and examples to use the latest APIs when `decollate batch` feature is also merged.
Pending on this PR: https://github.com/Project-MONAI/MONAI/pull/2315

**Comment by Nic-Ma** [comment]
Mark: there are 3 tasks to update for all the examples and notebooks:
1. metrics API.
2. decollate batch data.
3. correct `pre transform` or `post transform` to `preprocessing transform` or `postprocessing transform`.

Thanks.

**Comment by yiheng-wang-nv** [comment]
I will start this task since https://github.com/Project-MONAI/MONAI/pull/2315#event-4953733589 has been merged.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Add another item:
4. Change `SegmentationSaver` and `TransformInverter` handlers to use `SaveImaged` and `Invertd` transforms instead.

Thanks.

**Comment by wyli** [comment]
addressed  by https://github.com/Project-MONAI/tutorials/pull/246 https://github.com/Project-MONAI/tutorials/pull/253 https://github.com/Project-MONAI/tutorials/pull/254
