### ISSUE TITLE
preprocessing/postprocessing

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2410]
**Describe the bug**
The terms in the APIs such as 'pre-transform' and 'post-transform' should be replaced by `preprocessing` and `postprocessing` to be consistent with the literature. The relevant docstrings should be reviewed and updated.

**Comment by ericspod** [comment]
I'm good with that renaming.

**Comment by Nic-Ma** [comment]
OK, let me cover this feature request in PR #2315 .

Thanks.

**Comment by wyli** [comment]
fixed in https://github.com/Project-MONAI/MONAI/pull/2315
