### ISSUE TITLE
Transforms not updating meta data

### ISSUE THREAD

**Issue by Spenhouet** [Project-MONAI/MONAI#2424]
**Is your feature request related to a problem? Please describe.**

I would have expected that every transform has as input the image and the `meta_data` dict.
This is not the case for many transforms. They do not update the `meta_data`.
This leads to inconsistencies and errors since after the transforms the `meta_data` is no longer valid.

For example:

- `AddChannel` adds a new channel but does not update the `dim`, `spatial_shape` or `original_channel_dim` in `meta_data`.
- `Spacing` returns the new affine but does not update the `dim`, `pixdim`, `affine` or `spatial_shape` in `meta_data`.

This is really frustrating. Some transforms are written very well while others are not that great.

**Describe the solution you'd like**

Please update the `meta_data` in all transformations. This would also add consistency if every transform expects and returns the `meta_data` dict.

**Comment by rijobro** [comment]
Hi @Spenhouet, 

I appreciate it is frustrating when functionality isn't quite how you expected/hoped. However, this is a freely-available, community-supported piece of open-source code. Implying that some contributors didn't care about doing things properly is rather unfair and borders on breaching our [code of conduct](https://github.com/Project-MONAI/MONAI/blob/dev/CODE_OF_CONDUCT.md) for "showing empathy towards other community members". 

I agree that the transforms aren't perfect, but we're working on them! Feel free to add PRs to improve them in line with the changes you'd like to see.

**Comment by Spenhouet** [comment]
> Implying that some contributors didn't care about doing things properly is rather unfair

Sorry, you are right. I updated my comment.

> I agree that the transforms aren't perfect, but we're working on them!

That is why I'm opening up this feature request. It seems there is some discussion necessary since not everyone seems to see the `meta_data` as necessary: https://github.com/Project-MONAI/MONAI/pull/2421
I would vote for making the meta data a first class citizen and including it in all transforms (as parameter and as return value even when there is no change).

**Comment by wyli** [comment]
I think it is a valid feature request, mainly for the spatial transforms. In fact, we are tracking the changes for the MapTransform using the InvertibleTransform interface https://github.com/Project-MONAI/MONAI/blob/a0afa604bbb5f4e673597c5ca833ba1fd4b8547e/monai/transforms/inverse.py#L23

we are not far from this feature after finishing the array class inverse https://github.com/Project-MONAI/MONAI/issues/1749

see also the discussion here https://github.com/Project-MONAI/MONAI/issues/140,

**Comment by wyli** [comment]
thanks, preliminary implementation is on the dev branch, MetaTensor handles pixdim/affine/original_channel_dim. https://github.com/Project-MONAI/MONAI/blob/40717509198909b444d9566052602b7db0cfd0cb/monai/data/meta_tensor.py#L47-L63
