### ISSUE TITLE
Support to set pos/neg crop ratio for every class

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2432]
**Is your feature request related to a problem? Please describe.**
Feature request from @myron .
currently, we can only set the ratio for foreground / background, can't set the ratio for every class.
Need to develop a new crop transform to support ratio list of every class.

**Comment by rijobro** [comment]
sounds like a great idea!

**Comment by Nic-Ma** [comment]
Update: I am developing a new transform to get the indices of every class and randomly select crop centers based on a list of ratios.

Thanks.
