### ISSUE TITLE
DynUNet docstring conflicts with default kwarg for res_block

### ISSUE THREAD

**Issue by zbarry** [Project-MONAI/MONAI#2456]
In the docstring for `DynUNet`, `res_block` is said to be set to `True` by default, but it is actually set to `False` in the method definition:

https://github.com/Project-MONAI/MONAI/blob/079fcd46c33dc5a81b398dd4b077c3bb7b647a7b/monai/networks/nets/dynunet.py#L99-L115

**Comment by Nic-Ma** [comment]
Hi @zbarry ,

Thanks for your interest here and feedback!
@yiheng-wang-nv could you please help take a look at this issue and update the doc-string or the code?

Thanks in advance.

**Comment by zbarry** [comment]
Thanks, both!
