### ISSUE TITLE
Align to Decathalon challenges - Showcasing SOA performance - Spleen - Replicate NoNewNet results in clean code.

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#246]

**Comment by tvercaut** [comment]
For the record, this is the nnU-Net paper:
https://arxiv.org/abs/1809.10486

Metrics on teh Decathlon challenge can be found in the paper or on the website (click on "show all metrics"):
https://decathlon.grand-challenge.org/evaluation/results/

The implementation is here:
https://github.com/MIC-DKFZ/nnUNet

**Comment by wyli** [comment]
also it's a subtask of https://github.com/Project-MONAI/MONAI/issues/78

**Comment by wyli** [comment]
initial implementation available at https://github.com/Project-MONAI/tutorials/tree/master/modules/dynunet_pipeline

**Comment by wyli** [comment]
please file new tickets for any follow-ups.
