### ISSUE TITLE
Support more backends in distributed operations

### ISSUE THREAD

**Issue by sandylaker** [Project-MONAI/MONAI#2468]
The current version of MONAI utilizes `torch.distributed` for `all_gather`, `all_reduce` etc., e.g. in **line 409** below. However, this will raise an Error when I launch the parallel programs in `ignite.distributed.Parallel` context with `horovod` or `xla` backend: `RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.` Is it better to replace all the `torch.distributed` operations with `ignite.distributed` ones? They have naive support for all the backends.

https://github.com/Project-MONAI/MONAI/blob/1a707f0226bfe10c000cc54ac87b35d50973e221/monai/utils/misc.py#L359-L423

**Comment by Nic-Ma** [comment]
Hi @sandylaker ,

Thanks for raising this topic.
Currently, we only use `torch` and `numpy` as must-have dependencies, so all the metrics, classification saver, etc. are developed based on PyTorch native dist APIs for data parallel.
I marked this ticket for working group discussion.

Thanks.

**Comment by wyli** [comment]
Perhaps for this ticket we should prefer the ignite's interface if they are available? https://github.com/Project-MONAI/MONAI/issues/2330 will it resolve this issue?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Currently, all the refactored metrics can be used in regular PyTorch program with `multi-processing` data-parallel support.
Do you mean to use ignite APIs for all the metrics instead? I think this feature request is the opposite of ticket #2330 ? Maybe raise a discussion in the internal meeting.
Please feel free to correct me if I misunderstood your comments.

Thanks.

**Comment by wyli** [comment]
I mean in the utility functions we can support both ignite and torch native, with ignite having a higher priority. Will it be feasible?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your explanation.
Seems like a good idea to enhance the multi-processing computation.
Let me try to enhance the dist utilities later, if no ignite installed, fallback to use `torch.dist` native APIs.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @sandylaker ,

I submitted PR: https://github.com/Project-MONAI/MONAI/pull/2492 to address this ticket.
Unfortunately, we don't have Horovod or XLA test environment, could you please help verify the above PR?

Thanks in advance.

**Comment by sandylaker** [comment]
@Nic-Ma Hi, I built the source code from your fork, and run a simple test with following script:

```python3
import torch
from monai.utils import evenly_divisible_all_gather
import ignite.distributed as idist
from argparse import ArgumentParser


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("--backend", default="horovod")
    parser.add_argument("--nproc_per_node", type=int)

    args = parser.parse_args()
    return args


def test(local_rank):
    device = idist.device()
    rank = idist.get_rank()

    x = torch.randn(rank, 5).to(device)
    x = evenly_divisible_all_gather(x, concat=True)
    assert x.shape[0] == sum(range(idist.get_world_size()))


if __name__ == "__main__":
    args = vars(parse_args())
    with idist.Parallel(**args) as parallel:
        parallel.run(test)
```
I run the script with horovod backend on my 4-gpu server, and no error occurred. In the script above, `x.shape[0]` is expected to be 6.

I don't have an XLA device, so cannot run the test with `xla` backend. But I suppose it should work.

Hope it helps.

**Comment by Nic-Ma** [comment]
Hi @sandylaker ,

Cool! Really appreciate your help here!

Thanks.

**Comment by vfdev-5** [comment]
@sandylaker for XLA quick checking we can use Google Colab and specify TPU as accelerator

**Comment by wyli** [comment]
Hi @Nic-Ma, perhaps we should add some unit tests with horovod? we've been providing examples in the tutorial repo using horovod https://github.com/Project-MONAI/tutorials/blob/master/acceleration/distributed_training/unet_training_horovod.py
then we should properly maintain this feature, what do you think?

**Comment by Nic-Ma** [comment]
> Hi @Nic-Ma, perhaps we should add some unit tests with horovod? we've been providing examples in the tutorial repo using horovod https://github.com/Project-MONAI/tutorials/blob/master/acceleration/distributed_training/unet_training_horovod.py
> then we should properly maintain this feature, what do you think?

Hi @wyli ,

Sure, I created ticket to track it: https://github.com/Project-MONAI/MONAI/issues/2507.
I will develop a separate PR later to enable Horovod tests in our CI.

Thanks.
