### ISSUE TITLE
Segmentation / Classification integration tests forget to use decollate

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#2493]
Now, post processing transforms assume the input to be channel first tensors, but in:
https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_integration_segmentation_3d.py#L149
It used batch first tensors.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Thanks for your finding.
Let me fix it ASAP.

**Comment by Nic-Ma** [comment]
Mark: this is a blocker issue for MONAI v0.6 release as classification task can't work with the `decollate` mechanism.

Thanks.
