### ISSUE TITLE
Minor code format issue in PatchEmbeddingBlock

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2495]
**Describe the bug**
If running `/black`, the change in the newly added PatchEmbeddingBlock will cause CI error.
https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/blocks/patchembedding.py
And there are also some other potential issues about the input args.

**Comment by Nic-Ma** [comment]
I will add more code checks to `PatchEmbeddingBlock` and format it in a quick PR.
Thanks.

**Comment by wyli** [comment]
I think this autofix breaks the type ignore command https://github.com/Project-MONAI/MONAI/pull/2492/commits/be33e85fe82674e90cd87508ddd080a7bc4c0eb3

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, it is just 1 issue in `PatchEmbeddingBlock`, but the root cause is that we should not add `type ignore` at all, the typehint is not correct.

Thanks.

**Comment by wyli** [comment]
Sure, I hope this new feature release get stuck at the details of (unstable) type checking, given that the code showed good performance on some segmentation tasks. Would be great if the 'type ignore' could be removed, but it's not an urgent request for now, please make sure it's a nonbreaking fix...cc @ahatamiz

**Comment by ahatamiz** [comment]
Hi @Nic-Ma and @wyli 

I think #2496 already addresses these issues. @Nic-Ma would you please confirm ? 

Thanks.

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

Let's close this ticket for now.
I will revisit all the related code to double confirm it, will reopen the ticket and submit PR if found any other issues.

Thanks for your review!

**Comment by ahatamiz** [comment]
Hi @Nic-Ma 

Sure. Thank you for tracking down the issue on the PatchEmbeddingBlock. We can certainly revisit again.
