### ISSUE TITLE
Transformation Implementations from Clara/NiftyNet to MONAI

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#251]

**Comment by JunMa11** [comment]
Dear @wyli ,

Thanks for your great work so much.
I'm a user of NiftyNet and want to turn to MONAI now.
I'm very excited that you have a plan to transform the implementations from NiftyNet.

When these [segmentation networks](https://github.com/NifTK/NiftyNet/tree/dev/niftynet/network) will be finished?

Thanks again for your fantastic work:)

Kindest regards,
Jun

**Comment by wyli** [comment]
many thanks @JunMa11 we are actively doing the migration, it'll take some time because we want to ensure the quality and usability of MONAI, based on the lessons we learned during building NiftyNet as well as the feedback from the MONAI consortium

**Comment by wyli** [comment]
this is mostly done, please open new tickets for further specific feature requests.
