### ISSUE TITLE
Exponential moving average (EMA) handler

### ISSUE THREAD

**Issue by sandylaker** [Project-MONAI/MONAI#2514]
**Is your feature request related to a problem? Please describe.**
Exponential moving averaging is a very import trick for training CNNs like EfficienNet, MobileNet-V3, or self-supervised learning models like MoCo, BYOL etc. Specifically, we keep an exponential moving smoothed version of weights, and use it for validation and inference.

**Describe the solution you'd like**
We can implement this function as an ignite handler.

**Describe alternatives you've considered**

**Additional context**

**Comment by sandylaker** [comment]
I can work on this feature and send a PR

**Comment by Nic-Ma** [comment]
Hi @sandylaker ,

Cool, welcome your contribution!

Thanks.

**Comment by wyli** [comment]
I'd encourage a pull request directly to pytorch-ignite, because it’s a generic feature, widely-applicable. But if ignite doesn't want to integrate it for any reason, monai can take it...

Cc @vfdev-5

**Comment by vfdev-5** [comment]
@wyli thanks a lot for pinging! Yes, that's can be a feature for pytorch ignite.

**Comment by sandylaker** [comment]
@wyli Sure, I will make a PR to ignite first.
