### ISSUE TITLE
Can't select branch when creating pull request from forked repo to MONAI repo

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2517]
**Please use MONAI's Discussions tab**
I am facing an Github issue since last Saturday that I can't select branch when creating a pull request from forked repo to MONAI repo or from MONAI repo to forked repo, it's always loading branches:
![image](https://user-images.githubusercontent.com/27533405/124407749-44cc0480-dd77-11eb-8661-4fd72ab89123.png)
Maybe some internet issue only at my side? @wyli @ericspod @rijobro @IsaacYangSLA How about yours?
I am temporarily creating branches in the MONAI repo to work directly today.

Thanks in advance.

**Comment by rijobro** [comment]
Is it possibly a bug because `master` no longer exists? We switched to `main` and `dev` now.

**Comment by rijobro** [comment]
![image](https://user-images.githubusercontent.com/33289025/124447263-1a7b4680-dd79-11eb-9711-02a838b13298.png)

Mine doesn't seem to be permanently loading, although in this example I did the PR in the opposite direction from you.

**Comment by rijobro** [comment]
![image](https://user-images.githubusercontent.com/33289025/124447879-b86f1100-dd79-11eb-9fa8-9d322e0fed41.png)

Actually, you're right! It only works for me if I use the default forks/branches when creating a PR. If I try to modify, I get the same loading page you do...

**Comment by Nic-Ma** [comment]
Thanks @rijobro for confirming the issue, @wyli have you seen this issue in Github before? Maybe some Github settings updated during the weekend?

Thanks.

**Comment by wyli** [comment]
I created a pull request from my fork to project-monai, looks like it works fine. I'm not aware of any github settings update recently

**Comment by wyli** [comment]
I can replicate this issue if at least one of the branches in the comparison doesn't exist...
@Nic-Ma your fork doesn't have a `dev` branch, the default is `master`
@rijobro  your fork doesn't have a `dev` branch, the default is `default`

perhaps github could improve the error msg but I'm closing this ticket here

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Cool! Thanks for your finding! I created `dev` branch and renamed `master` to `main`, now I can get the branch list.

Thanks.
