### ISSUE TITLE
Deepgrow `Interaction` is not compatiable with `decollate_batch` for v 0.6.0 (8/July)

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#2525]
**Describe the bug**
In deepgrow tutorial (https://github.com/Project-MONAI/tutorials/blob/master/deepgrow/ignite/train.py#L201), we can see there are two groups of transforms: `pre_transforms` and `click_transforms`, and `click_transforms` will be used in `monai.apps.deepgrow.interaction.Interaction`. So far, this way is not compatiable with our `decollate_batch` logic.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Thanks for your issue report.
I am updating the handlers and iteration of DeepGrow, will try to fix it ASAP.

Thanks.
