### ISSUE TITLE
AssertionError: labels should have a channel with length equal to one.

### ISSUE THREAD

**Issue by rsreetech** [Project-MONAI/MONAI#2540]
I am getting this AssertionError: labels should have a channel with length equal to one when trying to run the Med_NIST tutorial example on google collab
AssertionError                            Traceback (most recent call last)
<ipython-input-11-da859643f6a3> in <module>()
     35 
     36 
---> 37             y_onehot = to_onehot(y)
     38             print()
     39             y_pred_act = act(y_pred)

1 frames
/usr/local/lib/python3.7/dist-packages/monai/networks/utils.py in one_hot(labels, num_classes, dtype, dim)
     58 
     59     if sh[dim] != 1:
---> 60         raise AssertionError("labels should have a channel with length equal to one.")
     61 
     62     sh[dim] = num_classes

AssertionError: labels should have a channel with length equal to one.

Any workardound for this error

**Comment by wyli** [comment]
thanks for reporting this, the notebook is now rectified.

for reference, the change is mainly at the postprocessing:
```py
auc_metric = ROCAUCMetric()  # before the training loop
...
y_onehot = [to_onehot(i) for i in y]
y_pred_act = [act(i) for i in y_pred]
auc_metric(y_pred_act, y_onehot)
auc_result = auc_metric.aggregate()
```
