### ISSUE TITLE
StatsHandler doesn't print iteration level results (7/July)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2544]
**Describe the bug**
previously running the tutorial on colab prints the iteration results:
https://colab.research.google.com/drive/1boqy7ENpKrqaJoxFlbHIBnIODAs1Ih1T
but the current weekly version doesn't work.

probably related to this check?
https://github.com/Project-MONAI/MONAI/blob/b4fca1d12245e8d7950ae4782058dc3cea6a9775/monai/handlers/stats_handler.py#L192

**Comment by wyli** [comment]
could you please help with this @Nic-Ma?

**Comment by Nic-Ma** [comment]
Sure, let me make a quick fix for it.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think the issue had been fixed with this PR in dev: https://github.com/Project-MONAI/MONAI/pull/2524?
Could you please help try again the notebook with latest dev and  `output_transform=from_engine(["loss"], first=True)`?

Thanks in advance.

**Comment by wyli** [comment]
thanks, it works now (the currently weekly release doesn't include the patch).
