### ISSUE TITLE
enhance unetr docstring with examples

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2548]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/2547

<div type='discussions-op-text'>

<sup>Originally posted by **jhkang0526** July  7, 2021</sup>
hello,

I recently saw about the UNETR. 

Is it currently possible to apply to 3D data?

If possible, how should I use it?

Thanks,

</div>

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

Thanks for providing the nice `UNETR` feature in MONAI v0.6.
Could you please help self-assign this ticket?

Thanks in advance.

**Comment by ahatamiz** [comment]
Hi @Nic-Ma 
Sure, however I don't think I have been given permission to self-assign. I don't see the option yet. Would you mind provide that permission ? 

I will submit a new PR regarding this. 

Thanks,
Ali

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

I assigned the ticket to you.

Thanks in advance.

**Comment by ahatamiz** [comment]
Thank you @Nic-Ma
