### ISSUE TITLE
Registration benchmarking - image loss

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/MONAI#2565]
**Is your feature request related to a problem? Please describe.**
MONAI currently have implemented 2 image similarity loss for registration application:

- LocalNormalisedCrossCorrelationLoss
- GlobalMutualInformationLoss

Both loss has been tested numerically (comparing with DeepReg) in the unity tests. However, it would be great to include the following tests:

- More tests on numerical accuracies by comparing it with more well established implementations
- Speed comparison

This issue is built for the detailed discussions on designing the tests. All kinds of thoughts and advices are welcomed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kate-sann5100** [comment]
@YipengHu

**Comment by YipengHu** [comment]
this may be used as reference: https://github.com/ANTsX/ANTsPy/blob/master/ants/utils/image_similarity.py
