### ISSUE TITLE
Image writer with itk backend to support more output image formats

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2620]
**Is your feature request related to a problem? Please describe.**
The `SaveImage` transform should be extended to support writing output in different formats using ITK.
https://github.com/Project-MONAI/MONAI/blob/830f8bb34532f63e188b43738f804fff6f059d5b/monai/transforms/io/array.py#L260-L261

the current nifti output doesn't work well with Slicer https://github.com/Project-MONAI/MONAILabel/issues/211

see also https://github.com/InsightSoftwareConsortium/ITK/issues/2663

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I have a question about the feature request of this ticket:
Currently, we have `nifti_saver` & `nifti_writer` and `png_saver` & `png_writer`, maybe there are 2 options:
1. If we just want to add support to save in DICOM format, we can add `dicom_saver` & `dicom_writer` based on ITK APIs.
2. If want to support many other formats, I think we need to totally refactor the saving part and make it just like the inverse of the `ImageReader` and `LoadImage`:
(1). Remove `nifti_saver` & `nifti_writer` and `png_saver` & `png_writer`.
(2). Add `nibabel_writer` for NIfTI, `pil_writer` for PNG, JPG, JPEG, BMP, `itk_writer` for any other formats.
(3). Use `SaveImage` transform as high-level API, mapping to `LoadImage`.

What do you think or you guys have other ideas?

Thanks.

**Comment by wyli** [comment]
I think as an initial step we could add a minimal itk_writer and make it an option in SaveImage in v0.7. The goal is to encourage the use of SaveImage and we'll refactor the underlying implementation later (beyond 0.7) -- For refactoring the writer, option 2 looks good, we still need to review the quality of these writer APIs and probably get comments/proposals from the working groups.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Plan makes sense, we can develop a `itk_writer` and call it in `SaveImage` directly instead of a `itk_saver` layer. When it's done in v0.7, we can refactor `nifti_writer` & `nifti_saver` to `nibabel_writer`, and refactor `png_writer` & `png_saver` to `pil_writer` based on the same pattern of `itk_writer`.
I can develop a PR for `ITKWriter` with the similar design of `ITKReader`, may not support many formats in the first step.

Thanks.
