### ISSUE TITLE
Inverse RandAffined transformation

### ISSUE THREAD

**Issue by chrisfoulon** [Project-MONAI/MONAI#2643]
**Describe the bug**
Calling .transform.inverse(data_dict) on a monai.data.Dataset when RandAffined was called on the image causes the following Exception: 
ValueError: ['bilinear'] is not a valid GridSampleMode
In the === Transform input info -- method === when it crashed I see:
Value: [{'class': ['ResizeWithPadOrCropd'], 'id': tensor([139679491139472]), 'orig_size': [tensor([91]), tensor([109]), tensor([91])], 'extra_info': {'mode': ['constant']}}, {'class': ['RandAffined'], 'id': tensor([139679491140304]), 'orig_size': [tensor([96]), tensor([128]), tensor([96])], 'extra_info': {'affine': tensor([[[ 0.9983,  0.0368,  0.0000, -0.0198],
         [ 0.0000,  0.9968, -0.0795,  0.0000],
         [ 0.0000,  0.0795,  0.9968,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]], dtype=torch.float64), **'mode': ['bilinear'],** 'padding_mode': ['border']}, 'do_transforms': tensor([True])}]

I dug a bit in the github files and it seems that the .transform.inverse function of Dataset returns lists of parameters but RandAffined.inverse expects str or GridSampleMode. 

**To Reproduce**
It happened with monai 0.5 and well as 0.6.

**Expected behavior**
Perform the inverse affine transformation

Please tell me whether I am doing something wrong or if this is actually something to be fixed. 

Thank you,
Chris.

**Comment by Nic-Ma** [comment]
Hi @chrisfoulon ,

Thanks for your feedback.
Could you please help share your full test program to debug? Then I will try to identify the issue ASAP.

Thanks.

**Comment by Nic-Ma** [comment]
I feel maybe you executed `inverse` on a batch data directly, if so, please try to decollate the batch data first, then execute `Invertd` transform for every item, you can refer to:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_inference_dict.py#L108

Thanks.

**Comment by chrisfoulon** [comment]
Here's my code roughly, stripped from unrelated pieces:

```val_ds = Dataset(image_list, transform=val_img_transforms)
model = my_load_UNet_model()
model.eval()
for val_data in val_loader:
    inputs = val_data['image'].to(device)
    outputs = model(inputs)
    outputs = post_trans(outputs) #  Only sigmoid and AsDiscrete 
    # [0] because the last transformation (so the first to be inverted) is ResizeWithPadOrCropd and it takes a 4D tensor
    val_data['image'] = val_data['image'].to(device)[0]
    val_data['label'] = outputs[0]
    inverted_output_dict = val_ds.transform.inverse(output_dict_data)
```
I will try your suggestion. The only thing is that, this way works with other transformations like ResizeWithPadOrCropd
But yeah, maybe I am not using it as it was intended. I was struggling to find some examples with inverse transformations, thanks for that.

**Comment by Nic-Ma** [comment]
Hi @chrisfoulon ,

Your current program is not recommended way to invert, and need to decollate batch first if running with MONAI 0.6.
Could you please help adjust based on this tutorials?
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_inference_dict.py#L108
For why need to decollate and how to migrate from MONAI 0.5 to 0.6, you can refer to:
https://github.com/Project-MONAI/MONAI/wiki/v0.5-to-v0.6-migration-guide

Thanks.
