### ISSUE TITLE
RandBiasField missing np.exp

### ISSUE THREAD

**Issue by JustinSzeto** [Project-MONAI/MONAI#2644]
**Describe the bug**
The bias field generated by `RandBiasField._generate_random_field` ([link](https://github.com/Project-MONAI/MONAI/blob/0ad9e73639e30f4f1af5a1f4a45da9cb09930179/monai/transforms/intensity/array.py#L434)) should be exponentiated, as done so in [NiftyNet's implementation](https://github.com/NifTK/NiftyNet/blob/935bf4334cd00fa9f9d50f6a95ddcbfdde4031e0/niftynet/layer/rand_bias_field.py#L99).

**To Reproduce**
```
import matplotlib.pyplot as plt
import numpy as np
from monai.transforms import RandBiasField

rand_bias_field = RandBiasField()
arr = np.ones((1,100,100))

bias_field = rand_bias_field(arr)

plt.figure(figsize=(12,6))
plt.subplot(121)
plt.imshow(bias_field[0])

plt.subplot(122)
plt.hist(bias_field.flatten())
plt.show()
```
![image](https://user-images.githubusercontent.com/20669652/126690750-2d55cbcc-42ee-44bf-828d-7b2738a5b2dd.png)

As shown on the histogram on the right, the values generated by the bias field are around 0 and can also be negative. This is not a proper bias field and multiplying an image by this bias field may invert values.

**Expected behavior**
The bias field should have values around 1. This is usually done by exponentiating the bias field since the bias field generated from the polynomial basis function is actually the log-transformed bias field (Refer to [last equation in section 3.1.1](https://www.sciencedirect.com/science/article/pii/S1361841517300257?via%3Dihub) and the NiftyNet implementation of RandBiasField (linked above). 

```
import matplotlib.pyplot as plt
import numpy as np
from monai.transforms import RandBiasField

rand_bias_field = RandBiasField()
arr = np.ones((1,100,100))

bias_field = np.exp(rand_bias_field(arr))

plt.figure(figsize=(12,6))
plt.subplot(121)
plt.imshow(bias_field[0])

plt.subplot(122)
plt.hist(bias_field.flatten())
plt.show()
```

![image](https://user-images.githubusercontent.com/20669652/126691848-dd9838a2-eb0f-4dca-8960-a13ef55113fc.png)

**Additional comments**
Are there any plans to make a batched Tensor-compatible implementation of RandBiasField so that this transform can theoretically be done on the GPU after batching? At the moment, the only critical numpy dependencies are the calls to `np.polynomial.legendre.leggrid2d` and `np.polynomial.legendre.leggrid3d`, but these can be easily implemented using PyTorch.

**Comment by wyli** [comment]
thanks for the detailed report @JustinSzeto, I'm fixing this in #2645.  
would be interesting to make the polynomials in PyTorch, I'll create another feature request for it.
