### ISSUE TITLE
Reimplement 4th place solution of RANZCR kaggle challenge (ETA 9/3)

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2648]
**Is your feature request related to a problem? Please describe.**
As offline discussed with the code author, plan to reimplement the solution of 4th place in RANZCR kaggle challenge with MONAI components and workflows:
https://www.kaggle.com/c/ranzcr-clip-catheter-line-classification/discussion/229706
- [x] Reproduce the existing pipeline with original code.
- [x] Implement the unsupported transforms and replace all transforms with MONAI transforms.
- [x] Replace network, loss, optimizer, etc. with MONAI components.
- [ ] Rewrite the training flow with MONAI workflows.

**Comment by Nic-Ma** [comment]
For the first step, will implement the `Cutout`, `LongestMaxSize`, `InvertImg` transforms, referring to `Albumentations` package.

Thanks.

**Comment by Nic-Ma** [comment]
Update: @yiheng-wang-nv already reproduced the similar metrics with single fold in both kaggle public LB and private LB, confirmed with the author.

Thanks.

**Comment by Nic-Ma** [comment]
Update for next near steps:
1. Replace the `CSV reading + OpenCV loading` logic with MONAI `CSVDataset + LoadImage transform` @yiheng-wang-nv .
2. Add `IntensityStats` transform to pre-compute the `max`, `mean`, `std` of intensity values of original input image, then other transforms can use it to adjust / clip the `scale` / `shift` parameters, etc. @Nic-Ma 
3. Replace all the albumentation transforms with MONAI transforms @yiheng-wang-nv .

Thanks.

**Comment by wyli** [comment]
Hi @Nic-Ma, not sure about the `IntensityStats` feature request, I thought a lambda function could easily address it. could you create a separate ticket to document it? for the other components, would be great to have a bit more details in separate tickets as well.

**Comment by Nic-Ma** [comment]
Sure, let me open some smaller tickets for items.

Thanks.

**Comment by Nic-Ma** [comment]
Update: @yiheng-wang-nv replaced all the transforms of the pipeline with MONAI transforms and tuned parameters, now it can get slightly better metrics in both the private and public leaderboards when trained on the same dataset:
```
MONAI transforms:
```
![image](https://user-images.githubusercontent.com/27533405/128530285-59c4e5f2-f243-4672-803a-576cccbeb685.png)
```
original pipeline:
```
![image](https://user-images.githubusercontent.com/27533405/128530487-d8d8982f-a664-42bc-88e8-9f2561d608b4.png)

Will try to train with this PR: https://github.com/Project-MONAI/MONAI/pull/2694 soon as it aligns with the original pipeline solution.

Thanks.

**Comment by yiheng-wang-nv** [comment]
> Update: @yiheng-wang-nv replaced all the transforms of the pipeline with MONAI transforms and tuned parameters, now it can get slightly better metrics in both the private and public leaderboards when trained on the same dataset:
> 
> ```
> MONAI transforms:
> ```
> 
> ![image](https://user-images.githubusercontent.com/27533405/128530285-59c4e5f2-f243-4672-803a-576cccbeb685.png)
> 
> ```
> original pipeline:
> ```
> 
> ![image](https://user-images.githubusercontent.com/27533405/128530487-d8d8982f-a664-42bc-88e8-9f2561d608b4.png)
> 
> Will try to train with this PR: #2694 soon as it aligns with the original pipeline solution.
> 
> Thanks.

FYI: these results are based on a single model trained on 80% of data. The data split comes from: https://www.kaggle.com/underwearfitting/how-to-properly-split-folds

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/301 workflow integration could be done based on further discussions
