### ISSUE TITLE
new documentation site theme?

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2655]
**Is your feature request related to a problem? Please describe.**
the current style of the documentation website is too compact and in my opinion it's not easy to read.
https://docs.monai.io/en/latest/index.html

**Describe the solution you'd like**
I had a quick setup for new sphinx themes such as:
https://monai-dev.readthedocs.io/en/new-doc-theme/

**Describe alternatives you've considered**
make customised functions to revise the current sphinx theme

**Additional context**
the new one
https://monai-dev.readthedocs.io/en/new-doc-theme/
 is also used by projects such as numpy, pandas
- https://pandas.pydata.org/docs/reference/index.html
- https://numpy.org/devdocs/reference/index.html

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think the new style looks good to me.
Thanks for the update.
