### ISSUE TITLE
Monai AsDiscrete with oneHot option set to true fails on after update

### ISSUE THREAD

**Issue by yang2lalang** [Project-MONAI/MONAI#2664]
I just made a new pull from the MONAI repo and my previous segmentation code has started failing.

I discovered in the AsDiscrete class, the line 

`img = one_hot(img, num_classes=_nclasses)`

was changed to 

`img = one_hot(img, num_classes=_nclasses, dim=0)`

This leads the one_hot conversion to fail on my data set of  torch.Size([4, 1, 128, 128, 128])

with error:

> Traceback (most recent call last):
> 
>   File "/home/okoli/notebooks/run3.py", line 354, in <module>
>     result = tr.train()
>   File "/home/okoli/notebooks/trainer.py", line 162, in train
>     self.evaluate()
>   File "/home/okoli/notebooks/trainer.py", line 553, in evaluate
>     val_outputs = self.post_label(val_labels)
>   File "/home/okoli/MONAI/monai/transforms/post/array.py", line 174, in __call__
>     img = one_hot(img, num_classes=_nclasses)
>   File "/home/okoli/MONAI/monai/networks/utils.py", line 81, in one_hot
>     raise AssertionError("labels should have a channel with length equal to one.")
> AssertionError: labels should have a channel with length equal to one.
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
>     main()
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
>     sigkill_handler(signal.SIGTERM, None)  # not coming back
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line

It seems the new update is expecting the Channel to be in dim=0 or the data to be 2D for making this conversion, but for my 3D dataset, Channel has to be at dim=1 or dim could be passed as a parameter

**Comment by Nic-Ma** [comment]
Hi @yang2lalang ,

Thanks for your interest here.
We enhanced the postprocessing transforms logic in MONAI v0.6, you can take a look at this doc to easily upgrade your program:
https://github.com/Project-MONAI/MONAI/wiki/v0.5-to-v0.6-migration-guide

Thanks.

**Comment by yang2lalang** [comment]
Okay, thanks i will use this guide
