### ISSUE TITLE
Class token (self.cls_token) in patchembedding block?

### ISSUE THREAD

**Issue by saruarlive** [Project-MONAI/MONAI#2677]
Hi,
I have found that class embedding (token,  self.cls_token ) is not applied in _patchembedding_ block used in _vit_ class.  The vision transformer article mentions it. Is there any reason not to add/concatenate the class token? 
source: [here](https://docs.monai.io/en/latest/_modules/monai/networks/blocks/patchembedding.html)

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

Could you please help share some comments about this question as you are expert on it?

Thanks in advance.

**Comment by ahatamiz** [comment]
Hi @saruarlive thank you for your comment. This version of ViT model was designed to serve as backbone for segmentation models and in particular the UNETR model. So it does not utilize class tokens. 

I will submit a new PR to support classification applications for ViT model and hence also add the class token.

**Comment by wyli** [comment]
Tracked by https://github.com/Project-MONAI/MONAI/issues/2682, I'm closing this
