### ISSUE TITLE
Add parameter explanations for `Affine`, `AffineGrid` and others

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#2688]
So far, there are no explanation for the parameter: `shear` and `scale` in `Affine`, `AffineGrid`, `create_shear` and `create_scale`. Users may not know what is `shear`, what is `scale`. 

In addition, I suggest to add value ranges for all parameters belong to `Affine`, thus users can understand what kind of values can be input.

**Comment by Nic-Ma** [comment]
Sure, I will update the related docs and highlight reasonable input values.

Thanks.
