### ISSUE TITLE
remove the hard-coded 3d constraint for resnet

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2715]
**Is your feature request related to a problem? Please describe.**
the resnet implementation is hardcoded for 3d only while the network API support both 2d and 3d
https://github.com/Project-MONAI/MONAI/blob/62425d7d8809d129b4f35a51f425d02d325bd816/monai/networks/nets/resnet.py#L230

all the underlying blocks should be reviewed and refined to support both 2d and 3d.

**Comment by yiheng-wang-nv** [comment]
Hi @Douwe-Spaanderman , could you please help for this task? I do not understand the parameter `shortcut_type`.
