### ISSUE TITLE
NiftiSaver supports save the cropped case

### ISSUE THREAD

**Issue by JiYuanFeng** [Project-MONAI/MONAI#2720]
Hi, thank you for your nice work. It's possible to support saving cropped data via the NiftiSaver (align to original data)?
For example, we always crop foreground regions in the MRI data. And the transformation func provides related information.

![image](https://user-images.githubusercontent.com/20653249/128624109-92e5b384-f391-4087-8f82-ceaca149ec5c.png)

And we can use this one to align to original data. Thank you

**Comment by Nic-Ma** [comment]
Hi @JiYuanFeng ,

Thanks for your interest and experiments with MONAI.
Actually, you can invert the preprocessing transforms of `image` on the `prediction` to restore the original shape and save.
(For `crop` transform, it will pad, for `pad` transform, it will crop)
Refer to this this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_inference_dict.py#L70

Thanks.

**Comment by JiYuanFeng** [comment]
Hi, Got it and thanks for the information
