### ISSUE TITLE
Create Docs landing page

### ISSUE THREAD

**Issue by zephyrie** [Project-MONAI/MONAI#2735]
**Is your feature request related to a problem? Please describe.**
The website only links to MONAI Core docs

**Describe the solution you'd like**
Create a landing page for Docs so that users can navigate to all MONAI Docs easily

**Comment by zephyrie** [comment]
Added docs page with MONAI Core and MONAI Label cards.  

Needed to add a CSS height fix to make the footer float at the bottom.

**Comment by wyli** [comment]
Addressed by https://github.com/Project-MONAI/project-monai.github.io/pull/19
