### ISSUE TITLE
Fix short page CSS/HTML 

### ISSUE THREAD

**Issue by zephyrie** [Project-MONAI/MONAI#2736]
**Describe the bug**
With the current CSS/HTML structure, short pages don't fully extend the footer to the bottom of the page.  This makes it look weird for pages with little content (upcoming docs landing page)

**Describe the solution you'd like**
Create a wrapper around each page and expand on the CSS to take up 100% height regardless of content length

**Comment by zephyrie** [comment]
I added a short/hacky fix for this issue for the docs page using inline CSS on the main section to fix this issue.  We can address this better when we work on our redesign.

**Comment by wyli** [comment]
Addressed by https://github.com/Project-MONAI/project-monai.github.io/pull/19
