### ISSUE TITLE
Add option for rounding via a transform

### ISSUE THREAD

**Issue by Spenhouet** [Project-MONAI/MONAI#2746]
**Is your feature request related to a problem? Please describe.**

Storing NIfTI images is often not done in the right data type (because it is forgotten). I had the issue multiple times that a label / segmentation image which is supposed to only consist of integer values was stored as float and values had slight rounding errors like containing 0.9999999 instead of 1.
When this is loaded with `LoadImage(dtype=np.int16)`, this will get set to 0 instead of 1 since `LoadImage` does only do a `.astype` and this will simply cut of the value.
This is a very hard to find issue if this happens.

**Describe the solution you'd like**

- One option could be to add a rounding option to `LoadImage`.
- We could extend `AsDiscrete` with a rounding option.
- It could also be added to `CastToType`
- Another option might be to have a specific `LoadLabels` or `LoadDiscreteImage` transform

The first option is closed to the issue I described but the rounding seems a bit "out of place".
It definitely fits to `AsDiscrete` but for loading label data I would always need to do:

```python
Compose([
    LoadImaged(...),
    AsDiscreted(..., round_to=0),
    CastToTyped(dtype=np.int16),
])
```

I would be in favor of having an explicit  `LoadLabels` or `LoadDiscreteImage` transform. This is what I'm already using in my local implementation.

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

Thanks for your feature.
I feel adding a `round` option to `AsDiscrete` transform may be the most suitable method.
@wyli @ericspod @rijobro , what do you guys think? If no other comments or ideas, I can do a PR for it soon.

Thanks.

**Comment by wyli** [comment]
yes, AsDiscrete could have a rounding method option. thanks for the report, I think we should also update the tutorial to show the usage.

**Comment by Nic-Ma** [comment]
Sure, I will add this option in a quick PR.

Thanks.

**Comment by rijobro** [comment]
If the original problem is that the datatype is lost when we read in the image, would the simplest solution not be to store the datatype in the dictionary of meta data?

**Comment by Spenhouet** [comment]
> If the original problem is that the datatype is lost when we read in the image, would the simplest solution not be to store the datatype in the dictionary of meta data?

No, the issue is that a NIfTI file is simply stored as float instead of explicitly as integer (human error). For segmentation images we only expect integers. Therefore a 

1. Load as float image
2. Round values
3. Cast type to integer

is the savest way to load label / segmentation data.

**Comment by Spenhouet** [comment]
I tested the implementation. Thanks :)
