### ISSUE TITLE
GlobalMutualInformationLoss with different bin distribution

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/MONAI#2755]
**Is your feature request related to a problem? Please describe.**
The current implementation of GlobalMutualInformationLoss can only apply Parzen windowing with bins distributed evenly between 0 and 1 instead of customise bins according to the input distribution.
This lead to two problems:
1) The inputs (`target` and `pred`) must range between 0 and 1
2) It is hard to benchmark this loss against the implementation by other packages (e.g antspyx)

**Describe the solution you'd like**
Reimplement GlobalMutualInformationLoss.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wyli** [comment]
Thanks, I've added this to the image registration milestone.

**Comment by kate-sann5100** [comment]
After searching, I have found the following mutual information implementations by established repositories:

1. Scikit-image([`skimage.metrics.normalized_mutual_information`](https://scikit-image.org/docs/dev/api/skimage.metrics.html#skimage.metrics.normalized_mutual_information))
2. NiftiReg implemented normalised mutual information
3. ANTsPY([`ants.image_mutual_information`](https://antspy.readthedocs.io/en/latest/registration.html?highlight=mutual#ants.image_mutual_information))
4. ITK
    (`itkJointHistogramMutualInformationImageToImageMetric`
    `itkNormalizedMutualInformationHistogramImageToImageMetric`
    [`itkMattesMutualInformationImageToImageMetric`](https://github.com/ANTsX/ANTsPy/blob/master/ants/lib/LOCAL_antsImageMutualInformation.cxx))

The most similar implementation to ours is `itkMattesMutualInformationImageToImageMetric`, while `ants.image_mutual_information` is its python wrapper.

**Comment by kate-sann5100** [comment]
The main difference is that while Mattes mutual information adopts B-Spline kernel to calculate the weight each voxel adds to respective bins, our implementation(similar to DeepReg and VoxelMorph) adopts Gaussian probability.

**Comment by kate-sann5100** [comment]
The following steps are planned:

1. Implement B-Spline kernel as an option, together with gaussian prob (our original implementation).
2. Benchmark our implementation with B-Spline kernel with `ants.image_mutual_information`. This could be achieved either by getting the same result when using the same input or show changes in same directions as the input changes. 
3.  Benchmark our implementation with Gaussian probability against B-Spline kernel by adjusting the `sigma` parameter.

**Comment by kate-sann5100** [comment]
Current and future progress will be uploaded to this pull request https://github.com/Project-MONAI/MONAI/pull/2847

**Comment by kate-sann5100** [comment]
@wyli @YipengHu

**Comment by kate-sann5100** [comment]
- The B-Spline kernel has been implemented. (updated in pull request [#2847](https://github.com/Project-MONAI/MONAI/pull/2847), but unit test is to be written.)
- The following image visualises the MattesMutualInformation calculated on an image and itself after translation (implemented with `monai.transforms.Affined(translate_params=(i, i, i))`) at different value of translate param `i` by our and ANTsPY's implementation.
- Though value difference occurs between our and ANTsPY's implementation
- We observe a monotonic increase in loss as the translation param `I` increases
- Moreover, the difference between our and ANTsPY's implementation decreases as the loss increases

**Comment by kate-sann5100** [comment]
![Unknown-2](https://user-images.githubusercontent.com/44606435/132770626-d8e553c5-a4ea-4af0-ab77-928edd01ef6d.png)

**Comment by YipengHu** [comment]
- although not expecting otherwise, maybe try the other two scenarios to be comprehensive: 
1. varying the three parameters independently with randomly sampled, fixed the other two
2. varying all three randomly than plot the sorted Euclidean distance vs. MI.
- looking at the graph, it may be trivial, but provide a piece of stats for testing monotonic relationship, perhaps Spearman rank-order correlation? 
@kate-sann5100

**Comment by YipengHu** [comment]
> looks cool, after the verifications, if we can reproduce the blue line in the unit test, it'll be a nice mile stone, what do you think?

Agreed.

**Comment by YipengHu** [comment]
Fine with me, although the equations do not show up well on my dark theme.
![2021-10-30 (2)](https://user-images.githubusercontent.com/2588157/139510293-16754fbc-a28b-431d-81f4-427f4a6d7518.png)
