### ISSUE TITLE
`AutoEncoder` does not have docstrings

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#2772]
Hi @rijobro , I just found the `AutoEncoder` and `VarAutoEncoder` classes does not have docstrings, should we add? Thanks!

**Comment by rijobro** [comment]
@ericspod I ported this from ptproto, was it based on a particular implementation or should I write general docstrings?

**Comment by ericspod** [comment]
I don't have specific docstrings for these, they were meant to be basic base level implementations that use template methods to define the network structure like the way our UNet works. It would be great if you could add some basic info on the arguments and what the `_get_*` methods do. Thanks!
