### ISSUE TITLE
Add tutorial for multiple instance learning (MIL) code for 2D pathology WSI classification (ETA 11/12/2021)

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#2781]
Add implementation of "Accounting for Dependencies in Deep Learning based Multiple Instance Learning for Whole Slide Imaging"

Input format: 2D TIFF (WSI)
Output format: class label

**Comment by myron** [comment]
Preliminary draft PR were added to tutorials. working on moving some components into monai core

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/431
