### ISSUE TITLE
Tensor computation for Brats transforms

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2819]
**Is your feature request related to a problem? Please describe.**
Hi @rijobro ,

Thanks for your great work on the Tensor-based transforms.
We are working on optimizing the Brats tutorial performance:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/brats_segmentation_3d.ipynb
And there are several random transforms in it, it may be helpful to move data to GPU Tensor, so is it possible to add Tensor support for the below 4 transforms first?
```
RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0),
NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
RandScaleIntensityd(keys="image", factors=0.1, prob=1.0),
RandShiftIntensityd(keys="image", offsets=0.1, prob=1.0),
```
I am not sure whether you have implemented them in Tensor locally?

Thanks in advance.

**Comment by rijobro** [comment]
Hi @Nic-Ma, I've just [posted](https://github.com/Project-MONAI/MONAI/pull/2278#issuecomment-903651666) the current backend of the transforms that I'm proposing to update to MONAI. As you can see, `RandFlip` will use torch.Tensor under the hood, and the other 3 transforms are ambivalent to torch/numpy input.

I will prioritise getting these into MONAI as quickly as possible, once the [current PR](https://github.com/Project-MONAI/MONAI/pull/2815) is merged. If you could help with the code review for that, I'll move onto the next ASAP.

**Comment by Nic-Ma** [comment]
Cool, sounds great! Thanks very much for your quick help!

**Comment by Nic-Ma** [comment]
- [ ] RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0)
- [ ] NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True)
- [ ] RandScaleIntensityd(keys="image", factors=0.1, prob=1.0)
- [ ] RandShiftIntensityd(keys="image", offsets=0.1, prob=1.0)
