### ISSUE TITLE
type annotation `NdarrayOrTensor`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2823]
**Is your feature request related to a problem? Please describe.**
`NdarrayOrTensor` should be replaced by a type variable such as `NdarrayTensor`
this will ensure advanced type checks for correctness however it might not be supported by all the tools such as pytype, mypy

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/93d467d00920aa3a27d46f3697a92a13c4866e74/monai/config/type_definitions.py#L65-L76

this is a follow up of https://github.com/Project-MONAI/MONAI/pull/2815

**Comment by Nic-Ma** [comment]
Currently, I think we used `# type: ignore` as a temp solution for many places, will also need to update them.

Thanks.

**Comment by rijobro** [comment]
I propose unifying the two to `NdarrayTensor = Union[np.ndarray, torch.Tensor]` and deleting `NdarrayOrTensor`. I tried this locally and there are a few changes that need to be made, but works for the most part.
