### ISSUE TITLE
dataloader 

### ISSUE THREAD

**Issue by yy97831** [Project-MONAI/MONAI#2830]
Hi

I think the dataloader will lead to memory leak when use both num_workers and pin_memory, the warning is as below:

    Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)

it happened when I was training a GAN

**Comment by Nic-Ma** [comment]
Hi @yy97831 ,

Thanks for your interest here.
I think this is a known PyTorch issue, PyTorch will fix it in the next version.

Thanks.

**Comment by yy97831** [comment]
ok thanks for the info : )

**Comment by yy97831** [comment]
@Nic-Ma  sorry just one more questions, do you by any chance know when is the next version coming up? Thanks

**Comment by Nic-Ma** [comment]
Hi @yy97831 ,

Sorry I am not very sure about PyTorch schedule, maybe you can check PyTorch Github repo for it.

Thanks.
