### ISSUE TITLE
enable multiple github runners on the test server

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#284]
**Is your feature request related to a problem? Please describe.**
the test server has eight GPUs, but the ci workflows only use two (hard-coded to device 0, 1). 

**Describe the solution you'd like**
would be great to set up 4 github runners on the server. so that it can accept concurrent CI jobs, to make full use of the server.

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/setupapp.yml#L27
https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/pythonapp.yml#L49

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

Currently, we already have many CI tests and it takes a long time to complete all, especially when running several PRs together. So we disabled several tests for PR.
Could you please help enable 4 runners on the CI server? I believe it should obviously help.
Thanks.

**Comment by IsaacYangSLA** [comment]
Three extra runners were added.  Their customized labels are runner1, runner2 and runner3.
