### ISSUE TITLE
TCIA Image and Adjunct Patient Data Dataset

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2877]
**Is your feature request related to a problem? Please describe.**
This is part of https://github.com/Project-MONAI/MONAI/discussions/2212, as a follow-up of https://github.com/Project-MONAI/MONAI/issues/2310

this ticket looks for a prototype of an "application-level" command such as 
```python
monai.apps.CsvTciaDataset("ISPY1_Combined.csv",["M","N","P"],["AM"],["AE"],"/tmp","training",transforms)
```
to 
- fetch metadata ([this file is an curated example](https://drive.google.com/file/d/1HQ7BZvBr1edmi8HIwdG5KBweXWms5Uzk/view?usp=sharing); as described in #2212 Section C step 2)
- fetch the image data according to the metadata (via the rest API; doc: https://wiki.cancerimagingarchive.net/display/Public/TCIA+Programmatic+Interface+REST+API+Guides)

More info about downloading:

>  the downloading from TCIA via Python in this notebook is leveraging https://github.com/lescientifik/tcia_downloader which is using a version of our API that's about to be upgraded.  In order to use the newer version of the REST API I think you'll need to update https://github.com/lescientifik/tcia_downloader/blob/master/src/tcia.py with a new "TCIA_ENDPOINT" in this line:
> 
> TCIA_ENDPOINT = (
>     "https://services.cancerimagingarchive.net/services/v3/TCIA/query/getImage")
> 
> We're still finalizing the documentation updates on our site, but I believe that should now be "https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage".
> 

As a starting point, the implementation will be in the tutorial repo.

**Comment by Nic-Ma** [comment]
This PR implemented the first step according to the plan:
https://github.com/Project-MONAI/tutorials/pull/342

Thanks.

**Comment by wyli** [comment]
closing in favor of https://github.com/Project-MONAI/MONAI/issues/4258
