### ISSUE TITLE
Choice of slice for initial seed point placement in deepgrow

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAI#2882]
In Sakinis et al., Interactive segmentation of medical images through fully convolutional neural networks, they describe a method for choosing the initial seed point for the 2D case, whereby the seed point will be placed in the inner most part of the region to be segmented with a higher probability.

To extend to 3D, the MONAI implementation of deepgrow finds all slices containing label using the FindAllValidSlicesd transform, and then in the AddInitialSeedPointd transform, a slice is chosen at random for the seed point placement:

https://github.com/Project-MONAI/MONAI/blob/7bfa428e82dbae5adc4d280dbb892cb9ce1bed5a/monai/apps/deepgrow/transforms.py#L102

In line with the thinking of Sakinis et al., would it be better to choose the middle slice with the highest probability rather than any slice with equal probability? This would avoid seed point being placed on an edge slice.

Happy to create a PR if there is agreement.

**Comment by Nic-Ma** [comment]
Hi @SachidanandAlle ,

Could you please help share some comments and guide here?

Thanks in advance.

**Comment by SachidanandAlle** [comment]
> In line with the thinking of Sakinis et al., would it be better to choose the middle slice with the highest probability rather than any slice with equal probability? This would avoid seed point being placed on an edge slice.

The initial ideas was to replicate user behavior.  When the user gets the image to annotate/click he would randomly pick any slice and start clicking.. better to avoid forcing him to go with the middle slice and place a seed point..

**Comment by pritesh-mehta** [comment]
Good point. Ok I agree with the current functionality. I'll close this :)
