### ISSUE TITLE
 Pathology Transforms inherit `torch.nn.Module`

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#2884]
**Is your feature request related to a problem? Please describe.**
While we are working on improving Digital Pathology pipelines, there is a need to chain our transforms with torchvision transforms and run them on them GPU. For some reason, implementing it using `ToDevice` and `TorchVision` transform did not show an improvement whereas using the same torchvision transforms and chaining them with the model (using `nn.Sequential` showed a speed up.

**Describe the solution you'd like**
Implement #2883 for all pathology transforms.
1. Derive all transform from `torch.nn.Module` instead of `Transform`
2. Implement `forward` for all transforms instead of `__call__`
3. Make all of them work with `torch.Tensors`

This solution should not have any impact on the rest of MONAI and should work with full backward compatibility.

**Comment by drbeh** [comment]
Hi @wyli @Nic-Ma, 
What do you think about it? This can give us an improved runtime for digital pathology pipeline and it shouldn't have any effect on anything else.
Thanks

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Thanks for raising this topic, `torch.Tensor` support is a main topic in MONAI v0.7, but we don't support `nn.Module` so far.
I didn't quite understand why "_implementing it using ToDevice and TorchVision transform did not show an improvement whereas using the same torchvision transforms and chaining them with the model (using nn.Sequential showed a speed up._"
Could you please help share the transforms part of your test program and the test results to help understand it?

Thanks in advance.

**Comment by wyli** [comment]
I think you can implement extensions of `nn.Module` and try to use them directly in the preprocessing. The basic API of monai dataset and loader should be compatible with `nn.Module` (since they are callable), but I'm not sure about the cache-based preprocessings.

**Comment by drbeh** [comment]
@Nic-Ma @Warvito, as we discussed in our meeting, the main benefit that it can provide us with is to chain the transforms with the model (using `nn.Sequential`) and run it on the GPU.

It seems that the main reason that we are getting more speedup in this manner is that the transforms are being applied on the batch of images instead of individual one but I will look more into this and see why using `ToDevice` and `Compose` did not give us a significant speedup. Will keep you posted.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

And I think we need to check the speedup when achieving the same target metrics.

Thanks.
