### ISSUE TITLE
ImportError: cannot import name 'NiftiDataset' from 'monai.data' (/usr/local/lib/python3.7/dist-packages/monai/data/__init__.py)

### ISSUE THREAD

**Issue by Sebagam** [Project-MONAI/MONAI#2886]
Hi all,

When trying to run MONAI on google colab:

ImportError: cannot import name 'NiftiDataset' from 'monai.data' (/usr/local/lib/python3.7/dist-packages/monai/data/__init__.py)

This issue was not present a few months ago.

Best,
Sebastian

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

Thanks for your interest here.
We already changed it to `ImageDataset` in v0.5.

Thanks.

**Comment by Sebagam** [comment]
Ok, thanks.
It looks that I have other compatibility issues.
How can I install v0.4?

**Comment by Nic-Ma** [comment]
Maybe you can try pip install monai==0.4.0?

Thanks.

**Comment by Nic-Ma** [comment]
But I strongly suggest you to update with MONAI v0.6 as we integrated many enhancements.

Thanks.

**Comment by Sebagam** [comment]
Hi Nic,

I think that there is an issue with the transformations, here is the code
if you want to check:
https://colab.research.google.com/drive/1XcHHnNvxVCbTDV7bgnWHrSjGD7XKzY_f#scrollTo=ec0QWW-Q69N6

Best,
Sebastian

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

If you check the error log, you can find that the data shape is wrong:
Shape: (1, 166, 256, 256, 1)
Actually your data already has channel dim at the last dim, you should not use `AddChannel` transform, you can use `EnsureChannelFirst` or `AsChannelFirst` transform.

Thanks.

**Comment by Sebagam** [comment]
Thank you, Nic,

Do you know what the following issue mean?

RuntimeError: DataLoader worker (pid(s) 1038) exited unexpectedly

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

I think maybe it's some PyTorch multi-processing issue? Can you try again with `num_workers=0`?

Thanks.

**Comment by Sebagam** [comment]
Hi Nic,

Thanks for your help.
I'm running the last tutorial for the 3D classifications.

Apparently, there is an incompatibility between the shape of my
tensor: torch.Size([2,
166, 256, 256, 1])

 and the model

https://colab.research.google.com/drive/1mz0YB0I-t3B0ZwPzazN9QlgTPnv9pZFJ?usp=sharing

I'm missing another transformation?

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

Seems something wrong with your data shape?
Could you please help add `EnsureChannelFirst` transform at the beginning of your transform chain?

Thanks.

**Comment by Sebagam** [comment]
I got this error now:
ValueError: meta_dict not available, EnsureChannelFirst is not in use.

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

As you are using array-based transforms instead of dict-based transforms, it may not work well.
Could you please help change to `AsChannelFirst` transform?

Thanks.

**Comment by Sebagam** [comment]
Thanks Nic, it's working now.

I have a question.
Do you know why I'm getting the best metric as a zero value? The loss
appears to be decreasing across epochs.

https://colab.research.google.com/drive/1mz0YB0I-t3B0ZwPzazN9QlgTPnv9pZFJ#scrollTo=kJrv4lBIALU7

Best,
Sebastian

**Comment by Nic-Ma** [comment]
I think maybe you can print out the model predictions, see whether it's overfitting?
@wyli @ericspod Could you guys help please share some comments about the training status?

Thanks in advance.

**Comment by Sebagam** [comment]
I think that I managed to fix it.
Do you know how to turn off this output?

INFO:nibabel.global:pixdim[0] (qfac) should be 1 (default) or -1;
setting qfac to 1

/usr/local/lib/python3.7/dist-packages/monai/data/utils.py:542:
UserWarning: Modifying image pixdim from [1.1999999 1.        1.
 0.       ] to [  1.19999993   1.           1.         218.40411641]
  warnings.warn(f"Modifying image pixdim from {pixdim} to {norm}")



Thanks

**Comment by Nic-Ma** [comment]
I think you can turn off all the warnings, referring to:
https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

Thanks.

**Comment by Sebagam** [comment]
Hi Nic,

Yes, I know that command.
The problem is the Nibabel information messages:

INFO:nibabel.global:pixdim[0] (qfac) should be 1 (default) or -1;
setting qfac to 1

pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1



Do you know how to suppress them?


Thanks

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Do you know something about this Nibabel warning?

Thanks in advance.
