### ISSUE TITLE
Preview transformation methods in documentation

### ISSUE THREAD

**Issue by cemde** [Project-MONAI/MONAI#2892]
It is quite easy to get overwhelmed by all the transforms offered within MONAI. I recently discovered [this torchvision overview of transforms](https://pytorch.org/vision/stable/auto_examples/plot_transforms.html#illustration-of-transforms).

It provides a panel with examples from each transform. I think something comparable would be very useful for MONAI.

**Comment by wyli** [comment]
thanks for the pointer, we can continue the discussion and track the progress in #2721
