### ISSUE TITLE
ImportError: cannot import name 'HistogramNormalized' from 'monai.transforms'

### ISSUE THREAD

**Issue by Namng1210** [Project-MONAI/MONAI#2893]
I'm getting this error when I tried to import HistogramNormalized. The same thing happened with HistogramNormalize while everything else seems to be available in transforms ?

**Screenshots**
![image](https://user-images.githubusercontent.com/69883752/132097491-e798a3ae-42db-4357-a4dd-61095d90991b.png)

**Environment**
OS : Ubuntu 18.04.5 LTS
Python version: 3.8.0 64bit
MONAI version monai - 0.6.0

**Comment by Nic-Ma** [comment]
Hi @Namng1210 ,

This transform was added after MONAI v0.6 release, please download latest dev branch to use it.

Thanks.
