### ISSUE TITLE
Using the transform RandCoarseDropoutd causes an error. 

### ISSUE THREAD

**Issue by Sandv** [Project-MONAI/MONAI#2896]
Hi 

Using the transform RandCoarseDropoutd causes an error. When I add RandCoarseDropoutd to a series of transforms as shown below this error occurs. Any ideas? It looks like a bug to me because the other transforms work fine...

Thank you for your help!
Veit

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items)
     91             return [_apply_transform(transform, item, unpack_items) for item in data]
---> 92         return _apply_transform(transform, data, unpack_items)
     93     except Exception as e:

6 frames
/usr/local/lib/python3.7/dist-packages/monai/transforms/transform.py in _apply_transform(transform, parameters, unpack_parameters)
     59 
---> 60     return transform(parameters)
     61 

/usr/local/lib/python3.7/dist-packages/monai/transforms/intensity/dictionary.py in __call__(self, data)
   1489             for key in self.key_iterator(d):
-> 1490                 d[key] = self.dropper(img=d[key])
   1491 

/usr/local/lib/python3.7/dist-packages/monai/transforms/intensity/array.py in __call__(self, img)
   1708                     if isinstance(fill_value, (tuple, list)):
-> 1709                         ret[h] = self.R.uniform(fill_value[0], fill_value[1], size=img[h].shape)
   1710                     else:

TypeError: can't assign a numpy.ndarray to a torch.FloatTensor

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-62-57c602c21a7b> in <module>()
----> 1 train_ds[1]
      2 case_num = 0
      3 
      4 case = first(train_loader)
      5 img_name = os.path.split(case["image_meta_dict"]["filename_or_obj"][0])[1]

/usr/local/lib/python3.7/dist-packages/monai/data/dataset.py in __getitem__(self, index)
     93             # dataset[[1, 3, 4]]
     94             return Subset(dataset=self, indices=index)
---> 95         return self._transform(index)
     96 
     97 

/usr/local/lib/python3.7/dist-packages/monai/data/dataset.py in _transform(self, index)
    658                     start_run = True
    659                     data = deepcopy(data)
--> 660                 data = apply_transform(_transform, data)
    661         return data
    662 

/usr/local/lib/python3.7/dist-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items)
    114             else:
    115                 _log_stats(data=data)
--> 116         raise RuntimeError(f"applying transform {transform}") from e
    117 
    118 
RuntimeError: applying transform <monai.transforms.intensity.dictionary.RandCoarseDropoutd object at 0x7f9068723110>

-------------------------

        RandAffined(
             keys=['image', 'label'],
             mode=('bilinear', 'nearest'),
             prob=0.8, spatial_size=(128, 128, 16),
             rotate_range=(0, 0, np.pi/2),
             scale_range=(0.3, 0.3, 0)),
        RandScaleIntensityd(keys=['image'], factors = 2, prob=0.9),
        RandGaussianNoised(keys= ['image'], prob=0.8, mean=0.0, std=0.05 ),
        RandCoarseDropoutd(keys= ['image'],holes = 1, spatial_size = 8, prob=0.6),

**Comment by Nic-Ma** [comment]
Hi @Sandv ,

Thanks for your interest here.
The root cause the that `RandCoarseDropoutd` doesn't support PyTorch Tensor data so far, could you please add `as_tensor_output=False` to `RandAffined` transform and try again?

@rijobro May I know whether you already implemented the Tensor version locally? If not, you or I can implement it.

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @rijobro @wyli ,

I think there is a concern that if using the random operation of torch.Tensor, we can't use local random state:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/intensity/array.py#L1709

Thanks.

**Comment by Sandv** [comment]
Thank you for your swift reply. I think MONAI is pretty amazing. Finally
some framework that does what is needed and takes most of the details off
the table!

I added the as_tensor_output=False to the prior transform and the error
goes away.
But the issue is now that the dropout area is always the same region... any
advice on that?

Thank you very much!
Veit

**Comment by Nic-Ma** [comment]
Hi think maybe you set `determinisim` for your program? So it's always the same?

Thanks.

**Comment by Sandv** [comment]
I checked the code, no setting of determinism. Even if it was on, I would
expect it to do the same random appearing thing each run, but not the exact
same area in each sample...

Here is a minimal code example that shows the unexpected behavior. Thank
you for your help!

# minimal Code
# %%
from monai.utils import first
import os, glob,re
import shutil
import tempfile
import nibabel as nib
import torch

import matplotlib.pyplot as plt
import numpy as np
from tqdm.auto import tqdm

from monai.data import CacheDataset, DataLoader, Dataset
from monai.inferers import sliding_window_inference
from monai.transforms import (
    AsDiscrete,
    AddChanneld,
    Compose,
    CropForegroundd,
    LoadImaged,
    Orientationd,
    RandFlipd,
    RandAffined,
    RandCropByPosNegLabeld,
    RandShiftIntensityd,
    ScaleIntensityRanged,
    Spacingd,
    RandRotate90d,
    ToTensord,
    EnsureChannelFirstd,
    EnsureTyped,
    EnsureType,
    RandGaussianNoised,
    RandAdjustContrast,
    RandScaleIntensityd,
    RandCoarseDropoutd,
    LocalPatchShuffling,
)

def show_examples(loader, n=2):

    for i in range(n):
        case = first(loader)

        img_name =
os.path.split(case["image_meta_dict"]["filename_or_obj"][0])[1]
        image = case["image"][0]
        label = case["label"][0]

        #print(f"image shape: {image.shape}, label shape: {label.shape}")
        plt.figure("image", (18, 6))
        plt.subplot(1, 2, 1)
        plt.title(img_name)
        plt.imshow(image[0, :, :, 1].detach().cpu(), cmap="gray")
        plt.subplot(1, 2, 2)
        plt.title("label")
        plt.imshow(label[0, :, :, 2].detach().cpu())
        plt.show()


#%%

def get_loaders(data_dir, BATCH_SIZE):

    data = np.zeros((5,128,128,16))
    img = nib.Nifti1Image(data, np.eye(4))
    nib.save(img,  'test.nii.gz')


    train_labels = glob.glob( "test.nii.gz")
    print(train_labels)
    train_images =  train_labels

    data_dicts = [
        {"image": image_name, "label": label_name}
        for image_name, label_name in zip(train_images, train_labels)
    ]

    train_transforms = Compose(
        [
            LoadImaged(keys=["image", "label"]),
            RandScaleIntensityd(keys=['image'], factors = 2, prob=0.9),
            RandCoarseDropoutd(keys= ['image'],fill_value = (0,100),holes =
1, spatial_size = 64, prob=0.8),
            EnsureTyped(keys=["image", "label"]),
        ]
    )

    train_ds = CacheDataset(
    data=data_dicts,
    transform=train_transforms,
    cache_num=1,
    num_workers=1,
    )
    train_loader = DataLoader(
        train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=1,
pin_memory=False
    )

    return(train_loader)
# %%
train_loader = get_loaders('', 1)
show_examples(train_loader, n=15)

# %%

[image: image.png]

**Comment by Nic-Ma** [comment]
Hi @Sandv ,

I didn't get your issue "the exact same area in each sample".
I tested the below program, seems it generated different result in 2 runs:
```py
dropout = RandCoarseDropout(holes=2, spatial_size=[2, 2, 2], fill_value=5, prob=1.0)
for _ in range(2):
    result = dropout(np.random.randint(0, 2, size=[3, 3, 3, 4]))
    print(result)
```

Thanks.
