### ISSUE TITLE
merge `LocalPatchShuffling` into `RandCoarseDropout`

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2898]
**Is your feature request related to a problem? Please describe.**
If comparing to `RandCoarseDropout`, I think the only difference is that `LocalPatchShuffling` shuffles the content in a hole instead of filling with random values, so maybe we can refactor `RandCoarseDropout` to support all cases, or build a base class and subclasses implement different filling method.

**Comment by Nic-Ma** [comment]
Hi @finalelement ,

Do you have other concerns about this feature request?
If not, I will try to implement it ASAP.

Thanks in advance.

**Comment by finalelement** [comment]
@Nic-Ma That is a great idea indeed. Do you think, the transform would become too complex though?

**Comment by Nic-Ma** [comment]
Hi @finalelement ,

Thanks for your support.
I will try to make a base class and several sub-classes for different filling methods.

Thanks.
