### ISSUE TITLE
GPU transforms not working with multiple workers

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#2912]
**Describe the bug**
Running MONAI transforms on GPU (using `ToDevice` transform) only works when the number of workers in `DataLoader` is 0.

**To Reproduce**
```python
preprocess_train = Compose(
import torch
from monai.apps.pathology.data import PatchWSIDataset
from monai.apps.utils import download_url
from monai.data import DataLoader
from monai.transforms import (
    Compose,
    ScaleIntensityRangeD,
    ToDeviceD,
    ToTensorD,
)
from monai.utils import first

NUM_WORKERS = 1
FILE_URL = "http://openslide.cs.cmu.edu/download/openslide-testdata/Generic-TIFF/CMU-1.tiff"
download_url(FILE_URL, "./image.tif", "5a3cfd4fd725c50578ddb80b517b759f")

torch.cuda.is_available()
device = "cuda:0"
preprocess_train = Compose(
    [
        ToTensorD(keys=("image", "label")),
        ToDeviceD(keys=("image", "label"), device=device),
        ScaleIntensityRangeD(keys="image", a_min=0.0, a_max=255.0, b_min=-1.0, b_max=1.0),
    ]
)

train_list = [
    {
        "image": "./image.tif",
        "location": [100, 100],
        "label": [0, 0, 0, 0, 0, 0, 0, 0, 0],
    }
]
train_dataset = PatchWSIDataset(
    data=train_list,
    region_size=20 * 3,
    grid_shape=3,
    patch_size=20,
    transform=preprocess_train,
    image_reader_name="cuCIM",
)

train_dataloader = DataLoader(train_dataset, num_workers=NUM_WORKERS, batch_size=1)
first_sample = first(train_dataloader)
print(">>> shape", first_sample["image"].shape)

```

**Expected behavior**
```bash
>>> shape torch.Size([9, 3, 20, 20])
```

**Environment**
```
================================
Printing MONAI config...
================================
MONAI version: 0.6.0+112.g7cfc8ea3
Numpy version: 1.21.1
Pytorch version: 1.10.0a0+ecc3718
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 7cfc8ea3c73ab63cfdca2e0cba9302f9286478a7

Optional dependencies:
Pytorch Ignite version: 0.4.5
Nibabel version: 3.2.1
scikit-image version: 0.15.0
Pillow version: 8.2.0
Tensorboard version: 2.5.0
gdown version: 3.13.0
TorchVision version: 0.11.0a0
tqdm version: 4.53.0
lmdb version: 1.2.1
psutil version: 5.8.0
pandas version: 1.1.4
einops version: 0.3.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.2 LTS
Platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.10
Processor: x86_64
Machine: x86_64
Python version: 3.8.10
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [3.4, 2.7, 96.0, 4.1, 2.7, 4.0, 14.2, 11.6, 3.9, 1.4, 3.9, 1.3, 0.0, 0.0, 0.7, 0.7]
CPU freq. (MHz): 1219
Load avg. in last 1, 5, 15 mins (%): [0.4, 1.4, 2.8]
Disk usage (%): 93.4
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.1
Available memory (GB): 26.4
Used memory (GB): 4.2

================================
Printing GPU config...
================================
Num GPUs: 2
Has CUDA: True
CUDA version: 11.4
cuDNN enabled: True
cuDNN version: 8202
Current device: 0
Library compiled for CUDA architectures: ['sm_52', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_86']
GPU 0 Name: NVIDIA TITAN RTX
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 72
GPU 0 Total memory (GB): 23.7
GPU 0 CUDA capability (maj.min): 7.5
GPU 1 Name: NVIDIA TITAN RTX
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 72
GPU 1 Total memory (GB): 23.7
GPU 1 CUDA capability (maj.min): 7.5```

**Comment by drbeh** [comment]
Hi @wyli @Nic-Ma @rijobro 
I'd appreciate you help to resolve this issue. Thanks

**Comment by drbeh** [comment]
In the provided code, if you set `NUM_WORKERS = 0`, all works fine.
Also if you remove `torch.cuda.is_available()`, it works too but there is nothing wrong with `torch.cuda.is_available()`. It just initializes CUDA and that's why it can reproduce the error.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

That's expected behavior as CUDA 11 can't work in forked subprocesses.
Could you please help try again your program with`monai.data.ThreadDataLoader(num_workers=0)`?
It will process the data in a separate thread.
Of course, to get a better perf, we may consider to support multi-threads in `ThreadDataLoader` in MONAI v0.8.

Thanks.

**Comment by drbeh** [comment]
Hi @Nic-Ma, `DataLoader` and `ThreadDataLoader` have the same behavior and both only works when `num_workers=0`, which is not desirable for our pathology pipeline since we are IO bound.

If there is not any solution here, can we consider #2883 to be able to run transforms on GPU?

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Have you confirmed how the torchvision transforms execute random logic for every item in a batch?

Thanks.

**Comment by drbeh** [comment]
@Nic-Ma, yes, torchvision transforms are applied on the entire batch, so with the random transforms we will have less augmentation. However, this is not an issue in general, and might affect small datasets. For our digital pathology pipeline we are training on 400k patches so the reduced randomness in augmentation should not have any significant effect.

Besides faster model training, adding this capability (#2883) is particularly beneficial for inference (validation and testing) where we don't have any random speed up. Thus, we can run them much faster with very simple changes.

**Comment by wyli** [comment]
> Hi @drbeh ,
> 
> That's expected behavior as CUDA 11 can't work in forked subprocesses.
> Could you please help try again your program with`monai.data.ThreadDataLoader(num_workers=0)`?
> It will process the data in a separate thread.
> Of course, to get a better perf, we may consider to support multi-threads in `ThreadDataLoader` in MONAI v0.8.
> 
> Thanks.

I agree with Nic that this is expected. Hi @drbeh could you elaborate how #2883 is related to this ticket, perhaps with some code examples? Thanks!

**Comment by drbeh** [comment]
> > Hi @drbeh ,
> > That's expected behavior as CUDA 11 can't work in forked subprocesses.
> > Could you please help try again your program with`monai.data.ThreadDataLoader(num_workers=0)`?
> > It will process the data in a separate thread.
> > Of course, to get a better perf, we may consider to support multi-threads in `ThreadDataLoader` in MONAI v0.8.
> > Thanks.
> 
> I agree with Nic that this is expected. Hi @drbeh could you elaborate how #2883 is related to this ticket, perhaps with some code examples? Thanks!

We needed #2883 to combine the gpu transforms with the model to be able to use Ignite pipeline in the same way as before. However, I am changing the digital pathology pipeline not to use Ignite workflow so the need is going away. Thanks.
