### ISSUE TITLE
`RandRotate90` and `RandZoom` to work with `torch.Tensor`

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#2913]
**Is your feature request related to a problem? Please describe.**
For digital pathology training pipeline to use `torch.Tensor`, there are still two transform that are not supporting this input types `RandRotate90` and `RandZoomD`. I know that there have been efforts on this front, so I am wondering if these transforms are in the pipeline? If so, is it possible to prioritize them? If not, is there anything that holding us from doing that besides time?

**Comment by wyli** [comment]
I believe they are already in PR #2278, @rijobro could you please help make these transforms into the core soon? @Nic-Ma  and I could work on them if you don't have time before v0.7.

**Comment by rijobro** [comment]
Sure, I'll put them to the top of the list of transforms.
