### ISSUE TITLE
add AMP(auto mixed precision) enabled example

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#293]
**Is your feature request related to a problem? Please describe.**
As native AMP support is available in PyTorch now, we need to add an example **notebook** for AMP.

**Describe the solution you'd like**
Refer to this TensorFlow example:
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Segmentation/UNet_Medical
And use this AI challenge dataset:
http://brainiac2.mit.edu/isbi_challenge/home
PyTorch AMP programming guide and example code:
https://pytorch.org/docs/stable/amp.html

**Comment by vfdev-5** [comment]
Hi @Nic-Ma, I can add it in one or all Ignite-based examples. Typically, the only change is in the way to create the trainer. Instead of
```pyhon
# Create trainer
device = torch.device('cuda:0')
trainer = create_supervised_trainer(net, opt, loss, device, False)
```
it will be 
```python
from torch.cuda.amp import GradScaler, autocast

# Create trainer
device = torch.device('cuda:0')
scaler = GradScaler()

def train_step(engine, batch):
    model.train()
    optimizer.zero_grad()
    x, y = batch[0].to(device), batch[1].to(device)
    with autocast():
        y_pred = model(x)
        loss_t = loss(y_pred, y)
    scaler.scale(loss_t).backward()
    scaler.step(optimizer)
    scaler.update()
    return loss_t.item()    

trainer = Engine(train_step)
```

PS: full support of AMP is not yet in the stable version of torch v1.5.0 but in v1.6.0 or currently master.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

First of all, thanks very much for your previous online/offline help during our development.
Glad to see your interest here, your ignite program certainly will be a good reference!
Could you please help make a notebook according to the issue description?
Suggest:
1. UNet segmentation.
2. Based on http://brainiac2.mit.edu/isbi_challenge/home dataset.
3. Better to provide a training speed & memory usage comparison of AMP enable/disable.

When your notebook is ready, you or I may also need to provide a pure PyTorch version notebook for non-ignite users.

Thanks.

**Comment by vfdev-5** [comment]
@Nic-Ma sounds good about the notebook !

The code can be based on this https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/unet_segmentation_3d_ignite.ipynb and run on this specific dataset ?

> Better to provide a training speed & memory usage comparison of AMP enable/disable.

Maybe, memory usage comparison can be not that relevant as we may prefer augment the batch size with enabled AMP ?

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

1. Yes, you can try to build the notebook based on the existing program.
But maybe you need to change the data pre-processing as dataset changed.
Refer to the TensorFlow version [example](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Segmentation/UNet_Medical).
2. 3D medical images are usually very big and typical batch size is: **1, 2 or 4**, many researchers can't run the training even with batch size = 1. So it's important to show how much memory decreased after AMP enabled.
I think you can show both: (1) same batch size for memory usage comparison, (2) same memory usage for speed?
3. This is not a very urgent task before PyTorch v1.6 release, let's try to polish it better together.

Thanks.

**Comment by hjmjohnson** [comment]
@Nic-Ma I am working on a variation of a similar problem for a project.  I'll see if I can make an example that is suitable for sharing.

**Comment by wyli** [comment]
looks like this become relevant as torch 1.6 is out https://github.com/pytorch/pytorch/releases/tag/v1.6.0

**Comment by Nic-Ma** [comment]
I will try to add AMP support to our workflows, then add 2 examples: AMP training for spleen with native PyTorch, AMP training for spleen with MONAI workflow.

Thanks.

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/841
