### ISSUE TITLE
Add `kwargs` to `ToTensor`, `ToNumpy` and `ToCupy`

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2951]
**Is your feature request related to a problem? Please describe.**
As we are adding more and more args based on `torch` API or `numpy` API, I think we should use `kwargs` directly for future support.
And I will also update the `covert_to_type` utility to convert `dtype` and `device` in 1 call to avoid duplicated copy.

**Comment by Nic-Ma** [comment]
Hi @wyli @rijobro ,

If you guys don't have concerns, I will make a PR for it today ASAP.

Thanks in advance.

**Comment by drbeh** [comment]
Thank you very much @Nic-Ma for taking care of this! 
Is there any reason that we can't just add `dtype` to these APIs? Not having explicit input arguments is a bit strange to me. I know that you are thinking of future addition arguments but I believe we will compromise the APIs to be explicit and self-explanatory, and it might not worth it.
