### ISSUE TITLE
Collection of medical datasets

### ISSUE THREAD

**Issue by jenspetersen** [Project-MONAI/MONAI#297]
**Is your feature request related to a problem? Please describe.**
It is often cumbersome to obtain some specific dataset required to reproduce results in a paper or just to quickly try an idea.

**Describe the solution you'd like**
Something like torchvision.datasets for medical datasets. I understand that there are often licensing issues, but it would be extremely convenient to have standardized access to the commonly used datasets (e.g. BraTS, not so familiar with other domains). This could come with a set of recommended transformations to get the data into a usable format.

Just want to start a discussion to for now, but would be willing to invest time!

**Comment by tvercaut** [comment]
This seems to duplicate to #271 and #88 
I'm closing it for that reason but feel free to reopen if you feel it's different

**Comment by jenspetersen** [comment]
#88 would certainly be a feature of this here, and technically #271 only says that data and models released under monai should reside in a separate repo. Maybe that implies that there should be a collection of datasets, but not necessarily that there is a desire to provide convenient access to the existing "big" ones (likely without a dedicated mirror). Would vote to keep open, because I think this issue expresses what might only be implied by the others, but I understand if you disagree.

**Comment by vfdev-5** [comment]
I had a similar reflexion as @jenspetersen about having torchvision.datasets for medical data.
For example, in https://github.com/Project-MONAI/MONAI/issues/293 it is suggested to use  http://brainiac2.mit.edu/isbi_challenge/home dataset. It would be more simple to import data using `from monai.datasets import ISBI` abstraction. cc @Nic-Ma 
Thoughts ?

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Thanks for your sharing!
We plan to host some public medical datasets at DropBox or some other public storage.
And support `from monai.datasets import XXX` when the above first step is done.
So I think we are on the same page of this topic.
BTW, we will track this task in https://github.com/Project-MONAI/MONAI/issues/271
Thanks.
