### ISSUE TITLE
torch gibbs and kspace noise

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#2972]
Hi @rijobro ,

I am checking the left transforms, seems these 4 intensity transforms already execute with Tensor data, but the code stype doesn't follow our backend design:
    "GibbsNoise",
    "RandGibbsNoise",
    "KSpaceSpikeNoise",
    "RandKSpaceSpikeNoise",
Do you also plan to add backend support for them in v0.7?

Thanks in advance.

_Originally posted by @Nic-Ma in https://github.com/Project-MONAI/MONAI/issues/2971#issuecomment-921924847_

**Comment by rijobro** [comment]
@Nic-Ma In the big PR, I made the FFT and invFFT compatible with both torch and numpy input. So these transforms will support both numpy and torch input without needing to convert.

**Comment by Nic-Ma** [comment]
Cool, that's great!

Thanks.
