### ISSUE TITLE
Sliding window inference with overlap and weighting

### ISSUE THREAD

**Issue by jenspetersen** [Project-MONAI/MONAI#298]
**Is your feature request related to a problem? Please describe.**
Image-scale predictions (e.g. segmentations) tend to become worse towards the outside of the image [citation needed, I know], resulting in non-smooth predictions when a sliding window approach is used.

**Describe the solution you'd like**
An option to perform sliding window inference with overlapping patches (e.g. by half patch size) and weighting (e.g. a Gaussian over the image) so we put more weight on predictions from the center of a patch.

**Comment by Nic-Ma** [comment]
Hi @jenspetersen ,

Thanks for your feedback!
That's a very good point. Actually, we already discussed internally about overlapping in sliding window, and want to have it in a future version.
I think that's a very important and valuable improvement to our evaluation method.
Do you have any interest to submit a PR that enhances our existing sliding window method?
Thanks.

**Comment by jenspetersen** [comment]
@FabianIsensee, you already implemented this, is that something you would/could contribute?

**Comment by Nic-Ma** [comment]
Hi @madil90 ,

Could you please help develop this feature request? It will obviously improve the evaluation performance.
Thanks.

**Comment by madil90** [comment]
@Nic-Ma Yes definitely. I'm looking at @FabianIsensee implementation and will start porting it to MONAI.

**Comment by mjorgecardoso** [comment]
@Nic-Ma @madil90 
Getting the patch weights with Gaussians is only one way to do this, but we should probably support other approaches. For example, the next two immediately come to mind. 

- Option 1: Get the window stride (overlap) to be equivalent to the maximum receptive field of a network. This one will be very harsh at rejecting any prediction close to the border of a patch, but will guarantee that the predictions are always valid by construction.
- Option 2: Get the mixing weight to be something else other than a Gaussian (e.g. distance from the centre of the patch). Given that kernels are 3x3, information propagation along the network does not "travel" isotropically, and thus should not be Gaussian (it is actually the Chebyshev Distance). 

Also, we need to be aware that not everything is a semantic segmentation model. E.g. weighted average of 2 predictions is not necessarily ideal for semantic regression models (image synthesis).

**Comment by madil90** [comment]
@mjorgecardoso Thanks, that's a very good point. I'll separate the weighting from overlapping in a way that we can implement other weighting algos later.

**Comment by Nic-Ma** [comment]
> @mjorgecardoso Thanks, that's a very good point. I'll separate the weighting from overlapping in a way that we can implement other weighting algos later.

Hi @madil90 ,

Thanks for your help on this PR! Looking forward to your update of our sliding window.
