### ISSUE TITLE
CPU environment has CUDA?!

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#2999]
**Describe the bug**
The PyTorch version that is being used for CPU only quick tests seems to be `1.9.0+cu102`, which is a cuda version. 
https://github.com/Project-MONAI/MONAI/runs/3667531453#step:9:435
https://github.com/Project-MONAI/MONAI/runs/3667531453#step:10:10

Also the installed torchvision: `TorchVision version: 0.10.0+cu102`
https://github.com/Project-MONAI/MONAI/runs/3667531453#step:10:29

This is causing issue with cucim: https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3669657801#step:10:10852
since cucim is not working in cuda<11.0 and this test environment is supposed to be CPU only where cuCIM should work but seems to be a CUDA 10.2 environment.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

I will submit a PR to skip cuCIM tests if CUDA < 11.0 today.

Thanks.

**Comment by wyli** [comment]
I think pytorch by default `pip install torch` is shipped with the compiled binaries, the test is simulating the commands. But it does not necessarily use the binaries during the tests -- I believe the flag `torch.cuda.is_avaialble()` is False in this case. 

What's the issue here? please follow the bug report template to provide more information about the expected behavior.

**Comment by wyli** [comment]
> Hi @drbeh ,
> 
> I will submit a PR to skip cuCIM tests if CUDA < 11.0 today.
> 
> Thanks.

Not sure how the reply is related to this ticket, I'm closing this ticket. please reopen with a detailed report following the template.

**Comment by drbeh** [comment]
@wyli, thanks for your comments. I updated the description to include why it is causing an error.

**Comment by drbeh** [comment]
> there's

So what's the reason that we have cuda102 version of some packages installed:
`Pytorch version: 1.9.0+cu102`: https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3669657801#step:10:18
`TorchVision version: 0.10.0+cu102`: https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3669657801#step:10:6200

**Comment by wyli** [comment]
> > there's
> 
> So what's the reason that we have cuda102 version of some packages installed?
> 
> `Pytorch version: 1.9.0+cu102`: https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3669657801#step:10:18
> `TorchVision version: 0.10.0+cu102`: https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3669657801#step:10:6200

That's the default behaviour of pytorch on Linux for `pip install torch` according to the installation guide (https://pytorch.org/), it'll install 1.9.0+cu102.

I believe this is expected for our testing pipeline, so I"m closing this ticket.

**Comment by drbeh** [comment]
> Hi @drbeh ,
> 
> I will submit a PR to skip cuCIM tests if CUDA < 11.0 today.
> 
> Thanks.

Hi @Nic-Ma , have you been able to submit a PR to skip cucim when cuda<11? It is a blocking factor in testing cucim and releasing monai. Thanks
