### ISSUE TITLE
Evaluation subpackage and metric implementations

### ISSUE THREAD

**Issue by jenspetersen** [Project-MONAI/MONAI#303]
I'd like to use this issue to discuss the structure of the evaluation part of MONAI, essentially what is currently `monai.metrics`. I plan to do the following in a PR, but obviously would like to coordinate with you guys.

1. Rename to `monai.evaluation` to make it more generic, at first there will be modules
    1. `metrics` (Implementations of metrics)
    2. `util`(For now a confusion matrix helper to hold TP, FP, FN, TN and a wrapper to convert metrics into a `ignite.metrics.Metric`)
2. Implement the most commonly used metrics
    1. Confusion matrix based metrics (see https://en.wikipedia.org/wiki/Confusion_matrix for an overview)
    2. Hausdorff distance (95), medpy has an implementation
    3. Surface distance, medpy has an implementation
    4. Check medpy, NiftyNet, Clara Train for other metrics (see also #85)

I'm assuming you also have ideas what that package should look like and requirements that I'm not aware of. Would love to hear your thoughts! I'm also a bit biased towards segmentation, I'm guessing there are special metrics for other tasks that should be integrated.

**Comment by Nic-Ma** [comment]
Hi @jenspetersen ,

Thanks for your interest and contribution here.
Your proposal is a big design topic, could you please help raise it up in the working group meeting directly as you are a member of it?
Thanks.

**Comment by jenspetersen** [comment]
Yes, that's the plan, just wanted to document it here as well :)

**Comment by justusschock** [comment]
Just a quick note: Currently we're also building a metrics package in lightning (See also [this project](https://github.com/PyTorchLightning/pytorch-lightning/projects/2)). Maybe we could also sync up to avoid duplicated efforts :)
