### ISSUE TITLE
Monai generates lots of Pyright/pylance errors (reportPrivateImportUsage)

### ISSUE THREAD

**Issue by dyollb** [Project-MONAI/MONAI#3031]
**Describe the bug**
Pyright complains about import statements like:
```
from monai.metrics import DiceMetric, ConfusionMatrixMetric
from monai.losses import DiceLoss
```
This is the style used e.g. in the monai tutorials.

**To Reproduce**
1. Open empty file in vscode, type `from monai.losses import DiceLoss`
2. Select Python interpreter to a python with monai installed
3. Check the errors in Problems section

**Expected behavior**
Importing functions from monai like above doesn't generate pyright errors.

**FYI**. The errors go away if I add `__all__ = [...]` statements to the `__init__.py` files in monai, e.g. for `monai.losses/__init__.py`
```
__all__ = [
  "DiceLoss",
  ...
]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12702862/134910817-c62cbd10-a541-472e-9e89-d9f9a8542254.png)

**Environment**
Windows 10, vscode with up-to-date pylance/pyright.
Python 3.6, monai-weekly==0.7.dev2132

```
MONAI version: 0.7.dev2132
Numpy version: 1.19.5
Pytorch version: 1.9.0+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: bcbf21ec88dd95929b1d6439ebbf37b3cb266988

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 8.3.2
Tensorboard version: 2.2.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.10.0+cu111
tqdm version: 4.62.2
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.1
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 2080 Ti
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 68
GPU 0 Total memory (GB): 11.0
GPU 0 CUDA capability (maj.min): 7.5
```

**Additional context**

**Comment by wyli** [comment]
I couldn't replicate this issue:
<img width="526" alt="Screenshot 2021-09-28 at 08 15 59" src="https://user-images.githubusercontent.com/831580/135040906-68c5f9d5-5191-4ef7-8ea1-b8e805600cf8.png">

Also I'm not sure why adding `__all__` is useful here, does pylance call `from monai.losses import *` implicitly?

--
vscode version:
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by dyollb** [comment]
I am only just learning about static analysis in python, so I don't know if the behavior of pyright is correct/good, or why the `__all__` is [needed](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package).

I checked again with monai==0.7, and get the same errors. Note that by default pyright is not enabled.
* install pylance vscode extension
* enable Type Checking (basic)

![image](https://user-images.githubusercontent.com/12702862/135063161-bfb5290a-96ca-485e-9e1a-0783a857d18a.png)

Note the errors can be ignored via a `pyrightconfig.json` file, e.g.:
```
{
    "include": [
        "src/",
        "tests/",
    ],
    "exclude": [
    ],
    "useLibraryCodeForTypes": true,
    "reportPrivateImportUsage": false,
    "reportMissingImports": "warning"
}
```

You can close the case if you don't won't to bother, or feel pyright is wrong. I guess the reason they are kind of push you to add the `__all__` is to make sure from X.Y import * will be **controlled**, i.e. import only specific objects and skips e.g. module of functions used in the `__init__.py` code, like `os`.

**Comment by wyli** [comment]
Thanks for giving the details! I still couldn't replicate the issues, probably I messed up my local vscode configs. In general, I think if the linting tool and error reporting are coupled with vscode, it'll be difficult to enforce it throughout the project via [the automatic checking](https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#checking-the-coding-style). Let's keep this ticket open for more investigations...

**Comment by dyollb** [comment]
In my project I added a github action to run pyright, like so:

```
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: static analysis
        working-directory: my_project
        run: |
          npm install pyright
          pyright 
```
with a pyrightconfig.json file at the top level of `my_project`.

**Comment by phcerdan** [comment]
I think this issue is still valid. `__all__` is recommended to be explicit about what the file is publicly exporting.

https://github.com/microsoft/pyright/issues/2277#issuecomment-937468789

**Comment by vikashg** [comment]
inactive and issue cannot be replicated

**Comment by MathijsdeBoer** [comment]
This still happens. All packages are the most recent versions.

<img width="1673" height="536" alt="Image" src="https://github.com/user-attachments/assets/ee89f0ba-e1aa-4a74-a31d-b1065d30cf1e" />

Quickly adding an `__all__` declaration in my local copy of `monai.metrics` solves the issue:

<img width="698" height="519" alt="Image" src="https://github.com/user-attachments/assets/988050c9-c59e-4660-a96c-c3ecdaff1d3b" />

<img width="861" height="260" alt="Image" src="https://github.com/user-attachments/assets/ec834a95-5958-4430-ad43-10d18819ddd6" />

Request to reopen this issue.
