### ISSUE TITLE
"RandGaussianSmoothd" and "RandGaussianNoised" failed when running with GPU tensors

### ISSUE THREAD

**Issue by dongyang0122** [Project-MONAI/MONAI#3049]
**Describe the bug**
Transfrom "RandGaussianSmoothd" and "RandGaussianNoised" failed when running with GPU tensors.

**To Reproduce**
Adding the transform "ToDeviced(keys=["image"], device="gpu")," before "RandGaussianSmoothd" or "RandGaussianNoised" for any segmentation pipeline.

**Expected behavior**
Expected to be without any error message.

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**

**Comment by Nic-Ma** [comment]
Thanks for your bug report, I will take a look ASAP.

**Comment by Nic-Ma** [comment]
Hi @dongyang0122 ,

I tested `RandGaussianNoised` with GPU tensor, but didn't see any error during training.
Could you please help share your error log?

Thanks in advance.

**Comment by rijobro** [comment]
The unit test also checks that it works with GPU input. Keen to hear what your set up is so that we can improve the unit test, too.

**Comment by wyli** [comment]
I couldn't replicate the issue with the latest `dev` branch, I'm closing this for now, but please feel free to reopen with more details.
