### ISSUE TITLE
Distributed unit test fails regularly

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#3053]
**Describe the bug**
Distributed unit test fails regularly, slowing down the merging of unrelated PRs.

example: https://github.com/Project-MONAI/MONAI/pull/3050/checks?check_run_id=3752705985#step:7:14964

```
======================================================================
FAIL: test_content (tests.test_handler_metrics_saver_dist.DistributedMetricsSaver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/MONAI/MONAI/tests/utils.py", line 382, in _wrapper
    assert results.get(), "Distributed call failed."
AssertionError: Distributed call failed.
```

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Thanks for your issue report.
I think the exact issue is `CUDA out of memory`, CC @madil90 to help check it.
Seems it's not easy to fix as we have limited GPU resources.

Thanks.

**Comment by wyli** [comment]
I'm enabling blossom-ci and making the current github-based tests optional.
the blossom-ci tests have been stable for a while:
<img width="1203" alt="Screenshot 2021-10-12 at 14 25 50" src="https://user-images.githubusercontent.com/831580/136964940-d25eb9ad-fe55-4480-9a93-f44928585152.png">

cc @Project-MONAI/core-reviewers
