### ISSUE TITLE
TPU support + 16 bit

### ISSUE THREAD

**Issue by williamFalcon** [Project-MONAI/MONAI#308]
hey!

Not sure if you've seen:
https://github.com/williamFalcon/pytorch-lightning.

The fastest growing PyTorch front-end project.

We're also now venture funded so we have a fulltime team working on this and will be around for a very long time :)

https://medium.com/pytorch/pytorch-lightning-0-7-1-release-and-venture-funding-dd12b2e75fb3?postPublishedType=repub

**Comment by wyli** [comment]
indeed there's a demo in monai uses pytorch lightning (https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d_lightning.ipynb). but not sure how this ticket is related to the title 'tpu support + 16 bit', could you please elaborate?
