### ISSUE TITLE
integration tests for the fast training tutorials

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3114]
**Is your feature request related to a problem? Please describe.**
would be great to set up integration tests so that the recommendations in the tutorials (https://github.com/Project-MONAI/tutorials/blob/master/acceleration/fast_model_training_guide.md) are up-to-date while the codebase evolves.

see also: https://github.com/Project-MONAI/MONAI/issues/2676

**Comment by Nic-Ma** [comment]
Sure, let me try to make the integration test for fast training tutorial.

Thanks.
