### ISSUE TITLE
Use persistent caching for pre-processing

### ISSUE THREAD

**Issue by hjmjohnson** [Project-MONAI/MONAI#316]
**Feature request**
Pre-processing large data sets (10000 3D medical images) can be a significant time burden and is too large to fit completely in memory.

**Describe the solution you'd like**
A persistent cache of pre-processed data that is generated on-the-fly as needed so that initial testing can occur quickly.

**Describe alternatives you've considered**
In-memory caching alone is insufficient for meeting the efficiency needs of experimentation of parameter spaces or simultaneously running many model configurations on the same pre-processed data.

Investigated Dask, and Partd, and similar parallel data stores, but those solutions seemed more invasive and less compatible with the current infrastructure.

**Additional context**
I originally was running out of memory on my 756GB memory node when attempting to cache results.

**Comment by Nic-Ma** [comment]
Thanks very much for your valuable suggestion, it will certainly improve the cache capability if supporting persistent storage.
Let's investigate it when @gml16 completed the multi-thread cache.
Of course, if you have interest to submit a proposal or PR, do welcome!
Thanks.

**Comment by hjmjohnson** [comment]
@Nic-Ma PR will be arriving in a few minutes.  It will likely have merge conflicts with @gml16, but it should be easy to reconcile once each one or the other is approved.

**Comment by hjmjohnson** [comment]
See #317
