### ISSUE TITLE
LoadImage support for TIFF files

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#3161]
**Is your feature request related to a problem? Please describe.**
Currently due to the extra consideration needed for TIFF files of histopathology WSI images in Camelyon dataset (huge images), we were using `PatchWSIData` to load these images. However, with other datasets like PANDA dataset for prostate cancer, the size of images allow for loading the entire image into memory. Thus, it might be beneficial to load such images by just using `LoadImage` transform similar to radiology use cases.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

I think `LoadImage` should already support TIFF based on ITK, could you please help try it?
If facing any issue, please let me know.

Thanks.

**Comment by myron** [comment]
LoadImageD doesn't work to read tiff file (latest monai release)

```
RuntimeError: can not find a suitable reader for file: (‘/340236fc3587d38939e3dd669bbfe3e8.tiff’,).
  Please install the reader libraries, see also the installation instructions:
  https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
  The current registered: [<monai.data.image_reader.ITKReader object at 0x7fe4cd03e3a0>, <monai.data.image_reader.NumpyReader object at 0x7fe4cd03e760>, <monai.data.image_reader.PILReader object at 0x7fe4cd03e490>, <monai.data.image_reader.NibabelReader object at 0x7fe4cd03ec70>].
```

**Comment by myron** [comment]
@Nic-Ma 
I tried LoadImageD for .tiff (WSI) file

Initially I got error
`RuntimeError: can not find a suitable reader for file: ('/PandaChallenge2020/train_images/17cedc9620be373816ca026a94e0d6c3.tiff',).                                      
    Please install the reader libraries, see also the installation instructions:                                                                                         
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.                                                                           
   The current registered: [<monai.data.image_reader.ITKReader object at 0x7f3792d803a0>, <monai.data.image_reader.NumpyReader object at 0x7f3792d80760>, <monai.data.ima
ge_reader.PILReader object at 0x7f3792d80490>, <monai.data.image_reader.NibabelReader object at 0x7f3792d80c70>, <monai.data.image_reader.ITKReader object at 0x7f3792d80
e20>]`

which is confusing, it says I have ITKReader registered, but I didn't have itk installed.  (we need a better error message)

After intalling (pip intall itk)

I get and image (16384, 17664, 4) float32
but it should be (16384, 17664, 3) uint8

3 channels (not 4) and uint8 (not float32).  This works correctly with other readers such as tiffile

is there a way to fix it? thanks

**Comment by Nic-Ma** [comment]
Hi @myron and @drbeh ,

Thanks for your feedback.
I am working on this ticket now to improve the image reader.
And BTW, I think `PILImage` is a better reader for your case, right?

Thanks.

**Comment by myron** [comment]
PIL can't read all tiff images (mine are multi page WSI images), but tiffile can
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/PIL/Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/train_images/340236fc3587d38939e3dd669bbfe3e8.tiff'`

**Comment by drbeh** [comment]
Hi @Nic-Ma, thanks for taking care of this. I think it's better to have either `tifffile` or `WSIReader` (which uses `cuCIM` or `OpenSlide`) to handle TIFF files. What do you think?

**Comment by Nic-Ma** [comment]
> Hi @Nic-Ma, thanks for taking care of this. I think it's better to have either `tifffile` or `WSIReader` (which uses `cuCIM` or `OpenSlide`) to handle TIFF files. What do you think?

Hi @drbeh , I think we already have `WSIReader` to handle pathology images, could you please help share some usage examples with @myron ?
I will try to correct the error message as @myron suggested:
"which is confusing, it says I have ITKReader registered, but I didn't have itk installed. (we need a better error message)"

Thanks.

**Comment by drbeh** [comment]
Hi @Nic-Ma, `WSIReader` is not a transform so it cannot be used in the way that Andriy wants. I remember once you added `WSIReader` to be used as part of `LoadImage` transform but you removed it because of cuCIM dependency, I guess. Is that right? 

Do you think that there is a way to bring it back `LoadImage`? We can implement a transform for WSIReader but it seems to be redundant.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

I think you can set `WSIReader` in `LoadImage` transform to load that image TIFF image, right?
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_reader.py#L663

Thanks.

**Comment by drbeh** [comment]
@myron 
You can use `LoadImage` with `cuCIM` as follow:
```python
from monai.transforms import LoadImageD
from monai.data import WSIReader

LoadImageD(keys="image", reader=WSIReader, reader_lib="cuCIM")
```

I have tested it and it worked but please let me know if you encounter any problem.

**Comment by myron** [comment]
Yes, It does not work for me
1) First, I need to read the image at level=1 of TIFF image (medium resolution), and WSIReader by default reads level=0 in get_data. I can't specify this option unless I manually call WSIReader.get_data(level=1)
I suggest we add this option in init method of WSIReader

2) Second  for some reason WSIReader (with cucim) returns channels first  3x10000x10000, 
It's not a big problem, but my next transform expect channels last (can we specify it as option somewhere?)

3) I timed WSIReader (with cucim) vs tifffile to read images , and cucim is 6x slower

```
start = time.time()
image = tifffile.imread(image_path, key=1)
image_time = time.time()-start

start = time.time()
img_obj = self.reader.read(image_path)
image2 = self.reader.get_data(img_obj, level=1)[0]
image_time2 = time.time()-start

image2 = image2.transpose(1,2,0)
print('image', image.shape, image.dtype, 'image2', image2.shape, image2.dtype, 'diff', np.sum(np.abs(image-image2)), 'time', image_time, image_time2)
```

`image (704, 2304, 3) uint8 image2 (704, 2304, 3) uint8 diff 0 time 0.009685277938842773 0.017395973205566406                                                             
image (6080, 2368, 3) uint8 image2 (6080, 2368, 3) uint8 diff 0 time 0.0294191837310791 0.1767117977142334                                                               
image (7936, 1024, 3) uint8 image2 (7936, 1024, 3) uint8 diff 0 time 0.06923389434814453 0.08520078659057617                                                             
image (1088, 8064, 3) uint8 image2 (1088, 8064, 3) uint8 diff 0 time 0.03526449203491211 0.14212989807128906                                                             
image (2304, 6272, 3) uint8 image2 (2304, 6272, 3) uint8 diff 0 time 0.047107696533203125 0.17316889762878418                                                            
image (6219, 5727, 3) uint8 image2 (6219, 5727, 3) uint8 diff 0 time 0.10056686401367188 0.2502741813659668                                                              
image (7085, 4979, 3) uint8 image2 (7085, 4979, 3) uint8 diff 0 time 0.09291744232177734 0.24531960487365723                                                             
image (5756, 9213, 3) uint8 image2 (5756, 9213, 3) uint8 diff 0 time 0.11238408088684082 0.35108399391174316                                                             
image (4992, 4352, 3) uint8 image2 (4992, 4352, 3) uint8 diff 0 time 0.03154873847961426 0.16646766662597656                                                             
image (3359, 7221, 3) uint8 image2 (3359, 7221, 3) uint8 diff 0 time 0.03799581527709961 0.18177342414855957                                                             
image (6336, 5888, 3) uint8 image2 (6336, 5888, 3) uint8 diff 0 time 0.08136940002441406 0.24615788459777832`

Should we add tiffile as a reader to WSIReader ???

thanks

**Comment by Nic-Ma** [comment]
2 minor comments:
1. All the MONAI components expect `channel-first` data, so maybe you can adjust your transform for it.
2. If you must tifffile package, it's OK to write your own `TifffileReader` in the tutorial, use it in `LoadImage` transform.

Thanks.

**Comment by myron** [comment]
1. So for the tutorial,  what if instead of TiffileReader I just write a custom transform to load image.  It takes less space and is more explicit.  Why would I write TifffileReader class, which then needs to be initialized inside LoadImaged ?
2. Should we add tifffile option into WSIReader ? it seems like a more fundamental solution

```
class LoadTiffd():

    def __init__( self, keys=['image'], level=1) :
        super().__init__()
        self.keys = keys
        self.level=level

    def __call__(self, data):

        d = dict(data)
        for key in self.keys:
            image = d[key]
            image = tifffile.imread(image, key=self.level)
            d[key] = image

        return d
```

**Comment by Nic-Ma** [comment]
Hi @myron ,

I prefer to option 2 if it makes sense to general WSI loading cases, @drbeh @wyli .
Option 1 to write a customized reader is good to show how to customize reader as a tutorial example, would be useful for other users.

Thanks.

**Comment by drbeh** [comment]
Thanks @myron and @Nic-Ma, I agree. I like the option 2 better. I can submit a PR to add `tifffile` to `WSIReader`. Also having general options (like the level) in the constructor makes sense to me. I will make a PR for that one too.

**Comment by myron** [comment]
@drbeh are you still planning PR to support tifffile?

**Comment by drbeh** [comment]
Hi @myron, I have added support for specifying image level when using CuCIM in LoadImage. The PR is being merged #3241 so you should be able to use it very soon. `cuCIM` is supposed to be as fast as `tifffile` but please try it and let me know if it was not up to the expectations.

```python
LoadImageD(keys="image", reader=WSIReader, backend="cuCIM", level=1)
```

**Comment by myron** [comment]
I've already tried to compare tifffile vs cucim, see https://github.com/Project-MONAI/MONAI/issues/3161#issuecomment-956848740

it's 6x slower with cucim for reading level=1.  We can use it , but it won't be optimal. Is it difficult to add tiffile?

**Comment by wyli** [comment]
fyi @gigony

**Comment by drbeh** [comment]
@gigony, I confirm that `tifffile` is 3X faster than `cuCIM`. Is it something expected?
That shapes are not the same but it seems that `tifffile` is not padding.

```python
t0 = perf_counter()
img_cucim = CuImage(filename).read_region(level=1)
t_cucim = perf_counter() - t0
print(f"CuCIM   : shape = {img_cucim.shape}, time = {t_cucim:.3f}")

t0 = perf_counter()
img_tiff = tifffile.imread(filename, key=1)
t_tiff = perf_counter() - t0
print(f"Tifffile: shape = {img_tiff.shape}, time = {t_tiff:.3f}")
```

```
CuCIM   : shape = [110592, 48896, 3], time = 29.703
Tifffile: shape = (110226, 48734, 3), time =  8.446
```

**Comment by gigony** [comment]
Hi @drbeh,

It is expected.

tifffile uses multithreads (# of cpus) internally while reading whole image(but it doesn't support partial image reading) whereas cuCIM's read_region doesn't use multithreads and whether if using them is delegated to the user.

If needed, We can make cuCIM use multithreads internally in C++ level or provide a utility function in Python to load whole image using multithreads (Please request such feature in Github issue).

If multithreads are used in cuCIM, cuCIM is faster than tifffile.

**Comment by drbeh** [comment]
Thank you @gigony! I will make a request in cuCIM GitHub repo.

**Comment by drbeh** [comment]
@myron, I will add `tifffile` support to `WSIReader`. https://github.com/Project-MONAI/MONAI/issues/3251

**Comment by myron** [comment]
@drbeh 
I tried using the WSIReader, as below

```
    train_transform = transforms.Compose(
        [
            transforms.LoadImageD(keys=["image"], reader=WSIReader, backend="cuCIM", dtype=np.uint8, level=1),
            transforms.ToTensord(keys=["image"]),
        ]
    )
```

it loads image fine, but then gives an error
```

TypeError: Caught TypeError in DataLoader worker process 0.                                                                                                              
Original Traceback (most recent call last):                                                                                                                              
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop                                                             
    data = fetcher.fetch(index)                                                                                                                                          
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch                                                                      
    return self.collate_fn(data)                                                                                                                                         
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate                                                          
    return {key: default_collate([d[key] for d in batch]) for key in elem}                                                                                               
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>                                                               
    return {key: default_collate([d[key] for d in batch]) for key in elem}                                                                                               
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate                                                          
    return {key: default_collate([d[key] for d in batch]) for key in elem}                                                                                               
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>                                                               
    return {key: default_collate([d[key] for d in batch]) for key in elem}                                                                                               
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 86, in default_collate                                                          
    raise TypeError(default_collate_err_msg_format.format(elem_type))                                                                                                    
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>  
```

it seems that LoadImageD creates an extra key d['image_meta_dict'] which is NoneType and couldn't be used to create a batch.  Since it's was working for other loaded images, the issue must be specific for WSIReader ?!

**Comment by cgohlke** [comment]
> tifffile uses multithreads (# of cpus) internally while reading whole image(but it doesn't support partial image reading)

Tifffile provides zarr store interfaces, which support partial image reading through zarr or dask. Unfortunately the overhead by zarr can be detrimental depending on how the image data in the TIFF is chunked. Tifffile also allows to iterate over segments and to memory map contiguous image data to numpy arrays if possible (e.g. ImageJ hyperstacks).

> If multithreads are used in cuCIM, cuCIM is faster than tifffile.

It's not unusual that C++/GPU implementations outperform Python implementations by 10 to 1000 and scale almost infinitely better with threads. It's more surprising that tifffile is often in the same order of magnitude when compared to libtiff, Bio-Formats etc. Anyway, the main purpose of tifffile is to get access (from Python) to image and metadata in TIFF-like (non-conformant) files used in bioimaging.

**Comment by gigony** [comment]
Thanks @cgohlke for the information!

It is great to see the message directly from the **tifffile** creator! :)
Thank you for building the awesome library!
I like its performance and flexibility -- decoding data (that takes most of the time) is done at C level (by using your imagecodecs package) and handling data is done in pure Python, that's why tifffile has a fairly great performance.

I just hope cuCIM can provide a similar feature parity in terms of image format support :)

**Comment by mahdics68** [comment]
Hi, I am using monai for UNET for 2D image segmentation. For training the model, I had a problem with reading and loading .tif format images, which I solved it by defining a class to open them and convert to numpy array. 
now, for testing the model, I get an error with seems related to "saver" part which belongs to "SaveImage" as a transforms in monai. the error is this:


/scratch1/users/menayat/conda/mambaforg/envs/main/lib/python3.10/site-packages/monai/metrics/utils.py:219: UserWarning: y should be a binarized tensor.
  warnings.warn(f"{name} should be a binarized tensor.")
Traceback (most recent call last):
  File "/usr/users/menayat/code/UNET/UNET_livecell_test.py", line 85, in <module>
    test_UNET_2d((int(roi_w), int(roi_h)), model_name)
  File "/usr/users/menayat/code/UNET/UNET_livecell_test.py", line 68, in test_UNET_2d
    saver(val_output)
  File "/scratch1/users/menayat/conda/mambaforg/envs/main/lib/python3.10/site-packages/monai/transforms/io/array.py", line 435, in __call__
    kw = self.fname_formatter(meta_data, self)
  File "/scratch1/users/menayat/conda/mambaforg/envs/main/lib/python3.10/site-packages/monai/data/folder_layout.py", line 22, in default_name_formatter
    subject = metadict[monai.utils.ImageMetaKey.FILENAME_OR_OBJ] if metadict else getattr(saver, "_data_index", 0)
KeyError: 'filename_or_obj'

Do you have any idea what should I do here? thanks in advance

**Comment by drbeh** [comment]
Hi @mahdics68,
It seems that you have not set the necessary metadata for `filename_or_obj`. 

Is there any reason to have a custom class and instead of using `LoadImage` (which relies on [`WSIReader`](https://github.com/Project-MONAI/MONAI/blob/eb6bbe8da518f49abd001ca5865672933ab1e9a2/monai/data/wsi_reader.py#L273) to load tiff files)?

Also can you share your code so we can help identify the problem?

**Comment by mahdics68** [comment]
Hi @drbeh ,
thanks for your help. temperoray I coukd solve the problem. but, still I have the problem explaining in the following:
I use a dataset which include cell images from different cell type. So, the name of each image includes the celltype as well.´and it seems "SaveImage" save the images name as meta data. I can save images with "imageio" as well. but I need these cell type later when I  visuallize the prediction. here is my code. I appreciate you in advance


```
import logging
import os
import sys
import tempfile
import numpy as np
from glob import glob

import torch
from PIL import Image

from UNET_livecell import TIFFLoader, TIFFLoaderSeg
from coco_image import get_image_and_mask_paths

from monai import config
from monai.data import ArrayDataset, create_test_image_2d, decollate_batch, DataLoader
from monai.inferers import sliding_window_inference
from monai.metrics import DiceMetric
from monai.networks.nets import UNet
from monai.transforms import Activations, AsDiscrete, Compose, LoadImage, SaveImage, ScaleIntensity


def test_UNET_2d(roi = (96,96), model_name = 'default.pth'):
    config.print_config()
    logging.basicConfig(stream=sys.stdout, level=logging.INFO)


    image_paths_train, mask_paths_train = get_image_and_mask_paths('train')
    image_paths_val, mask_paths_val = get_image_and_mask_paths('val')
    images = image_paths_train + image_paths_val
    segs = mask_paths_train + mask_paths_val
    
    
    

    # define transforms for image and segmentation
    imtrans = Compose([TIFFLoader(), ScaleIntensity()])
    segtrans = Compose([TIFFLoaderSeg(), ScaleIntensity()])
    val_ds = ArrayDataset(images, imtrans, segs, segtrans)
    # sliding window inference for one image at every iteration
    val_loader = DataLoader(val_ds, batch_size=1, num_workers=1, pin_memory=torch.cuda.is_available())
    dice_metric = DiceMetric(include_background=True, reduction="mean", get_not_nans=False)
    post_trans = Compose([Activations(sigmoid=True), AsDiscrete(threshold=0.5)])
    saver = SaveImage(output_dir="./output", output_ext=".tif", output_postfix="seg")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = UNet(
        spatial_dims=2,
        in_channels=1,
        out_channels=1,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
        num_res_units=2,
    ).to(device)

    model.load_state_dict(torch.load(model_name))
    model.eval()
    with torch.no_grad():
        for val_data in val_loader:
            val_images, val_labels = val_data[0].to(device), val_data[1].to(device)
            # define sliding window size and batch size for windows inference
            #roi_size = (96, 96)
            sw_batch_size = 4
            val_outputs = sliding_window_inference(val_images, roi, sw_batch_size, model)
            val_outputs = [post_trans(i) for i in decollate_batch(val_outputs)]
            val_labels = decollate_batch(val_labels)
            # compute metric for current iteration
            dice_metric(y_pred=val_outputs, y=val_labels)
            #for val_output in val_outputs:
            #    saver(val_output)
        # aggregate the final mean dice result
        print("evaluation metric:", dice_metric.aggregate().item())
        # reset the status
        dice_metric.reset()


# if __name__ == "__main__":
#     with tempfile.TemporaryDirectory() as tempdir:
#         main()
if __name__ == '__main__':
    np.random.seed(42)
    if len(sys.argv) < 4:
        print("Namusan kam dadi")
        exit()
    print('Namusan kam nadadi')
    _, roi_w, roi_h, model_name = sys.argv[:4]
    test_UNET_2d((int(roi_w), int(roi_h)), model_name)
```

**Comment by mahdics68** [comment]
and here are the custom classes I used: 
```
class TIFFLoader(Transform):
    def __init__(self):
        super().__init__()

    def __call__(self, image_path: str) -> np.ndarray:
        # open the TIFF image using the Image.open function
        image = Image.open(image_path)

        # convert the image to a NumPy array
        image = np.array(image)
        image = image.reshape(1, *image.shape)
        return image

class TIFFLoaderSeg(Transform):
    def __init__(self):
        super().__init__()

    def __call__(self, image_path: str) -> np.ndarray:
        # open the TIFF image using the Image.open function
        image = Image.open(image_path)

        # convert the image to a NumPy array
        image = np.array(image)
        image = image.reshape(1, *image.shape)
        image = image.astype(np.float64)
        image[image >1.0] = 1.0
        return image*255
```

**Comment by drbeh** [comment]
Hi @mahdics68,

`SaveImage` does not save the image namea as metadata. Based on the explanation of your problem, I think you can still use `SaveImage` but you should set its `output_name_formatter` argument. By default it uses the following name formatter:
https://github.com/Project-MONAI/MONAI/blob/e375f2a17c098d7b802e5ca64322db6ce874a3aa/monai/data/folder_layout.py#L21-L30
where depending on the input, it uses input filename or just and index. 

However, your custom  `TIFFLoader`  does not save the input image filename anywhere, so logically there is no way to have the input name in the output name in this way.

There are several ways to solve this problem but maybe simplest one without changing much your code is to convert the output of your `TIFFLoader` and `TIFFLoaderSeg`. For instance for `TIFFLoader` you can change the return to:

```
    return MetaTensor(x=image, meta={ImageMetaKey.FILENAME_OR_OBJ: image_path}
```
and here are the imports that you'd need:
```
from monai.data.meta_tensor import MetaTensor
from monai.utils import ImageMetaKey
```

Typically, it should work without any more changes but I didn't check what operations exactly you are doing in your pipeline so if you have any operation that causes this metadata information get lost along the way, you can also call the `saver` like this:
```
for val_output, val_image in zip(val_outputs, val_images):
    saver(val_output, val_image.meta)
```


P.S: If you have any further questions, please create a new discussion on [our discussion board](https://github.com/Project-MONAI/MONAI/discussions). Thanks
