### ISSUE TITLE
Not all load methods add pixdim to meta data

### ISSUE THREAD

**Issue by Spenhouet** [Project-MONAI/MONAI#3181]
**Description**
This might not necessarily be a bug but I did expect the pixdim to be stored in the meta data all the time - not only if a NIfTI was loaded.
 
When I'm loading a `.mgz` file with `LoadImaged(FILE_KEYS, "NibabelReader")` then the pixdim is missing.

I believe this can be calculated from the affine like this:

```python
def affine_to_pixdim(affine: np.ndarray) -> np.ndarray:
    """
    Calculate the voxel resolution in mm space (pixdim) based on the affine.

    Args:
        affine (np.ndarray): The affine describing the image.

    Returns:
        np.ndarray: The voxel resolution in mm space (pixdim).
    """
    dims = len(affine) - 1
    # Starting point projected in mm space.
    p1 = (np.ones(dims + 1) @ affine.T)[:dims]
    # Comparison points with single coordinate change projected in mm space.
    p2 = ((np.eye(dims + 1) + 1) @ affine.T)[:dims, :dims]
    # Calculate euclidean distance between starting point and comparison points.
    return np.linalg.norm(p2 - p1, axis=-1)  # type: ignore
```

Would be good if someone with a good understanding of this topic could validate this logic.

I propose that the `LoadImaged` transform calculates the `pixdim` if not already present.

**Environment**

<details>
  <summary>Click to view the environment</summary>

Printing MONAI config...

MONAI version: 0.7.0
Numpy version: 1.19.2
Pytorch version: 1.8.1+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: bfa054b9c3064628a21f4c35bbe3132964e91f43

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.1.1
scikit-image version: 0.18.0
Pillow version: 8.3.2
Tensorboard version: 2.7.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.62.3
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: 1.2.4
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Printing system config...

System: Windows
Win32 version: ('10', '10.0.19041', 'SP0', '')
Platform: Windows-10-10.0.19041-SP0
Processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
Machine: AMD64
Python version: 3.7.7
Process name: python.exe
Command: ['C:\\Users\\SebastianPenhouet\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\Windows\\System32\\de-DE\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\de-DE\\kernel32.dll.mui', fd=-1)]
Num physical CPUs: 6
Num logical CPUs: 12
Num usable CPUs: 12
CPU usage (%): [16.3, 11.8, 26.1, 20.3, 12.4, 7.2, 17.6, 16.3, 15.0, 9.2, 12.4, 58.2]
CPU freq. (MHz): 3501
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 97.8
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.9
Available memory (GB): 18.6
Used memory (GB): 13.3

Printing GPU config...

Num GPUs: 1
Has CUDA: True
CUDA version: 11.1
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: Quadro K2200
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 5
GPU 0 Total memory (GB): 4.0
GPU 0 CUDA capability (maj.min): 5.0

</details>

**Additional Information**

This relates to https://github.com/Project-MONAI/MONAI/issues/2424.

**Comment by wyli** [comment]
thanks, depending on the IO backend, when affine is available, this is provided at MetaTensor.pixdim: https://github.com/Project-MONAI/MONAI/blob/40717509198909b444d9566052602b7db0cfd0cb/monai/data/meta_tensor.py#L349-L352
