### ISSUE TITLE
How could I use MONAI to preprocess my data and save it?

### ISSUE THREAD

**Issue by demodoom1** [Project-MONAI/MONAI#3225]
I try to use MONAI transfroms to preprocess my nii data,but i can't save the post-processing file.
And many preprocessing methods result in nii images not being opened on ITKsnap,I want to know how could I use the transfroms to preprocess nii and open it in ITKsnap or others visual tool. Thanks!

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Do you have any experience with `ITKsnap` or other visual tools for our 3D output? I never used these tools...

Thanks in advance.

**Comment by demodoom1** [comment]
![image](https://user-images.githubusercontent.com/61397387/139580063-8a5b04e2-9108-4191-b962-560df550e79f.png)
![image](https://user-images.githubusercontent.com/61397387/139580074-2fdb0edf-7711-4808-85ed-3b7185da8266.png)
When I try to use the SimpleITK module precessing nii image,I have saved the Origin,the Spacing and the Direction,but could not open the nii again.I think it was the absence of some necessary information.

**Comment by demodoom1** [comment]
I want to use MONAI ,the transfrom like :
'    val_transforms = Compose([
        LoadImaged(keys=['image', 'label'])
        , EnsureChannelFirstd(keys=['image', 'label'])
        , Spacingd(keys=["image", "label"], pixdim=(1.0, 1.0, 3.0), mode=("bilinear", "nearest"))
        , Orientationd(keys=['image', 'label'], axcodes='PLI')
        , ScaleIntensityRanged(keys=['image'], a_min=-60, a_max=140, b_min=0.0, b_max=1.0, clip=True)
        , CropForegroundd(keys=["image", "label"], source_key="image")
        , EnsureTyped(keys=["image", "label"])
    ])'
to preprocess nii, it's very convenient for me...but i don't know how to use it and save it ...Thank you for your reply!

**Comment by demodoom1** [comment]
Luckily,I solved the problem by MONAI,thx the project!

**Comment by ericspod** [comment]
This might have been something related to some specific values in Nifti headers causing some tools to fail on read. We encountered this before with some ITK based tools (eg. ITKSnap) that would complain about an incorrect transform, we never figured out what about the transform was a problem since other tools read them just fine. If you're ok with your solution that's great but any more details on what the error was could be helpful later.

**Comment by demodoom1** [comment]
When I try SimpleITK to resample nii file,whatever I save the imform,it can't open in ITKsnap...&nbsp;
To my surprise&nbsp;when I use MONAI transform and the nibabel module,it worded.&nbsp;You can use ITKsnap by only saving new_affine and image.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Project-MONAI/MONAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 晚上11:38
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Project-MONAI/MONAI] How could I use MONAI to preprocess my data and save it? (Issue #3225)





 
This might have been something related to some specific values in Nifti headers causing some tools to fail on read. We encountered this before with some ITK based tools (eg. ITKSnap) that would complain about an incorrect transform, we never figured out what about the transform was a problem since other tools read them just fine. If you're ok with your solution that's great but any more details on what the error was could be helpful later.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
