### ISSUE TITLE
Add AverageMeter metric handler

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#3233]
**Is your feature request related to a problem? Please describe.**
It would be useful to have some AverageMeter metric or handler to continuously computing the average value during training, draft idea code:
```py
class AverageMeter(object):
    """Computes and stores the average and current value"""
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        if n > 0:
            self.val = val
            self.sum += val * n

            self.count += n
            self.avg = self.sum / self.count if self.count > 0 else self.sum
```

**Comment by Nic-Ma** [comment]
CC @myron @drbeh 

Thanks.

**Comment by wyli** [comment]
is it possible to use the `CumulativeIterationMetric` API directly in the tutorial? https://github.com/Project-MONAI/MONAI/blob/3960a514a5f44a10aceab463e926a19bc0b8c79a/monai/metrics/metric.py#L210-L216

**Comment by Nic-Ma** [comment]
Interest idea, need to investigate it.

Thanks.

**Comment by drbeh** [comment]
That's a great point @wyli.
@Nic-Ma, I checked on `CumulativeIterationMetric` but it is not possible to use it directly since the `aggregate` method is an abstract method. 
However, I believe it would be nice to have another class (like `RunningAverage` or anything) that inherit from `CumulativeIterationMetric`. What do you guys think? I can submit a PR.


https://github.com/Project-MONAI/MONAI/blob/3960a514a5f44a10aceab463e926a19bc0b8c79a/monai/metrics/metric.py#L172

**Comment by myron** [comment]
Here is a better version of it. it handles arrays and inf/nans
```
class AverageMeter(object):
    """Computes and stores the average and current value"""
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):

        if not np.isfinite(np.sum(val)) or not np.isfinite(np.sum(n)):
            #print('Warning AverageMeter, non-finite input', val, n)
            if not np.isfinite(np.sum(val)): val = 0
            if not np.isfinite(np.sum(n)): n = 1

        if n > 0:
           self.val = val
           self.sum += val * n

           self.count += n
           self.avg = np.where(self.count > 0, self.sum / self.count, self.sum)

```
