### ISSUE TITLE
PyPi hosted monai (version 0.7.0) does not allow additional keyword arguments.

### ISSUE THREAD

**Issue by WouterDurnez** [Project-MONAI/MONAI#3258]
https://github.com/Project-MONAI/MONAI/blob/02efc604014ee52936dca8828f47a5cae0036f67/monai/apps/datasets.py#L374

Perhaps something went wrong when uploading the latest version to PyPI, but there are no additional `dataset_params` in the `get_data` signature. Doublechecked the version (which is 0.7.0).

**Comment by wyli** [comment]
That feature was added after v0.7 and is currently on the development branch, you can access it via the weekly build https://pypi.org/project/monai-weekly/ (probably need to uninstall any existing versions to avoid conflicts).

**Comment by WouterDurnez** [comment]
Thanks a lot!
