### ISSUE TITLE
Support for SimpleITK

### ISSUE THREAD

**Issue by kiranvaidhya** [Project-MONAI/MONAI#327]
I'm trying to run the example files on a local dataset made of `.mha` files. I could convert them into Nifti files but SimpleITK is a nicely built library and is capable of handling different medical imaging formats.

Is there a plan to incorporate SimpleITK into this project?

**Comment by Nic-Ma** [comment]
Hi @kiranvaidhya ,

Thanks very much for your interest!
We already have an issue #135 that add SimpleITK related things for DICOM images.
Thanks.

**Comment by aylward** [comment]
Perhaps consider ITK Python.  It is a recent development that is directly derived from ITK.  ITK Python provides direct support for numpy arrays, xarrays, and other data formats. It also exposes more of ITK and is more "pythonic" than SimpleITK. It also exposes recent developments in GDCM for DICOM I/O.  See [ITK Python Quick Start](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html)

**Comment by wyli** [comment]
I'm closing this in favor of https://github.com/Project-MONAI/MONAI/issues/589
