### ISSUE TITLE
ImportError: cannot import name 'get_act_layer'

### ISSUE THREAD

**Issue by LaiaHumbertVidan** [Project-MONAI/MONAI#3271]
Hi, 

I am getting an error when trying to import get_act_layer using 'from monai.networks.layers import get_act_layer' and not able to figure out the reason or fix it.

Any help will be much appreciated.

Thank you.

Laia

**Comment by wyli** [comment]
could you please follow the bug reporting template to provide more info? https://github.com/Project-MONAI/MONAI/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by LaiaHumbertVidan** [comment]
Sure, done that now. Thank you.
________________________________

**Comment by wyli** [comment]
thanks, closing this in favour of https://github.com/Project-MONAI/MONAI/issues/3275.
