### ISSUE TITLE
ImportError: cannot import name 'get_act_layer'

### ISSUE THREAD

**Issue by LaiaHumbertVidan** [Project-MONAI/MONAI#3275]
**Describe the bug**
When trying to import get_act_layer using 'from monai.networks.layers import get_act_layer' I get an error which I am unable to solve or find the reason for: ImportError: cannot import name 'get_act_layer'. I am using Python 3.6.8 within Anaconda.

**To Reproduce**
1. Go to Python (v 3.6.8) within Anaconda
2. Try to import the get_act_layer Monai utility using 'from monai.networks.layers import get_act_layer'.

**Expected behavior**
I expected to be able to import the get_act_layer Monai utility by importing it as described in https://docs.monai.io/en/latest/networks.html.

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```
================================
Printing MONAI config...
================================
MONAI version: 0.5.3
Numpy version: 1.19.5
Pytorch version: 1.5.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: d78c669c67e38ddfbe572f6a0438e9df0b8c65d7

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.15.0
Pillow version: 6.0.0
Tensorboard version: 2.6.0a20210608
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.6.1
ITK version: 5.1.2
tqdm version: 4.60.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.6.2

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Platform: Windows-10-10.0.19041-SP0
Processor: Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
Machine: AMD64
Python version: 3.6.8
Process name: pythonw.exe
Command: ['C:\\Users\\lh18\\AppData\\Local\\Continuum\\anaconda2\\envs\\lhv\\pythonw.exe', '-m', 'spyder_kernels.console', '-f', 'C:\\Users\\lh18\\AppData\\Roaming\\jupyter\\runtime\\kernel-c81488ef87bd.json']
Open files: [popenfile(path='C:\\Users\\lh18\\AppData\\Local\\Spyder\\QtWebEngine\\Default\\Visited Links', fd=-1), popenfile(path='C:\\Users\\lh18\\.anaconda\\navigator\\scripts\\lhv\\spyder-out-2.txt', fd=-1), popenfile(path='C:\\Users\\lh18\\.anaconda\\navigator\\scripts\\lhv\\spyder-err-2.txt', fd=-1), popenfile(path='C:\\Users\\lh18\\AppData\\Local\\Temp\\spyder\\kernel-c81488ef87bd.stderr', fd=-1), popenfile(path='C:\\Users\\lh18\\.ipython\\profile_default\\history.sqlite', fd=-1), popenfile(path='C:\\Users\\lh18\\.anaconda\\navigator\\logs\\navigator.log', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\kernel32.dll.mui', fd=-1), popenfile(path='C:\\Users\\lh18\\.anaconda\\navigator\\navigator.lock', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1)]
Num physical CPUs: 4
Num logical CPUs: 8
Num usable CPUs: 8
CPU usage (%): [1.0, 0.6, 3.2, 0.5, 0.8, 0.6, 0.9, 0.3]
CPU freq. (MHz): 3600
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 73.7
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.7
Available memory (GB): 24.1
Used memory (GB): 7.6

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
GPU 0 Name: Quadro P600
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 3
GPU 0 Total memory (GB): 2.0
GPU 0 CUDA capability (maj.min): 6.1

**Additional context**

**Comment by Nic-Ma** [comment]
I would suggest you to try the latest MONAI version.

Thanks.

**Comment by LaiaHumbertVidan** [comment]
It worked! Thank you!
________________________________
