### ISSUE TITLE
ScaleIntesityRange performance

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#3276]
Related to https://github.com/Project-MONAI/MONAI/issues/3234

I need to normalize Uint8 image as (255 - x)/255, 
for which, the closest transform I found is
ScaleIntensityRange(a_min=255., a_max=0., b_min=0., b_max=1., clip=False, dtype=np.float32)

But with this, the overall training speed is 12% slower. And this transform is 5-6 times slower the my Manual simple function. 
First, the casting to float32 happens at the very end of ScaleIntensityRange, so all calculations are in double and only at the end cast to float32 (my example runtime 0.19s). If you pre-cast to float32, then speed improves ~2x (0.09s), but still not as fast as direct calculation (0.04s)
 
any recommendations on that?  is there a different transform I can use?
any should we change casting to float32 to be the first line in ScaleIntensityRange?
thanks

```
import numpy as np
from monai.transforms import Compose, ScaleIntensityRange, CastToType
import time

a=np.random.randint(255, size=(64, 3, 256, 256), dtype=np.uint8)

scaler = ScaleIntensityRange(a_min=255., a_max=0., b_min=0., b_max=1., clip=False, dtype=np.float32)
castscaler = Compose([CastToType(dtype=np.float32), scaler])

start = time.time()
b = (255 - a).astype(np.float32) / float(255)
print('Directly:', time.time()-start)

start = time.time()
b=scaler(a)
print('ScaleIntensityRange on uint8, time:', time.time()-start)

start = time.time()
b=castscaler(a)
print('ScaleIntensityRange pre-casted time:', time.time()-start)
```

Output:
```
Directly: 0.036348819732666016
ScaleIntensityRange on uint8, time: 0.19264698028564453
ScaleIntensityRange pre-casted time: 0.09259486198425293
```

**Comment by Nic-Ma** [comment]
Hi @myron ,

I think it will convert to `float32` before computation if you set `dtype=np.float32` in the transform.
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/utils.py#L168
Maybe the type check or data type check in the function took more time than converting directly:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/utils/type_conversion.py#L202
@wyli @rijobro What do you guys think?

Thanks in advance.

**Comment by wyli** [comment]
I feel this is reasonably good:
```py
ScaleIntensityRange(a_min=np.uint8(255), a_max=np.float32(0), b_min=np.float32(0), b_max=np.float32(1), clip=False)
```
0.03402090072631836

**Comment by myron** [comment]
@wyli this works but produces  completely wrong output

It turned out if one of the args ( eg a_min) is an Integer,  the output is wrong completely! which looks like a BUG

```
import numpy as np
from monai.transforms import Compose, ScaleIntensityRange, CastToType, ShiftIntensity, ScaleIntensity
import time
a=np.array([0,1,100,255]).astype(np.uint8)

print('input',a)

start = time.time()
b = (255 - a).astype(np.float32) / float(255)
print('Directly:', time.time()-start, b )

start = time.time()
b = (255 - a).astype(np.float32) / float(255)
print('Directly:', time.time()-start, b )

scaler1 = ScaleIntensityRange(a_min=255, a_max=0, b_min=0, b_max=1, clip=False, dtype=np.float32)
start = time.time()
b1=scaler1(a)
print('scaler1 (a,b in int):', time.time()-start, b1)

scaler2 = ScaleIntensityRange(a_min=255., a_max=0., b_min=0., b_max=1., clip=False, dtype=np.float32)
start = time.time()
b2=scaler2(a)
print('scaler2 (a,b in double):', time.time()-start, b2)

scaler3= ScaleIntensityRange(a_min=np.uint8(255), a_max=np.float32(0), b_min=np.float32(0), b_max=np.float32(1), clip=False)
start = time.time()
b3=scaler3(a)
print('scaler3  time:', time.time()-start, b3)

scaler4= ScaleIntensityRange(a_min=np.float32(255), a_max=np.float32(0), b_min=np.float32(0), b_max=np.float32(1), clip=False)
start = time.time()
b4=scaler4(a)
print('scaler4  time:', time.time()-start, b4)

```
output

```
input [  0   1 100 255]
Directly: 2.6702880859375e-05 [1.         0.99607843 0.60784316 0.        ]
scaler1 (a,b in int): 4.410743713378906e-05 [-0.00392157 -0.00784314 -0.39607844  0.        ]
scaler2 (a,b in double): 2.09808349609375e-05 [1.         0.99607843 0.60784316 0.        ]
scaler3  time: 3.3855438232421875e-05 [-0.00392157 -0.00784314 -0.39607844  0.        ]
scaler4  time: 2.5987625122070312e-05 [1.         0.99607843 0.60784316 0.        ]

```

In this example only scaler2 and scaler4 outputs the correct result. 
For scaler1 all args are in int, and the result is wrong, I suspect it's because it does calcluations in int first (and only casts to float at the end), and if the input is uint8 it fails
For scaler3 (your example) only a_min is in uint8, but it produces wrong result too


this is a very subtle bug, since setting a_min=255 (gives a wrong output) and a_min=255. (notice dot a the end, gives correct result)

**Comment by myron** [comment]
scaler4 works correctly, but is still 2x slower than Direct on a large size data. I think When you merge https://github.com/Project-MONAI/MONAI/pull/3277 it will be acceptable

we should still file/fix this bug  .  Probably if the data is Unsigned int, we should convert to final precision right away in ScaleIntensityRange, and not at the end

**Comment by wyli** [comment]
Sure, Also I think in that case the conversion should be done explicitly by, for example `Compose([CastToType(dtype=np.float32), scaler])`.
