### ISSUE TITLE
Different interpolation orders in Transforms for different input dict keys

### ISSUE THREAD

**Issue by martaranzini** [Project-MONAI/MONAI#328]
**Is your feature request related to a problem? Please describe.**
The composable transforms Resized, Rotated, RandRotated, Zoomd and RandZoomd do not allow to define different interpolation orders for different keys in the input dictionary, as the transform input `order` expects only a single integer and cannot accept a list. The possibility to define different interpolation orders would be useful for e.g. image-segmentation pairs, where the former might need interpolation order >= 1, while the segmentation requires interpolation order 0.

**Describe the solution you'd like**
A modification of the transforms to accept a list of orders, similar to what is already implemented for Spacingd (```interp_order``` input) or for the Rand2DElastic (```mode``` input). This would allow to define, e.g.:
```python
Resized(keys=['img', 'seg'], spatial_size=[96, 96], order=(1, 0))
```

**Describe alternatives you've considered**
For the Resized I could have the following workaround:
```python
transf = Compose([
    Resized(keys=['img'], spatial_size=[96, 96], order=1),
    Resized(keys=['seg'], spatial_size=[96, 96], order=0, anti_aliasing=False)])
```
However, this cannot work for data augmentation layers RandRotated and RandZoomd as it would apply different randomisation to the image and its respective segmentation.

**Additional context**
In the case of the Resized, the same feature would be useful for other inputs such as the ```anti_aliasing```.

**Comment by Nic-Ma** [comment]
Hi @martaranzini ,

Thanks for your issue report, that's truly not good enough.
You can try to use `RandAffined` transform for spatial transform operations which supports different `interp_order` for different keys.
And we are working on your issue to replace all the spatial transforms with new API.
Thanks.
