### ISSUE TITLE
Federated Learning 

### ISSUE THREAD

**Issue by Robin-des-Bois** [Project-MONAI/MONAI#329]
I am curious whether -and if so how- federated learning is on the roadmap of this project. The term appears in a few locations in the wiki, but without much context. 

The NVIDIA Clara project seems to have similar goals as this project apart from MONAI being open source and PyTorch based. Both projects are initiated by NVIDIA. Is MONAI intended as an open, PyTorch alternative/replacement to NVIDIA Clara including federated learning capabilities or is the focus a different one?

**Comment by wyli** [comment]
I think it'll become clearer with https://github.com/Project-MONAI/MONAI/issues/498

**Comment by Robin-des-Bois** [comment]
I guess this blog entry answers the question. 

https://blogs.nvidia.com/blog/2020/04/21/monai-open-source-framework-ai-healthcare/

> Future releases of NVIDIA Clara will also leverage the MONAI framework. We plan to bring together development efforts for NVIDIA Clara medical imaging tools and MONAI to continue delivering domain-optimized, robust software tools for researchers in healthcare imaging.

**Comment by wyli** [comment]
there's currently no plan to release the FL capabilities of Clara here. please see also https://github.com/Project-MONAI/tutorials/tree/master/federated_learning, https://github.com/Project-MONAI/tutorials/issues/46 I'm closing this ticket for now.
