### ISSUE TITLE
RandAffined fails with KeyError when allow_missing_keys and key at index 0 is missing

### ISSUE THREAD

**Issue by Spenhouet** [Project-MONAI/MONAI#3292]
**Describe the bug**
We have a pipeline in which not all samples have the same keys.
The `RandAffined` transform accesses fallback data via index 0.
If index 0 is a missing key, then this transform will fail with a `KeyError`.

```python
805   sp_size = fall_back_tuple(self.rand_affine.spatial_size, data[self.keys[0]].shape[1:])
806   # change image size or do random transform
807   do_resampling = self._do_transform or (sp_size != ensure_tuple(data[self.keys[0]].shape[1:]))
```

**Expected behavior**
If the option `allow_missing_keys` is set, I would expect the `RandAffined` transform to take the first element of the existing keys as fallback.

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

Thanks for your feedback.
It sounds like a good enhancement for the components, we have the logic `data[self.keys[0]].shape[1:]` in several transforms. I will try to update them based on your idea.

Thanks.

**Comment by Spenhouet** [comment]
@Nic-Ma Any idea how I could work around this without needing to patch all augmentation transforms?
I tried adding a fake image as first key but this is then actually used to resize the image (in the RandAffine transform). Probably this is an independent bug report.

**Comment by Spenhouet** [comment]
Okay, the RandAffine has much more problems. It is not working at all for us... I will use the torch.io transform instead. I don't have the time to open the bug report currently. I have probably more than 20 bug reports on my list which I did not yet report. It feels like I have half of MONAI patched in my code base... this really start to get frustrating.

**Comment by Spenhouet** [comment]
Just to note down: RandGaussianNoised has the same issue with missing keys.

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

Thanks for your feedback.
I am already working on a PR to address this issue, will submit for review soon.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

The PR had been merged into `dev` to fix this issue.

Thanks for your feedback.

**Comment by Spenhouet** [comment]
@Nic-Ma Thanks, I'm already testing it. I will give feedback if something does not work.

**Comment by Spenhouet** [comment]
@Nic-Ma I'm running in the issue that our pipeline has completely different keys for different pipeline entries.
So for some, all keys are missing.
With the normal `allow_missing_keys` logic, that is not a problem, since the iteration which applies the transforms will not iterate anything and just return the unchanged dict.
This would also need to happen here in the case that all keys are missing.

In our internal code we patched this by adding the following lines to the start of the transform call:

```python
if not any(self.key_iterator(d)):
    return d
```

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

Thanks for your feedback, that's interesting for the all missing case, let me think about it and try to improve locally.

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

I submitted PR https://github.com/Project-MONAI/MONAI/pull/3325 to support no keys case.

Thanks.

**Comment by Spenhouet** [comment]
Hi @Nic-Ma,

looks good to me! Thanks you!
