### ISSUE TITLE
ResNet class does not respect argument feed_forward=False

### ISSUE THREAD

**Issue by codingS3b** [Project-MONAI/MONAI#3314]
**Describe the bug**
The ResNet class has a parameter `feed_forward` which allows skipping of the final dense layer if I intepret that correctly. A respective layer is only created if the parameter is set to True (see [here](https://github.com/Project-MONAI/MONAI/blob/bfa054b9c3064628a21f4c35bbe3132964e91f43/monai/networks/nets/resnet.py#L231)) but in the forward pass, there is no query for whether the layer actually exists [see here](https://github.com/Project-MONAI/MONAI/blob/bfa054b9c3064628a21f4c35bbe3132964e91f43/monai/networks/nets/resnet.py#L308).

**To Reproduce**
```python
import torch
from monai.networks.nets.resnet import resnet50

x = torch.ones((1, 1, 64, 64, 64))
model_monai = resnet50(spatial_dims=x.ndim-2, n_input_channels=x.shape[1], feed_forward=False)
print(model_monai)

# throws an error
y = model_monai(x)

```

**Expected behavior**
The ResNet class should not throw an error if `feed_forward=False`.

**Comment by Nic-Ma** [comment]
Hi @codingS3b ,

Thanks for your interest here and feedback.
We will try to investigate and reproduce the issue ASAP.

Thanks.
