### ISSUE TITLE
RandAffined does not work as expected

### ISSUE THREAD

**Issue by Spenhouet** [Project-MONAI/MONAI#3316]
**Describe the bug**

Given the following image and label:
![image](https://user-images.githubusercontent.com/7819068/141314133-b37f21c1-48eb-413c-bba4-21c4e774f745.png)

When applying `RandAffined`, the image and labels no longer match:

![image](https://user-images.githubusercontent.com/7819068/141314287-5711ee04-cb1e-4cd7-9c55-451fcd0528b5.png)

**To Reproduce**

1. Load these files: [example_files.zip](https://github.com/Project-MONAI/MONAI/files/7521159/example_files.zip)
2. Execute this pipeline:
```python
from pathlib import Path

import numpy as np
from monai.transforms.compose import Compose
from monai.transforms.io.dictionary import LoadImaged, SaveImaged
from monai.transforms.spatial.dictionary import RandAffined
from monai.transforms.utility.dictionary import (EnsureChannelFirstd, ToTensord)
from monai.utils.enums import GridSampleMode

path = Path('scratch/rand_affine')

T1_KEY = 't1'
LABEL_KEY = 'labels'
FILE_KEYS = [T1_KEY, LABEL_KEY]
SAMPLE_MODES = [GridSampleMode.BILINEAR, GridSampleMode.NEAREST]

data = {
    T1_KEY: path / 't1.nii.gz',
    LABEL_KEY: path / 'labels.nii.gz',
}

process = Compose([
    LoadImaged(FILE_KEYS),
    ToTensord(FILE_KEYS),
    EnsureChannelFirstd(FILE_KEYS),
    RandAffined(
        FILE_KEYS,
        rotate_range=5.0 * np.pi / 180.0,  # type: ignore
        prob=1.0,
        mode=SAMPLE_MODES,
        allow_missing_keys=True,
    ),
    SaveImaged(
        FILE_KEYS,
        output_dir=path,
        output_postfix=f"out",
        resample=False,
        output_dtype=np.float32,
        separate_folder=False,
        print_log=False,
    )
])

process([data])
```

**Expected behavior**
The same random affine transformation is applied to all images.
After the transform the labels still match the image.

**Additional context**
I did not yet identify the issue.

**Comment by wyli** [comment]
I couldn't replicate the issue locally with a macbook and visualise with itk-snap.
<img width="776" alt="Screenshot 2021-11-11 at 15 51 27" src="https://user-images.githubusercontent.com/831580/141327964-e01303f6-91a0-43d1-808a-4e0cc6599118.png">

could you help provide more info?

**Comment by Spenhouet** [comment]
@wyli You did not use the data provided by me. Could you try it with that? It is part of the reproduction.

**Comment by wyli** [comment]
> @wyli You did not use the data provided by me. Could you try it with that? It is part of the reproduction.

I downloaded and unzipped the file, there are two files, `t1.nii.gz` and `labels.nii.gz`. itk-snap refuses to display 
<img width="398" alt="Screenshot 2021-11-11 at 15 58 35" src="https://user-images.githubusercontent.com/831580/141328988-a1856c6e-2dce-4071-930e-00eb5e071bc7.png">
the labels.nii.gz as segmentations for t1.nii.gz

**Comment by Spenhouet** [comment]
I'm not a itk-snap user but if there is a problem in itk-snap probably good to report it to their project. Not really the issue I'm reporting here though.

Try using MRIcroGL or Slicer. Both work fine.
