### ISSUE TITLE
Docs on https://docs.monai.io/ default to "latest" instead of "stable"

### ISSUE THREAD

**Issue by tomvars** [Project-MONAI/MONAI#3343]
Can be frustrating for users to find API differences between the default version of docs and the latest stable release, e.g the default version of docs suggest the`RandCropByPosNegLabeld` transform accepts an `allow_smaller` argument but this is not implemented in `v0.7.0`. Might be better to default the docs version to "stable".

**Comment by wyli** [comment]
thanks @tomvars, the default version is updated.
