### ISSUE TITLE
`AsDiscreted` bug when `threshold=0.0`

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#3387]
Reproduce the bug:

```
from monai.transforms import AsDiscreted
a = AsDiscreted(keys="pred", threshold=0.0)
```

<img width="1089" alt="Screen Shot 2021-11-23 at 10 56 39 PM" src="https://user-images.githubusercontent.com/68361391/143047946-07624927-dda0-4899-bfe6-36caec03d26a.png">

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Thanks for your bug report, let me fix it now.

**Comment by yiheng-wang-nv** [comment]
I think the PR in #3388 does not solve the issue, and a `threshold=0.0` test case does not added in the PR.
As you can see:

![Screen Shot 2021-11-24 at 1 58 22 PM](https://user-images.githubusercontent.com/68361391/143183227-5ed3e4f2-842c-40d0-b95d-b12071f5b962.png)

**Comment by yiheng-wang-nv** [comment]
I think I've found the error place:
https://github.com/Project-MONAI/MONAI/blob/839f7ef0536129df806bc2f9317bc9e65e3eee70/monai/transforms/post/array.py#L246

@Nic-Ma , this line is wrong since `0.0 or None` is None.
In addition, parameters in `__call__` of `AsDiscrete` are not covered in `test_as_discrete.py`, thus the test function does not find this issue, I think we may need more test cases.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Thanks for your test, let me have a try and investigate it ASAP.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I submitted PR #3393 to fix it and added more unit tests to cover the threshold=0.0 case.
The `call()` function of array transform is already covered by the dict transform, because:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/post/dictionary.py#L204
Could you please help review it?

Thanks in advance.
