### ISSUE TITLE
"WG: Pathology" label and category

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#3411]
**Is your feature request related to a problem? Please describe.**
For MONAI Pathology Working Group "WG: Pathology", *label* or *category (for discussion)* has been created. It would be great if we can have those tags to organize the issues and discussions. Thanks

**Comment by wyli** [comment]
thanks, the label list is now updated.

**Comment by drbeh** [comment]
Thank you, @wyli!
