### ISSUE TITLE
Make activation function a parameter of ResBlock

### ISSUE THREAD

**Issue by patricio-astudillo** [Project-MONAI/MONAI#3414]
The activation function of a ResBlock is currently hard coded. It would be nice if we could set it ourselves to a specific activation function.

https://github.com/Project-MONAI/MONAI/blob/73d9afa0e21ed190a8582f2ef087d3a98388bec6/monai/networks/blocks/segresnet_block.py#L69

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help take a look at this ticket?

Thanks in advance.

**Comment by patricio-astudillo** [comment]
I can add it too if you'd like and make a pull request?

**Comment by yiheng-wang-nv** [comment]
Hi @patricio-astudillo , sure, it would be nice if you can submit a pull request for it
