### ISSUE TITLE
WSIReader with OpenSlide can load regions of incorrect size by default

### ISSUE THREAD

**Issue by dccastro** [Project-MONAI/MONAI#3415]
**Describe the bug**
When `size` is unspecified and using the OpenSlide backend, `WSIReader.get_data()` assumes by default that the size of the slide at a given magnification `level` is `2**level` times smaller than the full-resolution size (see [here](https://github.com/Project-MONAI/MONAI/blob/0.8.0/monai/data/image_reader.py#L771-L773)). However, the magnification factors are not necessarily consecutive powers of 2, in which case the reader can return arrays of vastly incorrect size.

For example, I've encountered this issue with slides from the TCGA dataset. At the highest `level`, the image is downsampled by 32x instead of the assumed 8x, meaning the reader returns an image array that is 4x larger than necessary in each dimension (filled with 1/16th data, the rest padded with zeros).

**To Reproduce**
1. Download a pathology slide file with inhomogeneous downsampling levels (e.g. file "TCGA-2A-A8VL-01Z-00-DX1.2C2BD6EF-EC17-4117-AE89-A22B67AFB233.svs" from TCGA, available here on [the GDC portal](https://portal.gdc.cancer.gov/cases/49197847-cc83-4ce1-8397-d09cea4c4928?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.case_id%22%2C%22value%22%3A%5B%2249197847-cc83-4ce1-8397-d09cea4c4928%22%5D%7D%7D%5D%7D); has [1x, 4x, 16x, 32x] downsampling).
2. Install OpenSlide and its Python wrapper.
3. Instantiate `WSIReader(backend='openslide')`
```python
from monai.data.image_reader import WSIReader
reader = WSIReader(backend='openslide')
slide = reader.read("<your slide file>")
level = slide.level_count - 1  # pick highest level for demonstration
image = reader.get_data(slide, level=level)
# image is 4x4 times larger than expected and filled with 15/16=93.8% zeros
```

**Expected behavior**
The `WSIReader` should consider the actual magnification levels and corresponding dimensions encoded in the file headers. This information is readily available in the OpenSlide object's `level_dimensions` attribute ([docs](https://openslide.org/api/python/#openslide.OpenSlide.level_dimensions)).

**Environment**
- `monai` v0.6.0 (but same behaviour is still implemented in latest v0.8)
- `openslide` v3.4.1
- `openslide-python` v1.1.2

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Could you please help take a look at this ticket?

Thanks in advance.
