### ISSUE TITLE
ViT does not support torchscript

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#3432]
~~class `PatchEmbeddingBlock` does not support torchscript, due to the module `einops.layers.torch.Rearrange` used.~~

Update (02.09.2022) After Einops v0.4.0 released, it supports torchscript now, but the current ViT implementation still cannot support torchscript directly, some changes are necessary, and the einops usage should be kept.

**Comment by yiheng-wang-nv** [comment]
see also #3428

**Comment by ahatamiz** [comment]
Hi @yiheng-wang-nv 

Maybe you look at this:
https://github.com/arogozhnikov/einops/blob/45e795f122840beec70f0e1970b1e37b5809a8e6/tests/test_layers.py#L188

torchscript works on Rearrange.
