### ISSUE TITLE
Add DecathlonDatalist to enhance decathlon style loading

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#3444]
**Is your feature request related to a problem? Please describe.**
Currently, we already have several useful utilities to load or sample the decathlon datalist, would be nice to add a class to combine and enhance the feature.
We already have a reference implementation in NVIDIA Clara and can config it in the JSON file:
```
{"datalist": {"name": "DecathlonDatalist", "args": {XXX}}},
{"dataset": {"name": "CacheDataset", "args": {"data": "@datalist"}}}
```
I will try to reimplement it according to MONAI style.

**Comment by wyli** [comment]
Hi Nic, would be great to have more details on this, is it an enhancement of https://github.com/Project-MONAI/MONAI/blob/0935d5ab60b78b74e37e542244846de9ccfe7e39/monai/apps/datasets.py#L152

**Comment by Nic-Ma** [comment]
Hi @wyli ,

`DecathlonDatalist` is mainly supposed to load "decathlon style" datalist from JSON file, and do more logic.
It's a class level combination of the utilities in this file:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/decathlon_datalist.py

Thanks.
