### ISSUE TITLE
无法从monai引入ImageDataset

### ISSUE THREAD

**Issue by sole12343** [Project-MONAI/MONAI#3448]
![1638882889(1)](https://user-images.githubusercontent.com/52155079/145035708-25083b9e-6d80-40a2-b180-118c44f80c22.png)
我本来可以正常引用，可是当我无法正常读取我的数据后，我在网上找到方法，我下载pip install monai all，然后我就无法正常引用ImageDataset ,是你们更新后取消了这个包嘛？

**Comment by Nic-Ma** [comment]
Hi @sole12343 ,

The `ImageDataset` is still available in the latest MONAI codebase:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_dataset.py#L23

Thanks.
