### ISSUE TITLE
How to use Transchex?

### ISSUE THREAD

**Issue by silver-fox-12** [Project-MONAI/MONAI#3449]
Thank you for all the work in creating Monai! 

I'm new to the framework and curious if there are any tutorials on using the `Transchex` model? Is there any paper published related to the model? I could not find any information on the Internet. 

Additionally, would it be possible to use `Transchex`(or any other model supported by Monai) on the [CheXpert dataset](https://stanfordmlgroup.github.io/competitions/chexpert/)?

I'd be happy to contribute if that's something relevant for the project 🙂

**Comment by ahatamiz** [comment]
Hi @silver-fox-12 

Thanks for your interest. We will have a tutorial for TrasnChex very soon. 

Thanks

**Comment by silver-fox-12** [comment]
Thank you @ahatamiz! That'd be awesome 🙂

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/tree/master/multimodal/openi_multilabel_classification_transchex
