### ISSUE TITLE
Inconsistency of type hints/docstring VS codes for PersistentDataset

### ISSUE THREAD

**Issue by YuanTingHsieh** [Project-MONAI/MONAI#3452]
**Describe the bug**
There are inconsistencies in the PersistentDataset.
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset.py#L100

In docstring it says the "cache_dir" can be None and type hint it shows Optional.
If we want to be consistent with the docstring, we should add a default value None to this cache_dir argument.

**Comment by Nic-Ma** [comment]
Hi @YuanTingHsieh ,

Thanks for raising the issue.
I will try to fix it ASAP.

Thanks.

**Comment by wyli** [comment]
Typing.Optional indicates that the value can be None: https://docs.python.org/3/library/typing.html#typing.Optional

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your sharing.
The `None` value actually has no meaning in `PersistentDataset`, it will do nothing if `cache_dir=None`.
So I tried to make it more clear in #3453 , same as what you have set for `LMDBDataset`:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset.py#L426

Thanks.

**Comment by wyli** [comment]
When None is provided, the dataset becomes a regular dataset, it is a convenient option, I suggest we keep the current behaviour.

**Comment by Nic-Ma** [comment]
Thanks @wyli for your explanation.

Hi @ericspod @rijobro ,

what do you guys think about this `cache_dir` arg of `PersistentDataset`?
I feel it's not necessary to allow `None` value for it. If all you guys think it should support `None` to fallback to regular Dataset, I am OK to update `LMDBDataset` to be consistent with `PersistenDataset`.

Thanks in advance.

**Comment by wyli** [comment]
In my opinion the lmdbdataset has an additional logic (compared with persistentdataset) of creating a database file, allowing for none is confusing.

**Comment by Nic-Ma** [comment]
Hi @ericspod @rijobro ,

Could you please help share some comments about this discussion and the PR #3453 ?

Thanks in advance.

**Comment by wyli** [comment]
Just to clarify that the `Optional` type is different from an optional argument as described in the documentation (https://docs.python.org/3/library/typing.html#typing.Optional):

> "An optional argument with a default does not require the Optional qualifier on its type annotation just because it is optional. "

so I think for the `PersistentDataset`, it correctly states the type (`Optional`, allowing for `None`), and does not provide a default (https://github.com/Project-MONAI/MONAI/issues/2136).

For the lmdbdataset, I feel providing a "None" option can be confusing and reduce the readability, because the database handling logic is already quite complicated.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your explanation, I understand your point.
I just feel maybe it's not necessary to allow passing `None` to `PersistentDataset` to fallback to the regular Dataset.
For example, we don't allow `None` output dir in `SaveImaged`:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/io/dictionary.py#L220
Anyway, it's not a blocker issue or an obvious bug for us.

Thanks for the interesting discussion.

**Comment by YuanTingHsieh** [comment]
Thanks for providing the difference between type hint `Optional` and an optional argument.
I understand the original logic of the code now.

When I use this PersistentDataset, I would expect this persist something for me.
So personally, I prefer the `cache_dir` be required or default to somewhere like `/tmp/`, and PersistentDataset always persist data.

But I can also understand maybe someone wants the convenient way to turn it on and off.

If the decision is to allow `None` for `cache_dir` option so that it can fallback to regular Dataset (for convenience).
I would suggest add a section "If `cache_dir` is `None`, this dataset falls back to regular `Dataset`" to the Note docstring upfront (rather than in the args section) to make this clearer

**Comment by wyli** [comment]
We have the docstring for the input argument to describe this, which is quite clear to me: https://github.com/Project-MONAI/MONAI/blob/a7bc4a3cbaeaa3c505a25ca2ddf6922bda8ea7dc/monai/data/dataset.py#L165-L170

I'd suggest we close this ticket and the PR.

**Comment by Nic-Ma** [comment]
@ericspod @rijobro , seems you guys don't have any comments here, let me close the ticket and PR as @wyli suggested.

Thanks for the discussion.
