### ISSUE TITLE
Unused cls_token in PatchEmbeddingBlock

### ISSUE THREAD

**Issue by night-gale** [Project-MONAI/MONAI#3454]
**Describe the bug**
When I was training the `ViT` with `torch DistributedDataParallel`, during backward, `torch` raises error and reports that 
```
Parameters which did not receive grad for rank 0: vit.patch_embedding.cls_token
```
which means that the `cls_token` did not participate in the backward process.

I checked the implementation of `ViT` and `PatchEmbeddingBlock` and found the unused `cls_token` in `monai.networks.blocks.patchembedding.py: PatchEmbeddingBlock`.
![image](https://user-images.githubusercontent.com/52153974/145175732-6497f7a3-413b-4999-9843-feb0fec19b81.png)

**To Reproduce**
1. set environment variable in shell `TORCH_DISTRIBUTED_DEBUG=INFO`
2. train `ViT` with `torch DistributedDataParallel`

**Comment by Nic-Ma** [comment]
Thanks for raising the issue.
Hi @ahatamiz ,

Could you please help double confirm the issue?
If we really don't need the `cls_token`, please remove it.

Thanks in advance.

**Comment by night-gale** [comment]
Hi! @ahatamiz 
Thanks for your reply!

I understand that the cls_token is an essential component of ViT and can be toggled off by passing classification as False.

However, the redundant cls_token I found is in the PatchEmbeddingBlock. It is not reference in the forward method and cannot be turned off by passing argument.

I currently removed the cls_token in my local copy of Monai and everything now works fine.

It would be great if you could double check the implementation of PatchEmbeddingBlock.

Thanks!

**Comment by ahatamiz** [comment]
May I ask what application the ViT is used for ? if it is for classification, what I meant was to turn on the classification by doing something like:
`monai.networks.nets.ViT(img_size=(96,96,96), patch_size=(16,16,16), classification=True)
`
This way, it ensures that `cls_token` is being created and used. 

As indicated [here](https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/vit.py#L96), `cls_token` is only created if the ViT is used for classification. If not, it does not exist. 

Thanks

**Comment by ahatamiz** [comment]
Hi @Nic-Ma 

Thanks for the efforts. I would be appreciate it if this can be addressed in future PRs. 

Thanks.

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

OK, sure, I will fix it in a PR.

Thanks.
