### ISSUE TITLE
The loaded image and label get reversed in MONAI

### ISSUE THREAD

**Issue by hsiangyuzhao** [Project-MONAI/MONAI#3455]
I want to perform image registration and use MONAI-based data pipeline in my research. However, when I am loading image pair with MONAI, the image & label map of the moving image get "reversed".
![myplot](https://user-images.githubusercontent.com/53631393/145181218-483536d7-b8ca-44a4-8e2b-ddcd49a1e77d.png)
Here we can see that the label map of the image on the right doesn't match the one on the left.
However, when I am viewing the image with ITKSnap or loading them with TorchIO framework everything looks fine.
![Snipaste_2021-12-08_17-06-49](https://user-images.githubusercontent.com/53631393/145181391-75e963d8-769e-45a9-b4a7-a4040f75404c.png)
![FotoJet](https://user-images.githubusercontent.com/53631393/145181948-e44eb67e-d2db-494a-ac53-cdccbcdadffa.jpg)

(Upper one is ITKSnap and lower one is TorchIO)

**Comment by Nic-Ma** [comment]
Hi @hsiangyuzhao ,

Thanks for your experiments and feedback here.
Could you please help share your test program with MONAI? Let's check deeper about the logic.

Thanks in advance.

**Comment by hsiangyuzhao** [comment]
Hi @Nic-Ma ,
Thanks for the reply. The data loading code with MONAI is pasted below.
I guess it has something to do with the coordinate system but I have no idea where the problem occurs. Also, I have found that loading the image with Nibabel directly leads to the same result (the label map and image get "reversed"). The code is also pasted below.
```python
    def get_training_transform(self):
        image_keys = ('tbi', 't1')
        all_keys = ('tbi', 't1', 'lesion', 'tbi_label', 't1_label')
        augment = Compose([
            LoadImaged(keys=all_keys),
            AddChanneld(keys=all_keys),  # as channel first
            ResizeWithPadOrCropd(keys=all_keys, spatial_size=(176, 224, 176)),
            Resized(keys=all_keys, spatial_size=self.spatial_size),
            ScaleIntensityRangePercentilesd(keys='t1', b_max=1, b_min=0, upper=95, lower=5),
            # RandAxisFlipd(keys=all_keys, prob=0.5),
            # RandScaleIntensityd(keys=image_keys, factors=0.1, prob=0.5),
            # RandShiftIntensityd(keys=image_keys, offsets=0.1, prob=0.5),
            # Rand3DElasticd(keys=all_keys, prob=0.5, mode='nearest',
            #                sigma_range=(1, 20), magnitude_range=(0.3, 2.3),
            #                rotate_range=(np.pi / 6, np.pi / 6, np.pi / 6),
            #                shear_range=(0.1, 0.1, 0.1),
            #                scale_range=(0.2, 0.2, 0.2)),
            EnsureTyped(keys=all_keys)
        ])
        return augment
```

```python
img = nib.load('./img.nii').get_fdata()
label = nib.load('./label.nii').get_fdata()

img1 = nib.load('./img1.nii').get_fdata()
label1 = nib.load('./label1.nii').get_fdata()

import matplotlib.pyplot as plt

slice = 80
plt.figure(figsize=(12, 4))
plt.subplot(1, 4, 1)
plt.imshow(img[:, :, slice], cmap='gray')
plt.subplot(1, 4, 2)
plt.imshow(label[:, :, slice])
plt.subplot(1, 4, 3)
plt.imshow(img1[:, :, slice], cmap='gray')
plt.subplot(1, 4, 4)
plt.imshow(label1[:, :, slice])
plt.show()
```

**Comment by hsiangyuzhao** [comment]
![1](https://user-images.githubusercontent.com/53631393/145183798-29a1177a-9212-411d-9f3c-d7a18d607df5.png)
That is what happens when loading with Nibabel directly. Just the same as using MONAI.

**Comment by Nic-Ma** [comment]
Thanks for the test program.
I didn't see any obvious issue in the program, @wyli do you have any findings here?
Maybe we should move it to discussion as @wyli suggested.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @hsiangyuzhao ，

Cool!
Just set that parameter in MONAI `LoadImaged` transform:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/io/dictionary.py#L98

Thanks.

**Comment by hsiangyuzhao** [comment]
@Nic-Ma After reading the docs I have understood what to do with MONAI. Thanks for the reply, I will close the issue now.
