### ISSUE TITLE
Extension for cross-dimensional inference with SlidingWindowInferer

### ISSUE THREAD

**Issue by surajpaib** [Project-MONAI/MONAI#3458]
**Is your feature request related to a problem? Please describe.**
The request is to have an addition for the SlidingWindowInferer to support inference on, for example, 3D CT scans on a slice-by-slice basis using a 2D model. 

**Describe the solution you'd like**
A simple solution exists ofcourse, where the model is run using SimpleInferer on a slice-by-slice basis and then collected. However, adding this support to SlidingWindowInferer will allow it to be more generalized. A single interface can handle the inference for a 3D volume both with 2D and 3D models. 

**Describe alternatives you've considered**
I've implemented a naive version here: https://github.com/ganslate-team/ganslate/blob/master/ganslate/utils/sliding_window_inferer.py
which looks at the `roi_size` and the `inputs` and adds a `network_wrapper` over the 2D model

**Additional context**
I would be happy to contribute a better solution if this is interesting to a larger set of user.

**Comment by Nic-Ma** [comment]
Hi @surajpaib ,

Thanks for your idea here, sounds interesting to me.
And welcome to contribute a separate `inferer` for it.
@ericspod @rijobro What do you guys think?

Thanks in advance.

**Comment by wyli** [comment]
would be great to have a tutorial/demo instead of a dedicated module in the core codebase, please see the previous discussions https://github.com/Project-MONAI/tutorials/issues/130.

**Comment by surajpaib** [comment]
@wyli I see that an appropriate use-case of this has been requested before as well, great! 

The reason I proposed it as an addition to the `SlidingWindowInferer` is that, for most medical imaging use-cases, if you had a 3D volume of `[H, W, D]` and wanted to run a sliding window of size 1 in D over it, you would expect to receive 2D slices that can go into a 2D model then. By adding this to the `SlidingWindowInferer`, this would be taken care of. 

If you think this can be confusing to the end user who expects `[H, W, 1]` from it, which makes sense logically, I'm happy to do a tutorial or demo of it and not have it in the core codebase.

**Comment by wyli** [comment]
sure, perhaps first a pull request to the tutorial repo for a self-contained example, and then we can move the key components to the core codebase. I feel in this way we can focus on the ideas/designs first and don't waste time on the coding style and unit testing etc

**Comment by surajpaib** [comment]
Definitely agree. I'll submit a PR on the tutorial repo. I went through it a bit, where do you suggest I place it, similar to 
https://github.com/Project-MONAI/tutorials/blob/master/modules/3d_image_transforms.ipynb I presume?

**Comment by wyli** [comment]
thanks @surajpaib, that'd be great!

**Comment by Nic-Ma** [comment]
Hi @surajpaib ,

Thanks for your great work for the tutorial, would you like also contribute a PR to add your new SlidingWindow inferer?

**Comment by surajpaib** [comment]
@Nic-Ma 

Thanks and glad to contribute! 

I do have a few design questions on how to add it to `monai`. There are two options I'm thinking of,
1. Editing the existing `SlidingWindowInferer` to add this functionality. 
2. Creating a new `SlidingWindowInferer` / `SliceInferer` class that inherits `SlidingWindowInferer` and provides new functionality. 

The caveat with 1 is that intuitively a user might expect to only pass in 3D ROIs for 3D volumes. So this 2D/(N-1)D ROI version might seem a bit out of place. For 2, this functionality is the highlight so there should be no confusion - however, it might be prudent to add some `assert` and checks to make sure that the user is not confused about the usage of this new class. 

What do you think? I would prefer 2, but would like some comments on what you think might be more appropriate. If there are more options on how to do this, I am glad to discuss as well.

**Comment by Nic-Ma** [comment]
Hi @surajpaib ,

Thanks for your proposals.
I would suggest option 2, it's better to design multiple components for multiple features.
Please try to make the usage clear in the doc-string to help users.

Thanks in advance.

**Comment by surajpaib** [comment]
Hey @Nic-Ma 

Thanks for your input - I agree with your suggestion. I'll send in a PR in the coming days.

Apologies for the inactivity, courtesy of the holidays.
