### ISSUE TITLE
`reduction` for `ContrastiveLoss`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3460]
**Describe the bug**
the error messages and docstring should be consistent
https://github.com/Project-MONAI/MONAI/blob/a7bc4a3cbaeaa3c505a25ca2ddf6922bda8ea7dc/monai/losses/contrastive.py#L89-L91

https://github.com/Project-MONAI/MONAI/blob/a7bc4a3cbaeaa3c505a25ca2ddf6922bda8ea7dc/monai/losses/contrastive.py#L58

**Expected behavior**
implementing the option `reduction="none"`?

**Comment by wyli** [comment]
Hi @finalelement, could you please help look into this one?

**Comment by Nic-Ma** [comment]
Hi @finalelement ,

Could you please help check it?

Thanks in advance.

**Comment by finalelement** [comment]
Sure thing, will get back soon.

**Comment by wyli** [comment]
discussed with @finalelement that I'll deprecate the `reduction` option
