### ISSUE TITLE
ImportError: cannot import name 'Invertd' from 'monai.transforms' (/opt/monai/monai/transforms/__init__.py)

### ISSUE THREAD

**Issue by ataML** [Project-MONAI/MONAI#3474]
Trying to run the Brain Tumor 3D segmentation with MONAI notebook, and i get this error. 

ImportError: cannot import name 'Invertd' from 'monai.transforms' (/opt/monai/monai/transforms/__init__.py)

Environment:

OS: Ubuntu
python version: 3.8
monai version: latest
 cuda version: 11.2, V11.2.67

could you please help me with the issue?

**Comment by wyli** [comment]
Could you please follow the bug report template to include more system info?

**Comment by ataML** [comment]
In the following you can find the detailed system info: 

================================
Printing MONAI config...
================================
MONAI version: 0.5.2+24.g2a4c9e5
Numpy version: 1.19.2
Pytorch version: 1.8.0a0+52ea372
MONAI flags: HAS_EXT = True, USE_COMPILED = False
MONAI rev id: 2a4c9e514bbc603191e49120e9d598a9414c0e75

Optional dependencies:
Pytorch Ignite version: 0.4.4
Nibabel version: 3.2.1
scikit-image version: 0.15.0
Pillow version: 8.2.0
Tensorboard version: 1.15.0+nv
gdown version: 3.13.0
TorchVision version: 0.9.0a0
ITK version: 5.1.2
tqdm version: 4.53.0
lmdb version: 1.1.1
psutil version: 5.8.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.1 LTS
Platform: Linux-4.4.0-194-generic-x86_64-with-glibc2.10
Processor: x86_64
Machine: x86_64
Python version: 3.8.5
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 28
Num logical CPUs: 56
Num usable CPUs: 56
CPU usage (%): [92.1, 98.9, 9.3, 58.9, 100.0, 8.6, 93.4, 2.2, 2.2, 3.3, 21.1, 2.3, 0.0, 64.8, 22.0, 2.2, 2.2, 4.4, 15.6, 2.2, 62.2, 8.9, 3.3, 2.3, 6.7, 95.5, 3.3, 1.1, 2.2, 2.2, 13.0, 3.3, 2.2, 2.2, 2.2, 91.1, 2.2, 1.1, 0.0, 4.4, 0.0, 2.2, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 2.2, 0.0, 98.9]
CPU freq. (MHz): 2140
Load avg. in last 1, 5, 15 mins (%): [30.3, 29.6, 29.2]
Disk usage (%): 83.4
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 251.7
Available memory (GB): 228.7
Used memory (GB): 19.5

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.2
cuDNN enabled: True
cuDNN version: 8100
Current device: 0
Library compiled for CUDA architectures: ['sm_52', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_86']
GPU 0 Name: Tesla P100-PCIE-16GB
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 56
GPU 0 Total memory (GB): 15.9
GPU 0 CUDA capability (maj.min): 6.0

**Comment by Nic-Ma** [comment]
Hi @ataML ,

`Invertd` was introduced in MONAI v0.7 release, could you please help update your MONAI package to the latest?

Thanks.

**Comment by ataML** [comment]
Hi @Nic-Ma, 
thanks for your reply. I updated monai to version 0.8 and still get the same error, here you can find the config:


================================
Printing MONAI config...
================================
MONAI version: 0.8.0
Numpy version: 1.21.5
Pytorch version: 1.10.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 714d00dffe6653e21260160666c4c201ab66511b

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: NOT INSTALLED or UNKNOWN VERSION.
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 8.4.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: NOT INSTALLED or UNKNOWN VERSION.
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70']
GPU 0 Name: Tesla P100-PCIE-16GB
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 56
GPU 0 Total memory (GB): 15.9
GPU 0 CUDA capability (maj.min): 6.0
1
