### ISSUE TITLE
Introduce Boundary loss and Hausdorff loss

### ISSUE THREAD

**Issue by tomvars** [Project-MONAI/MONAI#3481]
Would be great to see the Boundary loss (http://proceedings.mlr.press/v102/kervadec19a.html) introduced into MONAI. Would require a `Transform` to produce distance maps from labels similar to this function - https://github.com/LIVIAETS/boundary-loss/blob/749602d822fcb097c79a7fb708805b8982c37030/utils.py#L260 and two `Loss` classes which could be based off of these implementations:
 https://github.com/LIVIAETS/boundary-loss/blob/749602d822fcb097c79a7fb708805b8982c37030/losses.py#L76
https://github.com/LIVIAETS/boundary-loss/blob/749602d822fcb097c79a7fb708805b8982c37030/losses.py#L99

**Comment by Nic-Ma** [comment]
Hi @tomvars ,

Thanks for your suggestion.
Sounds interesting, @wyli @ericspod is it common medical DL loss functions?
And @tomvars would you like to contribute PR for it?

Thanks in advance.

**Comment by ericspod** [comment]
We'd definitely be interested in new loss functions. My experience was hausdorff calculations can be quite expensive but a fast implementation would be nice to have as a metric as well. @rijobro this might be of interest for the problem we've been working on too.

**Comment by rijobro** [comment]
definitely!
