### ISSUE TITLE
Requires scikit-image>=0.14.2

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#349]
MONAI transforms depend on "resize" method from scikit-image (skimage.transform.resize), and will pass _anti_aliasing_ and _anti_aliasing_sigma_ arguments to this method; however, versions before v0.14.x does not have support arguements, and consequently produce error while  importing transforms from MONAI if previous versions are used.

Also v0.14.0 and v 0.14.1 import "_validate_lengths" from numpy.lib.arraypad, which does not exists anymore, so the appropriate requirement for MONAI should be 0.14.2.

I suggest updating requirements.txt with this minimum requirement:
`scikit-image>=0.14.2`

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

Thanks for your bug report and detailed explanation!
We are working in progress to re-implement several spatial transforms based on PyTorch directly to remove skikit-image dependency, will update as soon as possible.
Thanks.

**Comment by Nic-Ma** [comment]
Thanks for the suggestion, I already updated requirements in PR #357
