### ISSUE TITLE
Transforms for multichannel

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#3506]
```
directory = os.environ.get('/MONAI_DATA_DIRECTORY/')
root_dir = r'D:\' if directory is None else directory

from torch.utils.tensorboard import SummaryWriter
path_to_target = r'D:\'


t1 = sorted(glob.glob(os.path.join(path_to_target, "monai", "*_T1.nii")))
pd = sorted(glob.glob(os.path.join(path_to_target, "monai", "*_PD.nii")))
fs = sorted(glob.glob(os.path.join(path_to_target, "monai", "*_FS.nii")))
ang = sorted(glob.glob(os.path.join(path_to_target, "monai", "*_ANG.nii")))
train_labels = sorted(glob.glob(os.path.join(path_to_target, "monai/traingt", "*.nii.gz")))

data_dicts = [{'t1': t1, 'pd': pd, 'fs': fs, 'ang': ang, 'label': label_name} for t1, pd, fs, ang, label_name in zip(t1, pd, fs, ang, train_labels)]
train_files, val_files = data_dicts[:1], data_dicts[20:21]

def transformations():
    train_transforms = Compose([
        LoadImaged(keys=['t1','pd','fs','ang', 'label']),
        AddChanneld(keys=['t1','pd','fs','ang', 'label']),
        ConcatItemsd(keys=['t1','pd','fs','ang'], name="image"),
        RandCropByPosNegLabeld(keys=["image"], label_key="label", spatial_size=[80,80,80], pos=1, neg=1, num_samples=1),
        RandFlipd(keys=["image",'label'],  prob=0.4, spatial_axis=[0, 1, 2]),
        EnsureTyped(keys=["image",'label'])])
    val_transforms = Compose([
        LoadImaged(keys=['t1','pd','fs','ang','label']),
        AddChanneld(keys=['t1','pd','fs','ang','label']), 
        ConcatItemsd(keys=['t1','pd','fs','ang'], name="image"),
        RandCropByPosNegLabeld(keys=["image"], label_key="label", spatial_size=[80,80,80], pos=1, neg=1, num_samples=1),
        EnsureTyped(keys=["image",'label'])])
    return train_transforms, val_transforms

dice_metric = DiceMetric(include_background=True, reduction="mean", get_not_nans=False)
post_trans = Compose([EnsureTyped(keys=["image",'label']),Activations(sigmoid=True), AsDiscrete(threshold_values=True)])

def train_process(fast=True):
    epoch_num = 500
    learning_rate = 1e-3
    val_interval = 1

    train_trans, val_trans = transformations()
    train_ds = CacheDataset(data=train_files, transform=train_trans,  cache_num=1, cache_rate=1.0, num_workers=0)
    val_ds = CacheDataset(data=val_files, transform=val_trans, cache_num= 1, cache_rate=1.0, num_workers=0)
    train_loader = DataLoader(train_ds, batch_size=1, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=1, num_workers=0)

    check_data = first(train_loader)
    print(check_data["image"].shape, check_data["label"].shape)

    exit()
```

---------------------------------------------------------------------------------------------------------------------------

Loading dataset: 100%|█████████████████████████████████| 1/1 [00:01<00:00,  1.03s/it] 
Loading dataset: 100%|█████████████████████████████████| 1/1 [00:01<00:00,  1.04s/it] 
torch.Size([1, 4, 80, 80, 80]) torch.Size([1, 1, 80, 80, 80])

(monai) D:\>

---------------------------------------------------------------------------------------------------------------------------

Hi again,

Trying to load 4 channels of MRI images and a single 14 classes label. I find that the shape output are different:

(torch.Size([1, 4, 80, 80, 80]) torch.Size([1, 1, 80, 80, 80])

I have tried addchanneld with concatitems for this. Also tried with AsChannelFirstd as suggested in another thread without any luck.  Which steps do I need to do to ensure that there is not such a mismatch in shapes?

Thank you

**Comment by Nic-Ma** [comment]
Hi @carlpe ,

I didn't see the issue in `(torch.Size([1, 4, 80, 80, 80]) torch.Size([1, 1, 80, 80, 80])`, may I know what's the expected shape?

Thanks.

**Comment by carlpe** [comment]
Well, I just assumed that they had to be identical. Because if I run the training and validation steps, I get the following message:

epoch 1/500
1/1, train_loss: 0.9741
epoch 1 average loss: 0.9741

Traceback (most recent call last):
  File "d:/dlk_trainwindows3.py", line 203, in <module>
    epoch_num, m_epoch_loss_values, m_metric_values, m_epoch_times, m_best = train_process(fast=True)
  File "d:/dlk_trainwindows3.py", line 166, in train_process
    dice_metric(y_pred=val_outputs, y=val_labels)
  File "C:\Users\c\anaconda3\envs\monai\lib\site-packages\monai\metrics\metric.py", line 328, in __call__
    ret = super().__call__(y_pred=y_pred, y=y)
  File "C:\Users\c\anaconda3\envs\monai\lib\site-packages\monai\metrics\metric.py", line 68, in __call__
    return self._compute_list(y_pred, y)
  File "C:\Users\c\anaconda3\envs\monai\lib\site-packages\monai\metrics\metric.py", line 90, in _compute_list
    ret = [self._compute_tensor(p.detach().unsqueeze(0), y_.detach().unsqueeze(0)) for p, y_ in zip(y_pred, y)]
  File "C:\Users\c\anaconda3\envs\monai\lib\site-packages\monai\metrics\metric.py", line 90, in <listcomp>
    ret = [self._compute_tensor(p.detach().unsqueeze(0), y_.detach().unsqueeze(0)) for p, y_ in zip(y_pred, y)]
  File "C:\Users\c\anaconda3\envs\monai\lib\site-packages\monai\metrics\meandice.py", line 80, in _compute_tensor
    return compute_meandice(y_pred=y_pred, y=y, include_background=self.include_background)
  File "C:\Users\c\anaconda3\envs\monai\lib\site-packages\monai\metrics\meandice.py", line 123, in compute_meandice
    raise ValueError("y_pred and y should have same shapes.")

ValueError: y_pred and y should have same shapes.

The code for validation is;

`    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    n1=32
    model = UNet(dimensions=3, in_channels=4, out_channels=14, channels=(n1 * 1, n1 * 2, n1 * 4, n1 * 8, n1 * 16),
                 strides=(2, 2, 2, 2)).to(device)

    loss_function = DiceLoss(to_onehot_y=True,softmax=True)
    
    post_pred = AsDiscrete(argmax=True, to_onehot=True, n_classes=14)
    post_label = AsDiscrete(to_onehot=True, n_classes=14)

    optimizer = Novograd(model.parameters(), learning_rate * 10)
    scaler = torch.cuda.amp.GradScaler()
    n_epochs_stop = 50
    epochs_no_improve = 0
    early_stop = False
    best_metric = -1
    best_metric_epoch = -1
    best_metrics_epochs_and_time = [[], [], []]
    epoch_loss_values = list()
    metric_values = list()
    epoch_times = list()
    total_start = time.time()
    for epoch in range(epoch_num):
        epoch_start = time.time()
        print(f"epoch {epoch + 1}/{epoch_num}")
        model.train()
        epoch_loss = 0
        step = 0
        for batch_data in train_loader:
            step += 1
            inputs, labels = batch_data["image"].to(device), batch_data['label'].to(device)
            optimizer.zero_grad()

            with torch.cuda.amp.autocast():
                outputs = model(inputs)
                loss = loss_function(outputs, labels)                
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            epoch_loss += loss.item()
            epoch_len = math.ceil(len(train_ds) / train_loader.batch_size)
            print(f"{step}/{epoch_len}, train_loss: {loss.item():.4f}")
        epoch_loss /= step
        epoch_loss_values.append(epoch_loss)
        print(f"epoch {epoch + 1} average loss: {epoch_loss:.4f}")

        if (epoch + 1) % val_interval == 0 :
            model.eval()
            with torch.no_grad():
                metric_sum = 0.
                metric_count = 0
                for val_data in val_loader:
                    val_inputs, val_labels = val_data["image"].to(device), val_data['label'].to(device)
                    roi_size = (80,80,80)
                    sw_batch_size = 1
                    with torch.cuda.amp.autocast():
                            val_outputs = sliding_window_inference(val_inputs, roi_size, sw_batch_size, model)
                            val_outputs = [post_pred(i) for i in decollate_batch(val_outputs)]
                            val_labels = [post_label(i) for i in decollate_batch(val_labels)]
                            dice_metric(y_pred=val_outputs, y=val_labels)

                metric = dice_metric.aggregate().item()
                dice_metric.reset()
                
                if metric > best_metric:
                    best_metric = metric
                    epochs_no_improve = 0
                    best_metric_epoch = epoch + 1
                    best_metrics_epochs_and_time[0].append(best_metric)
                    best_metrics_epochs_and_time[1].append(best_metric_epoch)
                    best_metrics_epochs_and_time[2].append(time.time() - total_start)
                    torch.save(model.state_dict(), 'dlk.pth')
                else:
                    epochs_no_improve += 1

            print(f"current epoch: {epoch + 1} current mean dice: {metric:.4f}"
                  f" best mean dice: {best_metric:.4f} at epoch: {best_metric_epoch}")

            if epoch > 5 and epochs_no_improve == n_epochs_stop:
                print('Early stopping!' )
                early_stop = True
                break
            else:
                continue

        if early_stop:
            print("Stopped")
            break

        epoch_times.append(time.time() - epoch_start)
    print(f"train completed, best_metric: {best_metric:.4f} at epoch: {best_metric_epoch}"
          f" total time: {(time.time() - total_start):.4f}")
    return epoch_num, epoch_loss_values, metric_values, epoch_times, best_metrics_epochs_and_time

set_determinism(seed=0)
monai_start = time.time()
epoch_num, m_epoch_loss_values, m_metric_values, m_epoch_times, m_best = train_process(fast=True)
m_total_time = time.time() - monai_start
print(f"total training time of {epoch_num} epochs with MONAI: {m_total_time:.4f}")`

It seems that the issue is in validation somewhere and I as I mentioned; I thought it had to do with the shapes in transforms. Just testing with 1 subject for train/val here for reducing running time.

**Comment by ebrahimebrahim** [comment]
You might want to use [`monai.networks.utils.one_hot`](https://docs.monai.io/en/stable/transforms.html?highlight=onehot) to convert your ground truth labels to one-hot format

**Comment by carlpe** [comment]
Hi @ebrahimebrahim , 

Is it not done here;

    post_pred = AsDiscrete(argmax=True, to_onehot=True, n_classes=14)
    post_label = AsDiscrete(to_onehot=True, n_classes=14)

**Comment by carlpe** [comment]
if I print the shapes of val_outputs and val_labels
`                    with torch.cuda.amp.autocast():
                            val_outputs = sliding_window_inference(val_inputs, roi_size, sw_batch_size, model)
                            print(val_outputs.shape)
                            val_outputs = [post_pred(i) for i in decollate_batch(val_outputs)]
                            val_labels = [post_label(i) for i in decollate_batch(val_labels)]
                            print(labels.shape)
                            dice_metric(y_pred=val_outputs, y=val_labels)
`

I get:
torch.Size([1, 14, 80, 80, 80])                                                                                                                                                                                                                 
torch.Size([1, 1, 80, 80, 80])

**Comment by carlpe** [comment]
So, I found something interesting. 
If I change only the validation transform _RandCropByPosNegLabeld_ configuration, it works correctly. 
If I set the channels ['t1','pd','fs','ang'] here instead of the concatenated "image" from Concatitemsd (like I did in train_transforms) - then I get the following validation shapes and it seems to work:



```
def transformations():
    train_transforms = Compose([
        LoadImaged(keys=['t1','pd','fs','ang', 'label']),
        AddChanneld(keys=['t1','pd','fs','ang', 'label']),
        ConcatItemsd(keys=['t1','pd','fs','ang'], name="image"),
        RandCropByPosNegLabeld(keys=["image"], label_key="label", spatial_size=[80,80,80], pos=1, neg=1, num_samples=1),
        RandAdjustContrastd(keys=["image"], prob=0.3),
        RandRotated(keys=["image",'label'], range_x=0.3,range_y=0.4,range_z=0.4, prob=0.4 ),
        RandFlipd(keys=["image",'label'],  prob=0.4, spatial_axis=[0, 1, 2]),
        RandScaleIntensityd(keys=["image"], factors= 0.1, prob=0.3),
        NormalizeIntensityd(keys=["image"], nonzero=True, channel_wise=True),
        #ToTensord(keys=['image', 'label'])])
        EnsureTyped(keys=["image",'label'])])

    val_transforms = Compose([
        LoadImaged(keys=['t1','pd','fs','ang','label']),
        AddChanneld(keys=['t1','pd','fs','ang','label']),
        ConcatItemsd(keys=['t1','pd','fs','ang'], name="image"),
        RandCropByPosNegLabeld(keys=['t1','pd','fs','ang'], label_key="label", spatial_size=[80,80,80], pos=1, neg=1, num_samples=1),
        EnsureTyped(keys=["image",'label'])])
    return train_transforms, val_transforms

```
-------------------------------------------------
epoch 1/500
1/1, train_loss: 0.9798
epoch 1 average loss: 0.9798
torch.Size([1, 14, 400, 400, 400])
14 torch.Size([14, 400, 400, 400])
current epoch: 1 current mean dice: 0.0314 best mean dice: 0.0314 at epoch: 1
epoch 2/500

**Comment by carlpe** [comment]
I see the mistake now. I forgot to add "label"  to keys as such:

`RandCropByPosNegLabeld(keys=["image",'label'], label_key="label", spatial_size=[48,48,48], pos=1, neg=1, num_samples=1),`

Initially, I had only added it to label_key and not keys also.
Nevertheless, problem solved.
