### ISSUE TITLE
question about AddChanneld(MapTransform):

### ISSUE THREAD

**Issue by Peterisfar** [Project-MONAI/MONAI#352]
what is the means about this function?

![image](https://user-images.githubusercontent.com/31852119/81199636-80ddcb00-8ff5-11ea-9777-845b31f9850a.png)

**Comment by Nic-Ma** [comment]
Hi @Peterisfar ,

This transform will add a dim with 1 channel.
Using `None` is equivalent to using `numpy.newaxis`.
It's a numpy method to add dim: https://stackoverflow.com/questions/1408311/numpy-array-slice-using-none

Thanks.
