### ISSUE TITLE
Misleading warning message in decollate=False

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#3539]
**Is your feature request related to a problem? Please describe.**
Issue reported from NVIDIA QA team today:

Got this warning message in the Pathology program:
```MONAI transforms expect `channel-first` data, `decollate=False` may not work here.```
It has started since MONAI v0.6, where the default has changed to decollate=true.
@Nic-Ma isn’t this warning a bit misleading? Obviously, here everything is working and data is channel first but we need to have “decollate=false” for prob map generation.
```py
if postprocessing is not None:
    if not decollate and isinstance(postprocessing, Transform):
        warnings.warn("MONAI transforms expect `channel-first` data, `decollate=False` may not work here.")
```

**Comment by Nic-Ma** [comment]
Hi @wyli @ericspod @rijobro ,

If you guys don't have concerns, I plan to change this warning to `debug` level message.

Thanks in advance.

**Comment by rijobro** [comment]
Certainly shouldn't be a warning. If it's just a note on usage then it should be in a docstring somewhere.
