### ISSUE TITLE
ITKReader - ZIP file reading and Path object handling

### ISSUE THREAD

**Issue by industArk** [Project-MONAI/MONAI#3548]
**Is your feature request related to a problem? Please describe.**
I've been building file loaders for quite a diverse system and I stomp on a problem with monai's file readers.
1. File readers don't support pathlib's Path objects. Haven't checked for others (PILReader works fine) but using ITKReader with Path obj throws a CPP error from ITK lib that may be not clear for one.
`TypeError: in method 'itkImageIOFactory_CreateImageIO', argument 1 of type 'char const *'`
2. I haven't found any possibility to load ZIP files with monai. It would be very convenient to have it, let's say as an `ITKReader.read()` functionality.  The problem is when used at production, it is quite usually an end-user uploads ZIP files with a series of .dcm files.
2.1. An issue to the point above:
`ITKReader.read()` can't be used to read a file that is given `with zipfile.open() as file` from a ZIP as `ITKReader.read()` checks for `Path(name).is_dir()` which can't be done in such case and throws an error:
`ValueError: stat: embedded null character in path`

**Describe the solution you'd like**
1. Just to add handling Path objects.
2. Implemented ZIP file reader functionality in ITKReader
2.1. Fix the problem with handling files only through paths

**Describe alternatives you've considered**
1. For now just parsing Path objects to strings
2. At the mo, such loader has to be implemented manually in the system with zipfile library and ZIP unpacking in a way that each file may be accessed with a path. For now it is easier and faster to use `with zipfile.open() as file: pydicom.dcmread(file)` which works fine.

**Comment by Nic-Ma** [comment]
Hi @industArk ,

Thanks for your interest here and feedback.
Let me try to enhance the `Path` loading of readers soon.

Thanks.

**Comment by wyli** [comment]
which version is this? I think the path obj is supported by https://github.com/Project-MONAI/MONAI/blob/df75199b76a04d991081885888c54f8434eadba2/monai/data/image_reader.py#L207

https://github.com/Project-MONAI/MONAI/blob/df75199b76a04d991081885888c54f8434eadba2/tests/test_load_imaged.py#L54-L56

**Comment by Nic-Ma** [comment]
Hi @industArk ,

Could you please help test again with same ITK version as MONAI requirement: `itk>=5.2`?
I verified locally with `Path` and didn't see any issue.

Thanks.

**Comment by industArk** [comment]
Hi @Nic-Ma,
Many thanks for replying to the issue.

Apologies for losing your time - in my junior nature I haven't noted that I've been still using monai in the 0.7 version. After an update to 0.8, everything works perfectly with pathlib objects.
