### ISSUE TITLE
RandGaussianNoise changes the type of the input to np.float64

### ISSUE THREAD

**Issue by murraycutforth** [Project-MONAI/MONAI#356]
First, thanks for creating a great library!

**Describe the bug**
Applying the RandGaussianNoise tranform to a np.float32 array changes the dtype to np.float64. This causes a crash down the line since pytorch expects np.float32 inputs.

**Expected behavior**
The transformed image's dtype does not change

**Screenshots**
![image](https://user-images.githubusercontent.com/11088372/81280218-1017cc80-9050-11ea-87a6-7494da4288aa.png)

**Environment (please complete the following information):**
 - OS: Centos 7
 - Python version: 3.6
 - MONAI version: 0.1.0

This could be an easy fix, by changing
`return img + self._noise if self._do_transform else img
` 
to
`return img + self._noise.astype(img.dtype) if self._do_transform else img
`.

**Comment by murraycutforth** [comment]
I forgot to add, it's trivial to work around this by adding a CastToType transform in the transformation pipeline.

**Comment by Nic-Ma** [comment]
Hi @murraycutforth ,

Thanks for your bug report.
I will submit a PR to fix this issue soon.
Thanks.
