### ISSUE TITLE
Error while reading a single dicom image using a transform list

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/MONAI#3588]
**Describe the bug**
When I try to read a single dicom image I get the following error

```
Traceback (most recent call last):
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/CAII/app_classification/data_loaders.py", line 64, in <module>
    main()
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/CAII/app_classification/data_loaders.py", line 58, in main
    for _ in train_loader:
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/MONAI/monai/transforms/transform.py", line 83, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/MONAI/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/MONAI/monai/transforms/io/array.py", line 213, in __call__
    raise RuntimeError(
RuntimeError: cannot find a suitable reader for file: /data/Data/MayoClinicData/BreastDensity/DICOM_batch2/A/PN-8264/Screening_Mammography_w_Implants_TomoHD-2019-09-12/Radiation_Dose_Information/1.2.840.113713.17.1538.52353358421150228810446112130563574398.dcm.
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.ITKReader object at 0x7fdd7e670280>, <monai.data.image_reader.NumpyReader object at 0x7fdea8574eb0>, <monai.data.image_reader.PILReader object at 0x7fdea8574cd0>, <monai.data.image_reader.NibabelReader object at 0x7fdea8574e80>, <monai.data.image_reader.ITKReader object at 0x7fdd6f3b3b80>].


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gupta/anaconda3/envs/monai/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/CAII/app_classification/data_loaders.py", line 37, in __getitem__
    return self.transforms(self.image_files[index]), self.image_labels[index]
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/MONAI/monai/transforms/compose.py", line 160, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items)
  File "/data/Vikash/Tools_A100/Tools/BreastDensityMonai/MONAI/monai/transforms/transform.py", line 107, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.array.LoadImage object at 0x7fdd7e61ca60>

```

Point to note here is that I have all the libraries installed. In addition when I try to read the image using just the LoadImage() function as follows 
```
data=LoadImage(image_only=True, reader='itkreader')(filename)
```
It works.

**To Reproduce**
have a file list of single dicom images
```
class MammoDataset(torch.utils.data.Dataset):
	def __init__(self, image_files, image_labels, transforms):
		self.image_files = image_files
		self.image_labels = image_labels 
		self.transforms = transforms
 
	def __len__(self):
		return len(self.image_files)

	def __getitem__(self, index):
		return self.transforms(self.image_files[index]), self.image_labels[index]

train_transforms = Compose([LoadImage(image_only=True, reader="ITKReader"), AddChannel()])
train_ds = MammoDataset(train_images, train_labels, train_transforms)
train_loader = DataLoader(train_ds, batch_size=10, num_workers=1)
	for _ in train_loader:
		img, label = _[0], _[1]




**Expected behavior**
I tested the code with numpy arrays, that is a list of numpy arrays as filenames and they work fine. But when I try to use the dicom images in place of numpy arrays I get the above error

**Additional context**
I built the monai code in develop mode.

**Comment by vikashg** [comment]
so I narrowed down the problem even further. I get the error when I pass the imagelist to the transform function
```
train_transforms = Compose([LoadImage(image_only=True, reader="ITKReader"), AddChannel()])
train_transforms(file_list)
```

**Comment by rijobro** [comment]
Hi, I'm a little lost as to which cases work for you and which don't. I think you're trying two different things:
1. Compare `LoadImage` with `Compose([LoadImage, ...])`
2. Passing a single filename and a list of filenames.

Is this correct? Is there anything else I'm missing? Of the four possibilities above, which ones work and which ones don't?

**Comment by vikashg** [comment]
So, I was testing different scenarios 
List of filenames of numpy arrays work fine with any sort of configuration. 
However when I replace the list of filenames (of numpy arrays) with that of list of filenames of dicom images. I get the above error. 
If I pass a single filename, everything is fine. If I pass a list of filenames to either `LoadImage` or `Compose([LoadImage, ...])` I get the error.

**Comment by vikashg** [comment]
To clarify further 
```
LoadImage()(<list of filenames of numpy arrays>)  # works 
LoadImage()(<list of filenames of dicom images>)  # does not work
```

**Comment by vikashg** [comment]
@rijobro So, after digging a bit deeper into this, I found that the reason I was getting such an error was because raw dicom files do not have the same size. However, the errors were not very clear in pointing that out. If I feed the output of the LoadImage(), to a Resize() filter it works.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

I think we already covered this case in https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_load_image.py#L139
May I know what's the difference in this ticket?

Thanks in advance.

**Comment by rijobro** [comment]
Hi @vikashg @Nic-Ma ,

I still haven't fully managed to grasp which cases worked and didn't, but glad you managed to find a solution. (Perhaps a minimum working example would help next time.)

**Comment by vikashg** [comment]
Hi @rijobro, Sorry I would have sent some code but the thing is its dicom image so I cannot really share. But here is the final gist. the `LoadImage` was working when I was using a list of numpy images because all the numpy images are of same shape. But the same was not working when we used a list of dicom images, I later found that this is because the dicom images as it comes out of the scanner are not necessarily of the same shape and size and thus I was getting this error. 

So, a take home point here is if you are training on a batch of dicom images make sure that they are of the same size or use the transforms to resize the dicom image to the same size. More on discussions #3591 

Thanks a lot everyone.

**Comment by rijobro** [comment]
Thanks for the clarification. Couple of things on which I'm still hazy (although it really doesn't matter if you've found a solution that works for you):

- If images are passed through the `LoadImage` transform separately, then you would only see problems due to differences in image sizes when you collate the data -- i.e., in the when the `DataLoader` creates a batch. 
    - I wouldn't expect the `LoadImage` to raise an exception here.
    - The `Resize` transform would be useful (or `pad_list_data_collate`).
- If the images are different sizes but passed together, then I would expect the ITK backend to throw an error (maybe this is what you were referring to when you said the error message wasn't very helpful). 
    - But the `Resize` transform wouldn't be useful here, as an exception would be raised during the `LoadImage` step, and the `Resize` transform would never be reached.
- If the images are different sizes and stored as numpy arrays, then I would equally expect the reader to throw an error at this point, too.
