### ISSUE TITLE
Remove `"image"`, `"label"`, `"image_meta_dict"` and `"label_meta_dict"` from codebase

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#3603]
**Is your feature request related to a problem? Please describe.**
As a first step towards https://github.com/Project-MONAI/MONAI/issues/2424, we should remove all explicit calls to `"image_meta_dict"` and `"label_meta_dict"`.

**Comment by wyli** [comment]
primary data types are now migrated to metatenor
