### ISSUE TITLE
update string API in notebooks

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#361]
**Is your feature request related to a problem? Please describe.**
Now we already updated all the string related code to use "f string", need to update notebooks.

**Comment by Nic-Ma** [comment]
Hi @hjmjohnson ,

Could you please assign to yourself and take this task later?
Thanks in advance.

**Comment by hjmjohnson** [comment]
I do not have permission to assign myself, or change labels.  I can only submit PR's.

**Comment by arp95** [comment]
Hi @Nic-Ma . I am new to this. Can I contribute to this issue?

**Comment by Nic-Ma** [comment]
> Hi @Nic-Ma . I am new to this. Can I contribute to this issue?

Hi @arp95 ,

Of course, welcome to contribute a PR here!
You can take a look at our examples/notebooks, if you found some strings not in `f"XXX{xxx}XXX"` format, please update them.

Thanks.

**Comment by arp95** [comment]
@Nic-Ma you are referring to the print statements where i need to do the formatting of f-string format?

**Comment by Nic-Ma** [comment]
Hi @arp95 ,

You can check the strings in https://github.com/Project-MONAI/MONAI/tree/master/examples/notebooks
For example, change:
```py
print('image shape: {}, label shape: {}'.format(image.shape, label.shape))
```
to:
```py
print(f"image shape: {image.shape}, label shape: {label.shape}")
```

Thanks.

**Comment by arp95** [comment]
@Nic-Ma Thanks for the explanation. Working on it.
