### ISSUE TITLE
Add `AsContiguous` utility transform

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#3610]
**Is your feature request related to a problem? Please describe.**
Our internal QA team reported a performance issue that:
Running exact same spleen segmentation program on MONAI 0.7+ is **50% slower** than on MONAI 0.5.3, in the same PyTorch 21.10 docker.
Then @yiheng-wang-nv and I spent much time to investigate the issue, finally, I found that in the new code, we can skip the padding if not necessary:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/croppad/array.py#L128
While in the 0.5.3 code, it always pad the array.
And this pad API will potentially convert a **non-contiguous** NumPy array to a **contiguous** array, which will make the following transforms much faster when running with 0.5.3.

I think we faced several times `contiguous` related issues or discussions, would be nice to add an `AsContiguous` transform for both NumPy array and PyTorch Tensor. Then users can explicitly add this transform to whatever place of the transform chain.
It would be obviously useful to convert to contiguous before `CacheDataset` caching.
@ericspod @wyli @rijobro What do you guys think?

**Comment by wyli** [comment]
thanks, in this case what were the slow transforms when the memory is not contiguous?

**Comment by Nic-Ma** [comment]
> thanks, in this case what were the slow transforms when the memory is not contiguous?

Hi @wyli ,

In the spleen training pipeline, when the cached `image`, `label` is not contiguous, the `RandCropByPosNegLabeld` transform will be slower, because the numpy computation is much slower(5x slower) here:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/utils.py#L300
I verified that on local machine, @yiheng-wang-nv will help double confirm on other machines soon.
Then I will try to add the `AsContiguous` transform in our next tag if you guys don't other concerns.

Thanks.

**Comment by wyli** [comment]
I see, thanks for the info, in this case I think we can:
- review array copies such as `ravel` calls to check if they are necessary
- always channel-first contiguous when creating dataset cache

not sure about the new AsContiguous transform, because it's not obvious when/where to use it or not use it...

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your suggestion, that makes sense to me.
Let me try to do these 2 steps first for v0.8.1rc3.
About `AsContiguous`, let's revisit it if necessary later.

Thanks.

**Comment by Nic-Ma** [comment]
@wyli , BTW, if we want to always **channel-first contiguous** when creating dataset cache, we need to explicitly specify the `keys`, so it equals to adding a `AsContiguous` transform as the last non-random transform, right?

Thanks.

**Comment by wyli** [comment]
> 

I think it could be a utility in `monai.transforms.utils_pytorch_numpy_unification` to ensure ascontiguous for `NdarrayOrTensor`

**Comment by Nic-Ma** [comment]
> > 
> 
> I think it could be a utility in `monai.transforms.utils_pytorch_numpy_unification` to ensure ascontiguous for `NdarrayOrTensor`

Hi @wyli ,

Maybe I didn't describe my concern clear enough, I mean maybe we don't need to convert every `NdarrayOrTensor` in the data dictionary to be contiguous in `CacheDataset`, so we may need to specify the `keys`.
Or you think it's OK to automatically convert all the `NdarrayOrTensor` to be contiguous in `CacheDataset`?

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I submitted PR https://github.com/Project-MONAI/MONAI/pull/3614 to optionally support `contiguous` in CacheDataset.
Verified with the training performance of spleen segmentation pipeline.

Thanks.
