### ISSUE TITLE
question about the feature map's order?

### ISSUE THREAD

**Issue by Peterisfar** [Project-MONAI/MONAI#362]
![image](https://user-images.githubusercontent.com/31852119/81319586-7806fb00-90c2-11ea-86f9-6e678d74a26e.png)
![image](https://user-images.githubusercontent.com/31852119/81319617-805f3600-90c2-11ea-955c-07be7abed310.png)

**Comment by Nic-Ma** [comment]
Hi @madil90 ,

Could you please help answer this question as you are enhancing the SlidingWindow?
Thanks.

**Comment by madil90** [comment]
hi @Peterisfar . Our input order is NCHW[D] ([D] is for 3D data). We calculate slice values for spatial dimension (HWD for above case) and extract that portion of input to create input_slices. Since the B=1 always for sliding window, we use 0 for that case.

Please let me know if that answers your question. Thanks.

**Comment by Peterisfar** [comment]
> hi @Peterisfar . Our input order is NCHW[D] ([D] is for 3D data). We calculate slice values for spatial dimension (HWD for above case) and extract that portion of input to create input_slices. Since the N=1 always for sliding window, we use 0 for that case.
> 
> Please let me know if that answers your question. Thanks.


you mean the order is NCHWD? but 3D_conv‘s order is NCDHW。

**Comment by Nic-Ma** [comment]
Hi @Peterisfar ,

Actually, I think it's not a problem as it depends on how you define the dims.
For 1 general 3D object, you can define which dim is H, W or D as you want.
Take CT medical image for example, we define D is `slices`, then the shape is: NCHWD.
Thanks.

**Comment by Peterisfar** [comment]
> Hi @Peterisfar ,
> 
> Actually, I think it's not a problem as it depends on how you define the dims.
> For 1 general 3D object, you can define which dim is H, W or D as you want.
> Take CT medical image for example, we define D is `slices`, then the shape is: NCHWD.
> Thanks.

you are right
