### ISSUE TITLE
Discrete Gaussian kernel (gaussian_1d) should be adapted for discrete filtering

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#363]
**Describe the bug**
The [current Gaussian kernel](https://github.com/Project-MONAI/MONAI/blob/5fcbf5ab16638670d890031825869874ed3d59ef/monai/networks/layers/convutils.py#L40-L59) simply samples the continuous Gaussian function:
```python
def gaussian_1d(sigma, truncated=4.0):
    """
    one dimensional gaussian kernel.

    Args:
        sigma: std of the kernel
        truncated: tail length

    Returns:
        1D numpy array
    """
    if sigma <= 0:
        raise ValueError("sigma must be positive")


    tail = int(sigma * truncated + 0.5)
    sigma2 = sigma * sigma
    x = np.arange(-tail, tail + 1)
    out = np.exp(-0.5 / sigma2 * x ** 2)
    out /= out.sum()
    return out
```

**Expected behavior**
Discrete Gaussian filtering should be compatible with scale-space theory and rely on modified Bessel function for its kernel weights. See e.g.:
https://en.wikipedia.org/wiki/Scale_space_implementation#The_discrete_Gaussian_kernel

**Additional context**
ITK implements such a behaviour in itk::GaussianOperator:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkGaussianOperator.hxx

[Wikipedia](https://commons.wikimedia.org/wiki/File:Discrete_Gaussian_kernel.svg) also provides a basic python implementation (albeit relying on scipy and without rescaling):
```python
from scipy.special import iv
import numpy as np

def discrete_gaussian_kernel(n, t):
    T = np.exp(-t) * iv(n, t)
    return T
```

**Comment by arp95** [comment]
@wyli 
is this issue open? can i work on this?

**Comment by wyli** [comment]
> @wyli
> is this issue open? can i work on this?

yes please go ahead, and once added please by default turn this feature off, otherwise it will affect quite a few other tests
