### ISSUE TITLE
Possibility to revert initial transformations on network outputs

### ISSUE THREAD

**Issue by martaranzini** [Project-MONAI/MONAI#365]
**Is your feature request related to a problem? Please describe.**
It would be useful to have a way to apply to the network output "reverse" transformations of those initially used as pre-processing on the  inputs. For instance, if the inputs are resized or cropped with the relevant Monai transforms, it would be useful to be able to resize or pad the network output back to the original image size. 

**Describe the solution you'd like**
Perhaps a way to keep track of the original image size and the coordinates of the cropping could be sufficient to "revert" those transforms on the output and restore the original image size?

**Additional context**
In my case, I have images with slightly different sizes which are all mapped to (96, 96) at training. At inference, I could not use the Resize Transform at generating the Monai dataset, as I would lose the original size information and would not be able to generate segmentation outputs with the correct size. I overcame the issue by applying the resize operation on the tensors within the evaluation loop instead of using the Monai transform.

**Comment by Nic-Ma** [comment]
Hi @marksgraham ,

Thanks for your suggestion, that's a very good point!
1. In MONAI v0.1, if you use Nifti images, the `nifti_writer` can revert the model output according to the `affine`, `original_affine` and `original_shape` properties in the metadata.
2. But currently, not all the spatial transforms update `affine` after its operation, so we still need some effort to complete the "affine awareness" support for all spatial transforms.

Thanks.

**Comment by martaranzini** [comment]
Hi @Nic-Ma,

Great, thank you very much for considering this and for pointing me towards the properties in the metadata, I'll have a closer look to those.
Many thanks.

**Comment by Nic-Ma** [comment]
You are welcome, you can start from: https://github.com/Project-MONAI/MONAI/blob/master/monai/data/nifti_saver.py#L88
Thanks.

**Comment by rijobro** [comment]
What if all of our transforms had an `inverse` method? The `inverse` method of the `Compose` class would call the `inverse` of each of the composed transforms (in the opposite order to the forward). Any cropping would be padded, so that information would be lost, but that would be it as far as I can see. 

Naturally, it's possible to use non-MONAI transforms, and in this case if an `inverse` method hasn't been implemented, we'll simply throw an error.

I'm happy to work on this if it's a good idea.

**Comment by wyli** [comment]
I'll send out a calendar invitation to discuss @Nic-Ma @rijobro probably need to create a few subtasks out of this ticket so that we could collaborate

**Comment by rijobro** [comment]
Closing this issue as an updated issue with proposed solution is here: https://github.com/Project-MONAI/MONAI/issues/1515, so it would be better to continue any discussions there.
