### ISSUE TITLE
./runtests.sh does not pick up on missing imports

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#3654]
**Describe the bug**
As can be seen here: https://github.com/Project-MONAI/MONAI/runs/4802838071,
the `.runtests.sh` passes (the job named `flake8`), yet the tests fail, due to missing imports: https://github.com/Project-MONAI/MONAI/runs/4802838468?check_suite_focus=true#step:10:11980.

**Expected behavior**
Our `runtests.sh` script should pick up on these.

**Comment by rijobro** [comment]
We use `mypy` to check for missing imports on the main code, but running`mypy tests/test_*.py` reported no errors strangely.

I think I've fixed it by using `pylint` (extra dependency) that also runs on the `tests` folder.  Will submit a PR for review.

**Comment by wyli** [comment]
I see, probably the flake8 config suppressed warnings https://github.com/Project-MONAI/MONAI/blob/f0896593557ce30f47895e7f8b7a1f5294d3e881/setup.cfg#L101

**Comment by rijobro** [comment]
I should have specified that after some debugging, I found that missing imports are detected for files inside of the subfolder `monai`, but not detected in other subfolders, such as `tests`.

**Comment by rijobro** [comment]
Great, good hunting!
