### ISSUE TITLE
Discussion of weighting of generalized Dice loss

### ISSUE THREAD

**Issue by cckao** [Project-MONAI/MONAI#371]
Hi,

I would like to discuss this snippet in `dice.py`.

https://github.com/Project-MONAI/MONAI/blob/ad06dff7f85711048690b2e85c99d51001612708/monai/losses/dice.py#L189-L193

I could understand that you don't want any weight to be `inf`. However, is setting them to the maximum non-infinite value a good idea?

My intuition is Dice loss is designed to emphasize the scarce foregrounds. The weights become infinity when no foreground is present, which means the associated gradients are going to teach the network how to predict backgrounds. And you assign a large weight to it? I think it is weird.

Any idea? Thanks a lot.

**Comment by wyli** [comment]
my understanding is that because the segmentation targets are one-hot maps, `torch.max(b)` will always be in the range of [1/V, 1] (V denotes the number of voxels) when `w_type` is 'simple'.  It seems to be a reasonable replacement for the infs.

alternatively, I think we could set w to `1 / (sum(ground_o) + 1e-6)` to avoid inf,  then w becomes 1e6 when there's no foreground for a particular class. but perhaps w=1e6 puts too much weight in penalising the false positives of that class.

**Comment by cckao** [comment]
In our projects, we just set the weight to zero. That is, something like
```python
w = self.w_func(ground_o.float())
for b in w:
     infs = torch.isinf(b)
     b[infs] = 0.0
     # b[infs] = torch.max(b)
```

We do this because we usually seek to Dice loss to save us from too many false negatives, not false positives. This setting works fine in our projects, but I think we need something more adaptive or smart.

**Comment by wyli** [comment]
thanks for sharing, I think it makes sense especially when the classes are mutually exclusive and the predictions come from softmax, setting it to zero ignores the current class, implicitly emphasizes the other non-empty classes. does the `torch.max(b)` work for your project? to penalise false negatives more, maybe we could increase the weights on the denominators for the non-empty classes.

**Comment by cckao** [comment]
I haven't try `torch.max(b)`, but I guess it won't work better. We use Dice loss because we got too many negative samples, and it's safe to ignore some negative samples. Setting the weight to 0 is not aimed to emphasize other non-empty classes but to save the current class.

**Comment by wyli** [comment]
maybe it's also helpful to set `include_background=False` or consider other components from monai such as "cropforeground' https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/croppad/array.py#L155 and balanced sampling https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/croppad/dictionary.py#L186

**Comment by cckao** [comment]
They are useful features. I will definitely try them. Thanks for the suggestion.
