### ISSUE TITLE
problem about Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), interp_order=(3, 0), mode='nearest'),

### ISSUE THREAD

**Issue by Peterisfar** [Project-MONAI/MONAI#372]
![image](https://user-images.githubusercontent.com/31852119/81501050-b3930680-9308-11ea-92de-c149286514d9.png)

 this code  is used for what? and how to change it to c++？

**Comment by Nic-Ma** [comment]
Hi @Peterisfar ,

This transform adjust medical image spacing based on the `affine` porperty in Nifti header.
Check more details: https://nipy.org/nibabel/coordinate_systems.html
There may be some C++ library to do similar operation as it's a common process.
Thanks.
