### ISSUE TITLE
problem about your different transfomer compose?

### ISSUE THREAD

**Issue by Peterisfar** [Project-MONAI/MONAI#373]
![image](https://user-images.githubusercontent.com/31852119/81501094-ff45b000-9308-11ea-8361-7f941d3a7c8b.png)
![image](https://user-images.githubusercontent.com/31852119/81501144-3caa3d80-9309-11ea-9827-0b8c2d354ae6.png)

why the transfomer compose is different?

**Comment by Nic-Ma** [comment]
Hi @Peterisfar ,

The first one is for MSD spleen dataset, the second one is a demo example for generated dataset, they are totally different tasks.
Thanks.

**Comment by Peterisfar** [comment]
> Hi @Peterisfar ,
> 
> The first one is for MSD spleen dataset, the second one is a demo example for generated dataset, they are totally different tasks.
> Thanks.

if i want to train other dataset , how to use the transfomer compose?

**Comment by Nic-Ma** [comment]
I think you need to analyze your dataset case by case.
Of course, you can refer to the spleen example and adjust the unsuitable transforms.
Thank.
