### ISSUE TITLE
Test time augmentation need to update with new features

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#3732]
**Is your feature request related to a problem? Please describe.**
Hi @rijobro ,

Thanks for providing the TTA module since MONAI 0.5.
@dongyang0122 @holgerroth and I discussed the TTA module for evaluation cases, and found several things should be updated:
1. All the invert transform logic in TTA can be replaced by `Invertd` transform directly now.
And `Invertd` transform provides more features.
2. The post transform example in the doc-string is not `decollate` logic.
3. Better to ensure `determinism` for the random transforms in the example of doc-string.
4. It copy between Numpy and Tensor several times because we didn't support Tensor in transforms and don't have the proper numpy <-> tensor conversion before:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/test_time_augmentation.py#L188
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/test_time_augmentation.py#L190
It will also cause numpy error if the transforms inverse() outputs Tensor.
Should be updated to support `NdarrayOrTensor` directly.
5. Some doc-strings exceed 120 chars.

**Comment by wyli** [comment]
thanks, for item 5 line length we use B950 to warn the line length, which means it's ok to have a <=10% overflow  https://github.com/PyCQA/flake8-bugbear/blame/master/README.rst#L169

**Comment by Nic-Ma** [comment]
> thanks, for item 5 line length we use B950 to warn the line length, which means it's ok to have a <=10% overflow https://github.com/PyCQA/flake8-bugbear/blame/master/README.rst#L169

Thanks for your sharing!
