### ISSUE TITLE
Please use MONAI Discussion tab for questions

### ISSUE THREAD

**Issue by faizan1234567** [Project-MONAI/MONAI#3738]
**Please use MONAI's Discussions tab**
For questions relating to MONAI usage, please do not create an issue.

Instead, use [MONAI's GitHub Discussions tab](https://github.com/Project-MONAI/MONAI/discussions). This can be found next to Issues and Pull Requests along the top of our repository.

I am facing this error while evaluating my model. I don't know what wrong:
applying transform <monai.transforms.post.array.AsDiscrete object at 0x7f49b2f15a90>

**Comment by wyli** [comment]
Hi, it will be very useful if you follow the bug reporting template to provide more information. 

You may want to use this forum to post questions https://github.com/Project-MONAI/MONAI/discussions.
