### ISSUE TITLE
Bug in RandAffined transformations

### ISSUE THREAD

**Issue by murraycutforth** [Project-MONAI/MONAI#375]
**Describe the bug**
When RandAffined is called on a dict containing more than one array (for example an image and a segmentation), and if `self.rand_affine.do_transform` is false, then the transformation returns the wrong result for everything after the first array.

**To Reproduce**
The transforms_demo_2d notebook can be easily repurposed to demonstrate this bug.

**Screenshots**
This is the output from two identical RandAffined transformations.

With prob = 1.0:
![image](https://user-images.githubusercontent.com/11088372/81538294-7b221580-9366-11ea-9556-582629de5e87.png)

With prob = 0.0:
![image](https://user-images.githubusercontent.com/11088372/81538487-b6244900-9366-11ea-938d-7a4eb11db9e2.png)

**Environment (please complete the following information):**
 - OS: Centos 7
 - Python version: 3.7
 - MONAI version [e.g. git commit hash]: 0.1.0+34.gad06dff.dirty

**Additional context**
I did some digging on this in my own fork of the code. The relevant code in RandAffined is:
https://github.com/Project-MONAI/MONAI/blob/ad06dff7f85711048690b2e85c99d51001612708/monai/transforms/spatial/dictionary.py#L313-L330

The bug occurs because 
https://github.com/Project-MONAI/MONAI/blob/ad06dff7f85711048690b2e85c99d51001612708/monai/transforms/spatial/dictionary.py#L321
returns a numpy array, whereas
https://github.com/Project-MONAI/MONAI/blob/ad06dff7f85711048690b2e85c99d51001612708/monai/transforms/spatial/dictionary.py#L319
returns a ``torch.Tensor``. And the ``Resample`` class behaves differently with these different types of input. For ``torch.Tensor`` grids, Resample uses ``clone()``, and operates on a copy, whereas with numpy inputs, ``torch.as_tensor()`` is called which then references the original data. Just changing the constructor from ``torch.as_tensor()`` to ``torch.tensor()`` ensures that torch makes a copy of the grid, which means future calls to ``Resample`` will have the correct grid values.

I'll submit a PR from my fork with the fix?

Note that this bug will also happen with ``Rand2DElasticd`` and ``Rand3DElasticd`` since they follow the same pattern, but this fix to ``Resample`` will also apply to them.

**Comment by Nic-Ma** [comment]
Hi @murraycutforth ,

Thanks very much for your bug report and detailed debug information!
Please submit your fix PR as you said.
Thanks in advance!
