### ISSUE TITLE
installation.md (in docs/source) should be INSTALLATION.md in root

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#3756]
I think it's typical for the `INSTALLATION.md` file to live in the base level, helping users find it. It's linked in our `README.md` but things would still be clearer if it were where users expect it to be. I'm hesitant to move it as I'm not sure if it would break any other hyperlinks. Thoughts?

**Comment by wyli** [comment]
I feel the current root folder has too many files, some are configs for computers and some are documentation...

**Comment by rijobro** [comment]
Sure, closing this for now.
