### ISSUE TITLE
interp_order to be moved to class __init__ method

### ISSUE THREAD

**Issue by pmehta1203** [Project-MONAI/MONAI#377]
https://github.com/Project-MONAI/MONAI/blob/ad06dff7f85711048690b2e85c99d51001612708/monai/transforms/spatial/array.py#L68

The interp_order should be moved to allow separate specification for images and segmentations.

**Comment by Nic-Ma** [comment]
Hi @pmehta1203 ,

Thanks for your interest in project MONAI.
If you use dictionary version `Spacingd` transform to handle images and segmentations together, you can separately set `interp_order` for them in a list:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/spatial/dictionary.py#L74
Please feel free to contact me if you have any other questions.
Thanks.

**Comment by tvercaut** [comment]
For the record, this is related to #328
