### ISSUE TITLE
'None' type of label will be failed with multiple batchsize when using NiftiDataset as DataLoader 

### ISSUE THREAD

**Issue by tangzhe0220** [Project-MONAI/MONAI#378]
**Describe the bug**
When I'm using NiftiDataset class, and set labels as None, it will return fail during iteration. The class function _getitem_ always return "img, target" or "img, target, compatible_meta", target is set from labels. DataLoader could not return with None type by multiple batch size. 

**To Reproduce**
1. Go to 'unet_training_array.py'
2. remove labels, set it as None
3. Run commands 'python unet_training_array.py'

**Expected behavior**
I think it has another output with only img from NiftiDataset.

**Screenshots**
![image](https://user-images.githubusercontent.com/20511588/81559727-886ced80-93c2-11ea-88db-6b8cc5da8b65.png)
![image](https://user-images.githubusercontent.com/20511588/81560053-3a0c1e80-93c3-11ea-8322-4ca07194560d.png)

**Environment (please complete the following information):**
 - Windows10/Centos7
 - Python 3.7
 - MONAI version [#374 ]
 - CUDA/cuDNN version 10.1
 - GPU models and configuration：GTX2080Ti, V100

**Comment by Nic-Ma** [comment]
Hi @tangzhe0220 ,

Thanks for your bug report!
I am adjusting array level `Dataset` recently, the PR https://github.com/Project-MONAI/MONAI/pull/351 should also fix this issue.
Thanks.
