### ISSUE TITLE
syntax warning of literal

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3783]
**Describe the bug**
command:
```
./runtests.sh --clean; python -W error -c "import monai"
```
outcome:
```py
  File "/Users/Documents/MONAI/monai/transforms/spatial/array.py", line 176
    if spatial_size is not -1 and spatial_size is not None:
       ^
SyntaxError: "is not" with a literal. Did you mean "!="?
```

**Comment by wyli** [comment]
patch included in https://github.com/Project-MONAI/MONAI/pull/3773

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your issue report, I also saw this warning yesterday, it's a warning from python 3.8+.
There is also another warning: `"is" with a literal. Did you mean "=="?`
Could you please help also identify and update it in your PR?

Here is the raw warnings I saw yesterday when testing the `save_state` PR:
```
root@apt-sh-ai:/workspace/data/medical/MONAI# python tests/test_save_state.py
"is not" with a literal. Did you mean "!="?
"is" with a literal. Did you mean "=="?
..........
----------------------------------------------------------------------
Ran 10 tests in 0.010s

OK
```

Thanks.
