### ISSUE TITLE
Implementation of average surface distance differs from scientific literature

### ISSUE THREAD

**Issue by SilviaSeidlitz** [Project-MONAI/MONAI#3788]
**Describe the bug**
We discovered that the definition of the average (symmetric) surface distance (ASD) differs between the [deepmind implementation](https://github.com/deepmind/surface-distance/blob/master/surface_distance/metrics.py#L293), the MONAI implementation and common use in literature. Some references of the common definition in literature are listed here:

- [T. Heimann et al., "Comparison and Evaluation of Methods for Liver Segmentation From CT Datasets" in IEEE Transactions on Medical Imaging, vol. 28, no. 8, pp. 1251-1265, Aug. 2009, doi: 10.1109/TMI.2009.2013851](https://doi.org/10.1109/TMI.2009.2013851)
- [Y. Varduhi and I. Voiculescu, "Family of boundary overlap metrics for the evaluation of medical image segmentation" in Journal of Medical Imaging 5.1, 2018](https://dx.doi.org/10.1117%2F1.JMI.5.1.015006)
- [S. Vera et al., "Medial structure generation for registration of anatomical structures" Skeletonization. Academic Press, pp. 313-344, 2017](https://doi.org/10.1016/B978-0-08-101291-8.00013-4)
- [L. Zhou et al., "Deep neural networks for surface segmentation meet conditional random fields." arXiv preprint arXiv:1906.04714, 2019](https://arxiv.org/abs/1906.04714)

Comparing the MONAI definition to the common literature definition, the difference occurs in the case of symmtric ASD computation. In MONAI, both sets of distances (prediction to groundtruth and groundtruth to prediction) are individually averaged before the ASD is computed as average of these two values. In the literature, the distances are instead concatenated and averaged all together:

MONAI (`asd_monai`):
```python
for b, c in np.ndindex(batch_size, n_class):
    (edges_pred, edges_gt) = get_mask_edges(y_pred[b, c], y[b, c])
    surface_distance = get_surface_distance(edges_pred, edges_gt, distance_metric=distance_metric)
    if surface_distance.shape == (0,):
        avg_surface_distance = np.nan
    else:
        avg_surface_distance = surface_distance.mean()  # type: ignore
    if not symmetric:
        asd[b, c] = avg_surface_distance
    else:
        surface_distance_2 = get_surface_distance(edges_gt, edges_pred, distance_metric=distance_metric)
        if surface_distance_2.shape == (0,):
            avg_surface_distance_2 = np.nan
        else:
            avg_surface_distance_2 = surface_distance_2.mean()  # type: ignore
        asd[b, c] = np.mean((avg_surface_distance, avg_surface_distance_2))
```

Literature (`asd_own`):
```python
for b, c in np.ndindex(batch_size, n_class):
    (edges_pred, edges_gt) = get_mask_edges(y_pred[b, c], y[b, c])
    distances_pred_gt = get_surface_distance(edges_pred, edges_gt, distance_metric=distance_metric)
    if symmetric:
        distances_gt_pred = get_surface_distance(edges_gt, edges_pred, distance_metric=distance_metric)
        distances = np.concatenate([distances_pred_gt, distances_gt_pred])
    else:
        distances = distances_pred_gt
    
    asd[b, c] = np.nan if distances.shape == (0,) else np.mean(distances)
```

The biggest difference between these two definitions arises in the case of a large difference in surface size between groundtruth  and prediction, in which case the MONAI implementation leads to the distances computed for the object of smaller surface to be overweighted compared to the distances computed for the object of larger surface.

Here is an example of different ASD values obtained for the showcase of a small and a large object: 

```python
gt = torch.ones(10, 10, dtype=torch.int64)
pred = torch.zeros(10, 10, dtype=torch.int64)
pred[4:6, 4:6] = 1
print(f'{gt = }')
print(f'{pred = }')

surface_distances = compute_surface_distances(gt.type(torch.bool).numpy(), pred.type(torch.bool).numpy(), (1, 1))
gt_to_pred, pred_to_gt = compute_average_surface_distance(surface_distances)
print(f'deep mind: {np.mean([gt_to_pred, pred_to_gt]) = }')

gt = F.one_hot(gt, num_classes=2).permute(2, 0, 1).unsqueeze(0)
pred = F.one_hot(pred, num_classes=2).permute(2, 0, 1).unsqueeze(0)
print(f'{asd_own(pred, gt, symmetric=False).item() = }')
print(f'{asd_monai(pred, gt, symmetric=False).item() = }')
print(f'{asd_own(gt, pred, symmetric=False).item() = }')
print(f'{asd_monai(gt, pred, symmetric=False).item() = }')

print(f'{asd_own(pred, gt, symmetric=True).item() = }')
print(f'{asd_monai(pred, gt, symmetric=True).item() = }')
print(f'{asd_own(gt, pred, symmetric=True).item() = }')
print(f'{asd_monai(gt, pred, symmetric=True).item() = }')
```

```
gt = tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
pred = tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
deep mind: np.mean([gt_to_pred, pred_to_gt]) = 4.224683633075019
asd_own(pred, gt, symmetric=False).item() = 4.0
asd_monai(pred, gt, symmetric=False).item() = 4.0
asd_own(gt, pred, symmetric=False).item() = 4.5385930456363175
asd_monai(gt, pred, symmetric=False).item() = 4.5385930456363175
asd_own(pred, gt, symmetric=True).item() = 4.484733741072686
asd_monai(pred, gt, symmetric=True).item() = 4.269296522818159
asd_own(gt, pred, symmetric=True).item() = 4.484733741072686
asd_monai(gt, pred, symmetric=True).item() = 4.269296522818159
```

**Comment by wyli** [comment]
thanks for the detailed bug report, your implementation is also consistent with http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/34_Segmentation_Evaluation.html would you like to create a pull request to release your implementation in MONAI?
