### ISSUE TITLE
Resampling / Spacing enhancements

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#3844]
https://docs.monai.io/en/stable/transforms.html?highlight=spacing#spacing

Current transform to resample to the desired resolution always resamples  even if the data is already at (almost) the desired resolution.  Since the  augmentation transforms (zoom, rotation, etc) will resample the data again, it would be advantageous to skip the Spacing transform if the current image resolution is already "close" to the desired resolution.  

E.g if the desired resolution is 0.8x0.8x2.5, and the image resolution is 0.7x0.7x.2,5 then skip "Spacing".  Perhaps we can have a parameter to enable it.   This will save time during training, and won't produce interpolation artifacts when it's not necessary.

**Comment by Nic-Ma** [comment]
Hi @myron ,

Thanks for your feedback.
Actually we already have the tolerance to compare affine when resampling:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/utils.py#L93
I can create a PR to make this value as an arg for resampling transforms, but I am not very sure whether it's necessary.
Maybe current `1e-3` is already good enough?
@ericspod @wyli @holgerroth @dongyang0122 Could you please help share some opinions before I change something?

Thanks.

**Comment by wyli** [comment]
I think we could have a meta transform to achieve 'SkipIf' or 'SkipUnless' to make the transform conditional. Or have another way to archive this. We should think about it. If it's just a performance issue maybe we should focus on the lazy resampling.

(anyway the tolerance was not designed for this purpose. Please don't revise that API for this feature request.)

**Comment by myron** [comment]
I'd recommend to  add an option for a  range of resolutions e.g min_bound=[0.7 0.7 2], max_bound=[0.8 0.8 3.5], in which case the resampling will be skipped if the resolution is already in that range

**Comment by myron** [comment]
I think the idea of skipping resampling is to save on computations (and unnecessary interpolations).  I've looked at the proposed change (min_pixdim max_pixdim ), and it simply keeps the original resolution, but still does the unnecessary resampling (if I understand the change with correctly)

**Comment by wyli** [comment]
the skipping is done at the spatial resampler https://github.com/Project-MONAI/MONAI/blob/ba670c9ba78f9f4d76eb12b4d33f245b5774d462/monai/transforms/spatial/array.py#L265-L267

**Comment by myron** [comment]
I see.  But such a logic seems a bit convoluted. 
1) it hides the skipping part (harder to read)
2) the images will still be converted to float (even if no resampling happened) in _post_process
3) it will push this transform (on the stack of transforms), and when doing Inverse - it will have to be processed even if not resampling happened. I assume the inverse resampler will do nothing too (since the affine transforms are close).  But depending how it's implemented it may still get slower, I remember the inverter does copy (clone) of the memory, so this may trigger this copy during inversion. 

I'm ok to keep it, if you think it's okay

**Comment by wyli** [comment]
Sure, we still need to transform some metadata and data type for consistency when skipping the resampling. otherwise we run into batch collating issues, for example recently this ticket: https://github.com/Project-MONAI/MONAI/issues/5127
