### ISSUE TITLE
GridPatchDataset not working on ArrayDataset input

### ISSUE THREAD

**Issue by amirjaber** [Project-MONAI/MONAI#3849]
I am trying to do a patch_based training using GridPatchDataset and copying everything from the tutorial example. I can see the Dataloader creating the patches with right size for both image and labels but when trying to train with ignite.engine.create_supervised_trainer, it throughs an error:
TypeError: conv3d(): argument 'input' (position 1) must be Tensor, not list
The reason is that GridPatchDataset generates a list for each patch with shape: torch.Size([batch_size, 1, 64, 64, 16]) torch.Size([batch_size, 4, 2]).
```py
imtrans = Compose([LoadImage(image_only=True),ScaleIntensity(), AddChannel(), ToTensor()])
segtrans = Compose([LoadImage(image_only=True), AddChannel(), ToTensor()])
val_imtrans = Compose([LoadImage(image_only=True),ScaleIntensity(), AddChannel(), ToTensor()])
val_segtrans = Compose([LoadImage(image_only=True), AddChannel(), ToTensor()])

ds = ArrayDataset(images, imtrans, segs, segtrans)
val = ArrayDataset(valimages, val_imtrans, val_segs, val_segtrans)
patch_iter = PatchIter(patch_size=spatial_size, start_pos=(0,0,0))
def img_seg_iter(x):
    return (zip(patch_iter(x[0]), patch_iter(x[1])),)
ds = GridPatchDataset(ds,img_seg_iter,with_coordinates=False)
val = GridPatchDataset(val,img_seg_iter,with_coordinates=False) 

train_loader = torch.utils.data.DataLoader(
    ds, batch_size=10, num_workers=2, pin_memory=torch.cuda.is_available()
)
val_loader = torch.utils.data.DataLoader(
    val, batch_size=10, num_workers=2, pin_memory=torch.cuda.is_available()
)
im, seg = first(train_loader)
print(im[0].shape, im[1].shape)

trainer = ignite.engine.create_supervised_trainer(
    net, opt, loss, device, False
)
trainer.run(train_loader, epochs)

TypeError: conv3d(): argument 'input' (position 1) must be Tensor, not list
```

**Comment by Nic-Ma** [comment]
Hi @amirjaber ,

Please try to `monai.data.DataLoader` or set the `collate_fn` of PyTorch DataLoader to:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/utils.py#L331

Thanks.

**Comment by amirjaber** [comment]
Thanks @Nic-Ma. I studied collate_fn and wrote a specific collate_fn that parses im, seg after GrdiPatchDataset:
def list_collate(batch):
    from torch.utils.data._utils.collate import default_collate
    data = [(k[0][0],k[1][0]) for k in batch]
    return default_collate(data)
Now I have these shapes in the output of torch.utils.data.DataLoader which starts training.  torch.Size([batch, 1, 64, 64, 16]) torch.Size([batch, 1, 64, 64, 16])
But the issue is GridPatchDataset did not browse through image and cover multiple patches for whole image. I noticed that only one patch per input image is created. How can I fix that?

**Comment by Nic-Ma** [comment]
Hi @amirjaber ,

I think `GridPatchDataset` generates a patch a time:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/grid_dataset.py#L141
If you want to get multiple patches a time, you can use the regular `Dataset` with `RandCropByPosNegLabeld`, refer to:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_training_dict.py#L69

Thanks.

**Comment by amirjaber** [comment]
Thanks @Nic-Ma So basically MONAI has no patch based technique to sweep all image and labels and train on those patches? It seems like a very necessary feature that should be implemented. Pls let me know if I am missing sth here.

**Comment by Nic-Ma** [comment]
Hi @amirjaber ,

`GridPatchDataset` is iterable dataset, have you tried the `PatchDataset`?
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/grid_dataset.py#L150

Thanks.

**Comment by amirjaber** [comment]
@Nic-Ma I tried GridPatchDataset, the documentation shows applying it only in one image. I want to iterate on two images ( image, segmentations). When I use the 

def img_seg_iter(x):
return (zip(patch_iter(x[0]), patch_iter(x[1])),)
ds = GridPatchDataset(ds,img_seg_iter,with_coordinates=False)

It gives only one patch for each image and does not iterate over the whole image. Is there any example from PatchDataset or GridPatchDataset that applied on both image and segmentations and used for training?

**Comment by Nic-Ma** [comment]
Hi @amirjaber ,

I see your point, I would suggest to make your data in `dict` format and use `dict` based transforms of MONAI, refer to:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_training_dict.py#L64

Thanks.

**Comment by wyli** [comment]
It looks like an issue with the iterator, this one seems to work:

```py
imtrans = Compose([LoadImage(image_only=True),
                   ScaleIntensity(), AddChannel(), EnsureType()])
segtrans = Compose([LoadImage(image_only=True), AddChannel(), EnsureType()])

ds = ArrayDataset(images, imtrans, segs, segtrans)
patch_iter = PatchIter(patch_size=(64, 64, 64), start_pos=(0, 0, 0))


def img_seg_iter(x):
    for img, seg in zip(patch_iter(x[0]), patch_iter(x[1])):
        print(img[1], seg[1]) #print coordinates
        yield ((img[0], seg[0]), )

ds = GridPatchDataset(ds, img_seg_iter, with_coordinates=False)

loader = torch.utils.data.DataLoader(
    ds, batch_size=2, num_workers=0, pin_memory=torch.cuda.is_available()
)
im, seg = first(loader)
print("image shapes:", im.shape, seg.shape)
# for img, seg in loader:
#     print(img.shape, seg.shape)

```

I'll revise the tutorial.
