### ISSUE TITLE
LoadImaged for 2D/3D grayscale tiff files

### ISSUE THREAD

**Issue by perlmutter** [Project-MONAI/MONAI#3858]
Using `LoadImaged` on a 2D grayscale tiff file with `WSIReader` and `backend=cucim` returns an array with 3 "color" channels, which are all identical.

For example,
```
data_dict = {"image": "test.tif"}
x = np.random.randint(low=0,high=256,size=(128,128),dtype=np.uint8)
io.imsave(data_dict["image"],x) 

print("cucim: shape = " + str(cucim.CuImage(data_dict["image"]).shape))
transform = LoadImaged(keys=["image"], reader=WSIReader, backend='cuCIM')
print("LoadImaged-cucim: shape = " + str(transform(data_dict)["image"].shape))
```
returns,
```
cucim: shape = [128, 128, 1]
LoadImaged-cucim: shape = (3, 128, 128)
```

When using `backend=tifffile` the files are misread entirely
```
print("tifffule: shape = " + str(tifffile.imread(data_dict["image"]).shape))
transform = LoadImaged(keys=["image"], reader=WSIReader, backend='tifffile')
print("LoadImaged-tifffile: shape = " + str(transform(data_dict)["image"].shape))
```
returns,
```
tifffule: shape = (128, 128)
LoadImaged-tifffile: shape = (3, 128)
```

Is this the expected behavior? Is there a better way to read 2D grayscale tiff files into monai? How about 3D grayscale tiffs?

Thanks,
David

**Comment by vikashg** [comment]
Hi David, 
Can you please tell me which version of Monai are you using? I have a bunch of .svs file and I am trying to use the ```LoadImaged``` with backend ```cuCIM```

**Comment by perlmutter** [comment]
moani version 0.8.0

I got the same error messages before specifying `reader=WSIReader` and `backend=`... following this documentation: https://github.com/Project-MONAI/MONAI/issues/3161

Perhaps WSIReader is not appropriate for grayscale tiffs, but as far as I can tell it's the only reader that opens tiffs at all. Would be great to have a default `tifffilereader` option for `LoadReader` that can read 2D/3D/grayscale/color tiffs

**Comment by wyli** [comment]
this is partly a cucim issue:  

```py
import numpy as np                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
import cucim                                                                                                                                                                                                                                     
from skimage import io                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                 
data_dict = {"image": "test.tif"}                                                                                                                                                                                                                
x = np.random.randint(low=0, high=256, size=(128, 128), dtype=np.uint8)                                                                                                                                                                          
io.imsave(data_dict["image"], x)                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
region = cucim.CuImage("test.tif").read_region(location=(0, 0), size=(128, 128), level=0)                                                                                                                                                        
print(region.shape) 
```

log:
```
[Plugin: cucim.kit.cuslide] Loading the dynamic library from: /opt/conda/lib/python3.8/site-packages/cucim/clara/cucim.kit.cuslide@22.02.00.so
Initializing plugin: cucim.kit.cuslide (interfaces: [cucim::io::IImageFormat v0.1]) (impl: cucim.kit.cuslide)
[Plugin: cucim.kit.cumed] Loading the dynamic library from: /opt/conda/lib/python3.8/site-packages/cucim/clara/cucim.kit.cumed@22.02.00.so
Initializing plugin: cucim.kit.cumed (interfaces: [cucim::io::IImageFormat v0.1]) (impl: cucim.kit.cumed)
[128, 128, 4]
[Plugin: cucim.kit.cuslide] Unloaded.
[Plugin: cucim.kit.cumed] Unloaded.
```
cc @gigony

**Comment by wyli** [comment]
this doesnt work with the input without a channel dim, 
https://github.com/Project-MONAI/MONAI/blob/d6327a765cf23dafd680b2a4b472edf9639e1087/monai/data/image_reader.py#L922-L924
could you please help @drbeh, thanks in advance!

**Comment by drbeh** [comment]
Hi @perlmutter,

The intended use of`WSIReader` and its backends (`cuCIM` and `OpenSlide`) are not for loading any arbitrary array in a TIFF file but for Whole Slide Images in pathology.
First of all, as @wyli mentioned, you need to have a channel dimension. Otherwise, the backends may interpret have generate different outputs:
- `cuCIM` will add the new dimension by repeating values (@gigony could you please confirm this?), 
- `Tifffile` will not add any channel dimension so `WSIReader` consider the last dim as the channel dim and will truncate it to 3 (to have RGB image),
- `OpenSlide` will fail to load the image.

Second of all, how do you have grayscale images? I have never encountered a grayscale WSI image, is it a toy example?

**Comment by perlmutter** [comment]
> Hi @perlmutter,
> 
> The intended use of`WSIReader` and its backends (`cuCIM` and `OpenSlide`) are not for loading any arbitrary array in a TIFF file but for Whole Slide Images in pathology (which are 2D colored images). First of all, as @wyli mentioned, you need to have a channel dimension. Otherwise, the backends may generate different outputs:
> 
> * `cuCIM` will add the new dimension by repeating values (@gigony could you please confirm this?),
> * `Tifffile` will not add any channel dimension so `WSIReader` consider the last dim as the channel dim and will truncate it to 3 (to have RGB image),
> * `OpenSlide` will fail to load the image.
> 
> Second of all, how do you have grayscale images? I have never encountered a grayscale WSI image, could you please explain the use case so we can see if we should support it here of elsewhere?

@drbeh , you're right, my application is not whole slide imaging. I work with microCT data, at a user-facility for scientific applications: https://als.lbl.gov/beamlines/8-3-2/. We don't use medical imaging formats like dicom. Instead we store raw data in hdf5, but typically give users reconstructions in tiffs (either 3D tiffs or individual 2D slices). Would very much appreciate general tiff support in monai.

**Comment by drbeh** [comment]
> @drbeh , you're right, my application is not whole slide imaging. I work with microCT data, at a user-facility for scientific applications: https://als.lbl.gov/beamlines/8-3-2/. We don't use medical imaging formats like dicom. Instead we store raw data in hdf5, but typically give users reconstructions in tiffs (either 3D tiffs or individual 2D slices). Would very much appreciate general tiff support in monai.

@perlmutter, I believe we already support functionality via ITK. You should be able to use `ITKReader` for your use case. For your example above you can change it to:
```python
import numpy as np                                                                                                                                                                                                                           
from skimage import io
from monai.transforms import LoadImaged
from monai.data.image_reader import ITKReader       

data_dict = {"image": "test.tif"}
x = np.random.randint(low=0,high=256,size=(128,128),dtype=np.uint8)
io.imsave(data_dict["image"],x) 

transformD = LoadImaged(keys=["image"], reader=ITKReader)
image = transformD(data_dict)["image"]
print(f"ITKReader: image shape = {image.shape}")
```

```
ITKReader: image shape = (128, 128)
```

**Comment by drbeh** [comment]
> perhaps in the wsireader it's useful to raise a runtime error when the input doesn't have the required colour channels?

@wyli, that depends on the backends and each of them handles this differently, so we don't know it before loading the image. It should be addressed in `cuCIM`, so I made an issue on their repo.

**Comment by drbeh** [comment]
I'm closing this in favor of the follow up issues.

**Comment by drbeh** [comment]
I'm closing this in favor of the follow up issues.
