### ISSUE TITLE
`RandKSpaceSpikeNoise` got an unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by mibaumgartner** [Project-MONAI/MONAI#3867]
**Describe the bug**
`RandKSpaceSpikeNoise` does not work with NumPy array if `intensity_range` is not set manually.

In case a NumPy array is provided, the linked part will call `np.mean(.., dim=...)` but NumPy does not support dim arguments (should be `axis`). The implementation works fine for `torch.Tensors`.

https://github.com/Project-MONAI/MONAI/blob/d6327a765cf23dafd680b2a4b472edf9639e1087/monai/transforms/intensity/array.py#L1816-L1818

**To Reproduce**
Call transform on NumPy array with default values (specifically `intensity_range =None`).

**Expected behavior**
No crash.

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @mibaumgartner ,

Thanks for your feedback!
@yiheng-wang-nv , could you please help confirm and fix it?

Thanks in advance.
