### ISSUE TITLE
class MultiModal - updating in the for loop

### ISSUE THREAD

**Issue by razi2021** [Project-MONAI/MONAI#3880]
**Describe the bug**
It looks like that in the 'class MultiModal(BertPreTrainedModel):' inside the 'forward' function in lines 240, 242, and 244, the variables are not getting updated. As the input argument, they receive the very initial input and not the output of the previous layer which is supposed to be the reason for using a 'for loop'.
Is that a bug, or is there something that I'm missing out on?

**Comment by wyli** [comment]
@ahatamiz this looks like a bug, could you help?
https://github.com/Project-MONAI/MONAI/blob/82ec2fef6e0636a0290a454b82a262d6871a84d5/monai/networks/nets/transchex.py#L237-L245
