### ISSUE TITLE
additional info when the shapes don't match

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3883]
**Is your feature request related to a problem? Please describe.**
shape checks such as
https://github.com/Project-MONAI/MONAI/blob/82ec2fef6e0636a0290a454b82a262d6871a84d5/monai/metrics/meandice.py#L122-L123
should provide more details about the current shapes for better usability.

```py
raise ValueError(f"y_pred and y should have same shapes, got {y_pred.shape} and {y.shape}.")
```

would be great to review all the error messages... cc @Project-MONAI/core-reviewers

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Would you like to help double-check and enhance the error messages in our metrics?

Thanks.
