### ISSUE TITLE
Is there any example by using ignite and monai with multiple gpus?

### ISSUE THREAD

**Issue by foxet** [Project-MONAI/MONAI#389]
Is there any example by using ignite and monai with multiple gpus?

**Comment by Nic-Ma** [comment]
Hi @foxet ,

You can refer to this simple example:
https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/multi_gpu_test.ipynb
Thanks.

**Comment by skrishnanv** [comment]
Hi, 
Unfortunately the link above is broken.
i think it is here now
https://github.com/Project-MONAI/tutorials/blob/master/acceleration/multi_gpu_test.ipynb
