### ISSUE TITLE
MVP example for model inference and saving predicted results.

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#39]
Sliding window inference
Writing segmentation as a nifti image (Nifti image writer)
Writing classification as a json file (json writer)

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Would you like to add this part to your existing 3D segmentation example? Or create a new example?
I suggest to unify most logics of the evaluation and validation processes.
Thanks.

**Comment by pdogra89** [comment]
Eric, Wenqi and Nic would align on Design and what can be leveraged from NiftyNet mechanism.
