### ISSUE TITLE
The first convolutional layer in ResNet is hardcoded to be anisotropic

### ISSUE THREAD

**Issue by Can-Zhao** [Project-MONAI/MONAI#3918]
**Is your feature request related to a problem? Please describe.**
In monai/networks/nets/resnet.py, line 210, the get_conv1() produces the first convolutional layer in ResNet.
The convolutional kernel it produces is anisotropic, with 
kernel_size=(conv1_t_size, 7, 7),
stride=(conv1_t_stride, 2, 2),
padding=(conv1_t_size // 2, 3, 3)

This might be a little adhoc. 

**Describe the solution you'd like**
It would be great if the default convolutional kernel is isotropic or let the users decide these parameters in all three dimensions.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help take a look this ResNet structure related question?

Thanks in advance.
