### ISSUE TITLE
add keep_largest_connected_component transform

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#393]
**Is your feature request related to a problem? Please describe.**
"keep_largest_connected_component" is very useful a transform in medical tasks.
Need to add it to MONAI.

**Comment by tvercaut** [comment]
Note that if possible, it would be great to avoid a dependence on a non-pytorch based library. In the short term skimage might be fine but this would have to be changed later on.

Kornia is looking into similar questions: https://github.com/kornia/kornia/issues/428 https://github.com/kornia/kornia/issues/293
