### ISSUE TITLE
develop COVID-19 segmentation & classification examples

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#396]
**Is your feature request related to a problem? Please describe.**
We can try to develop COVID-19 segmentation and classification examples based on the public datasets

**Comment by Nic-Ma** [comment]
Hi @pdogra89 ,

This task is blocked by dataset now, we didn't find a suitable COVID-19 public dataset.
Could you please help connect research team or others to help provide an existing PyTorch program training on some public COVID-19?
Then we can convert it to a MONAI example.
Thanks.

**Comment by JunMa11** [comment]
Hi @Nic-Ma ,

[Here](https://github.com/JunMa11/COVID-19-CT-Seg-Benchmark) is a COVID-19 CT dataset with 20 cases.

It would be highly appreciated if you could create a MONAI example using this data.
Best,
Jun

**Comment by Nic-Ma** [comment]
Hi @JunMa11 ,

Thanks for your sharing!
We are evaluating many datasets with research team, I will raise this dataset in the next internal discussion soon.

Thanks.

**Comment by JunMa11** [comment]
Hi @Nic-Ma ,

Thanks so much for your consideration.

Please feel free to let me know if you have any questions about this dataset.

Best,
Jun

**Comment by Nic-Ma** [comment]
Hi @pdogra89 ,

Could you please also add this dataset when research team evaluates suitable public dataset?
Thanks.

**Comment by tvercaut** [comment]
@taigw and his team just published a paper with 120 annotated CT scans: https://github.com/HiLab-git/COPLE-Net

This could be a nice dataset for this demo.

Note that @taigw's code is already in pytorch so could be a good starting point for a MONAI implementation.

**Comment by wyli** [comment]
Hi @tvercaut, I had a quick chat with him yesterday as well :)
I'll work on this
