### ISSUE TITLE
ImportError: cannot import name 'instantiate' from 'monai.utils

### ISSUE THREAD

**Issue by Tai-Hsien** [Project-MONAI/MONAI#3973]
Hello,

I just followed the installation guide and installed MONAI today with the latest stable version via pypl.

However, after that, I typed `python -c 'import monai; monai.config.print_config()'` to validate the installation, and it always shows the error as `ImportError: cannot import name 'instantiate' from 'monai.utils'`.

Could someone advise how to fix this problem? No idea how to solve it since it fails at the first step. Many thanks!

**Comment by Nic-Ma** [comment]
Hi @Tai-Hsien ,

May I know what the "latest stable" version you mean here? Weekly build or 0.8.1?

Thanks.

**Comment by Tai-Hsien** [comment]
> Hi @Tai-Hsien ,
> 
> May I know what the "latest stable" version you mean here? Weekly build or 0.8.1?
> 
> Thanks.

It's 0.8.1.

**Comment by Tai-Hsien** [comment]
Hello,
I think I found the problem. I actually installed both monai and monai-weekly. Once I removed both of them and reinstall. Everything works!
