### ISSUE TITLE
SaveImaged add feature for dictionary-based output postfix

### ISSUE THREAD

**Issue by scarpma** [Project-MONAI/MONAI#3984]
I think it would be useful if the function `monai.transforms.saveImaged` could accept `output_postfix` parameter in the form of a dictionary.

The problem is that when it loads muiltiple data based on the `keys` parameter, then all inputs are saved with the same output filename.

Having something like
```python
output_postfix={'image':'_imgTrans', 'label':'_labTrans']
```
to save images and labels with different postfixes.

**Comment by scarpma** [comment]
Ok, maybe I'm not using this class correctly. The problem is that I have the same file name for both image and label (but in different directory). When I tried to save both, the output filenames were the same (maybe because the input folders were discarded) and so everything was overwritten by the last saving operation.

I would like to save both image and label in two different directories specified by me (through a dictionary, for example). Is this possible ?

I don't understand very well how the filename definition works. Sorry for the dumb question

**Comment by Nic-Ma** [comment]
Hi @scarpma ,

Please take a look this `data_root_dir` arg, it's designed for your case:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/io/dictionary.py#L194

Thanks.

**Comment by scarpma** [comment]
Ahhh ok. Now it makes sense ! Thank you.

I have another doubt. What about the `meta_keys` arg ?

To give a specific example, I have a dictionary with
```python
{
    'image' : something,
    'image_meta_dict' : something,
    'label' : something,
    'label_meta_dict' : something,
}
```

what should I put in  the `meta_keys` arg to fetch the correct meta data dictionaries ? It seems that it does not accept a dictionary, so I'm going with the list `['image_meta_dict', 'label_meta_dict']`, but I'm not sure this is the right thing to do.

Thanks again !

**Comment by Nic-Ma** [comment]
You can set `meta_keys` to `['image_meta_dict', 'label_meta_dict']` or set `meta_key_postfix`.
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/io/dictionary.py#L224

Thanks.

**Comment by scarpma** [comment]
Ok, but isn't it strange to specify `meta_keys` through a list while referring to a dictionary-based data ? How is the order checked ?

**Comment by Nic-Ma** [comment]
> Ok, but isn't it strange to specify `meta_keys` through a list while referring to a dictionary-based data ? How is the order checked ?

Hi @scarpma , the `keys` arg is also a list, the data is a dict.

Thanks.

**Comment by scarpma** [comment]
Ah ok, you are right !!! But maybe it would make sense to accept dictionary-like meta data keys. Just an idea.

Thanks for the clarification. For me we can close the issue.
