### ISSUE TITLE
Dictionary version of Monai Transpose

### ISSUE THREAD

**Issue by Alberto1404** [Project-MONAI/MONAI#3987]
Hello all. In the task I am working on, I am incorrectly reading the volume images with CacheDataset, because the shape they have is HxWxD. When creating the loader, I want shape (B,C,D,H,W), and I am getting (B,C,H,W,D). I saw the transformation transpose, that should be enough passing the correct indexes as arguments. Nevertheless, I am dealing with a dictionary in my loaders, with keys ['image'] and ['label']. Would it be possible to have a "Transposed" in the docs?
Thank you for your time

**Comment by ebrahimebrahim** [comment]
To clarify, `monai.transforms.TransposeD` exists but it just isn't in the docs. Should definitely be added to the docs.

**Comment by wyli** [comment]
thanks, this is now revised on the dev branch (https://docs.monai.io/en/latest/transforms.html#transposed) it'll be included on the default doc page in the next milestone release.
