### ISSUE TITLE
MVP example for model validation every N training steps

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#40]
-Depends on task 2
- Minimal evaluation metrics interface (or using ignite.metrics?)
-Event handler for model validation and early stopping

**Comment by Nic-Ma** [comment]
Hi @madil90 ,

I already submitted PR #66 to support mean_dice metric, could you please help add the validator handler and early-stop for training example based on ignite?
Thanks in advance.

**Comment by madil90** [comment]
Sure. I can add these over the weekend.

**Comment by Nic-Ma** [comment]
Hi @madil90 ,

Thanks, I also update the PR to support both multi-labels and multi-classes outputs.
