### ISSUE TITLE
MONAI Pathology Overall Structure

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4005]
Here I have prepared the overall structure of MONAI Pathology when blending into the core MONAI. Please feel free to put you comments and I will update it accordingly. 

![Overall Structure](https://user-images.githubusercontent.com/3968947/160178816-5e5fbd71-9079-4fa2-a843-4133528cc2a4.jpg)

I will create separate issues for each of the components that requires changes or needs to be implemented. We will address these changes in a new branch for pathology and will merge when ready.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Thanks for your detailed summary, looks good.
Looking forward to the following PRs that refactor them into the core code.

Thanks.

**Comment by JohnMasoner** [comment]
Hi @drbeh ,

I'm sorry that i comment the closed the issus.
I‘m watching #4006, the issus brought this to my attention.
I want to know what's app to plot the Overall Structure Picture.

Thanks.

**Comment by drbeh** [comment]
Hi @JohnMasoner, 
I have used Miro for those diagrams: https://miro.com
Regarding #4006, can you let me know what is your use case? 
Thanks

**Comment by JohnMasoner** [comment]
Hi @drbeh ,
Actually, I want to trying to contribution the #4006. 
I am learning something about #4006 ,maybe i can do it.
Thanks

**Comment by drbeh** [comment]
Hi @JohnMasoner,

Absolutely, that's the whole point of an open-source library. #4006 requires some architecting and defining how the component should interface with each other but would be great if you can make any contribution. Please discuss your design on #4006 or start a draft pull request as soon as you have something to discuss (don't wait until all the done).

We also have implemented this stain normalizer in cucim, so feel free to take a look at it too. 
https://github.com/rapidsai/cucim/blob/branch-22.08/python/cucim/src/cucim/core/operations/color/stain_normalizer.py

Thanks
