### ISSUE TITLE
conda test errors: test_matshow3d

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4011]
**Describe the bug**
```
======================================================================
FAIL: test_samples (tests.test_matshow3d.TestMatshow3d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/MONAI/MONAI/tests/test_matshow3d.py", line 70, in test_samples
    np.testing.assert_allclose(comp["rms"], 30.786983, atol=1e-3, rtol=1e-3)
  File "/usr/local/miniconda/envs/monai/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/miniconda/envs/monai/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 4.74991119
Max relative difference: 0.1542831
 x: array(26.037072)
 y: array(30.786983)

======================================================================
FAIL: test_plot (tests.test_threadcontainer.TestThreadContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/MONAI/MONAI/tests/test_threadcontainer.py", line 107, in test_plot
    self.assertIsNone(comp, comp)  # None indicates test passed
AssertionError: 'Error: Image files did not match.\n  RMS Value: 28.09905059190909\n  Expected:  \n    /Users/runner/work/MONAI/MONAI/tests/testing_data/threadcontainer_plot_test.png\n  Actual:    \n    /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpav42fn_w/threadcontainer_plot_test.png\n  Difference:\n    /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpav42fn_w/threadcontainer_plot_test-failed-diff.png\n  Tolerance: \n    0.05' is not None : Error: Image files did not match.
  RMS Value: 28.09905059190909
  Expected:  
    /Users/runner/work/MONAI/MONAI/tests/testing_data/threadcontainer_plot_test.png
  Actual:    
    /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpav42fn_w/threadcontainer_plot_test.png
  Difference:
    /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpav42fn_w/threadcontainer_plot_test-failed-diff.png
  Tolerance: 
    0.05

----------------------------------------------------------------------
Ran 5904 tests in 1950.197s

FAILED (failures=2, skipped=355)
```

**Comment by yiheng-wang-nv** [comment]
Hi @wyli and @Nic-Ma , I tried to reproduce these errors but did not achieve the same error. What I did is:
```
conda env create --file environment-dev.yml
conda activate monai
./runtests.sh --build --unittests
```
These two errors are all coming from `matplotlib.testing.compare.compare_images`, and the images saved in `tests/testing_data` will be compared with the created images from the unittests. I checked the [source code](https://matplotlib.org/3.1.0/_modules/matplotlib/testing/compare.html) of `compare_images`, and the method it used is very straightforward, thus here I wish to submit a PR first to implement this method in MONAI directly, thus we can at least get more useful information from the errors. What do you think?

**Comment by wyli** [comment]
It's possibly a version issue, the corresponding environment in a non-conda setup is here (example) https://github.com/Project-MONAI/MONAI/runs/5702401097?check_suite_focus=true

To debug, you can push to your fork with a temp branch and with the config modification to trigger the test like this https://github.com/Project-MONAI/MONAI/commit/238d883a92d11bea021ebd605837c9cdbfc78d2f

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , it looks like same errors are not happened. For example: [in the latest conda workflow](https://github.com/Project-MONAI/MONAI/actions/runs/2068674346), and[ in my forked temp branch](https://github.com/yiheng-wang-nv/MONAI/runs/5768679573?check_suite_focus=true).
Whereas, we may need to fix another windows bug, which happens all the time:
```
  File "C:\Miniconda\envs\monai\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
monai.utils.module.OptionalImportError: from torchvision.transforms import Pad (cannot import name 'PILLOW_VERSION' from 'PIL' (C:\Miniconda\envs\monai\lib\site-packages\PIL\__init__.py)).
```

**Comment by wyli** [comment]
thanks, perhaps we add a version constraint here, torchvision >= 0.7.0 (looks like it's required by pytorch >= 1.6)

**Comment by yiheng-wang-nv** [comment]
This error is from the torchvision side, and it has been fixed after `torchvision >=0.5.0` (see  [here](https://github.com/pytorch/vision/releases/tag/v0.5.0)). But in our workflow, the following command installs `torchvision-0.2.2`.
```
conda install pytorch torchvision torchaudio cpuonly -c pytorch -c conda-forge
```

**Comment by wyli** [comment]
we change this line to https://github.com/Project-MONAI/MONAI/blob/3947d4e214db99ae31b961d8b13d5d603b180686/environment-dev.yml#L33
to `- torchvision>=0.7.0` to address the issue, what do you think?

**Comment by yiheng-wang-nv** [comment]
> we change this line
> 
> https://github.com/Project-MONAI/MONAI/blob/3947d4e214db99ae31b961d8b13d5d603b180686/environment-dev.yml#L33
> 
> 
> to `- torchvision>=0.7.0` to address the issue, what do you think?
> perhaps that's a good reminder that these places should be updated as well: https://github.com/Project-MONAI/MONAI/blob/dev/setup.cfg#L38 https://github.com/Project-MONAI/MONAI/blob/dev/requirements-dev.txt#L29

Sure, also for https://github.com/Project-MONAI/MONAI/blob/3947d4e214db99ae31b961d8b13d5d603b180686/.github/workflows/conda.yml#L50, which is the place that lead to the issue. It's a bit weird that in the step of ` Windows only install`, with this command, `pytorch-1.9.1` and `torchvision-0.2.2` are installed at the same time. Let me a try first.

![Screen Shot 2022-03-31 at 7 19 56 PM](https://user-images.githubusercontent.com/68361391/161043719-d286eab5-8131-4f0e-874f-83ef3ca9b6a7.png)

**Comment by wyli** [comment]
appears to be addressed by https://github.com/Project-MONAI/MONAI/pull/4044
