### ISSUE TITLE
Use consistent naming for interpolation order selections

### ISSUE THREAD

**Issue by hjmjohnson** [Project-MONAI/MONAI#403]
parameter and instance variable names used `interp_order` and
`order` in various parts of the code.  Prefere to use a consistent
naming of `interp_order` for MONAI naming consistency.

**Describe the solution you'd like**
Use consistent naming for interpolation order
    
Created an enumeration to provide explicit names to the valid
interp_order values.

**Describe alternatives you've considered**
Leave inconsistent naming for backward compatibility.

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/407
