### ISSUE TITLE
Discussion categories needs attention! 

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4035]
GitHub Discussions supports only up to 10 categories, and in in MONAI Discussions, we have already exhausted them, so there is no room for a new working group category. On the other hand, maybe we have not taken the right use of categories, these categories are supposed to represent the type of question/discussion and not the related subjects (like different WGs). Subjects can be assigned using labels where there is no limit on the number.
My suggestion is to make it simpler for the users, and remove all `#WG: ...` categories while keeping only the four main categories:
💬 General
💡 Ideas
🙏 Q&A
🙌 Show and tell

**Comment by drbeh** [comment]
@wyli @Nic-Ma if you agree with the above, I can clean it up.

**Comment by wyli** [comment]
Sure thanks @drbeh. Perhaps show and tell could be removed, it's not currently used...

**Comment by drbeh** [comment]
@wyli, I realized that I can edit the categories but I cannot delete them!
