### ISSUE TITLE
Component Specifications for HoVerNet

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4040]
Create specifications for all the necessary components for training and evaluation of Simultaneous Segmentation and Classification of Nuclei in Multi-Tissue Histology Images using HoVerNet model.
- paper: https://arxiv.org/abs/1812.06499
- code: 
  - https://github.com/vqdang/hover_net
  - https://github.com/TissueImageAnalytics/tiatoolbox/tree/develop/tiatoolbox/models/architecture

The specifications of each components can simply be defined as an [issue](https://github.com/Project-MONAI/MONAI/issues) in MONAI, where an explanation of need or a reference code, or detailed specification of the component is given.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Thanks for raising the ticket.
May I know the context or initial requirement why we want to add this `HoVerNet`? I suspect it comes from some discussion in the Pathology working group?
CC @wyli 

Thanks in advance.

**Comment by drbeh** [comment]
Hi @Nic-Ma, yes it comes from pathology working group. @JHancox has more information on that.
