### ISSUE TITLE
Support string config starts with bundle syntax or expression contains "@"

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#4057]
**Is your feature request related to a problem? Please describe.**
Thanks for @gigony 's feedback, in some corner cases, maybe a string in the bundle config contains our predefined syntax.
For example:
```
"username": "%%%%cool"
```
Or:
```
"money": "$$$$$"
```
Or:
```
"comment": "#####good"
```
And even in an expression, may contain unexpected "@" syntax:
```
"outout_dir": "$@root_dir + '~/nic-ma@nvidia/temp' + 'model.pt'"
```

So it would be nice to have a way to support the syntax in the string config.

**Comment by holgerroth** [comment]
We also have this issue with nvflare where the path to downloaded model files contain the email address of the admin, e.g. `/t1_workspace/admin@nvflare.com/transfer/7def72a7-a224-403c-9969-2eb9da02db7b/workspace/app_server/FL_global_model.pt`

This causes a reference ID error with bundle.

```
packages/monai/bundle/reference_resolver.py", line 231, in update_refs_pattern
    raise KeyError(msg)
KeyError: "can not find expected ID 'nvflare' in the references."
```

**Comment by Nic-Ma** [comment]
Hi @holgerroth ,

Thanks for your report, please note that: Something like: `{"test": "admin@nvflare.com"}` can work in the bundle, We just treat it as a reference in the 2 cases: (1) a string starts with "@", (2) a string starts with "$" and contains "@" in it.

Thanks.

**Comment by Nic-Ma** [comment]
The logic in the dev is not correct, because it always try to check reference even not started with "@" or "$":
https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/reference_resolver.py#L225
Should only do it when: `if value_is_expr or value == item`.

Thanks.
