### ISSUE TITLE
Redesign of WSIReader

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4071]
Right now `WSIReader` is based on `ImageReader` class with `read` and `get_data` methods. However, reading whole slide images regardless of the library to use have its own additional complexities that are not captured in the base class. 
Also, currently, we have implemented different backends `cuCIM`, `OpenSlide`, and TiffFile` through if statements!

My suggestion would be to have a `WSIReader` base class that implements those additional functionalities such as evaluating the level based on ppm/resolution, validating the pyramidal levels, etc. along with abstract methods that each of the libraries has to implement. In this way, we can implement each backend in different classes like `CuCIMReader` (for cuCIM) inherited from `WSIReader`.

This not only makes the code cleaner and more readable but also decouples MONAI integration of third-party WSI reader libraries and makes the future contribution easier and safer.

The overall structure would look like this: (will update #4005)
![wsi](https://user-images.githubusercontent.com/3968947/161667951-1debad7b-6856-4157-8a45-0cd88fedbfd4.jpg)

**Comment by drbeh** [comment]
@wyli @Nic-Ma @ericspod @rijobro 
Do you have any comment here? does it make sense to you?

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Thanks for the refactoring idea.
I think it overall looks good to me, maybe we can simplify it to a flattened file structure:
`monai/data/wsireader.py` and `monai/data/wsidataset.py`
What do you think?
CC @wyli @ericspod 

Thanks.

**Comment by ericspod** [comment]
I think this is a good change though `WSIReader` should still inherit from `ImageReader` so that the API remains compatible. `TiffReader` isn't just reading TIFF images but specifically those storing slide data so this class should have a more specific name to not appear to be a general purpose TIFF image reader, `PILReader` is meant for that instead.

**Comment by drbeh** [comment]
> Hi @drbeh ,
> 
> Thanks for the refactoring idea. I think it overall looks good to me, maybe we can simplify it to a flattened file structure: `monai/data/wsireader.py` and `monai/data/wsidataset.py` What do you think? CC @wyli @ericspod
> 
> Thanks.

Hi @Nic-Ma, thanks for your feedback. I agree with this naming too.
I just wanted to follow the previous suggestions with @wyli (https://github.com/Project-MONAI/MONAI/issues/3868#issuecomment-1075020965)  and @ericspod (https://github.com/Project-MONAI/MONAI/issues/3868#issuecomment-1075199718).
Either way is fine with me, the benefit that I can see for having a `wsi` directory is to declutter `data` directory, and add all WSI related stuff, e.g. `datasets.py`, `reader.py`, ` writer.py` (maybe in the future), under the same name space (`monai.data.wsi`).

What do you think? @wyli @ericspod @Nic-Ma

**Comment by drbeh** [comment]
> I think this is a good change though `WSIReader` should still inherit from `ImageReader` so that the API remains compatible. `TiffFileReader` isn't just reading TIFF images but specifically those storing slide data so this class should have a more specific name to not appear to be a general purpose TIFF image reader, `PILReader` is meant for that instead.

You are right! Here we are implementing a specific use of tifffile library, so we should be more clear. I'll think of a better name for that.

**Comment by wyli** [comment]
It looks good, given that `monai.data` doesn't currently have subfolders, I suspect `monai/data/wsireader.py` and `monai/data/wsidataset.py` are more consistent with the rest of the module.

**Comment by drbeh** [comment]
Sure, that's fine with me. Follow the same format as `image_*.py`, I'll make `wsi_*.py`.
