### ISSUE TITLE
Bundle Relative Paths

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#4093]
**Is your feature request related to a problem? Please describe.**
Paths specified in MONAI Bundles should be defined as relative to the bundle's directory so that they aren't dependent on specific file placements on any user system. 

**Describe the solution you'd like**
The model weights for example should be referred to as `./models/model.pt` or via a known bundle directory variable/function such as `$bundle_path("./models/model.pt")`. This would simplify and generise referring to parts of the bundle in config files.

**Describe alternatives you've considered**
The example bundle in the tutorials repo uses absolute paths which wouldn't work on my machine without modification. Ideally we should be able to provide examples which users can use without modification and will do something useful with known commands straight from the repo.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Thanks for your suggestion.
I think we can define a "BUNDLE_ROOT" field in the config, then all the other internal paths use path like "@BUNDLE_ROOT + '/models/model.pt'". Other users only need to edit the "BUNDLE_ROOT" for these own environment.
What do you think?

Thanks.
