### ISSUE TITLE
MVP example for tensorboard logging

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#41]
-Tensorboard visualisation of 3d images

**Comment by Nic-Ma** [comment]
Hi @nvkevlu ,

As you are expert on 3D visualization and auto-documentation, could you please help with this task?
The minimal requirements will be:
1. Wenqi will extract pure python example from existing notebook training example, for better development and review process.
2. You can add ignite Event-Handlers to above example with functions:
    (1) log **training loss** to tensorboard, show the training curve.
    (2) log **validation metrics** to tensorboard, show the metrics curves(validation is still in development).
    (3) log 1-5 **validation results** to tensorboard, reference on how to show 3D image in tensorboard:
  https://github.com/NifTK/NiftyNet/blob/ddf7767faffa2ac856d669a4c882468915f50f4a/niftynet/io/misc_io.py#L736-L753

Please feel free to contact if you have any questions.
And of course, welcome discussion within the team.
Thanks in advance.

**Comment by pdogra89** [comment]
Kevin is working on this - create a pull request - Nic to follow up
