### ISSUE TITLE
extensions of the surface-based metric

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4103]
**Is your feature request related to a problem? Please describe.**
Follow up of https://github.com/Project-MONAI/MONAI/pull/4050,
this is a feature request to extend the surface-based metric module for 3D, with the support of more detailed quantizations when computing local surface lengths/areas (such as the computation proposed in https://github.com/deepmind/surface-distance).

https://github.com/Project-MONAI/MONAI/pull/4050#discussion_r842152042
> the way 3D surfaces & surface distances are handled in deep mind is different from MONAI: Instead of defining surfaces at surface voxel boundaries, surface points are located on a grid that is shifted by half of the grid spacing along each axis (cf. Fig. 10 in their [paper](https://arxiv.org/abs/1809.04430)):
> 
> ![grafik](https://user-images.githubusercontent.com/4249077/161634269-8a2e1161-2da0-4f05-8dcd-08bff241e6f6.png)
> 
> I think it should be discussed more broadly whether to keep the surface computation currently used in MONAI, or to switch to the deep mind computation, or to establish a switch such that the user can decide on the computation. This choice should be made consistently for all boundary-overlap metrics.

cc @SilviaSeidlitz

**Comment by jakubMitura14** [comment]
Hausdorff distance and Average surface distance in Monai are already implemented using the deep mind library you are referring to, what exactly is not present that you need?

You can also lok into some fast approximation that I am now developing in 

https://github.com/Project-MONAI/MONAI/pull/4078

this can give potentially the performant approximations of the quantities you are requesting

**Comment by wyli** [comment]
>  what exactly is not present that you need?
> 

please see https://github.com/Project-MONAI/MONAI/pull/4050#discussion_r846827002

**Comment by jakubMitura14** [comment]
ok thanks !

**Comment by hreso110100** [comment]
> 

Hi can Average surface distance be considered same as Average Hausdorff distance ? Because I cant see Average Hausdorff distance implementation in monai. Thanks for reply

**Comment by jakubMitura14** [comment]
Hello I can not say wheather they are mathemathically the same as my mathemathical skills are not sufficient - I suppose not exactly, but I ran some statistical experiments suggesting that they are closely correlated - correlation around 0.9 and very low p values.

**Comment by wyli** [comment]
no they are different distances @hreso110100

**Comment by hreso110100** [comment]
And is there some plan to add also this metric ?

**Comment by jakubMitura14** [comment]
Here is working Morphological algorithm (pytorch extension - not MONAI)
https://github.com/jakubMitura14/Hausdorff_morphological

Hovewer this is fast morphological approximation - quite accurate and having very good performance, still not exact, also it can be considered rather research than production software


To be honest recently I got a new job and was unable to spend time debugging MONAI pull request here is the pull request to MONAI - it is not working, would you like to contribute in debugging :)
https://github.com/Project-MONAI/MONAI/pull/4078
