### ISSUE TITLE
Extend AMP selection choices

### ISSUE THREAD

**Issue by danieltudosiu** [Project-MONAI/MONAI#4116]
**Is your feature request related to a problem? Please describe.**
AMP creates instability during training

**Describe the solution you'd like**
Extend the AMP dtype selection as HuggingFace suggests [here](https://huggingface.co/docs/transformers/v4.16.2/en/performance#bf16).

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

Thanks very much for your feature request.
Seems it's necessary to support the new A100 AMP features in the engines `with torch.cuda.amp.autocast()`.
Let me think about it and get back soon.

Thanks.
