### ISSUE TITLE
Can you provide some image registration examples？

### ISSUE THREAD

**Issue by shuanggou** [Project-MONAI/MONAI#414]
Excellent work, I think it is very helpful for the development of medical imaging field.
I'm now engaged in medical image registration, can you provide some registration examples？
Thank you.

**Comment by Nic-Ma** [comment]
Hi @shuanggou ,

Thanks for your interest here, glad to see it's helpful to you.
@wyli @tvercaut could you please help share some information about registration examples as you are working on related topics?

Thanks.

**Comment by wyli** [comment]
thanks let's track the relevant with this ticket https://github.com/Project-MONAI/MONAI/issues/250, I'm closing this one
