### ISSUE TITLE
Segmentation example on multiple labels

### ISSUE THREAD

**Issue by radiplab** [Project-MONAI/MONAI#415]
**Is your feature request related to a problem? Please describe.**
The spleen segmentation example is incredibly helpful. Several of my projects involve multiple labels - e.g. the right and left lateral ventricle. 

**Describe the solution you'd like**
I'd greatly appreciate an example or guidance on how to train a model with multiple labels.

**Additional context**
I'm pretty new to this, and suspect it's a pretty easy modification to the example.

**Comment by Nic-Ma** [comment]
Hi @radiplab ,

Thanks for your interest here!
Actually, I think it's not hard to change to a multi-labels dataset based on the spleen example:
1. Change the network definition to expected output channels: `out_channels=xxx`.
2. The label of multi-labels should be already in One-Hot format, and need to add `Sigmoid` to model output before loss computation. So change the loss definition to:
`DiceLoss(do_sigmoid=True)`.
3. A similar change to the `compute_meandice`, to_onehot = False and add sigmoid.

Maybe I still miss something that specific to your dataset, you can have a try first.

Thanks.

**Comment by radiplab** [comment]
Thanks a lot for getting back to me. I made the changes you suggested and received an error stating "Ground truth one-hot has differing shape (torch.Size([1, 1, 108, 129, 108])) from source (torch.Size([1, 2, 108, 129, 108]))" This occurred within the training code at: 

value = compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False,                                                 to_onehot_y=False, add_sigmoid=True)

I have a vague understanding I need to account for the extra label somewhere, but am unsure how to do that. I'm basically working from the example at https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb. I'm trying to train from label files with 2 labels: right ventricle = 1, left ventricle = 2. So my changes basically looked like this:

# Changed model to have 3 out_channels. Did not change in_channels
model = monai.networks.nets.UNet(dimensions=3, in_channels=1, out_channels=3, channels=(16, 32, 64, 128, 256), strides=(2, 2, 2, 2), num_res_units=2, norm=Norm.BATCH).to(device)

# Changed loss_function to sigmoid
loss_function = monai.losses.DiceLoss(do_sigmoid=True)

# Changed compute_meandice to onehot=False and add_sigmoid=True
value = compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False, to_onehot_y=False, add_sigmoid=True)

Really appreciate your help.

**Comment by Nic-Ma** [comment]
Hi @radiplab ,

I think the problem is that label dims don't match model output dims.
If you only have 2 labels, why you set `out_channels=3` instead of 2?
If you don't want to remove the first channel when computing mean_dice, you need to set:
`include_background=True`.

Thanks.

**Comment by radiplab** [comment]
Thanks again. Setting out_channels=2 made it run without error but something remains incorrect. In the spleen example, out_channels is also 2 and the background is not included, and there is only 1 label? It finished after ~ 30 epochs with a dice ~ 1.2. Somehow my Dice is calculating incorrectly. Also, my output looked like this:
![results](https://user-images.githubusercontent.com/58953167/82932455-0f3ad200-9f4e-11ea-9b0b-93a9f2c42089.png)

So at this point, I made the changes listed above and out_channels=2, with code otherwise identical to https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb. 

While debugging, my val_outputs after sliding_window_inference has a min of -1.4 and a max of 19. I guess I would expect it to range from 0-2 just like my labels. That's what I then pass into my compute_meandice as the first argument. 

Anyway, I apologize if this is convoluted. I'm sure I'm just not accounting for the extra labels correctly through dimensions of a tensor or passed arguments, but am new enough to this it's difficult to debug. Again, appreciate your help.

**Comment by Nic-Ma** [comment]
Hi @radiplab ,

1. The spleen example output is 2 labels, first label is background, second label is spleen. We only compute mean_dice on the second label.
2. For your case, I think you have 2 labels, both are foreground, right? So you should compute mean_dice on them all(include_background=True).
3. About the model output range, if you are doing `multi-labels` task, please set `add_sigmoid=True`, if you are doing `multi-classes` task, please set `mutually_exclusive=True`.
4. If your label is not in One-Hot format, please set `to_onehot_y =True`.

Thanks.

**Comment by radiplab** [comment]
Ok I'm making progress. I can train a model with 2 labels (right ventricle, left ventricle) with just the 2 changes below (my labels are not in onehot format initially - it's 0 (background), 1, or 2):

model = monai.networks.nets.UNet(dimensions=3, in_channels=1, **out_channels=3**, channels=(16, 32, 64, 128, 256), strides=(2, 2, 2, 2), num_res_units=2, norm=Norm.BATCH).to(device)

loss_function = monai.losses.DiceLoss(to_onehot_y=True, **do_sigmoid=True**)

value = compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False, to_onehot_y=True, mutually_exclusive=True) # **unchanged from spleen example** 

I also changed this line after compute_meandice to accurately capture the number of metrics (not apparent if there's only 1 label):
metric_count += len(value) # This doesn't capture the number of metrics, it always returns 1
To:
metric_count += value.shape[1] # The metrics are in a [1,2] dimensional array

I am still having 1 issue. My labels (right and left lateral ventricle) are extremely similar, almost mirror images of each other. However, the 2nd label always trails the 1st label in Dice score, and with progressive epochs they diverge more, with the 2nd label getting worse and the 1st label getting better. Early on, the Dice for 1st label is ~ 0.8, and the Dice for the 2nd label is ~ 0.6. After about 100 epochs, the Dice for the first label is ~ 0.9, and the Dice for the 2nd label is ~ 0.4. I'm not sure if I'm calculating the Dice score incorrectly, or if this is real. If real, not sure why it would be happening. Is there any chance my random crop transform somehow favors the first label consistently? This is what I'm using, same as the spleen example:

RandCropByPosNegLabeld(keys=['image', 'label'], label_key='label', size=(96, 96, 96), pos=1, neg=1, num_samples=4, image_key='image', image_threshold=0)

Thanks again for your advice and patience.

**Comment by radiplab** [comment]
Or maybe my input labels need to be onehot format? Might explain why it trains fine for the first label but worse for the second - the cropping is always looking for a "1" as foreground? If so, is there a method for converting labels to onehot within the train and val transforms? Thanks...

**Comment by Nic-Ma** [comment]
Hi @radiplab ,

We do `RandCropByPosNegLabeld ` to select foreground in below logic:
```py
label_flat = np.any(label, axis=0).ravel()  # in case label has multiple dimensions
fg_indices = np.nonzero(label_flat)[0]
```
It can support both One-Hot or not.

What are the transforms you used in this task? For your case, I think you should not use `Flip` or `Rotate` related transforms.

Thanks.

**Comment by radiplab** [comment]
Appreciate your guidance on this. Still seeing the Dice score slowly degrade for the 2nd label down to ~ 0.2, and the first label stays at ~ 0.9. I'm just unsure if it's something I'm doing wrong, or if there's an underlying bug causing the inequality in dice scores between essentially symmetric labels. Just for completeness, this covers pretty much everything I'm doing - thank you again:

I'm using [this dataset](https://drive.google.com/file/d/15uqY_6J-gTdiP4MC_tYLr5rtH9X1KmIv/view?usp=sharing) - obtained from the Human Connectome Project, with just the ventricle labels isolated.

**These transforms:**
```
    train_transforms = Compose([
        LoadNiftid(keys=['image', 'label']),
        AddChanneld(keys=['image', 'label']),
        Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 1.5), interp_order=(3, 0), mode='nearest'),
        Orientationd(keys=['image', 'label'], axcodes='RAS'),
        ScaleIntensityRanged(keys=['image'], a_min=0, a_max=1000, b_min=0.0, b_max=1.0, clip=True),
        CropForegroundd(keys=['image', 'label'], source_key='image'),
        RandCropByPosNegLabeld(keys=['image', 'label'], label_key='label', size=(96, 96, 96), pos=1, neg=1, num_samples=4, image_key='image', image_threshold=0),
        ToTensord(keys=['image', 'label'])
    ])
    val_transforms = Compose([
        LoadNiftid(keys=['image', 'label']),
        AddChanneld(keys=['image', 'label']),
        Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 1.5), interp_order=(3, 0), mode='nearest'),
        Orientationd(keys=['image', 'label'], axcodes='RAS'),
        ScaleIntensityRanged(keys=['image'], a_min=0, a_max=1000, b_min=0.0, b_max=1.0, clip=True),
        CropForegroundd(keys=['image', 'label'], source_key='image'),
        ToTensord(keys=['image', 'label'])
    ])
```

**These datasets and loaders:**
```
    train_ds = monai.data.CacheDataset(data=train_files, transform=train_transforms, cache_rate=1.0)
    train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=4, collate_fn=list_data_collate)

    val_ds = monai.data.CacheDataset(data=val_files, transform=val_transforms, cache_rate=1.0)
    val_loader = DataLoader(val_ds, batch_size=1, num_workers=4)  
```

**These model, loss, and optimizers:**
```
    model = monai.networks.nets.UNet(dimensions=3, in_channels=1, out_channels=3, channels=(16, 32, 64, 128, 256),
                                    strides=(2, 2, 2, 2), num_res_units=2, norm=Norm.BATCH).to(device)
    loss_function = monai.losses.DiceLoss(to_onehot_y=True, do_sigmoid=True)
    optimizer = torch.optim.Adam(model.parameters(), 1e-4)
```

**And training this way - I added code to display the mean dice for each label as well as the overall mean dice:**
```
    val_interval = 2
    best_metric = -1
    best_metric_epoch = -1
    epoch_loss_values = list()
    metric_values = list()
    for epoch in range(600):
        print('-' * 10)
        print('Epoch {}/{}'.format(epoch + 1, 600))
        model.train()
        epoch_loss = 0
        step = 0
        for batch_data in train_loader:
            step += 1
            inputs, labels = batch_data['image'].to(device), batch_data['label'].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_function(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            #print('{}/{}, train_loss: {:.4f}'.format(step, len(train_ds) // train_loader.batch_size, loss.item()))
        epoch_loss /= step
        epoch_loss_values.append(epoch_loss)
        print(' Epoch {} average loss: {:.4f}'.format(epoch + 1, epoch_loss))

        if (epoch + 1) % val_interval == 0:
            model.eval()
            with torch.no_grad():
                metric_sum = 0.
                metric_count = 0
                all_metric_sum = None
                i = 1
                for val_data in val_loader:
                    val_inputs, val_labels = val_data['image'].to(device), val_data['label'].to(device)
                    sw_batch_size = 4
                    val_outputs = sliding_window_inference(val_inputs, (96, 96, 96), sw_batch_size, model)
                    value = compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False,
                                            to_onehot_y=True, mutually_exclusive=True)
                    
                    if all_metric_sum is None:
                        all_metric_sum = value.cpu().numpy()
                    else:
                        all_metric_sum = np.append(all_metric_sum, value.cpu().numpy(), axis=0)
                        all_metric_sum = np.sum(all_metric_sum, axis=0)
                        all_metric_sum = np.expand_dims(all_metric_sum, axis=0)

                    #**metric_count += len(value)
                    metric_count += value.shape[1]
                    metric_sum += value.sum().item()
                    i = i + 1

                all_metric = all_metric_sum / i
                metric = metric_sum / metric_count
                metric_values.append(metric)
                if metric > best_metric:
                    best_metric = metric
                    best_metric_epoch = epoch + 1
                    torch.save(model.state_dict(), model_output_path)
                    print('saved new best metric model')
                print(' Current epoch {} current mean dice: {:.4f} best mean dice: {:.4f} at epoch {}'.format(
                    epoch + 1, metric, best_metric, best_metric_epoch))
                print(' Epoch ' + str(epoch + 1) + ' individual dice averages: ', end='')
                for i in range(all_metric.shape[1]):
                    print(str(all_metric[0][i]) + ' ', end='')
                print('')
```

**Comment by radiplab** [comment]
More progress, but an odd problem. 

Again, the [right and left ventricle labels](https://drive.google.com/file/d/15uqY_6J-gTdiP4MC_tYLr5rtH9X1KmIv/view?usp=sharing) only train correctly on label '1', not label '2'. The dice reaches ~ 0.9 for the 1st label, about 0.6 for the 2nd, then steadily declines for the 2nd (I let it run for up to 400 epochs). I tried swapping the ventricles (right ventricle 1-->2, left ventricle 2-->1) and that made no difference. So the problem isn't intrinsic to 1 ventricle. I wasn't doing rotations, but I tried adding rotations about every axis and that did not improve it. I also output the center slice from the labels as .png files to verify the labels were correct for every file, and they are.

I then tried 2 totally different structures - the right putamen and left thalamus. That worked great! Both quickly reached a dice of ~ 0.9. Maybe a problem with the ventricles being so similar and symmetric? Then I tried just both putamina - also similar, symmetric structures. That worked fine as well.

So I think my code is correct, but I'm stumped as to why the lateral ventricles are different, training fine for label '1' and poorly for label '2'. If anyone has ideas I'd love to hear them. Thanks!

**Comment by Nic-Ma** [comment]
Hi @radiplab ,

Glad to see you got good progress here.
I think the problem is that: You asked how to handle "multi-labels" in this issue, so I provided several steps to do that.
But after checking your images and code, I feel your task is "multi-classes" segmentation instead of "multi-labels" now...
So you need to change all the "add_sigmoid" or "do_sigmoid" to `softmax` and try again.

Thanks.

**Comment by radiplab** [comment]
Ha! Well that worked. Thanks a lot for your time and advice. 

For anyone following along, to do multilabel classification, just change out_channels in the network definition to your number of labelled structures + 1 (the extra 1 being the background). Everything else from the spleen segmentation example stays the same.

**Comment by Nic-Ma** [comment]
> Ha! Well that worked. Thanks a lot for your time and advice.
> 
> For anyone following along, to do multilabel classification, just change out_channels in the network definition to your number of labelled structures + 1 (the extra 1 being the background). Everything else from the spleen segmentation example stays the same.

Hi @radiplab ,

It's "multi-classes segmentation" instead of "multi-labels classification".
Thanks.

**Comment by patriciacs1994** [comment]
Hi @Nic-Ma, I have followed your steps to build a multi-classes segmentation model but I am getting an error in this line:

`value = monai.metrics.compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False)`
_ValueError: y_pred and y should have same shapes._
y_pred shape is: torch.Size([1, 4, 192, 192])
y shape is:  torch.Size([1, 1, 192, 192])

So, I guess I have to include **to_onehot_y=True** in compute_meandice. But when I do it the next error shows up:
_TypeError: compute_meandice() got an unexpected keyword argument 'to_onehot_y'_

Do you know how to solve this?
Thank you in advance

**Comment by Nic-Ma** [comment]
Hi @patriciacs1994 ,

You should consider to apply `post transforms` before metrics, refer to:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d.ipynb

Thanks.

**Comment by patriciacs1994** [comment]
Thank you for your quick response @Nic-Ma,
Now, it works!

**Comment by ankitabuntolia** [comment]
> 

When should we do One-Hot encoding of labels in a multi-label segmentation problem? I mean before creating a dataloader?

Thanks!

**Comment by Mushtaqml** [comment]
@Nic-Ma, I am sorry, but after reading this discussion a couple of times, I am still confused to figure out the difference between multi-label and multi-class segmentation. How can you figure it out from your mask labels?

**Comment by KumoLiu** [comment]
Hi @Mushtaqml,
Multiclass classification means a classification task with more than two classes; Multiclass classification makes the assumption that each sample is assigned to one and only one label which are mutually exclusive.
Multilabel classification assigns to each sample a set of target labels. This can be thought of as predicting properties of a data-point that are not mutually exclusive.
Hope it helps you, thanks.

**Comment by MUKILAN-2003** [comment]
@Nic-Ma I Have an query. If i am doing an multi-label(0-7) classification then what was the out_channel ?

**Comment by Nic-Ma** [comment]
Hi @MUKILAN-2003 ,

I think the model output is always in OneHot format, so your `out_channel` is should be 8?
And `to_onehot=8` means the number of classes is 8 when converting the label to OneHot.
CC @KumoLiu for the further discussion.

Thanks.

**Comment by MUKILAN-2003** [comment]
Thanks ! @Nic-Ma @KumoLiu
Ok Then the Orginal Target also need to have 8 channle Right ? like (1,8,512,256,256) [Batch.Channel,Slice,Size,Size]

**Comment by MUKILAN-2003** [comment]
`out_channel = 8` and my y_label in shape of (1,1,512,256,256) [MultiLabel]. Thrown an error while training
![image](https://user-images.githubusercontent.com/65155327/188297860-883f2b7b-cf32-4bce-907b-e3c135f2bdc2.png)

**Comment by KumoLiu** [comment]
Hi @MUKILAN-2003,
If you are doing an multi-label classification why your label have spatial size, your label shape should be B*1 or B*C.

**Comment by MUKILAN-2003** [comment]
@KumoLiu 
3-D Segmentation thats why the label shape is [1,512,256,256] (Channel, Slice, Size, Size)
Is this wrong ?

**Comment by KumoLiu** [comment]
Hi @MUKILAN-2003，
So you are doing a segmentation task, then your target shape should be in (B, 8, 512, 256, 256) in a onh-hot format. Check if your loss function do a one-hot. You can also refer to this [multi-label segmentation](https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/brats_segmentation_3d.ipynb) tutorial for more tips!

**Comment by MUKILAN-2003** [comment]
Yeah ! @KumoLiu
Then the the **y_true** should be (B, 8, 512, 256, 256) in a one-hot format. Right ?

Thank You

**Comment by KumoLiu** [comment]
Yes. y_true should be one-hot format. 8 classes (0 - 7) can be formatted to 8 channel such as (B, 8, 512, 256, 256) @MUKILAN-2003

**Comment by MUKILAN-2003** [comment]
Ok Thanks for clarification. If I have any doubts I will ping you

Thank You @KumoLiu

**Comment by MUKILAN-2003** [comment]
@KumoLiu 
```
model = UNet(
    spatial_dims=3,
    in_channels=1,
    out_channels=8,
    channels=(16, 32, 64, 128, 256),
    strides=(2, 2, 2, 2),
    num_res_units=2,
    norm=Norm.BATCH,
).to(device)

loss_function = DiceLoss(to_onehot_y=False, sigmoid=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4)
dice_metric = DiceMetric(include_background=True, reduction="mean")
```

---
Why [Min is < 0] and [Max is > 1] ? Orginal Mask has min of 0 and max 1. Why predicted range differ ? What mistake I have done

![image](https://user-images.githubusercontent.com/65155327/188306225-650f2352-adeb-4405-9ef1-e9b8209d80c9.png)

**Comment by KumoLiu** [comment]
Hi @MUKILAN-2003, it seems the output of network is not processed by the activation function and binarization.

**Comment by MUKILAN-2003** [comment]
> Hi @MUKILAN-2003, it seems the output of network is not processed by the activation function and binarization.

Did I miss any data processing ?

**Comment by KumoLiu** [comment]
Hi @MUKILAN-2003,
```
post_transforms = Compose([
    Invertd(
        keys="pred",
        transform=val_org_transforms,
        orig_keys="image",
        meta_keys="pred_meta_dict",
        orig_meta_keys="image_meta_dict",
        meta_key_postfix="meta_dict",
        nearest_interp=False,
        to_tensor=True,
    ),
    Activationsd(keys="pred", sigmoid=True),
    AsDiscreted(keys="pred", threshold=0.5),
])

model.load_state_dict(torch.load(
    os.path.join(root_dir, "best_metric_model.pth")))
model.eval()
with torch.no_grad():
    for val_data in val_org_loader:
        val_inputs = val_data["image"].to(device)
        val_data["pred"] = inference(val_inputs)
        val_data = [post_transforms(i) for i in decollate_batch(val_data)]
        val_outputs, val_labels = from_engine(["pred", "label"])(val_data)
        dice_metric(y_pred=val_outputs, y=val_labels)
        dice_metric_batch(y_pred=val_outputs, y=val_labels)

    metric_org = dice_metric.aggregate().item()
    metric_batch_org = dice_metric_batch.aggregate()

    dice_metric.reset()
    dice_metric_batch.reset()
```
For more information, refer to this [multi-label segmentation](https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/brats_segmentation_3d.ipynb) tutorial.
