### ISSUE TITLE
Docstrings in `wsi_reader.py` are not consistent

### ISSUE THREAD

**Issue by fepegar** [Project-MONAI/MONAI#4156]
Hi all,

I am loading an ROI of a large histological image using a `reader = WSIReader(backend='cucim')`. For that, I need to pass the `location` and `size` kwargs. The former is expressed as `x_min, y_min`, whereas the latter is `height, width`. I think there is a clash in this nomenclatures, as x and y are typically used for the horizontal (width) and vertical (height) dimensions, respectively, but here x seems to refer to the row (vertical dimension) and y seems to refer to the column (horizontal dimension).

My suggestion is replacing `x_min, y_min` with `y_min, x_min` or, even better, `top_row, left_column`.

**Comment by drbeh** [comment]
Hi @fepegar,

That's a good catch, thanks! I agree with your nomenclature. I believe this confusion has happened because the underlying libraries (cuCIM and OpenSlide) use the reverse of coordinates. We'll fix this!
