### ISSUE TITLE
data list utility enhancement

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4173]
**Is your feature request related to a problem? Please describe.**
the current data list utility assumes that when the key is `"test"`, the data is a list of filenames. https://github.com/Project-MONAI/MONAI/blob/ed1c281a0f1b0d9c364ed59020a69ab2a821a5f2/monai/data/decathlon_datalist.py#L125-L126

would be great to optionally support the testing data in the form of a list of dictionaries, to be consistent with the `'training'` list, for example,

```
        "test":
        [
            {'image': '/workspace/data/chest_19.nii.gz',  'othermetafield': 0},
            {'image': '/workspace/data/chest_31.nii.gz',  'othermetafield': 1}
        ]
```

**Comment by Nic-Ma** [comment]
Sure, I will try to enhance the API ASAP.

Thanks.
