### ISSUE TITLE
Error about tensor size

### ISSUE THREAD

**Issue by zswgzx** [Project-MONAI/MONAI#418]
Follow up of #323, any help would be appreciated :)

**Comment by zswgzx** [comment]
Ok RandZoomd keep_size=true. 

Is there any way to avoid having my data folder removed after training? It came to my attention that ../data was gone...

**Comment by Nic-Ma** [comment]
Hi @zswgzx ,

The original example generated test data in it, so removed all the data after training.
If not expected for your case, just remove this line: `shutil.rmtree(tempdir)`
Thank.

**Comment by zswgzx** [comment]
Got it. So how can the info from events.out.tfevents be extracted?

**Comment by Nic-Ma** [comment]
I am not sure, I think that's out of the scope of MONAI.
Thanks.

**Comment by zswgzx** [comment]
understood.
Since i have a small sample for training/validation, one solution would be performing 2d unet with every 3-5 slices as a channel. Is monai able to handle this? If so, how would u recommend to achieve? Thanks as always.

**Comment by Nic-Ma** [comment]
Hi @zswgzx ,

Your solution is similar to: xhttps://github.com/Project-MONAI/MONAI/issues/299.
Maybe you can use SpatialCrop to crop Z dim and call `AsChannelFirst` transform.

Thanks.

**Comment by zswgzx** [comment]
Will try. Thanks! Would you think it's easier to do so by the array (vs. dict) call?
So how'd I add an additional image from different modality in both training and validation? e.g. t1w & t2w images per scan + label image for segmentation.

**Comment by Nic-Ma** [comment]
I think maybe dict transform is better here? I can try the most useful transforms for your case.
What do you mean by "add an additional image" here? I didn't get what you plan to do.

Thanks.

**Comment by zswgzx** [comment]
That'd be wonderful~ xiexie!

Sorry about the confusion. As in the original example, there's just an image (e.g. t1w image or t2w or else) and a label pair per scan as input. What if I have, e.g. both t1w and flair images (already co-registered) and one label per scan as the input? Please let me know if it's still unclear.

**Comment by Nic-Ma** [comment]
Hi @zswgzx ,

OK, I see. The `LoadNifti` or `LoadNiftid` transform can support a list of images:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/io/array.py#L62
It will stack the images together.

Thanks.
