### ISSUE TITLE
Transform to Threshold Image for Tissue

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4181]
**Is your feature request related to a problem? Please describe.**
A transform that given a RGB image (a tile from histopathology image or a WSI at low resolution), apply thresholding algorithm to distinguish the tissue from the background, and outputs a binary mask and some statistics.

**Comment by JHancox** [comment]
A slightly different use-case is when you tile the input and the thresholded output is binary per tile. This results in the same low-res binary mask but is accomplished in a different way. Usually this is done at an intermediate resolution with the output being low res.

**Comment by KumoLiu** [comment]
Hi @drbeh, @JHancox
I'm still a bit missing the point, is MONAI's `ForegroundMask` not up to the task at the moment, and why?
https://github.com/Project-MONAI/MONAI/blob/9689abf834f004f49ca59c7fe931caf258da0af7/monai/transforms/intensity/array.py#L2196

**Comment by drbeh** [comment]
Hi @KumoLiu, it might be. Please check and verify the requested features are already addressed in `ForegroundMask`. Thanks

**Comment by KumoLiu** [comment]
Hi @JHancox, I quite didn't understand what mean "Return a binary image with each pixel representing a tile", does it mean for each tile to return a binary image to represent the corresponding mask? It seems we can ingest the WSI with `WSIReader`, split it into tiles with `GridPatch`, and in each patch use `ForegroundMask` to get a binary mask. If I understand correctly, the components in MONAI maybe already meet the requirements. Do I missing anything, I would be appreciated it if you can correct me! Thanks!

**Comment by JHancox** [comment]
Hi @KumoLiu , So, I'm probably making it sound more complicated that it is!
If you have an input image of say 1000 x 1000 (x3) and you want to threshold tiles of 50x50(x3), then at the end of the process, you end up with a binary image/mask of dimension 20 x 20 - or a list of coordinates of foreground patches. As @drbeh says, if this requirement can be met by existing features - fantastic! 
What this is, hopefully building towards is the ability to use this dynamically, within a DataReader that can then yield foreground patches. Hope that helps.
