### ISSUE TITLE
MVP example for multiple GPU training

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#42]
-Additional refactoring iteration to unify single-gpu/multiple gpu training?

**Comment by Nic-Ma** [comment]
Hi @madil90 ,

As you are expert on Deep Learning performance tuning and also done many investigations on PyTorch, could you please help to develop this task?
The minimal requirements will be:
1. Wenqi extracts pure python example from notebook example(already committed PR).
2. You can submit a PR to add Multi-GPU logics for training and evaluation(still in development) examples.
BTW, please note that: don't save the parallel model to files, be careful.
Please feel free to contact if you have any questions.
Thanks in advance.

**Comment by pdogra89** [comment]
Eric will create a work in progress PR - Eric and Adil to align - don't want to independent pull requests.

**Comment by wyli** [comment]
resolved via #49 #51
