### ISSUE TITLE
Deprecating Old Pathology Components

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4226]
Following our discussion in #4216 about wether we should deprecate the old pathology components (including the components in `monai/app/pathology` and elsewhere), or we should simply remove them and mention it in the release note.

My suggestion would be to deprecate since we have users that are continuously building pipelines based on our pathology components but I see Nic's point (https://github.com/Project-MONAI/MONAI/pull/4216#issuecomment-1116222932) about making a breaking change too. Any Thought?

@Nic-Ma @wyli @ericspod

**Comment by ericspod** [comment]
If we have no real need to delete things I would apply our deprecation decorators and set a version to remove things in, if people complain about things disappearing too soon it's easier to bump that version rather than reintroduce deleted code.
