### ISSUE TITLE
Packaging C++ functions in MONAI

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAI#4232]
There are quite a few C++ functions currently in MONAI that are quite useful in a number of applications. 
However, all C++ code requires compilation before they can be used (e.g. through JIT compilation or using BUILD_MONAI=1).

In order to use such C++ functions as dependency in other projects, these may need to be packaged as pre-compile binaries as we have already seen a number of issues with dependencies that required compilation (e.g. SImpleCRF dependency issues in MONAI Label see for example: https://github.com/Project-MONAI/MONAILabel/issues/605 and https://github.com/Project-MONAI/MONAILabel/issues/719).

There are of course discussions about moving some useful dependencies for MONAI Label scribbles into MONAI, so they can be maintained properly through community efforts (see for example discussion here: https://github.com/Project-MONAI/MONAILabel/pull/731 and here: https://github.com/Project-MONAI/MONAI/issues/1601)

It may be relevant to address these packaging issue for C++ functionality so that these can be used as dependency in other projects.

Relevant pointers:
- Torch extension builder for CI workflows: https://github.com/charliebudd/torch-extension-builder
- torchmaxflow wrapper for maxflow that is relevant for scribbles functionality in MONAI Label: https://github.com/masadcv/torchmaxflow

cc: @tvercaut @charliebudd

**Comment by tvercaut** [comment]
We can certainly transfer the [torch-extension-builder](https://github.com/charliebudd/torch-extension-builder) repo to sit under the [Project-MONAI](https://github.com/Project-MONAI) organisation if there is appetite for MONAI to support it.

**Comment by charliebudd** [comment]
I'm happy for MONAI to fork the repo. I think we can all agree a good end goal would be to have this supported by PyTorch. Untill that time moving into MONAI would provide better visability. An alternate direction would be to form a new github org ("PyTorch extention community" for example) as this could help to bring in stake holders from other projects. Either way I have added an MIT license to the git repo. I hope to have more time to work on this in the near future.

**Comment by charliebudd** [comment]
From the looks of it the debug information is being left in. Adding the [-g0 flag](https://github.com/charliebudd/torch-content-area/blob/0ac529dba89d299154d609e27761903b1834167b/setup.py#L10-L13) to the c++ compiler in setup.py will strip this. The wheels for my current project are around 1MB.

**Comment by masadcv** [comment]
@charliebudd would it be possible to also include Windows build in this? Or maybe this could be added as a future work?

**Comment by masadcv** [comment]
Many thanks! Yes, it certainly will be quite useful to have these precompiled for Windows - since most users we have seen have issue compiling source on Windows (see for example: https://github.com/Project-MONAI/MONAILabel/issues/363#issuecomment-1020445110)

**Comment by tvercaut** [comment]
For the time being, I would suggest to track generic packaging issues with torch-extension-builder in the @charliebudd's repo. E.g. for windows support:
https://github.com/charliebudd/torch-extension-builder/issues/13

**Comment by wyli** [comment]
> From the looks of it the debug information is being left in. Adding the [-g0 flag](https://github.com/charliebudd/torch-content-area/blob/0ac529dba89d299154d609e27761903b1834167b/setup.py#L10-L13) to the c++ compiler in setup.py will strip this. The wheels for my current project are around 1MB despite including binaries for multiple compilations.

thanks, this might be an issue for monai, I've enabled cuda10.2/11.3+pytorch1.9/1.10/1.11+multiple archs and the package size becomes 130Mb with the recommended compiler flags. with more than 100Mb, pypi is not supported by default https://test.pypi.org/help/#file-size-limit.

**Comment by masadcv** [comment]
> > From the looks of it the debug information is being left in. Adding the [-g0 flag](https://github.com/charliebudd/torch-content-area/blob/0ac529dba89d299154d609e27761903b1834167b/setup.py#L10-L13) to the c++ compiler in setup.py will strip this. The wheels for my current project are around 1MB despite including binaries for multiple compilations.
> 
> thanks, this might be an issue for monai, I've enabled cuda10.2/11.3+pytorch1.9/1.10/1.11+multiple archs and the package size becomes 130Mb with the recommended compiler flags. with more than 100Mb, pypi is not supported by default https://test.pypi.org/help/#file-size-limit.

is there any way to reduce this size to get to an acceptable range?

**Comment by charliebudd** [comment]
> > > From the looks of it the debug information is being left in. Adding the [-g0 flag](https://github.com/charliebudd/torch-content-area/blob/0ac529dba89d299154d609e27761903b1834167b/setup.py#L10-L13) to the c++ compiler in setup.py will strip this. The wheels for my current project are around 1MB despite including binaries for multiple compilations.
> > 
> > 
> > thanks, this might be an issue for monai, I've enabled cuda10.2/11.3+pytorch1.9/1.10/1.11+multiple archs and the package size becomes 130Mb with the recommended compiler flags. with more than 100Mb, pypi is not supported by default https://test.pypi.org/help/#file-size-limit.
> 
> is there any way to reduce this size to get to an acceptable range?

yes, as I said, the -g0 compiler flag will inform the compiler to strip the debug symbols. This is standard practice for release code and significantly decreases the build size.

**Comment by wyli** [comment]
I tried flags such as `"cxx", ["-g0", "-Wl,-s", "-Os"]`, the wheel file size is still 126M, mainly within the package there are:
```
-rw-r--r--@  89M  _C.so.pt110cu102
-rw-r--r--@  78M  _C.so.pt110cu113
-rw-r--r--@  89M  _C.so.pt111cu102
-rw-r--r--@  78M  _C.so.pt111cu113
-rw-r--r--@  89M  _C.so.pt19cu102
```

**Comment by vikashg** [comment]
maybe out of scope for monai-core? @masadcv  Please reopen if needed
