### ISSUE TITLE
Constructor `mode` argument ignored in SpatialResample

### ISSUE THREAD

**Issue by karwojan** [Project-MONAI/MONAI#4269]
There is a `mode` argument in `SpatialResample.__call__` method and in `SpatialResample` constructor. It has default values in both `__call__` method and in constructor, which causes constructor value is always ignored.

**Comment by Nic-Ma** [comment]
Hi @karwojan ,

Thanks for your interest here.
If the `mode` arg of `__call__` is `None`, it will use the mode from `self.mode`.

Thanks.

**Comment by wyli** [comment]
I think the default value in `__call__` could be improved to None https://github.com/Project-MONAI/MONAI/blob/1dfeb7430c37524c0dab02427a5489c329f77b66/monai/transforms/spatial/array.py#L140 I'll try to create a PR...
