### ISSUE TITLE
Improve bundle doc for the `import` logic

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#4283]
**Is your feature request related to a problem? Please describe.**
Thanks for @diazandr3s 's feedback, it's not clear in the bundle doc that:
1. Which class names can be used in `_target_` directly, which class should provide the full `module path`?
**answer**: MONAI classes and functions can be used directly.
2. When using `import` in the config, which packages are pre-imported? seems `monai`, `np`, `torch`.
**answer**: yes, the default behavior of `ConfigParser` will import `monai`, `numpy`, `np`, `torch` as these are MONAI min deps.
3. Should I import the components in the config? Like transforms, network, etc.
**answer**: only need to import 3rd libs for `expressions`, not for `_target_` instantiation.

Would be nice to enhance the bundle doc for these points.

**Comment by Nic-Ma** [comment]
CC @diazandr3s @ericspod @wyli 

Thanks.

**Comment by wyli** [comment]
I think these should be covered in https://github.com/Project-MONAI/tutorials/blob/master/modules/bundle/get_started.ipynb

**Comment by Nic-Ma** [comment]
> I think these should be covered in https://github.com/Project-MONAI/tutorials/blob/master/modules/bundle/get_started.ipynb

Hi @wyli ,

Yes, the tutorial notebook should be updated, and I think we should also describe in the doc:
https://docs.monai.io/en/latest/config_syntax.html#instantiate-a-python-object for the **class name**.
https://docs.monai.io/en/latest/config_syntax.html#to-evaluate-as-python-expressions for the **import logic**.
What do you think?

Thanks.

**Comment by wyli** [comment]
@Nic-Ma I think the syntax page here is for a quick reference only, details should go to the tutorials.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think maybe we should provide the page for all the details of syntax with examples, then users just search this page for any syntax questions. Refer to the `omegaconf`:
https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#creating
Many examples of bundle syntax can be found in this slides:
https://docs.google.com/presentation/d/1qXl5-GT14kST68RDCJ408ilMpiHDCAN1QnecuRoqyZI/edit?usp=sharing

The tutorial notebook is just one practice example which can't cover all cases.

Anyway, I am open for the discussion.
@ericspod @diazandr3s What do you guys feel when you started to develop a bundle? Do you want to refer to the documentation page or tutorial notebook?

Thanks.

**Comment by diazandr3s** [comment]
This is great, @Nic-Ma. Thanks for adding it.

I've just created the PR for the DeepEdit here: https://github.com/Project-MONAI/model-zoo/pull/3

I'll upload the pt and ts files once the training is completed.

In general, I like the way this is working. My only concern is that users need to first make sure that the code/algorithm works in Python as it is not easy to debug this.

I guess this is only a disadvantage among the advantages this all has.

Thanks again!!!

**Comment by diazandr3s** [comment]
I missed this part of the question:

> What do you guys feel when you started to develop a bundle? Do you want to refer to the documentation page or tutorial notebook?

I'd suggest having that in the Notebook format

I've created the DeepEdit bundle based on the already developed bundle for Spleen segmentation and the Notebook mostly. The development is easier when you have a JSON parser (i.e. [online](https://jsoneditoronline.org/#left=local.zecido))

**Comment by Nic-Ma** [comment]
Submitted PR for it: https://github.com/Project-MONAI/tutorials/pull/712.

Thanks.
