### ISSUE TITLE
`iter_patch_slices` Patch Order

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4287]
Similar to convolutions, the way usually sliding window is implemented is going over the slow dimension first and then go down the other indices (sweeping row by row), like this:
```python
A = [[ a, a, b, b],
     [ a, a, b, b],
     [ c, c, d, d],
     [ c, c, d, d]] 

L = [[[a,a],[a,a]],[[b,b],[b,b]], [[c,c],[c,c]], [[d,d],[d,d]]
```

However, in `iter_patch_slices`, this behavior is intentionally reversed:
https://github.com/Project-MONAI/MONAI/blob/cd77e910400eed5b596e739fb588e118677c813f/monai/data/utils.py#L148-L149
Is there any reason for that? Can we stick to the more common convention?

**Comment by wyli** [comment]
good question, looks like there is an inconsistency:
```py
import numpy as np
from monai.data import dense_patch_slices, iter_patch_slices

A = [['a', 'a', 'b', 'b'], ['a', 'a', 'b', 'b'], ['c', 'c', 'd', 'd'], ['c', 'c', 'd', 'd']]

print('dense_patch_slices')
xx = dense_patch_slices([4,4],[2,2], [2,2])
for i in xx: print(np.asarray(A)[i])

print('iter_patch_slices')
for i in iter_patch_slices([4,4], [2,2]):
    print(np.asarray(A)[i])

```

results:
```
dense_patch_slices
[['a' 'a']
 ['a' 'a']]
[['b' 'b']
 ['b' 'b']]
[['c' 'c']
 ['c' 'c']]
[['d' 'd']
 ['d' 'd']]
iter_patch_slices
[['a' 'a']
 ['a' 'a']]
[['c' 'c']
 ['c' 'c']]
[['b' 'b']
 ['b' 'b']]
[['d' 'd']
 ['d' 'd']]
```
I think we should by default consistently use the row-major order, could you help update `iter_patch_slices`?

**Comment by ericspod** [comment]
I'm late to the party but it was an older reasoning I had about why it was that ordering, with images that are WH ordering like NIFTI this did things in the right order.
