### ISSUE TITLE
Prepare the codebase for the public alpha:

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAI#43]
-Refactor input ‘transform’ interfaces
    - Finalise the code folder structure
    - More thorough unit tests
    - More integration tests
    - Following the current design, more networks/losses/metrics/transforms

**Comment by Nic-Ma** [comment]
Hi All,

To start this discussion, I have a proposal of "_Refactor input ‘transform’ interfaces_":
1. Keep current **'vanilla' implementation** of transforms, it's similar to torchvision and **user can use it** if they don't have "dict" input data.
2. Add another higher level adapter or proxy class to **handle "dict" based input data**. Take "random window croping" for example, this proxy layer will:
_(1) generate a random window.
(2) call our **crop_transform** twice to crop the same window on 2 apply keys('image', 'label')._

Welcome your discussion and please feel free to correct me if I misunderstand anything.
Thanks in advance.
