### ISSUE TITLE
Add the support for bio signals ( 1D data )

### ISSUE THREAD

**Issue by 0reza** [Project-MONAI/MONAI#4325]
Hey,
As the project name suggest, it's a framework for deep learning in biomedical field.
But I don't get it, why it's so focused on medical imaging?

There is a wide variety of medical data that is not image, like neurosignals or sounds of the organs.

I like to contribute to the project, and very interested to know about the potential of new data type the framework is capable of processing.

**Comment by wyli** [comment]
thanks, this is currently under discussion here: https://github.com/Project-MONAI/MONAI/discussions/4119 and recently the core dev team also had initial discussions on ECG. would you mind putting more details in #4119 for some concrete ideas, I'm closing this ticket for now.
