### ISSUE TITLE
using StrEnum instead of Enum

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4351]
**Is your feature request related to a problem? Please describe.**
StrEnum (new in py3.11 https://docs.python.org/3.11/library/enum.html#enum.StrEnum) "is the same as Enum, but its members are also strings and can be used in most of the same places that a string can be used."

this is a feature request for incorporating this class which will hopefully simplify the codebase in many places such as 
https://github.com/Project-MONAI/MONAI/blob/eb60b9caf0a103af53ab5f3d620ceb2c116a4851/monai/transforms/croppad/array.py#L94

however `StrEnum` is not available for other versions of python that monai supports, some customized class should be introduced. see also the discussion https://discuss.python.org/t/built-in-strenum/4192

cc @SachidanandAlle

**Comment by Nic-Ma** [comment]
Interesting feature, thanks for the sharing.

**Comment by wyli** [comment]
addressed by providing `monai.utils.StrEnum` https://github.com/Project-MONAI/MONAI/blob/40717509198909b444d9566052602b7db0cfd0cb/monai/utils/enums.py#L52-L61
