### ISSUE TITLE
Organisation of metrics folder

### ISSUE THREAD

**Issue by csudre** [Project-MONAI/MONAI#4389]
**Is your feature request related to a problem? Please describe.**
The Metrics Reloaded consortium has classified the metrics in 3 main categories and it would be great to have them organised according to these categories for an easy match and reference between the consortium recommendations and the MONAI practical implementation

**Describe the solution you'd like**
The three categories are the following:
Counting metrics - Fbeta / IoU / Sensitivity@Specificity / Specificity@Sensitivity ...
Multithreshold metrics - AUROC / FPROC / AP
Distance based metrics - ASSD / MSD / NSD / HD / Boundary IoU

metrics could be for instance organised in sub-folders according to the category they belong to

**Describe alternatives you've considered**
Possible alternative would be to gather all metrics of the same category in the same python class

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/issues/5740
