### ISSUE TITLE
Implementation of IoU

### ISSUE THREAD

**Issue by csudre** [Project-MONAI/MONAI#4394]
**Is your feature request related to a problem? Please describe.**
Please include the IoU as additional counting based metric

**Describe the solution you'd like**
IoU is simply defined as TP/(2*TP+FP+FN) - However one should indicate point out in the documentation that IoU and F1 evaluate similar aspects and should therefore not be used in conjunction

**Comment by Nic-Ma** [comment]
Hi @csudre ,

We already have some basic implementation for IoU in the codebase:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/box_utils.py#L765
Could you please help take a look at whether it can satisfy your request?

Thanks.

**Comment by csudre** [comment]
Hi @Nic-Ma,
It seems that on the link it covers only the case of boxes - I meant here IoU for a pixelwise segmentation not only bounding box. So won't be enough as far as I can see. This is also known as the Jaccard similarity coefficient

Best

**Comment by Nic-Ma** [comment]
Hi @csudre ,

OK, I see. Thanks for raising this feature request.
Let me mark it for development and welcome contribution.

Thanks.

**Comment by yashika-git** [comment]
Hi @Nic-Ma @csudre 
Can I try adding this feature?
Thank You

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

Of course, please feel free to submit a PR for it.
Welcome your contribution!

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

BTW, IoU of segmentation will also be useful for our other MONAI-based projects, would be nice to include it in MONAI.

Thanks in advance.

**Comment by yashika-git** [comment]
Hi @Nic-Ma,

I'm getting started with it, need to read a little.
Hope to come up with the code by tonight.
Looking forward to contributing to MONAI :)

**Comment by yashika-git** [comment]
@Nic-Ma, It is taking me longer to implement as I've never contributed in open source before and I got a little overwhelmed. But I'll surely come up with the code soon.

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

Don't worry, take your time, and please feel free to raise any questions if you have.

Thanks for the contribution!

**Comment by yashika-git** [comment]
Hi @Nic-Ma,

I came across an implementation of IoU (Jaccard) in the source code of Dice Loss.
Please take a look:
https://github.com/Project-MONAI/MONAI/blob/f02519353d230873bcc12fbb7a61755ffbbfc337/monai/losses/dice.py#L176

Shall we create a separate codebase for IoU or can we mention in the documentation somewhere that IoU can be implemented through Dice Loss?

Please let me know, I would love to either add the code as a separate file or add to the documentations.

Thank You

**Comment by Nic-Ma** [comment]
Hi @ericspod @dongyang0122 @wyli ,

Could you please help share some comments about this question from a typical researcher's angle?

Thanks in advance.

**Comment by ericspod** [comment]
The DiceMetric doesn't use the DiceLoss for reasons related to NaN (like [here](https://github.com/Project-MONAI/MONAI/blob/0b97bb6172f967c4b4dd1de92263e26186db54b9/monai/metrics/meandice.py#L147)) and other implementation details that vary from the loss function so I would suggest that a IoU metric would follow this pattern for the same reasons and not use the loss function. I would suggest the DiceMetric is the template to follow in your implementation.

**Comment by dongyang0122** [comment]
Logically, losses and indicators serve different purposes. It is better to implement them separately according to their own needs.

**Comment by yashika-git** [comment]
@dongyang0122, Right. My bad, I had mixed up the things. 
Thank you!

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

Thanks very much for your contribution!
I will invite some experts to review it ASAP.
And BTW, I think maybe you submitted pull request to the wrong repo(your own repo), could you please submit it from `your repo / your branch` to `MONAI repo / MONAI dev branch`? For example: https://github.com/Project-MONAI/MONAI/pull/4494

Thanks.

**Comment by yashika-git** [comment]
@Nic-Ma, Thank you, I have submitted it to the right repo now.
