### ISSUE TITLE
rand zoom "keep_size" should default to True?

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#447]
**Describe the bug**
a few monai examples use `RandZoom` and `Resize`,
but when RandZoom's `keep_size` option is False (the current default)
the preprocessor generates outputs that are almost identical to the inputs.

**To Reproduce**
this script tries to to 2x zoom and resize to `768x1024`:
```python
import matplotlib.pyplot as plt
import scipy.misc

from monai.transforms import RandZoom, Resize

img = scipy.misc.face(gray=True)[None]
zoom = RandZoom(prob=1.0, min_zoom=2, max_zoom=2)
resize = Resize(spatial_size=(768, 1024))
new_img = resize(zoom(img))

plt.subplots(1, 2)
plt.subplot(1, 2, 1)
plt.imshow(img[0], cmap="gray")
plt.subplot(1, 2, 2)
plt.imshow(new_img[0], cmap="gray")
plt.show()
```
the output is:
![Figure_1](https://user-images.githubusercontent.com/831580/83173251-a780b480-a110-11ea-938e-bce626eb28ce.png)

**Expected behavior**
setting `keep_size` to True 
(`zoom = RandZoom(prob=1.0, min_zoom=2, max_zoom=2, keep_size=True)`) 
gives the expected output:
![correct](https://user-images.githubusercontent.com/831580/83173377-d860e980-a110-11ea-8ada-75d9b9ed3e94.png)

**Environment (please complete the following information):**
 - OS macos
 - Python version 3.6
 - MONAI version 3181e3efb4b359acd7006c71e1146a299a51040e

**Additional context**
quit a few places use `RandZoom(..., keep_size=False)` and `Resize` together, they are probably wrong

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, this is truly an bug as we discussed before v0.1 release. And we already `keep the size` for `Rotate` related transforms, should do the same for Zoom.
I am trying to fix it in PR: https://github.com/Project-MONAI/MONAI/pull/448
Will update all examples and notebooks soon.
Could you please also update the Colab example of MedNIST?
Thanks.

**Comment by ferchonavarro** [comment]
Hi @Nic-Ma one question also related to the RandZoom, ut seems like the default padding is to mirror the pixels in the border, is it possible to change this to minimum or zeros?

**Comment by Nic-Ma** [comment]
Hi @ferchonavarro ,

May I know why you want to change the default value of padding arg?
I think for most cases, `edge` can help to generate a smooth edge in the image, and it will not affect the training.

Thanks.

**Comment by ferchonavarro** [comment]
> Hi @ferchonavarro ,
> 
> May I know why you want to change the default value of padding arg?
> I think for most cases, `edge` can help to generate a smooth edge in the image, and it will not affect the training.
> 
> Thanks.

Hi @Nic-Ma 

I dont really know if this will affect the trianing. Just visually it makes more sense that after a RandZoom transformation the image has zero pad or minimum or max depending on the user, for example in this image
![sub-verse417_split-verse277_ce-no_L2](https://user-images.githubusercontent.com/19378667/115017190-6aebb200-9eb6-11eb-9296-16e2494b492c.png)

Rather than something like this, which is the default behavior at the moment.
![sub-verse417_split-verse277_ce-no_T9](https://user-images.githubusercontent.com/19378667/115017777-52c86280-9eb7-11eb-966d-71f97ef97d1e.png)
