### ISSUE TITLE
SwinUNETR architecture implementation error?

### ISSUE THREAD

**Issue by razorx89** [Project-MONAI/MONAI#4487]
**Describe the bug**
According to the paper, each transformer output should be processed by a residual block before concatenation with other features. However, for stage 3 the features are concatenated directly, which is not in line with the figures in the publication.

https://github.com/Project-MONAI/MONAI/blob/0b97bb6172f967c4b4dd1de92263e26186db54b9/monai/networks/nets/swin_unetr.py#L285-L286 

@ahatamiz

**Comment by razorx89** [comment]
Thanks for clarifying. However, this still differs from the explanation in the papers [here](https://arxiv.org/pdf/2201.01266.pdf) and [here](https://arxiv.org/pdf/2111.14791.pdf).

<img width="546" alt="image" src="https://user-images.githubusercontent.com/15977832/173504456-42cbe6b7-a076-4062-bbee-f0e51b9e8b04.png">

I think this deviation from the described architecture should be at least noted in the docstring.

**Comment by ahatamiz** [comment]
Sure. I will update the docstring.

**Comment by dirtycomputer** [comment]
Where is the updated version?
