### ISSUE TITLE
Hyperlink in the config syntax doesn't work

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#4489]
**Describe the bug**
Thanks for Can's feedback, all the hyperlinks within "Syntax examples explained" in the config syntax page don't work:
https://docs.monai.io/en/latest/config_syntax.html#1--to-interpolate-with-python-objects

It may because the index or special character in the title names.
Would be nice to update them.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, the links can work in Github markdown preview, but can't work in the HTML page.
Sorry I didn't get what you mean "modify it would break the github links"?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Yes, the links can work in Github markdown preview, but can't work in the HTML page. Sorry I didn't get what you mean "modify it would break the github links"?
> 
> Thanks.

I mean it might be difficult to have both html/github working consistently given we have indexing and characters in the titles, if you can fix both versions that's good.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I submitted a PR for it: https://github.com/Project-MONAI/MONAI/pull/4490, could you please help review it?
I think it can work for both Github preview and HTML page now.

Thanks in advance.
