### ISSUE TITLE
reader backend for dicom

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4502]
**Is your feature request related to a problem? Please describe.**
this feature request is for adding basic Dicom support with a pydicom backend in addition to the existing readers (by extending the base class monai.data.ImageReader)
https://github.com/Project-MONAI/MONAI/blob/af0e0e9f757558d144b655c63afcea3a4e0a06f5/monai/data/image_reader.py#L45

note that as references: 
- there are deploy operators based on pydicom such as https://github.com/Project-MONAI/monai-deploy-app-sdk/tree/main/monai/deploy/operators
- the current itk backend ignores the some of the tags, but in general the new backend implementation should return a similar data structure: https://colab.research.google.com/drive/14R9RzmaKQn0Ahpxf9OwhW6U7kcH1_MRi
- the new backend will support the reading https://github.com/Project-MONAI/MONAI/discussions/4227

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

You can refer to the `ITKReader` for the DICOM features.

Thanks.
