### ISSUE TITLE
Flexible UNet implementation with backbones

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#4533]
**Is your feature request related to a problem? Please describe.**
Followup discussion of #896 .
Currently, we don't have a flexible segmentation pipeline that can support different backbones and pretrained weights.
I think it would be very useful to provide such networks, at least for the UNet implementation.
Actually, we already have some similar prototype in the tutorial:
https://github.com/Project-MONAI/tutorials/blob/main/kaggle/RANZCR/4th_place_solution/models/seg_model.py
I think we can start from integrating this implementation.
@wyli @yiheng-wang-nv What do you think?

**Comment by wyli** [comment]
To be clear about the requirements, there are multiresolution feature encoders implemented such as https://github.com/Project-MONAI/MONAI/blob/78509ae55ef98660907544e92713e44897bb7e48/monai/networks/nets/efficientnet.py#L559

This ticket looks for 
- a unet-style decoder, for multiresolution upsampling/deconv and skip connections
- segmentation head as the final output block of decoder
- A wrapper for encoder/decoder/head, this could be a generic segmentation wrapper

**Comment by yiheng-wang-nv** [comment]
Add @binliunls
