### ISSUE TITLE
SpacingD doesn't change pixdim metadata

### ISSUE THREAD

**Issue by Douwe-Spaanderman** [Project-MONAI/MONAI#4559]
**Describe the bug**
Transform SpacingD doesn't change the pixdim field in the metadata. I am not sure this is done on purpose, but I think it should change the pixdim similarly as it changes the affine matrix in the metadata.

**To Reproduce**
1. Use transform SpacingD
2. Print key metadata

**Expected behavior**
data["key_meta_dict"]["pixdim"] should change based on new pixdim. 
Maybe even better would be to get an additional key:
- data["key_meta_dict"]["pixdim"] <- new spacing
- data["key_meta_dict"]["pixdim_before_spacing_transform"] <- old spacing

**Comment by wyli** [comment]
thanks for the report, this will be addressed in the upcoming release with MetaTensor. currently you can use `from monai.data.utils import affine_to_spacing` to compute the previous spacing, for example:
`affine_to_spacing(data["key_meta_dict"]["original_affine"])`

**Comment by wyli** [comment]
now on the dev branch
```py
>>> from monai.transforms import SpacingD
>>> import torch
>>> x = torch.zeros((1, 10, 10))
>>> data = {'img': x}
>>> output = SpacingD('img', (1.4, 1.6))(data)
>>> output['img'].pixdim
tensor([1.4000, 1.6000, 1.0000], dtype=torch.float64)
```
