### ISSUE TITLE
Consider enhancing get_train_stats()

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/MONAI#4563]
**Is your feature request related to a problem? Please describe.**
Currently, the Trainer's [get_train_stats](https://github.com/Project-MONAI/MONAI/blob/d34fa14eed3191126fc1bc1a9751e69e0396f78b/monai/engines/trainer.py#L60)() function is returning a fixed set of stats

```
    def get_train_stats(self) -> dict[str, float]:
        return {"total_epochs": self.state.max_epochs, "total_iterations": self.state.epoch_length}
```

**Describe the solution you'd like**
Make it configurable true input arguments.

**Describe alternatives you've considered**
Alternatively, anyone needing train stats could access `trainer.state` directly. However, having a general `get_train_stats()` call might have more utilities.

**Additional context**
Training stats could be useful in contexts such as federated learning.

**Comment by habibcomsats** [comment]
I agree with @holgerroth 

More general and flexible stats collector is needed in order to support a large variety of single and multimodal trainers.

**Comment by Nic-Ma** [comment]
I will try to enhance the `get_train_stats` API with more flexible fields.

Thanks.
