### ISSUE TITLE
The instructions for building documentation fail

### ISSUE THREAD

**Issue by mersad95zd** [Project-MONAI/MONAI#4575]
**Describe the bug**
The instructions provided at
https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#building-the-documentation
are not reproducible on Ubuntu 20.04.4, most likely due to dependency upgrades.

**To Reproduce**
1. Go to 'https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#building-the-documentation'
2. follow the instructions
3. the first issue that occurs is that Sphinx won't be installed, docutils needs to be downgraded to a version < 0.17.
4. after installation completes, "make html" won't run since Sphinx-build lies in a directory that is not part of the local PATH. Therefore, one needs to use export to add that to the local PATH. 
5. Finally, pygments also needs to be downgraded to 2.7 in order for "make html" to run. 

**Expected behavior**
After these modifications, "make html" should build the documentation in the html format.

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```
================================
Printing MONAI config...
================================
MONAI version: 0.9.0+21.g8536cd31
Numpy version: 1.22.4
Pytorch version: 1.11.0+cu113
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 8536cd316e2dab0c2d85fe56a2e2697d3dca765e
MONAI __file__: /home/mdarestani/monai_local/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 4.0.1
scikit-image version: 0.19.3
Pillow version: 7.0.0
Tensorboard version: 2.9.1
gdown version: 4.4.0
TorchVision version: 0.12.0+cu113
tqdm version: 4.64.0
lmdb version: 1.3.0
psutil version: 5.9.1
pandas version: 1.4.2
einops version: 0.4.1
transformers version: 4.20.0
mlflow version: 1.26.1
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.4 LTS
Platform: Linux-5.13.0-44-generic-x86_64-with-glibc2.29
Processor: x86_64
Machine: x86_64
Python version: 3.8.10
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='/home/mdarestani/monai_local/MONAI/cufile.log', fd=3, position=4497, mode='a', flags=33793)]
Num physical CPUs: 18
Num logical CPUs: 36
Num usable CPUs: 36
CPU usage (%): [5.4, 99.4, 5.4, 4.8, 5.4, 5.4, 5.4, 5.4, 5.4, 5.9, 5.9, 5.4, 5.4, 6.0, 6.0, 5.4, 5.4, 5.4, 4.8, 4.8, 5.4, 5.4, 5.4, 5.4, 4.8, 4.8, 5.4, 5.4, 5.4, 4.8, 5.4, 5.4, 5.4, 5.4, 5.4, 6.0]
CPU freq. (MHz): 3047
Load avg. in last 1, 5, 15 mins (%): [0.4, 0.3, 0.2]
Disk usage (%): 53.1
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.1
Available memory (GB): 29.3
Used memory (GB): 1.4

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.3
cuDNN enabled: True
cuDNN version: 8200
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
GPU 0 Name: NVIDIA TITAN RTX
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 72
GPU 0 Total memory (GB): 23.6
GPU 0 CUDA capability (maj.min): 7.5

**Additional context**

**Comment by wyli** [comment]
thanks for reporting, the build instructions work fine with a ubuntu 20.04 docker image in our premerge tests

https://github.com/Project-MONAI/MONAI/blob/ff9ff55dd9198dabcc31eebe3109332ea708b356/.github/workflows/pythonapp.yml#L216-L224

perhaps it's your local setup issue?

**Comment by mersad95zd** [comment]
Hmm, might be, I just had to add sphinx builds to my PATH. Guess if someone faces the same error, they can do the same thing. Thanks for looking into it!
