### ISSUE TITLE
OptionalImportError: from einops import rearrange (No module named 'einops').  trying to implement SwinUnetR

### ISSUE THREAD

**Issue by hemanthh17** [Project-MONAI/MONAI#4585]
`OptionalImportError: from einops import rearrange (No module named 'einops').`
`For details about installing the optional dependencies, please visit:`
   ` https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies`
I am getting the above error even after installing all the required packages

**Comment by wyli** [comment]
could you please follow the bug reporting template to provide more info?
