### ISSUE TITLE
Update NVFlare FL spleen seg example to use MONAIClientAlgo

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/MONAI#4615]
**Is your feature request related to a problem? Please describe.**
This example needs updating to use new MONAIAlgo and bundle configuration (once ready) https://github.com/Project-MONAI/tutorials/tree/main/federated_learning/nvflare/nvflare_spleen_example

**Describe the solution you'd like**
Update example to use MONAIAlgo and bundle configs, see https://github.com/Project-MONAI/MONAI/issues/4612.
It will also need integration with [NVFlare](https://github.com/NVIDIA/NVFlare) (adding a `ClientAlgoExecutor`)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by wyli** [comment]
documentation updated https://github.com/Project-MONAI/tutorials/tree/main/federated_learning/nvflare
