### ISSUE TITLE
FORCE_CUDA doesn't force CUDA if `torch.cuda.is_available()`

### ISSUE THREAD

**Issue by ashgillman** [Project-MONAI/MONAI#4621]
I would have assumed that FORCE_CUDA would attempt to install CUDA in all cases.

I suspect the logic here:

https://github.com/Project-MONAI/MONAI/blob/edf3b742a4ae85d1f30462ed0c7511c520fae888/setup.py#L39

should be

```py
 BUILD_CUDA = FORCE_CUDA or (torch.cuda.is_available() and (CUDA_HOME is not None))
```

Or perhaps I misunderstood the flag. I couldn't find any documentation for it in the installation guide.

Cheers,
Ash

**Comment by wyli** [comment]
correct, would you be interested in submitting a PR? 

also, it's an experimental feature that we don't encourage extensive use. 
if you are reading that line probably you are able to workaround it, for example, by providing a `CUDA_HOME` https://github.com/pytorch/pytorch/blob/88f4a1240275205f630dbaca97b1f5d7977f25f8/torch/utils/cpp_extension.py#L84
