### ISSUE TITLE
backward compatible `EnsureType`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4637]
**Is your feature request related to a problem? Please describe.**
the current `EnsureType` removes any metadata
https://github.com/Project-MONAI/MONAI/blob/99b9dd7cf0667113e56f0dd90d40699115048d59/monai/transforms/utility/array.py#L464

given it's extensively used in the existing tutorials, would be great to enable metatensor output support and remove the inverse to preserve metadata when inverting the transform.
https://github.com/Project-MONAI/MONAI/blob/99b9dd7cf0667113e56f0dd90d40699115048d59/monai/transforms/utility/dictionary.py#L570-L574

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising this ticket.
@KumoLiu and I also see this issue when updating the tutorials, I think maybe we can just change the default value of `data_type` arg to `str "metatensor"` instead of `"tensor"`?

Thanks.

**Comment by wyli** [comment]
sure @Nic-Ma, I'm working on a fix for this one.
