### ISSUE TITLE
fastMRI data reader

### ISSUE THREAD

**Issue by mersad95zd** [Project-MONAI/MONAI#4646]
**Is your feature request related to a problem? Please describe.**
fastMRI dataset (https://fastmri.org/dataset/), a benchmark for accelerated MRI reconstruction, contains `.h5` files. Currently, a proper data reader for such files (in the fastMRI format) is missing.

**Describe the solution you'd like**
Add the fastMRIReader class.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by wyli** [comment]
#4653
