### ISSUE TITLE
Interoperability numpy functions <> MetaTensor

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4649]
**Is your feature request related to a problem? Please describe.**
would be nice if `MetaTensor` could have basic compatibility with numpy functions,
perhaps returning the primary array results as `np.ndarray` is a good starting point.

but currently it is

```py
>>> import monai
>>> import numpy as np
>>> np.sum(monai.data.MetaTensor(1.0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in sum
  File "/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2298, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * (*, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: out, axis
 * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)
 * (tuple of names dim, bool keepdim, *, torch.dtype dtype)
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising the discussion.
I don't quite understand this feature request, I suggested to keep supporting both numpy and tensor at the beginning of development for `MetaTensor`, but later I think @ericspod @rijobro and we two aligned to drop numpy support to make the code base clear and let's make this breaking change before 1.0. So why we want to support `np.XXX()` for `MetaTensor` now?
Maybe I misunderstand some important info, @rijobro @ericspod what do you think?

Thanks.

**Comment by wyli** [comment]
Hi @Nic-Ma  this request is about basic compatibility/interoperability, it's not really about the design of the core data structure. In v0.9 the transform outputs are numpy and the exiting user code may assume numpy output. Currently we can use `np.sum(MetaTensor.detach().numpy())` anyway, it'll be nice to make it simpler such as `np.sum(MetaTensor)`.

**Comment by Nic-Ma** [comment]
OK, if we can update `MetaTensor` to automatically support `np.XXX()`, it's non-breaking to the design.

Thanks.
