### ISSUE TITLE
Bug in GeneralizedDiceLoss

### ISSUE THREAD

**Issue by argman** [Project-MONAI/MONAI#4656]
```
w = self.w_func(ground_o.float())
for b in w:
    infs = torch.isinf(b)
    b[infs] = 0.0
    b[infs] = torch.max(b)
```
the implementation seems to count for ground_o = 0, but change b cannot change w

**Comment by wyli** [comment]
thanks for reporing, that's addressed in more recent versions of MONAI https://github.com/Project-MONAI/MONAI/issues/3618
