### ISSUE TITLE
Questions on Rand3DElastic

### ISSUE THREAD

**Issue by marksgraham** [Project-MONAI/MONAI#467]
Wondering if anyone can help me understand the behaviour of the `Rand3DElastic` transform? I've two questions:

1. Is it possible to return an deformed image with the same  size as the input image? It seems like I need to specify the argument `spatial_size = [h, w, d]`, which seemingly returns a volume of that size centred on the input. Ideally I would like to perform elastic deformation using `Rand3DElastic` and then later take a _random_ cropping of the deformed image using the `RandSpatialCrop` transform. Alternatively I would be happy if I could use  `Rand3DElastic` to return a random cropping of my input, but that doesn't seem possible.

2. Does the argument `prob` control the probability that a random transformation is performed, in addition to the elastic deformation? The documentation makes it sound like the return type is completely changed by this argument:

> prob (float) – probability of returning a randomized affine grid. defaults to 0.1, with 10% chance returns a randomized grid, otherwise returns a spatial_size centered area extracted from the input image.

To me this sounds like either a deformed image is returned, or a grid. I don't think this is the case but caused me a lot of confusion when reading.

Thanks for  your help!
Mark

**Comment by wyli** [comment]
for the first question: you can set `translate_range` with some supports for that, for example if the input is 200x200x200, and output window is 60x60x60, set translate_range=[-70, 70], will have the effects of randomly cropping window-- shifting the 60x60x60 window with x, y, z units sampled from [-70 70] (x, y, z are offsets relative to the input image centre)

for the second, with the same example, prob=0.1 means that with 90% chance it returns a 60x60x60 window (centre window of the 200x200x200 input) without any random factors; with 10% chance it returns a deformed window.

thanks for the feedback we'll update the docs and/or examples

**Comment by marksgraham** [comment]
Thanks Wenqi!
