### ISSUE TITLE
Support DICOM keys when pruning extra keys

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#4677]
**Is your feature request related to a problem? Please describe.**
Currently, seems we only prune the nifti keys:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/utils.py#L1469
It may be necessary to support other keys and DICOM keys.
@yiheng-wang-nv reported the feedback when developing TCIA dataset.

**Comment by yiheng-wang-nv** [comment]
Thanks @Nic-Ma . As for dicom data, PydicomReader will save all tags with the `to_json_dict` method, and the keys are derived from original dicom tags. For example, "00200037", "7FE00008".
<img width="741" alt="Screen Shot 2022-07-12 at 11 06 29 PM" src="https://user-images.githubusercontent.com/68361391/178522826-bfc039c8-7ccd-4ead-94cf-39276ede2565.png">

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/pull/4819 regex support
