### ISSUE TITLE
Invalid Syntax Appearing

### ISSUE THREAD

**Issue by Janson-Kappen** [Project-MONAI/MONAI#4682]
Hello there, 

I am a new user to Monai and I getting an "invalid syntax" message when using the SqueezeDimd transformation. I have experienced this with other transformations as well, including the RandRotate transformation. Please advise, thanks!
<img width="974" alt="Screen Shot 2022-07-12 at 2 45 39 PM" src="https://user-images.githubusercontent.com/106348967/178571621-8c345cd1-27a2-4ef2-bff5-8423f3864533.png">
<img width="922" alt="Screen Shot 2022-07-12 at 2 46 05 PM" src="https://user-images.githubusercontent.com/106348967/178571623-a4ab19ef-14f9-4e7d-85a5-7b33570032e4.png">
<img width="738" alt="Screen Shot 2022-07-12 at 2 46 28 PM" src="https://user-images.githubusercontent.com/106348967/178571627-50392be2-7986-4d45-8194-9cc48f04ccbe.png">

**Comment by wyli** [comment]
both lines of `SqueezeDimd...` should end with `,`. (next time for this kind of question please use https://github.com/Project-MONAI/MONAI/discussions)
