### ISSUE TITLE
GridPatchDataset - can't associate label to patches extracted

### ISSUE THREAD

**Issue by RonanENX** [Project-MONAI/MONAI#469]
**Describe the bug**
I want to extract patches from a PET image, and associate them with a label to further train a classification network. I used ArrayDataset to generate arrays from my files (nifti), and therefore applied GridPatchDataset to yield me patches. When I don't provide the argument "labels=y_train" to "ArrayDataset", it works fine, providing me with the patches extracted from the original image. However, when I add the argument "labels=y_train", I obtain the following error " 'int' object has no attribute "shape". In some way, the function get_valid_patch_size is doing wrong. 

My aim is to provide the network with patches extracted from the scans, each one associated with the global label of the scan. So with PET images of size 128x128x128, with a patch_size of (64x64x64) I would obtain 8 patches having all the same label. I could therefore shuffle this whole patches dataset and use it to train a network for a classification task. Correct me if it doesn't make sense.

Have I implemented it the correct way or am I wrong ? Can this error be corrected by modifying the ArrayDataset or GridPatchDataset class ?

**To Reproduce**
## y_train=[0,1,0,0,...]
imtrans = Compose([
    LoadNifti(image_only=True),
    ScaleIntensity(),
    AddChannel(),
    Resize((128,128,128)),
    ToTensor()
])
ds=ArrayDataset(train_files, imtrans, labels=y_train)
ds=GridPatchDataset(ds, (64,64,64))
loader=DataLoader(ds, batch_size=8,num_workers=2, pin_memory=torch.cuda.is_available())
im, label = monai.utils.misc.first(loader)
print(type(im), im[0].shape, label)

**Expected behavior**
I expected the dataLoader to provide me with tensors of size (8,1,64,64,64,8), the last 8 corresponding to the labels of the patches

**Error message**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-2e39af64ab80> in <module>
----> 1 im=monai.utils.misc.first(loader)

~/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/monai/utils/misc.py in first(iterable, default)
     34     Returns the first item in the given iterable or `default` if empty, meaningful mostly with 'for' expressions.
     35     """
---> 36     for i in iterable:
     37         return i
     38     return default

~/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    854             else:
    855                 del self._task_info[idx]
--> 856                 return self._process_data(data)
    857 
    858     def _try_put_index(self):

~/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    879         self._try_put_index()
    880         if isinstance(data, ExceptionWrapper):
--> 881             data.reraise()
    882         return data
    883 

~/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/torch/_utils.py in reraise(self)
    393             # (https://bugs.python.org/issue2651), so we work around it.
    394             msg = KeyErrorMessage(msg)
--> 395         raise self.exc_type(msg)

AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ronan.thomas/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ronan.thomas/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/home/ronan.thomas/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/monai/data/grid_dataset.py", line 65, in __iter__
    yield from zip(*iters)
  File "/home/ronan.thomas/anaconda3/envs/patchs_HN/lib/python3.6/site-packages/monai/data/utils.py", line 142, in iter_patch
    patch_size = get_valid_patch_size(arr.shape, patch_size)
AttributeError: 'int' object has no attribute 'shape'

**Environment:**
Ubuntu 18.04
MONAI version: 0.1.0
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Numpy version: 1.18.1
Pytorch version: 1.5.0
Ignite version: 0.3.0
CUDA 10.12
Nvidia GTX 1050

Thank you in advance for your answers

**Comment by wyli** [comment]
Hi @RonanENX, the grid dataset is mainly designed for segmentation tasks. here you need to make a dataset that is aware of the patch level indexing. this is still work in progress in monai https://github.com/Project-MONAI/MONAI/commit/d347895d6a1a7f637e8bb22b9ccea396dae2d6e6.

but a quick working example for your case would be (assuming 8 patches per volume):
```python
import numpy as np
from torch.utils.data import DataLoader

from monai.data import ArrayDataset, Dataset, ZipDataset, iter_patch
from monai.transforms import AddChannel, Compose, Resize

# input img
img = np.zeros((128, 128, 128))
train_files = [img, img.copy(), img.copy()]
# input labels
y_train = ["a", "b", "a"]

imtrans = Compose([AddChannel(), Resize((128, 128, 128))])
y_train_patch = [x_p for x in y_train for x_p in [x] * 8]


class MyDataset(Dataset):
    def __init__(self, data):
        super().__init__(data)

    def __len__(self):
        return len(self.data) * 8

    def __getitem__(self, idx):
        img_id = int(idx / 8)
        patches = list(iter_patch(self.data[img_id][0], patch_size=[1, 64, 64, 64]))
        patch_id = idx - img_id * 8
        return patches[patch_id]


image_dataset = ArrayDataset(img_files=train_files, img_transform=imtrans)
patch_dataset = MyDataset(image_dataset)
ds = ZipDataset([patch_dataset, y_train_patch])
for x, y in DataLoader(ds, batch_size=2, shuffle=True):
    print(x.shape, y)
```

**Comment by blemasso** [comment]
Hi @RonanENX , I have the same problem as yours. As you, I work with a list of nifti files (not with matrices as in the example of Wyli). Therefore, the solution presented above do not work for me.
Did you found a solution to extract patches from images, and associate them with a label to further train a classification network?

Ths, 
Benjamin
