### ISSUE TITLE
support block type strings in resnet

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4691]
**Is your feature request related to a problem? Please describe.**
from https://github.com/Project-MONAI/MONAI/discussions/4678, the resnet input args should be able to understand strings in addition to the class types, the corresponding docstrings should be revised https://github.com/Project-MONAI/MONAI/blob/d99857cb49aab464ac38f7926ce4c6f299417721/monai/networks/nets/resnet.py#L173-L175

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help update the ResNet for it?

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
Hi @Nic-Ma , sure. Also for `SENet`.
