### ISSUE TITLE
IO formats 

### ISSUE THREAD

**Issue by asmagen** [Project-MONAI/MONAI#471]
Hello

How do I perform multi class semantic (instance) segmentation over my set of 2D PNG/TIF grayscale images and their corresponding masks file (NPY numpy array, TIF or any other) matrix representation with # channels corresponding to the classes?
Do I need to use NIFTI_interface? If so, how do I convert my PNG/TIF/NPY files to this format?

Thank you

**Comment by Nic-Ma** [comment]
Hi @asmagen ,

Thanks for your interest here!
1. Basically, I think the `LoadPNG` or `LoadPNGd` transform can load `TIF` format image also.
So maybe you can use `LoadPNGd(keys=["image", "label"])` to have a try first?
2. How many classes in this task? If you do need to convert to Nifti format, you can use the `nibabel` lib to save a numpy array into Nifti file.

Thanks.

**Comment by asmagen** [comment]
Thanks for your response @Nic-Ma 

1. Is there a tutorial performing a similar segmentation task and using PNG/TIF images via LoadPNGd(keys=["image", "label"]) or similar that I can adapt? I'm new to image analysis so I was hoping to get a quick start somehow.
2. I have. 7 classes including background (1st channel background, 2nd tumor, 3rd normal, 4 stroma etc). Some images don't have all of the tissue regions, e.g., some are all tumor, so the normal channel will be empty. I'm not sure if it's a problem. So do I need tot convert the format to Nifty or is it not necessary? If I do need it, do I use `img.to_filename(os.path.join('build','test4d.nii.gz'))`?

Thanks
