### ISSUE TITLE
Enhance bundle.read_config to pick either yaml or json automatically

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAI#4717]
https://github.com/Project-MONAI/model-zoo/tree/dev/models/pancreas_ct_dints_segmentation/configs
vs
https://github.com/Project-MONAI/model-zoo/tree/dev/models/spleen_ct_segmentation/configs

One using yaml and other using json.

If we want to use https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/config_parser.py#L254
We have to pre-check if user is using yaml or json.
This API can be abstracted to config without extension and `def read_config` can take care of loading based on what exists..

**Comment by Nic-Ma** [comment]
HI @SachidanandAlle ,

`config_parser` can support both YAML and JSON files and we don't force the filename of configs.
So maybe better to get the expected config filename before parsing?
CC @tangy5 as Yucheng is working on adding bundle support in MONAI Label according to our plan.

Thanks.

**Comment by SachidanandAlle** [comment]
Also it shall be great if you can support **_overrides_** as part of `ConfigParser.read_config`.  
Currently it's only supported through `monai.bundle.run`

**Comment by SachidanandAlle** [comment]
> ```python
> parser.config.update({"my_dims": 3})
> ```

Thanks.. it worked for my usecase..
i can override `bundle_root` by using your method.. for future.. better if this gets supported as arg/pararm similar to `monai.bundle.run`

**Comment by Nic-Ma** [comment]
Thanks @wyli for providing the basic example.
Besides the dict update, you can use `set/get` operations of `ConfigParser` with specified `id` directly:
```py
>>> from monai.bundle import ConfigParser

>>> 
>>> config = {
...     "my_dims": 2,
...     "dims_1": "$@my_dims + 1",
... }
>>> parser = ConfigParser(config)
>>> parser["my_dims"] = 3
>>> print(parser)
{'my_dims': 3, 'dims_1': '$@my_dims + 1'}
>>> parser["my_dims"] = {"3d": 3, "2d": 2}
>>> 
>>> print(parser["my_dims#2d"])
2
>>> print(parser.get("my_dims#5d", "no exist"))
no exist
>>> parser["my_dims#5d"] = 5
>>> print(parser["my_dims#5d"])
5
```

Thanks.
