### ISSUE TITLE
Consolidate ZeRO state before checkpoint saving

### ISSUE THREAD

**Issue by danieltudosiu** [Project-MONAI/MONAI#4723]
**Is your feature request related to a problem? Please describe.**
When checkpoint saving occurs there should be a check if the object that state_dict() is called on is a ZeroRedundancyOptimizer instance

**Describe the solution you'd like**
Prior to the call state_dict() call a consolidate_state_dict() call should be issued.

**Describe alternatives you've considered**
The only alternative is for the users to write themselves Handlers to do that, segregating the checkpoint-saving logic.

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

Currently, we are leveraging the ignite API to save the state_dict of components:
https://github.com/pytorch/ignite/blob/master/ignite/handlers/checkpoint.py#L465
Could you please help share a simple example code for your proposal?
@vfdev-5 Maybe it's a request for ignite?

Thanks in advance.

**Comment by danieltudosiu** [comment]
@Nic-Ma,

Sorry, you are right, this is a feature request for Ingite. 

Will create a ticket there.

Thanks!
