### ISSUE TITLE
Unsupported data type in `ConcatItemsD`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#4741]
**Is your feature request related to a problem? Please describe.**
`ConcatItemsD` only support numpy.ndarray and  torch.Tensor now, which is incompatible with MetaTensor data type.
https://github.com/Project-MONAI/MONAI/blob/c45b3f05b00567f2fa0c2058b8c9eb01fef573c4/monai/transforms/utility/dictionary.py#L969-L975

**Describe the solution you'd like**
Support MetaTensor data type

**Comment by Nic-Ma** [comment]
Good catch.
Could you please help submit a PR to enhance it?

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think the `cat` operation on MetaTensor is similar to the `collate` of meta information?

Thanks.

**Comment by wyli** [comment]
I think for now we can just support basic cat for metatensors using torch.cat. The output meta is the first input's meta by default...
