### ISSUE TITLE
Video dataset for inference

### ISSUE THREAD

**Issue by binliunls** [Project-MONAI/MONAI#4746]
**Is your feature request related to a problem? Please describe.**
Richard's tutorial [video_seg](https://github.com/Project-MONAI/tutorials/blob/1d7d0863d43e7ce1641154f6e8b2db0f80e5d963/modules/video_seg.ipynb) has a great application value on deploying segmentation models on video streams. However, trivial works like splitting the video to frames need to be done before inference if videos are given instead of images.  Therefore, a video dataset accepting a video as input and frames of the video as output may be convenient to this use case and enable a fast video inference pipeline.
A video dataset like other datasets in monai but using a video as input and frames, ordered according to the frame index in the video, as output may be what users would like to be seen.

**Describe the solution you'd like**

- [ ] Implement a dataset with a video input and generate frames as output.

**Comment by rijobro** [comment]
Hi there,
I have some datasets (video from file and video from video camera) in a [file on my repository](https://github.com/rijobro/real_time_seg/blob/main/python/video_seg.py). Feel free to tidy this up (e.g., the transforms need to be lifted out from the dataset) and submit this as a PR. This requires OpenCV.

**Comment by rijobro** [comment]
I have created a PR with the dataset but don't think it should be merged until a tutorial has been created that uses it. Can be based on my tutorial that was referenced at the top of this issue.
