### ISSUE TITLE
MetaTensor for Pathology

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4759]
Similar to radiology where we have a common `MetaTensor` properties and have employed them in radiology transforms, we need to explore the best way to leverage `MetaTensor` for pathology components and create a consensus around the common properties and metadata.

We have discussed this in our July 19 MONAI Pathology WG Dev Meeting, and also started a conversation around it: https://github.com/Project-MONAI/MONAI/discussions/4734

Below are the components that need to be evaluated and update when we arrive at a decision for MetaTensor for Pathology.
- [x] #4673
- [x] #4955
- [x] #4957
- [x] #4674
- [x] #4956
- [x] #4954

And here are the pipelines that are going to be affected.
- [x] #5078 
  - Pathology metastasis detection pipeline
  - Pathology multiple-instance learning pipeline

**Comment by Nic-Ma** [comment]
As offline sync with @drbeh , add @KumoLiu to the discussion and further development.

Thanks.
