### ISSUE TITLE
resnet10 downsamples images anisotropically  

### ISSUE THREAD

**Issue by elieffrig** [Project-MONAI/MONAI#4797]
**Describe the bug**
Hello, I'm using resnet10 and I noticed that when importing it directly from monai using monai.networks.nets.resnet10(), the images are downsampled twice more in the y and z directions than in the x direction at the first layer, as shown on the first screenshot below. However, when I get resnet10 by doing a copy paste of the source code (https://docs.monai.io/en/latest/_modules/monai/networks/nets/resnet.html) in my jupyter notebook, this doesn't happen (see the second screenshot). I'm using MONAI 0.8.0. I hope my explanations are clear enough, I can provide more details if needed. 

**To reproduce this bug:**

```
from torchinfo import summary
import monai
resnet = monai.networks.nets.resnet10(
            spatial_dims=3, 
            n_input_channels=1, 
           num_classes=256)
summary(resnet, [(1,1,32,32,32)], depth=2)
```

<img width="425" alt="monai_bug_import" src="https://user-images.githubusercontent.com/51292333/181786346-e8691b11-bc55-4070-b6a7-9a31c642ed9c.PNG">
<img width="454" alt="monai_bug_copy" src="https://user-images.githubusercontent.com/51292333/181786345-72dfb12e-5a86-47dc-bc08-1557a6974503.PNG">

**Comment by yiheng-wang-nv** [comment]
Hi @elieffrig , thanks for posting this ticket. It was a bug in monai 0.8, and not it has been fixed (see also in: https://github.com/Project-MONAI/MONAI/issues/3918). To avoid the issue, could you update the monai version?

**Comment by elieffrig** [comment]
I updated monai and it works now, thank you very much for your answer !
