### ISSUE TITLE
default behavior of `pixdim` in `Spacing`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4812]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/4807

<div type='discussions-op-text'>

<sup>Originally posted by **ChenglongWang** August  1, 2022</sup>
Recently, I noticed that the `pixdim` argument from the `Spacing` transform is inconsistent with other transforms.
For the `pixdim` in `Spacing` transform, `if providing a single number, will use it for the first dimension. items of the pixdim sequence map to the spatial dimensions of input image`. However, for the most of other transforms, such as `Resize`, `SpatialPad`, and `BorderPad`, single number argment will be automatically filled to the image size by using `fall_back_tuple` fn.
I'm wondering why `Spacing` transform is designed this way. Will this inconsistency lead to any improper usage?</div>

for example `pixdim=4.0` is currently interpreted as `pixdim=(4.0, 1.0, 1.0)` for 3d (defaulting to 1.0), this is a feature request to make it `pixdim=(4.0, 4.0, 4.0)` isotropic.

**Comment by a-parida12** [comment]
@wyli looks like this issue is still open and no one is working on it. I would like to put a PR

**Comment by wyli** [comment]
thanks, welcome your PR @a-parida12!
