### ISSUE TITLE
EnsureChannelFirst calls AddChannel which is deprecated

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#4822]
**Describe the bug**
Using `EnsureChannelFirst` gives the warning: `<class 'monai.transforms.utility.array.AddChannel'>: Class `AddChannel` has been deprecated since version 0.8. please use MetaTensor data type and monai.transforms.EnsureChannelFirst instead.` This is because `EnsureChannelFirst` calls `AddChannel` internally.

**Comment by KumoLiu** [comment]
Hi @rijobro,
Maybe we could simply ignore the warning in `EnsureChannelFirst ` like this:
```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    self.add_channel = AddChannel()
```
I'm not sure if it's a good way. Thanks.

**Comment by rijobro** [comment]
Although we could, I don't think that would be very good programming practice. If we're saying it's deprecated then we shouldn't be using it. `AddChannel` is very basic, it's essentially `x = x[None]`, so I think it's OK to just copy that implementation. Better yet would be to implement `AddChannel` in terms of `EnsureChannelFirst`, but I think that would be over-engineering a very simple problem.

**Comment by KumoLiu** [comment]
After offline discussion with @Nic-Ma, we think we can remove  `AddChannel` and  `AsChannelFirst` call from `EnsureChannelFirst ` which solves the problem of reporting warnings and will not affect us when we deprecated `AddChannel` and  `AsChannelFirst` in the future.

What do you think @rijobro @wyli ?

**Comment by wyli** [comment]
yes please help submit a PR @KumoLiu, addchannel is deprecated, which means the codebase itself shouldn't use the component , please also remove any other usage
