### ISSUE TITLE
DatasetSummary for non-segmentation tasks

### ISSUE THREAD

**Issue by NabJa** [Project-MONAI/MONAI#4824]
**Is your feature request related to a problem? Please describe.**
The DatasetSummary class computes the dataset statistics (e.g. mean pixel intensity, ...) based on the image **and** its label. However, there are many cases where this summary might be helpful without having a label. An example would be a simple image classification task. Here, I would want to use these statistics to normalize/process my images, without having a mask as a label.

**Describe the solution you'd like**
The DatasetSummary should allow me to set `label_key=None` to always compute all statistics without considering the label. Additionally it would be helpful to allow to add a function to select some foreground based on the image (like in transform.CropForeground).

**Describe alternatives you've considered**
It's possible to generate some arbitrary mask (e.g. where image > 0) and add it as label to the dataset. However, this is attached to unnecessary overhead. 

**Additional context**
None

**Comment by wyli** [comment]
thanks, this is now supported by the data analyzer https://github.com/Project-MONAI/MONAI/blob/fdb16acbf606a425c412fecaddcdd0c782925581/tests/test_auto3dseg.py#L327-L346
