### ISSUE TITLE
MetaTensor Needs `__str__` Method

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#4840]
**Is your feature request related to a problem? Please describe.**
When a `MetaTensor` is printed with `print` it produces its metadata information in addition to what a tensor would normally print. This is usually too verbose for just printing to screen, and differs from default behaviour from Pytorch. The design intent was to not require users to have to deal with MetaTensors, it's meant to be opt-in, but this change has a visible difference the unexpecting user would have to dig into to solve. 

**Describe the solution you'd like**
Add a `__str__` method to `MetaTensor` to preserve the printing behaviour of regular tensors but leave `__repr__` for those wanting larger outputs. This can be prototyped with:

```python
class MetaTensor1(monai.data.MetaTensor):
    def __str__(self):
        return str(self.as_tensor())
    
t=torch.rand(10)
print(t.min())  # expected
print(monai.data.MetaTensor(t).min())  # too verbose
print(MetaTensor1(t).min())  # as expected
```

**Describe alternatives you've considered**
The alternative to get default behaviour is `print(t.as_tensor())` but that is now forcing users to opt-in to MetaTensor and makes code non-portable, ie. won't work with regular Pytorch tensors if used somewhere without MONAI

**Additional context**
This [comment](https://stackoverflow.com/a/2626364/2788477) summarises usage of `__str__` and `__repr__`. I think this approach makes `__str__` readable and leaves `__repr__` unambiguous as it is now.

**Comment by wyli** [comment]
agreed, __str__ should be compact... the example the output of `print(t.min())` and `print(MetaTensor1(t).min())` are identical, is it possible to make it clear when it's a metatensor?

**Comment by ericspod** [comment]
In this case the type mentioned could be changed, the output is `tensor(0.0144)` so could be `MetaTensor(0.0144)` instead. `__str__` isn't necessary unambiguous though, `print(str("3"))` and `print(str(3))` for example while `print(repr("3"))` and `print(repr(3))` differ.

**Comment by wyli** [comment]
ok, that makes sense, then printing `tensor(0.0144)` looks fine in both cases. could you help submit a PR? I think the only relevant test case is here https://github.com/Project-MONAI/MONAI/blob/a9095d09d919e94c2c07aa74fc46c1e4f9530ecd/tests/test_meta_tensor.py#L425

**Comment by rijobro** [comment]
`MetaTensor(0.0144)` instead of `tensor(0.0144)` would be nice!

**Comment by wyli** [comment]
> 

it's possible to generate `MetaTensor(0.0144)` following the regular tensor's `__repr__`:
```py
class MetaTensor1(monai.data.MetaTensor):
    def __str__(self, *, tensor_contents=None):
        return torch._tensor_str._str(self, tensor_contents=tensor_contents)
```

code from 
https://github.com/pytorch/pytorch/blob/8a6c104ce9398815989317f208eae80ea2fe6ac1/torch/_tensor.py#L423

https://github.com/pytorch/pytorch/blob/8a6c104ce9398815989317f208eae80ea2fe6ac1/torch/_tensor_str.py#L358-L365
