### ISSUE TITLE
Add docstrings to MonaiAlgo class

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/MONAI#4845]
**Is your feature request related to a problem? Please describe.**
Add docstrings to MonaiAlgo class

**Describe the solution you'd like**
Detailed docstrings

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by wyli** [comment]
also we need one line for the module level readme https://github.com/Project-MONAI/MONAI/blob/dev/monai/README.md
