### ISSUE TITLE
Problem with Monai processing of image

### ISSUE THREAD

**Issue by Jawa1212** [Project-MONAI/MONAI#4849]
Hello. I am trying to use the code from: https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/brats_segmentation_3d.ipynb

Everything runs fine, until I try the following line:

val_data_example = val_ds[2]

I get a very long error which looks as follows:
--------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\transform.py:90, in apply_transform(transform, data, map_items, unpack_items, log_stats)

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\transform.py:54, in _apply_transform(transform, parameters, unpack_parameters)

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\io\dictionary.py:133, in __call__(self, data, reader)
    113 def __init__(
    114     self,
    115     keys: KeysCollection,
   (...)
    118     overwriting: bool = False,
    119 ) -> None:
    120     """
    121     Args:
    122         keys: keys of the corresponding items to be transformed.
    123             See also: :py:class:`monai.transforms.compose.MapTransform`
    124         loader: callable function to load data from expected source.
    125             typically, it's array level transform, for example: `LoadNifti`,
    126             `LoadPNG` and `LoadNumpy`, etc.
    127         meta_key_postfix: use `key_{postfix}` to store the metadata of the loaded data,
    128             default is `meta_dict`. The meta data is a dictionary object.
    129             For example, load Nifti file for `image`, store the metadata into `image_meta_dict`.
    130         overwriting: whether allow to overwrite existing meta data of same key.
    131             default is False, which will raise exception if encountering existing key.
    132 
--> 133     Raises:
    134         TypeError: When ``loader`` is not ``callable``.
    135         TypeError: When ``meta_key_postfix`` is not a ``str``.
    136 
    137     """
    138     super().__init__(keys)

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\io\array.py:245, in __call__(self, filename, reader)
    244 img = Image.open(name)
--> 245 data = np.asarray(img)
    246 if self.dtype:

RuntimeError: LoadImage cannot find a suitable reader for file: C:\Users\jawah\AppData\Local\Temp\tmpj7bzihni\Task01_BrainTumour\imagesTr\BRATS_035.nii.gz.
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.NumpyReader object at 0x000001FB9F5476A0>, <monai.data.image_reader.PILReader object at 0x000001FB9F5472B0>].

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\transform.py:90, in apply_transform(transform, data, map_items, unpack_items, log_stats)

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\transform.py:54, in _apply_transform(transform, parameters, unpack_parameters)

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\compose.py:173, in __call__(self, input_)
    147 class Compose(Randomizable, Transform):
    148     """
    149     ``Compose`` provides the ability to chain a series of calls together in a
    150     sequence. Each transform in the sequence must take a single argument and
    151     return a single value, so that the transforms can be called in a chain.
    152 
    153     ``Compose`` can be used in two ways:
    154 
    155     #. With a series of transforms that accept and return a single
    156        ndarray / tensor / tensor-like parameter.
    157     #. With a series of transforms that accept and return a dictionary that
    158        contains one or more parameters. Such transforms must have pass-through
    159        semantics; unused values in the dictionary must be copied to the return
    160        dictionary. It is required that the dictionary is copied between input
    161        and output of each transform.
    162 
    163     If some transform generates a list batch of data in the transform chain,
    164     every item in the list is still a dictionary, and all the following
    165     transforms will apply to every item of the list, for example:
    166 
    167     #. transformA normalizes the intensity of 'img' field in the dict data.
    168     #. transformB crops out a list batch of images on 'img' and 'seg' field.
    169        And constructs a list of dict data, other fields are copied::
    170 
    171             {                          [{                   {
    172                 'img': [1, 2],              'img': [1],         'img': [2],
--> 173                 'seg': [1, 2],              'seg': [1],         'seg': [2],
    174                 'extra': 123,    -->        'extra': 123,       'extra': 123,
    175                 'shape': 'CHWD'             'shape': 'CHWD'     'shape': 'CHWD'
    176             }                           },                  }]
    177 
    178     #. transformC then randomly rotates or flips 'img' and 'seg' fields of
    179        every dictionary item in the list.
    180 
    181     The composed transforms will be set the same global random seed if user called
    182     `set_determinism()`.
    183 
    184     When using the pass-through dictionary operation, you can make use of
    185     :class:`monai.transforms.adaptors.adaptor` to wrap transforms that don't conform
    186     to the requirements. This approach allows you to use transforms from
    187     otherwise incompatible libraries with minimal additional work.
    188 
    189     Note:
    190 
    191         In many cases, Compose is not the best way to create pre-processing
    192         pipelines. Pre-processing is often not a strictly sequential series of
    193         operations, and much of the complexity arises when a not-sequential
    194         set of functions must be called as if it were a sequence.
    195 
    196         Example: images and labels
    197         Images typically require some kind of normalisation that labels do not.
    198         Both are then typically augmented through the use of random rotations,
    199         flips, and deformations.
    200         Compose can be used with a series of transforms that take a dictionary
    201         that contains 'image' and 'label' entries. This might require wrapping
    202         `torchvision` transforms before passing them to compose.
    203         Alternatively, one can create a class with a `__call__` function that
    204         calls your pre-processing functions taking into account that not all of
    205         them are called on the labels.
    206     """
    208     def __init__(self, transforms: Optional[Union[Sequence[Callable], Callable]] = None) -> None:

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\transform.py:114, in apply_transform(transform, data, map_items, unpack_items, log_stats)

RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x000001FB9E75ACD0>

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Input In [64], in <cell line: 2>()
      1 # pick one image from DecathlonDataset to visualize and check the 4 channels
----> 2 val_data_example = val_ds[2]
      3 print(f"image shape: {val_data_example['image'].shape}")
      4 plt.figure("image", (24, 6))

File ~\anaconda3\envs\new1\lib\site-packages\monai\data\dataset.py:97, in __getitem__(self, index)
     74 class PersistentDataset(Dataset):
     75     """
     76     Persistent storage of pre-computed values to efficiently manage larger than memory dictionary format data,
     77     it can operate transforms for specific fields.  Results from the non-random transform components are computed
     78     when first used, and stored in the `cache_dir` for rapid retrieval on subsequent uses.
     79 
     80     For example, typical input data can be a list of dictionaries::
     81 
     82         [{                            {                            {
     83              'img': 'image1.nii.gz',      'img': 'image2.nii.gz',      'img': 'image3.nii.gz',
     84              'seg': 'label1.nii.gz',      'seg': 'label2.nii.gz',      'seg': 'label3.nii.gz',
     85              'extra': 123                 'extra': 456                 'extra': 789
     86          },                           },                           }]
     87 
     88     For a composite transform like
     89 
     90     .. code-block:: python
     91 
     92         [ LoadNiftid(keys=['image', 'label']),
     93           Orientationd(keys=['image', 'label'], axcodes='RAS'),
     94           ScaleIntensityRanged(keys=['image'], a_min=-57, a_max=164, b_min=0.0, b_max=1.0, clip=True),
     95           RandCropByPosNegLabeld(keys=['image', 'label'], label_key='label', spatial_size=(96, 96, 96),
     96                                  pos=1, neg=1, num_samples=4, image_key='image', image_threshold=0),
---> 97           ToTensord(keys=['image', 'label'])]
     98 
     99     Upon first use a filename based dataset will be processed by the transform for the
    100     [LoadNiftid, Orientationd, ScaleIntensityRanged] and the resulting tensor written to
    101     the `cache_dir` before applying the remaining random dependant transforms
    102     [RandCropByPosNegLabeld, ToTensord] elements for use in the analysis.
    103 
    104     Subsequent uses of a dataset directly read pre-processed results from `cache_dir`
    105     followed by applying the random dependant parts of transform processing.
    106 
    107     Note:
    108         The input data must be a list of file paths and will hash them as cache keys.
    109 
    110     """
    112     def __init__(
    113         self,
    114         data: Sequence,
   (...)
    117         hash_func: Callable[..., bytes] = pickle_hashing,
    118     ) -> None:
    119         """
    120         Args:
    121             data: input data file paths to load and transform to generate dataset for model.
   (...)
    131                 defaults to `monai.data.utils.pickle_hashing`.
    132         """

File ~\anaconda3\envs\new1\lib\site-packages\monai\data\dataset.py:821, in _transform(self, index)
    819 class ArrayDataset(Randomizable, _TorchDataset):
    820     """
--> 821     Dataset for segmentation and classification tasks based on array format input data and transforms.
    822     It ensures the same random seeds in the randomized transforms defined for image, segmentation and label.
    823     The `transform` can be :py:class:`monai.transforms.Compose` or any other callable object.
    824     For example:
    825     If train based on Nifti format images without metadata, all transforms can be composed::
    826 
    827         img_transform = Compose(
    828             [
    829                 LoadNifti(image_only=True),
    830                 AddChannel(),
    831                 RandAdjustContrast()
    832             ]
    833         )
    834         ArrayDataset(img_file_list, img_transform=img_transform)
    835 
    836     If training based on images and the metadata, the array transforms can not be composed
    837     because several transforms receives multiple parameters or return multiple values. Then Users need
    838     to define their own callable method to parse metadata from `LoadNifti` or set `affine` matrix
    839     to `Spacing` transform::
    840 
    841         class TestCompose(Compose):
    842             def __call__(self, input_):
    843                 img, metadata = self.transforms[0](input_)
    844                 img = self.transforms[1](img)
    845                 img, _, _ = self.transforms[2](img, metadata["affine"])
    846                 return self.transforms[3](img), metadata
    847         img_transform = TestCompose(
    848             [
    849                 LoadNifti(image_only=False),
    850                 AddChannel(),
    851                 Spacing(pixdim=(1.5, 1.5, 3.0)),
    852                 RandAdjustContrast()
    853             ]
    854         )
    855         ArrayDataset(img_file_list, img_transform=img_transform)
    856 
    857     Examples::
    858 
    859         >>> ds = ArrayDataset([1, 2, 3, 4], lambda x: x + 0.1)
    860         >>> print(ds[0])
    861         1.1
    862 
    863         >>> ds = ArrayDataset(img=[1, 2, 3, 4], seg=[5, 6, 7, 8])
    864         >>> print(ds[0])
    865         [1, 5]
    866 
    867     """
    869     def __init__(
    870         self,
    871         img: Sequence,
   (...)
    876         label_transform: Optional[Callable] = None,
    877     ) -> None:
    878         """
    879         Initializes the dataset with the filename lists. The transform `img_transform` is applied
    880         to the images and `seg_transform` to the segmentations.
   (...)
    889 
    890         """

File ~\anaconda3\envs\new1\lib\site-packages\monai\data\dataset.py:83, in _transform(self, index)
     74 class PersistentDataset(Dataset):
     75     """
     76     Persistent storage of pre-computed values to efficiently manage larger than memory dictionary format data,
     77     it can operate transforms for specific fields.  Results from the non-random transform components are computed
     78     when first used, and stored in the `cache_dir` for rapid retrieval on subsequent uses.
     79 
     80     For example, typical input data can be a list of dictionaries::
     81 
     82         [{                            {                            {
---> 83              'img': 'image1.nii.gz',      'img': 'image2.nii.gz',      'img': 'image3.nii.gz',
     84              'seg': 'label1.nii.gz',      'seg': 'label2.nii.gz',      'seg': 'label3.nii.gz',
     85              'extra': 123                 'extra': 456                 'extra': 789
     86          },                           },                           }]
     87 
     88     For a composite transform like
     89 
     90     .. code-block:: python
     91 
     92         [ LoadNiftid(keys=['image', 'label']),
     93           Orientationd(keys=['image', 'label'], axcodes='RAS'),
     94           ScaleIntensityRanged(keys=['image'], a_min=-57, a_max=164, b_min=0.0, b_max=1.0, clip=True),
     95           RandCropByPosNegLabeld(keys=['image', 'label'], label_key='label', spatial_size=(96, 96, 96),
     96                                  pos=1, neg=1, num_samples=4, image_key='image', image_threshold=0),
     97           ToTensord(keys=['image', 'label'])]
     98 
     99     Upon first use a filename based dataset will be processed by the transform for the
    100     [LoadNiftid, Orientationd, ScaleIntensityRanged] and the resulting tensor written to
    101     the `cache_dir` before applying the remaining random dependant transforms
    102     [RandCropByPosNegLabeld, ToTensord] elements for use in the analysis.
    103 
    104     Subsequent uses of a dataset directly read pre-processed results from `cache_dir`
    105     followed by applying the random dependant parts of transform processing.
    106 
    107     Note:
    108         The input data must be a list of file paths and will hash them as cache keys.
    109 
    110     """
    112     def __init__(
    113         self,
    114         data: Sequence,
   (...)
    117         hash_func: Callable[..., bytes] = pickle_hashing,
    118     ) -> None:
    119         """
    120         Args:
    121             data: input data file paths to load and transform to generate dataset for model.
   (...)
    131                 defaults to `monai.data.utils.pickle_hashing`.
    132         """

File ~\anaconda3\envs\new1\lib\site-packages\monai\transforms\transform.py:114, in apply_transform(transform, data, map_items, unpack_items, log_stats)

RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x000001FB9F547640>

Please help.

**Comment by Nic-Ma** [comment]
Hi @Jawa1212 ,

Thanks for your interest here.
As the error log shows, I think you need to install `nibabel` library to read the NIfTI file:
```
RuntimeError: LoadImage cannot find a suitable reader for file: C:\Users\jawah\AppData\Local\Temp\tmpj7bzihni\Task01_BrainTumour\imagesTr\BRATS_035.nii.gz.
Please install the reader libraries, see also the installation instructions:
https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
The current registered: [<monai.data.image_reader.NumpyReader object at 0x000001FB9F5476A0>, <monai.data.image_reader.PILReader object at 0x000001FB9F5472B0>].
```

Thanks.
