### ISSUE TITLE
Enhance Documentation of LoadImage to Clarify Image Transposition

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#4862]
**Is your feature request related to a problem? Please describe.**
Image data loaded from non-medical 2D formats like jpeg are transposed by the `ImageReader` class loading them, this is because these images are WH order and typical Pytorch ordering is HW. It's not clear to users that this is happening and can be really confused when using the loaders with natural images or photographs, or even MedNIST data as compared to loading with PIL directly.

**Describe the solution you'd like**
Documentation for `LoadImage` should be updated to state that this occurs for a number of non-medical specific file formats. 

**Describe alternatives you've considered**
Tilting my head to the side any time I visualise an image.

**Additional context**
I had forgotten this was intended behaviour and wasn't helped by documentation.

**Comment by Nic-Ma** [comment]
Thanks for raising this topic, OK, let me try to enhance the doc.

**Comment by wyli** [comment]
I just wanted to show an example of the indexing convention difference (swapped), for your reference:

```py
from PIL import Image
import itk

import monai

monai.apps.utils.download_url("https://monai.io/assets/img/MONAI-logo_color.png")
filename = "MONAI-logo_color.png"
im_pil = Image.open(filename).load()
im_itk = itk.imread(filename)

# check the indexing
for x in range(100):
    for y in range(31):
        assert tuple(im_itk[y, x]) == tuple(im_pil[x, y])

print(Image.__version__)  # 9.2.0
print(itk.__version__)  # 5.2.1
```
from monai's perspective, the design choice is to be consistent when using loadimage with different backend libraries.

**Comment by Nic-Ma** [comment]
Yes, and the "different backend libraries" represent the "medical specific" as @ericspod described.

Thanks.

**Comment by wyli** [comment]
not sure if it's medical specific, it's just the choice of row-major or column-major convention.
