### ISSUE TITLE
Vnet InputTransition ignores out_channel param

### ISSUE THREAD

**Issue by a-parida12** [Project-MONAI/MONAI#4896]
**Describe the bug**
The `InputTransition` class at `monai.networks.nets.vnet` takes in the parameter `out_channels` but ignores it in the implementation to the hard coded original value of 16. Check screenshots of the problem below.

**To Reproduce**
```python
from monai.networks.nets.vnet import InputTransition

in_tr = InputTransition(spatial_dims=3, in_channels=1, out_channel=32, act,= ("elu", {"inplace": True}),  bias=False)
inp = torch.zeros(1, 1,32, 32,32)
out = in_tr(inp)
print(out.shape[1])
```

**Expected behavior**
Expected behavior is to print `32` an not `16`.

**Screenshots**

![annotely_image](https://user-images.githubusercontent.com/23334003/184164330-eaf2a786-f8bf-41e6-b166-dac38342ea3e.jpeg)

**Comment by a-parida12** [comment]
I have added a patch to solved the issue and added a pull request

**Comment by linnabraham** [comment]
Seems like this issue is  not fixed. The VNet architecture is still hard coding the output channels as 16.  
Check line 257 [https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/vnet.py]( https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/vnet.py)
