### ISSUE TITLE
User can add new stats method in dataset summary / analyzer

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/MONAI#4905]
**Is your feature request related to a problem? Please describe.**
User may need customized functions so that they can have their own statistic metric in dataset_summary/data_analyzer.

**Describe the solution you'd like**
Reference link for a potential: 
https://github.com/Project-MONAI/MONAI/pull/4765#discussion_r943427586

**Describe alternatives you've considered**

**Additional context**

**Comment by wyli** [comment]
addressed in https://github.com/Project-MONAI/MONAI/blob/5beeda587d59c931eef45368ca9825079d1cc3da/monai/auto3dseg/seg_summarizer.py#L165-L166
