### ISSUE TITLE
remove APIs that are marked deprecated since v0.6 and v0.7?

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4909]
**Is your feature request related to a problem? Please describe.**
some APIs such as
https://github.com/Project-MONAI/MONAI/blob/535c6f1fc8767c09a21dba2464ca687f23c85154/monai/networks/blocks/convolutions.py#L101

https://github.com/Project-MONAI/MONAI/blob/535c6f1fc8767c09a21dba2464ca687f23c85154/monai/transforms/post/dictionary.py#L137-L154
are deprecated since version 0.6 and 0.7, they (and their corresonding tests) could be removed.

**Comment by Nic-Ma** [comment]
Thanks for raising the request.
Let me try to make a PR for it.

Thanks.
