### ISSUE TITLE
Make the class name of the IoU metric consistent with other metrics

### ISSUE THREAD

**Issue by binliunls** [Project-MONAI/MONAI#4910]
**Is your feature request related to a problem? Please describe.**
The class name of IoU metrics is "MeanIoU", which is not consistent with other metrics, like the [dice metric](https://github.com/Project-MONAI/MONAI/blob/535c6f1fc8767c09a21dba2464ca687f23c85154/monai/metrics/meandice.py#L22).  And it is similar to a metric handler, like the [mean dice handler](https://github.com/Project-MONAI/MONAI/blob/535c6f1fc8767c09a21dba2464ca687f23c85154/monai/handlers/mean_dice.py#L19). This may make users confuse about the IoU handler and metric.

**Describe the solution you'd like**

- [ ] Change the class name of the iou metric to "IoUMetric"
- [ ] Add a "mean_iou.py" file to the handler folder, in which an IoU handler named "MeanIoU" will be implemented.

@Nic-Ma @wyli Do you think if it's ok to change like this?

**Comment by wyli** [comment]
thanks, I'm fine with MeanIoU or IoUMetric, if there's any renaming please make sure it's backwards compatible.

**Comment by binliunls** [comment]
@Nic-Ma  In order to maintain a backwards compatible code, I think we shouldn't change the metric part of IoU and just add a handler of IoU with another name. How do you think about this?
Thanks.

**Comment by Nic-Ma** [comment]
Hi @binliunls ,

Current metric name of IoU is not consistent with other metrics, I think we should correct it instead of adding additional wrong name.. It's just added in 0.9.1, I suppose not many users. Please change the name with `deprecated` API.

Thanks.
