### ISSUE TITLE
Compute federated data statistics

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/MONAI#4923]
**Is your feature request related to a problem? Please describe.**
Allow the computation of summary data statistics at each client.

**Describe the solution you'd like**

- Add a function to compute data stats summaries to ClientAlgo/MonaiAlgo.
- Should work with MONAI bundle

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Nic-Ma** [comment]
What would the `data stats summaries` look like?

Thanks.

**Comment by wyli** [comment]
https://github.com/Project-MONAI/MONAI/pull/5240
