### ISSUE TITLE
mypy warning: tests/__init__.py:34: error: Cannot assign to a method

### ISSUE THREAD

**Issue by hjmjohnson** [Project-MONAI/MONAI#494]
**Describe the bug**
mypy static checker provides warning:

`tests/__init__.py:34: error: Cannot assign to a method`

**To Reproduce**
1. Modify setup.cfg and enable error checking for `tests/__init__.py`
2. `MYPYPATH=$(pwd)/monai mypy $(pwd)`

**Expected behavior**
No warnings produced.

**Comment by hjmjohnson** [comment]
@benjamin-gorman Could you try to address this warning?

**Comment by benjamin-gorman** [comment]
### Solutions

```python
setattr(unittest.case._AssertWarnsContext, "__enter__", _enter_pr_4800)
```

```python
unittest.case._AssertWarnsContext.__enter__ = _enter_pr_4800  # type: ignore[assignment]
```

### Context

> I prefer setattr over using # type: ignore. Mypy won't complain about it. This is something we could discuss in the common issues section in the docs.

https://github.com/python/mypy/issues/2427#issuecomment-384229898

> The has been no progress recently. The workarounds discussed above (setattr or # type: ignore) are still the recommended ways to deal with this.

https://github.com/python/mypy/issues/2427#issuecomment-480263443

### Progression of _enter_pr_4800

- Present in [master](https://github.com/python/cpython/blob/master/Lib/unittest/case.py#L252), [3.7](https://github.com/python/cpython/blob/3.7/Lib/unittest/case.py#L227), [3.8](https://github.com/python/cpython/blob/3.8/Lib/unittest/case.py#L251)
- Missing from [3.5](https://github.com/python/cpython/blob/3.5/Lib/unittest/case.py#L227), [3.6](https://github.com/python/cpython/blob/3.6/Lib/unittest/case.py#L227), [3.9](https://github.com/python/cpython/blob/3.9/Lib/unittest/case.py#L252)

### Alternatively

There is the [typing.Protocol fix](https://github.com/python/mypy/issues/708#issuecomment-667989040) but that would require a `.pyi` file and seems overkill.

**Comment by wyli** [comment]
the workaround is well documented https://github.com/Project-MONAI/MONAI/blob/bbc2da59c26a5409c1fec219e112a48495633bbc/tests/__init__.py#L32-L36
closing this issue
