### ISSUE TITLE
Add option to set determinism with bundle configs

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/MONAI#4942]
**Is your feature request related to a problem? Please describe.**
There should be a configuration option to enable deterministic training with monai bundle. Currently, a user has to add python code in the "[training](https://github.com/Project-MONAI/model-zoo/blob/dd0b54642c1e6af62d3ecf6cc845e2f7ca281125/models/spleen_ct_segmentation/configs/train.json#L284)" portion of the config:
```
    "training": [
        "$monai.utils.set_determinism(seed=123)",
        "$setattr(torch.backends.cudnn, 'benchmark', True)",
        "$@train#trainer.run()"
    ]
```
This can be difficult to use in security-constrained environments such as in federated learning, where one might want to disable the python code execution in the bundle.

**Describe the solution you'd like**
There should be an option to set the deterministic behavior using configuration style options, e.g., the below to achieve the same behavior as above:
```
  "determinism": {
    "random_seed": 123,
    "benchmark": True
  }
```

**Describe alternatives you've considered**
MonaiAlgo for executing FL training does not run the "training" section in the config. Therefore the code there is not being executed. One can achieve determinism by using the "_required_" option for the SupervisedTrainer but this will not work if python code is disabled.

**Additional context**
Especially important feature to support FL.

**Comment by Nic-Ma** [comment]
Hi @holgerroth ,

Thanks for raising the question.
Actually, I think it's hard to execute the `set_determinism()` function without python expression, unless we hard-code some logic in the bundle `ConfigParser` to call it internally, which we are trying to avoid.
Now we don't suppose any config logic in the JSON, totally use the JSON content to define the whole logic.
For the FL program, if we can't execute python expressions in the config, can we call `set_determinism()` somewhere in the FL program before parsing the bundle?
@wyli What do you think?

**Comment by wyli** [comment]
Yes, perhaps we have this hardcoded in monaialgo for FL, and later extending this to the primary bundle parser if we receive feature requests? cc @Nic-Ma

**Comment by holgerroth** [comment]
I feel MonaiAlgo is the wrong place for handling this. Determinism is a general MONAI feature that is used by many bundles. Why not have some purpose logic for this in the config parser?
________________________________

**Comment by wyli** [comment]
currently the config parser connects the structured configs and the python-based components. It is quite generic and decoupled from the underlying machine learning APIs. So adding numpy/torch specific code logic to it doesn't make sense to me... 

however, we can define some system default pre-set config json, and the user can choose to load it as system-wide predefined commands, and override these default keys in their own config files.

```json
"rng_seed": null,
"deterministic": [
    "$monai.utils.set_determinism(seed=@rng_seed)",
    "..."
]
```

the pre-set configs could be hosted in monai's data storage and requires checksum matching before loading/running

**Comment by wyli** [comment]
maybe one valid feature request is to create two types of permissions for the `run_eval` flag, https://github.com/Project-MONAI/MONAI/blob/1941283b1862e3f578ccfeb2bdfa864171125029/monai/bundle/config_item.py#L318
1. whether to eval any user-provided command strings
2. whether to eval a set of predefined command strings from trusted sources

so that when option 1 is disabled at a system level, the user can still have the flexibility to use the 2nd option to run some predefined commonly used commands.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Interesting idea, need further step to gather some predefined expressions?

Thanks.

**Comment by holgerroth** [comment]
> "determinism": {
>     "random_seed": 123,
>     "benchmark": True
>   }

Exactly, adding something like this to the config would be independent of the underlying implementation. There's no dependency on numpy/pytorch:
```
  "determinism": {
    "random_seed": 123,
    "benchmark": True
  }
```

**Comment by holgerroth** [comment]
> currently the config parser connects the structured configs and the python-based components. It is quite generic and decoupled from the underlying machine learning APIs. So adding numpy/torch specific code logic to it doesn't make sense to me...

Exactly, adding something like this to the config would be independent of the underlying implementation. There's no dependency on numpy/pytorch:

  "determinism": {
    "random_seed": 123,
    "benchmark": True
  }

**Comment by Nic-Ma** [comment]
Hi @holgerroth ,

Based on the latest comment from @wyli , I think he means a different proposal: "`eval` a set of predefined command strings from trusted sources".
@wyli Or maybe I misunderstood your idea?

Thanks.
