### ISSUE TITLE
Change the value of guidance in deepedit, the network output does not change

### ISSUE THREAD

**Issue by wojiazaiyugang** [Project-MONAI/MONAI#4966]
**Describe the bug**
run deepedit's tutorial 
https://github.com/Project-MONAI/tutorials/blob/main/deepedit/ignite/infoANDinference.ipynb
Change the value of guidance in deepedit, the network output does not change
![image](https://user-images.githubusercontent.com/14771322/186088885-f445ea56-da09-4eeb-8a24-072d9dea3ee6.png)

It was found that it was abnormal when the data of clicks was taken from the transform of **AddGuidanceFromPointsDeepEditd**

**To Reproduce**
1. run deepedit's tutorial，record network output
![image](https://user-images.githubusercontent.com/14771322/186089036-b5c0dcff-cf6e-4f70-9fb0-550ace6fde3f.png)
2. Change the value of guidance to whatever
3. rerun deepedit's tutorial，the network output does not change

**Expected behavior**

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**

**Comment by SachidanandAlle** [comment]
This needs a change in tutorial page.. not in transform..
