### ISSUE TITLE
Add SwinUNETR to the Auto3dseg configuration

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/MONAI#4983]
Description
The ticket to add SwinUNETR as one of the backbone for auto3dseg pipeline. 

Status
Draft ready, Task09 Spleen successful. 
To validate performance and test on MRI dataset as well. 

Progress:

- [x] Build the SwinUNETR bundle for hybrid programming, including config files, scripts and configurator file.
- [x] Test the pipeline using Task09 Spleen dataset with training/validation/inference.
- [x] Test the pipleline with Task05 Prostate dataset with same process. 
- [x] Format checks.
- [x] Test multi gpu training
- [x] Double check whether the configurator can generate correct YAML config file according to SwinUENTR model specification, (e.g., the image dimension will be different from other models with variant datasets)

**Comment by mingxin-zheng** [comment]
@tangy5 I changed status from to-do to done. Thanks!

**Comment by mingxin-zheng** [comment]
@tangy5 I will close this ticket and change status to done. Thanks!
