### ISSUE TITLE
Sobel gradient calculation transform

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#4997]
HoVerNet losses requires calculation of numerical gradient of HoVerMaps in horizontal and vertical direction. This can be achieved by a Sobel kernel. skimage implementation uses 3x3 Sobel kernel but this pipeline requires a 5x5 kernel. Thus having a Sobel filter to calculate gradients with a flexible kernel size would be very helpful.

**Comment by wyli** [comment]
there's a relevant transform https://github.com/Project-MONAI/MONAI/blob/99b9dd7cf0667113e56f0dd90d40699115048d59/monai/transforms/post/array.py#L560 and utility https://github.com/Project-MONAI/MONAI/blob/99b9dd7cf0667113e56f0dd90d40699115048d59/monai/networks/layers/simplelayers.py#L245

**Comment by YipengHu** [comment]
minor: using separated 1d kernels should make it more efficient, [1.,.0,-1.]

**Comment by drbeh** [comment]
> minor: using separated 1d kernels should make it more efficient, [1.,.0,-1.]

Hi @YipengHu, can you elaborate on this? How do you go from applying 1D kernel of [1, 0, -1] to get equivalent result of applying 2D kernel of [[1, 0, -1], [2, 0, -2], [1, 0, -1]]?

**Comment by YipengHu** [comment]
> > minor: using separated 1d kernels should make it more efficient, [1.,.0,-1.]
> 
> Hi @YipengHu, can you elaborate on this? How do you go from applying 1D kernel of [1, 0, -1] to get equivalent result of applying 2D kernel of [[1, 0, -1], [2, 0, -2], [1, 0, -1]]?

Just apply the convolution twice :)
if K = [1,0,-1] * [1,0,-1]^T, then use convolution associativity: X*K = X * ( [1,0,-1] * [1,0,-1]^T) = X * [1,0,-1] * [1,0,-1]^T
* being conolution operator; ^T being transpose
(I think there is a constant, but omittable, term for the exact sobel operator)
Similar to separable Gaussian filtering commonly implemented in most numerical packages, e.g.: Sec 3.1 in https://medium.com/jun94-devpblog/cv-2-gaussian-and-median-filter-separable-2d-filter-2d11ee022c66

**Comment by drbeh** [comment]
> > > minor: using separated 1d kernels should make it more efficient, [1.,.0,-1.]
> > 
> > 
> > Hi @YipengHu, can you elaborate on this? How do you go from applying 1D kernel of [1, 0, -1] to get equivalent result of applying 2D kernel of [[1, 0, -1], [2, 0, -2], [1, 0, -1]]?
> 
> Just apply the convolution twice :) if K = [1,0,-1] * [1,0,-1]^T, then use convolution associativity: X*K = X * ( [1,0,-1] * [1,0,-1]^T) = X * [1,0,-1] * [1,0,-1]^T
> 
> * being conolution operator; ^T being transpose
>   (I think there is a constant, but omittable, term for the exact sobel operator)
>   Similar to separable Gaussian filtering commonly implemented in most numerical packages, e.g.: Sec 3.1 in https://medium.com/jun94-devpblog/cv-2-gaussian-and-median-filter-separable-2d-filter-2d11ee022c66

@YipengHu, that's right for separable Gaussian filtering but Sobel kernels, I believe, are essentially 2D. From the example, I did't get how we can derive a Sobel kernel as 
```
[1,0,-1]^T * [1,0,-1] =  [[1, 0, -1], [0, 0, 0], [-1, 0, 1]]
```
which is not a Sobel kernel.

**Comment by wyli** [comment]
I think the key idea is that sobel kernel is separable, we can use https://github.com/Project-MONAI/MONAI/blob/99b9dd7cf0667113e56f0dd90d40699115048d59/monai/networks/layers/simplelayers.py#L200 to accelerate the transform. What we implemented is a kind of generalized version for larger kernel sizes, the actual speed up needs to be checked against the kernel size.

**Comment by YipengHu** [comment]
@drbeh yup, sobel should be separable, https://en.wikipedia.org/wiki/Sobel_operator

For the purpose of computing/approximating gradient, sobel kernel is one of many choices. Here, the differenciating [1,0,-1]^T and [1,0,-1] should be sufficient, without the [1,2,1] and [1,2,1]^T, the latter two of which only have smoothing effect.
