### ISSUE TITLE
Unable to Perform Inverse Transform when ToTensord is applied

### ISSUE THREAD

**Issue by Febrio** [Project-MONAI/MONAI#5004]
**Describe the bug**

Unable to perform inverse dictionary transforms when:
 - MONAI version is 0.9.1
 - ToTensorD is applied at the end of Compose

**To Reproduce**
Code to reproduce the behavior:
1. Define a compose transforms such as the following
```python

import os
import monai
import torch
import numpy as np
import pandas as pd
from monai.transforms import  DivisiblePadD, AddChannelD, LoadImageD, ToTensorD, OrientationD, ScaleIntensityD

#Define simple transforms 
keys = 'image'
transform_ = monai.transforms.Compose(( 
                            LoadImageD(keys),
                            AddChannelD(keys),
                            ScaleIntensityD(keys),
                            DivisiblePadD(keys, k=32),
                            OrientationD(keys, axcodes='RAI'),
                            ToTensorD(keys),  ))  

img_ = transform_({'image': img_path[0]}) # Please note I used an image from the Automated Cardiac Diagnosis challenge (ACDC) dataset

transform_.inverse(img_)
```
2. Should receive an error, please go under Screenshots section of this report and see  **_Error location and message_**

**Expected behavior**
Able to perform inverse transform without any error as ToTensord is an invertible transform

**Screenshots**

**_Error location and message_**
![image](https://user-images.githubusercontent.com/8273168/186830683-82615765-f386-42db-872e-01c04fdb0c4d.png)

**_Other Odd behaviour_**

When ToTensord transform is applied, "applied_operations" attribute doesn't exist within the data that you want to inverse. See below screenshot.

![image](https://user-images.githubusercontent.com/8273168/186835207-9c3b12b2-266c-41e3-81eb-6aa71af66472.png)

"applied_operations" attribute exists when ToTensorD is not applied to the transform (see below screenshot)
![image](https://user-images.githubusercontent.com/8273168/186834917-b3bd89d3-7303-43e4-93c1-338559fc1628.png)

**Environment**

Obtained environment after performing
python -c 'import monai; monai.config.print_debug_info()'

================================
Printing MONAI config...
================================
MONAI version: 0.9.1
Numpy version: 1.23.2
Pytorch version: 1.12.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 356d2d2f41b473f588899d705bbc682308cee52c
MONAI __file__: /datasets/work/hb-mrigrt/work/projects/2022-08-10_MirorrNetRegistration/venv_2/lib/python3.9/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 4.0.1
scikit-image version: 0.19.3
Pillow version: 9.2.0
Tensorboard version: 2.9.1
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.64.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.9.1
pandas version: 1.4.3
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.
```

```

**Comment by wyli** [comment]
thanks for reporting, this is addressed recently and a patch (https://github.com/Project-MONAI/MONAI/pull/4874) will be available in the upcoming release.
