### ISSUE TITLE
set `image_only=True` in `LoadImaged`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#5007]
**Is your feature request related to a problem? Please describe.**
Since 0.9.1, we recommend that users use `MataTensor`, which will save the meta information in metatensor by default. The default value of `image_only` in `LoadImage` is False, which will return image and header dict. 
https://github.com/Project-MONAI/MONAI/blob/09993fa8cd6066493afe48a952103402c6050f0b/monai/transforms/io/dictionary.py#L79
For some transforms that have deprecated the meta_dict which meta information in meta_dict will not be updated in time. Such as `Spacingd`
https://github.com/Project-MONAI/MONAI/blob/09993fa8cd6066493afe48a952103402c6050f0b/monai/transforms/spatial/dictionary.py#L326-L327

**Describe the solution you'd like**
Set `image_only=True` in `LoadImaged` and `LoadImage`

**Comment by rijobro** [comment]
I think we'd definitely like to see this happen, we didn't do this initially as there may be lots of other places in the codebase that assume load image to return the meta data, or at least to return multiple objects. This sort of thing would be trickier to pick up on:
```
image = LoadImage()(fname)[0]
```
With the old default, `[0]` would return just the image and omit the metadata. But if the default were changed then `[0]` would slice the image taking the 0th element of the 0th dimension. This wouldn't cause an error, so would be hard to spot but would clearly be erroneous as we'd be throwing away parts of the image.

It would be hard to find and replace all instances of this in our own code base and tutorials, but we have no way of correcting code that users have written.

**Comment by wyli** [comment]
changing the default will avoid this confusion https://github.com/Project-MONAI/MONAI/issues/5097.
