### ISSUE TITLE
clear temporary files after running run_tests.sh

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#501]
**Is your feature request related to a problem? Please describe.**
running `run_tests.sh` may generate cache files in the folder such as .mypy_cache, .pytype.

**Describe the solution you'd like**
one option is to offer a `--clean` option in `run_tests.sh` to remove the files if they exist

**Describe alternatives you've considered**
N/A

**Comment by fabrizzioalco** [comment]
Is this solved? I would like to contribute

**Comment by wyli** [comment]
@fabrizzioalco I don't think it's solved, please go ahead,

**Comment by fabrizzioalco** [comment]
Can someone help me run the project? I can't see where in the Docs says how to do it

**Comment by Nic-Ma** [comment]
Hi @fabrizzioalco ,

You can try to run all the tests from root folder:
`bash run_tests.sh --coverage`

You may need to pip install some dependency.

Thanks.

**Comment by fabrizzioalco** [comment]
Thanks a lot!

**Comment by fabrizzioalco** [comment]
However, trying to run the project its giving me this error: 
File "<string>", line 1, in <module>
  File "monai/__init__.py", line 16, in <module>
    from .utils.module import load_submodules
  File "monai/utils/__init__.py", line 15, in <module>
    from .misc import *
  File "monai/utils/misc.py", line 22
    def zip_with(op, *vals, mapfunc=map):
                                                         ^
SyntaxError: invalid syntax

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help share more information about this issue as you set the pytype env?
Thanks.

**Comment by fabrizzioalco** [comment]
Sure. 
When i clone the repo i run pip3 install -r requirements.txt and then run the tests with ./runtests.sh  --coverage to see which files are created, throw me that error of typos. Is that what you were looking for>

**Comment by wyli** [comment]
> Sure.
> When i clone the repo i run pip3 install -r requirements.txt and then run the tests with ./runtests.sh --coverage to see which files are created, throw me that error of typos. Is that what you were looking for>

thanks, I couldn't replicate this issue for now, might be a bug, could you create an issue with the bug report template? https://github.com/Project-MONAI/MONAI/issues/new?assignees=&labels=&template=bug_report.md&title=
