### ISSUE TITLE
Add Hybrid Segmentation Loss 

### ISSUE THREAD

**Issue by yashika-git** [Project-MONAI/MONAI#5023]
I was trying to implement UNet++ (issue #896 ). 
In the UNet++ paper, authors suggest using hybrid segmentation loss:
```

We then define a hybrid segmentation loss consisting of pixelwise cross-entropy loss and soft dice-coefficient loss for each
semantic scale. The hybrid loss may take advantages of what both loss functions have to offer: smooth gradient and handling
of class imbalance.

```
Equation 2 in [this](https://arxiv.org/pdf/1912.05074.pdf ) paper, describes the Mathematical formula to calculate the loss.

Can this loss be implemented in MONAI?

**Additional context**
<img width="286" alt="image" src="https://user-images.githubusercontent.com/40869641/187203028-6bcb33af-f991-43e7-b4e8-2d36ef6ecc14.png">

**Comment by yashika-git** [comment]
@Nic-Ma, Shall this loss be added, will it be helpful?
Thank you

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

I think it would be a nice enhancement for MONAI, welcome your contribution.
@wyli Do you have any concern?

Thanks.

**Comment by yashika-git** [comment]
Thank you, I'll try adding this.

**Comment by myron** [comment]
is this hybrid loss the same as  Dice + CrossEntropy loss?  https://github.com/Project-MONAI/MONAI/blob/dev/monai/losses/dice.py#L609

**Comment by yashika-git** [comment]
@myron, Yes, it seems to be the same.
I'll close the issue.
