### ISSUE TITLE
Make HoVerNet  work SuperviseTrainer

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5028]
Using `SupervisedTrainer` for HoVerNet pipeline training requires a `prepare_batch` to prepare data differently than how it is being prepared in `default_prepare_batch` since HoVerNet target includes three different tensors.

**Comment by Nic-Ma** [comment]
Pending on @KumoLiu to verify whether the existing `ExtraPrepareBatch` can satisfy the requirement.
If not, I will try to implement a new subclass.

Thanks.

**Comment by drbeh** [comment]
Hi @Nic-Ma @KumoLiu, may I know what is the status of this? Is it in progress or you have found another way to train? Thanks

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

The draft PR is here: https://github.com/Project-MONAI/tutorials/pull/999.

Thanks.

**Comment by drbeh** [comment]
@KumoLiu has already implemented it in the tutorial and will port it to the monai core, maybe monai/apps/pathology.
