### ISSUE TITLE
Doubt in BasicUNet documentation

### ISSUE THREAD

**Issue by yashika-git** [Project-MONAI/MONAI#5046]
Should cat_chns represent "number of channels from the encoder" instead of "number of channels from the decoder" since the encoder channels are concatenated with the upsampled decoder channels?

https://github.com/Project-MONAI/MONAI/blob/f49cc963179d1ca678f6ca2d05918157959bd9b3/monai/networks/nets/basic_unet.py#L127

**Comment by yashika-git** [comment]
Hi @Nic-Ma, 
Could you please help with it?
Thanks

**Comment by KumoLiu** [comment]
Hi @yashika-git, it seems you are right, I will update the docstring as soon as possible.
