### ISSUE TITLE
ContrastiveLoss with dynamic batchsize

### ISSUE THREAD

**Issue by a-parida12** [Project-MONAI/MONAI#5070]
**Is your feature request related to a problem? Please describe.**
When we instantiate an instance of type class `ContrastiveLoss` we need to pass in the parameter for `batch_size`. This assumes that the batch size remains constant all through the training(which is not always the case). 

**Describe the solution you'd like**
As we know and have fixed in the [docs](https://docs.monai.io/en/latest/losses.html#monai.losses.ContrastiveLoss) that the forward accepts inputs of shape `B[F]`, why not pick up the Batch size dynamically in the forward. Is there a reason why it is not designed in that fashion?

I would be happy to put a pull request if it is okay.

**Comment by finalelement** [comment]
@a-parida12 Please go ahead and send a PR, I feel we should make the dynamic part optional so that we don't break existing code for other users and keep the default dynamic_batch_size=False

We need insights from @wyli if it's okay for the optional idea :)

**Comment by a-parida12** [comment]
Thanks, @finalelement! I thought the majority of the losses from PyTorch don't require that the batch size be known and fixed so extending that to this too. But you are right we need to be backward compatible too.  I will wait for @wyli 's input and then begin the PR.

**Comment by a-parida12** [comment]
Also tagging this discussion for the completeness of my motivation https://github.com/Project-MONAI/tutorials/discussions/624

**Comment by wyli** [comment]
yes please go ahead, would be great to automatically infer the batch size whenever possible.
