### ISSUE TITLE
About SwinUnetr PatchMerging

### ISSUE THREAD

**Issue by good-demo** [Project-MONAI/MONAI#5076]
Can I use official code to pretrian 2d images(like imagenet's weight) and finetune in MONAI's SwinUnetr.  I find  in MONAI's swintransformer net the 4th layer have PatchMerging but in official code is not have.

 Official:downsample=PatchMerging if (i_layer < self.num_layers - 1) else None
MONAI: downsample=down_sample_mod
down_sample_mod = look_up_option(downsample, MERGING_MODE) if isinstance(downsample, str) else downsample

**Comment by tangy5** [comment]
Hi @good-demo , the SwinUNETR model is originally trained with 3D images with [96, 96,96] volume. The current MONAI implementation has the 2D option. You can pre-train your own swin-transformer, but if the weight variables key are different between "official code" and SwinUNETR's swin-transformer, it will cause error when loading weights. You can write another load_from function to load part of the pre-trained weights as an option if this is the case. Thanks.
