### ISSUE TITLE
Add Post-processing Transforms in MONAI for Nuclei Prediction 

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#5100]
**Description**
It is an overall PR created to track the progress of adding post-processing transforms in MONAI. 

**Describe the solution you'd like**
Several post-processing transforms need to be added to MONAI which I simply divided into two categories.
- Common transforms which can be integrated into MONAI core
- HoVerNet-specific transforms which can be integrated into [apps/pathology/transforms](https://github.com/Project-MONAI/MONAI/tree/dev/monai/apps/pathology/transforms)

**Tasks**

Common transforms:
- [x] Get a bounding box  [`BoundingRect`](https://github.com/Project-MONAI/MONAI/blob/b36ba6c84f8f56c08e80b16acace9d466b70078a/monai/transforms/croppad/array.py#L1343)
- [x] Remove small objects [`RemoveSmallObjects`](https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/post/array.py#L342)
- [x] #5015
- [x] #5310
- [x] #4181

HoVerNet-specific transforms:
- [x] #5178
- [x] #5179
- [x] #5180

**Additional context**
There is already a draft implementation in the tutorial repo refer to https://github.com/Project-MONAI/tutorials/pull/890.
Related PR: https://github.com/Project-MONAI/MONAI/issues/4181
Related Issues: https://github.com/Project-MONAI/MONAI/issues/4180

cc @wyli @Nic-Ma @drbeh @JHancox @shaneahmed

**Comment by JHancox** [comment]
I think @drbeh may have already tackled the last Common Transform ("Calculate the distance from sequence...")

The first 2 HNet-specific Transforms are to do with representing contours. There may be a different representation that we would prefer to adopt. This one just provides compatibility with the existing OpenCV-based outputs (which are better, IMHO, than SciPy's)

**Comment by drbeh** [comment]
I'm closing as all the post-processing added. Optimizing the efficiency of these transforms are very important and should be planned for the future releases.
