### ISSUE TITLE
issue to compute Conditional Random Field (CRF) from monai.networks.blocks

### ISSUE THREAD

**Issue by antoniocandito** [Project-MONAI/MONAI#5110]
**Describe the bug**
getting the following error from computing monai CRF
OptionalImportError: import monai._C (No module named 'monai._C').

**To Reproduce**
1. Go to https://gist.github.com/masadcv/84f1bc9f505056ea8f4290d14a002d2a

**Comment by wyli** [comment]
please use this guide https://docs.monai.io/en/latest/installation.html#option-2-editable-installation, if something doesn't work, please open another bug report following the template to provide more details.

**Comment by antoniocandito** [comment]
tried to install Monai all the way possible but still get this error...

**Comment by anisaaaaaaaaaaaa** [comment]
i got the same error while computing monai CRF
