### ISSUE TITLE
Problem with data augmentation in spleen example notebook

### ISSUE THREAD

**Issue by neshang** [Project-MONAI/MONAI#512]
**Describe the bug**
I was trying out the `spleen_segmentation_3d.ipynb` and encountered problem with data transformation. In the 'Setup transforms for training and validation' section, the line `Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), interp_order=(3, 0), mode='nearest'),` keeps causing error. After I checked the documentation, it seems like the argument `interp_order`
 should be a string rather than a tuple of int. It seems like this is the case in other example notebooks as well, was there a code base change that leads to this problem or is there anything I missed?

**To Reproduce**
Run through the notebook.

**Expected behavior**
It should run without any error.
**Environment (please complete the following information):**
 - OS
 - Python version
 - MONAI version [e.g. git commit hash]: 0.1.0
 - CUDA/cuDNN version
 - GPU models and configuration

**Comment by Nic-Ma** [comment]
Hi @neshang ,

Thanks very much for your bug report.
We just updated the API of Spacing yesterday and didn't update the examples.
I already submitted a PR #513  to update it.
Thanks.

**Comment by neshang** [comment]
Thank you @Nic-Ma  :)
