### ISSUE TITLE
Allow keeping original spatial size in RandAffine transformation

### ISSUE THREAD

**Issue by elitap** [Project-MONAI/MONAI#517]
Wouldn't it be nice to have the option to keep the spatial size of the input image (saptial_size=None) when applying a RandAffine transformation. Like that the RandAffine could be used to subsitute the chaining of RandRotated and RandZoom, which is slower and there is a quality loss because of the  multiple interpolations. To me that seems to be a often required feature before, applying random crops. 

Would just be great to have a faster preproccessing pipeline by using RandAffine instead of RandRotated and RandZoom.

As soon as I find some time I look into it, but maybe its also a stupid idea :-)

**Comment by wyli** [comment]
thanks for the nice suggestion, I'll look into this as well.

just wanted to mention that the use case of "RandRotated+RandZoom+RandomCropping" is partly covered by RandAffine. could set spatial_size as the final cropped size in this case.

multiple random crops from one iteration of RadnRotated+RandZoom is not implemented yet.

**Comment by elitap** [comment]
Thank you already for considering the feature. In my case I would need the RandCropByPosNegLabeld after rotation and zoom, so keeping the original spatial size after the RandAffine would add flexibility to allow that.

Thanks and really, really great work, love it so far :-)
