### ISSUE TITLE
FlexibleUNet is_pad

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#5187]
This argument isn't obvious to me, and I don't find the docstrings clear enough to understand what's going on. I think the English grammar isn't quite correct (happy to help there if necessary). I would appreciate further explanation here:

https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/flexible_unet.py#L243-L244

**Comment by wyli** [comment]
please also remove this type of docstrings: https://github.com/Project-MONAI/MONAI/blob/b36ba6c84f8f56c08e80b16acace9d466b70078a/monai/networks/nets/flexible_unet.py#L220-L221, use a ticket instead.
