### ISSUE TITLE
Dataset for NuCLS

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5191]
The NuCLS dataset contains over 220,000 labeled nuclei from breast cancer images from TCGA and is a freely available under CC0. This dataset is recommended to be used for HoVerNet pipeline in MONAI instead of Lizard dataset with CC4 license, which hinders using that dataset in MONAI.
It would be nice to have a MONAI dataset to abstract away all the details and provide the pipeline with patch of images and its segmentation masks and classes.

NuCLS Dataset: https://github.com/PathologyDataScience/BCSS
NuCLS Paper: https://arxiv.org/pdf/2102.09099.pdf

**Comment by drbeh** [comment]
Discussed with Lee and Mohamed (Northwestern University) on the way to improve the annotation quality and create segmentation masks.

**Comment by drbeh** [comment]
The NuCLS dataset with nuclei delineation is prepared. The annotations are created in a bootstrapping way from the original annotations in NuCLS using Mask-RCNN and refined using annotations from BCSS dataset. Thanks to @kheffah

**Comment by jackyxie5** [comment]
Hi,
I was wondering if this NuCLS dataset is available in MONAI now? I cannot seem to find it in the documentation.
