### ISSUE TITLE
deprecate `meta_dict` usage in `monai.auto3dseg`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5201]
for example, this should be deprecated in favor of metatensor reprentations
https://github.com/Project-MONAI/MONAI/blob/84e271ec939330e7cedf22b3871c4a2a62d3c2a2/monai/auto3dseg/analyzer.py#L192

https://github.com/Project-MONAI/MONAI/blob/84e271ec939330e7cedf22b3871c4a2a62d3c2a2/monai/auto3dseg/analyzer.py#L764

**Comment by mingxin-zheng** [comment]
@wyli Thanks for bring up the issue. 

What's your opinion to deprecate the `meta_key_postfix`. I think we can either
- Remove the `meta_key_postfix` in the next release
- Add deprecation message and keep it for a few version
