### ISSUE TITLE
varautoencoder  has a bug preventing it working on 1D data

### ISSUE THREAD

**Issue by supratikbose** [Project-MONAI/MONAI#5225]
**Describe the bug**
(1): BUG 1
When we create a varautoencoder object with:, spatial_dims =1 and in_shape=(num_channels, width),  within the __init__() method the eventual value of "self.final_size" (check after line 117 in varautoencoder.py) is an integer and NOT a Tuple - irrespective of strides, channels. For spatial_dims > 1, "self.final_size is a tuple.
Later when decode_forward() gets called either independently or as part of forward(), evaluation of *self.final_size in line 144 throws an error "TypeError: view() argument after * must be an iterable, not int"  
(2): BUG / Wish:
decode_forward() has a default parameter use_sigmoid: bool = True, yet, while calling the provided forward() method, this flag can not be modified.

**To Reproduce**
#################################################
!python -c "import monai" || pip install -q "monai-weekly[pillow]"
import torch
from monai.networks.nets import VarAutoEncoder
numSamplesInBatch = 4
num_channels = 1
width = 1024
testMonaiVARModel = VarAutoEncoder(
                spatial_dims=1,
                in_shape=(num_channels, width),
                out_channels=1,
                latent_size=32,
                channels=(8,16,32),
                strides=(2,2,2)
            )
x = torch.randn(size=(numSamplesInBatch, num_channels, width), dtype=torch.float32)
recon = testMonaiVARModel(x)
#################################################
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-1de792a4e86d> in <module>
     14             )
     15 x = torch.randn(size=(numSamplesInBatch, num_channels, width), dtype=torch.float32)
---> 16 recon = testMonaiVARModel(x)

/opt/conda/envs/baseImcutVxm/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/envs/baseImcutVxm/lib/python3.7/site-packages/monai/networks/nets/varautoencoder.py in forward(self, x)
    159         mu, logvar = self.encode_forward(x)
    160         z = self.reparameterize(mu, logvar)
--> 161         return self.decode_forward(z), mu, logvar, z

/opt/conda/envs/baseImcutVxm/lib/python3.7/site-packages/monai/networks/nets/varautoencoder.py in decode_forward(self, z, use_sigmoid)
    142     def decode_forward(self, z: torch.Tensor, use_sigmoid: bool = True) -> torch.Tensor:
    143         x = F.relu(self.decodeL(z))
--> 144         x = x.view(x.shape[0], self.channels[-1], *self.final_size)
    145         x = self.decode(x)
    146         if use_sigmoid:

TypeError: view() argument after * must be an iterable, not int

**Expected behavior**
I have fixed the bug by deriving from varautoencoder and modifying the __initi__() method:
if isinstance(self.final_size, int):
            self.final_size = (self.final_size,)

**Screenshots**

**Environment**
MONAI version: 0.8.0
Numpy version: 1.21.5
Pytorch version: 1.9.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 714d00dffe6653e21260160666c4c201ab66511b

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.2.0
Tensorboard version: 2.7.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.2.2
tqdm version: 4.61.1
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.8.0
pandas version: 1.3.5
einops version: 0.4.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
```

**Additional context**
Add any other context about the problem here.

**Comment by KumoLiu** [comment]
Hi @supratikbose, thanks for pointing out the issue, I have created PR #5236 to fix it, it will be merged after all tests are passed. Thanks!
