### ISSUE TITLE
LoadImage will throw an exception under certain circumstances

### ISSUE THREAD

**Issue by macdavid** [Project-MONAI/MONAI#5227]
**Describe the bug**
 The following code in monai.transforms.io.array may throw an exception when track_meta is False:

        img = MetaTensor.ensure_torch_and_prune_meta(img_array, meta_data, self.simple_keys)
        if self.ensure_channel_first:
            img = EnsureChannelFirst()(img)
        if self.image_only:
            return img
        return img, img.meta  # for compatibility purpose

**Comment by KumoLiu** [comment]
Hi @macdavid, could you please paste your code and the error messages so that we can further locate the error? Thanks!

**Comment by macdavid** [comment]
> Hi @macdavid, could you please paste your code and the error messages so that we can further locate the error? Thanks!

When get_track_meta() is False, function ensure_torch_and_prune_meta will return Tensor, then img.meta will throw Exception

**Comment by wyli** [comment]
closed by https://github.com/Project-MONAI/MONAI/commit/ef68f16dde33172b2eeae5397ac75aa717808875
