### ISSUE TITLE
allow_low_quality_matches is always set to True

### ISSUE THREAD

**Issue by souvik3333** [Project-MONAI/MONAI#5250]
**Describe the bug**
`allow_low_quality_matches` in `set_regular_matcher` is always set to `True` and it's not using value from the argument, in retinanet.
https://github.com/Project-MONAI/MONAI/blob/e9f48e3416a506c0775fbe2366528ff1a30906bc/monai/apps/detection/networks/retinanet_detector.py#L327

**Comment by Nic-Ma** [comment]
Hi @Can-Zhao ,

Could you please help confirm it and fix?

Thanks in advance.

**Comment by Can-Zhao** [comment]
> **Describe the bug** `allow_low_quality_matches` in `set_regular_matcher` is always set to `True` and it's not using value from the argument, in retinanet.
> 
> https://github.com/Project-MONAI/MONAI/blob/e9f48e3416a506c0775fbe2366528ff1a30906bc/monai/apps/detection/networks/retinanet_detector.py#L327

Nice catch!! Fixed it in https://github.com/Project-MONAI/MONAI/pull/5255
