### ISSUE TITLE
Change HoVerNet Model Output from Dict to Tensor

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5265]
HoVerNet model has three branches and currently each of them are being return with an associated key and all together as a dictionary. This approach is nice since we know what branch we are dealing with with the `Enum`s that are defined; however, it is creating some challenges since this kind of outputs is not common in MONAI, and requires some changes:
1. HoVerNet Loss function needs to accept dictionary of Tensors (instead of one Tensor) for prediction and target (https://github.com/Project-MONAI/MONAI/pull/5199)
2. a new PrepareBatch is need to extract all the keys for the target and return a dictionary for target (instead of a tensor)
3. SuperviseTrainer needs to be updated to accept dictionary as the model outputs
4. Post process Transforms should implement new additional keys (https://github.com/Project-MONAI/MONAI/pull/5186#discussion_r981308312)

Considering that with this simple change, there is no need for any of the above changes, I am leaning toward making this backward incompatibility and making HoVerNet outputs a tensor where each channel represents output of one branch:
- first channel: nuclei segmentation (NP branch)
- second channel: horizontal map (HV branch)
- third channel: vertical map (HV branch)
- fourth channel (and any additional channel): classification output (NC branch)

@wyli @Nic-Ma @ericspod @rijobro @JHancox What do you think?

**Comment by wyli** [comment]
I feel it would make too strong assumptions about dtype and spatial shape of the branches...will returning a tuple address most of the issues? (If we are talking about the model outputs, then not sure how this is related to preparebatch which is about the inputs)

**Comment by JHancox** [comment]
Like @wyli, I think it might be rather constraining to impose the type/spatial restriction that this implies. Easy for me to say though, since I am not familiar enough in the downstream complications this creates. I'm certainly not wedded to the dictionary output though. If tuple (and/or namedtuple - if TS supports these days) can work, that's fine. I do like the elegance of the dictionary though.

**Comment by drbeh** [comment]
> I feel it would make too strong assumptions about dtype and spatial shape of the branches...will returning a tuple address most of the issues? (If we are talking about the model outputs, then not sure how this is related to preparebatch which is about the inputs)

Right but prepare_batch also prepare the target/label, which makes a little sense to be in a different type than the model output.

**Comment by drbeh** [comment]
@wyli @JHancox Thanks for your feedback.
I agree with @JHancox, that dictionaries are more elegant [and readable] than tuples in this case. If there is not enough motivation to make it tensor, we continue with the current implementation (dictionaries) and I will close this issue.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Thanks for raising the proposal, I have 2 concerns:
1. Does the different outputs have the same spatial shape? If not, we can't stack them into one Tensor.
2. If we stack them into one Tensor, how to apply different post-processing on different outputs separately?

Thanks.

**Comment by drbeh** [comment]
Hi @Nic-Ma, thanks for your questions.
1. yes, they are all have the same spatial shape
2. postprocessing can use three of the channels and create a new tensor for instance segmentation.

However, IMO we need more motivation to make a backward incompatible change, so I close this issue, and plan for the afterward changes.
