### ISSUE TITLE
Add SomeOf in monai.transforms.Compose 

### ISSUE THREAD

**Issue by visionNoob** [Project-MONAI/MONAI#5312]
**Is your feature request related to a problem? Please describe.**
I think although "SomeOf" is very useful feature for data augmentation and its easy implementation, 
there is no feature for "SomeOf" in monai transforms (Only naive compose and OneOf are implemented) 
https://docs.monai.io/en/stable/_modules/monai/transforms/compose.html#OneOf

**Describe the solution you'd like**
Adding SomeOf class with reference to albumentation's (https://github.com/albumentations-team/albumentations/blob/master/albumentations/core/composition.py#L332)

**Describe alternatives you've considered**
I would like to implement SomeOf feature and contribute to MONAI.

**Additional context**
none

**Comment by rachmadionl** [comment]
hi @Nic-Ma,
I'm new to the whole open-source contributions (never done this before), but I'd like to give it a shot for this issue. May I help? What should I prepare and read first? Thanks in advance.

**Comment by rachmadionl** [comment]
hi @Nic-Ma,
I have read it just now, and I'll try to implement SomeOf. If I understnad it correctly, what I should do first before anything is to create a fork of MONAI repo, right?

**Comment by Nic-Ma** [comment]
@rachmadionl Exactly, thanks!

**Comment by tuanchien** [comment]
Hi all, I wrote up this compositor to use on another project a few months back. Didn't get around to looking at upstreaming it until today and saw this issue. It's not exactly the same as Albumentations. The TLDR of this implementation is it samples without replacement each time using uniform sampling.  You can choose to grab a fixed number of transforms, or variable number (within a given range) each time.

I believe the Albumentations version allows non uniform weighting of transforms, and sampling with replacement as a configurable option. It only allows a fixed number of samples to be drawn each time.

Am open to extending the code if you are wanting to use those missing features from Albumentations.

@rachmadionl I also don't mean to usurp your efforts if you were planning on submitting something. Happy to close my PR and let you submit yours instead if you had something cooked up already.

**Comment by wyli** [comment]
thanks, it's addressed by https://github.com/Project-MONAI/MONAI/pull/6143
