### ISSUE TITLE
optional import error in ViT 

### ISSUE THREAD

**Issue by Ahmed93Saber** [Project-MONAI/MONAI#5325]
**Describe the bug**
When instantiating the ViT from monai, the code throws
monai.utils.module.OptionalImportError: from einops.layers.torch import Rearrange (No module named 'einops').

**To Reproduce**
run this code:
`
    model = monai.networks.nets.ViT(
        in_channels=1,
        img_size=(240, 240, 64),
        patch_size=(32, 32, 32),
        post_activation=None,
        classification=True,
        num_classes=1,
        dropout_rate=0.25,
        hidden_size=128,
        num_heads=4,
        num_layers=4,
        mlp_dim=512
    )
`

**Expected behavior**
the model should be instantiated properly 

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**
I think you need to include einops in your dependencies

**Comment by wyli** [comment]
Have you tried `pip install "monai[einops]"`? more details: https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

**Comment by Ahmed93Saber** [comment]
problem solved when I ran: 

`pip install 'monai[einops]' `

Thanks a lot :D
