### ISSUE TITLE
In "./runtests.sh --coverage" the project fails

### ISSUE THREAD

**Issue by fabrizzioalco** [Project-MONAI/MONAI#533]
**Describe the bug**
Trying to run _**./runtests.sh --coverage**_ throw me syntax error in modules of the project.

**To Reproduce**
1. Go to root project
3. Run commands bash runtests.sh --coverage

**Expected behavior**
Expect to do some tests 

**Screenshots**
<img width="454" alt="Screen Shot 2020-06-10 at 4 49 09 PM" src="https://user-images.githubusercontent.com/25325755/84322400-8a99a780-ab3a-11ea-81eb-9d698538c107.png">

**Environment (please complete the following information):**
 - OS Mojave
 - Python 3.7.7

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @fabrizzioalco ,

Could you please try to install all the requirements and try again?
`pip install -r requirements-dev.txt`
Make you have GPU and CUDA env ready.

Thanks.

**Comment by fabrizzioalco** [comment]
If im trying to run this on a Mac i wont be able because of i don't have NVIDA hardware?

**Comment by wyli** [comment]
> If im trying to run this on a Mac i wont be able because of i don't have NVIDA hardware?
could you include more info of the error? the first few lines of the version numbers such as
```
MONAI version: 0.1.0+122.g190d099.dirty
Python version: 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy version: 1.18.5
Pytorch version: 1.5.0
Ignite version: 0.3.0
```

**Comment by fabrizzioalco** [comment]
MONAI version: 0.1.0+116.g7444466.dirty
Python version: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.18.5
Pytorch version: 1.4.0
Ignite version: 0.3.0
1.4.0

**Comment by fabrizzioalco** [comment]
Already fix it
