### ISSUE TITLE
DataAnalyzer in auto3dseg will record negative numbers of spacing

### ISSUE THREAD

**Issue by XIANYUNYEHE-DEL** [Project-MONAI/MONAI#5332]
**Describe the bug**
I use `DataAnalyzer` to statistic LITS dataset, but i get some negative numbers of spacings in `data_stats.yaml`.
> spacing: - [-0.9765620231628418, 0.9765620231628418, 2.5]

I check this file in 3D Slicer, and get IJK to RAS Direction Matrix `[-1.0000, 1.0000, 1.0000]`. It seems that this is the reason for the negative spacing. I check other negative spacing data and find the same phenomenon. It will cause problems in the stats_summary and create the wrong information of spacing.

**Comment by wyli** [comment]
agreed, this is probably incorrect:
https://github.com/Project-MONAI/MONAI/blob/731c7435d6acdc058564e174b9a9589b447e977f/monai/auto3dseg/analyzer.py#L245-L247

it should be done with metatensor.pixdim or https://github.com/Project-MONAI/MONAI/blob/731c7435d6acdc058564e174b9a9589b447e977f/monai/data/utils.py#L688

**Comment by mingxin-zheng** [comment]
A related issue here: https://github.com/Project-MONAI/MONAI/issues/5201

@XIANYUNYEHE-DEL what needed to change seems straightforward to me. I will submit a PR to fix this.
@wyli Can the PR remove the `meta_key_postfix` completely or we need a few versions to deprecate it?

**Comment by mingxin-zheng** [comment]
@XIANYUNYEHE-DEL I created a [PR](https://github.com/Project-MONAI/MONAI/pull/5367) to fix this. Thanks for bringing it to our attention!
