### ISSUE TITLE
There are two risks adding a `transform_list` here:

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/MONAI#5336]
Improve customization of transform list in DataAnalyzer.

        There are two risks adding a `transform_list` here:
- A custom `transform_list` can nullify previous settings by the user in the `__init__ `. Docstrings and warnings need to be added.
- DataAnalyzer supports command line interface via Python Fire. But putting a transform_list (list object of Transforms) will be something Python Fire cannot support.

_Originally posted by @mingxin-zheng in https://github.com/Project-MONAI/MONAI/pull/5240#discussion_r995346573_

**Comment by mingxin-zheng** [comment]
Thanks @holgerroth for creating the ticket.

For the first point, we need to add some docstrings/warnings for Auto3DSeg
