### ISSUE TITLE
`compute_meandice` and `compute_meaniou` should be `compute_dice` and `compute_iou`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5381]
**Describe the bug**
the basic logic in
https://github.com/Project-MONAI/MONAI/blob/bc09a4ce642b7ae32d0264e9025938b416fd56a3/monai/metrics/meandice.py#L106-L108

https://github.com/Project-MONAI/MONAI/blob/bc09a4ce642b7ae32d0264e9025938b416fd56a3/monai/metrics/meaniou.py#L106-L108

don't include any metrics reduction logic, so their names shouldn't contain 'mean'.

**Comment by myron** [comment]
I think either name is okay, and compute_dice seems like a little bit semantically better option here, but both are okay 

but we should consider extending this function  as in here https://github.com/Project-MONAI/MONAI/pull/5379/files#diff-df0f76defe29c2c91286e52334ead7a0f1f54e392d1a3e8280e2e714800dc4cbR158

or refactoring dice overall https://github.com/Project-MONAI/MONAI/issues/5378

**Comment by wyli** [comment]
these are function elements at a 'low level', and have nothing to do with the ticket you mentioned @myron, let's not make cross-references if they are unrelated.
