### ISSUE TITLE
Remove hashing by key from CacheDatast  (hash_as_key) 

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#5390]
In the CacheDataset we have an option to hash by key (hash_as_key with hash_func=pickle_hashing).  It looks like , it is not used anywhere in the code or in any tutorials. 

Historically, the option was added due to @dongyang0122 request
 https://github.com/Project-MONAI/MONAI/issues/3734
 https://github.com/Project-MONAI/MONAI/pull/3739
 I've just synced with @dongyang0122 and he is not using this option either (and never used it)   

Hashing by key also seems not practical,  computing hash on 3D image inquires overhead (and it needs to be done every time when trying to access hash , both for read/write).  Finally other Datasets sub-classes don't have this option at all, which makes it inconsistent.   

I don't really see a good use-case to keep it. If there are duplicate images in the dataset , and they have to be exactly identical to a voxel for it to work,  then it will be probably faster to just process a dubplicate image, then checking for hash for all images.  Or even better to run some check for dublicates beforehand. 

If we remove it completely,  we'll simplify quite a bit our code in CacheDataset.  There is already a refactoring PR https://github.com/Project-MONAI/MONAI/pull/5365, perhaps we can remove this hashing by key too @Nic-Ma

**Comment by dongyang0122** [comment]
I don't know yet that this feature is available. And I don't recall the actual use of these PRs. It would be great if you could help me understand the functionality here. Thank you! @wyli @Nic-Ma

**Comment by Nic-Ma** [comment]
Hi @dongyang0122 ,

This feature is designed for your previous proposal: avoid duplicated caching if enhanced the dataset items by copying.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @myron ,

I created PR https://github.com/Project-MONAI/MONAI/pull/5398 to unify the `list` and `dict` types for the cache content.
Could you please help review it?

Thanks in advance.

**Comment by wyli** [comment]
the `hash_as_key`+`hash_func` provides the flexibility of customizing the cache keys, for example, it supports use cases of using some metatensor's .meta dict value as the cache key

**Comment by myron** [comment]
> the `hash_as_key`+`hash_func` provides the flexibility of customizing the cache keys, for example, it supports use cases of using some metatensor's .meta dict value as the cache key

Thanks @wyli, I understand what it's doing, but those use-cases are hypothetical.  We don't have any real use case for it.  As far as I know, no one is using this feature, and it was not used ever before since the day it was added in monai.  Is it wrong to remove the unused functionality to have a cleaner and more maintainable API (with less bug possibilities) ?

**Comment by Nic-Ma** [comment]
Hi @myron ,

As I described in the previous comment, there is a typical use case is to avoid duplicated caching content if having duplicated input images in the data list. For example, to enhance a small dataset, @dongyang0122 usually copies items in the data list:
```json
"training": [
        {
            "image": "./imagesTr/prostate_14.nii.gz",
            "label": "./labelsTr/prostate_14.nii.gz"
        },
        {
            "image": "./imagesTr/prostate_14.nii.gz",
            "label": "./labelsTr/prostate_14.nii.gz"
        },
        {
            "image": "./imagesTr/prostate_41.nii.gz",
            "label": "./labelsTr/prostate_41.nii.gz"
        },
        {
            "image": "./imagesTr/prostate_41.nii.gz",
            "label": "./labelsTr/prostate_41.nii.gz"
        },
        {
            "image": "./imagesTr/prostate_34.nii.gz",
            "label": "./labelsTr/prostate_34.nii.gz"
        },
        {
            "image": "./imagesTr/prostate_34.nii.gz",
            "label": "./labelsTr/prostate_34.nii.gz"
        }
]
```
And even we don't have tutorials or bundles that contain this feature, we should not suppose MONAI users don't use it at all as we already released it many days, we should avoid breaking changes after 1.0.
What do you think?
CC @wyli @ericspod 

Thanks.
