### ISSUE TITLE
Dimension is hardcoded for softmax/argmax for PostTransform

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAI#5391]
For both Dictionary and Array based post transform, the dimension is hardcoded.

Softmax:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/post/array.py#L115

Argmax:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/post/array.py#L203

When the input is `[Batch, Channel, x, y...]` these transforms can't be used as dimension is kind of hardcoded here..

> Possibly similar things can be fixed in other places in POST Transform.. (when you search `dim=0`)

**Comment by wyli** [comment]
I made a PR earlier but didn't seem to get enough interests  https://github.com/Project-MONAI/MONAI/pull/3735 maybe we revisit @ericspod @Nic-Ma @rijobro
