### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#5394]
Python 3.11 has just been released and looks to be significantly [faster than its predecessors](https://towardsdatascience.com/python-3-11-is-indeed-faster-than-3-10-1247531e771b). Pytorch support for python 3.11 [hasn't been released yet](https://github.com/pytorch/pytorch/issues/86566), but when it has we should add 3.11 to our test scripts. Numpy already supports python 3.11 so all good on that front.

**Comment by rijobro** [comment]
@wyli can we add something like this to our testing?
```bash
conda install -c conda-forge python==3.11 -y
pip install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/cu117
pip install numpy
```

**Comment by wyli** [comment]
current status:

- deployed cpu minimal tests: https://github.com/Project-MONAI/MONAI/blob/e7bfac61f286782756c083f992e8efc2b14f18b1/.github/workflows/pythonapp-min.yml#L78
- jit testing error skipped https://github.com/Project-MONAI/MONAI/blob/e7bfac61f286782756c083f992e8efc2b14f18b1/tests/utils.py#L712-L715
