### ISSUE TITLE
MetaTensor size bug in transform function

### ISSUE THREAD

**Issue by chuxiang93** [Project-MONAI/MONAI#5414]
Since SIZE is a function of the class metatensor, this sentence does not work. The correct way should be  "fg_indices.size()[0]".

https://github.com/Project-MONAI/MONAI/blob/f407fcce1c32c050f327b26a16b7f7bc8a01f593/monai/transforms/utils.py#L512

**Comment by wyli** [comment]
thanks for reporting, I'm submitting a patch https://github.com/Project-MONAI/MONAI/pull/5415
