### ISSUE TITLE
KeyError: 'label'  monai/apps/auto3dseg/data_analyzer.py

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5427]
**Describe the bug**
running `python -m monai.apps.auto3dseg DataAnalyzer get_all_case_stats` with ` --label_key=None`

there's a `KeyError: 'label'` with this line:
https://github.com/Project-MONAI/MONAI/blob/6e77d57938a4253353265616b54ab8be3f2d5ab3/monai/apps/auto3dseg/data_analyzer.py#L265

would be great to have test cases for `label_key=None`

cc @mingxin-zheng do you have time for this?

**Comment by mingxin-zheng** [comment]
@wyli Sure I can fix this. 

There is a test for CPU case but not GPU case. I will add it in the `SIM_GPU_TEST_CASES`
https://github.com/Project-MONAI/MONAI/blob/6e77d57938a4253353265616b54ab8be3f2d5ab3/tests/test_auto3dseg.py#L73

**Comment by mingxin-zheng** [comment]
@wyli 
On a second thought, this error occurred because None is passed as `string` rather than `NoneType` in the argument list. It is not a test problem but more about the design of input arguments...

**Comment by wyli** [comment]
I see, it seems there's no way to provide `None` via python fire CLI.

**Comment by wyli** [comment]
> I see, it seems there's no way to provide `None` via python fire CLI.

I tried this example the `None` works fine:

```py
import fire

def hello(name="hello"):
  return f"{type(name)}"

if __name__ == '__main__':
  fire.Fire(hello)
```

`python my_test_3.py --name=None`

it outputs:

`<class 'NoneType'>`

**Comment by mingxin-zheng** [comment]
Hi @wyli , you're right. I did one similar experiment last week but somehow I can't replicate it anymore. Your snippet is giving `NoneType`. It seems Python Fire create a special rule for "None" as an input. If the `name` argument is none or NoNe, the output will be
`<class 'str'>`

But with this finding, I tested using the `label_key` with `None` in Data Analyzer, and it is not giving me any errors as below.

What platform did you use when running into the error?

```python
import os
import nibabel as nib
import numpy as np
import subprocess

from monai.bundle.config_parser import ConfigParser
from monai.data import create_test_image_3d

sim_datalist = {
    "testing": [{"image": "val_001.fake.nii.gz"}, {"image": "val_002.fake.nii.gz"}],
    "training": [
        {"fold": 0, "image": "tr_image_001.fake.nii.gz", "label": "tr_label_001.fake.nii.gz"},
        {"fold": 0, "image": "tr_image_002.fake.nii.gz", "label": "tr_label_002.fake.nii.gz"},
        {"fold": 1, "image": "tr_image_001.fake.nii.gz", "label": "tr_label_001.fake.nii.gz"},
        {"fold": 1, "image": "tr_image_004.fake.nii.gz", "label": "tr_label_004.fake.nii.gz"},
    ],
}

def create_sim_data(dataroot: str, sim_datalist: dict, sim_dim: tuple, **kwargs) -> None:
    if not os.path.isdir(dataroot):
        os.makedirs(dataroot)

    # Generate a fake dataset
    for d in sim_datalist["testing"] + sim_datalist["training"]:
        im, seg = create_test_image_3d(sim_dim[0], sim_dim[1], sim_dim[2], **kwargs)
        nib_image = nib.Nifti1Image(im, affine=np.eye(4))
        image_fpath = os.path.join(dataroot, d["image"])
        nib.save(nib_image, image_fpath)

        if "label" in d:
            nib_image = nib.Nifti1Image(seg, affine=np.eye(4))
            label_fpath = os.path.join(dataroot, d["label"])
            nib.save(nib_image, label_fpath)

if __name__ == '__main__':

    work_dir = './tmp_workdir'
    dataroot_dir = os.path.join(work_dir, "sim_dataroot")
    if not os.path.isdir(work_dir):
        os.makedirs(work_dir)
    if not os.path.isdir(dataroot_dir):
        os.makedirs(dataroot_dir)
    datalist_file = os.path.join(work_dir, "sim_datalist.json")
    ConfigParser.export_config_file(sim_datalist, datalist_file)
    create_sim_data(dataroot_dir, sim_datalist, (32, 32, 32), rad_max=8, rad_min=1, num_seg_classes=1)

    cmd_cuda = """
    python -m monai.apps.auto3dseg DataAnalyzer get_all_case_stats --datalist="./tmp_workdir/sim_datalist.json"
            --dataroot="./tmp_workdir/sim_dataroot" --output_path="./tmp_workdir/data_stats_cuda.yaml"
            --device="cuda" --label_key=None
    """

    cmd_cpu = """
    python -m monai.apps.auto3dseg DataAnalyzer get_all_case_stats --datalist="./tmp_workdir/sim_datalist.json"
            --dataroot="./tmp_workdir/sim_dataroot" --output_path="./tmp_workdir/data_stats_cpu.yaml"
            --label_key=None
    """
    subprocess.run(cmd_cuda.split())
    subprocess.run(cmd_cpu.split())
   
```

**Comment by mingxin-zheng** [comment]
Thanks @wyli . You are right. It seems `None` and `"None"` are treated as special inputs for `NoneType` in Python Fire. Other inputs such as "NoNe" , or "none" are treated as `str`.
