### ISSUE TITLE
Installing monai with python 3.10.x version fails

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAI#5429]
```
ERROR: Could not find a version that satisfies the requirement itk>=5.2; extra == "itk" (from monai[fire,gdown,ignite,itk,lmdb,nibabel,openslide,pillow,psutil,skimage,tensorboard,torchvision,tqdm]) (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1, 5.3rc2, 5.3rc2.post1, 5.3rc3, 5.3rc4, 5.3rc4.post1, 5.3rc4.post2, 5.3rc4.post3)
ERROR: No matching distribution found for itk>=5.2; extra == "itk"
```

Many users are trying this, and it fails for them.  The new Ubuntu 22.04 comes with python 3.10.x preinstalled.  So we are forcing users to work/downgrade python version

**Comment by wyli** [comment]
1.0.1 is tested with py3.10 https://github.com/Project-MONAI/MONAI/pull/537 without the optional itk dependency. A work around would be "pip install -U --pre itk", then install monai..

**Comment by SachidanandAlle** [comment]
For some reasons it didn't work completely for some users... or may be for some data
https://github.com/Project-MONAI/MONAILabel/issues/1064

**Comment by wyli** [comment]
closing -- itk 5.3 is now available and it supports py3.10
