### ISSUE TITLE
ITKReader with inverse indexing does not work

### ISSUE THREAD

**Issue by beantr96** [Project-MONAI/MONAI#5441]
Hi team, I'm using monai.data.LoadImaged with ITKReader and the inverse_indexing option = True to load data. The MONAI version is 1.0.1 and ITK version 5.2.1post1. However, it leads to a segmentation fault error and breaks the dataloader. Downgrading MONAI to 0.9.0 seems to solve the issue but I wonder what the root cause is and how to solve it more efficiently.

Thanks.

**Comment by wyli** [comment]
thanks for reporting, assuming you are talking about `monai.transforms.LoadImaged` as there's no `monai.data.LoadImaged` class in monai. There's no `inverse_indexing` argument for that class, do you mean `reverse_indexing`?

if changing the argument doesn't work, could you please follow the bug reporting template to provide more details?

**Comment by wyli** [comment]
thanks, could you try:
```py
LoadImaged(keys=("image", "label"), reader=ITKReader, reverse_indexing=True)
```
instead of:
```py
LoadImaged(keys=("image", "label"), reader=ITKReader(reverse_indexing=True))
```
I think they are different when the loader has multiple workers...

**Comment by beantr96** [comment]
Hi @wyli I think it still does not work for me. The only solution that I found so far is to downgrade MONAI to 0.9.0. But that version is a bit old so I'm looking for some alternative solution. Thanks... 
![image](https://user-images.githubusercontent.com/25809806/199539108-52ddf2f6-d6a0-4ab6-b343-856e878db087.png)

**Comment by wyli** [comment]
thanks, I couldn't replicate this issue locally. strange because 0.9.0 vs 1.0.1 the itkreader didn't have any change related to `reverse_indexing `. if you can share more detailed log or example image volumes I can look into this further

**Comment by beantr96** [comment]
Hi @wyli, I'm sorry for the late reply. I did some further analysis. Actually I was able to print the shape of the tensor but unable to print the tensor itself.

```python
from monai.transforms import AddChanneld, Compose, LoadImaged
from monai.data import ITKReader
# A dict of filepaths of the image and label to load 
input_dict = {"image": "tcia_exp/imagesTr/LUNG1_001.nii.gz", "label": "tcia_exp/labelsTr/LUNG1_001.nii.gz"}
loader = Compose([LoadImaged(keys=("image", "label"), reader=ITKReader(reverse_indexing=True)), AddChanneld(keys=("image", "label"))])
# Output
out = loader(input_dict)
print(out["image"].shape)
print(out["label"].shape)
print(out["image"]) # this gives segmentation fault error
print(out["label"]) # this gives segmentation fault error

```
In addition, when I print `type(out["image"])`, MONAI 1.0.1 returns `<class 'monai.data.meta_tensor.MetaTensor'>` while MONAI 0.9.0 returns `<class 'itk.itkPyBufferPython.NDArrayITKBase'>`.

**Comment by ntatsisk** [comment]
Hi @wyli, I am also getting an error when reading images with ITKReader. My data must be quite similar to @beantr96 (Lung CTs from Tcia/Learn2Reg challenge). I am using `MONAI==1.0.1` and `itk==5.3rc4.post3`.  Here is a minimal reproducible example:

```
import os, itk
from monai.apps import download_and_extract
from monai.data import ITKReader
from monai.transforms import LoadImage

# Download and extract Learn2Reg data
root_dir = './'
train_url = "https://zenodo.org/record/3835682/files/training.zip"
folderpath = os.path.join(root_dir, "LungCT")

if not os.path.exists(folderpath):
    os.mkdir(folderpath)

download_and_extract(url=train_url, output_dir=folderpath)

# Read an image with plain itk
filepath = os.path.join(folderpath, "training", "scans", "case_001_exp.nii.gz")
image = itk.imread(filepath, itk.F)
print(image.GetSpacing())

# Read the same image with ITKReader from MONAI (... gives error)
x = LoadImage(reader=ITKReader)(filepath)
print(x.shape)
```

Output:
```
training.zip: 266MB [00:05, 50.0MB/s]
2022-11-15 19:46:46,943 - INFO - Downloaded: C:\Users\kntatsis\AppData\Local\Temp\tmprgca21nj\training.zip
2022-11-15 19:46:46,943 - INFO - Expected md5 is None, skip md5 check for file C:\Users\kntatsis\AppData\Local\Temp\tmprgca21nj\training.zip.
2022-11-15 19:46:46,959 - INFO - Non-empty folder exists in LungCT\training, skipped extracting.
itkVectorD3 ([1.75, 1.25, 1.75])
Traceback (most recent call last):
  File "C:\Users\kntatsis\work\monai_itkreader_error\monai_itkreader_error.py", line 22, in <module>
    x = LoadImage(reader=ITKReader)(filepath)
  File "C:\Users\kntatsis\itk-elastix-env\lib\site-packages\monai\transforms\io\array.py", line 271, in __call__
    meta_data = switch_endianness(meta_data, "<")
  File "C:\Users\kntatsis\itk-elastix-env\lib\site-packages\monai\transforms\io\array.py", line 84, in switch_endianness
    data = {k: switch_endianness(v, new) for k, v in data.items()}
  File "C:\Users\kntatsis\itk-elastix-env\lib\site-packages\monai\transforms\io\array.py", line 84, in <dictcomp>
    data = {k: switch_endianness(v, new) for k, v in data.items()}
  File "C:\Users\kntatsis\itk-elastix-env\lib\site-packages\monai\transforms\io\array.py", line 86, in switch_endianness
    raise RuntimeError(f"Unknown type: {type(data).__name__}")
RuntimeError: Unknown type: itkMatrixF44
```

It does't appear related to `reverse_indexing` but I hope it is still not off-topic! Thanks :)

**Comment by wyli** [comment]
thanks for reporting @ntatsisk, that's addressed recently... https://github.com/Project-MONAI/MONAI/pull/5433 the patch will be released in December. 

you can uninstall monai 1.0.1 and try `pip install monai-weekly` or install the current stable release of itk, that's 5.2.1

**Comment by beantr96** [comment]
Hi @wyli, so is there any update from your side regarding the inverse_indexing issue?

**Comment by wyli** [comment]
> Hi @wyli, so is there any update from your side regarding the inverse_indexing issue?

I couldn't replicate the issue using your screenshots.

**Comment by beantr96** [comment]
@wyli That's strange since me and my colleague in the team had the same issue. Have you tried printing the image tensor instead of just the shape. Printing the shape did occasionally work but printing the tensor always led to segmentation fault. Thanks for your help!

**Comment by wyli** [comment]
I don't have these inputs:
```
input_dict = {"image": "tcia_exp/imagesTr/LUNG1_001.nii.gz", "label": "tcia_exp/labelsTr/LUNG1_001.nii.gz"}
```

**Comment by beantr96** [comment]
Hi @wyli I cannot upload those files since they are too large but any Medical Segmentation Decathlon (MSD) images have this issue as well. If you have MSD files perhaps could you try them? Many thanks!

**Comment by wyli** [comment]
yes I tried, for example `Task06_Lung/imagesTr/lung_001.nii.gz` and `Task06_Lung/labelsTr/lung_001.nii.gz` but couldn't reproduce.
