### ISSUE TITLE
Upgrade PyTorch base docker to 22.10

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#5452]
**Is your feature request related to a problem? Please describe.**
As the new PyTorch docker had been released: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch.
It would be nice to update our dependency and CI tests to cover it.

**Comment by wyli** [comment]
Hi @Nic-Ma I'm working on it https://github.com/Project-MONAI/MONAI/tree/5431-torch-add113-drop17 and @YanxuanLiu will take over this

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Cool! sounds good.

Thanks.
