### ISSUE TITLE
Utils to generate infer and metadata to simplify bundle creation

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAI#5455]
Creating a bundle is not a simple task. I am an all in monai user. I would like to write only 1 file the train.config (json or yml) file

Please provide a util to take a train config and generate the metadata.json and infer config needed for monai deploy and monai label

**Comment by Nic-Ma** [comment]
Please refer to the API: https://docs.monai.io/en/stable/_modules/monai/bundle/scripts.html#init_bundle.

Thanks.
