### ISSUE TITLE
Adding voxelmorph in MONAI?

### ISSUE THREAD

**Issue by bhosalems** [Project-MONAI/MONAI#5484]
**Is your feature request related to a problem? Please describe.**
Adding 3d image registration model called voxelmorph https://arxiv.org/pdf/1809.05231.pdf.

**Describe the solution you'd like**
Trainable voxelmorph model.

**Comment by wyli** [comment]
that's not currently implemented in this codebase, contributions is greatly welcomed.

**Comment by bhosalems** [comment]
Thanks, I could add it as time permits. Can you point me to the right direction for contribution?

**Comment by aliunluml** [comment]
I will work on this if that's OK for both of you.

**Comment by aliunluml** [comment]
Ok. I am not able to work on this at the moment. If there is anyone else interested, please feel free to work on this.

**Comment by kvttt** [comment]
Hi @wyli, may I work on this?
