### ISSUE TITLE
`NetAdapter` now does not support torchscript

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#5485]
When I tried to update `pathology_tumor_detection` bundle to use monai 1.0.1, it raised torchscript error like:
```
RuntimeError:
Unknown type name 'dict':
  File "/home/venn/Desktop/monai-code/test_model_zoo/lib/python3.8/site-packages/monai/networks/nets/netadapter.py", line 110
        if isinstance(x, tuple):
            x = x[0]  # it might be a namedtuple such as torchvision.model.InceptionOutputs
        elif isinstance(x, dict):
                           ~~~~ <--- HERE
            x = x[self.node_name]  # torchvision create_feature_extractor
        if self.pool is not None:

```
On monai 0.9.1, no error happened, thus I checked the history of the implementation and found that this PR: https://github.com/Project-MONAI/MONAI/pull/4873 may raise the issue, and the key point is that within the unit test, there is no check on torchscript.

Therefore, should we modify the structure to support torchscript, or `NetAdapter` does not necessarily support it so far?
This also impact the plan to update the pathology bundle to support MONAI 1.0.1 (see also in: https://github.com/Project-MONAI/model-zoo/issues/180).

Hi @Nic-Ma @wyli @drbeh , may need your help to discuss about this issue, thanks in advance!

**Comment by wyli** [comment]
hi @yiheng-wang-nv thanks for reporting the issue, I'll look into it...
