### ISSUE TITLE
ImportError: cannot import name 'ArrayDataset'

### ISSUE THREAD

**Issue by petteriTeikari** [Project-MONAI/MONAI#549]
Following the [notebook tutorial on 3D UNet](https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/unet_segmentation_3d_ignite.ipynb), the `ArrayDataset` is not found from where it was suppose to be found, while everything else seems to be available?  

![image](https://user-images.githubusercontent.com/1060514/84504376-bee4a380-acb3-11ea-8aa4-4b72ea656271.png)

 - OS: Ubuntu 18.04
 - Python version: 3.6 venv
 - MONAI version: monai 0.1.0 (installed today with `pip install monai`, `monai-0.1.0-202004191421-py3-none-any.whl`)

**Comment by Nic-Ma** [comment]
Hi @petteriTeikari ,

This `ArrayDataset` is new added in v0.2.
You can either change to pip install from source code:
`pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI`
or:
change the branch to `releases/0.1.0` and check the examples again.

Thanks.

**Comment by petteriTeikari** [comment]
Thanks @Nic-Ma for quick reply, the install from source worked and `ArrayDataset` was found

**Comment by petteriTeikari** [comment]
Actually when continuing with the example, this error happened with the line `im, seg = monai.utils.misc.first(loader)`:

```python
TypeError: object of type 'ArrayDataset' has no len()
```

**Comment by petteriTeikari** [comment]
@Nic-Ma when following the same example, I also ran into this error 

`TypeError: object of type 'ArrayDataset' has no len()`

when executing this line:

`im, seg = monai.utils.misc.first(loader)`
