### ISSUE TITLE
Dim error in `HoVerNetLoss`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#5500]
**Describe the bug**
Since in `SobelGradients `, we need input with shape (C, H, W, [D]), but I find in `HoVerNetLoss`, it used shape with (B, H, W).
https://github.com/Project-MONAI/MONAI/blob/27362e482761985daac8d5ef732eb57b50c741f1/monai/transforms/post/array.py#L888-L890
https://github.com/Project-MONAI/MONAI/blob/27362e482761985daac8d5ef732eb57b50c741f1/monai/apps/pathology/losses/hovernet_loss.py#L69-L72

**Comment by drbeh** [comment]
@KumoLiu @JHancox That's right! The Sobel gradient has changed but this one not. I'll submit a quick fix.
