### ISSUE TITLE
LoadImageD and MetaTensor

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#5509]
It's more of question to clarify, not a bug. can you help clarify plz

- LoadImage() and LoadImaged() always return MetaTensor. Is it by design?  I'm okay either way, just want to clarify. So we can't return the original data format ?

- line 281 `return img, img.meta if isinstance(img, MetaTensor) else meta_data`. The img seems to be always a MetaTensor, is that check necessary?

https://github.com/Project-MONAI/MONAI/blob/c27ab360212ad122f5ca41fc69b8c2f47676b809/monai/transforms/io/array.py#L273-L281

- inside of MetaTensor.ensure_torch_and_prune_meta(), we seems to do conversion to Tensor twice on lines 487 and 504.  on 487 we `img = convert_to_tensor(im)` and `return MetaTensor(img, meta=meta) ` will internally call torch.as_tensor on img.  

https://github.com/Project-MONAI/MONAI/blob/c27ab360212ad122f5ca41fc69b8c2f47676b809/monai/data/meta_tensor.py#L487-L504

Thank you

**Comment by wyli** [comment]
it's possible to globally turn off the metatensor...
```py
>>> from monai.data import set_track_meta
>>> set_track_meta(False)
>>> from monai.transforms import LoadImage
>>> x = LoadImage(image_only=True)("IBSR_01_ana.nii.gz")
>>> type(x)
<class 'torch.Tensor'>
```

but these are not systematically tested for end-to-end workflows, for example, some transform inverting pipelines might not work properly...

**Comment by myron** [comment]
> it's possible to globally turn off the metatensor...
> 
> ```python
> >>> from monai.data import set_track_meta
> >>> set_track_meta(False)
> >>> from monai.transforms import LoadImage
> >>> x = LoadImage(image_only=True)("IBSR_01_ana.nii.gz")
> >>> type(x)
> <class 'torch.Tensor'>
> ```
> 
> but these are not systematically tested for end-to-end workflows, for example, some transform inverting pipelines might not work properly...

I see, thank you.  what about the last question:  lines 487 and 504 seems both convert to tensor internally, or can we remove line 487  `img = convert_to_tensor(im)` ?

**Comment by wyli** [comment]
I think it is about returning a fresh copy of the input, @rijobro perhaps can confirm

**Comment by rijobro** [comment]
Looking at the code, I'm not 100% sure if both are needed. I'm also not 100% which of them would create a deepcopy of the data. Feel free to mess around with it for a variety of inputs (`torch.Tensor`, `MetaTensor` and `np.ndarray`) and see how many copies are created (when debugging, you could do `print(img is im)` etc.). Also check for contiguous vs non-contiguous input, as the comment mentions this: `img = convert_to_tensor(im)  # potentially ascontiguousarray`.

If they can be combined into one, I'm happy for us to do that.

**Comment by wyli** [comment]
thanks, now the repeated `convert_to_tensor` is changed to a simple meta assignment:
https://github.com/Project-MONAI/MONAI/blob/b59216458751db89598219f318f3ead2643fdf11/monai/data/meta_tensor.py#L545-L552
