### ISSUE TITLE
InvertD() transform should preserve device of the output

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#5510]
https://github.com/Project-MONAI/MONAI/blob/e44f3b904c8c599e46fdfa22758639c63b47ee59/monai/transforms/post/dictionary.py#L703-L706

Currently the inverse transform Invertd() always changes the output tensor device to `self.device` which is `cpu` (default initialization).  And there is no way to preserve the original device (if it's not know in advance).  

- I recommend the default parameter  "device=None", which is to do NO device conversion. 

- Also the default option post_func is `post_func = lambda x: x
 `, which is a redundant call. Perhaps we can do post_func = None as default, and skip it in that case

**Comment by wyli** [comment]
> And there is no way to preserve the original device (if it's not know in advance).

I think setting `device=None` will preserve the device, or do I miss something here?

**Comment by myron** [comment]
you're right, the concept of `inverted_data.to(None)`  will keep the device, I though that it would not work.  apologies. I think it didn't work for me for some additional reason. thanks for updating the options defaults, it looks much better now and more consistent with other transforms
