### ISSUE TITLE
Rand2DElastic implicitly scales images based on spacing

### ISSUE THREAD

**Issue by murraycutforth** [Project-MONAI/MONAI#552]
**Describe the bug**
Applying Rand2DElastic with large spacing values appears to have the effect of padding the image and then resampling to the original size (easiest to understand from the screenshot below). This means that the pixel resolution has been increased (equivalent to zooming out on the image).

**Expected behavior**
I would expect that the scale of the image would not be affected by the spacing parameter of the random elastic deformation. 

I haven't yet had a chance to look at the code in more detail to work out why this happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/11088372/84506036-9f02af00-acb6-11ea-95ff-5daa853e5b9a.png)

The image/label pair on the left is generated with Rand2DElasticd using spacing=(100,100), and the image/label pair on the right for comparison is generated using spacing=(1,1). Both images are 512x512.

**Environment (please complete the following information):**
 - MONAI version: 0.1.0

**Comment by fabrizzioalco** [comment]
Hey, Im going to take a look at this. I'll read the code and try to fix it :)

**Comment by fabrizzioalco** [comment]
@wyli Can i have some assist with docker to reproduce this?

**Comment by fabrizzioalco** [comment]
@hjmjohnson Is the docker image has NVIDA installed or do i need to have it on my computer?

**Comment by Nic-Ma** [comment]
Hi @fabrizzioalco ,

You can install env by MONAI docker and then git clone your repo to develop in it:
```
# with docker v19.03+
docker run --gpus all --rm -ti --ipc=host projectmonai/monai:latest
```
Or you can manually install the dependency by `pip install -r requirements.txt`.

Thanks.

**Comment by wyli** [comment]
I'm working on this

**Comment by wyli** [comment]
> I'm working on this

**Comment by wyli** [comment]
Many thanks for reporting this issue @murraycutforth.  The upsampling of control grids didn't take the extra control points into account.  #647 fixes it.
