### ISSUE TITLE
Remove skimage dependency in get_largest_connected_component_mask

### ISSUE THREAD

**Issue by YuanTingHsieh** [Project-MONAI/MONAI#554]
**Is your feature request related to a problem? Please describe.**
Remove extra dependency

**Describe the solution you'd like**
Remove skimage dependency

**Describe alternatives you've considered**
If can't write a faster or equivalent alternative than just keep it.

**Additional context**

**Comment by YuanTingHsieh** [comment]
I'll work on this.

**Comment by wyli** [comment]
no progress. I'm closing this ticket.

**Comment by wyli** [comment]
related to this one, a faster version is now available via https://github.com/Project-MONAI/MONAI/pull/3677
