### ISSUE TITLE
Promote Child Items to Top Level

### ISSUE THREAD

**Issue by bhashemian** [Project-MONAI/MONAI#5553]
The MONAO dict-based transforms acts on the top level keys, for instance `data={"image": ..., "pred": ...}`; however, when the output is nested (like in the hovernet model), the actual data will lie one level below like `data={"image": ..., "pred": {"a":..., "b":...}}`.

Currently, if user want to apply transform on "a" or "b", it can use `Lambdad` and apply that transfrom on `data["pred"]` instead and use "a" and "b" as keys. However, if the user want to apply a transform on "image" and "a" for instance, I didn't find any transform that can enable it.

Here a transform that can promote these children items ("a" and "b") to the same level of "image" can solve the problem.

**Comment by myron** [comment]
Hi, I'm not familiar with this model, but i'm just curious  at which place do we get the output in this form `"pred": {"a":..., "b":...}}` during loading pipeline or post-processing after prediction? I don't think any loading, augmentation transforms produce such format.   or if the model  produces such output, can we simple reformat the output of the model? thank you

**Comment by drbeh** [comment]
Hi @myron, we got this in the output of HoVerNet model.
```
{"pred": {"horizontal_vertical": ..., "nucleus_prediction": ..., "type_prediction": ...}
```
https://github.com/Project-MONAI/MONAI/blob/77651add61b50f2a31fcc3c8b510d3179daa078c/monai/networks/nets/hovernet.py#L581-L586


Changing that will cause backward incompatibilities internally and externally.

**Comment by myron** [comment]
I see, thank you.  then if you have access to model output in the python code,  you could directly add those keys "horizontal_vertical", 'nucleus_prediction".. to you main dict 
e.g. `batch_data.update(output["pred])`
this would save you from writing another monai transform. 
but, I guess you don't have access to it in python code, then yes, you'd need a new transfor . I think there is a similar in-spirit transform  **splitdim** https://docs.monai.io/en/stable/transforms.html#splitdim, but that only split a tensor dimension to create new key, value pairs.
