### ISSUE TITLE
Potential 3D bug in EfficientNet Squeeze and Excitation layer

### ISSUE THREAD

**Issue by swilson314** [Project-MONAI/MONAI#5574]
efficientnet.py

```
        if self.has_se:
            self._se_adaptpool = adaptivepool_type(1)
            num_squeezed_channels = max(1, int(in_channels * self.se_ratio))
            self._se_reduce = conv_type(in_channels=oup, out_channels=num_squeezed_channels, kernel_size=1)
            self._se_reduce_padding = _make_same_padder(self._se_reduce, [1, 1])
            self._se_expand = conv_type(in_channels=num_squeezed_channels, out_channels=oup, kernel_size=1)
            self._se_expand_padding = _make_same_padder(self._se_expand, [1, 1])
```

I believe the image_size = [1, 1] in _make_same_padder() should actually be [1, 1, 1] for the EfficientNet to support 3D. This is just by inspection, but I suspect this oversight came from extending 2D code.

**Comment by wyli** [comment]
agreed, would you like to contribute a fix?

**Comment by swilson314** [comment]
Great, yes. I'm new to Monai, are there any special instructions?

**Comment by wyli** [comment]
Sure, the contributing guide has some details https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md and please let me know if you have any specific questions

**Comment by wyli** [comment]
Hi @yiheng-wang-nv could you please help fix this one, it seems https://github.com/Project-MONAI/MONAI/pull/5695 had stalled.
