### ISSUE TITLE
flake8 released 6.0.0 and breaks our ci tests

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#5578]
For examples:

in MONAI: https://github.com/Project-MONAI/MONAI/actions/runs/3535256520/jobs/5933068678
in model zoo: 
https://github.com/Project-MONAI/model-zoo/actions/runs/3536887667/jobs/5938751674

I just noticed that flake8 releases its 6.0.0 version (https://github.com/PyCQA/flake8/commit/b9a7794c4f425ef8419081e6993f99419cc667ea), it may have some breaking changes that raise the issue.

**Comment by wyli** [comment]
duplicate of https://github.com/Project-MONAI/MONAI/issues/5575?

**Comment by yiheng-wang-nv** [comment]
> duplicate of #5575?

Thanks! Let me change the cfg file in model zoo.
