### ISSUE TITLE
pytorch warning with python 3.11

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#5579]
**Describe the bug**
I'm getting a warning that is constantly printed with python 3.11. I'm using the `PersistentCacheDataset`, I suspect that is where the warning is coming from but can't currently breakpoint it. Warning is:

> /home/rbrown/miniconda3/lib/python3.11/site-packages/torch/storage.py:315: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.

**Comment by wyli** [comment]
https://github.com/Project-MONAI/MONAI/pull/5863 fixes this, please create a separate issue with the traceback if that's not the case.
