### ISSUE TITLE
.ndpi file format not supported by cucim

### ISSUE THREAD

**Issue by Ycblue** [Project-MONAI/MONAI#5599]
The WSIReader with 'cucim' backend is still unable to process WSIs with '.ndpi' extension. 
I am aware, that switching the backend to 'openslide' will work, but it is quite inconvenient since I have a large dataset with slides of different formats and I want to benefit from the speed of cucim backend. 

Just as a minimal example:

```
from monai.transforms import LoadImage
from monai.data.wsi_reader import WSIReader

train_transform = LoadImage(reader=WSIReader, backend='cucim', level=3)
filename = '/some/WSI/file/with.ndpi'
img_obj = train_transform(filename)
```

Is .ndpi support coming soon for Cucim or CuImage? 
If not, is there a way to automatically switch backends for the Reader, when a file is detected that cucim does not support? 

Thanks!

**Comment by wyli** [comment]
cc @gigony

**Comment by wyli** [comment]
thanks, this request won't be addressed by this codebase, so I'm closing it, please consider creating a new request at https://github.com/rapidsai/cucim
