### ISSUE TITLE
Nondeterministic in `HoVerNet`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#5609]
In the current `HoVerNet` implementation of MONAI, it uses `UpSample` with `NONTRAINABLE` mode which used [torch.nn.functional.interpolate()](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html#torch.nn.functional.interpolate) may cause nondeterministic.
https://github.com/Project-MONAI/MONAI/blob/d0db5fd9d4da3bc7027d22c52bb9c405c3b9e879/monai/networks/nets/hovernet.py#L535-L537

https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms

**Describe the solution you'd like**
It may need to be explained in the docstring.

**Comment by KumoLiu** [comment]
cc @JHancox @drbeh, could you please double confirm it?

**Comment by JHancox** [comment]
@KumoLiu Is this non-determinism specific to Upsample? Also, doesn't it use torch.nn.Upsample rather than torch.nn.functional.interpolate?

**Comment by KumoLiu** [comment]
Yes, it uses [torch.nn.functional.interpolate()](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html#torch.nn.functional.interpolate) in torch.nn.UpSample.
https://github.com/pytorch/pytorch/blob/b136f3f310aa01a8b3c1e63dc0bfda8fd2234b06/torch/nn/modules/upsampling.py#L156

**Comment by wyli** [comment]
thanks, I'm labelling this a feature request to update the docstring for both hovernet and UpSample
