### ISSUE TITLE
`HoVerNetNuclearTypePostProcessing` not working with default arguments

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5616]
**Describe the bug**
`HoVerNetNuclearTypePostProcessing` not working when `output_classes=None` and `return_centroid=False`, which are the default arguments for this transform.

**Comment by wyli** [comment]
isn't this test case cover what you described?

https://github.com/Project-MONAI/MONAI/blob/9adfb4b1e8f88e8620428d3bddb8e896ba09c8df/tests/test_hovernet_nuclear_type_post_processing.py#L52

**Comment by drbeh** [comment]
> isn't this test case cover what you described?
> 
> https://github.com/Project-MONAI/MONAI/blob/9adfb4b1e8f88e8620428d3bddb8e896ba09c8df/tests/test_hovernet_nuclear_type_post_processing.py#L52

@wyli, the test doesn't seem to check the type segmentation map. It should be fixed too.
