### ISSUE TITLE
`HoVerNetPostProcessing` to include all branches

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5617]
`HoVerNetNuclearTypePostProcessing` processes the nuclear type branch and already post-processed output of other branches. Thus for nuclear prediction and hovermap, there is no single post processing transform, and the user should put together 5 different transforms with the right sequence.

It would be great to simplify this process for the user who want to use HoVerNet post processing.

**Comment by wyli** [comment]
could you please put more details @drbeh

**Comment by drbeh** [comment]
> could you please put more details @drbeh

done!
