### ISSUE TITLE
Colab enabled notebooks

### ISSUE THREAD

**Issue by mibaumgartner** [Project-MONAI/MONAI#562]
**Is your feature request related to a problem? Please describe.**
It would be great to have example notebooks which can be directly run in Google Colab. IMO this would greatly improve the onboarding of new users.
Furthermore, including the notebooks und selected outputs inside the documentation could improve the usability, as can be seen in the [PyTorch Tutorials](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) (or in [rising](https://rising.readthedocs.io/en/stable/classification_2d_mednist.html) :) ) 

**Describe the solution you'd like**
See above :) 

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by Nic-Ma** [comment]
Hi @mibaumgartner ,

Thanks for your great suggestions, actually, we already have some Colab notebooks:
https://colab.research.google.com/drive/1wy8XUSnNWlhDNazFdvGBHLfdkGvOHBKe
We may add more notebooks later for the next version release.

Thanks.

**Comment by Nic-Ma** [comment]
We already have a very detailed document for PyTorch users:
https://colab.research.google.com/drive/1boqy7ENpKrqaJoxFlbHIBnIODAs1Ih1T

Thanks.
