### ISSUE TITLE
Intensity overflow in `ShiftIntensity`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#5621]
**Describe the bug**
Now in `ShiftIntensity`, the default is to use the input dtype as the output dtype. As we discussed in https://github.com/Project-MONAI/MONAI/pull/5535, it will cause an issue when the intensity goes beyond the original range. 
https://github.com/Project-MONAI/MONAI/blob/4cf6cf846468bc325d1695e9a13137f88d31daae/monai/transforms/intensity/array.py#L238

I followed @wyli's suggestion and tried to add `convert_data_dtype` referring to https://github.com/pytorch/vision/blob/ad128b753c7e8cc0c600dfddac22ff48fc73c9d9/torchvision/transforms/functional_tensor.py#L64, but I find that what they did may be different with what we want.

```
>>> a = torch.tensor([175, 175], dtype=torch.uint8)
>>> b = convert_image_dtype(a, dtype=torch.float32)
>>> print(b, b.dtype)
tensor([0.6863, 0.6863]) torch.float32
```

I try to add some warning in this [draft pr](https://github.com/Project-MONAI/MONAI/pull/5620). But that still doesn't solve the problem. Because even if the user sees the warning, the user cannot modify it because the `ShiftIntensity` does not have the `dtype` parameter passed in. And if we add `convert_data_dtype` for each transform, it still doesn't look right, because we change the intensity inside the transform, which may not be what the user wants. 
Like what @ericspod and @myron said in https://github.com/Project-MONAI/MONAI/pull/5535, adding a clip transform is indeed a good solution, but it does not solve the current bug, because the data dtype has been changed inside the transform, that is, the intensity has been changed.
At the moment, I have not thought of a better way than adding a WARNING. 
Do you have any suggestions? cc @wyli @ericspod @myron @Nic-Ma

**Comment by wyli** [comment]
I meant something like this:
```py
import torch
from torchvision.transforms.functional_tensor import _max_value

def safe_int_convert(val, dtype):
    m = _max_value(dtype)
    return val.clamp(0, m).to(dtype)


a = torch.tensor([-15, 260, 0])
b = a.to(torch.uint8)
print(b)
c = safe_int_convert(a, torch.uint8)
print(c)
```

it'll remove the overflow:
```
tensor([241,   4,   0], dtype=torch.uint8)
tensor([  0, 255,   0], dtype=torch.uint8)
```

**Comment by KumoLiu** [comment]
> I meant something like this:
> 
> ```python
> import torch
> from torchvision.transforms.functional_tensor import _max_value
> 
> def safe_int_convert(val, dtype):
>     m = _max_value(dtype)
>     return val.clamp(0, m).to(dtype)
> 
> 
> a = torch.tensor([-15, 260, 0])
> b = a.to(torch.uint8)
> print(b)
> c = safe_int_convert(a, torch.uint8)
> print(c)
> ```
> 
> it'll remove the overflow:
> 
> ```
> tensor([241,   4,   0], dtype=torch.uint8)
> tensor([  0, 255,   0], dtype=torch.uint8)
> ```

Hi @wyli, thanks for your explanation, and yes I know that but it still clips intensity inside the dtype convert. What if the user does not want to clip？Not sure whether should do it?

**Comment by wyli** [comment]
we can add a flag `safe` default to false (just do `a.to(dtype)`);
when `safe=True`,
```
out, *_ = convert_data_type(data=out, dtype=img.dtype, safe=True) 
```
we check and remove potential over/udnderflow

**Comment by KumoLiu** [comment]
@wyli Ok, I will do that. Thanks!
