### ISSUE TITLE
More robust `is_supported_format` suffix check

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#5634]
**Is your feature request related to a problem? Please describe.**
Sometimes the data I receive have uppercase suffixes (e.g., IMAGE.PNG), this could be recognized as the lowercase counterpart.

**Describe the solution you'd like**
Simply change this line
https://github.com/Project-MONAI/MONAI/blob/025c10751a1be596b3be9d0b64bb095e653804c3/monai/data/utils.py#L1103

to something like
```python
    if len(tokens) == 0 or all("." + s.lower() not in "".join(map(str.lower, tokens)) for s in suffixes):
```

If this is acceptable, I'm happy to open a PR.

**Comment by wyli** [comment]
Thanks, a PR would be great!
