### ISSUE TITLE
Add mypy typchecking of untyped functions for source code (not tests)

### ISSUE THREAD

**Issue by Shadow-Devil** [Project-MONAI/MONAI#5657]
**Is your feature request related to a problem? Please describe.**
MyPy currently only checks functions with type definitions. It would be great to add more type annotations to untyped functions, so they are also type checked.

Following config can be added to the `setup.cfg` so that MyPy also checks untyped functions:
```py
check_untyped_defs = True
```
But running MyPy with this setting will show ~1000 type errors.

**Describe the solution you'd like**
Adding type annotations to the codebase so that MyPy runs without errors even when enabling:
```py
check_untyped_defs = True
```

Since most of the type errors happen inside test cases this issue will only include the main source code. Test code can remain dynamically typed without any problems.

**Additional context**
Follow up of #5605.

**Comment by Shadow-Devil** [comment]
@wyli I have a question about this function: 
https://github.com/Project-MONAI/MONAI/blob/aef2ecccd4b4d0a663fb8a256ee36d8b00bdde10/monai/transforms/utils.py#L1634-L1650

Why should this work with `str, bytes` and forward the call to this function?
https://github.com/Project-MONAI/MONAI/blob/aef2ecccd4b4d0a663fb8a256ee36d8b00bdde10/monai/transforms/utils_pytorch_numpy_unification.py#L345-L360
This function only allows `NdarrayTensor` as its argument, so either we should extend the signature of this function to also include `str` and `bytes` or the `isinstance` should be adjusted.

**Comment by wyli** [comment]
I think otherwise the str, bytes will be treated as `Sequence`, going through line 1649 in `convert_to_contiguous`. please help add some docstring if it makes sense.

(also if it's easier for you, please feel free to group and make smaller PRs instead of addressing 1000+ typing issues in one PR)

**Comment by Shadow-Devil** [comment]
Currently, I go through the different modules so e.g. `utils`, `visualize` and create separate commits for each.

For the `convert_to_contiguos` function, I think it makes most sense to adjust the signature of `ascontiguousarray` since it also works for any other type (returning it back).

**Comment by Shadow-Devil** [comment]
It looks like most of the errors that mypy throws are inside the test cases. For now, I will only fix the typing for the actual source code and will configure mypy to only apply the stricter checking to it.
