### ISSUE TITLE
use reshape over view? any benefit to keep using view over reshape?

### ISSUE THREAD

**Issue by Joeycho** [Project-MONAI/MONAI#5684]
https://github.com/Project-MONAI/MONAI/blob/a05c20292cf0c293ee5964517de099c67deb9d64/monai/metrics/confusion_matrix.py#L166

Hi all,

I got `view-size-is-not-compatible-with-input-tensors-size-and-stride` error when using confusion_matrix.

Should we consider replacing view with reshape? or enforce contiguous() before view() operator? The reference is below.

https://discuss.pytorch.org/t/view-size-is-not-compatible-with-input-tensors-size-and-stride/121488/2?u=joeycho

**Comment by wyli** [comment]
thanks for reporting, agree that reshape is more robust in this case.
