### ISSUE TITLE
[Feature request] Expose ITK Image to MONAI MetaTensor conversion

### ISSUE THREAD

**Issue by ntatsisk** [Project-MONAI/MONAI#5708]
**Is your feature request related to a problem? Please describe.**
I am trying to convert easily between ITK Image and MONAI MetaTensor. Currently, I am using my own simple function that works for my partcular use case:

```
def itk_image_to_metatensor(img):
    reader = ITKReader(affine_lps_to_ras=False)
    img_array, meta_data = reader.get_data(img)
    img_array = convert_to_dst_type(img_array, dst=img_array, dtype=itk.D)[0]
    metatensor = MetaTensor.ensure_torch_and_prune_meta(img_array, meta_data)
    metatensor = EnsureChannelFirst()(metatensor)

    return metatensor
``` 
which more-or-less the code that lives insde `LoadImage`: https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/io/array.py#L273-L289

**Describe the solution you'd like**
I would like that MONAI provides two functions e.g. `itk_image_to_metatensor()` and `metatensor_to_itk_image()`. The implementation of the first already exists inside `LoadImage` transform (https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/io/array.py#L273-L289) and of the latter inside ITKWriter: https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_writer.py#L470-L517. So, ideally they just need to be exposed in order for them to be more easily usable.

Thanks in advance ;) 
--
xref for us: https://github.com/InsightSoftwareConsortium/ITKElastix/issues/126

**Comment by Shadow-Devil** [comment]
Hi, I would like to work on this issue. 
Where should these two functions be placed (maybe inside the [monai.data.utils.py](https://github.com/Shadow-Devil/MONAI/blob/6cb4ced0ea50b427a4065b4516be61b7a073abce/monai/data/utils.py) file)?

**Comment by wyli** [comment]
thanks @Shadow-Devil, there's an ongoing PR and possibly it's getting redirected to monai https://github.com/InsightSoftwareConsortium/itk-torch-transform-bridge/pull/6. 

@ntatsisk Please let us know if you need any help or prefer us to take over the PR redirection. cc @thewtex @HastingsGreer

**Comment by ntatsisk** [comment]
Hi @Shadow-Devil, @wyli, and thanks for the interest! Feel free to take over the PR redirection, and I can help as well. I am looking forward to seeing this integrated to MONAI. :)  

I will try to do the final changes in the PR as soon as possible so that it is ready for the transfer.

**Comment by Spenhouet** [comment]
The proposed functions might not properly work, see: https://github.com/InsightSoftwareConsortium/itk-torch-transform-bridge/issues/7

I suggest we should solve this first.

**Comment by ibro45** [comment]
In case someone knows what's causing this https://github.com/Project-MONAI/MONAI/issues/6985
