### ISSUE TITLE
[Feature request] Plugin/Module to visualize MONAI Transforms

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAI#5711]
**Is your feature request related to a problem? Please describe.**

There is no tool to visualize the effect of MONAI transforms on a custom dataset.

MONAI Label users will highly benefit from a tool/plugin/module that allows them to visualize the effect of the MONAI transforms applied to their dataset. 

I've got lots of questions about which transforms are best to do data augmentation or to preprocess their dataset: window scale intensity, random flipping, random rotation, scaling, affine transform, etc.

The idea of this tool is to facilitate the selection of MONAI transforms that researchers can use [here](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/trainers/segmentation.py#L74-L98) to do data augmentation. 

Ideally, researchers can use this plugin with individual transform and/or a set of random transformations (Compose).

**Describe the solution you'd like**
A MONAI tool/plugin/module that allows users to visualize the effects of the MONAI transforms applied to their dataset.

**Comment by dzenanz** [comment]
You could get the feel of some data augmentation transforms by using [TorchIO's Slicer plugin](https://torchio.readthedocs.io/interfaces/slicer.html). Maybe MONAI could make a similar thing? The easiest thing would be to add MONAI-specific transforms to the [exiting plugin code](https://github.com/fepegar/SlicerTorchIO). If the author of the plugin @fepegar doesn't like that, a fork could be made.

**Comment by fepegar** [comment]
I think adding MONAI transforms to the TorchIO extension might make things confusing, so forking would possibly make more sense. But I might be wrong!

**Comment by arpinerap** [comment]
I agree with @diazandr3s. Its really hard to manage so huge amount of possibilities in transforms that Monai offer without a graphic interface. TorchIO´s Slicer plugin is a wonderfull tool but with very little options. Developing a good data augmentation strategy without being able to know what transforms exactly do with your images is really hard. Please, reconsider @diazandr3s request, no doubt I´ll be the first user. Thanks in advance!

**Comment by dzenanz** [comment]
If no one else plans to work on this, I could take a crack over the next weeks. @wyli could you assign it to me?

**Comment by Nic-Ma** [comment]
Hi @dzenanz ,

Sure, welcome contribution!

Thanks.

**Comment by wyli** [comment]
given that a monai `Compose` object could be created from a yaml/json config, e.g.
https://github.com/Project-MONAI/MONAI/blob/315d2d2fc29a83fc863bfcb6088e8d06f6cae027/tests/testing_data/transform_metatensor_cases.yaml#L50-L70

is it possible/useful to make a generic slicer plugin visualising a set of transforms in a user-specified config? cc @SachidanandAlle any suggestions for @dzenanz to get started?

**Comment by dzenanz** [comment]
I created [my fork](https://github.com/dzenanz/SlicerTorchIO) and I am looking at [Slicer extension developing docs](https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html), so the timing on this suggestion is excellent.

**Comment by dzenanz** [comment]
I will probably need these conversion routines:
https://github.com/Project-MONAI/MONAI/commit/2a8c8cd4771f58b11b7ee5d6168de6cd0bf82861#diff-ca2b9fd231511881f60bf8fc5364948993600f30797edd36c976f013d57738b5R357-R361

**Comment by wyli** [comment]
@SachidanandAlle put together an initial codebase here: https://github.com/Project-MONAI/SlicerMONAIViz 

all contributions are welcomed :)

**Comment by dzenanz** [comment]
This is great! I tried to use it and immediately have some feedback. The images loaded via MonaiViz module have different direction matrix from images drag-dropped into Slicer (RAS vs LPS convention). Those buttons for editing the transform list should have mouse-over hint which explains what each button does. The dictionary flavored transforms should have one argument prefilled: `keys`, and it should be set to `['image', 'label']`. I also have a suggestion about installation docs, but I will do that via a PR.

**Comment by dzenanz** [comment]
PR https://github.com/Project-MONAI/SlicerMONAIViz/pull/1 created.

**Comment by dzenanz** [comment]
Adding tooltips was easy, too. PR: https://github.com/Project-MONAI/SlicerMONAIViz/pull/2.

**Comment by wyli** [comment]
thank you @SachidanandAlle @dzenanz @diazandr3s -- closing this for now, please file follow-up tickets here https://github.com/Project-MONAI/SlicerMONAIViz/issues.

**Comment by dzenanz** [comment]
PR https://github.com/Project-MONAI/SlicerMONAIViz/pull/5 is the last of my initial suggestions. The other PRs implement the other suggestions I raised in https://github.com/Project-MONAI/MONAI/issues/5711#issuecomment-1444352944.
