### ISSUE TITLE
Enhance HoverNet to support torchvision's resnet50 pretrained weights

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#5717]
The encoder part of HoverNet follows the reference, and is a version of preact-resnet50. Our implementation has the same structure except some different layer names, thus we defined a function `_load_pretrained_encoder` to do the remap to load the provided weights from the reference.
However, the encoder is not a generic version and cannot match torchvision's standard resnet50. Therefore, it would be nice to adapt our implementation and support this version too.

I already tried to add this feature, and submitted a draft PR (https://github.com/Project-MONAI/MONAI/pull/5688), and I will do some changes and make it for review.

cc @Nic-Ma @wyli @KumoLiu

**Comment by wyli** [comment]
is it possible to in general allow for a 'backbone' module as the encoder, like the MILModel?

https://github.com/Project-MONAI/MONAI/blob/492ebc6516c3a82368f6779d24f101617e60f92d/monai/networks/nets/milmodel.py#L41-L44

**Comment by Nic-Ma** [comment]
> is it possible to in general allow for a 'backbone' module as the encoder, like the MILModel?
> 
> https://github.com/Project-MONAI/MONAI/blob/492ebc6516c3a82368f6779d24f101617e60f92d/monai/networks/nets/milmodel.py#L41-L44

Hi @yiheng-wang-nv ,

I agree with @wyli , maybe you can also add support for torch `Module` type arg for `backbone`?

Thanks.

**Comment by yiheng-wang-nv** [comment]
Hi @wyli and @Nic-Ma , thanks for the suggestions. Maybe I can try to modify my previous trial (https://github.com/Project-MONAI/MONAI/pull/5664). milmodel is a good example, I will think about how to enhance my PR.

**Comment by yiheng-wang-nv** [comment]
Hi @wyli and @Nic-Ma , my preliminary opinion is that there are many hard coded places in our implementation which makes the whole network not very flexible (for example: it only support 270 or 256 input, the freeze way is not generic, the decoder  part is fixed so far). Therefore, if making a "backbone" arg, it still cannot support many different backbones unless we do fully refactor the class.

In addition, according to @KumoLiu 's experiments, change the structure (such as using the standard resnet50 structure) rather than keep the original preact-resnet50 structure decreases the performance at least in CONSEP dataset. It's the reason why I closed #5664 and modified #5688 to implement a way to: support loading different weights, but keep the structure the same.

Hi @wyli , @Nic-Ma , what do you think? Thanks!

**Comment by wyli** [comment]
thanks @yiheng-wang-nv for the investigation, maybe later we can work on a second version to improve the flexibility and keep #5688 if it's needed for this release cc @Nic-Ma

**Comment by Nic-Ma** [comment]
> thanks @yiheng-wang-nv for the investigation, maybe later we can work on a second version to improve the flexibility and keep #5688 if it's needed for this release cc @Nic-Ma

I agree, what do you mean "keep https://github.com/Project-MONAI/MONAI/pull/5688 if it's needed for this release"? I think you mean to merge #5688 first?

Thanks.

**Comment by wyli** [comment]
> > thanks @yiheng-wang-nv for the investigation, maybe later we can work on a second version to improve the flexibility and keep #5688 if it's needed for this release cc @Nic-Ma
> 
> 
> 
> I agree, what do you mean "keep https://github.com/Project-MONAI/MONAI/pull/5688 if it's needed for this release"? I think you mean to merge #5688 first?
> 
> 
> 
Yes I think we merge if needed
