### ISSUE TITLE
rename `regist_class` to `register_class`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5724]
I think 'regist' is a typo, will correct it in various places
- https://github.com/Project-MONAI/MONAI/blob/8aafd882aedc2bc54e93fb14e02e4a000bca2869/monai/networks/nets/flexible_unet.py#L43
- https://github.com/Project-MONAI/MONAI/blob/8aafd882aedc2bc54e93fb14e02e4a000bca2869/monai/networks/nets/flexible_unet.py#L41

cc @binliunls @Nic-Ma

**Comment by binliunls** [comment]
Hi @wyli ,
     It is a typo issue. Thank you very much for your update.

Thanks,
Bin
