### ISSUE TITLE
rename `apply_gaussion` to `apply_gaussian`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5725]
i think `gaussion` is a typo

https://github.com/Project-MONAI/MONAI/blob/ff12159143aa72e5ba6bbba9aad2cc6688519314/monai/apps/nuclick/transforms.py#L332

cc @SachidanandAlle

**Comment by SachidanandAlle** [comment]
Its a private method.. we can rename it.. thanks 👍
