### ISSUE TITLE
Adding a loss mask? 

### ISSUE THREAD

**Issue by petteriTeikari** [Project-MONAI/MONAI#573]
Are there any plans to add an easy way to include "loss mask" to `Dataset` class for segmentation task? As what I understood, it only takes `img` and `seg`?

For example I have such CT volumes with the following "windowing" that could be masked away

![image](https://user-images.githubusercontent.com/1060514/84707668-076fbb80-af57-11ea-9bba-be1183c43d68.png)

And in general the following behavior could be a nice feature

https://github.com/deepmind/deepmind-research/blob/cf0a9ca46058a61e8b66bc8708cd35ac77209bc6/hierarchical_probabilistic_unet/geco_utils.py#L100

**Comment by Nic-Ma** [comment]
Hi @petteriTeikari ,

Thanks for your interest here.
Actually, the Dataset in MONAI accepts `dict` type input data.
So you can put a datalist like:
```py
[
    {"img": img1, "seg": seg1, "loss_mask": mask1},
    {"img": img2, "seg": seg2, "loss_mask": mask2},
    {"img": img3, "seg": seg3, "loss_mask": mask3},
    ... ...
]
```

And BTW, suggest using `CacheDataset` to accelerate your training process.

Thanks.

**Comment by myron** [comment]
@petteriTeikari 
We also have the masked dice loss, for convenience, which should work in your case (if you're using dice)
https://github.com/Project-MONAI/MONAI/blob/22d975b1d8c374b2ba5a360140ccd983be193311/monai/losses/dice.py#L139

**Comment by petteriTeikari** [comment]
Thanks for the clarifications @Nic-Ma and @myron that indeed was something that I was trying to find from the documentation

**Comment by petteriTeikari** [comment]
> @petteriTeikari
> We also have the masked dice loss, for convenience, which should work in your case (if you're using dice)
> https://github.com/Project-MONAI/MONAI/blob/22d975b1d8c374b2ba5a360140ccd983be193311/monai/losses/dice.py#L139

@myron Do you have any plans to add the "masked"-option for all types of losses? As in, would be niceto play with some own custom losses and all your off-the-shelf ones with the loss masking option

**Comment by eddyleelin** [comment]
Sorry, could I ask what is the current status of this issue? @wyli 
It seems like currently `MaskedDiceLoss` is the only type of segmentation loss with an implementation of masking. Would it be beneficial to extend this to the other types of losses, such as Tversky or Focal Losses? Perhaps with a wrapper function like [MultiScaleLoss](https://docs.monai.io/en/latest/losses.html#multiscaleloss)? Thanks 😄

**Comment by wyli** [comment]
sure @eddyleelin, let me look into this...
