### ISSUE TITLE
MetricsReloaded support

### ISSUE THREAD

**Issue by brudfors** [Project-MONAI/MONAI#5740]
The MetricsReloaded package under Project-MONAI (https://github.com/Project-MONAI/MetricsReloaded), developed by @csudre, is a recommendation framework for biomedical image analysis validation. As already discussed with @wyli, @Nic-Ma, @csudre and others; being able to use this framework in MONAI would be very valuable. The aim of this issue is to integrate MetricsReloaded support into MONAI.

**Comment by wyli** [comment]
closing this by

- https://github.com/Project-MONAI/MONAI/pull/5741
- https://github.com/Project-MONAI/MONAI/pull/5920

the other packaging/demo tasks are tracked https://github.com/Project-MONAI/MONAI/milestone/91 with separate tickets.
