### ISSUE TITLE
Auto3D data analysis should use multiple threads

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAI#5743]
Data analysis is running sequentially with single thread. When using duplicating instance22 100 times, this step takes 6+ hours to complete. Please use multiple thread/ works as the analysis step is independent of each other. However, you need to aggregate the result summary

**Comment by wyli** [comment]
please use the `worker: int` parameter provided:

https://github.com/Project-MONAI/MONAI/blob/c10cdd226d94f06600a929de13c5d78bda6e8a10/monai/apps/auto3dseg/data_analyzer.py#L120
