### ISSUE TITLE
Auto3d Add function to generate the shell scripts which can run separately. 

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAI#5747]
**Is your feature request related to a problem? Please describe.**
Currently Auto3d generates a markdown telling you what command to run if you want to run a single network architecture 
it would be nice to generate a bash script directly so user can directly run it 

As a work around I go into the code and use the private function 
cmd, devices_info = algo._create_cmd(train_param)
instead simply create the bash script to export cuda device=device_info then run the cmd as 
(time  $cmd )| tee log.txt

**Comment by myron** [comment]
thank you, are you trying to run a single algo?

you can simply call (from any generated algo folder)
`python sripts/train.py run --config_file=configs/hyper_parameters.py`
or for multigpu
`torchrun sripts/train.py run --config_file=configs/hyper_parameters.py`

the device_info is not needed (it's only to support running from notebooks).  
the scripts folder already has train.py, eval.py, infer.py,  if we add ".sh" one-liner aliases of these, it will a lot of files in the scripts folder

**Comment by wyli** [comment]
please see https://github.com/Project-MONAI/tutorials/blob/main/auto3dseg/docs/bundle.md
