### ISSUE TITLE
Inconsistencies post-processing results in HoVerNet

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#5750]
**Describe the bug**
There are some inconsistencies between our post-processing implementation and the original author’s post-processing implementation which may be a MONAI 1.1 blocker issue.

![image](https://user-images.githubusercontent.com/55491388/207761462-a09fa658-7412-4644-88c6-4b5b4af9ef5e.png)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Please note this may be a blocker issue for MONAI 1.1. @KumoLiu is working on it right now.

Thanks.
