### ISSUE TITLE
Resume training in AutoRunner after interruptions

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/MONAI#5756]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to resume training in `AutoRunner`.
Issues is better described in #5754 

**Describe the solution you'd like**
When the training in `AutoRunner` is interrupted, the user can skip the trained algorithms and continue the training on the ones that are not started before. 

For example, there are 4 algorithms and 5 folds for each algorithm. The total number of trainings to perform is 20. When `AutoRunner` executes the 10th training, something happens and interrupts/cancels the training. When the user would like to continue the work in the same folder, they can run the same command and the training will restart from the 10th, instead of all over from the beginning.

**Describe alternatives you've considered**
The current solution is doing it manually:

```python
import os
import warnings
from monai.auto3dseg import algo_from_pickle

warnings.filterwarnings("ignore")

output_folder = "work_dir"
history_trained = []
history_untrained = []
tasks = []
for name in sorted(os.listdir(output_folder)):
    write_path = os.path.join(output_folder, name)

    if not os.path.isdir(write_path):
        continue

    obj_filename = os.path.join(write_path, "algo_object.pkl")
    if not os.path.isfile(obj_filename):  # saved mode pkl
        continue

    algo, algo_meta_data = algo_from_pickle(obj_filename, template_path=None)
    algo.template_path = algo_meta_data["template_path"]

    if "best_metrics" in algo_meta_data:
        history_trained.append({name: algo})
    else:
        history_untrained.append({name: algo})
        tasks.append(algo)

print("history_trained: ", history_trained)
print("history_untrained: ", history_untrained)

train_param = {}
for algo in tasks:
    algo.train(train_param)
```

**Additional context**

**Comment by myron** [comment]
yes, good point.  We currently save progress of major steps only in cache.yaml (data analysis, generation, full training..)
we can reuse same file cache.yaml (or use a new one) to save the completion of each algo (each fold) to skip them on the re-run. 

after code folders are generated, we can create a key (in cache.yaml)   dict["training"] ={"algoA_0" : False, "algoA_1": False...}   indicating False/True if that training step was completed

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/commit/e4b313d59b2702cd2a441d7a557650ced78dc6c8 please consider creating new ticket for further enhancements.
