### ISSUE TITLE
randomized torchvision transforms API change since 1.0.1

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5774]
**Describe the bug**
since monai 1.1.0rc2, `RandTorchVisiond` has removed the `prob` argument and it doesn't support 'randomized apply' (via this commit https://github.com/Project-MONAI/MONAI/commit/3873d236a732b31fbf33ed297bccaa1c2a93873f), .

so the previously randomized transform in 1.0.1, for example:

```py
from monai.transforms import RandTorchVisiond

xform = RandTorchVisiond(keys="image", prob=0.5, name="ColorJitter", brightness=0.25, contrast=0.75)
```

should be replaced by something like (not fully tested yet)

```py
from monai.transforms import RandLambdaD, TorchVision

tv_xform = TorchVision(name="ColorJitter", brightness=0.25, contrast=0.75)
xform = RandLambdaD(keys="image", prob=0.5, func=tv_xform)
```

cc @drbeh @KumoLiu @Nic-Ma @SachidanandAlle

**Comment by wyli** [comment]
a workaround was added to the model zoo https://github.com/Project-MONAI/model-zoo/pull/280 which should address the syntax error but might change the previous training outcomes. this model zoo changes will need a follow up.

**Comment by Nic-Ma** [comment]
Hi @KumoLiu , @drbeh ,

Could you please help confirm the pathology tutorials and bundles with the latest MONAI v1.1 package?
Hopefully every tutorial or bundle should work fine, otherwise, we need to update them ASAP.

Thanks in advance.

**Comment by KumoLiu** [comment]
Hi @Nic-Ma, I have tested all pathology tutorials and bundles.
In pathology_nuclei_classification, I find some errors when running the evaluation, here are the error [logs](https://github.com/Project-MONAI/MONAI/files/10311760/cls.log).
In pathology_nuclick_annotation, there is also some error when running the evaluation, here is the error [logs](https://github.com/Project-MONAI/MONAI/files/10311762/test.log), seems post-processing is wrong. cc @SachidanandAlle.

Thanks!

**Comment by SachidanandAlle** [comment]
Is your validation dataset matching the one mentioned in the example:
https://github.com/Project-MONAI/model-zoo/tree/dev/models/pathology_nuclei_classification#preprocessing

Can you share some part of yours..?
For both classification and nuclick the input is same (pre-processed).

Both the errors are possibly due to incorrect input image/label.  You can double-check if the path and files/input are correct wrt dataset.json.

**Comment by KumoLiu** [comment]
Hi @SachidanandAlle, yes the data is prepared by this [notebook](https://github.com/Project-MONAI/tutorials/blob/main/pathology/nuclick/nuclick_training_notebook.ipynb). Here is a screenshot of the JSON file and I also checked the file path.
<img width="846" alt="Screen Shot 2022-12-28 at 12 52 47" src="https://user-images.githubusercontent.com/55491388/209759501-e824a082-15fa-4271-b969-fb05bc969f3f.png">

**Comment by SachidanandAlle** [comment]
Even the training is not working?

**Comment by KumoLiu** [comment]
> Even the training is not working?

Training and inference work, only evaluation not works.

**Comment by KumoLiu** [comment]
> > Even the training is not working?
> 
> Training and inference work, only evaluation not work.

**Comment by SachidanandAlle** [comment]
Are there enough records in dataset Json for validation? During the training if evaluation runs then explicit evaluation.json should be working also.. only it as additional save image transform in post.. and rest gets inherited from train.json

Currently on a break.. will check it out after holidays.. evaluation.json is not really a blocker for anyone to try.. train and infer and tutorials are good enough for now.. if there is a real problem in evaluation Json.. it shall be fixed post holidays

**Comment by KumoLiu** [comment]
> Are there enough records in dataset Json for validation? During the training if evaluation runs then explicit evaluation.json should be working also.. only it as additional save image transform in post.. and rest gets inherited from train.json
> 
> Currently on a break.. will check it out after holidays.. evaluation.json is not really a blocker for anyone to try.. it's no use for nucleus usecase.. train and infer and tutorials are good enough for now.. if there is a real problem in evaluation Json.. it shall be fixed post holidays

Of course, have a good holiday! I will try to take a look at it.

**Comment by drbeh** [comment]
Hi @SachidanandAlle, does https://github.com/Project-MONAI/model-zoo/pull/292 address the issue raised here? Can we close this?

**Comment by SachidanandAlle** [comment]
Ok

**Comment by ericspod** [comment]
I think this is resolved so I'm closing, if not we should create a new issue for v1.3.
