### ISSUE TITLE
LocalNet Upsampling

### ISSUE THREAD

**Issue by fvlntn** [Project-MONAI/MONAI#5782]
Hello,

I've been using your LocalNet/GlobalNet and there was something off with my DDFs for a long time but couldn't think there was a direct error in your implementation. After checking it, there indeed is one small mistake.

Original is using Trilinear Upsampling (look at papers or DeepReg).
But here it is using F.interpolate which uses "Nearest" interpolation by default, both in https://github.com/Project-MONAI/MONAI/blob/97918e46e0d2700c050e678d72e3edb35afbd737/monai/networks/blocks/regunet_block.py#L189 and in https://github.com/Project-MONAI/MONAI/blob/97918e46e0d2700c050e678d72e3edb35afbd737/monai/networks/nets/regunet.py#L339 .

Try looking at your output DDFs with LocalNet, it is really non-linear. 
Changing both method to "trilinear" for 3D data fixes the problem and makes the DDFs smooth like in the LocalNet paper.

F.interpolate() => F.interpolate(mode="trilinear")
Linear/Bilinear/Trilinear depending on dimensions.

Thanks a lot for your hard work,
Franck

**Comment by fvlntn** [comment]
Maybe torch updated F.interpolate to use "nearest" by default in a recent update. In such case you should also check all F.interpolate uses?

**Comment by wyli** [comment]
thanks for reporting, I'll make a PR to make it flexible.

cc @yiheng-wang-nv do you have any experience of different interpolating modes here: https://github.com/Project-MONAI/MONAI/blob/c5ea694985dc1e8eeef075da3a65b2c2fc2f9a8e/monai/networks/nets/dynunet.py#L272
