### ISSUE TITLE
`build-docs` workflow failed

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#5793]
The workflow failed in recent PRs such as: https://github.com/Project-MONAI/MONAI/actions/runs/3805194186/jobs/6472957035#step:7:243

**Comment by yiheng-wang-nv** [comment]
it may due to `sphinx-build` new release: https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-released-dec-29-2022

**Comment by wyli** [comment]
looks like the issue here https://github.com/pydata/pydata-sphinx-theme/issues/1094 I'll update the workaround in #5794
