### ISSUE TITLE
simplify the configparser usage to get parsed attributes easily

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5804]
**Is your feature request related to a problem? Please describe.**

the current usage looks tedious (https://github.com/Project-MONAI/research-contributions/blob/07da7ad36a0b218556a427f3bc5292a772c30f60/auto3dseg/algorithm_templates/segresnet2d/scripts/infer.py#L34-L50)

```py
parser = ConfigParser()
parser.read_config(config_file_)
parser.update(pairs=_args)

data_file_base_dir = parser.get_parsed_content("data_file_base_dir")
data_list_file_path = parser.get_parsed_content("data_list_file_path")
self.fast = parser.get_parsed_content("infer")["fast"]
self.num_adjacent_slices = parser.get_parsed_content("num_adjacent_slices")
self.num_sw_batch_size = parser.get_parsed_content("num_sw_batch_size")
self.output_classes = parser.get_parsed_content("output_classes")
self.overlap_ratio = parser.get_parsed_content("overlap_ratio")
self.patch_size_valid = parser.get_parsed_content("patch_size_valid")
softmax = parser.get_parsed_content("softmax")

ckpt_name = parser.get_parsed_content("infer")["ckpt_name"]
data_list_key = parser.get_parsed_content("infer")["data_list_key"]
output_path = parser.get_parsed_content("infer")["ouptut_path"]
```

this is a feature request of simplifying the APIs to support more user-friendly calls
to get the parsed config as attributes directly:

```py
cfg = ConfigParser()
cfg.read_config(config_file_)
cfg.update(pairs=_args)

data_file_base_dir = cfg.data_file_base_dir
data_list_file_path = cfg.data_list_file_path
self.fast = cfg.infer.fast
...
```

cc @Project-MONAI/core-reviewers

**Comment by Shadow-Devil** [comment]
Hi, I would like to work on this issue. 
Is this the only place where this simplification should be done or 
should I also look out for other places with similar `parser.get_parsed_content()` usage?

**Comment by Shadow-Devil** [comment]
E.g., here: https://github.com/Project-MONAI/research-contributions/blob/07da7ad36a0b218556a427f3bc5292a772c30f60/auto3dseg/algorithm_templates/dints/scripts/dummy_runner.py#L37-L49

**Comment by Shadow-Devil** [comment]
While searching through the files, I think I found a typo: https://github.com/Project-MONAI/research-contributions/blob/07da7ad36a0b218556a427f3bc5292a772c30f60/auto3dseg/algorithm_templates/dints/scripts/infer.py#L48
It should be `output_path` not `ouptut_path`, right?

**Comment by Shadow-Devil** [comment]
I think I got the issue wrong, 
it's not about replacing the code inside research-contributions, 
but to simplify the API so that the code works as described.
But I still want to work on it.

**Comment by Shadow-Devil** [comment]
My proposal would be to implement it the following way:
```python
    def __getattr__(self, key):
        """
        Get the config by id.

        Args:
            key: id to specify the expected position. See also :py:meth:`__getitem__`.

        """
        return self[key]
```
Now the implementation just forwards the call to `__getitem__()` so we don't need to duplicate the code.
From the [python documentation](https://docs.python.org/3/reference/datamodel.html#object.__getattr__): _Called when the default attribute access fails..._

So the method won't be called if a defined method/property is tried to be accessed (e.g. `config` or `get_parsed_content()`)

**Comment by wyli** [comment]
sounds great, I'm assigning this to you , it's ok if the first PR only works for the shallow structure...I haven't thought in detail about the nested case but we can always follow up and improve it.

(also thanks for reporting the typo!)

**Comment by Nic-Ma** [comment]
Sounds good for the initial PR idea, I think we can think about the nested case together later.
But personally I feel the nested case is "must-have", otherwise, the user experience may be strange.

Thanks.

**Comment by Shadow-Devil** [comment]
An approach similar to [ConfigArgParse](https://github.com/bw2/ConfigArgParse) would be nice. Here you first configure your parser and then call `parser.parse_args()` which returns an `Namespace` with the parsed configuration items as attributes (also nested).
