### ISSUE TITLE
How to configure Rand3DElastic to achieve the same results as torchio.RandomElasticDeformation?

### ISSUE THREAD

**Issue by wojiazaiyugang** [Project-MONAI/MONAI#5808]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/3267

<div type='discussions-op-text'>

<sup>Originally posted by **Spenhouet** November  5, 2021</sup>
Until now we are using torchio's [RandomElasticDeformation](https://torchio.readthedocs.io/transforms/augmentation.html#randomelasticdeformation). This performs a grid based deformation.
I'm now trying to achieve the same results with [Rand3DElastic](https://docs.monai.io/en/latest/transforms.html?highlight=blur#rand3delastic) but I can not make it work.

Are they even the same logic / operation (generally)?

I fail to understand the parameters which Rand3DElastic requires and what effect they have.

Example results:

|   | Original | [RandomElasticDeformation](https://torchio.readthedocs.io/transforms/augmentation.html#randomelasticdeformation) | [Rand3DElastic](https://docs.monai.io/en/latest/transforms.html?highlight=blur#rand3delastic) |
| --- | --- | --- | --- |
| Parameter |  | num_control_points=7, max_displacement=7.5, locked_borders=2, p=1.0  | sigma_range=(5, 7), magnitude_range=(50, 150), mode=[GridSampleMode.BILINEAR, GridSampleMode.NEAREST], prob=1.0  |
| Image | ![image](https://user-images.githubusercontent.com/7819068/140506189-1de62021-a9ae-445c-9bbd-a29e7ea3c1e3.png) | ![image](https://user-images.githubusercontent.com/7819068/140506391-f47eee6c-cdea-4dd0-9649-adb174ab464f.png)  | ![image](https://user-images.githubusercontent.com/7819068/140506509-c722427f-f2ae-4d07-9e81-6835586e05f6.png) |
| Label | ![image](https://user-images.githubusercontent.com/7819068/140506626-c0ec3353-4761-44ab-8eae-f582e466d67e.png) | ![image](https://user-images.githubusercontent.com/7819068/140506761-32fcf810-5c77-4dd5-bd50-4771690e6d3d.png) | ![image](https://user-images.githubusercontent.com/7819068/140506695-5293005e-c883-4a21-b473-63ef94c0830f.png) |

Especially, [Rand3DElastic](https://docs.monai.io/en/latest/transforms.html?highlight=blur#rand3delastic) introduces these undesired humps:

![image](https://user-images.githubusercontent.com/7819068/140507520-c6d18c4e-5b9d-4119-85b0-2f186964648f.png)

Maybe someone could give an intuition on how to set the parameters to achieve a similar result to torchio (without these humps)?</div>

**Comment by wyli** [comment]
Rand3DElastic is currently controlled by `sigma_range` (the spatial extent to deform) and `magnitude_range` (the multiplier to the random offsets),
here are some visualization of the deformed grids:
<img src=https://user-images.githubusercontent.com/831580/210778858-1d3ed388-de63-4fc9-a81f-1f398c32fdc7.png width=400><img src=https://user-images.githubusercontent.com/831580/210778865-d83a6ffd-2d73-4d39-8972-ed67a13129da.png width=400>
<img src=https://user-images.githubusercontent.com/831580/210778869-f74ed218-9c77-4d7c-bd57-c2492d768fe7.png width=400><img src=https://user-images.githubusercontent.com/831580/210778872-6a876a91-d791-4542-9b6b-aa528f05ccb3.png width=400>



script that I used to generate the figures:
```py
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.collections import LineCollection

import monai.transforms as mt
from monai.networks.layers import GaussianFilter
from monai.utils import convert_to_tensor
np.random.seed(0)

sigma_range = (5, 5)
magnitude_range = (100, 100)

sp_size = (80, 80)
device = "cpu"
rotate_range = None
shear_range = None
translate_range = None
scale_range = None

grid = mt.utils.create_grid(spatial_size=sp_size, device=device, backend="torch")
sigma = np.random.uniform(sigma_range[0], sigma_range[1])
gaussian = GaussianFilter(spatial_dims=2, sigma=sigma, truncated=3.0).to(device)
rand_offset = np.random.uniform(-1.0, 1.0, [3] + list(sp_size)).astype(np.float32, copy=False)
offset = convert_to_tensor(rand_offset, device=device).unsqueeze(0)
mag = np.random.uniform(magnitude_range[0], magnitude_range[1])
grid[:3] += gaussian(offset)[0] * mag
rand_grid = mt.RandAffineGrid(
    rotate_range=rotate_range,
    shear_range=shear_range,
    translate_range=translate_range,
    scale_range=scale_range,
    device=device,
)
grid = rand_grid(grid=grid)

ax = plt.gca()
xx = grid[0]
yy = grid[1]
segs1 = np.stack((xx, yy), axis=2)
segs2 = segs1.transpose(1, 0, 2)
ax.add_collection(LineCollection(segs1, color="C0"))
ax.add_collection(LineCollection(segs2, color="C0"))
ax.autoscale()
ax.set_aspect("equal")
plt.title(f"sig={sigma_range}, mag={magnitude_range}")
plt.show()

```
