### ISSUE TITLE
Consistent usage of annotation syntax

### ISSUE THREAD

**Issue by Shadow-Devil** [Project-MONAI/MONAI#5835]
**Is your feature request related to a problem? Please describe.**
There are already some files using the new syntax for annotations. 
https://github.com/Project-MONAI/MONAI/search?q=from+__future__+import+annotations
The old type aliases from the `typing` module are deprecated starting with python 3.9,
 so to be future-prove it makes sense to migrate to the new style.

**Describe the solution you'd like**
Use `from __future__ import annotations` in all source files using annotations, so we have consistent usage (and not only in ~5 files).
The new annotations are also more readable e.g. `Optional[Union[List[str], str]]` vs. `list[str] | str | None`.

Secondly, this issue includes changing `from typing import Callable, Sequence, ...` to `from collections.abc import Callable, Sequence, ...` since the ones in the `typing` module are deprecated. They are interchangable even for `isinstance` checks (see also [this stackoverflow thread](https://stackoverflow.com/questions/62547848/should-isinstance-check-against-typing-or-collections-abc)).

**Additional context**
- [PEP 585](https://peps.python.org/pep-0585/)
- [Documentation to the typing module](https://docs.python.org/3.10/library/typing.html)
- Old discussion about this topic: https://github.com/Project-MONAI/MONAI/pull/4150#issuecomment-1104115319

**Comment by drbeh** [comment]
Hi @Shadow-Devil, thanks for initiating this improvement.
I agree that updating the typing is a reasonable task since many of them are already deprecated although there is not a defined plan for when they are being removed (maybe in few years).

**Comment by Shadow-Devil** [comment]
From the typing module documentation:
> The deprecated types will be removed from the [typing](https://docs.python.org/3.10/library/typing.html#module-typing) module in the first Python version released 5 years after the release of Python 3.9.0. See details in [PEP 585](https://www.python.org/dev/peps/pep-0585)—Type Hinting Generics In Standard Collections.

So it's not urgent, but I think the new syntax is still more readable and it would be better to have a consistent code style IMO.

**Comment by drbeh** [comment]
Exactly, 3.9.0 was released in 2020 so they should be removed in 2025 but no release has officially defined to remove them.
