### ISSUE TITLE
MetricsReloaded Wrapper as a monai handler

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5849]
Follow up of https://github.com/Project-MONAI/MONAI/pull/5741
the MetricsReloaded Wrapper could be made available as a component in `monai.handlers`, 
and so that it can work with monai.engine and model bundles written with workflows.

cc @brudfors @Nic-Ma

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help on this ticket?

Thanks in advance.

**Comment by brudfors** [comment]
Ni @Nic-Ma, For your info, I am meeting with Carole tomorrow to discuss the MetricsReloaded API, so should be able to work on this shortly thereafter.

**Comment by Nic-Ma** [comment]
> Ni @Nic-Ma, For your info, I am meeting with Carole tomorrow to discuss the MetricsReloaded API, so should be able to work on this shortly thereafter.

Looks great. Don't worry, I think @yiheng-wang-nv may already implemented the handler for `MetricsReloaded`, it's not a big task.

Thanks.
