### ISSUE TITLE
Make MLPBlock compatible with diffusion models

### ISSUE THREAD

**Issue by Warvito** [Project-MONAI/MONAI#5853]
**Is your feature request related to a problem? Please describe.**
To be able to re-use the [MLPBlock](https://github.com/Project-MONAI/MONAI/blob/fdd07f36ecb91cfcd491533f4792e1a67a9f89fc/monai/networks/blocks/mlp.py) in the implementation of diffusion models (developed in MONAI Generative Models (related to https://github.com/Project-MONAI/GenerativeModels/issues/141)), it is necessary to be able to use the GEGLU activation function (from https://arxiv.org/pdf/2002.05202.pdf) in the block.

If GEGLU is selected, it would also be necessary to change self.linear1 to `nn.Linear(hidden_size, mlp_dim* 2)`. 

**Describe the solution you'd like**
Some implementations create a GEGLU block as a separated class and instantiate it inside the MLP block if this activation is selected, for example:
```
        project_in = nn.Sequential(
            nn.Linear(dim, inner_dim),
            nn.GELU()
        ) if not glu else GEGLU(dim, inner_dim)
```
from https://github.com/Stability-AI/stablediffusion/blob/8bde0cf64f3735bb33d93bdb8e28120be45c479b/ldm/modules/attention.py#L67 and https://github.com/huggingface/diffusers/blob/21bbc633c4d7b9bb7f74caf4b248c6a4079a85c6/src/diffusers/models/attention.py#L306 .
Maybe MONAI could use something similar.

**Comment by wyli** [comment]
thanks @Warvito, do you have time to submit a pull request for this?

**Comment by Shadow-Devil** [comment]
Hi, can I work on this issue if Warvito doesn't have time to implement this?

**Comment by Nic-Ma** [comment]
@Shadow-Devil Welcome your contribution!
