### ISSUE TITLE
Implement an Gaussian Merger

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5874]
One strategy to merge patches that we are already supporting in `SligingWindowInferer` is to use Gaussian weights to blend the patches together. To support this feature in the new design, a Gaussian Merger is required to be implemented.

Ref: https://github.com/Project-MONAI/MONAI/issues/5837

**Comment by drbeh** [comment]
@vikashg may I know what is the reason to close this issue?!

**Comment by vikashg** [comment]
@drbeh I think it was completed no as it was merged on Jun 22, 2023 ? If it is not we can reopen. We are trying to get a handle on all the open issues and see what are completed or inactive etc.

**Comment by vikashg** [comment]
ok my bad. Thanks for reopening.
