### ISSUE TITLE
replace assertion errors and improve error messages

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5898]
**Is your feature request related to a problem? Please describe.**
AssertionError such as this case:

https://github.com/Project-MONAI/MONAI/blob/86c7ecdc1225529a379e2cd58c23fe53aa79b0d0/monai/transforms/compose.py#L223-L224

could be improved to have a more specific type, and the error messages can be more specific about the variables:

```py
if len(weights) != len(self.transforms): 
    raise ValueError(
        f"transforms and weights should be same size, got {len(weights)} and {len(self.transforms)}."
    ) 
```

**Comment by ishandutta0098** [comment]
@wyli is this issue still open for more assertion error changes?

**Comment by KumoLiu** [comment]
Hi @ishandutta0098, yes. Welcome to contribute.
