### ISSUE TITLE
medical segmentation decathlon dataset as MONAI dataset

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#591]
**Is your feature request related to a problem? Please describe.**
this ticket looks for the integration of [the medical segmentation decathlon datasets](https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2)
following the pattern in [monai.applications.MedNISTDataset](https://github.com/Project-MONAI/MONAI/blob/master/monai/application/datasets.py#L22)

the data need to be hosted elsewhere to allow for simple/robust automatic downloading

(related to https://github.com/Project-MONAI/MONAI/issues/246)

**Comment by Nic-Ma** [comment]
Hi @pdogra89 , can we get some storage like Amazon S3?
Thanks.

**Comment by Nic-Ma** [comment]
Mark: move into V0.2 scope.
Thanks.

**Comment by Nic-Ma** [comment]
Requirements
$ pip install downloader
 
Python code
$ from google_drive_downloader import GoogleDriveDownloader as gdd
$ gdd.download_file_from_google_drive(file_id='1RzPB1_bqzQhlWvU-YGvZzhx2omcDh38C',dest_path='./hippo.tar', showsize=True)
