### ISSUE TITLE
LocalNet does not take depth as argument

### ISSUE THREAD

**Issue by ajoshiusc** [Project-MONAI/MONAI#5911]
**Describe the bug**
LocalNet does not take depth as argument. It infers it from max(extraction_levels).
So extracted ddf is from deepest layer and is low resolution. It is not from the output layer as expected, at depth 0.
The output image would be blocky since blocky ddf has been applied. 
In fact there is no way easy way to get high resolution ddf from the output layer that I know of.  Please correct me if I am wrong.
To fix this, depth argument should be exposed from the super class regunet.

**To Reproduce**
1. Run the 3d registration tutorial [lung registratiion](https://github.com/Project-MONAI/tutorials/blob/main/3d_registration/paired_lung_ct.ipynb)
2. Plot the ddf. Since this tutorial uses extraction_level=3, the ddf is blocky, with block size of 8. It is not smooth as expected.

**Expected behavior**
The ddf should be smooth without any blocky-ness.

**Comment by wyli** [comment]
Thanks for reporting, extraction level [3] is currently a workaround to be compatible with a previously trained model. The issue is tracked here https://github.com/Project-MONAI/tutorials/issues/1056 the value should be updated and the model retrained.

**Comment by fvlntn** [comment]
Actually, @ajoshiusc, the problem you are refering to isn't due to Depth. The problem is due to upsampling. By default, LocalNet uses NearestNeighbor but it should use Trilinear (as stated by LocalNet paper).

I reported the issue 2 months ago:
https://github.com/Project-MONAI/MONAI/issues/5782

Changing it to Trilinear solves the issue and makes the DDF smooth.

**Comment by ajoshiusc** [comment]
@fvlntn you could be right that trilinear is better than nearest-neighbor interpolation. However, I think ddf should be obtained from the last layer, not the deepest layer. I I am not sure if we can get high res ddf by upsampling it from the deepest layer, irrespective of interpolation method.

**Comment by fvlntn** [comment]
I'm using extract_levels=[0,1,2,3] and without Trilinear Upsampling, it gives blocky DDF of size 8. With Trilinear, it gives smooth DDF. 
But yeah I think 2^3=8 so it always gives blocky DDF if you extract from deeper level. Just wanted to let you know how I worked around it
