### ISSUE TITLE
TUM-CAMP-Networks-Contribution

### ISSUE THREAD

**Issue by vgonzalezd** [Project-MONAI/MONAI#5921]
**We would like to contribute with 3 refactored networks codes in MONAI**

DAF3D: 
Wang, Y., Dou, H., Hu, X., Zhu, L., Yang, X., Xu, M., ... & Ni, D. (2019). Deep attentive features for prostate segmentation in 3D transrectal ultrasound. IEEE transactions on medical imaging, 38(12), 2768-2778.
https://github.com/wulalago/DAF3D/blob/master/README.md 

QuickNAT: 
Roy, A. G., Conjeti, S., Navab, N., Wachinger, C., & Alzheimer's Disease Neuroimaging Initiative. (2019). QuickNAT: A fully convolutional network for quick and accurate segmentation of neuroanatomy. NeuroImage, 186, 713-727.
https://www.sciencedirect.com/science/article/abs/pii/S1053811918321232 

IFSSnet:
Al Chanti, D., Duque, V. G., Crouzier, M., Nordez, A., Lacourpaille, L., & Mateus, D. (2021). IFSS-Net: Interactive few-shot siamese network for faster muscle segmentation and propagation in volumetric ultrasound. IEEE transactions on medical imaging, 40(10), 2615-2628.
https://hal.science/hal-03197457/document

**Comment by wyli** [comment]
please let us know if you have any questions, the contributing guide has some info about creating pull requests in MONAI https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#preparing-pull-requests
