### ISSUE TITLE
Expand 3d classification example to multi-class

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#593]
Would it be possible to expand the 3d classification example from binary classification to a multi-class classification?

**Comment by Nic-Ma** [comment]
Hi @bartmch ,

Thanks for your interest here.
Actually, the 3D classification example is already treated as multi-class classification instead of binary classification(output channel = 1).
We set the model output tp `out_channels=2` and used `CrossEntropy` loss function:
https://github.com/Project-MONAI/MONAI/blob/master/examples/classification_3d/densenet_training_dict.py

Thanks.

**Comment by bartmch** [comment]
Ok, I understand that `model = monai.networks.nets.densenet.densenet121(spatial_dims=3, in_channels=1, out_channels=2,).to(device)` is actually a 3-class classifier instead of a binary (2-class) one.
But what kind of input does this model expects? Does it requires a one hot encoder like this? `labels = np.array([[1,0,0], [1,0,0], [0,1,0], [0,1,0], [0,0,1], [0,0,1], [1,0,0], [0,1,0], [0,0,1]], dtype=np.int64)` 
The one-hot encoder works when changing the CrossEntropyLoss loss_function from `loss = loss_function(outputs, labels)` to `loss = loss_function(outputs, torch.max(labels, 1)[1])` as the loss function only works with label values. But it errors on `compute_roc_auc` step.

> AssertionError: labels should have a channel with length equals to one.

**Comment by Nic-Ma** [comment]
Hi @bartmch ,

1. `model = monai.networks.nets.densenet.densenet121(spatial_dims=3, in_channels=1, out_channels=2,).to(device)` means the input image is 1 channel of [0, 1] values, output is **2 channels** of [0, 1] values(first channel is prediction for background, second channel is prediction for IXI). So it's 2 classes classification instead of 1 binary(1 class) classification.
2. As this is a multi-classes classification task instead of a multi-labels classification task, here the `label` data is **not in One-Hot** format and works with `CrossEntropyLoss`. If you want to train a multi-labels task, you need to use `BCELoss` instead.

Thanks.

**Comment by bartmch** [comment]
Hi @Nic-Ma,

1. Right, we're saying the same thing I just have my wording wrong. So for my four label classification problem (0, 1, 2, 3, 4) `model = monai.networks.nets.densenet.densenet121(spatial_dims=3, in_channels=1, out_channels=2,).to(device)` will stay the same. 2 channels where the 2d channel is the 5-classes prediction (mutually exclusive btw)
2. I'm a bit confused about the 2d point. If I understand you correctly this means that the class labels should be stored as `labels = np.array([0, 1, 2, 3, 4], dtype=np.int64)`.

**Comment by Nic-Ma** [comment]
Hi @bartmch ,

1. I don't understand your "the 2d channel is the 5-classes prediction".
If you have 5 classes(0, 1, 2, 3, 4), I think your `out_channels` should be 5. It's `channels` of the output data, not `dims`. 
2. If you are doing a multi-classes task, your label can be 1 channel data, for example: [3, 2, 0, 0, ... 4, 2, 1], `CrossEntropy` loss function expects it.

Thanks.

**Comment by bartmch** [comment]
Point 1&2, got it!
In the current tutorial setup, how can you get a performance metric for each class? E.g. "compute_roc_auc" only returns a single number.

Also, probably a multi-class-unrelated question, compute_roc_auc doesn't expect softmax.
`auc_metric = compute_roc_auc(y_pred, y, to_onehot_y=True, softmax=True)`
> TypeError: compute_roc_auc() got an unexpected keyword argument 'softmax'

**Comment by bartmch** [comment]
> Point 1&2, got it!
> In the current tutorial setup, how can you get a performance metric for each class? E.g. "compute_roc_auc" only returns a single number.
> 
> Also, probably a multi-class-unrelated question, compute_roc_auc doesn't expect softmax.
> `auc_metric = compute_roc_auc(y_pred, y, to_onehot_y=True, softmax=True)`
> 
> > TypeError: compute_roc_auc() got an unexpected keyword argument 'softmax'

the function compute_roc_auc needs to be changed in the tutorial from:
`auc_metric = compute_roc_auc(y_pred, y, to_onehot_y=True, softmax=True)`
to:
`auc_metric = compute_roc_auc(y_pred, y, to_onehot_y=True, add_softmax=True)`

**Comment by Nic-Ma** [comment]
Hi @bartmch ,

The tutorial uses the latest source code instead of MONAI v0.1, the API is:
https://github.com/Project-MONAI/MONAI/blob/master/monai/metrics/rocauc.py#L53

I think `softmax=True, average=None` is what you need.

Thanks.

**Comment by petteriTeikari** [comment]
If you have the time @Nic-Ma et al.

Maybe multiclass 3D segmentation example could be nice as well @Nic-Ma as I have label masks with 6 mutually exclusive classes (`[0,1,2,3,4,5]`  integer values in a `uint8` Nifti, `0` being the background) with the following relevant lines

```python
monai.networks.nets.UNet(dimensions=3, in_channels=1, *out_channels=num_of_classes*
self.loss_function = monai.losses.DiceLoss(to_onehot_y=True, softmax=True)
value = compute_meandice(y_pred=outputs, y=labels, include_background=True,
                                 to_onehot_y=True, mutually_exclusive=True)
```

with the meandice giving Dice scores above 1?

![image](https://user-images.githubusercontent.com/1060514/85757143-29abcb00-b707-11ea-9db3-df770362d6e9.png)

Losses seem be to be reasonable for this quick dummy test dataset, and properly then averaged over all classes? Is it correct just to divide the `mean_val_dice` with `num_of_classes`?

`mean_val_dice = torch.tensor(val_dice / num_items / num_of_classes)`

And that worked for one training run, but then I ran into `nan` mean dice values on next one while the `train_loss` and `val_loss` were going somewhere, but of course the model checkpoint saving depended on the mean dice value improvement

![image](https://user-images.githubusercontent.com/1060514/85757508-71caed80-b707-11ea-941a-7f827010e5f9.png)

**Comment by Nic-Ma** [comment]
Hi @petteriTeikari ,

I think this is another task, right? I saw it's segmentation instead of classification.
About the MeanDice question, you can refer to the spleen example:
https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb
```py
            metric_sum = 0.
            metric_count = 0
            for val_data in val_loader:
                val_inputs, val_labels = val_data['image'].to(device), val_data['label'].to(device)
                roi_size = (160, 160, 160)
                sw_batch_size = 4
                val_outputs = sliding_window_inference(val_inputs, roi_size, sw_batch_size, model)
                value = compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False,
                                         to_onehot_y=True, mutually_exclusive=True)
                metric_count += len(value)
                metric_sum += value.sum().item()
            metric = metric_sum / metric_count
            metric_values.append(metric)
```

Thanks.

**Comment by petteriTeikari** [comment]
Yes another task, sorry for continuing in the classification thread @Nic-Ma 

And I took the example from https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d_lightning.ipynb

And it looks the same 

```python
 images, labels, masks = batch['img'], batch['seg'], batch['mask'] # TODO! masks not used atm
        roi_size = self.val_ROI
        sw_batch_size = self.val_sw_size
        outputs = sliding_window_inference(images, roi_size, sw_batch_size, self.forward)
        loss = self.loss_function(outputs, labels)
        value = compute_meandice(y_pred=outputs, y=labels, include_background=True,
                                 to_onehot_y=self.one_hot, mutually_exclusive=True)
        tensorboard_logs = {'TRAIN/val_loss': loss}
        return {'val_loss': loss, 'val_dice': value, 'log': tensorboard_logs}
```

And it works for when I have just background + actual class so I was a bit confused why that now happened

**Comment by Nic-Ma** [comment]
I think you need to aggregate the results of `compute_meandice` to get the MeanDice, just like what I shared in previous comments.
Thanks.
