### ISSUE TITLE
feature request : please add cldice loss

### ISSUE THREAD

**Issue by dirtycomputer** [Project-MONAI/MONAI#5938]
**Is your feature request related to a problem? Please describe.**
[clDice - a Novel Topology-Preserving Loss Function for Tubular Structure Segmentation](https://openaccess.thecvf.com/content/CVPR2021/papers/Shit_clDice_-_A_Novel_Topology-Preserving_Loss_Function_for_Tubular_Structure_CVPR_2021_paper.pdf)
The abstract of this paper:⬇️
> Accurate segmentation of tubular, network-like structures, such as vessels, neurons, or roads, is relevant to many fields of research. For such structures, the topology is their most important characteristic; particularly preserving connectedness: in the case of vascular networks, missing a connected vessel entirely alters the blood-flow dynamics. We introduce a novel similarity measure termed centerlineDice (short clDice), which is calculated on the intersection of the segmentation masks and their (morphological) skeleta. We theoretically prove that clDice guarantees topology preservation up to homotopy equivalence for binary 2D and 3D segmentation. Extending this, we propose a computationally efficient, differentiable loss function (soft-clDice) for training arbitrary neural segmentation networks. We benchmark the soft-clDice loss on five public datasets, including vessels, roads and neurons (2D and 3D). Training on soft-clDice leads to segmentation with more accurate connectivity information, higher graph similarity, and better volumetric scores.

**Describe the solution you'd like**
[Official code repo](https://github.com/jocpae/clDice)
Please integrate the code in Monai project, that will help lots of researchers who working on vessels, neurons, tree or tabular structure. This official code repo has already implemented 2D and 3D version clDice loss, it will be easy to merge to current MONAI project. Thank you.

**Comment by yashika-git** [comment]
@wyli, can I work on implementing this?

**Comment by wyli** [comment]
sure, I'm assigning this to you, thanks!

**Comment by dirtycomputer** [comment]
Are there any positive outcomes now?

**Comment by dirtycomputer** [comment]
Any update?

**Comment by dirtycomputer** [comment]
@wyli

**Comment by wyli** [comment]
no visible progress at the moment, unassigning this ticket...

I saw a PR https://github.com/Project-MONAI/MONAI/pull/6632 by @zilima but was closed now (would you still be interested in contributing? @zilima)

**Comment by zilima** [comment]
Hi Wenqi, thanks for the email, I am working from a company repo, let me
double check with our team members and get back to you soon.




Zili Ma

Sr. Data Scientist

p: +1 (617) 818 0925

e: ***@***.***

RapidAI.com <https://rapidai.com/>

<https://www.linkedin.com/company/rapid-ai>  <https://twitter.com/rapidai>
<https://www.youtube.com/channel/UC4KBnsVQpEwGkZWZcZBEU1A?view_as=subscriber>

**Comment by jocpae** [comment]
Hi, first author of clDice here. Thank you for bringing clDice to Monai. We checked the implementation and it is correct. What are the steps to make it part of the main release?

**Comment by wyli** [comment]
thanks for confirming @jocpae, the module is available in monai 1.3.0 -- `pip install monai==1.3.0`.

**Comment by jocpae** [comment]
Great, thank you! I do not find it in the docs https://docs.monai.io/en/stable/losses.html yet. Should we prepare something?

**Comment by zma-rapidai** [comment]
Thanks for letting me know this great news.
Best,
Zili




Zili Ma

Sr. Data Scientist

p: +1 (617) 818 0925

e: ***@***.***

RapidAI.com <https://rapidai.com/>

<https://www.linkedin.com/company/rapid-ai>  <https://twitter.com/rapidai>
<https://www.youtube.com/channel/UC4KBnsVQpEwGkZWZcZBEU1A?view_as=subscriber>

**Comment by jocpae** [comment]
We would also like to add clDice as a metric to Monai we would do a PR soon?

**Comment by KumoLiu** [comment]
> We would also like to add clDice as a metric to Monai we would do a PR soon?

Hi @jocpae, we have a `LossMetric` which is a wrapper to make ``loss_fn`` available as a cumulative metric. Would that be helpful?
https://github.com/Project-MONAI/MONAI/blob/e801540166655fb602df8f749089db2a4cabc0de/monai/metrics/loss_metric.py#L26
