### ISSUE TITLE
New type hint in `Inferer` implies additional restriction

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5946]
The new type hint added to `Inferer` is not implying the same design as before and is implicitly adding additional restriction on `Inferer` base class which may not be desirable. It suggests that the output of the network and the output of `Inferer` call should have the same type, which might not expected as the `Inferer` should be allowed to produce results (via post-processing for instance) different than the network's output.
https://github.com/Project-MONAI/MONAI/blob/385ac0bb6612f88f92e0862a6aee033fb8df5de7/monai/inferers/inferer.py#L51

**Comment by drbeh** [comment]
@Shadow-Devil @wyli @Nic-Ma

**Comment by Shadow-Devil** [comment]
I am very sorry that my type annotations were not correct. I just looked through all currently implemended subclasses and found this relationship. To what should it be changed? Replace both `T`s with `Any`s?

**Comment by drbeh** [comment]
No problem, @Shadow-Devil! You are right that the current implementation of the concrete classes follow that pattern but I don't see the need to restrict it. Returning `Any` makes more sense to me.

@Nic-Ma on a side note, maybe we should revisit the `Inferer` call signature to include other inputs too. Currently, the input can only be torch Tensor while in the case of whole slide images, a string for filename or an image object might be preferable but not allowed here. What do you think?

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

I think we have the `*args: Any, **kwargs: Any` in the signature?

Thanks.

**Comment by wyli** [comment]
I'm fine with either `Any` or the current dev branch approach, just wanted to mention that when we use the inferer as an input parameter, the consistent `Callable[..., T] -> T` seems to be more robust if the user wants to tune the inference method 
https://github.com/Project-MONAI/MONAI/blob/385ac0bb6612f88f92e0862a6aee033fb8df5de7/monai/engines/trainer.py#L147

and in the case of postprocessing types that are different than the network definitions can also be achieved with a thin wrapper, for example https://github.com/Project-MONAI/MONAI/blob/fdd07f36ecb91cfcd491533f4792e1a67a9f89fc/monai/apps/detection/utils/predict_utils.py#L86-L88

**Comment by drbeh** [comment]
> 

Hi @Nic-Ma, you are right but I am referring to the `inputs` value here:
https://github.com/Project-MONAI/MONAI/blob/385ac0bb6612f88f92e0862a6aee033fb8df5de7/monai/inferers/inferer.py#L51
The inputs is not necessarily what we are feeding to the network, e.g., for WSI, the inputs can be `(filename, location)`, which is uses to extract a torch.Tensr and being fed to the network.

**Comment by drbeh** [comment]
I agree and as I said, it is fine with me to add a restriction to `Inferer` but we should be explicit about design changes and not *accidentally* change it to something that might be fine or not. The good practice is to consider any unintended design change as a bug and fix it by either reverting it or doing an explicit review.

If people agree with this design change, we can close this issue (agree: 👍 disagree: 👎).

OLD:
https://github.com/Project-MONAI/MONAI/blob/a77de4adff49037ffb24ea2cae217fac40302181/monai/inferers/inferer.py#L50

NEW:
https://github.com/Project-MONAI/MONAI/blob/385ac0bb6612f88f92e0862a6aee033fb8df5de7/monai/inferers/inferer.py#L51

@wyli @Nic-Ma @ericspod

**Comment by ericspod** [comment]
Sorry to draw this out but I've had a chance to look at it and I'd say `T` should be `Any` in the signature. I can see later inferrers being defined which use networks returning tuples of values and producing a result through sliding window that combines those so the result is a single tensor.

**Comment by Nic-Ma** [comment]
> > 
> 
> Hi @Nic-Ma, you are right but I am referring to the `inputs` value here:
> 
> https://github.com/Project-MONAI/MONAI/blob/385ac0bb6612f88f92e0862a6aee033fb8df5de7/monai/inferers/inferer.py#L51
> 
> 
> The inputs is not necessarily what we are feeding to the network, e.g., for WSI, the inputs can be `(filename, location)`, which is uses to extract a torch.Tensr and being fed to the network.

Hi @drbeh ,

Sorry for the late response, thanks for raising the discussion. I think maybe we can change the signature to allow `inputs: torch.Tensor | None`? Then for your case, you can define your subclass:
```py
def __call__(filename=XXX, location=YYY):
    super().__call__(inputs=None)
```
What do you think?

Thanks.
