### ISSUE TITLE
set mypy warn_unused_configs to False

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5954]
**Is your feature request related to a problem? Please describe.**

the unused `noqa` and `type: ignore` are currently detected and removed automatically, there's no need to block pull requests CI with

https://github.com/Project-MONAI/MONAI/blob/3a3f6c465199e510db14ea3cfe0c5a3c921da015/setup.cfg#L188-L189

this is a feature request to switch the checking off.

**Comment by Shadow-Devil** [comment]
I'm very sorry, this was my fault. I use this setting while adding the type annotations, but this shouldn't have been committed, I'll create a PR which reverts this.
