### ISSUE TITLE
Simple GAN Example

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#596]
**Is your feature request related to a problem? Please describe.**
Provide a basic GAN example with generator and discriminator networks to demonstrate MONAI usage.

**Describe the solution you'd like**
This will consist of a notebook tutorial and additional networks.

**Comment by gagandaroach** [comment]
I am working on adding a simple GAN example in #519

**Comment by Nic-Ma** [comment]
> I am working on adding a simple GAN example in #519

Hi @gagandaroach ,

This is another topic, Eric will add a simple GAN example here.
Your PR is much more complicated GAN and for the `research` folder. I think your target is to re-implement a cool research paper.
Similar to: https://github.com/Project-MONAI/MONAI/tree/master/research/coplenet-pneumonia-lesion-segmentation

Thanks.
