### ISSUE TITLE
`pip install monai` doesn't have `get_largest_connected_component_mask` included 

### ISSUE THREAD

**Issue by wuyuanhang94** [Project-MONAI/MONAI#598]
**Describe the bug**
both `pip install monai` and `pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
` doesn't have `get_largest_connected_component_mask` included, which causes the failure of jupyter notebook kernel

**To Reproduce**
Run commands: `jupyter notebook`

**Expected behavior**
```ImportError: cannot import name 'get_largest_connected_component_mask' from 'monai.transforms.utils' (/home/yiw/anaconda3/lib/python3.7/site-packages/monai/transforms/utils.py)```

**Environment (please complete the following information):**
 - OS: Ubuntu 14.04
 - Python version: Anaconda Python 3.7.6
 - MONAI version [e.g. git commit hash]: '0.1.0'
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: RTX 2080 Super

**Additional context**
I copied the lastest utils.py from master tot, and delete Optional, it stops throwning errors.

**Comment by wyli** [comment]
Hi @wuyuanhang94 I couldn't replicate this issue. could you follow [the installation steps from Q3](https://github.com/Project-MONAI/MONAI/wiki/Frequently-asked-questions-and-answers#q3-after-installing-monai-with-pip-why-does-importing-modules-give-an-error-no-module-named-) and report the version number?

**Comment by wuyuanhang94** [comment]
cool, thanks @wyli, issue solved
