### ISSUE TITLE
need commercial friendly pre-trained weights for pathology_tumor_detection bundle and example

### ISSUE THREAD

**Issue by daguangxu** [Project-MONAI/MONAI#5984]
**Is your feature request related to a problem? Please describe.**
 pathology_tumor_detection bundle uses imagenet pre-trained weights which is for non-commercial use

**Describe the solution you'd like**
Need commercial friendly pre-trained weights for pathology_tumor_detection bundle and example, similar to https://github.com/Project-MONAI/model-zoo/tree/dev/models/pathology_nuclei_segmentation_classification

**Comment by KumoLiu** [comment]
I think this one can already be closed by these two PR.
https://github.com/Project-MONAI/model-zoo/pull/357
https://github.com/Project-MONAI/tutorials/pull/1370
