### ISSUE TITLE
review and implement transform functionals in dev

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5991]
**Is your feature request related to a problem? Please describe.**
part of #4855 

this is to track the progress of implementing transform functionals from the prototype defined in #5860, for logically three parts
- [x] minor utility enhancements in
  - [x] monai.data.metatensor (https://github.com/Project-MONAI/MONAI/pull/6017)
  - [x] monai.transforms.lazy.utils (https://github.com/Project-MONAI/MONAI/pull/6017)
  - [x] monai.transforms.transform (https://github.com/Project-MONAI/MONAI/pull/6017)
- [x] crop and pad transforms with unit tests (monai.transforms.croppad)
  - [x] crop array/dict https://github.com/Project-MONAI/MONAI/pull/6068
  - [x] pad array/dict https://github.com/Project-MONAI/MONAI/pull/6031
  - [x] remaining transforms https://github.com/Project-MONAI/MONAI/pull/6083
- [x] spatial transforms with unit tests (monai.transforms.spatial)
  - [x] spatial_resample https://github.com/Project-MONAI/MONAI/pull/6060
  - [x] the other spatial transforms https://github.com/Project-MONAI/MONAI/pull/6080

monai.data.dataset, monai.transforms.compose changes require more discussions and are not within the scope of this feature request.
please feel free to raise issues, and split them into subtasks if needed cc @yiheng-wang-nv @KumoLiu @Nic-Ma

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , @KumoLiu ,
FYI: I think that the modifications of `minor utility enhancements` is not very complicate relatively, therefore I will start on this part first.

**Comment by yiheng-wang-nv** [comment]
Update: @KumoLiu already started working on crop transforms. I'm now starting on spatial transforms.
