### ISSUE TITLE
examples of multi-gpu sliding-window inference

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#603]
**Is your feature request related to a problem? Please describe.**
would be great to update one of the segmentation inference examples to show the multi-gpu utilities

**Additional context**
one of the sliding window example
https://github.com/Project-MONAI/MONAI/blob/master/examples/segmentation_3d/unet_evaluation_dict.py

**Comment by Nic-Ma** [comment]
Sounds good a suggestion, I will update that example to use our `get_devices_spec` utility API.
Thanks.
