### ISSUE TITLE
Working with multi image formats

### ISSUE THREAD

**Issue by nguyen14ck** [Project-MONAI/MONAI#604]
**Is your feature request related to a problem? Please describe.**
Besides file format nii.gz, it's better if supporting other biomedical image formats (mrc, dicom...)

**Describe the solution you'd like**
Besides package nibabel, images can (automatically) be read by package Simple ITK... or a custom function defined by user (custom dataset)

Thanks!

**Comment by Nic-Ma** [comment]
Hi @nguyen14ck ,

1. We are developing DICOM support: https://github.com/Project-MONAI/MONAI/pull/200.
2. It's a good idea to support `custom dataset`, you can inherit any of the existing `Dataset` and do the `data loading` logic in "__item__()", then execute other transforms except `LoadNifti`.

Thanks.

**Comment by nguyen14ck** [comment]
Thanks @Nic-Ma.
Could MONAI support mrc file as well? It's a popular format.

**Comment by Nic-Ma** [comment]
Hi @nguyen14ck ,

Thanks for your feedback, I recorded this request and raised to internal discussion.

Thanks.

**Comment by RespectKnowledge** [comment]
Hi,
It is great framework for researcher.
could you provide 3D segmentation demo other than Brain dataset?
Thanks in advance

**Comment by Nic-Ma** [comment]
Hi @RespectKnowledge ,

Thanks for your interest here, actually, you can find many examples or notebooks at:
https://github.com/Project-MONAI/MONAI/tree/master/examples
Including Spleen segmentation, Brain tumor segmentation or synthetic data segmentation, etc.

Thanks.

**Comment by wyli** [comment]
please see #856
