### ISSUE TITLE
Consider adding support for PyTorch on Apple M1/M2 MPS enabled devices

### ISSUE THREAD

**Issue by dazzag24** [Project-MONAI/MONAI#6043]
PyTorch now runs on Apple M1 MPS devices. This could open up access to MONAI to a wider range of users without the need for a dedicated GPU device.

However the current support for MPS is not 100% complete so this is very likely not feasible right now.

Others have already run into operations that are [not supported](https://github.com/pytorch/pytorch/issues/77818#issuecomment-1243806293) e.g Conv3D() and the PyTorch team have stated that they are planning on adding support.

See [this](https://github.com/pytorch/pytorch/issues/77764) which tracks adding support for the missing operations for the MPS backend.

**Comment by wyli** [comment]
looks like github ci runners don't currently support `setup-python` with these devices https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/
