### ISSUE TITLE
GridPatch transform support for max num_patches while filtering

### ISSUE THREAD

**Issue by kenza-bouzid** [Project-MONAI/MONAI#6049]
**Is your feature request related to a problem? Please describe.**

GridPatch is very useful to tile on the fly for a fixed number of patches. One usually uses an estimate of the average of number of tiles per slide. For slide with fewer tissue patches than the requested num_patches, we might end up  with some background tiles, which might be desirable in some cases to ensure an even number of tiles. For other cases, where we try to limit any background tiles, we would like to have a way of filtering out background tiles for a fixed number of patches (this might result in fewer tiles than the requested num_patches).

**Describe the solution you'd like**
In monai.tranforms.spatial.array.GridPatch, filtering is done as follow in lines 3279-3283
```        
#Filter patches
        if self.num_patches:
            patched_image, locations = self.filter_count(patched_image, locations)
        elif self.threshold:
            patched_image, locations = self.filter_threshold(patched_image, locations)
```
It would be great to add a flag for filtering background when num_patches > 0, maybe filter_bkgd_for_fixed_num_patches set to False by default

```      
#Filter patches
        if self.num_patches:
            patched_image, locations = self.filter_count(patched_image, locations)
        elif self.threshold or self.filter_bkgd_for_fixed_num_patches:
            assert self.threshold, "threshold must be set when filter_bkgd_for_fixed_num_patches is True"
            patched_image, locations = self.filter_threshold(patched_image, locations)
```

**Describe alternatives you've considered**
One alternative would be to change elif by if, but it might not be desirable for all use cases.

**Additional context**

**Comment by drbeh** [comment]
Hi @kenza-bouzid, 
Thank you very much for reporting this. you are right, it either gives specific number of patches or filter patches, and this is by design. I see your point about having max_num_patches while filtering the background. I will set it as a feature request and will evaluate it if we can prioritize its implementation. Will keep you posted.

**Comment by kenza-bouzid** [comment]
Actually if you only change the elif by an if, it should work! If the user doesn't want filtering then threshold shouldn't be set? Maybe precise this in the docs?

**Comment by drbeh** [comment]
@kenza-bouzid you are right but then it will be padded with zero tensors to have the same number of patches, which I don't think is desirable for use case. Right?

https://github.com/Project-MONAI/MONAI/blob/3eef61e82883e9bc6c08d26954fc86286df7d1b3/monai/transforms/spatial/array.py#L3241

**Comment by kenza-bouzid** [comment]
@drbeh good point, then maybe only pad `if self.num_patches and not self.threshold` ?

**Comment by drbeh** [comment]
Yes, it is done! Feel free to review it. Thanks
