### ISSUE TITLE
Random Patch Dataset

### ISSUE THREAD

**Issue by nguyen14ck** [Project-MONAI/MONAI#606]
**Is your feature request related to a problem? Please describe.**
Patch-based dataset: set random sampling mode, and set the number of patches from each image (volume) (will be extracted when iterating dataloader). 
Could we have this to train with large images and large datasets? Thank you.

**Comment by Nic-Ma** [comment]
Hi @nguyen14ck ,

Thanks for your suggestion.
We already have this feature enabled by transform: [RandCropByPosNegLabeld](https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/croppad/dictionary.py#L224).
About how to use this transform, you can refer to the example in: [Spleen 3D segmentation with MONAI](https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb).

Thanks.

**Comment by wyli** [comment]
> Hi @nguyen14ck ,
> 
> Thanks for your suggestion.
> We already have this feature enabled by transform: [RandCropByPosNegLabeld](https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/croppad/dictionary.py#L224).
> About how to use this transform, you can refer to the example in: [Spleen 3D segmentation with MONAI](https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb).
> 
> Thanks.

I don't think RandCropByPosNegLabeld matches the requirement. This feature request is about a randomised version of the grid dataset https://github.com/Project-MONAI/MONAI/blob/master/monai/data/grid_dataset.py

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, both `RandCropByPosNegLabeld` and `grid dataset` need a slight change to enable it.
I am working on an enhancement for `RandCropByPosNegLabeld` to support `pos_ratio=None`.
It will randomly select patches without pos/neg ratio, same as the Clara behavior.

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Yes, both `RandCropByPosNegLabeld` and `grid dataset` need a slight change to enable it.
> I am working on an enhancement for `RandCropByPosNegLabeld` to support `pos_ratio=None`.
> It will randomly select patches without pos/neg ratio, same as the Clara behavior.
> 
> Thanks.

Implementing this with a transform will shuffle the patches from different images sufficiently.
clara/tensorflow's dataset shuffle function has a buffer size parameter

**Comment by Nic-Ma** [comment]
Make sense.

**Comment by Nic-Ma** [comment]
Mark: the `RandSpatialCropSamples` transform had been merged.
Thanks.

**Comment by nguyen14ck** [comment]
Thank you, @Nic-Ma!

**Comment by nguyen14ck** [comment]
@Nic-Ma

"RandomSpatialCropSamplesd" returns a number of patches at the same time. This acts like a batch.
Let say the usual batch_size is 4 (or 8 or 16), while the number of samples can be larger (for example: 128). 
Then the actual_batch_size = batch_size * number_of_samples = 4*128 = 512 with spatial_size (96, 96, 96).
My GPU does not have enough memory to handle large "actual_batch_size" like that.

Currently, I work around by setting the number of samples = 1 (similar to using RandomSpatialCropd).
And I duplicate each file name the file list several times (= number of patch samples). That makes the data loader read the patches iteratively.

Could you consider a "Random version" of "Grid dataset", instead of transform like this? Thanks.

**Comment by Nic-Ma** [comment]
Hi @nguyen14ck ,

Yes, random version `GridDataset` is a cool idea, @wyli and I discussed it before, will try to implement later.
And to save memory for caching, maybe you can try our `PersistentDataset`: https://github.com/Project-MONAI/MONAI/blob/master/monai/data/dataset.py#L61.

Thanks.

**Comment by wyli** [comment]
fixed by #1087

**Comment by nguyen14ck** [comment]
Hi @Nic-Ma and @wyli,

Thanks for the implementation of patch dataset!

Could you consider modify/add an option to the function "sliding_window_inference" as well?
The current function **extracts-appends-stores all the patches first (in gpu?)**, then infers & combines. 
That can be fast & convenient, but it consumes too much memory. For an image 512*512*512, patch size 96*96*96, the GPU 16gb runs out of memory in several seconds. 

Could we just extract-infer patch by patch (this does not take running time longer too much), and then only append-store the inferred result to the output array? This is what TorchIO does and I work around like this.

Many thanks!
