### ISSUE TITLE
Pre-segment images using a mask

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#609]
Hi, is there a way to mask images given a mask by e.g. using a "monai.transforms" function? For example: Use a lung mask Nifti's for "pre-segmenting" Chest CT Nifti's before feeding it into the [classification example](https://github.com/Project-MONAI/MONAI/blob/master/examples/classification_3d/densenet_training_dict.py)

Thank you

**Comment by Nic-Ma** [comment]
Hi @bartmch ,

Thanks for your great suggestion!
Actually, this transform is already in our internal to-do list, I will submit an issue for it.

Thanks.

**Comment by wyli** [comment]
if you are looking for some quick prototype, This could be done by creating a simple `masked` function (the transforms are callables, can be complicated, but in this case it's quite simple)
```py
def masked(data_dict):
     data_dict["image"] = data_dict["image"] * data_dict["label"]
     return data_dict

```
use it in a composed:
```python

val_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    masked,
    ScaleIntensityRanged(keys=['image'], a_min=-57, a_max=164, b_min=0.0, b_max=1.0, clip=True),
    ToTensord(keys=['image', 'label'])
])
```
![Screenshot 2020-06-30 at 20 20 01](https://user-images.githubusercontent.com/831580/86167864-31a4aa00-bb0f-11ea-8978-3f41370a6348.png)

 if you comment out the `masked` in the transform chain, you get the original:
```py
val_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    #  masked,
    ScaleIntensityRanged(keys=['image'], a_min=-57, a_max=164, b_min=0.0, b_max=1.0, clip=True),
    ToTensord(keys=['image', 'label'])
])
```
![Screenshot 2020-06-30 at 20 20 11](https://user-images.githubusercontent.com/831580/86167936-4ed97880-bb0f-11ea-9955-1ed4a496aaa9.png)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I am making a PR to support `MaskIntensity` transform for this feature request.
So I will reopen for a while.
Thanks.
