### ISSUE TITLE
Logging doesn't work well in Monai version 1.0.0 or higher

### ISSUE THREAD

**Issue by bys9595** [Project-MONAI/MONAI#6115]
**Describe the bug**
From Monai version 1.0.0 or higher, I found that 'logging' is not works well as expected.

**To Reproduce**
Please run the code below in each version 1.0.0 and 0.9.0
_____________________________________________________________________________
import logging
import monai

logging.basicConfig(level=logging.INFO, handlers=[logging.FileHandler('log.txt'), logging.StreamHandler(os.sys.stdout)])
logger = logging.getLogger('main')
logging.info('Hello')
________________________________________________________________________

If you run the code above without importing monai package, it works well.
If you run the code above with importing monai 0.9.0, it works well.
However, if you import monai with a version greater than 1.0.0, no text is written to the log file.

**Environment**
python 3.8.15
torch 1.12.0+cu113
numpy 1.24.2
typing_extensions 4.5.0

**Comment by wyli** [comment]
thanks for reporting, I think that's been fixed on the latest dev branch. to verify it, please try the weekly preview builds or install from GitHub https://docs.monai.io/en/latest/installation.html#weekly-preview-release
