### ISSUE TITLE
A Dropout rate of 50% is systematically applied in the V-Net even when dropout_prob is set to 0

### ISSUE THREAD

**Issue by BLmbert** [Project-MONAI/MONAI#6116]
First of all thanks for this great repo ! 

I noticed that the segmentation performance of the V-Net was a step below other architectures (DynUNet, BasicUnetPlusPlus ...). By looking at the implementation, I noticed that a dropout rate of 50% is systematically applied (hard-coded) in the UpTransition layers of the V-Net, even the user sets ```dropout_prob```  to 0. 

In monai.networks.nets.vnet : 
`self.dropout = dropout_type(dropout_prob) if dropout_prob is not None else None` (l147)
-->  `self.dropout2 = dropout_type(0.5)` **(l148)**

**Expected behavior**
It is expected that dropout is set to 0 when ```dropout_prob``` is set to 0 in the VNet class.

[https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/vnet.py](url)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think the original author of VNet already left our team, could you please help confirm this question?

Thanks in advance.

**Comment by KumoLiu** [comment]
Hi @BLmbert, I just take a look at the original implementation. There are indeed two dropout rate in the net. The second dropout is hardcoded to 0.5 in the original implementation. Of course, we could also make the second dropout ratio more flexible as well. The `dropout_prob` the user set is used in [Line 155](https://github.com/Project-MONAI/MONAI/blob/b85e2c6751d525488dddc2e3b0b05576d81208be/monai/networks/nets/vnet.py#L155)
https://github.com/mattmacy/vnet.pytorch/blob/a00c8ea16bcaea2bddf73b2bf506796f70077687/vnet.py#L93-L94

Thanks!
cc @wyli @Nic-Ma
