### ISSUE TITLE
Install Monai with all dependencies on windows following the documentation

### ISSUE THREAD

**Issue by bpavie** [Project-MONAI/MONAI#6118]
**Describe the bug**
The installation of Monai with all dependecies does not work following the documentation
[https://docs.monai.io/en/stable/installation.html#from-github](https://docs.monai.io/en/stable/installation.html#from-github)

**To Reproduce**

```
git clone https://github.com/Project-MONAI/MONAI.git
cd MONAI/
pip install -e '.[all]'
```

Get the following error:
`ERROR: '.[all]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).`

**How it should be run on windows**
`pip install -e .[all]`

However, on windows 10, I still get an error:

```
from pydantic import BaseModel, ValidationError
      ModuleNotFoundError: No module named 'pydantic'
      [end of output]
```

**Comment by ytl0623** [comment]
Hi there, I got the same error when I use command: `pip install -e '.[all]'`.
But if I tried to use command `pip install -r requirements-dev.txt`, it looks worked!!!
And I found that there are three requirements file: requirements.txt requirements-dev.txt requirements-min.txt, maybe you can download all dependencies with those file.

**Comment by ytl0623** [comment]
For the second question,

`from pydantic import BaseModel, ValidationError
      ModuleNotFoundError: No module named 'pydantic'
      [end of output]`

After I use command `pip install pydantic`, and it works for me.

**Comment by ytl0623** [comment]
@wyli @bpavie 

Hi there, I found the way install MONAI with all dependencies on Windows.
The command should run `pip install -e ".[all]"` (double quotation marks), and it works for me.

So, maybe we can mark the differences between installation on linux and windows in  the documentation https://docs.monai.io/en/stable/installation.html#from-github.

And the second question, we can add package '**pydantic**' in [options.extras_require] section in the [setup.cfg](https://github.com/Project-MONAI/MONAI/blob/dev/setup.cfg#L48) file.

(Line 48)
[options.extras_require]
all =
    nibabel
    ninja
    ...
    **pydantic**

Hope the above method helps you!

**Comment by wyli** [comment]
thanks @ytl0623, for the ModuleNotFoundError, could you please share the full error log by any chance? the project's tests currently couldn't detect this error.

**Comment by ytl0623** [comment]
Hi, @wyli, the error log is like below when running command `pip install -e '.[all]'` on Windows system. 
```
ERROR: '.[all]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

And I found that the way install MONAI with all dependencies should run `pip install -e ".[all]"` (double quotation marks).
The reason why it works is that the Windows shell doesn't recognize single quotes to delimit a string at all, so on Windows you'll need to use double quotes.

Finally, maybe we can mark the differences between installation on Linux and Windows in the documentation https://docs.monai.io/en/stable/installation.html#from-github.

Thanks!
