### ISSUE TITLE
Inconsistent writing of Metadata. Loading +  Saving results in different metadata.

### ISSUE THREAD

**Issue by phcerdan** [Project-MONAI/MONAI#6136]
**Describe the bug**
Using SaveImage after LoadImage results in image saved with different metadata.

**To Reproduce**
```
    original2 = LoadImage(image_only=True)(original_file)
    SaveImage(output_dir=output_folder + "/monai_modified_meta",
              output_ext = ".nrrd",
              writer= "ITKWriter",
              resample=False,
              separate_folder= False,
              squeeze_end_dims = False,
              output_dtype=itk.SI)(original2)

```
Where `original_file` points to the attached image (a dcm 2D slice):
[CT.X.1.2.276.0.7230010.3.1.4.0.6.1667732449.1809819.zip](https://github.com/Project-MONAI/MONAI/files/10960531/CT.X.1.2.276.0.7230010.3.1.4.0.6.1667732449.1809819.zip) 

**Expected behavior**
The metadata should be the same of the original image after save.

**Screenshots**
The original dcm loaded in Slicer:
![image](https://user-images.githubusercontent.com/3021667/224795265-34b792ac-2a2a-4864-88d7-e4d2b5ab9e9c.png)

The result after loading + saving with the above code:
![image](https://user-images.githubusercontent.com/3021667/224795462-4441a4c1-9db4-4ad0-8b34-79adbac37a3c.png)

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```
```
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
```

**Additional context**
I have tested using `itk`:
```
original_itk = itk.imread(original_file)
itk.imwrite(original_itk, output_folder + "/monai_modified_meta/original_after_itk_save.nrrd")
```

and the metadata is conserved (afer opening it in Slicer).
There must be some internal Monai logic messing this up. 

The data is a bit odd, but correct, the spacing is negative. ITK corrects this at the moment of reading, flipping the sign in the direction matrix for those indices with negative spacing (and flipping the signs in spacing).

**Comment by wyli** [comment]
thanks for reporting, `original2 = LoadImage(image_only=True, affine_lps_to_ras=False)(original_file)` when loading with give the itk result. I think there's a bug for the default image writing, will look into it soon.

**Comment by phcerdan** [comment]
Thanks @wyli.
How can I provide that `afine_lps_to_ras = False` option to `SaveImage` instead of `LoadImage`?  I see the option is there for the `ITKWriter`, but `SaveImage` doesn't seem to accept it.

**Comment by wyli** [comment]
yes, I also tried that, currently the usage is
```py
save = SaveImage(
    output_dir=output_folder + "/monai_modified_meta",
    output_ext=".nrrd",
    writer="ITKWriter",
    resample=False,
    separate_folder=False,
    squeeze_end_dims=False,
    output_dtype=itk.SI,
)
save.set_options(init_kwargs={"affine_lps_to_ras": False})
save(original2)
```

but this logic doesn't look right at the moment...https://github.com/Project-MONAI/MONAI/blob/a8302eca3fc31554d4bd30fae84150766ce13472/monai/data/image_writer.py#L501-L502

**Comment by KumoLiu** [comment]
I find another bug when taking a look at this issue.
When using `PydicomReader` to read a dcm slice(2d), we didn't correctly record the spacing. Maybe using `(0028, 0030) Pixel Spacing` this tag can be safer.
https://github.com/Project-MONAI/MONAI/blob/678b5124a74f32859d692d142728ca1f7fa98a25/monai/data/image_reader.py#L687
