### ISSUE TITLE
Add percentile version of ScaleIntensityRange

### ISSUE THREAD

**Issue by abpwrs** [Project-MONAI/MONAI#614]
**Describe the solution you'd like**

A variant of `monai.transforms.ScaleIntensityRange` that has upper and lower intensity percentile parameters instead of `a_min` and `a_max`.      

So this transform would rescale each image differently depending on the intensity distribution of the `img` parameter instead of scaling all images the same, as `ScaleIntensityRange` does.

General idea:
```python
class ScaleIntensityRangePercentiles(Transform):
    def __init__(self, lower_percentile: float, upper_percentile: float, b_min: float, b_max: float, clip: bool = False) -> None:
        self.lower_percentile = lower_percentile
        self.upper_percentile = upper_percentile
        self.b_min = b_min
        self.b_max = b_max
        self.clip = clip

    def __call__(self, img):
        ### Calculate percentiles from img
        ### Rescale using percentiles
        ### Optional clipping
```
**Describe alternatives you've considered**
Modify the current `ScaleIntensityRange` transform to include a percentile option:         

`ScaleIntensityRange(a_min, a_max, b_min, b_max, clip=False, percentile=True)`         

Which would treat `a_min` and `a_max` as percentiles instead of intensity values.

**Comment by Nic-Ma** [comment]
Hi @abpwrs ,

Thanks for your feature request, it's truly another common intensity transform.
I will add this to our development plan.
Thanks.
