### ISSUE TITLE
PydicomReader (0028, 0030) Pixel Spacing

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6159]
When using `PydicomReader` to read a dcm slice(2d), we didn't correctly record the spacing. Maybe using `(0028, 0030) Pixel Spacing` this tag can be safer.
https://github.com/Project-MONAI/MONAI/blob/678b5124a74f32859d692d142728ca1f7fa98a25/monai/data/image_reader.py#L687

_Originally posted by @KumoLiu in https://github.com/Project-MONAI/MONAI/issues/6136#issuecomment-1472245743_

**Comment by wyli** [comment]
we can compute this from existing metadata, cf https://github.com/Project-MONAI/MONAI/issues/6136#issuecomment-1472348745, closing the ticket for now, feel free to reopen

**Comment by phcerdan** [comment]
Is this fixed? I am hitting exactly this with old Monai 1.1 using PydicomReader.
Are we reading affine directly instead of metadata.spacing? Thanks!

**Comment by wyli** [comment]
> Are we reading affine directly instead of metadata.spacing? 

yes, reading affine and you can access the spacing via `metatensor.pixdim`
