### ISSUE TITLE
Enable resuming training from the autorunner and manually

### ISSUE THREAD

**Issue by heyufan1995** [Project-MONAI/MONAI#6199]

**Comment by wyli** [comment]
- resuming training https://github.com/Project-MONAI/MONAI/commit/e4b313d59b2702cd2a441d7a557650ced78dc6c8
- optionally specify algorithms to use https://github.com/Project-MONAI/MONAI/commit/aef2ecccd4b4d0a663fb8a256ee36d8b00bdde10
