### ISSUE TITLE
documentation updates for 0.2.0

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#621]
**Describe the solution you'd like**
this ticket tracks the documentation updates for the 0.2.0 release (early July)
- [x] double check the examples and research code
- [x] update highlights (#536 #540)
- [x] update change log (may revisit #234)
- [x] revise the contributing guide to reflect the changes of local tests https://github.com/Project-MONAI/MONAI/pull/496 https://github.com/Project-MONAI/MONAI/pull/553
- [x] revise the contributing guide to reflect the changes of minimal CI tests https://github.com/Project-MONAI/MONAI/pull/595
~- [ ] update website and double-check all the URLs https://github.com/Project-MONAI/project-monai.github.io~ (will address this in the website source code repo)
- [x] #391 
- [x] change to use `pip install monai==0.2.0` for some examples/demos
- [x] group transforms into subsections in https://github.com/Project-MONAI/MONAI/blob/master/docs/source/transforms.rst

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your summary.
1. I can take "double check the examples", could you please help check the `research` folder?
2. For "change to use pip install monai==0.2.0 for some examples/demos", I think we only need to change the research folder and Colab examples, right?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Thanks for your summary.
> 
> 1. I can take "double check the examples", could you please help check the `research` folder?
> 2. For "change to use pip install monai==0.2.0 for some examples/demos", I think we only need to change the research folder and Colab examples, right?
> 
> Thanks.

sounds good, thanks! 

btw shall we divide the transforms https://github.com/Project-MONAI/MONAI/blob/master/docs/source/transforms.rst into the same categories as the code folder? https://github.com/Project-MONAI/MONAI/tree/master/monai/transforms (pad/crop, intensity, spatial, ...)

I'll let you know if I'm working on it, otherwise please do it if you have time

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I don't think we need to split transforms so far.
I think it's better to make it possible to switch versions(or branch) in UI.
For example, if users want to check the docs of MONAI v0.1, they can change the version to v0.1. Default version is the latest release(v0.2 branch). If they want to check the docs of latest code, they can change to the master branch.
Does it possible to do?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> I don't think we need to split transforms so far.
> I think it's better to make it possible to switch versions(or branch) in UI.
> For example, if users want to check the docs of MONAI v0.1, they can change the version to v0.1. Default version is the latest release(v0.2 branch). If they want to check the docs of latest code, they can change to the master branch.
> Does it possible to do?
> 
> Thanks.

yes there's an option on the website @IsaacYangSLA could you please enable the other versions of the doc based on existing tags?

I've been using the docs website for a while, I find it's particularly difficult to find the transform without a ctrl+f search. And when I can't remember the transform's class name, it is quite painful to go through the 50+ transforms...

**Comment by Nic-Ma** [comment]
Hi @wyli ，

I see your point, the reason I want to keep all transforms in 1 page is that: Most times you know part of the transform name and easy to search in 1 file. If split them into 6 categories, beginners can't figure out which category the transform belongs to.
That's same with PyTroch `torch.nn` page: https://pytorch.org/docs/stable/nn.html, it's a very long page and the exact code is in different folders: https://github.com/pytorch/pytorch/tree/master/torch/nn.

Thanks.

**Comment by wyli** [comment]
yes, I don't want to split them into different pages, but into different sections. so that we have an additional level of collapsible sidebar like pytorch's right sidebar:
![Screenshot 2020-06-29 at 07 30 37](https://user-images.githubusercontent.com/831580/85980534-8266b680-b9da-11ea-8434-7c4cdd57023f.png)

**Comment by Nic-Ma** [comment]
OK, that sounds good, please feel free to adjust that in your docs PR.
Thanks.

**Comment by wyli** [comment]
> OK, that sounds good, please feel free to adjust that in your docs PR.
> Thanks.

sure I'm working on this

**Comment by Nic-Ma** [comment]
Checked all the examples and notebooks and submitted PR https://github.com/Project-MONAI/MONAI/pull/687 to fix issues.
Thanks.

**Comment by Nic-Ma** [comment]
> > Hi @wyli ,
> > I don't think we need to split transforms so far.
> > I think it's better to make it possible to switch versions(or branch) in UI.
> > For example, if users want to check the docs of MONAI v0.1, they can change the version to v0.1. Default version is the latest release(v0.2 branch). If they want to check the docs of latest code, they can change to the master branch.
> > Does it possible to do?
> > Thanks.
> 
> yes there's an option on the website @IsaacYangSLA could you please enable the other versions of the doc based on existing tags?
> 
> I've been using the docs website for a while, I find it's particularly difficult to find the transform without a ctrl+f search. And when I can't remember the transform's class name, it is quite painful to go through the 50+ transforms...

Hi @IsaacYangSLA , could you please help take a look and help on this request? Please feel free to set up discussion if necessary.
Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

Could you please help provide your update here?
Really cool to see the versions now.
Thanks very much!

**Comment by IsaacYangSLA** [comment]
Hi @Nic-Ma and @wyli , I just updated the document hosting website.  Here are the current versions, 0.1.0, 0.2.0, stable and latest.  0.1.0 and 0.2.0 were generated from those two tags.  Stable is the latest release tag and identical to 0.2.0 for now.  Latest is always the head of master branch.
When a new tag is added to the repo, which follows the semantic version [PEP 440]( https://www.python.org/dev/peps/pep-0440/) and is not a pre-release tag, the stable version of the document will be updated.  So 0.2.1rc2 will not update stable while 0.2.1 will.

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

Thanks very much for your update! Really impressive update for our doc web pages.
