### ISSUE TITLE
optionally skip logging when rank >0

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6230]
**Is your feature request related to a problem? Please describe.**
it's useful to remove the logging handlers when rank > 0, example code:

```py
import logging
import torch.distributed as dist
from monai.apps.auto3dseg.auto_runner import logger


def mute_logger(_logger):
    if _logger.hasHandlers():
        for h in list(_logger.handlers):
            _logger.removeHandler(h)
    _logger.addHandler(logging.NullHandler())


logger.warning("logging start")  # example of logging (all ranks)
if dist.is_available() and dist.is_initialized() and dist.get_rank() > 0:
    mute_logger(logger)
logger.warning("logging end")  # example of logging (only rank 0)
```

would be great to make it a generic utility in monai:
- adds the capability of 'unmute'
- adds the support of modifying any monai logger -- `logging.getLogger("name")`
- when starting a logger, provides an option of rank0 only?

**Comment by mingxin-zheng** [comment]
Hi @wyli @myron @Nic-Ma , I was thinking of an implementation of this feature, and wondering if it would be good to use the filterer to meet the needs in the ticket

```
import logging
import torch
import torch.distributed as dist

class RankFilter(logging.Filter):
    def __init__(self, func=None):
        """default filter is to log only if rank == 0"""
        super().__init__()
        self.func = func if func else lambda rank: rank == 0
        if dist.is_available() and dist.is_initialized():
            self.rank = dist.get_rank()
        else:
            raise ValueError("torch.distributed is not available")

    def filter(self, record):
        if self.func(self.rank):
            return True
        else:
            return False

logger = logging.getLogger("auto3dseg")

if torch.cuda.device_count() > 1:
    dist.init_process_group(backend="nccl", init_method="env://")
    world_size = dist.get_world_size()
else:
    world_size = 1

rank_filter = RankFilter()
logger.addFilter(rank_filter)

logger.warning("warning")  # will only log when rank==0 with the default filter
```

If this looks good to you, I will move on and write a PR.

**Comment by wyli** [comment]
thank, that's better than the method of changing handlers.. please feel free to create a PR, we can discuss the details and merge.

**Comment by myron** [comment]
apologies for late comments, after merge or https://github.com/Project-MONAI/MONAI/pull/6243

but it seems we don't need this class RankFilter. All we need is to allow a user to enable or disable logging for a given process (in distributed).   I don't think the torch.distributed logic should be inside of our logger methods.
It's better for a user to manually check distributed, get rank, and then enable or disable logging manually.

After reading about python logging, it seems this functionality already exists , by doing either:
1) logger.propagate = False
https://docs.python.org/3/library/logging.html#logging.Logger

or 

2) logging.disable(level=...)
https://docs.python.org/3/library/logging.html#logging.disable
or

3) simple callable filter function (not class)
https://docs.python.org/3/library/logging.html#logging.Filter.filter
e.g. logger.addFilter(lambda x: False)

I think this is perfectly sufficient, and we don't need to maintain an extra class for RankFilter() .
@mingxin-zheng  @wyli  what do you think?

**Comment by mingxin-zheng** [comment]
Hi @myron , I did not fully get the points. Maybe a snippet of using one of the methods you mentioned can help me understand the use case better. What confuses me is that how the users are supposed to change the logging method outside of the train.py when they are using Auto3DSeg. Thanks!

**Comment by wyli** [comment]
@myron we also used it in the dictconfig based approach for setting up the logging https://gist.github.com/wyli/a63895305b86163cb1929bb687f7488b

**Comment by mingxin-zheng** [comment]
Thank you @myron for the details which helped me better understand the concerns. I agree with you on the usage and the flexibility.
