### ISSUE TITLE
INSTANCE_NVFUSER / InstanceNorm3dNVFuser GPU memory overhead 

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#6265]
When using norm "INSTANCE_NVFUSER" which uses InstanceNorm3dNVFuser,   in multi-gpu distributed training, the CUDA-0 device (only) gets ~2GB extra GPU memory allocations which are never released, which often leads to OOM crashes.

It seems the culprit is here

https://github.com/Project-MONAI/MONAI/blob/1b0808db48b2a3c0eb4287c6290bd754e70fb88b/monai/networks/layers/factories.py#L273-L279

with some dummy allocations.

a) first issue is they are all on CUDA:0 which will all go to first gpu in multi-gpu training
b) second this will be called many times potentially (all places where instancenorm is initialized in the network), and even though the dummy case looks small, It seems it allocates a lot of memory for some reason
c) GPU mem overhead persists (never released) for some reason, may be something specific for this norm function.

commenting these lines for "try/except" solved the issue

Can we just remove this try/except paragraph completely? thanks

@yiheng-wang-nv @Nic-Ma

**Comment by myron** [comment]
my PR to remove try/except https://github.com/Project-MONAI/MONAI/pull/6266

**Comment by wyli** [comment]
sure, the workaround was to fix this issue https://github.com/Project-MONAI/MONAI/issues/4235, I guess we still need it, let me add it to the tests. 

not sure if this skip is needed https://github.com/Project-MONAI/MONAI/commit/1cd0d7baedb460d8fd475d95cc802e2d3b140f7b#diff-8f2debbe9c6aa7e8c0b4f65cf36df76bcc5097ce006af6638ae37fb14950ec5e,  looks like it's been fixed https://github.com/NVIDIA/apex/issues/1562

**Comment by myron** [comment]
great, thanks!
