### ISSUE TITLE
Update pathology tools to handle deparate `WSIReader`

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#6276]
Since `monai.data.image_reader.WSIReader` is deparate, I think we should avoid calling it.
For example, class `LesionFROC` still uses it (see [here](https://github.com/Project-MONAI/MONAI/blob/05533abc2974631cf65d08d8719c09a27f16bed9/monai/apps/pathology/metrics/lesion_froc.py#L20)
BY the way, this class is also used in bundle:
https://github.com/Project-MONAI/model-zoo/blob/dev/models/pathology_tumor_detection/scripts/lesion_froc.py

In addition, there may have some typos in the deparate class, may need to double confirm related places. For example:
https://github.com/Project-MONAI/MONAI/blob/05533abc2974631cf65d08d8719c09a27f16bed9/monai/data/image_reader.py#L1241
The `msg_suffix` is wrong since we do not have `monai.wsi_reader.WSIReader`.

**Comment by yiheng-wang-nv** [comment]
Hi @drbeh , may need your help to address this ticket, thanks in advance!

**Comment by drbeh** [comment]
Hi @yiheng-wang-nv, that is addressed in #6262, so after the PR is merged, this issue should be resolved.
