### ISSUE TITLE
Ensure usage of anything deprecated since 0.8 is removed

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#6280]
There are several components that have been deprecated since v0.8 and many of them has been removed including all pathology related classes (addressed in PR #6262); however, there are still classes that have been used vastly throughout test cases, tutorials and bundles, so removing them requires some coordination with other monai repos and modifying the code that are utilizing them before removing them.

[UPDATE] The usage of below classes will be removed but they will be kept as a wrapper with an associated remove version of 1.3.

- [ ] AsChannelFirst and AsChannelFirstd
- [ ] AddChannel and AddChanneld
- [ ] SplitChannel and SplitChannels

**Comment by drbeh** [comment]
@wyli @Nic-Ma @ericspod 
Following our discussion at https://github.com/Project-MONAI/MONAI/pull/6262#issuecomment-1494530285, there are three popular classes that have been deprecated and removing them may cause trouble for the user (they have been vastly used across monai repos, e.g. bundle, tutorials, label, etc.). Wenqi proposed to create an alias to `AsChannelFirst` to `EnsureChannelFirst` instead of removing it. I think that is a good solution and we may want to do with the two other ones:

1. `AsChannelFirst` -> `EnsureChannelFirst`
2. `AddChannel` -> `EnsureChannelFirst(channel_dim="no_channel")`
3. `SplitChannel` -> `SplitDim(channel_dim = 0)`

What do you guys think?

**Comment by wyli** [comment]
cc @SachidanandAlle @holgerroth this might break some apps/demos

**Comment by drbeh** [comment]
@ericspod, I agree that we should clean up our bundles and tutorials to use the correct classes but what is the point of keeping deprecated notice if we don't want to remove them?
or do you suggest to remove them anyways?

**Comment by ericspod** [comment]
> @ericspod, I agree that we should clean up our bundles and tutorials to use the correct classes but what is the point of keeping deprecated notice if we don't want to remove them?
> or do you suggest to remove them anyways?

If their deprecation date hasn't been reached yet they should stay but additionally I think a lot of people are using these classes in production still. We were mentioning them at bootcamps recently as well so I think a bit more leeway is needed.

**Comment by codevisioner** [comment]
Using the numpy with version<2.0 worked for me.  (pip install numpy==1.24)
