### ISSUE TITLE
ClassesToIndicesd large RAM consumption

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#6285]
Currently ClassesToIndicesd can be used to pre-compute and cache the locations of all background/foreground classes. 
This significantly speedups the cropping transform RandCropByLabelClassesd, since the coordinates of class voxels do not need to be computed every time. 

Unfortunately for an average dataset it requires ~80gb of extra RAM, with an average cache (per image) is on the order of image size itself. (most of it due to background coordinates, or by some large segmentation classes). 

PR: https://github.com/Project-MONAI/MONAI/pull/6284

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/pull/6284
