### ISSUE TITLE
progress bar with tqdm

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#629]
**Is your feature request related to a problem? Please describe.**
instead of implementing the progress bar related functionality, [tqdm](https://github.com/tqdm/tqdm) looks like a good library to use directly. this ticket requests replacing the existing code to use tqdm implementations

**Comment by wyli** [comment]
this feature is postponed, please see https://github.com/Project-MONAI/MONAI/pull/633

**Comment by wyli** [comment]
shall we revisit this @Nic-Ma ? looks like python3.8 support is out. 
MONAI's current progress bar doesn't work well with google colab.

**Comment by Nic-Ma** [comment]
Sounds good, I will take a look at latest TQDM.
Thanks.
