### ISSUE TITLE
Make spatial transform inverse compatible for multiple passes

### ISSUE THREAD

**Issue by liamchalcroft** [Project-MONAI/MONAI#6314]
Using SpacingD as a pre-processing transform in a MONAILabel app, and the Deepedit click transforms often require multiple iterations. The default inverse transform runs into 2 errors when trying to inverse the SpacingD transform for the second time:

1. 'TypeError: Cannot interpret 'torch.float64' as a data type' from 'get_numpy_dtype_from_string' in 'monai/utils/type_conversion.py' . I am able to fix this locally by changing the function to remove any numpy/torch prefix: 'dtype=str(dtype).split('.')[-1]'
2. ' KeyError: 'src_affine' ' from 'monai/transforms/spatial/array.py", line 226, in inverse: kw_args["dst_affine"] = kw_args.pop("src_affine")' . I am able to fix this locally by adding this line before the inverse fn return: 'kw_args["src_affine"] = kw_args["dst_affine"]' in order to restore the src_affine.

**Comment by wyli** [comment]
thanks for reporting these, if you plan to contribute, 
for 1, please add tests to https://github.com/Project-MONAI/MONAI/blob/06defb7644585c462aba126325dd1fdda5d98db6/tests/test_get_equivalent_dtype.py#L45-L50

for 2, please change it to `kw_args["src_affine"] = kw_wargs.get("dst_affine")` to allow for empty `src_affine` before calling the inverse fn
