### ISSUE TITLE
Is predicted images of registration method have same affine matrices as the affine matrices of fixed images ?

### ISSUE THREAD

**Issue by JosianeUwineza** [Project-MONAI/MONAI#6328]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/6313

<div type='discussions-op-text'>

<sup>Originally posted by **JosianeUwineza** April  6, 2023</sup>
To get registration pair(moving and fixed) images and masks(.nii.gz). I took fixed images and masks rotate them by 10 degrees and perform registration using monai LocalNet model. With this data I found that the dice score reached 97%, but when use Monai SaveImage where resample is set to False, the predicted image is at the same position as moving image buy visualizing it .  when I checked affine of fixed image, moving image and predicted image I found that the moving and predicted image has same affine matrices. Is this mean that the monai LocalNet can't register images and mask which is slightly rotated? what I can do ?

Your helps will be much appreciated

Thanks</div>

**Comment by wyli** [comment]
thanks, let's continue the discussion in the original thread for the context... this is now yet a bug report or feature request, let me close this one for now.

**Comment by JosianeUwineza** [comment]
ok, no problem
