### ISSUE TITLE
Auto3DSeg ensemble needs to take images from different devices

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/MONAI#6361]
**Describe the bug**
Referece link:
https://github.com/Project-MONAI/research-contributions/pull/211?notification_referrer_id=NT_kwDOARtBabM1OTU2NDAwNjk5OjE4NTYzNDMz#issuecomment-1507906702

Different algorithms may return results on different devices (CPU or GPU) , e.g. if algo didn't have enough gpu memory it may do CPU based slidingwindow inference. So than when we do Ensembling, some internal function concatinate the predictions and it fails, since the predictions are on different devices.

**Comment by wyli** [comment]
Addressed by #6368
