### ISSUE TITLE
Enhance BundleWorkflow properties and the operations

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#6424]
**Is your feature request related to a problem? Please describe.**
During testing with our bundle tutorials, found some improvement areas for the new feature `BundleWorkflow`.
Will comment in this ticket and submit PR to fix then.

**Comment by KumoLiu** [comment]
May need `dataset_dir` and `datalist` in `InferProperties` since we need specify the data for inference.
https://github.com/Project-MONAI/model-zoo/blob/33eaff5e7135dfa20ad47f5559c4bfc8bcca74c1/models/spleen_ct_segmentation/configs/inference.json#L8-L9
https://github.com/Project-MONAI/tutorials/blob/c6b15b53b6d5345d87cd91c27efa046d8ab88b41/model_zoo/app_integrate_bundle/ensemble.py#L151

**Comment by KumoLiu** [comment]
May need `transforms` in `InferProperties` if we want to modify the post-transforms like something in this [tutorial](https://github.com/Project-MONAI/tutorials/blob/c6b15b53b6d5345d87cd91c27efa046d8ab88b41/model_zoo/app_integrate_bundle/ensemble.py#L128-L140) and don't want to re-initialize the transforms.

**Comment by Nic-Ma** [comment]
Thanks for the feedbakc.
I will prepare detailed document or notebook to describe different use cases for:
(1) Customized MONAI `BundleWorkflow` developer.
(2) MONAI `BundleWorkflow` user application.

Thanks.

**Comment by Nic-Ma** [comment]
I added `dataset_dir`, `dataset`, `dataset_data`, `handlers`(optional) to make the inference properties consistent with train properties, don't add others as train doesn't have them: https://github.com/Project-MONAI/MONAI/pull/6432.
And also added support to register app specific required properties.

@KumoLiu , for your postprocessing case, I think you can easily set that by nested Compose:
`workflow.postprocessing = Compose([workflow.postprocessing, ensemble_transform])`
What do you think?

Thanks.

**Comment by KumoLiu** [comment]
Hi @Nic-Ma, 
> workflow.postprocessing = Compose([workflow.postprocessing, ensemble_transform])

for the suggestion you said, I think it can't work when the postprocessing has the invert transform, since it will initialize the transforms twice which can't pass the id check.
Thanks!

**Comment by Nic-Ma** [comment]
Based on https://github.com/Project-MONAI/MONAI/pull/6432, I would suggest:
```py
# this application additionally requires a bundle workflow to provide the `dataloader` property
inference_workflow.add_property(name="dataloader", required=True)

EnsembleEvaluator(val_data_loader=inference_workflow.dataloader)
```

What do you think?

Thanks.
