### ISSUE TITLE
Auto augmentation methods 

### ISSUE THREAD

**Issue by hreso110100** [Project-MONAI/MONAI#6453]
**Is your feature request related to a problem? Please describe.**
I recently discoved auto augmentation methods for regular images in pytorch/torchvision docs (e.g. https://pytorch.org/vision/main/generated/torchvision.transforms.AutoAugment.html), but I found out that it is very hard to apply these methods in MONAI/medical domain due to implementation restrictions.

**Describe the solution you'd like**
Due to this problem I started to reimplement these methods to be compatible with MONAI ecosystem (recently I have finished TrivialAugment to be applicable for 3D medical images )

**Describe alternatives you've considered**
At first I tried to use original implementation but it is restricted to 2D images (sometimes even only to RGB images), which is obviously not desired.

**Additional context**
I would like to submit my reimplementation to MONAI, so others will be able to use it as well.

**Comment by wyli** [comment]
thank you, please feel free to create PRs (https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md), preferably implementing this using only pytorch and monai APIs would make it easy to maintain for the core dev team.

**Comment by hreso110100** [comment]
Thank you I will do my best.
