### ISSUE TITLE
`ConfigParser` doesn't need `deepcopy`

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#6463]
**Is your feature request related to a problem? Please describe.**
In the current implementation, `ConfigParser` executes `deepcopy` for every config item when recursively parse the whole config:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/config_parser.py#L379
But actually, all the parsing logic just read the config item content and generate a new config object:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/reference_resolver.py#L295
So I would suggest to remove this `deepcopy` logic, it can bring 3 benefits:
1. If use python object in the config dict, `deepcopy` it may cause `Invertd` failure due to mismatch object ID.
2. If the config structure contains very big python object (like CacheDataset), it will increase memory usage, especially considering it's a recursive operation.
3. Some python objects may not support pickle operation and deepcopy will fail.

**Comment by Nic-Ma** [comment]
CC @KumoLiu @yiheng-wang-nv

**Comment by yiheng-wang-nv** [comment]
Update: I modified the link @Nic-Ma posted within the ticket and fixed the link with a commit before related changes. It is helpful for further check.
