### ISSUE TITLE
Can't save label and pred label correctly.

### ISSUE THREAD

**Issue by dirtycomputer** [Project-MONAI/MONAI#6465]
**Describe the bug**
Can't save label and pred label correctly.
It looks like some problem with Oriented.

**Expected behavior**
<img width="391" alt="IMG_7499" src="https://user-images.githubusercontent.com/48406770/236284859-84ae91c8-47fa-44dd-a78f-f4185391870e.PNG">

Two coronary part should be like⬆️ 
But what I got like this⬇️ （red is predict label, green is ground truth)
It seems like not oriented, and two part are mirrored independently.
I don't known why.
![IMG_7498](https://user-images.githubusercontent.com/48406770/236284878-2896424f-a6a5-440f-ab55-06c6534765a3.jpg)

**Screenshots**
Code:
<img width="709" alt="截屏2023-05-05 01 33 08" src="https://user-images.githubusercontent.com/48406770/236284260-8e5b6e35-3c55-4504-905f-1ecd24b33749.png">
<img width="665" alt="截屏2023-05-05 01 33 22" src="https://user-images.githubusercontent.com/48406770/236284271-ea692415-e309-40f3-bfc9-4ecfb90cc358.png">
<img width="616" alt="截屏2023-05-05 01 33 47" src="https://user-images.githubusercontent.com/48406770/236284273-2ae6a285-8559-4558-a2a4-2bcaa8381f0e.png">
<img width="837" alt="截屏2023-05-05 01 33 56" src="https://user-images.githubusercontent.com/48406770/236284279-aa2586c4-8ed5-403e-a15a-0ed6ec56a8ab.png">

**Comment by dirtycomputer** [comment]
solution： LoadImaged(keys=["image"],image_only=False, meta_keys="image_meta_dict"),
It wasted me one whole night....

**Comment by WeijieChen2017** [comment]
Solved my problem! Thank you!
