### ISSUE TITLE
Enhance `monai.bundle.verify_net_in_out` to enable multiple input in forward

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#6486]
Currently, the function only supports to input a tensor into the network:
https://github.com/Project-MONAI/MONAI/blob/5fae0c1c7525bebee1e43a625c7777f594cc97a4/monai/bundle/scripts.py#L936

However, to make it more generic, we should support kwargs for networks that have multiple input args, for example:

https://github.com/Project-MONAI/GenerativeModels/blob/fd04ec6f98a1aec7b6886dff1cfb4d0fa72fe4fe/generative/networks/nets/diffusion_model_unet.py#L1848

This ticket is also related to:
https://github.com/Project-MONAI/model-zoo/pull/390

**Comment by yiheng-wang-nv** [comment]
cc @Nic-Ma @Can-Zhao

**Comment by Nic-Ma** [comment]
Thanks for raising the reqeust, please submit a PR for it.
