### ISSUE TITLE
Imports are not added to ConfigParser.globals unless explicitly parsed.

### ISSUE THREAD

**Issue by RETIREglitch** [Project-MONAI/MONAI#6495]
**Describe the bug**
When making use of config files the following behavior is present:
Any statement containing $import will import the module automatically, even if not explicitly parsed. However, they are not added to ConfigParser.globals

When explicitly parsing an import statement for **any** module, all other imports in the config file are also added to ConfigParser.globals.

**To Reproduce**
You can run the following script to reproduce the behaviour.
```
from monai.bundle import ConfigParser
config_file = {
    "import": [ 
        "$import datetime as dt"
    ],
    "explicit_import": [
        "$import glob"
    ],
    "print_datetime": "$print(dt.datetime.now())"
}

# get the config_file ready to be parsed
parser = ConfigParser(config=config_file)
for k,v in parser.globals.items():
    print(f"{k}: \t{v}")

parser.get_parsed_content("print_datetime") # this expression runs, even though datetime isn't in globals

parser.get_parsed_content("explicit_import") # this adds both glob and datetime to globals, despite only glob being in the explicit_import
print("\nExplicitly imported glob")
for k,v in parser.globals.items():
    print(f"{k}: \t{v}")
```

output:

```
monai: 	
torch: 	
np: 	
numpy: 	
2023-05-09 11:04:24.047853

Explicitly imported glob
monai: 	
torch: 	
np: 	
numpy: 	
dt: => not explicitly imported.
glob: 
```	

**Expected behavior**
All imports are added to globals by default, or only the explicitly parsed imports are added to globals.

**Environment:**
 - Ubuntu
 - Python 3.9.2
 - MONAI 1.1.0 release
 - CUDA Version: 12.0, cudnn: 8500
 - Tesla M60

**Comment by Nic-Ma** [comment]
Hi @RETIREglitch ,

I think that's expected behavior? @wyli .
You can set the globals when parsing: https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/config_parser.py#L81

Thanks.

**Comment by wyli** [comment]
currently `parser = ConfigParser(config=config_file)` won't trigger any import statements, but get_parsed_content will trigger all the imports. does this cause any practical issues?

**Comment by RETIREglitch** [comment]
Ah, so it is get_parsed_content in general that adds all the imports. I was checking if it was possible to check for unused variables/imports in my project. Otherwise this implementation is probably fine.

**Comment by wyli** [comment]
thanks, closing this for now...
