### ISSUE TITLE
Bug for changing `channel_dim` in Whole slide image reader

### ISSUE THREAD

**Issue by Dylan-H-Wang** [Project-MONAI/MONAI#6511]
I tried to change the default value for `channel_dim` in `CuCIMWSIReader` and found that the outputs were not correct. Therefore, I checked the source code and identified the buggy part:
https://github.com/Project-MONAI/MONAI/blob/e5cf74aac60cb3512d92f9abb3dd48b5ed36e8d0/monai/data/wsi_reader.py#L821-L827
Suppose I set `channel_dim=-1`, and then `patch = patch[:3] ` is not modifying the channel part at all, instead, it changes the image dimension!

Same problem for `TiffFileWSIReader`:
https://github.com/Project-MONAI/MONAI/blob/e5cf74aac60cb3512d92f9abb3dd48b5ed36e8d0/monai/data/wsi_reader.py#L1179-L1186

**Comment by KumoLiu** [comment]
Hi @Dylan-H-Wang, it seems the channel dim changes in L818. Could you please give me a small piece of code that can reproduce the bug, then I could take a look at it?
https://github.com/Project-MONAI/MONAI/blob/e5cf74aac60cb3512d92f9abb3dd48b5ed36e8d0/monai/data/wsi_reader.py#L817-L818
Thanks!

**Comment by Dylan-H-Wang** [comment]
> Hi @Dylan-H-Wang, it seems the channel dim changes in L818. Could you please give me a small piece of code that can reproduce the bug, so then I could take a look at it?
> 
> https://github.com/Project-MONAI/MONAI/blob/e5cf74aac60cb3512d92f9abb3dd48b5ed36e8d0/monai/data/wsi_reader.py#L817-L818
> 
> Thanks!

Yes, that is what causes this bug. Since the `channel_dim` is moved to desired position `self.channel_dim`, this line
https://github.com/Project-MONAI/MONAI/blob/e5cf74aac60cb3512d92f9abb3dd48b5ed36e8d0/monai/data/wsi_reader.py#L1186
should also based on the `self.channel_dim` instead of assuming its default value at `self.channel_dim=0`

Here is the code to reproduce the bug
```python
from monai.data import CuCIMWSIReader, TiffFileWSIReader

img_path = "./data/CAMELYON16/images/normal_150.tif"

reader = CuCIMWSIReader(channel_dim=0)
slide = reader.read(img_path)
slide_data= reader.get_data(slide, level=0)[0]
print(slide_data.shape) # (3, 60928, 65536)
      
reader = CuCIMWSIReader(channel_dim=-1)
slide = reader.read(img_path)
slide_data= reader.get_data(slide, level=0)[0]
print(slide_data.shape) # 3, 65536, 3)

reader = TiffFileWSIReader(channel_dim=-1)
slide = reader.read(img_path)
slide_data= reader.get_data(slide, level=0)[0]
print(slide_data.shape) # (3, 65426, 3)
```

**Comment by KumoLiu** [comment]
Thanks, now I can reproduce it, I will create a PR to fix it.

**Comment by KumoLiu** [comment]
Hi @Dylan-H-Wang, I just create a [PR](https://github.com/Project-MONAI/MONAI/pull/6514) to fix it. It would be great if you could test it on your side to see if it works.
Thanks!

**Comment by Dylan-H-Wang** [comment]
> Hi @Dylan-H-Wang, I just create a [PR](https://github.com/Project-MONAI/MONAI/pull/6514) to fix it. It would be great if you could test it on your side to see if it works.
> Thanks!

Seems perfect on my side. Thank you for the helps!
