### ISSUE TITLE
Spatial Gradient

### ISSUE THREAD

**Issue by fvlntn** [Project-MONAI/MONAI#6541]
Hello,

I used Bending Energy Loss from your code and it was really strange:

![image](https://github.com/Project-MONAI/MONAI/assets/23518242/7edad255-2e5f-4bab-9739-b482af03a38f)

Code is using spatial_gradient like:
dx[i] = (x[i+1] - x[i-1]) / 2.

Loss is regularizing DDFs based on even/odd voxels. 
By using spatial_gradient as dx[i] = (x[i+1] - x[i]), it solves the smoothness issue.

![image](https://github.com/Project-MONAI/MONAI/assets/23518242/a63b9ad1-95e9-4e35-9d3b-eb6660896b28)

Thanks

**Comment by wyli** [comment]
thanks for reporting, I think dx[i] = (x[i+1] - x[i]) will cause a 0.5 shift in the results...
maybe you can consider the method proposed here https://github.com/Project-MONAI/MONAI/issues/5939

**Comment by vikashg** [comment]
closing as alternative suggested
