### ISSUE TITLE
Add highlight description for lazy-resampling

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#6580]
**Is your feature request related to a problem? Please describe.**
As we are close to the release of MONAI 1.2, would be nice to include the description for lazy-resampling in highlights.

**Comment by atbenmurray** [comment]
> Hi @atbenmurray ,
> 
> Once #6571 merged, could you please help provide this part?
> 
> Thanks in advance.

No problem. Where does it go?

**Comment by Nic-Ma** [comment]
Hi @atbenmurray ,

Thanks, please add it to this page: https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/whatsnew_1_2.md.

**Comment by Nic-Ma** [comment]
Hi @atbenmurray ,

This is urgent for the MONAI 1.2 release today or tomorrow, could you please help add the description?

Thanks in advance.

**Comment by atbenmurray** [comment]
I will. I've been in the middle of a house move that nearly went badly wrong. I'll sit down in an hour to write it

**Comment by atbenmurray** [comment]
@Nic-Ma Please see #6590
