### ISSUE TITLE
Documentation improvements for Randomizable

### ISSUE THREAD

**Issue by YuanTingHsieh** [Project-MONAI/MONAI#659]
In here: https://docs.monai.io/en/latest/transforms.html#randomizable

From the text description.
I think it is not clear that this self.R is a class variable instead of an instance variable.
And it is also not clear that self.R is of type np.random.RandomState

**Comment by Nic-Ma** [comment]
Hi @YuanTingHsieh ,

Thanks for your bug report, I submitted PR https://github.com/Project-MONAI/MONAI/pull/660 to update it and added example.
