### ISSUE TITLE
Compute Pseudo dice API

### ISSUE THREAD

**Issue by LReion** [Project-MONAI/MONAI#6599]
When I trained with nnunet, the evaluation metric was Pseudo Dice, but I couldn't find the calculation Pseudo Dice in the metrics of MONAI, I hope to add it, thank you.

**Comment by hyacinth97223** [comment]
I am very interested in this issue and currently have the following two ideas to complete this issue.
1.Import third party to finish
2. I implemented a program related to Pseudo dice
Hope the above method can help you, thanks.
