### ISSUE TITLE
Filter only ".dcm" files when reading DICOM series

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#6627]
**Is your feature request related to a problem? Please describe.**
When I try to load a DICOM folder, the loading will fail if there is some irrelevant file in the folder (or I have to set `force=True`). E.g., when I load the DICOM series from the [LIDC-IDRI](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=1966254) database, there's a `.xml` annotation file in the folder, the loader will try to load it as well and cause failure.

**Describe the solution you'd like**
Change this line 
https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/data/image_reader.py#L469
to something like
```python
series_slcs = Path(name).glob("*.dcm")
```
I'm not sure if there are other suffixes to be considered.

**Comment by mingxin-zheng** [comment]
Hi @function2-llx , thanks for the suggestion, but I have seen some scanners exporting DICOM without the ".dcm" suffix, e.g. "IM_0001" on some ultrasound systems.

**Comment by function2-llx** [comment]
@mingxin-zheng Yes, maybe we can let the user decide whether to filter and what suffix to filter.

**Comment by mingxin-zheng** [comment]
I tagged this as a feature request and see if this is a generalized usage. Besides using the suffix to filter files, there are also many other possible name filters users want to customize. I am not sure whether a filter on suffix or something more general is needed.

For now, as I see the `read` method take list of files, you may try to glob the `.dcm` files as a list and pass it to the reader in your script.

https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/data/image_reader.py#L441

If we go for a filter later, maybe we can allow a regex pattern here for file inclusion/exclusion in the pydicom reader.

https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/data/image_reader.py#L470

**Comment by function2-llx** [comment]
Thanks, I feel like using a regex pattern is a good idea. 

On the other hand, reading a list of files may not work as expected because they will be stacked along the channel dimension (even permutation after that is not feasible since the affine check will fail).

https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/data/image_reader.py#L443-L444
