### ISSUE TITLE
Wrong spacing checking logic in DICOM series combination

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#6630]
**Describe the bug**

I found some issues in the following code snip:

https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/data/image_reader.py#L510-L521

1. In line 520, spacing should be got from `slices[idx]` instead of `first_slice`; there's the same issue in line 521;
2. the default value in line 514 is `[1.0, 1.0, 1.0]`, which is a `list` instance, while the default value in line 520 is `(1.0, 1.0, 1.0)`, which is a `tuple` instance, and `(1.0, 1.0, 1.0) == [1.0, 1.0, 1.0]` will result in `False`.

**Comment by wyli** [comment]
thanks for reporting, would you like to submit a PR to fix it? I think the relevant elementwise checks could be done with allclose https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/transforms/utils_pytorch_numpy_unification.py#L58
