### ISSUE TITLE
DeepSupervisionLoss is not documented 

### ISSUE THREAD

**Issue by HussainAlasmawi** [Project-MONAI/MONAI#6682]
The DeepSupervisionLoss (https://github.com/Project-MONAI/MONAI/blob/dev/monai/losses/ds_loss.py) is not documented.

**Comment by wyli** [comment]
thanks for reporting, would you like to create a PR to fix it?

**Comment by HussainAlasmawi** [comment]
Yes, can you please explain to me how to do it?

**Comment by wyli** [comment]
sure, please add the class names to https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/losses.rst?plain=1, similar to this pull request https://github.com/Project-MONAI/MONAI/pull/6671.

this doc provides details about how to create a pull request for this project https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md  let us know if you have any specific questions.
