### ISSUE TITLE
Add scripts directory to Python search directories automatically and avoid using PYTHONPATH

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6722]

**Comment by KumoLiu** [comment]
I think we have already added the scripts directory automatically in the bundle, not sure what this means here.
https://github.com/Project-MONAI/model-zoo/blob/e6ecc282d5490f1b66ccd16948b94cd5590152e4/models/pathology_nuclei_classification/configs/evaluate.json#L69
