### ISSUE TITLE
UNet Training Error: Size of Tensors Mismatched

### ISSUE THREAD

**Issue by jillianlee** [Project-MONAI/MONAI#678]
I'm currently experiencing mismatch between my input tensors while trying to train UNet with BraTS2018 data.

I'm working off of the spleen example, which has been very helpful, but I've been unable to complete training. I've referred to issues #418 and #323, but am still stuck.

My code is as follows:

**Data set and Transforms**

```
text_t1 = open(r'C:\Users\jilli\Documents\MF-MRI\BraTS 2018 Training Data\Training\filename_t1.txt', 'r') 
train_images = text_t1.read().split('\n')

text_segs = open(r'C:\Users\jilli\Documents\MF-MRI\BraTS 2018 Training Data\Training\filename_seg.txt', 'r') 
train_labels = text_segs.read().split('\n')

data_dicts = [{'image': image_name, 'label': label_name}
              for image_name, label_name in zip(train_images, train_labels)]
train_files, val_files = data_dicts[:-9], data_dicts[-9:]

train_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    ScaleIntensityRanged(keys=['label'], a_min=0, a_max=4, b_min=0.0, b_max=1.0, clip=True),
    #CropForegroundd(keys=['image', 'label'], source_key='image'),
    ToTensord(keys=['image', 'label'])
])
val_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    ScaleIntensityRanged(keys=['label'], a_min=0, a_max=4, b_min=0.0, b_max=1.0, clip=True),
    #CropForegroundd(keys=['image', 'label'], source_key='image'),
    ToTensord(keys=['image', 'label'])
])
```
**Cache Dataset**

```
train_ds = monai.data.CacheDataset(
    data=train_files, transform=train_transforms, cache_rate=1.0, num_workers=0
)
# train_ds = monai.data.Dataset(data=train_files, transform=train_transforms)

# use batch_size=2 to load images and use RandCropByPosNegLabeld
# to generate 2 x 4 images for network training
train_loader = monai.data.DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=0, multiprocessing_context = None)

val_ds = monai.data.CacheDataset(
    data=val_files, transform=val_transforms, cache_rate=1.0, num_workers=0
)
# val_ds = monai.data.Dataset(data=val_files, transform=val_transforms)
val_loader = monai.data.DataLoader(val_ds, batch_size=1, num_workers=0, multiprocessing_context = None)
```

**Training**
```
device = torch.device('cpu')
model = monai.networks.nets.UNet(dimensions=3, in_channels=1, out_channels=2, channels=(16, 32, 64, 128, 256),
                                 strides=(2, 2, 2, 2), num_res_units=2, norm=Norm.BATCH).to(device)
loss_function = monai.losses.DiceLoss(to_onehot_y=True, softmax=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4)

val_interval = 2
best_metric = -1
best_metric_epoch = -1
epoch_loss_values = list()
metric_values = list()
for epoch in range(600):
    print('-' * 10)
    print('Epoch {}/{}'.format(epoch + 1, 600))
    model.train()
    epoch_loss = 0
    step = 0
    for batch_data in train_loader:
        step += 1
        inputs, labels = batch_data['image'].to(device), batch_data['label'].to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = loss_function(outputs, labels)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        print('{}/{}, train_loss: {:.4f}'.format(step, len(train_ds) // train_loader.batch_size, loss.item()))
    epoch_loss /= step
    epoch_loss_values.append(epoch_loss)
    print('epoch {} average loss: {:.4f}'.format(epoch + 1, epoch_loss))

    if (epoch + 1) % val_interval == 0:
        model.eval()
        with torch.no_grad():
            metric_sum = 0.
            metric_count = 0
            for val_data in val_loader:
                val_inputs, val_labels = val_data['image'].to(device), val_data['label'].to(device)
                roi_size = (160, 160, 160)
                sw_batch_size = 4
                val_outputs = sliding_window_inference(val_inputs, roi_size, sw_batch_size, model)
                value = compute_meandice(y_pred=val_outputs, y=val_labels, include_background=False,
                                         to_onehot_y=True, mutually_exclusive=True)
                metric_count += len(value)
                metric_sum += value.sum().item()
            metric = metric_sum / metric_count
            metric_values.append(metric)
            if metric > best_metric:
                best_metric = metric
                best_metric_epoch = epoch + 1
                torch.save(model.state_dict(), 'best_metric_model.pth')
                print('saved new best metric model')
            print('current epoch {} current mean dice: {:.4f} best mean dice: {:.4f} at epoch {}'.format(
                epoch + 1, metric, best_metric, best_metric_epoch))
```

I get the following error:
```Traceback (most recent call last):
  File "<ipython-input-20-6831040c0cf9>", line 41, in <module>
    outputs = model(inputs)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\AppData\Roaming\Python\Python37\site-packages\monai\networks\nets\unet.py", line 128, in forward
    x = self.model(x)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\AppData\Roaming\Python\Python37\site-packages\monai\networks\layers\simplelayers.py", line 33, in forward
    return torch.cat([x, self.submodule(x)], self.cat_dim)

RuntimeError: Sizes of tensors must match except in dimension 1. Got 39 and 40 in dimension 4
```

Please note image.shape = label.shape = 160, 160, 78

My current set up is on Windows 10
MONAI version: 0.2.0rc1+19.ge8c26a2
Python version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Numpy version: 1.19.0
Pytorch version: 1.5.0

Any help would be greatly appreciated! Thanks so much.

**Comment by Nic-Ma** [comment]
Hi @jillianlee ,

Thanks for your interest here!
I checked the Brats 2018 dataset and found the root cause of your problem is that:
Every item in the Brats 2018 dataset contains 4 images and 1 label, so `LoadNiftd` returns data with shape [H, W, D, 4].
It's different from the Spleen dataset, which doesn't have channel dim.
So you should use `AsChannelFirstd` transform instead of `AddChanneld` transform.

BTW, in order to complete your practice with Brats 2018 dataset, you also need to adjust below items:
1. UNet input channel should be 4.
2. `ScaleIntensityRanged` transform is used to scale image intensity, I don't understand why you used it to adjust labels.
Maybe it's unnecessary in Brats segmentation task.

I am considering to develop a tutorial for **multi-labels** 3D segmentation task based on Brats 2018 dataset soon.

Thanks.

**Comment by jillianlee** [comment]
Hi Nic, thanks for getting back to me so quickly!

For my problem, I was looking to use only a single-channel input. I had made a separate folder containing only the T1 images and labels from the BraTS data set. For the input, I had provided a complete list of the T1 filenames inside that folder, so I expected that the `LoadNiftid` would only read in that 1 single channel input.

I did try your suggested changes to see if somehow the reader was obtaining the other channels, but I got another error:

```
Traceback (most recent call last):

  File "<ipython-input-23-6dca7b902f2f>", line 1, in <module>
    runfile('C:/Users/jilli/Documents/Python Scripts/monai test 2.py', wdir='C:/Users/jilli/Documents/Python Scripts')
  File "C:\Users\jilli\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/jilli/Documents/Python Scripts/monai test 2.py", line 116, in <module>
    outputs = model(inputs)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\AppData\Roaming\Python\Python37\site-packages\monai\networks\nets\unet.py", line 128, in forward
    x = self.model(x)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\AppData\Roaming\Python\Python37\site-packages\monai\networks\blocks\convolutions.py", line 144, in forward
    res = self.residual(x)  # create the additive residual from x
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 481, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: Expected 5-dimensional input for 5-dimensional weight [16, 4, 3, 3, 3], but got 4-dimensional input of size [2, 155, 160, 160] instead
```

Also - I had used `ScaleIntensityRanged` to adjust the labels because the BraTS labels are multi-class, so there are intensities from 0-4, but I wanted to do a binary segmentation problem, so I rescaled. Should I be using another method for this goal?
I did try getting rid of this rescale command as well but I got the same error as I had originally posted about.

Thanks!

**Comment by Nic-Ma** [comment]
Hi @jillianlee ,

1. OK, if you changed to only use 1 channel data, your previous `AddChanneld` logic is correct. The error was caused by different image sizes. You need to add a `Resized` transform to align all images in a batch.
2. I think `rescale` is not a good idea for labels because it will interpolate values. You can define your own transform to do your specific conversion.

Thanks.

**Comment by jillianlee** [comment]
Hi @Nic-Ma 

Ah I see! That makes sense. Sorry for all the questions, I'm now having difficulty with `Resized`. I've tried figuring out whats wrong by referring to other issues that have used this command but I still can't figure it out.

The new transforms list is as follows:
```
train_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    Resized(keys=['image', 'label'], spatial_size = (150, 150, 68), mode =('bilinear', 'nearest')),
    ToTensord(keys=['image', 'label'])
])
val_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    Resized(keys=['image', 'label'], spatial_size = (150, 150, 68), mode =('bilinear', 'nearest')),
    ToTensord(keys=['image', 'label'])
])
```
and it gives me the following error

```
  File "C:\Users\jilli\AppData\Roaming\Python\Python37\site-packages\monai\transforms\spatial\array.py", line 315, in __call__
    input=torch.as_tensor(img[None], dtype=torch.float),
ValueError: applying transform <monai.transforms.compose.Compose object at 0x0000024B030B3A88>.
```

You are definitely correct though, when I tried adding CropForegroundd, I got another error that indicated the images were of different sized.

I'm not quite sure why `Resized` specifically is giving me an error, I installed the latest Monai via Git. I've tried different settings and sizes with `Resized` but I still get the same error. Please let me know if you have any more advice.

Thanks so much for your help and patience!

**Comment by Nic-Ma** [comment]
Hi @jillianlee ,

1. I think maybe you encountered a known issue of PyTorch: https://github.com/pytorch/pytorch/issues/33812.
Could you please help update your MONAI source code to the latest of master branch and try again?
2. In order to debug transforms, you can try to insert [DataStatsd](https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/utility/dictionary.py#L260) transform into your transform chain.

Thanks.

**Comment by jillianlee** [comment]
Hi @Nic-Ma 

Thanks again for your continued help.

So I've updated both Pytorch and MONAI: 
```
MONAI version: 0.2.0rc3+18.gd5e56ab
Python version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Numpy version: 1.18.5
Pytorch version: 1.5.0
```
and I've added `DataStatsd`. I am a bit more confused now however, as this is showing that all the images and labels are the same shape (`Shape: (1, 160, 160, 78)`).

1. If I have    
```
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    DataStatsd(keys = ['image', 'label']),
    ToTensord(keys=['image', 'label']) ])
```
The error is: `RuntimeError: Sizes of tensors must match except in dimension 1. Got 39 and 40 in dimension 4`

2. If I add `Resized` and set the shape to 160, 160, 78, I get a series of 3 handling errors:
```
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
...
ValueError: applying transform <monai.transforms.spatial.dictionary.Resized object at 0x000001479B33F648>.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
...
ValueError: applying transform <monai.transforms.compose.Compose object at 0x000001479D057888>.
```
3. If I implement the CropForeground transform like in the spleen example, I get the following: 
`RuntimeError: stack expects each tensor to be equal size, but got [1, 93, 112, 72] at entry 0 and [1, 90, 108, 68] at entry 1`


I'm very confused about what's going on here since it seems the sizing of the inputs is fine? The negative strides error is mentioned in some Pytorch forums, but I'm not sure how to fix it via the MONAI system.

Best,
Jillian

**Comment by Nic-Ma** [comment]
Hi @jillianlee ,

1. I think your "negative strides" issue is something related to contiguous data in Numpy, I submitted a PR https://github.com/Project-MONAI/MONAI/pull/691 to convert the data type before transforms.
Could you please help download my PR and help verify locally again? Hope it can fix your issue.
2. `CropForegroundd` will only keep the valid area and change the data shape, so you need to call it before `Resized`.

Thanks.

**Comment by jillianlee** [comment]
Hi @Nic-Ma 

So I have downloaded MONAI version: 0.2.0rc3+18.gd5e56ab, and am still getting the same error when trying to use `Resized`.

Here is the full error traceback:
```
Traceback (most recent call last):

  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 276, in apply_transform
    return transform(data)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\spatial\dictionary.py", line 297, in __call__
    d[key] = self.resizer(d[key], mode=self.mode[idx], align_corners=self.align_corners[idx])
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\spatial\array.py", line 332, in __call__
    input=torch.as_tensor(img, dtype=torch.float).unsqueeze(0),

ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 276, in apply_transform
    return transform(data)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\compose.py", line 229, in __call__
    input_ = apply_transform(_transform, input_)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 278, in apply_transform
    raise type(e)(f"applying transform {transform}.").with_traceback(e.__traceback__)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 276, in apply_transform
    return transform(data)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\spatial\dictionary.py", line 297, in __call__
    d[key] = self.resizer(d[key], mode=self.mode[idx], align_corners=self.align_corners[idx])

  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\spatial\array.py", line 332, in __call__
    input=torch.as_tensor(img, dtype=torch.float).unsqueeze(0),
ValueError: applying transform <monai.transforms.spatial.dictionary.Resized object at 0x000001A66A085988>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-4-6dca7b902f2f>", line 1, in <module>
    runfile('C:/Users/jilli/Documents/Python Scripts/monai test 2.py', wdir='C:/Users/jilli/Documents/Python Scripts')
  File "C:\Users\jilli\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/jilli/Documents/Python Scripts/monai test 2.py", line 66, in <module>
    check_data = monai.utils.misc.first(check_loader)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\utils\misc.py", line 41, in first
    for i in iterable:
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jilli\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\data\dataset.py", line 56, in __getitem__
    data = apply_transform(self.transform, data)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 278, in apply_transform
    raise type(e)(f"applying transform {transform}.").with_traceback(e.__traceback__)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 276, in apply_transform
    return transform(data)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\compose.py", line 229, in __call__
    input_ = apply_transform(_transform, input_)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 278, in apply_transform
    raise type(e)(f"applying transform {transform}.").with_traceback(e.__traceback__)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\utils.py", line 276, in apply_transform
    return transform(data)
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\spatial\dictionary.py", line 297, in __call__
    d[key] = self.resizer(d[key], mode=self.mode[idx], align_corners=self.align_corners[idx])
  File "C:\Users\jilli\Anaconda3\lib\site-packages\monai\transforms\spatial\array.py", line 332, in __call__
    input=torch.as_tensor(img, dtype=torch.float).unsqueeze(0),
ValueError: applying transform <monai.transforms.compose.Compose object at 0x000001A66A0728C8>.
```

I'm also still a bit confused as to why this transform is actually needed? The original motivation was that the data set was not consistent in size, but I found with DataStatsd that all the images actually are consistent in size, yet I still get the mismatch error without applying the resize transform.

Sorry for all the confusion. Thanks so much,

Jillian

**Comment by Nic-Ma** [comment]
1. I think maybe you didn't download the code of my PR, did you use the below command?
`git clone https://github.com/Nic-Ma/MONAI.git --branch 678-fix-astesnor-issue`
And set PYTHONPATH to this folder?
2. Could you please help print the size of all the images in a batch? To see whether they are consistent in size.

Thanks.

**Comment by jillianlee** [comment]
Ah you're right, I did not set the PYTHONPATH correctly. This did fix the error with the `Resized` so I merged the changes
 with my MONAI module! Thanks so much, but the original size mismatch error at the model input is back again, even with the `Resized` transform:
`RuntimeError: Sizes of tensors must match except in dimension 1. Got 39 and 40 in dimension 4`

The `DataStatsd` debugger is showing all the files are the same size, and I've attached a screenshot showing some of the debugger output.

![Screenshot (85)](https://user-images.githubusercontent.com/56376166/86448292-8e0cf280-bce4-11ea-8854-d6471fe4c665.png)

**Comment by wyli** [comment]
thanks for the detailed feedback and discussions @jillianlee @Nic-Ma, now it's a UNet usage issue, the size of the UNet input should be divisible by 4 in this configuration. making the last spatial dim size 76 or 80 will resolve this issue. There are a few possible ways to achieve this in MONAI (padding, cropping, resizing, random affine transform...)  cc @ericspod

**Comment by jillianlee** [comment]
Hi @wyli 

So I tried using `Resized` and set spatial_size to 160, 160, 72 and I get a very similar error to before:
`RuntimeError: Sizes of tensors must match except in dimension 1. Got 9 and 10 in dimension 2` 

This error also occurs if I set the size to a cube of dimensions 72, 72, 72

If I use SpatialPadd instead to resize to 168, 168, 80, I again get a similar error:
`RuntimeError: Sizes of tensors must match except in dimension 1. Got 21 and 22 in dimension 2`

I have found other people report very similar errors, especially when dealing with UNets. They too fix it with a resize, but I'm not sure whats going wrong here as it appears from the Check Transforms portion of the code that the size adjustments I'm doing are applying correctly:
`image shape: torch.Size([160, 160, 72]), label shape: torch.Size([160, 160, 72])`

**Comment by wyli** [comment]
Sorry I was not verifying it properly. The size should be divisible by 16, so `160,160,80` would work.
If you want to use image size `160,160,72` or `168,168,80`, then change the network to have `channels=(16, 32, 64, 128), strids=(2, 2, 2)` from `channels=(16, 32, 64, 128, 256), strides=(2, 2, 2, 2)`

**Comment by jillianlee** [comment]
This worked! Thank you. I did also have to change the output_channel to 1 which I believe makes snse. The image input is a single channeled image and the label is a multi-class single channeled label, so a single output channel with a loss function with to_onehot_y = True should correctly run training right?

Thanks again, both of you! I greatly appreciate all your help.

**Comment by wyli** [comment]
sure thanks for your detailed follow-up @jillianlee, it's helpful for the project as well.

I can't remember exactly how the original labels are organised, but you may want to use sigmoid=True instead of softmax=True, if the labels are not mutually exclusive.

**Comment by Marfi92** [comment]
I start working on 3D unet for segmentation. I am using spleen_segmentation_3d_(1).ipynb script. I can run the code for your data. I got an error when I run it on my own dataset. 
The size and dimensions of images are the same (512 512 x) and format nii.gz. the voxel spacing and origin and orientations of my data are different with yours. 
voxel spacing: 1 1 1 
origin and orientation 0 0 0
while for your data it is
voxel .799 .799 5 
origin 406.2 406.2 0
Would you please help me?
I got this error:
"RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/transform.py", line 102, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/transform.py", line 66, in _apply_transform
    return transform(parameters)
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/croppad/dictionary.py", line 861, in __call__
    self.randomize(label, fg_indices, bg_indices, image)
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/croppad/dictionary.py", line 852, in randomize
    self.cropper.randomize(label=label, fg_indices=fg_indices, bg_indices=bg_indices, image=image)
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/croppad/array.py", line 1068, in randomize
    self.allow_smaller,
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/utils.py", line 520, in generate_pos_neg_label_crop_centers
    centers.append(correct_crop_centers(center, spatial_size, label_spatial_shape, allow_smaller))
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/utils.py", line 447, in correct_crop_centers
    raise ValueError("The size of the proposed random crop ROI is larger than the image size.")
ValueError: The size of the proposed random crop ROI is larger than the image size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/monai/data/dataset.py", line 104, in __getitem__
    return self._transform(index)
  File "/usr/local/lib/python3.7/dist-packages/monai/data/dataset.py", line 877, in _transform
    data = apply_transform(_transform, data)
  File "/usr/local/lib/python3.7/dist-packages/monai/transforms/transform.py", line 129, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.RandCropByPosNegLabeld object at 0x7f1b6d225c90>"

**Comment by Marfi92** [comment]
Hi Liu,
It works well. Thanks for the adorable project.
Have a nice day.

**Comment by Marfi92** [comment]
Hi YunLiu,
When I extended my dataset with different dimensions in third dimension (527 527 70) (527 527 60) (527 527 80) with spacingd(.....(1,1,1)) I received image and labels with different dimension
Image shape (528, 528 , 65) and Label shape (340,340,129)
Would you please help me to handle this issue?
Thanks again for your help and time.

With this transformation
train_transforms = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        ScaleIntensityRanged(
            keys=["image"], a_min=-57, a_max=164,
            b_min=0.0, b_max=1.0, clip=True,
        ),
        CropForegroundd(keys=["image", "label"], source_key="image"),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        Spacingd(keys=["image", "label"], pixdim=(
            1, 1, 1), mode=("bilinear", "nearest")),

        # user can also add other random transforms
        # RandAffined(
        #     keys=['image', 'label'],
        #     mode=('bilinear', 'nearest'),
        #     prob=1.0, spatial_size=(96, 96, 96),
        #     rotate_range=(0, 0, np.pi/15),
        #     scale_range=(0.1, 0.1, 0.1)),
    ]
)
val_transforms = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        ScaleIntensityRanged(
            keys=["image"], a_min=-57, a_max=164,
            b_min=0.0, b_max=1.0, clip=True,
        ),
        CropForegroundd(keys=["image", "label"], source_key="image"),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        Spacingd(keys=["image", "label"], pixdim=(
            1, 1, 1), mode=("bilinear", "nearest")),
    ]
)

**Comment by Marfi92** [comment]
Hi 
I solved problem and the size of labels and images are similar after transformation. I have a problem in training step. 
epoch 1/2
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-49-efab8ac501d1>](https://localhost:8080/#) in <module>
     21         )
     22         optimizer.zero_grad()
---> 23         outputs = model(inputs)
     24         loss = loss_function(outputs, labels)
     25         loss.backward()

15 frames
[/usr/local/lib/python3.7/dist-packages/torch/_tensor.py](https://localhost:8080/#) in __torch_function__(cls, func, types, args, kwargs)
   1119 
   1120         with _C.DisableTorchFunction():
-> 1121             ret = func(*args, **kwargs)
   1122             if func in get_default_nowrap_functions():
   1123                 return ret

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 7 but got size 8 for tensor number 1 in the list.


Would you please help me to solve it?
voxel spacing in images are 1 1 1 and in labels are 0.6 0.6 2 for some case 0.6 0.6 1.5.

**Comment by KumoLiu** [comment]
Hi @Marfi92, you need to ensure the shape of the label and image is the same, maybe use `ResizeWithPadOrCrop`. Thanks!

**Comment by KumoLiu** [comment]
> train_transforms

Hi @Marfi92, I'm not sure, it's up to the shape you input to the network. Just added it to your `train_transforms` and `val_transforms`, thanks!

**Comment by Marfi92** [comment]
Thanks for your help. It works.
