### ISSUE TITLE
Spacing transform does not update `pixdim`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#6832]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/6831

<div type='discussions-op-text'>

<sup>Originally posted by **agaldran** August  7, 2023</sup>
Hello,

Sorry about the naive question, I am trying to wrap my head around transforms and meta_dicts. Right now I have the following operations:
```
import monai.transforms as t

data_dict = {'image': 'data/ct/images/.whatever.nii.gz'}
loader = t.LoadImaged(keys=('image'), image_only=False)
loaded_data_dict = loader(data_dict)
print(loaded_data_dict['image'].shape, loaded_data_dict['image_meta_dict']['pixdim'][1:4])
```
which returns a shape and voxel sizes of `[281, 313, 182]` and `(0.50,0.50,0.75)` respectively. Now, if I run:
```
spacing = t.Spacingd(keys=['image'], pixdim=(0.50, 0.50, 1.5), mode=('bilinear')) 
spaced_data_dict = spacing(loaded_data_dict)
print(spaced_data_dict['image'].shape, spaced_data_dict['image_meta_dict']['pixdim'][1:4])
```
I am expecting to see approx half the voxels in the Z direction, as the original spacing was 0.75 and I am asking for twice that spacing. For the other directions, nothing should be changed^* . This is what I get:
```
[281, 313, 92], (0.50,0.50,0.75)
```
So, although the number of voxels are as expected, the spacing remains the same. I cannot find any other key in the meta data dictionary that tells me what is the *current* spacing for this volume. Am I doing something wrong here?
</div>

**Comment by wyli** [comment]
yes, the image's original `'pixdim'` is not modified, the current pixdim is a property: `spaced_data_dict["image"].pixdim`

**Comment by KumoLiu** [comment]
> yes, the image's original `'pixdim'` is not modified, the current pixdim is a property: `spaced_data_dict["image"].pixdim`

Does it mean we don't need to modify it or we may enhance it in the future?

**Comment by wyli** [comment]
We don't have a good reason to modify it at the moment, a single source of truth for the original and current pixdim seems to be consistent and easy to maintain..
