### ISSUE TITLE
`lazy` argument has no effect in `Compose.__call__`

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#6841]
According to the code, only `self.lazy` is used:
https://github.com/Project-MONAI/MONAI/blob/8e99af5f96df0746d6cbcaed88feaea0e51abd56/monai/transforms/compose.py#L321-L335

There's the same issue in `OneOf`. I'm not sure if this is intended. Also, the typing of `lazy` strangely has `str`.

https://github.com/Project-MONAI/MONAI/blob/8e99af5f96df0746d6cbcaed88feaea0e51abd56/monai/transforms/compose.py#L450-L473

**Comment by wyli** [comment]
thanks, these look like bugs, I'm labelling this contribution wanted.
