### ISSUE TITLE
SurfaceDiceMetric expose use_subvoxels as a parameter

### ISSUE THREAD

**Issue by matt3o** [Project-MONAI/MONAI#6866]
**Is your feature request related to a problem? Please describe.**
I wanted to try out the `SurfaceDiceMetric` in the Deepmind implementation way. However the class itself does not expose the `use_subvoxels` as a parameter. After quickly checking I am not sure how to set the kwargs where `use_subvoxels` is drawn from.
If there is an easy way to access that, it would be fine for me. Otherwise I'd open a PR to add `use_subvoxels` as a flag instead.
Thanks a lot for the good work!

**Comment by matt3o** [comment]
@wyli Ah yep but that won't work with Ignite, right? I tried it the way below which obviously doesn't work, but I don't know how else to pass use_subvoxels into the metric..

```python
    surface_dice_metric = SurfaceDiceMetric(
        include_background=include_background, 
        class_thresholds=(2,2), 
        reduction="mean", 
        get_not_nans=False,
        #, use_subvoxels=True
    )   
    surface_dice_metric_ignite = IgniteMetric(
        metric_fn=surface_dice_metric,
        output_transform=from_engine(["pred", "label"]),
        save_details=False,
    )   
```

**Comment by wyli** [comment]
>  but that won't work with Ignite, right? 

that's true, it seems the main limitation is from this line which is hard-coded to take two inputs:
https://github.com/Project-MONAI/MONAI/blob/024767239c306d49c4f30b63a20c3ee82cd83536/monai/handlers/ignite_metric.py#L112

**Comment by matt3o** [comment]
Would it be okay to open a PR for setting `use_subvoxels` in `SurfaceDiceMetric.__init__()`?
Won't be much work and enables the code to work with Ignite as well.

**Comment by wyli** [comment]
> Would it be okay to open a PR for setting `use_subvoxels` in `SurfaceDiceMetric.__init__()`? Won't be much work and enables the code to work with Ignite as well.

sure, thanks @matt3o ! assigning this to you...
