### ISSUE TITLE
Enhance `_get_all_bundles_info` to load auth token from env varible

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#6880]
It would be more convenient to receive not only an arg of `auth_token`, but also support to load from env variable.
More bundles will require more times of requests, and easier to reach to rate limit, therefore enabling the token from an env variable is helpful to reduce the rate limit issue in some places such as running the CI tests.

cc @wyli

**Comment by wyli** [comment]
this is not required since https://github.com/Project-MONAI/MONAI/pull/6997, we can revisit if there are other cases using an auth_token.
