### ISSUE TITLE
monai.data.DataLoader with num_workers > 0

### ISSUE THREAD

**Issue by YazdanSalimi** [Project-MONAI/MONAI#6881]
Thanks for the great project!
I'd like to know if you solved the problem of monai.data. DataLoader with num_workers more than zero. 
the issue is related to torch and is somehow solved in this comment : 
"https://discuss.pytorch.org/t/errors-when-using-num-workers-0-in-dataloader/97564"
However, when I select num_workers more than zero the execution time goes from 30 to 140 seconds per epoch. 
wrapping the code in if __name__ == "__main__": solve the error but still running very slow.
Thank you.

**Comment by ericspod** [comment]
This is likely related to general Python multiprocessing behaviour and possibly Windows behaviour if you're on that platform. Our DataLoader class inherits directly from Pytorch's class and doesn't change anything that would impact this behaviour. As far as Pytorch code is concerned we can't really fix that I feel. Beyond what the solution here is the behaviour of DataLoader is dependent on what transforms you have, so your slower times might be related to multiple processes trying to access disk storage at once. It can also be related to what Dataset class you use and whether these are cached or not.

**Comment by YazdanSalimi** [comment]
Thank you for your answer. 
I did not mention that I am using Windows 11. the dataset is cached and stored on SSD drive.
I believe this is torch limitation. 
Thanks

**Comment by ericspod** [comment]
Yes, I'm afraid it is likely a Windows problem (since it doesn't use fork), and possibly some optimisation that would help with data access. One possiblity is to try [ThreadDataLoader](https://github.com/Project-MONAI/MONAI/blob/6e471401f7dd8a0067fe36325bb1cc6611e924b6/monai/data/thread_buffer.py#L137) with `use_thread_workers=True` and see if that helps under Windows.
