### ISSUE TITLE
DistributedWeightedRandomSampler remove `shuffle=False` option

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6885]
**Describe the bug**
https://github.com/Project-MONAI/MONAI/blob/4cd717ca830ed7cd811144d96675fdbe586633a4/monai/data/samplers.py#L98
the random sampler will always generate 'shuffled' outputs, the `shuffle=False` option is not valid and should be removed

**Comment by AmirAflak** [comment]
Would like to take this.
