### ISSUE TITLE
robust username masking in print_config

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6914]
https://github.com/Project-MONAI/MONAI/blob/6f5005fddfaf935cc9b723be823f446a09136d11/monai/config/deviceconfig.py#L103-L110
if home directories are in other locations, eg. networked directories, the regex patterns won't match. I'd suggest a more thorough approach is to get the username with `getpass.getuser()` or `os.path.basename(os.path.expanduser("~"))` then replace all instances of that string in the output with "<username>". This will catch more places but will miss paths that might contain other identifying names, but these should be very rare.

_Originally posted by @ericspod in https://github.com/Project-MONAI/MONAI/issues/6913#issuecomment-1699093111_

**Comment by anishrajan25** [comment]
@wyli I would like to pick this up.
