### ISSUE TITLE
connected component analysis to return components individually

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6926]
**Is your feature request related to a problem? Please describe.**
the current implementation is hard coded to merge top N components
https://github.com/Project-MONAI/MONAI/blob/df1779b742caa7ffdfa4115eafff3ce96da0c6f1/monai/transforms/utils.py#L1056-L1058

would be great to optionally return individual components as channels

**Comment by vikashg** [comment]
ITs possible to leverage other libraries for addressing these tasks so maybe we can leverage them @wyli please reopen if needed
