### ISSUE TITLE
How to deal with segmentation with multi-class labels?

### ISSUE THREAD

**Issue by SHAUNZXY** [Project-MONAI/MONAI#696]
Hi,
Would it be possible to modify the 3d segmentation example to a multi-class labels segmentation?
Best,
Shaun

**Comment by Nic-Ma** [comment]
Hi @SHAUNZXY ,

Thanks for your feature request here!
I think it's similar to https://github.com/Project-MONAI/MONAI/issues/415.
As the existing spleen tutorial is a multi-classes segmentation task, I will also add a multi-labels segmentation tutorial soon.

Thanks.

**Comment by SHAUNZXY** [comment]
Thanks so much!

**Comment by wyli** [comment]
should be addressed by #715, if it's not the case, please file a new issue.
