### ISSUE TITLE
init_bundle Should Put License File in `docs`

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#6964]
**Is your feature request related to a problem? Please describe.**
When `init_bundle` is used to create a new bundle directory it should put the temp license file in `docs` instead of the root.

**Comment by wyli** [comment]
currently the model zoo items have the `LICENCE` in at the root directory and `data_license.txt` in the `docs/` https://github.com/Project-MONAI/model-zoo/blob/dev/CONTRIBUTING.md#license-format `init_bundle`  is currently follow this format..

**Comment by ericspod** [comment]
The [specification](https://docs.monai.io/en/stable/mb_specification.html ) has the file in `docs`. That seems neater to me but if that's not wanted we should change the spec then.
