### ISSUE TITLE
Add min_size_in_mm to RemoveSmallObjects transform

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAI#7034]
**Describe the solution you'd like**
RemoveSmallObjects is a great transform that is very much needed. However its arg is  
min_size (int) – objects smaller than this size (in pixel) are removed.
Tumors and organs in medical are measured in mm^3 or CC^3. As radiologist same remove tumors that are smaller than 3 mm 

**Describe alternatives you've considered**
I had to use a transform to resample to 1x1x1 so the pixel count is 1mm^3 remove the tumors then resample back to org size. Instead this should be a simple multiplication as we have the dims actual measurements in the metadata

**Comment by wyli** [comment]
the `min_size` can take into account the `metatensor.pixdim` if it's a MetaTensor before the converting https://github.com/Project-MONAI/MONAI/blob/cc3faa35a065dc1a0ead90a959687722ba60e290/monai/transforms/utils.py#L1089-L1090

https://github.com/Project-MONAI/MONAI/blob/cc3faa35a065dc1a0ead90a959687722ba60e290/monai/transforms/utils.py#L1101
