### ISSUE TITLE
GradCam

### ISSUE THREAD

**Issue by JuanPabloMontoya271** [Project-MONAI/MONAI#713]
Is there any utility for computing and displaying gradcams?

**Comment by Nic-Ma** [comment]
Hi @JuanPabloMontoya271 ,

Thanks for your suggestion here, we haven't implemented GradCam utility so far, it could be useful to help understand the network. Marked for working group discussion.

Thanks.

**Comment by JuanPabloMontoya271** [comment]
Hi, about this feature, I ended up doing the 3D Gradcam code by myself, I would be happy to share it with you if you want to implement it. Its the least I can do, this opensource project has helped me a lot in my projects. 

:)

**Comment by Nic-Ma** [comment]
Hi @JuanPabloMontoya271 ,

Cool! Thanks very much for sharing!
Glad to learn from it.
Or you can submit a PR directly if you like.

Thanks in advance.

**Comment by synapsesneurons** [comment]
Is there any plan to add GradCam to the next version?
