### ISSUE TITLE
Enhance `list_data_collate` to handle a batch with both list and non-list items

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#7166]
**Is your feature request related to a problem? Please describe.**
Suppose the following transform function is defined:
```python
from monai import transforms as mt
trans = mt.OneOf(
    [
        mt.RandSpatialCropD(['img', 'seg'], roi_size=(8, 8)),
        mt.RandCropByPosNegLabelD(['img', 'seg'], label_key='seg', spatial_size=(8, 8), num_samples=1),
    ],
)
```

If `RandSpatialCropD` is used, it will produce a dict; if `RandCropByPosNegLabelD` is used, it will produce a list of dict.

Later in `list_data_collate`, however, it determines if all the items in a batch should be expanded by only the first item.

https://github.com/Project-MONAI/MONAI/blob/fa15eec1ad668efec89780775363ed69e9a07626/monai/data/utils.py#L501-L502

**Describe the solution you'd like**
Determine for each item respectively if it should be expanded, e.g.:
```python
    data = [
        x
        for item in batch
        for x in (item if isinstance(item, list) else [item])
    ]
```

**Comment by wyli** [comment]
thanks, this looks like a duplicated request of https://github.com/Project-MONAI/MONAI/discussions/6929 https://github.com/Project-MONAI/MONAI/issues/5135, have you tried using `RandSpatialCropSamplesd` instead of `RandSpatialCropD`?

**Comment by function2-llx** [comment]
Yes, this is a duplicate one. `RandSpatialCropSamplesD` works for me, thanks for the suggestion.
