### ISSUE TITLE
Test-Time-Augmentation(TTA)

### ISSUE THREAD

**Issue by mjq93** [Project-MONAI/MONAI#718]
Hi,
    I wonder if you can add some tools for test-time-augmentation, especially in semantic segmentation tasks.
Thank you

**Comment by Nic-Ma** [comment]
Hi @shuanggou ,

Thanks for your feature request.
TTA is very useful for model evaluation. I will try to develop several other `EnsembleEvaluators`(average, vote, etc.) besides existing `SupervisedEvaluator` under `engines`, and then develop some tutorial to show the usage.
Thanks.

**Comment by tvercaut** [comment]
@taigw Feel free to chime in, it would be great to have an implementation of our paper in MONAI:
Wang, Guotai, Wenqi Li, Michael Aertsen, Jan Deprest, Sébastien Ourselin, and Tom Vercauteren. "Aleatoric uncertainty estimation with test-time augmentation for medical image segmentation with convolutional neural networks." Neurocomputing 338 (2019): 34-45. https://doi.org/10.1016/j.neucom.2019.01.103

**Comment by wyli** [comment]
this partly depends on https://github.com/Project-MONAI/MONAI/issues/365
