### ISSUE TITLE
NN-UNet

### ISSUE THREAD

**Issue by iffthomas** [Project-MONAI/MONAI#7190]
Hi, Thank you for implementing an nnUnet api for monai.

I'm currently playing around with your implementation.
I'm curious if there exist a possiblity to change the trainer_class_name to nnUNetTrainer_250epoch while only training for the 2D case on all folds I have (I've got 5).
what would be a suitable approach to achieve this?
I've tried adding --config "2d" that my command would look like this
python -m monai.apps.nnunet nnUNetV2Runner run --input_config='./input.yaml' --trainer_class_name nnUNetTrainer_1epoch --config "2d"

**Comment by KumoLiu** [comment]
Hi @iffthomas, for how to run nnunet, you can refer to this [tutorial](https://github.com/Project-MONAI/tutorials/tree/main/nnunet).
https://github.com/Project-MONAI/MONAI/blob/2658b00a88cb6751ac155cc2d133e35aba0d30de/monai/apps/nnunet/nnunetv2_runner.py#L957
https://github.com/Project-MONAI/MONAI/blob/2658b00a88cb6751ac155cc2d133e35aba0d30de/monai/apps/nnunet/nnunetv2_runner.py#L559
If you use the run command, it will run all the configs by default.

Hope it helps, thanks!
