### ISSUE TITLE
Ensemble Outputs for AutoRunner

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#7204]
Currently, after AutoRunner finished the job, the information about the ensemble methods and metrics are only printed in the log and the user doesn't have any access to the results of the ensemble method. The AutoRunner needs to provide this information to user so she can extract the ensembled models for further inference or other utilizations.

**Comment by vikashg** [comment]
closing as alternatives exist. If needed @drbeh please reopen it.
