### ISSUE TITLE
Improve documentation: Transform parameters with multiple keys 

### ISSUE THREAD

**Issue by msseibel** [Project-MONAI/MONAI#7220]
I was using the RandomZoomd. It took me a while to figure out how to specify different mode parameters for different keys. 
Can you state it clearly in the docs that if keys=[img, mask], then mode should/can be set as mode=['area','nearest']? Better: Use dictionary based mapping: mode = {'img':'area', 'mask':'nearest'}. I assume that my concern does not only apply to this function but to many more.

**Comment by KumoLiu** [comment]
Hi @msseibel, thanks for your interest here.
I think we mentioned this in the docstring, that mode can be a sequence of string, each element corresponds to a key in ``keys``.
https://github.com/Project-MONAI/MONAI/blob/782c1e616312612c9f25bf4a33986ace67f7851e/monai/transforms/spatial/dictionary.py#L2026

**Comment by msseibel** [comment]
Ah. Thank you. My bad. I was reading the documentation in my local MONAI folder and there it was missing.
