### ISSUE TITLE
Enhance deepedit transforms to do label check

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#7225]
Errors should be raises if input wrong `label_names`

cc @diazandr3s @Nic-Ma

**Comment by diazandr3s** [comment]
> Errors should be raises if input wrong `label_names`
> 
> cc @diazandr3s @Nic-Ma

Hi @yiheng-wang-nv,

This is a good point. One thing we could do is to use **.lower()** for the label names.
However, a minimum typo in the label name would be recognised as a completely different label. 
Maybe with regular expressions?

**Comment by yiheng-wang-nv** [comment]
Hi @diazandr3s , thanks for the suggestion. I think for the first version, we can simply add `.lower()` only. I will submit a PR soon.

**Comment by yiheng-wang-nv** [comment]
I rethink about this requirements, the current logic is like:
```
# Creating guidance for all clicks
all_guidances = {}
for key_label in self.label_names.keys():
clicks = d.get(key_label, [])
clicks = list(np.array(clicks).astype(int))
all_guidances[key_label] = self._apply(clicks, factor)
d[self.guidance] = all_guidances
```
in the transform level, it may not be able to check input data keys. For example, if the input data and label names are like:
```
data = {'image': image_id, 'spleen': [[1, 2, 3,], [1, 2, 2]], 'bounding_box': [[2, 3], [4, 5]}
label_names = {
        "spleen": 1,
        "background": 0
    }
```
We cannot consider `bounding_box` as an error, since it may be used for other purpose, such as for the next transform or for loss calculation, ...

HI @diazandr3s , what do you think? Maybe we can close this issue right now
