### ISSUE TITLE
SegResNet in 1D not supported yet

### ISSUE THREAD

**Issue by nvahmadi** [Project-MONAI/MONAI#7235]
The SegResNet architecture has proven to be competitive to UNet for segmentation problems in 2D and 3D, which makes it popular for benchmarking (and it is a default architecture in Auto3DSeg).
Recently, I tried benchmarking it against UNet for a 1D "segmentation" problem, namely photometry basecalling in genomic sequencers. UNet architectures from MONAI actually can be used for 1D, and they offer many options for parametrization. 
Unfortunately, SegResNet is restricted to 2D or 3D (see [code](photometry )). Would it be difficult to enable it for 1D? @myron

**Comment by vikashg** [comment]
closing as very specific case and also out of scope for monai I think
