### ISSUE TITLE
DenseNet121 failing to register in AzureML using mlflow

### ISSUE THREAD

**Issue by kavmar** [Project-MONAI/MONAI#7246]
Hi,

I hope my set up it not too particular to the MONAI project. I have difficulties with DenseNet121 in combination with AzureML. 

I am trying to train on a local GPU MONAI DenseNet121 model and log it into AzureML using python SDK and mlflow. The training and communication is ok and I can save the model locally. However, model is not getting registered into AzureML Registry. I have simplified the training script to a bare minimum to demonstrate the problem: 

Here is the script to reproduce the problemr:
import torch
from monai.networks.nets import DenseNet
#from DenseNet import DenseNet

import mlflow
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--mlflow_tracking_uri", type=str, help="mlflow tracking uri")
parser.add_argument("--exp_name", type=str, help="experiment name")
args = parser.parse_args()

mlflow_tracking_uri = args.mlflow_tracking_uri

outputs_dir = "outputs"
model_name = "local_model"
experiment_name = args.exp_name
mlflow.set_tracking_uri(mlflow_tracking_uri)
mlflow.set_experiment(experiment_name=experiment_name)
  
# Start logging
run = mlflow.start_run()

# monai model
model = DenseNet(spatial_dims=2, in_channels=3, out_channels=1000).to("cuda")
# torch model
#model = DenseNet(num_classes=1000).to("cuda")

torch.save(model.state_dict(), 'large_densenet.pth')
model.load_state_dict(torch.load('large_densenet.pth'))
 
# mlflow.tracking
mlflow.pytorch.log_model(
    pytorch_model=model,
    registered_model_name=model_name,
    artifact_path=model_name
)
 
mlflow.stop()

Interestingly, if I run the code with pure pytorch DenseNet, the model gets registered. To me this shows that communication/credentials is not a problem. I tried several MONAI models and found that the above code I am able to register in AzureML the following models: AHNet, SegResNet, SEResNet50, SEResNeXt50, HighResNet, RegUNet, GlobalNet, FullyConnectedNet
But these are failing: SegResNetVAE, UNet, SwinUNETR, VNet, VarFullyConnectedNet, FlexUNet, DenseNet121

 I am not able to figure out what could be the problem with these MONAI models. Any thought are highly appreciated.

Thanks a lot

**Comment by KumoLiu** [comment]
Hi @kavmar, I can't reproduce the issue from the given code. Could you please share more information such as the error message, MONAI version, and so on?
Thanks!

**Comment by kavmar** [comment]
Hi @KumoLiu . Thanks for looking into this.
First and foremost, I have to emphasize that I run with local compute, not in AzureML. I create a virtualenv and pip install torch mlflow azure-ai-ml azureml-mlflow monai azureml-core
To authenticate against Azure I use Service Principal, though InteractiveBrowserCredential should work as well. I have another python script to set up an MLClient job (including workspace, environment). In this script I also obtain mlflow_tracking uri for mlflow running in Azure, where I log the metrics. I want to emphasize that metrics nicely make it AzureML. Then I call:

job = command(
    code="./",
    command=f"python dense_model.py --mlflow_tracking_uri {mlflow_tracking_uri} --exp_name {experiment_name}",
    compute='local',
    environment=env,
    experiment_name=experiment_name,
)

where dense_model.py contains the code from my first post. Again I emphasize that mlflow is not local, but runs in AzureML.  The error message is not telling really much:

azure.core.exceptions.ServiceResponseError: ('Connection aborted.', TimeoutError('The write operation timed out'))

But I do not  think it is related to connectivity or size of the model. Pure pytorch DenseNet model is double size of monai DenseNet121 and pytorch is happily registered. It seems to me as if there would be something in monai DenseNet121, which mlflow cannot cope with, while assuming it is pytorch model.

Thanks a lot for your thoughts.

**Comment by KumoLiu** [comment]
Hi @kavmar, I tried `mlflow.pytorch.log_model` to log `DenseNet121` with mlflow==2.8.1, and no issue reports.
<img width="182" alt="Screen Shot 2023-11-22 at 11 44 31" src="https://github.com/Project-MONAI/MONAI/assets/55491388/2cf0eb09-66ec-4a46-958b-ae7e28a2b8a5">

**Comment by kavmar** [comment]
Hi @KumoLiu. Is the screenshot from **Azure ML Studio workspace**? Can you try to go to Models > Artifacts and Download the model.pth? Does it download the file?

![download_model](https://github.com/Project-MONAI/MONAI/assets/120589640/ec48c10c-c973-4db5-97fe-740720814b49)

**Comment by KumoLiu** [comment]
Hi @kavmar, I just ran it locally to try to confirm whether DenseNet can be uploaded to mlflow successfully, and the model can be downloaded successfully.

**Comment by kavmar** [comment]
Hi @KumoLiu. I understand now. You run training script and mlflow locally to show that the model can be registered. I did the same and can confirm this is the case.
I hoped that somebody with AzureML Studio access would be able to reproduce the problem and possibly have an idea what could the core. What seems to be the case is that when AzureML is left out, the involved components, that is mlflow and DenseNet121 from monai work as expected. Which point's towards azureml-mlflow wrapper component, whcih AzureML uses. 

Thanks for support and time spent while testing.
