### ISSUE TITLE
Checkpoint Function Not Well Tested For Old Pytorch Versions

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#7265]
**Describe the bug**
The function `torch.utils.checkpoint.checkpoint` doesn't have a `use_reentrant` argument in Pytorch<=1.10. This function is used with this argument in `SwinUNETR` but tests don't cover the case where using checkpointing is enabled. The tests should be enhanced to account for this, or we drop support for older versions of Pytorch. This is related to an issue in PR #7260.

**To Reproduce**
1. Create an instance of `SwinUNETR` with `use_checkpoint=True` and attempt a forward pass using an older version of Pytorch.

**Expected behavior**
Forward pass should work as normal.

**Environment**

Pytorch<=1.10.

**Comment by KumoLiu** [comment]
A simple solution would be to skip the test before 1.10. What do you think?
