### ISSUE TITLE
Implement the ability to use layernorm with resnet models

### ISSUE THREAD

**Issue by MiguelMonteiro** [Project-MONAI/MONAI#7294]
**Is your feature request related to a problem? Please describe.**
Batch norm can be problematic with small batch sizes and certain applications due to computing running batch statistics. Layernorm does not have this problem but it is not available to use in with monai's resnet models:

```
from monai.networks.nets.resnet import ...
```

**Describe the solution you'd like**
Implement the ability to use layer norm with resnet models

**Describe alternatives you've considered**
I have tried using other models which support layer norm such as densenet but it seems to be broken also. See https://github.com/Project-MONAI/MONAI/issues/7293

**Comment by aymuos15** [comment]
Hi @KumoLiu

Could I work on this?

**Comment by KumoLiu** [comment]
@aymuos15, sure, please refer to the [CONTRIBUTION GUIDE](https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md).
