### ISSUE TITLE
PicklingError on spleen_segmentation_3d.ipynb

### ISSUE THREAD

**Issue by MunemuraSuzuki** [Project-MONAI/MONAI#735]
Hi I'm new to MONAI and Pytorch

I'm trying 'Medical image segmentation tutorial'.
I copied and run the cell under 'Execute a typical PyTorch training process', but  while it displayed 'epoch 1/600', PickingError raised.
PicklingError: Can't pickle <function CropForegroundd.<lambda> at 0x0000028FCC417510>: attribute lookup CropForegroundd.<lambda> on monai.transforms.croppad.dictionary failed
Please tell me how to fix this error.
best,

My environment is as follows
Windows10
MONAI version: 0.2.0+17.g34d2a70
Python version: 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.18.5
Pytorch version: 1.5.1

Optional dependencies:
Pytorch Ignite version: 0.3.0
Nibabel version: 3.1.1
scikit-image version: 0.17.2
Pillow version: 7.1.2
Tensorboard version: 2.2.2

**Comment by Nic-Ma** [comment]
Hi @MunemuraSuzuki ,

Thanks for your interest here.
May I know which tutorial you ran? We don't have a tutorial named "Medical image segmentation tutorial".
I think you mean the spleen segmentation tutorial:
https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/spleen_segmentation_3d.ipynb
I tried to run it and can't reproduce your issue.

Thanks.

**Comment by MunemuraSuzuki** [comment]
Hi @Nic-Ma 

Thank you for quick response.
Yes, I tried the spleen_segmentation_3d.ipynb.
I tired again, but got the same result.
Now, I copied the all output message.
Is there any key to solve the problem?

Thanks.

----------
epoch 1/600

---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-8-1d74214f2c44> in <module>
     11     epoch_loss = 0
     12     step = 0
---> 13     for batch_data in train_loader:
     14         step += 1
     15         inputs, labels = batch_data['image'].to(device), batch_data['label'].to(device)

~\.conda\envs\MONAI1\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    277             return _SingleProcessDataLoaderIter(self)
    278         else:
--> 279             return _MultiProcessingDataLoaderIter(self)
    280 
    281     @property

~\.conda\envs\MONAI1\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    717             #     before it starts, and __del__ tries to join but will get:
    718             #     AssertionError: can only join a started process.
--> 719             w.start()
    720             self._index_queues.append(index_queue)
    721             self._workers.append(w)

~\.conda\envs\MONAI1\lib\multiprocessing\process.py in start(self)
    103                'daemonic processes are not allowed to have children'
    104         _cleanup()
--> 105         self._popen = self._Popen(self)
    106         self._sentinel = self._popen.sentinel
    107         # Avoid a refcycle if the target function holds an indirect

~\.conda\envs\MONAI1\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~\.conda\envs\MONAI1\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

~\.conda\envs\MONAI1\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     63             try:
     64                 reduction.dump(prep_data, to_child)
---> 65                 reduction.dump(process_obj, to_child)
     66             finally:
     67                 set_spawning_popen(None)

~\.conda\envs\MONAI1\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

PicklingError: Can't pickle <function CropForegroundd.<lambda> at 0x00000240AD5B8268>: attribute lookup CropForegroundd.<lambda> on monai.transforms.croppad.dictionary failed

**Comment by Nic-Ma** [comment]
Hi @MunemuraSuzuki ,

I think maybe your issue is something related to the multi-processing in windows.
You can refer to: https://github.com/Project-MONAI/MONAI/issues/684 first.

Thanks.

**Comment by MunemuraSuzuki** [comment]
Hi @Nic-Ma 

According to your advise, I refered to  #684 
I  set num_workers to 0, and the cord worked !

Thanks.
