### ISSUE TITLE
MedNIST Example Fails on Colab under MONAI 0.2.0 but works on 0.1.0

### ISSUE THREAD

**Issue by brymrsh** [Project-MONAI/MONAI#741]
**Describe the bug**

**To Reproduce**
1. Go to Colab and run through example
2. Install MONAI 0.1.0 to see that it works but fails under 0.2.0
3. Run commands Documented in example

**Expected behavior**
Can you please update example to work under 0.2.0.

.

**Comment by Nic-Ma** [comment]
Hi @brymrsh ,

Thanks for your bug report!
1. Could you please help confirm whether the MedNIST tutorial in MONAI is correct? https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_tutorial.ipynb
2. Could you please help provide your error log?

@wyli we need to double-check the MedNIST tutorial in Colab.

Thanks.

**Comment by wyli** [comment]
thanks -- now fixed

**Comment by brymrsh** [comment]
I pulled and ran in my AWS environment and I had same issue.  Works for 0.1.0 but fails for 0.2.0.

Thanks,
Bryan

**Comment by Nic-Ma** [comment]
Hi @brymrsh , could you please help provide your error log?

Hi @wyli , seems the issue exists in some specific environment, I reopen it.

Thanks.

**Comment by wyli** [comment]
thanks, triple checked that the Colab instance works fine. perhaps the Jupyter notebook has some issue in a certain environment, please file a separate ticket with more details if needed.

**Comment by brymrsh** [comment]
It works for me now, thanks for fix!

I also have integrated MONAI 0.2.0 into our AWS SageMaker ML service if interested I am happy to share for community.

Thanks,
Bryan Marsh
AWS Solution Architect
brymrsh@amazon.com
