### ISSUE TITLE
Kernel crash when using SwinTransformer from swin_unetr.py, while all other models work fine. 

### ISSUE THREAD

**Issue by jrad9921** [Project-MONAI/MONAI#7447]
I'm unable to load SwinTransformers from the swin_unetr.py. The script just gets killed everytime SwinTransformers are being used inside it.  

In the interactive, the kernel crashes everytime the model is loaded:
model = monai.networks.nets.swin_unetr.SwinTransformer(in_chans = 1, embed_dim = feature_size, window_size = window_size, patch_size = patch_size, depths = depths, num_heads = num_heads).to(dev)

with the error: "The Kernel crashed while executing code in the current cell or a previous cell. 
Please review the code in the cell(s) to identify a possible cause of the failure. 
Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. 
View Jupyter [log](command:jupyter.viewOutput) for further details."

With any other monai model, the script runs fine, even with ViT. 

I updated my environment after which this issue with SwinTransformer has emerged. So could this be a problem of version clash of NumPy with some package that only the swin_unetr depends on and therefore not with any other networks?

**Comment by KumoLiu** [comment]
Hi @jrad9921, the reason may be the insufficient memory since SwinTransformer should be a large model than many other networks . Did you check your memory?

**Comment by jrad9921** [comment]
Thank you @KumoLiu, yes it was the memory problem, reduced the window size by half and it works now with 43546872 many parameters.
