### ISSUE TITLE
Python 3.12 import AttributeError: 'FileFinder' object has no attribute 'find_module'

### ISSUE THREAD

**Issue by Hendrik-code** [Project-MONAI/MONAI#7458]
**Describe the bug**
When installing monai (via pip) into a conda environment of python 3.12.1, I get a 
"
AttributeError: 'FileFinder' object has no attribute 'find_module'
"
as soon as i call "import monai"

**To Reproduce**
1. conda create --name test python=3.12
2. conda activate test
3. pip install monai
4. python
5. import monai
-> see screenshot below

**Expected behavior**
I should be able to import monai

**Screenshots**
installing monai triggered a lot of other package installations: 
![Screenshot from 2024-02-09 13-06-58](https://github.com/Project-MONAI/MONAI/assets/19862882/71118752-d811-4034-af86-1c0eb70a625a)

![Screenshot from 2024-02-09 13-03-27](https://github.com/Project-MONAI/MONAI/assets/19862882/7b505ba6-1501-4e11-b6e9-bc3a883b2e8b)

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c "import monai; monai.config.print_debug_info()"
```
Well, the import statement crashes, so this info cannot be given.

**Additional context**
I am pretty sure it has to do with "find_module" being deprecated in python 3.12, as well as the "load_module" function in monai.utils.module.py (line 210 and following). Probably needs to be replaced with the 3.12 version of those function calls.

**Comment by ImranNust** [comment]
I am facing the same issue. Have you resolved it? Do I need to depreciate the python library to lower version?

**Comment by ImranNust** [comment]
> I am facing the same issue. Have you resolved it? Do I need to depreciate the python library to lower version?

I just downgraded Python to 11* version and installed monai, and it worked!
