### ISSUE TITLE
Bug about function "compute_meandice" in monai/metrics/meandice.py.

### ISSUE THREAD

**Issue by mjq93** [Project-MONAI/MONAI#746]
Hi, 
    I used the function  "compute_meandice", and found that result is nan if the labels are all negative samples. I think maybe it can be modified this way:
![image](https://user-images.githubusercontent.com/11666931/87281911-4b3dec80-c526-11ea-8db2-a8e28de19aab.png)
Thank you

**Comment by Nic-Ma** [comment]
Hi @mjq93 ,

Thanks for your interest here.
Actually, I think "Nan" is expected output here, and we should skip "Nan" when computing the average value.
You can find more details in [DiceMetric](https://github.com/Project-MONAI/MONAI/blob/master/monai/metrics/meandice.py#L22).

Thanks.

**Comment by mjq93** [comment]
Hi @Nic-Ma ,
Thank you for your kind reply, I got it. I think you are right.
Thanks.
