### ISSUE TITLE
Random Motion artifacts for MRI

### ISSUE THREAD

**Issue by Can-Zhao** [Project-MONAI/MONAI#7499]
**Is your feature request related to a problem? Please describe.**
I was wondering if we are interested in more MRI data augmentation like:
https://torchio.readthedocs.io/transforms/augmentation.html#torchio.transforms.RandomMotion
https://torchio.readthedocs.io/transforms/augmentation.html#torchio.transforms.RandomGhosting

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by girishsenthil** [comment]
Is this issue looking for an implementation using the library linked or a completely new implementation for the monai repo?

**Comment by Can-Zhao** [comment]
I was not sure which way works better

**Comment by SomeUserName1** [comment]
Is the goal here to use torchio through monai?
Reimplementation seems to me unnecessary as torchios augmentation transforms work well - Am i overseeing something?

**Comment by KumoLiu** [comment]
Hi @SomeUserName1, certainly, it would indeed be beneficial to incorporate a feature similar to PyTorch's TorchVision into MONAI. If developed as a wrapper transform, it can seamlessly integrate with other existing transforms, enhancing our overall functionality.
https://github.com/Project-MONAI/MONAI/blob/c3a7383494b35f82bc3193797a3b07629e94c0c0/monai/transforms/utility/array.py#L1130
Thanks!

**Comment by SomeUserName1** [comment]
Will do on monday, thanks for the pointer!
