### ISSUE TITLE
NiftiSaver saves image unreadable with SimpleITK

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#753]
**Describe the bug**
The saved results in "research>coplenet-pneumonia-lesion-segmentation" cannot be opened in ITK-SNAP. It results in an error (see screenshot). I can open the files in Python with SimpleITK.ReadImage()

**To Reproduce**
Run the "coplenet-pneumonia-lesion-segmentation" MONAI research example and try to open the segmentation mask (e.g.: .../MONAI/research/coplenet-pneumonia-lesion-segmentation/output/case_1/case_1_seg.nii.gz) with ITK-SNAP.

**Screenshots**
![image](https://user-images.githubusercontent.com/10415569/87379802-25562d80-c5a2-11ea-9d59-5c4ee6fa9766.png)

**Environment (please complete the following information):**
 - Python version 3.6.9
 - MONAI version [e.g. git commit hash] 0.2.0 (running as explained in [research example](https://github.com/Project-MONAI/MONAI/tree/master/research/coplenet-pneumonia-lesion-segmentation))

**Comment by Nic-Ma** [comment]
Hi @wyli , could you please help check this issue? Did we test NiftiSaver with SimpleITK before?
Thanks.

**Comment by bartmch** [comment]
Setting the meta_data to None results in the same ITK-SNAP issue. I'm working with ITK-SNAP version 3.8.0
Opening the same nii.gz with SimpleITK in Python seems to work. Saving it from here with `sitk.ImageFileWriter()` yields the same error.

**Comment by wyli** [comment]
yes, I can replicate this issue. ITK-SANP is not happy with long long int as the data type. please consider using some other visualisation software, or change line 55 of `run_inference.py` from 
```python
saver = NiftiSaver(output_dir=OUTPUT_FOLDER)
```
to 
```python
saver = NiftiSaver(output_dir=OUTPUT_FOLDER, dtype=np.int8)
```

(please feel free to reopen if the problem persists)
