### ISSUE TITLE
DataLoader failed when num_workers greater than zero

### ISSUE THREAD

**Issue by jslalu** [Project-MONAI/MONAI#755]
I am new to MONAI. When I set num_workers  greater than 0, the following error occurred. Does anybody have a solution to this problem?

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by Nic-Ma** [comment]
Hi @jslalu ,

May I know your software environment?
And what example program did your run?
Thanks.

**Comment by jslalu** [comment]
@Nic-Ma I run the program in Windows 10, and here are versions of some key modules.

MONAI version: 0.2.0
Python version: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
Numpy version: 1.18.5
Pytorch version: 1.5.1

Optional dependencies:
Pytorch Ignite version: 0.4.0
Nibabel version: 3.1.1
scikit-image version: 0.17.2
Pillow version: 7.2.0
Tensorboard version: 2.2.2

I am working on a classification task in which I adapted the MedNIST example to enable Nifti input. Setting num_workers=0 is OK, but greater than 0 is not. Hope you can find the problem from the attached code. 

Thanks.

[classification_demo.zip](https://github.com/Project-MONAI/MONAI/files/4918239/classification_demo.zip)

**Comment by Nic-Ma** [comment]
Hi @jslalu ,

I feel your issue is similar to https://github.com/Project-MONAI/MONAI/issues/306, it's a known issue of PyTorch.
Can we you add `main` function and try again?

Thanks.

**Comment by jslalu** [comment]
@Nic-Ma It works, but I feel no spped up in every iteration. Is it because my batch size is too small (batch_size = 5, num_workers = 5)? In which case will the num_worksers param make a difference?

Thanks.

**Comment by Nic-Ma** [comment]
Hi @jslalu ,

I think that's some common PyTorch topic, maybe you need to do some experiments for more details?
Please feel free to raise issues if related to MONAI bugs.

Thanks.
