### ISSUE TITLE
`DeprecationWarning`: `pkg_resources` is deprecated as an API in `utils/module.py`

### ISSUE THREAD

**Issue by joshuacwnewton** [Project-MONAI/MONAI#7559]
The following warning has appeared in our `pytest` output:

```python
=============================== warnings summary ===============================
python/envs/venv_sct/lib/python3.9/site-packages/monai/utils/module.py:396
  /home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/utils/module.py:396:"""
DeprecationWarning: pkg_resources is deprecated as an API. 
See https://setuptools.pypa.io/en/latest/pkg_resources.html
    pkg = __import__(module)  # top level module
"""
```

MONAI version: `1.3.0`

Skimming the MONAI source code, it seems like MONAI made this an optional import in https://github.com/Project-MONAI/MONAI/pull/2482:

https://github.com/Project-MONAI/MONAI/blob/ec63e068fec85dff5f043d73f2c029b359332707/monai/utils/module.py#L591

But, it seems like `pkg_resources` shouldn't be used at all: https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by rukundob451** [comment]
@joshuacwnewton is this issue still available?

**Comment by joshuacwnewton** [comment]
I presume so, given that there have been no changes to the MONAI codebase to remove the usage of `pkg_resources`. :)

**Comment by ken-ni** [comment]
I'm with CodeDay Labs 2024, my team is currently working on this.
