### ISSUE TITLE
Elastic3D causes error when using mixed precision training (apex.amp)

### ISSUE THREAD

**Issue by YuhuaBillChen** [Project-MONAI/MONAI#759]
**Describe the bug**
When using the apex.amp to train a model with MONAI's Elastic3D transformation as input, it raises errors about "Double Tensor" is being used in the graph, which stops the mixed-precision training because amp assumes every tensor in the model is float32.
After removing the Elastic3D transform, the whole program works like a charm, so it must be the Elastic3D causing the error.

**To Reproduce**
1. Install Nvidia's Apex package: https://github.com/NVIDIA/apex
2. Put the Elastic Transform into the MONAI dataset
3. Follow the instruction to add amp mixed-precision training: https://nvidia.github.io/apex/amp.html
4. Train the model

**Expected behavior**
Should not raise any issues and amp should be using.

**Screenshots**
![image](https://user-images.githubusercontent.com/9154611/87502387-4c4e4700-c616-11ea-8863-b3ee8252a66a.png)

**Environment (please complete the following information):**
 - OS Ubuntu 18.04
 - Python version 3.7
 - MONAI version [e.g. git commit hash] v0.2
 - CUDA/cuDNN version                    10.1
 - GPU models and configuration      Titan RTX

**Additional context**
It seems like the Gaussian filter causes it for the random affine grid inside the Elastic3D, which is using double precisions. I think an easy way to solve this issue is to convert the tensor into float32 explicitly.

**Comment by Nic-Ma** [comment]
Hi @YuhuaBillChen ,

Thanks for your experiments and detailed results.
As PyTorch is going to release v1.6 soon which will officially support AMP, we didn't enable AMP by NVIDIA Apex.
We will totally support AMP when PyTorch v1.6 released and try to make all modules compatible.
If you want to use Apex for your experiments now, maybe you can easily modify the code to work around first?

Thanks.
