### ISSUE TITLE
Incorrect operation of dense_patch_slices

### ISSUE THREAD

**Issue by murraycutforth** [Project-MONAI/MONAI#761]
**Describe the bug**
I found that the sliding window inference function was much slower than expected. Looking into this, I found that the dense_patch_slices function is returning many duplicated slices for certain inputs.

**To Reproduce**
For example:

```
>>> x = dense_patch_slices(image_size=(100,100), patch_size=(50,50), scan_interval=(25,25))
>>> for slice in x:
...     print(slice)
... 
(slice(0, 50, None), slice(0, 50, None))
(slice(0, 50, None), slice(25, 75, None))
(slice(0, 50, None), slice(50, 100, None))
(slice(0, 50, None), slice(50, 100, None))
(slice(25, 75, None), slice(0, 50, None))
(slice(25, 75, None), slice(25, 75, None))
(slice(25, 75, None), slice(50, 100, None))
(slice(25, 75, None), slice(50, 100, None))
(slice(50, 100, None), slice(0, 50, None))
(slice(50, 100, None), slice(25, 75, None))
(slice(50, 100, None), slice(50, 100, None))
(slice(50, 100, None), slice(50, 100, None))
(slice(50, 100, None), slice(0, 50, None))
(slice(50, 100, None), slice(25, 75, None))
(slice(50, 100, None), slice(50, 100, None))
(slice(50, 100, None), slice(50, 100, None))
```

**Expected behavior**
dense_patch_slices should return a list of slice objects which cover the volume, overlap by the specified scan interval, but without any duplicates.

**Environment (please complete the following information):**
 - OS: Centos 7
 - MONAI version: 0.2.0+34.g267407f

**Additional context**
I would like to fix this problem, and add a few unit tests for this function at the same time.

**Comment by Nic-Ma** [comment]
Hi @murraycutforth ,

Thanks very much for your bug report and detailed experiments!
I submitted PR https://github.com/Project-MONAI/MONAI/pull/763 to fix this issue.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @murraycutforth, PR has been merged, could you please help update to the latest code and verify again?

Thanks.
