### ISSUE TITLE
minior comment error

### ISSUE THREAD

**Issue by mjq93** [Project-MONAI/MONAI#764]
![image](https://user-images.githubusercontent.com/11666931/87648023-32ca0e00-c782-11ea-98fa-dcb1c3098c35.png)
![image](https://user-images.githubusercontent.com/11666931/87648182-42495700-c782-11ea-8df5-c89fddb5bc83.png)

**Comment by Nic-Ma** [comment]
Hi @mjq93 ,

Thanks for your feedback.
These 2 parameters work together to generate the label ratio, so I put the same dos-string for them.
Anyway, I submitted PR #768 to update the doc-string and make it more clear.

Thanks.
