### ISSUE TITLE
Cannot fing the medical_resnet50 model when using perceptual loss

### ISSUE THREAD

**Issue by vasl12** [Project-MONAI/MONAI#7645]
In monai/losses/perceptual.py

I would like to report that the model names do not correspond to the models in torch hub for the medical datasets and as a result the perceptual loss class is cumbersome to deal with.

E.g. `medical_resnet50_23datasets `should become `medicalnet_resnet50_23datasets` in order to find the model in torch hub.

`class PercetualNetworkType(StrEnum):
    alex = "alex"
    vgg = "vgg"
    squeeze = "squeeze"
    radimagenet_resnet50 = "radimagenet_resnet50"
    medicalnet_resnet10_23datasets = "medicalnet_resnet10_23datasets"
    medical_resnet50_23datasets = "medical_resnet50_23datasets"
    resnet50 = "resnet50"
`

**Comment by Lucas-rbnt** [comment]
Hi, it seems that this problem has already been solved in this recent PR #7548
