### ISSUE TITLE
How to input two different modal images

### ISSUE THREAD

**Issue by shenao1994** [Project-MONAI/MONAI#765]
I am a MONAI rookie.I checked the documentation, but did not find a detailed explanation. Now I have two modal images of T2 and ADC. Can you tell me the specific method of input? Thank you!

**Comment by shenao1994** [comment]
`    train_files = [{"t2Img": t2Img, "adcImg": adcImg, "label": label} for t2Img, adcImg, label in
                   zip(t2_image_file_list[:10],
                       adc_image_file_list[:10],
                       image_label_list[:10])]`
......
`        for batch_data in train_loader:
            step += 1
            inputs, labels = batch_data["t2Img"].to(device), batch_data["label"].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_function(outputs, labels)`

**Comment by Nic-Ma** [comment]
Hi @shenao1994 ,

I checked your code, seems you can get "t2Img" and "adImg" from `batch_data` keys, so could you please explain more details about your question?

Thanks.

**Comment by shenao1994** [comment]
@Nic-Ma I want to know how to modify the input so that it can inputs two modals of t2 and adc.In other words, input t2 and adc in the dictionary as two channels.I can only input t2 images now.

**Comment by Nic-Ma** [comment]
Hi @shenao1994 ,

I see, if you want to make them into 2 channels, you can use the `ConcatItemsd` transform:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/utility/dictionary.py#L387
And if your images don't have channel dim, please use `AddChanneld` first.

Thanks.

**Comment by shenao1994** [comment]
@Nic-Ma 
It's very helpful to me!

Thanks!

**Comment by shenao1994** [comment]
@Nic-Ma Sorry to bother you again.I modified the code according to your prompt.I modified the code according to your prompt. However, an error occurred during operation. Please help me look at the code. I modified **in-channels=2**, but told me to input two channels. I don't know how to input separately.
`train_transforms = Compose(
        [
            LoadNiftid(keys=["t2Img", "adcImg"]),
            AddChanneld(keys=["t2Img", "adcImg"]),
            ScaleIntensityd(keys=["t2Img", "adcImg"]),
            Resized(keys=["t2Img", "adcImg"], spatial_size=(32, 32, 32)),
            RandRotate90d(keys=["t2Img", "adcImg"], prob=0.8, spatial_axes=[0, 1]),
            ToTensord(keys=["t2Img", "adcImg"]),
        ]
    )
    val_transforms = Compose(
        [
            LoadNiftid(keys=["t2Img", "adcImg"]),
            AddChanneld(keys=["t2Img", "adcImg"]),
            ScaleIntensityd(keys=["t2Img", "adcImg"]),
            Resized(keys=["t2Img", "adcImg"], spatial_size=(32, 32, 32)),
            ToTensord(keys=["t2Img", "adcImg"]),
        ]
    )

    # Define dataset, data loader
    check_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    check_loader = DataLoader(check_ds, batch_size=2, num_workers=4, pin_memory=torch.device)
    check_data = monai.utils.misc.first(check_loader)
    print(check_data["t2Img"].shape, check_data["adcImg"].shape, check_data["label"])

    # create a training data loader
    device = torch.device("cpu")
    train_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=4, pin_memory=torch.device)

    # create a validation data loader
    val_ds = monai.data.Dataset(data=val_files, transform=val_transforms)
    val_loader = DataLoader(val_ds, batch_size=2, num_workers=4, pin_memory=torch.device)

    # Create DenseNet121, CrossEntropyLoss and Adam optimizer

    model = monai.networks.nets.densenet.densenet121(spatial_dims=3, in_channels=2, out_channels=2).to(device)
    loss_function = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), 1e-5)

    # start a typical PyTorch training
    val_interval = 2
    best_metric = -1
    best_metric_epoch = -1
    writer = SummaryWriter()
    for epoch in range(5):
        print("-" * 10)
        print(f"epoch {epoch + 1}/{5}")
        model.train()
        epoch_loss = 0
        step = 0
        for batch_data in train_loader:
            step += 1
            print(batch_data)
            result = ConcatItemsd(keys=["t2Img", "adcImg"], name="inputs")(batch_data)
            inputs, labels = result["inputs"].to(device), batch_data["label"].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_function(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            epoch_len = len(train_ds) // train_loader.batch_size
            print(f"{step}/{epoch_len}, train_loss: {loss.item():.4f}")
            writer.add_scalar("train_loss", loss.item(), epoch_len * epoch + step)
        epoch_loss /= step`

_**RuntimeError: Given groups=1, weight of size 64 2 7 7 7, expected input[4, 1, 32, 32, 32] to have 2 channels, but got 1 channels instead**_

**Comment by Nic-Ma** [comment]
Hi @shenao1994 ,

I saw you didn't put the `ConcatItemsd` transform in the transform chain and you didn't load your labels.
If this is a segmentation task, suggest:
```py
train_transforms = Compose([
    LoadNiftid(keys=["t2Img", "adcImg", "label"]),
    AddChanneld(keys=["t2Img", "adcImg"]), # I suppose you label data already have 2 channels
    ConcatItemsd(keys=["t2Img", "adcImg"], name="img")
    ScaleIntensityd(keys="img"),
    Resized(keys=["img", "label"], spatial_size=(32, 32, 32)),
    RandRotate90d(keys=["img", "label"], prob=0.8, spatial_axes=[0, 1]),
    ToTensord(keys=["img", "label"])
])
```

Thanks.

**Comment by shenao1994** [comment]
@Nic-Ma 
Thank you very much for your suggestion.It's a classification task.So Can I modify the code according to your method in a classification task?

**Comment by Nic-Ma** [comment]
I think so, if classification, you don't need to resize or rotate on labels.
Thanks.

**Comment by sulaimanvesal** [comment]
> Hi @shenao1994 ,
> 
> I saw you didn't put the `ConcatItemsd` transform in the transform chain and you didn't load your labels. If this is a segmentation task, suggest:
> 
> ```python
> train_transforms = Compose([
>     LoadNiftid(keys=["t2Img", "adcImg", "label"]),
>     AddChanneld(keys=["t2Img", "adcImg"]), # I suppose you label data already have 2 channels
>     ConcatItemsd(keys=["t2Img", "adcImg"], name="img")
>     ScaleIntensityd(keys="img"),
>     Resized(keys=["img", "label"], spatial_size=(32, 32, 32)),
>     RandRotate90d(keys=["img", "label"], prob=0.8, spatial_axes=[0, 1]),
>     ToTensord(keys=["img", "label"])
> ])
> ```
> 
> Thanks.

I am doing this but get the following error?

RuntimeError: stack expects each tensor to be equal size
