### ISSUE TITLE
Missing `alpha` parameter of Focal loss in DiceFocalLoss

### ISSUE THREAD

**Issue by dkalsan** [Project-MONAI/MONAI#7682]
**Describe the bug**
The available class [monai.losses.DiceFocalLoss](https://docs.monai.io/en/stable/_modules/monai/losses/dice.html#DiceFocalLoss) is missing the `alpha` parameter for Focal loss. Is this a result of some design choice or just got overlooked in the implementation?

**Expected behavior**
`alpha` parameter should be passed to the monai.losses.FocalLoss or have the reason for its absence documented.

**Comment by KumoLiu** [comment]
Hi @dkalsan, what does `alpha` mean here, can you be more explicit? Thanks.

**Comment by dkalsan** [comment]
I mean the argument passed down to the FocalLoss class during construction, which results in an alpha-balanced Focal loss as per the paper. I believe this argument should also be available in the DiceFocalLoss since it's effectively just a wrapper around the two losses.

From the [docstring of FocalLoss](https://docs.monai.io/en/stable/losses.html#monai.losses.FocalLoss):
> alpha – value of the alpha in the definition of the alpha-balanced Focal loss. The value should be in [0, 1]. Defaults to None.
