### ISSUE TITLE
Adopt, promote, and enforce *automatic* import sorting

### ISSUE THREAD

**Issue by benjamin-gorman** [Project-MONAI/MONAI#776]
**Is your feature request related to a problem? Please describe.**

An extension of #340 to cover imports.

**Describe the solution you'd like**

[isort](https://timothycrosley.github.io/isort/) seems to be the popular option. Was [worked on](https://github.com/psf/black/issues/333#issuecomment-653737073) to include a [black profile](https://timothycrosley.github.io/isort/docs/configuration/profiles/) for easy integration.

```ini
[isort]
profile = black
line_length = 120
skip = .git, venv, versioneer.py, _version.py, conf.py
skip_glob = *.pyi
```

[GitHub Action](https://github.com/olance/isort-action)

**Describe alternatives you've considered**

Not adding another tool to the chain. The order of imports is not detrimental.

**Comment by Nic-Ma** [comment]
Hi @benjamin-gorman ,

Looks like an interesting format tool, do you plan to work a PR?
Thanks.

**Comment by benjamin-gorman** [comment]
> Hi @benjamin-gorman ,
> 
> Looks like an interesting format tool, do you plan to work a PR?
> Thanks.

Opened #781

**Comment by wyli** [comment]
update: #781 has been merged, need to revise the CI and auto formatted before closing this ticket
