### ISSUE TITLE
Add MedNeXt model architectures within MONAI

### ISSUE THREAD

**Issue by surajpaib** [Project-MONAI/MONAI#7786]
**Is your feature request related to a problem? Please describe.**
There seems to be some demand for ConvNeXt based architectures #4798 implemented in MONAI. Having a ConvNeXt-based segmentation model could be quite useful as it seems to perform very convincingly, based on results from this paper https://arxiv.org/abs/2404.09556

**Describe the solution you'd like**
Provide an implementation of the MedNeXt model architecture in MONAI

**Additional context**
I've implemented and benchmarked an implementation of `MedNeXt`, heavily based on code (https://github.com/MIC-DKFZ/MedNeXt) from the original authors. This implementation has support for dynamic configuration of blocks and follows an API very similar to `SegResNetDS` and was benchmarked through MONAI bundle config. 

Happy to contribute this to MONAI (with the proper source attribution) if there is interest.

**Comment by KumoLiu** [comment]
Hi @surajpaib, welcome to the contribution, and if you like you can also add a bundle with your benchmark result into the model zoo repo and tutorial in the tutorial repo! Thanks!

**Comment by surajpaib** [comment]
Hi @KumoLiu, great! 

I will make a PR first into the core and then I can probably spend some time later making it a zoo supported bundle, right now   I am using [lighter](https://github.com/project-lighter/lighter) with the MONAI bundle config structure and it might need some tweaks.

**Comment by rcremese** [comment]
Hello @surajpaib,
I'm also interested by implementing MedNeXt in the MONAI core library as a first participation in an open-source project.
So I just wonder where you are with it so far and if you need help for integration.

**Comment by surajpaib** [comment]
Hi @rcremese 

I've got the mednext code repurposed from the original repo to a very MONAI SegResNet like interface. I'll need to make the push to my MONAI fork. I'm currently busy on a work trip. I'll hopefully push it over the next week. It would be great to have some help with testing and simple performance benchmarks if that interests you

**Comment by rcremese** [comment]
Well, it's my turn to be in hollidays. But sure I would be interested to help on that issue. Just tell me what kind of benchmark you want me to test and wich branch of your fork I should use to test your implementation.

**Comment by surajpaib** [comment]
Hi @rcremese,

I've made an early PR for the mednext implementation and added some basic tests similar to the segresnet. 

I've tested this version on a training loop as well and it seems to perform well - I ran this a while ago and it seems like I've purged my results. 

If you could also run a quick training loop, that would be really nice I think. Not sure of any other tests that come to mind.

**Comment by surajpaib** [comment]
As @KumoLiu suggested, we could also work together to add a tutorial, model bundle and put the test results there

**Comment by rcremese** [comment]
Hi @surajpaib ,
