### ISSUE TITLE
monai.utils depends on deprecated/removed distutils package

### ISSUE THREAD

**Issue by bcdarwin** [Project-MONAI/MONAI#7790]
**Describe the bug**

Technically more of a feature request, `monai.utils.misc` uses `distutils.utils.strtobool` which prevents this module from being imported in Python 3.12.

See [here](https://github.com/Project-MONAI/MONAI/blob/1.3.1/monai/utils/misc.py#L27).

**To Reproduce**

With Python 3.12.x and MONAI 1.13.1:

`import monai.utils`

**Comment by rdozier-work** [comment]
+1 to this

**Comment by bcdarwin** [comment]
> +1 to this

@rdozier-work this was done in #7900, just hasn't hit trunk yet.

**Comment by KumoLiu** [comment]
You can use monai-weekly as a workaround for now.
```
pip install monai-weekly
```
