### ISSUE TITLE
implement reference networks from papers using pure pytorch

### ISSUE THREAD

**Issue by atbenmurray** [Project-MONAI/MONAI#78]

**Comment by wyli** [comment]
please create a separate ticket for each of the todos:
- [ ]  highresnet
- [ ] dense v-net
- [ ] squeeze-and-excitation resnet
- [ ] resnext
- [ ] se-resnext
- [ ] standard VAE
- [ ] deepmedic
- [ ] holistic network
- [ ] affine/deform net


https://niftynet.readthedocs.io/en/dev/niftynet.network.html

**Comment by tvercaut** [comment]
There is no clear action point that I can see related to this issue -> closing
