### ISSUE TITLE
Missing documentation for `Invert`

### ISSUE THREAD

**Issue by kvttt** [Project-MONAI/MONAI#7832]
**Describe the bug**
Previously reported [here](https://github.com/Project-MONAI/MONAI/discussions/7289) and [here](https://github.com/Project-MONAI/MONAI/issues/7286). The documentation for `Invert` is [missing](https://docs.monai.io/en/stable/transforms.html#post-processing).

**Additional context**
It is somewhat confusing to see `Invertd` in the documentation but not `Invert`, especially for users who look at the documentation instead of source code for reference.

**Comment by rajatkhanduja** [comment]
@kvttt, @KumoLiu 

The [documentation](https://docs.monai.io/en/stable/transforms.html#invert) is no longer missing. Should the issue be marked closed?
