### ISSUE TITLE
The resolution to be used in input images for inferencing in a  trained nodule detector model

### ISSUE THREAD

**Issue by Rajesh-ParaxialTech** [Project-MONAI/MONAI#7844]
Hello

![image](https://github.com/Project-MONAI/MONAI/assets/159233894/b35e08d7-4898-43ba-b030-2e581f06da42)

In case of a  nodule detector model trained with images with resolution 0.7 x 0.7 x 1.25, does that mean the input images used in future during inferencing also must be of the same resolution ?  

Thanks

Rajesh

**Comment by KumoLiu** [comment]
Duplicated with https://github.com/Project-MONAI/MONAI/discussions/7846.
