### ISSUE TITLE
monai 0.2.0 windows OS with the error "_pickle.PicklingError" when run "spleen_segmentation_3d.ipynb"

### ISSUE THREAD

**Issue by guoyingbo** [Project-MONAI/MONAI#787]
**Describe the bug**
when I run spleen_segmentation_3d.ipynb on windows 10 
it report error report:
_pickle.PicklingError: Can't pickle <function CropForegroundd.<lambda> at 0x000001E4C0440168>: attribute lookup CropForegroundd.<lambda> on monai.transforms.croppad.dictionary failed

**To Reproduce**
2. Install '....'
3. Run commands '....'

**Expected behavior**

**Screenshots**
"C:\Program Files\Python37\python.exe" D:/data/spleen_segmentation_3d.py
MONAI version: 0.2.0+44.gd7f3b98
Python version: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.19.0
Pytorch version: 1.5.1

Optional dependencies:
Pytorch Ignite version: 0.3.0
Nibabel version: 3.1.0
scikit-image version: 0.17.2
Pillow version: 7.1.2
Tensorboard version: 2.2.2

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

image shape: torch.Size([226, 157, 113]), label shape: torch.Size([226, 157, 113])
32/32 Load and cache transformed data:  [==============================]
9/9 Load and cache transformed data:  [==============================]
----------
epoch 1/600
Traceback (most recent call last):
  File "D:/data/spleen_segmentation_3d.py", line 184, in <module>
    for batch_data in train_loader:
  File "C:\Program Files\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Program Files\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function CropForegroundd.<lambda> at 0x000001E4C0440168>: attribute lookup CropForegroundd.<lambda> on monai.transforms.croppad.dictionary failed

Process finished with exit code 1
**Environment (please complete the following information):**
 - OS=windows10 64bit
 - Python version 3.7.8
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version
 - GPU models and configuration

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @guoyingbo ,

Thanks for your interest here.
I think this is known issue of PyTorch multi-processing, you can find more details and solution here: https://github.com/Project-MONAI/MONAI/issues/735

Thanks.

**Comment by wyli** [comment]
added to the FAQ https://github.com/Project-MONAI/MONAI/wiki/Frequently-asked-questions-and-answers (please feel free to reopen)
