### ISSUE TITLE
Reproducibility clarification

### ISSUE THREAD

**Issue by wantinghuang** [Project-MONAI/MONAI#788]
Hi, I have a few questions about reproducibility in MONAI.
MONAI states "reproducible" as its feature but we all know that PyTorch states that some of its API is a source of nondeterminism in [docs](https://pytorch.org/docs/stable/notes/randomness.html). 
In this sense, how does MONAI prevent nondeterminism and maintain reproducibility?
Does this mean that MONAI avoid all the functions that caused nondeterminism, such as torch.nn.functional.interpolate()? 
Can the training process be reproduced when we only use MONAI API for training and inference? What if we add a self-defined data augmentation that include source of nondeterminism, such as torch.nn.functional.interpolate()?

PS: I also wander how MONAI differ from Clara. They both have data augmentations and model architectures and are both supported by NVIDIA. Other than open source, does MONAI have something that surpass Clara? Why does Nvidia launch this project when there has been Clara? Would you please help me to clear the confusions...
Many thanks.

**Comment by Nic-Ma** [comment]
Hi @wantinghuang ,

Thanks for your interest in project MONAI.
For the reproducible features, currently, MONAI keeps the same as PyTorch, we build MONAI based on PyTorch, may try to optimize more features in future versions.
For Clara & MONAI questions, @pdogra89 could you please help share some description?

Thanks.

**Comment by wantinghuang** [comment]
Hi @Nic-Ma, thanks for your response.
