### ISSUE TITLE
CUDA implementation of higher-order image resampling (e.g. cubic spline)

### ISSUE THREAD

**Issue by tvercaut** [Project-MONAI/MONAI#789]
**Is your feature request related to a problem? Please describe.**
Pytorch's [`grid-sample`](https://pytorch.org/docs/stable/nn.functional.html#grid-sample) function provides a GPU implementation of linear interpolation for image redsampling. Registration networks and warping-based augmentation layers may benefit from higher-order image resampling which is currently not available in either pytorch or MONAI.

**Describe the solution you'd like**
Implement a CUDA-based higher-order interpolation layer allowing for a backward pass (i.e. differentiable).

**Describe alternatives you've considered**
N/A

**Additional context**
NiftyNet ported the code from NiftyReg for that purpose: https://niftynet.readthedocs.io/en/dev/niftynet.contrib.niftyreg_image_resampling.html

This issue spins from #95 and relies on #785 for enabling a propoer packaging of such feature.

**Comment by tvercaut** [comment]
Copying some notes from #1452 to ease the discussion.

The nitorch-based code in MONAI (https://github.com/Project-MONAI/MONAI/tree/master/monai/csrc/resample) only partially adresses the need. It seems we have two options:
- increase the scope of the current implementation and also include pre-filtering (e.g. based on https://github.com/DannyRuijters/CubicInterpolationCUDA)
- switch to a more complete implementation (e.g. based on niftyreg as done for NiftyNet https://github.com/NifTK/NiftyNet/tree/dev/niftynet/contrib/niftyreg_image_resampling)

**Comment by vikashg** [comment]
closing as the issue was closed earlier
