### ISSUE TITLE
Update doc to drop support Python 3.8 when it meets its the end of life 

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/MONAI#7915]
**Describe the bug**

Since Python 3.8 is near end of life, and MONAI start dropping tests. Please also update the installation documentation to reflect this change.

- https://github.com/Project-MONAI/MONAI/blob/dev/docs/images/python.svg
- https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md
- https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/installation.md
- https://github.com/Project-MONAI/MONAI/blob/9554f471a416d2f111dce08cf2d729254a502e48/monai/apps/auto3dseg/auto_runner.py#L554
- https://github.com/Project-MONAI/MONAI/blob/9554f471a416d2f111dce08cf2d729254a502e48/monai/auto3dseg/utils.py#L410
- https://github.com/Project-MONAI/MONAI/blob/9554f471a416d2f111dce08cf2d729254a502e48/setup.cfg#L24
- https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md

**Comment by KumoLiu** [comment]
It's already fixed in https://github.com/Project-MONAI/MONAI/pull/7909.

**Comment by mingxin-zheng** [comment]
Thanks!
