### ISSUE TITLE
Scipy Deprecation Warnings

### ISSUE THREAD

**Issue by scarere** [Project-MONAI/MONAI#7956]
**Is your feature request related to a problem? Please describe.**
Scipy warnings when importing monai.apps.utils.download_and_extract. Would like these warnings to be addressed so that they go away

![Screenshot from 2024-07-26 11-14-23](https://github.com/user-attachments/assets/86fc9e29-89c2-40e9-85bb-579cdd5806c5)

**Comment by KumoLiu** [comment]
Hi @scarere, thanks for pointing this out. It has been fixed in https://github.com/Project-MONAI/MONAI/issues/7677.
Could you please try with the latest or monai-weekly? Thanks!
