### ISSUE TITLE
Can I use multiple images as multi-channel input in trasnforms?

### ISSUE THREAD

**Issue by zulubal01** [Project-MONAI/MONAI#796]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @zulubal01 ,

Thanks for your interest here.
Yes, you can use multiple images as multi-channels in ways:
1. If you images are in same shape, you can load them together by passing a list of file paths to `LoadNifti` or `LoadNiftid`.
2. If you images are not in same shape, you can load them separately and concate them by `ConcateItemsd`, similar to: https://github.com/Project-MONAI/MONAI/issues/794

Thanks.
