### ISSUE TITLE
"Developer Guide" Tutorial link in the docs needs to point to latest version

### ISSUE THREAD

**Issue by hmeine** [Project-MONAI/MONAI#7968]
**Describe the bug**
As someone interested in MONAI, I just used the Colab link to the tutorial from the docs: https://colab.research.google.com/drive/1boqy7ENpKrqaJoxFlbHIBnIODAs1Ih1T

This tutorial instantiates mt.AddChannelD transforms which no longer exist in the latest MONAI release. I spent a few minutes trying to 

**To Reproduce**
1. Go to https://colab.research.google.com/drive/1boqy7ENpKrqaJoxFlbHIBnIODAs1Ih1T
2. Run all cells
3. Observe error

**Expected behavior**
The introductory notebook should run through without errors.

**Comment by hmeine** [comment]
While I did search for an existing issue in this repo, I only found the tutorial repo later. There, it already seems to be tackled (https://github.com/Project-MONAI/tutorials/pull/1527), yet the official docs still contain a link to an old notebook version, apparently. So I'll change the title to reflect the remaining action to be taken.

**Comment by hmeine** [comment]
Sorry, I did not want to close the issue, but it should remind of the necessary update of https://docs.monai.io/en/stable/#getting-started

**Comment by hmeine** [comment]
Maybe https://colab.research.google.com/github/Project-MONAI/tutorials/blob/main/modules/developer_guide.ipynb would be a better link than using a specific google drive copy?

**Comment by KumoLiu** [comment]
Hi @hmeine, thanks for pointing it out, I have created a pr to fix it.
https://github.com/Project-MONAI/MONAI/pull/7971

Thanks.
