### ISSUE TITLE
triggering integration tests for PR that is ready to merge

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#801]
**Is your feature request related to a problem? Please describe.**
currently each commit to a new/existing PR triggers a set of quick unit tests but not the integration tests,
would be great to provide an option (probably via the existing chatops) to trigger the integration tests before merging the PRs

**Comment by behxyz** [comment]
@wyli, just to clarify this issue, you want to write in a PR comment something like `/integration` and it triggers and runs `runtest.sh --net`, right?

**Comment by wyli** [comment]
exactly, currently `/black` triggers the formatting workflow defined here: https://github.com/Project-MONAI/monai-code-formatter/tree/master/.github/workflows. ideally `/integration` command would trigger the integration workflow from that repo https://github.com/Project-MONAI/monai-code-formatter/actions. our self hosted test server is shared among the repos under project-monai org.
