### ISSUE TITLE
Add LogSoftmax option in dice.py

### ISSUE THREAD

**Issue by arp95** [Project-MONAI/MONAI#802]
In the dice.py file we have options to add sigmoid or softmax to the output. We can also add LogSoftmax to the output to ensure numeric overflows dont take place.
Either we can replace the softmax operation by LogSoftmax or have both options available.
@wyli @Nic-Ma

**Comment by Nic-Ma** [comment]
Hi @arp95 ,

Thanks for your feature request.
I submitted PR #803 to adjust the activation layers in losses and metrics.

Thanks.
