### ISSUE TITLE
Consider Not Using Pytype in PR tests

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#8022]
**Is your feature request related to a problem? Please describe.**
Pytype is very slow and there's not much that seems to be done about this. One of the checks in PRs is to run this for everything which significantly slows down the review process occasionally. Would we be better off moving this to an occasional test instead? Typically if mypy is ok with code pytype is as well so there's not that much value.

**Describe the solution you'd like**
Move pytype to be weekly test or something like this. Optionally we could test with pyright but this is throwing up a lot of errors currently owing to our import system (which may benefit from a revamp itself).

**Comment by KumoLiu** [comment]
Hi @ericspod, as suggested, I set the pytype test as not required for each PR and added the format test to weekly-preview.
