### ISSUE TITLE
Multiprocessing error when running python3 auto3dseg_hello_world.py

### ISSUE THREAD

**Issue by dvitaly07** [Project-MONAI/MONAI#8023]
Running auto3dseg_hello_world.py on a multi GPU processing cluster triggers a multiprocessing error:
![Screenshot from 2024-08-18 11-11-41](https://github.com/user-attachments/assets/6e3545c1-32f6-48d2-99f2-9d06049435c1)
![Screenshot from 2024-08-18 11-13-31](https://github.com/user-attachments/assets/e0b2ac2c-c7d8-4df4-a19a-70c1a185c073)

**Comment by KumoLiu** [comment]
Closed as duplicated with https://github.com/Project-MONAI/tutorials/discussions/1790
