### ISSUE TITLE
Indexing not working as expected

### ISSUE THREAD

**Issue by msseibel** [Project-MONAI/MONAI#8046]
Hi,

there is an inconsistency between PyTorch and Monai for the indexing behavior.

`arr` is a `monai.data.meta_tensor.MetaTensor` 

Indexing with np.arange(2) / torch.arange(2) does not work:

arr[np.arange(2)].shape
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/smp/lib/python3.9/site-packages/monai/data/meta_tensor.py", line 297, in __torch_function__
    ret = MetaTensor.update_meta(ret, func, args, kwargs)
  File "/opt/conda/envs/smp/lib/python3.9/site-packages/monai/data/meta_tensor.py", line 236, in update_meta
    if batch_idx not in (slice(None, None, None), Ellipsis, None) and idx == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Indexing from a torch array with the same shape, device and dtype works:
```
torch.randn(*arr.shape,device=arr.device,dtype=arr.dtype)[np.arange(2)].shape
torch.Size([2, 11, 416])
```

Converting `arr` to vanilla pytorch fixes the problem, but I am uncertain about the implications.

I am using Monai 1.2.0. Has this been fixed in recent version? Or has at least the error message improved? E.g. a hint could be added to convert the tensor to vanilla pytorch with `as_tensor`.

**Comment by KumoLiu** [comment]
Hi @msseibel, I tried with the latest version, it works fine now.
```
from monai.data import MetaTensor
import numpy as np
import torch
arr = MetaTensor(np.random.rand(2, 11, 416))
arr[np.arange(2)].shape
```

Thanks!

**Comment by msseibel** [comment]
Good know. One more reason to upgrade! Thanks.
