### ISSUE TITLE
black and mypy didn't format chars more than 120

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#809]
**Describe the bug**
I found some doc-strings > 120 but wasn't formatted or detected by CI, for example:
https://github.com/Project-MONAI/MONAI/commit/68cfbd345aeb3622b5434cb8671cc95998be3341#diff-c320296cf3910802a1348c3e65c09f29L44
and
https://github.com/Project-MONAI/MONAI/pull/803/commits/68cfbd345aeb3622b5434cb8671cc95998be3341#diff-22747695a3870bf9f59c050fd75e0600L51

**Comment by wyli** [comment]
looks like a known issue of black https://github.com/psf/black/issues/144

**Comment by wyli** [comment]
this won't be fixed unless black considers this feature
