### ISSUE TITLE
Is monai down?

### ISSUE THREAD

**Issue by snaka99** [Project-MONAI/MONAI#8158]
Hi I was trying to enter monai's documentation but i cant , is monai down?

**Comment by KumoLiu** [comment]
Hi @snaka99, yes, we’re following up on this. Will fix it ASAP. Thanks.

**Comment by MiguelMonteiro** [comment]
Hello, is there a place where I can find a copy of the documentation while the main website is down?

**Comment by MIKE-GUO233** [comment]
the website is still down, when can you fix it💔？

**Comment by aylward** [comment]
It is back.   The domain provider made a mistake.  We regret the inconvenience.
