### ISSUE TITLE
3d medical image classification

### ISSUE THREAD

**Issue by saishanbhag** [Project-MONAI/MONAI#817]
Hi,
It would be of great help if you can help me with the following - I'm working on detecting blockages in blood vessels using a video( CT scan) of the concerned region of the body. So basically i want to classify whether the video shows an example of clogged blood vessel or a freely flowing blood vessel. Could you suggest any MONAI package i can use to build the solution framework ?

**Comment by Nic-Ma** [comment]
Hi @saishanbhag ,

Thanks for your interest here!
Basically, I think you can refer to this 3D medical image classification example: https://github.com/Project-MONAI/MONAI/tree/master/examples/classification_3d
And as video classification may be slightly different at the Z dimension, you need to think about whether it's the same as the 3D image.

Thanks.

**Comment by saishanbhag** [comment]
Thanks for your prompt reply. I will try stacking the frames from the video to build a tensor similar to a 3D image.
