### ISSUE TITLE
Support different save path for `trt_compile`

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#8175]
Currently, the `.plan` file will be produced in the same path as the model weights. However, if the model weights is in a read only folder, permission error may happen.

I think we should add a separate arg "plan_path" for `trt_compile` function.

Hi @borisfom , what do you think?

**Comment by borisfom** [comment]
Why, it is supposed - user can use any path as base_path in trt_compile() call - I just used weights path as base_path in inference_trt.json for convenience (and dependency on weights).

**Comment by yiheng-wang-nv** [comment]
Thanks for the explain, let me close this unnecessary issue
