### ISSUE TITLE
Current/upcoming Gradient visualisation functionalities?

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#818]
Hi, I'm currently using Captum in my Pytorch code to make my models more "explainable". Does Monai have any built-in functions such as DeepLift? If not, is there any such functionality on the roadmap?

**Comment by Nic-Ma** [comment]
Hi @bartmch ,

That's an interesting idea, we don't have such functions in MONAI so far.
I marked for discussion in MONAI working group.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Can we close this ticket now as you already implemented GradCam?

Thanks.
