### ISSUE TITLE
This is a question about classification.

### ISSUE THREAD

**Issue by shenao1994** [Project-MONAI/MONAI#819]
I am dividing a set of image data into five categories. I want to set the label like this, because these data are related. Can you tell me how to modify the related code?

**1   1 0 0 0 0
2   1 1 0 0 0 
3   1 1 1 0 0
4   1 1 1 1 0
5   1 1 1 1 1**

Thanks！

**Comment by Nic-Ma** [comment]
Hi @shenao1994 ,

What's your original label format? I feel you can write some script to convert them.
Is there some MONAI related requirement to convert labels? Maybe you want to develop a transform to convert in run-time?

Thanks.

**Comment by shenao1994** [comment]
The original label is [0, 1, 2, 3, 4]. But there is a connection between my data, so I want to set the label as I said.

**Comment by Nic-Ma** [comment]
Sorry I can't help much with your question as it's not a MONAI issue and I don't quite understand your context.
Maybe you can write a script to `swtich case` the labels?
```py
if label == 0:
    label = [0, 0, 0, 0, 0]
elif label == 1:
    label = [1, 0, 0, 0, 0]
... ...
```

Thanks.
