### ISSUE TITLE
Implementation of HighResBlock and HighResNet having only 1 conv in residual block? 

### ISSUE THREAD

**Issue by acostanzo999** [Project-MONAI/MONAI#823]
Hi, I am modifying the preexisting HighResNet when I noticed in the class HighResBlock there is only one instance of Norm, Activation, Conv and not two like there is in the paper. Am I missing something or is this intentional. I know that the Block itself is repeated three times with one dialation and 6 more times with 2 different dialations.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help double confirm this issue?
Thanks.

**Comment by wyli** [comment]
the current highresblock could have N convolutional layers (https://github.com/Project-MONAI/MONAI/blob/master/monai/networks/nets/highresnet.py#L142) or do i misunderstand your question?

**Comment by acostanzo999** [comment]
Thank you ahh sorry I didn't catch this earlier!
