### ISSUE TITLE
bug in GeneralizedWassersteinDiceLoss

### ISSUE THREAD

**Issue by michalhg** [Project-MONAI/MONAI#826]
in **GeneralizedWassersteinDiceLoss** the forward() is missing : 

if not(target.type() in [torch.LongTensor, torch.cuda.LongTensor]):
            target = target.long()

since the wasserstein_distance_map expects flat_target to be a long  integer type tensor

please fix. otherwise it throws an error

**Comment by Nic-Ma** [comment]
Hi @michalhg ,

Thanks for your bug report!
I will try to fix it soon.

**Comment by wyli** [comment]
cc @LucasFidon
