### ISSUE TITLE
3D image transforms using own data

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#831]
Using Ubuntu server 18.04.

I have been testing some of the interesting tutorials on Monai. They are all functioning as expected. 
I am now trying to use some own MR data for some of these tutorials, for example the 3D_image_transform tutorial, but I am encountering some errors which raises some questions.

The files I want to use for this are:
T1 image: /home/titan/data/test/images/test_009.nii
Label: /home/titan/data/test/labels/test_009.nii.gz

I have named them in such a way to match the filenames in the spleen decathlon set. Do the filenames of the dataset need to follow a certain pattern?

As you see on the below screenshot, I get the error when trying to organize the file names into a list of dictionaries.

![image](https://user-images.githubusercontent.com/54416001/88894803-c868a180-d248-11ea-8fad-94efb243904a.png)

How do I deal with this issue? It might be a very easy question for some of you, but it might be helpful to some of us beginners nonetheless.

**Comment by Nic-Ma** [comment]
Hi @carlpe ,

Thanks for your interest here.
I think it seems like some issue with python APIs instead of MONAI, could you please try to re-run the program and print all the things in `daa_dicts`?
And how many elements in your list? More than 9?

Thanks.

**Comment by carlpe** [comment]
Here is what I found:

![image](https://user-images.githubusercontent.com/54416001/89008508-1645de00-d30b-11ea-9ba8-acfa47c3a76b.png)

**Comment by carlpe** [comment]
I added some more subjects to the server and then this happened:

![image](https://user-images.githubusercontent.com/54416001/89009461-e5ff3f00-d30c-11ea-8253-c6869995a04e.png)


Seems it did not work with only one subject

**Comment by carlpe** [comment]
It works now that I added more 👍

**Comment by Nic-Ma** [comment]
Sounds good!
As your code "[:-9]", it needs at least 9 items.

Thanks.

**Comment by carlpe** [comment]
Oh ok, thank you! 
Do not be surprized if I have more questions for you at a later stage =)
