### ISSUE TITLE
Segmentation tutorial output using own data

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#835]
Testing the spleen segmentation tutorial on some own data....
Everything is working fine up to the point of showing the output. It is blank.

What am I missing here?

![3](https://user-images.githubusercontent.com/54416001/89029409-afd2b700-d32e-11ea-9bb6-148fb38c93e3.png)

**Comment by Nic-Ma** [comment]
Hi @carlpe ,

Maybe you can print out the raw value of `val_outputs` to verify whether it's all 0?

Thanks.

**Comment by carlpe** [comment]
Hi Nic,

Here is the print of val_outputs...

![image](https://user-images.githubusercontent.com/54416001/89155419-13482900-d569-11ea-8ab8-dc4cf845cf67.png)

**Comment by Nic-Ma** [comment]
These are values of the corner, you need to print some values at center of the image.
I think you can also try to remove the `torch.argmax()` and **test every channel** when you plot the values and see whether it can plot something reasonable?

Thanks.
