### ISSUE TITLE
Is there a way to set window level values to all the images on the Compose

### ISSUE THREAD

**Issue by JuanPabloMontoya271** [Project-MONAI/MONAI#838]
Hi is there an specific tool to set the window values to the images?

**Comment by Nic-Ma** [comment]
Hi @JuanPabloMontoya271 ,

What's the `window` you mean here? Image crop or some intensity adjustment?
Thanks.

**Comment by JuanPabloMontoya271** [comment]
The intensity adjustment, like described here:
https://radiopaedia.org/articles/windowing-ct#:~:text=The%20window%20level%20(WL)%2C,be%20brighter%20and%20vice%20versa.

**Comment by Nic-Ma** [comment]
Hi @JuanPabloMontoya271 ,

Maybe this transform is what you need: https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/intensity/dictionary.py#L269

Thanks.

**Comment by JuanPabloMontoya271** [comment]
Thank you, yes that was the solution
