### ISSUE TITLE
Can you visualize the 3D Unet model in Spleen 3D segmentation example?

### ISSUE THREAD

**Issue by zhongyiZhang18** [Project-MONAI/MONAI#846]
The code is quite nice and tidy and it runs prefectly, but there is not much details about the model structure, especially for the res_units part. 

Could you please visualize this model? Thx

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Could you please help provide some docs or introduction about the UNet?

Thanks.

**Comment by ericspod** [comment]
There was a previous question on this here: https://github.com/Project-MONAI/MONAI/issues/464 We had also discussed the structure in a paper on an earlier version of the network: https://link.springer.com/chapter/10.1007/978-3-030-12029-0_40
