### ISSUE TITLE
Saving outputs as Nifti files in Spleen Segmentation example with Pytorch Lightning

### ISSUE THREAD

**Issue by hasansari** [Project-MONAI/MONAI#849]
Hi,

Thanks for your all your efforts to develop Monai and adding some nice examples to try it. I have tried the Spleen PyTorch lightning example with my data and training goes well. I am trying to load the generated .ckpt file, run iference and save the generated outputs as nifti files. Is there an example script for this as well?

**Comment by Nic-Ma** [comment]
Hi @hasansari ,

Thanks for your interest and experiments here.
About how to load PyTorch model, do inference and save Nifti files, you can refer to:
https://github.com/Project-MONAI/MONAI/blob/master/examples/segmentation_3d/unet_evaluation_dict.py
Hi @marksgraham , please feel free to correct me if Lightning has some different ways to do these tasks.

Thanks.

**Comment by marksgraham** [comment]
Yes looks good, just note you can treat the `LightningModule` as the model itself, so modifying @Nic-Ma's example, assuming your module is called `Net` as in the lightning example provided in Monai:

```
# load model
trained_model = Net.load_from_checkpoint(PATH)

# run on an image, x
net.eval()
out = trained_model(x)
```

**Comment by hasansari** [comment]
> Yes looks good, just note you can treat the `LightningModule` as the model itself, so modifying @Nic-Ma's example, assuming your module is called `Net` as in the lightning example provided in Monai:
> 
> ```
> # load model
> trained_model = Net.load_from_checkpoint(PATH)
> 
> # run on an image, x
> net.eval()
> out = trained_model(x)
> ```

Thank you very much. This seems very practical, but I just tried this and got the following error:

RuntimeError: Sizes of tensors must match except in dimension 1. Got 63 and 64 in dimension 2 (The offending index is 1)

Any ideas? Thank you in advance!

**Comment by marksgraham** [comment]
What is the shape of your input, x, and how many layers are there in your
unet?
