### ISSUE TITLE
Nonlinear histogram intensity transform

### ISSUE THREAD

**Issue by marksgraham** [Project-MONAI/MONAI#862]
**Describe the solution you'd like**
I think it would be useful to have a transform that provides random, nonlinear warping of an image's intensity histogram. This is motivated by research showing that strong contrast adjustments can force networks to focus on learning shapes, rather than intensity differences, increasing the generalisability of trained networks to new data, see e.g. [here](https://arxiv.org/pdf/2003.01995.pdf).

**Additional context**
I've already worked on a version of this transform for my own research, and included a couple of examples below. I can integrate into MONAI if you think it would be a good addition.

Mild augmentation:
![image](https://user-images.githubusercontent.com/7947315/89523331-92906380-d7da-11ea-9bd6-2470bc6c46db.png)

Strong augmentation:
![image](https://user-images.githubusercontent.com/7947315/89523766-58739180-d7db-11ea-87ca-a5c270f1e770.png)

**Comment by wyli** [comment]
looks great, just wanted to note that some intensity mappings would cause information loss, for example, in the strong augmentation case, original intensities 5.5 to 7.5 are all mapped to about 8, the relevant tissues become indistinguishable in the transform output

**Comment by Nic-Ma** [comment]
Hi @marksgraham ,

Welcome to contribute your idea to MONAI!
BTW, we have some similar intensity transforms:
https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/intensity/array.py#L300

https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/intensity/array.py#L554

Thanks.
