### ISSUE TITLE
Minor bug in example

### ISSUE THREAD

**Issue by jbschiratti** [Project-MONAI/MONAI#864]
**Describe the bug**
In [`examples/classification_3d_ignite/densenet_training_array.py`](https://github.com/Project-MONAI/MONAI/blob/master/examples/classification_3d_ignite/densenet_training_array.py), the input MRI images have shape `(H, W, C)` but the `Resize` transform expects the channel axis to be first. This "bug" (it might be one although it has little impact) is found in the other classification examples.

**Expected behavior**
One may add a `AsChannelFirst` transform before `Resize`.

**Comment by Nic-Ma** [comment]
Hi @jbschiratti ,

Thanks for your interest here.
The input MRI images are 3D images and have shape `(H, W, D)` without `channel` dim.
So we used `AddChannel` transform to add an additional channel-first dim(almost all transforms suppose channel-first).

Thanks.

**Comment by jbschiratti** [comment]
@Nic-Ma Yes, you're right! Thanks

**Comment by Nic-Ma** [comment]
Hi @jbschiratti ,

No problem, please feel free to raise issues or questions when you using MONAI.
Thanks.
