### ISSUE TITLE
spleen_segmentation_3d_lightning Notebook Bug

### ISSUE THREAD

**Issue by gagandaroach** [Project-MONAI/MONAI#877]
**Describe the bug**

Last cell in notebook "Check best model output with the input image and label"  does not execute.

**To Reproduce**
1. Run Spleen Segmentation 3d Lightning Notebook
2. cell produces error: 

> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Expected behavior**
Model should successfully be evaluated 

**Screenshots**

Identified by @benjamin-gorman in https://github.com/Project-MONAI/MONAI/blob/80e2976573a9dff92fd5cd41d830b606a2e956b0/examples/notebooks/spleen_segmentation_3d_lightning.ipynb

**Environment (please complete the following information):**
I reproduced the bug on
 - OS: Debian Buster
 - Python version:  3.8.3
 - MONAI version: master
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: GTX 1080TI 

**Additional context**
Adding PR fix

**Comment by Nic-Ma** [comment]
Hi @marksgraham , could you please help double confirm and review Gagan's PR for this issue?

Thanks in advance.

**Comment by marksgraham** [comment]
Yes looks good to me!
