### ISSUE TITLE
There are several minor issues in new updated notebooks

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#881]
**Describe the bug**
We just had a very big update for all the notebooks which also brought some minor issues.
Reviewing in process, use this ticket to track:
1. Need to update the dataset paths to public dir instead of a personal home path.
2. Need to update the plot of CacheDataset notebook, used wrong data to plot.
3. Use torch.cuda to profile memory usage.
I will submit a PR to fix all the above issues after review.
4. Some random outputs are not "suitable" to show the transform results.

**Comment by Nic-Ma** [comment]
Hi @ericspod and @wyli ,

I tried to use `torch.cuda.memory_summary()` to print out memory usage, but the output layout is incompatible with jupyter notebook. Good news is that jupyter notebook can "freeze" current GPU memory status after training, so I just added `nvidia-smi` after training, preview of latest notebook:
https://github.com/Nic-Ma/MONAI/blob/881-refine-notebooks/examples/notebooks/automatic_mixed_precision.ipynb

Thanks.

**Comment by wyli** [comment]
it seems the torch memory summary command worked here: https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/transform_speed.ipynb it shows Cur Usage/Peak Usage, not sure how accurate it is

**Comment by ericspod** [comment]
Either notebook looks fine but importantly the different is memory usage is shown with `nvidia-smi`. The other routines in the `torch.cuda` package give a lot of information on what is allocated, reserved, active, blocks, etc. It might be useful to have some profiling/logging mechanism in place to follow these statistics throughout training as well as CPU and main memory usage.

**Comment by Nic-Ma** [comment]
Hi @ericspod and @wyli ,

Thanks for your feedback, I made a mistake before. Updated the notebook to use `torch.cuda.memory_summary()`:
https://github.com/Nic-Ma/MONAI/blob/881-refine-notebooks/examples/notebooks/automatic_mixed_precision.ipynb
I think maybe it's good enough for current stage?

Thanks.

**Comment by ericspod** [comment]
This will do for now, sure. It shows the differing memory usage as we'd expect from AMP.

**Comment by Nic-Ma** [comment]
Merged into new repo: https://github.com/Project-MONAI/Tutorials
Close this ticket now.
Thanks.
