### ISSUE TITLE
Add Convolution transform

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#898]
A convolution manipulation with fixed filter weights is deterministic, thus it can be considered to be a new transform method. In addition, this feature is helpful for implementing #586

**Comment by yiheng-wang-nv** [comment]
use convolution to calculate how many positive pixels around is not feasible, since a large kernel size brings tremendous calculations, let me close this issue and think about other methods.

**Comment by wyli** [comment]
integral image might be helpful? https://en.wikipedia.org/wiki/Summed-area_table

**Comment by yiheng-wang-nv** [comment]
Thanks! Let me take a look!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Wenqi Li <notifications@github.com>
发送时间: Thursday, August 13, 2020 6:01:48 PM
收件人: Project-MONAI/MONAI <MONAI@noreply.github.com>
抄送: Yiheng Wang <vennw@nvidia.com>; State change <state_change@noreply.github.com>
主题: Re: [Project-MONAI/MONAI] Add Convolution transform (#898)


integral image might be helpful? https://en.wikipedia.org/wiki/Summed-area_table

―
