### ISSUE TITLE
intensity normalisation transform

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#9]

**Comment by Nic-Ma** [comment]
Hi @atbenmurray ,

I committed a PR #25 for this task, could you please help review it?
Glad to see your feedback.
Thanks.

**Comment by ericspod** [comment]
Currently we have the functionality to rescale arrays to [0,1] range, this suffices for the segmentation example so we feel it's beyond the MVP scope.

**Comment by Nic-Ma** [comment]
Hi @ericspod  @atbenmurray  @wyli  @yanchengnv ,

Thanks for the discussion of the design principle on transforms.
I think we are on the same page to **use basic PyTorch only**. Then I have several questions about **ShapeFormat**, could you please help make them clear before we start to develop?
1. torchvision supposes the 2D input images are **PIL image** which is "channel last", and converts to **torch.Tensor** which is "channel first" in "toTensor()" transform. Can we also suppose **all 3D input images are "channel last"**?
2. If not all input images are "channel last", how does every transform know the input image is "channel last" or "channel first"? In previous design, we defined a MediaImage object to record **ShapeFormat information with image data** together, then we can support **12 kinds of ShapeFormats** in transforms.
3. Should the transform support to process **both numpy data** and **torch.Tensor data**? If only support numpy data, I think we need to define an implicit transform  "toTensor()" at the end of chain.
Welcome your discussion and please feel free to correct me if I misunderstand anything.
Thanks in advance.

**Comment by wyli** [comment]
@Nic-Ma  as I understand it, for the current sprint we assume the input image is in NifTI format, which uses 'channel last'. Before feeding it to the network we add another 'ToTensor' transform to convert it into a 'channel first' torch tensor. Let's keep the implementation "minimal", for example, [following torch vision's implementation](https://github.com/pytorch/vision/blob/9a22a8a750cbfecfae44adfb1c6e72991637f35f/torchvision/transforms/functional.py#L43).

**Comment by wyli** [comment]
#25 #28 jointly resolve this issue.
