### ISSUE TITLE
GAN questions

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#902]
I am experimenting with GAN and have some general questions. 

**1. How do I resume training from a given checkpoint?**

**2. How can I save my outputs with the spacing that I would prefer? I use the following code to save the outputs at the end, but everytime it outputs with spacing 1.0:**

![image](https://user-images.githubusercontent.com/54416001/90223249-fbe12980-de0d-11ea-8391-9f106e96aa6e.png)

**3. How do I view image reconstructions with random latent codes view trained generator output while using a 3D volume?
Here I would like to show a given slice from the 3D volume like in the "Segmentation tutorial". The code for previews in the GAN tutorial is for 2D only.**

**Comment by carlpe** [comment]
Another thing. What could be the reason for this phenomenon in GAN?

Here the d-loss goes to 250 and the g-loss to 0 after a set of epochs.

![image](https://user-images.githubusercontent.com/54416001/90236810-8c763480-de23-11ea-80ae-b69870ba1f9d.png)

I have resampled my images to different sizes..  it works well with (64,64,64) and (72,72,72).. But  when I try with (128,128,128).. then this happens... 

Do I need to change number of channels or latent size? In case, do I add 128 only to the disc_net channels? 

![image](https://user-images.githubusercontent.com/54416001/90237004-deb75580-de23-11ea-9549-6884feb2994e.png)


Thanks!

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Could you please help on this issue as you are expert on the GAN network and built GAN tutorial.
Thanks in advance.

**Comment by ericspod** [comment]
1. The [GAN workflow notebook](https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_GAN_workflow.ipynb) uses `CheckpointSaver`, so to load use `CheckpointLoader`, such as in [this example](https://github.com/Project-MONAI/MONAI/blob/bbc5e063268182b2d79b02ddb5156a38528cb62a/examples/classification_3d_ignite/densenet_evaluation_array.py). There are other examples using this class to look at as well. 
2. I think the `affine` argument of the `write_nifti` function is what you would want to change the spacing: https://github.com/Project-MONAI/MONAI/blob/0d197e6bea9dd2244c63b80a80b464ef23a5aab9/monai/data/nifti_writer.py#L27
3. For viewing 3D volumes the easiest thing is just slice the volume at a particular place and view it with matplotlib's imshow. An alternative is to use the animation features of matplotlib like [these examples](https://stackoverflow.com/questions/43445103/inline-animations-in-jupyter). We maybe should add some useful utilities for doing this in MONAI later.

The loss issues with the GAN looks possibly like mode collapse. There's always issues with GANs and the stability of training two networks together, this is sensitive to network and data sizes so going to 128^3 could introduce this issue. There's many articles online about mode collapse and GAN stability in general, one thing to try here is to set the discriminator dropout value to something small like 0.15 and see if that helps, and not using residual units in the discriminator as well (`num_res_units=0`). I couldn't say if changing the other network parameters would help or not, the sizes of inputs/outputs is correct.

**Comment by carlpe** [comment]
Thanks for the feedback! I will try it later

**Comment by carlpe** [comment]
I tried with num_res_units=0  over the course of 1000 epochs now first (batch_size=10)

![image](https://user-images.githubusercontent.com/54416001/90402206-66f55f00-e09f-11ea-9bac-7f68011bcdc0.png)

Next I will set dropout to 0.15 and see difference.


The outputs are much better, and the "mode collapse" is not present here.

Do you recommend to add the "best_metric"  code from the GAN tutorial into the GAN workflow ?

**Comment by ericspod** [comment]
It does look better. We didn't use any metrics in the tutorials so "best_metric" shouldn't be mentioned there. If you wanted to use some metric to assess how well the GAN is performing it would depend on the data but something like wasserstein distance or mamixmum mean discrepancy might be appropriate. We haven't these implemented in MONAI yet however.

**Comment by carlpe** [comment]
Yes, a lot better indeed!

It seems as the best_metric is used on the GAN mednist  tutorial (https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_GAN_workflow.ipynb), but not on the GAN workflow notebook (https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_GAN_workflow.ipynb) as of now, or am I mistaken?

Nevertheless. I will continue my experiments and ask more questions here. Is this the best place for such inquiries or is there another site for general discussion? Such IRC group?

**Comment by ericspod** [comment]
`best_metric` is included in the mednist tutorial by accident, it isn't actually used. We should remove it shortly. 

The [Pytorch forums](https://discuss.pytorch.org) would be a good place to ask, and we're working on other venues for help and feedback with users.

**Comment by Nic-Ma** [comment]
I submitted PR https://github.com/Project-MONAI/MONAI/pull/905 to remove the `best_metrics`.

Thanks.

**Comment by carlpe** [comment]
The graph looks like this with dropout = 0.15 .. I did 5000 epochs with batch_size 10
![image](https://user-images.githubusercontent.com/54416001/90483514-19c3cc80-e135-11ea-84c3-08b691e2f0ce.png)

Example of result:
![image](https://user-images.githubusercontent.com/54416001/90483698-627b8580-e135-11ea-949f-ee8afc472f22.png)

Original input example:
![image](https://user-images.githubusercontent.com/54416001/90483768-8212ae00-e135-11ea-87c3-b621fafd02df.png)



The outputs look abit "mosaic"... is it due to the spacing? I did not understand where to use the affine argument in write nifti :-/  

![image](https://user-images.githubusercontent.com/54416001/90483852-acfd0200-e135-11ea-95c6-55dc2af7de64.png)

Please explain how to change the spacing

**Comment by ericspod** [comment]
The mosaicing is perhaps a result of the use of transpose convolutions in the generator, if the kernel size is 3x3x3 they have less overlap over their inputs, so a pixel in one layer derives information from only one other in the previous layer. We were discussing the solution to this, using subpixel convolutions in place of just transpose convolutions, this does involve changing the generator's `_get_layer` to use `SubpixelUpsample`. 

The `affine` argument of `write_nifti` takes a 4x4 array as a value representing the affine transform matrix. By default this will be the identity matrix, instead you can provide a scaling matrix with different scale factors for each dimension to set the spacing of the output nifti file. To scale by SX, SY, SZ in the X, Y, and Z dimensions respectively you would use the value `np.diag([SX,SY,SZ,1])`.

**Comment by carlpe** [comment]
Nice, I will try it out later.
One thing I did notice with some quick experimentung was that the outputs seemed to get better and less "mosaic" when increasing the kernel size. The time needed pr epoch went up though. I tried for example 21 in kernel size just for extreme test, and the mosaic 2as almost gone.

I did also notice that the kernel size needs to be an odd number and the strides an even number.. or else i got an error stating that the dilation was the same, i can not remember exactly, i can paste the error code tomorrow. Is this expected error?

**Comment by ericspod** [comment]
Yes that's expected error, I was discussing in another issue that the rational behind our Convolution class was to ensure an output's spatial size would be divided by the stride, but this works currently with odd kernel sizes only.

**Comment by carlpe** [comment]
I replaced the code the code in generator.py (screenshot left). But I am getting an error when I define the networks (screenshot left side) : ModuleAttributeError: 'Generator' object has no attribute 'use_shuffle'


![image](https://user-images.githubusercontent.com/54416001/91143483-e47a2a00-e6b2-11ea-8ef0-6de1283316e6.png)

**Comment by ericspod** [comment]
That was from my experimental code. Just remove line 155 and move lines 156-185 to the left.

**Comment by carlpe** [comment]
Thanks ericspod 👍

**Comment by carlpe** [comment]
NameError: NameError: name 'SubpixelUpsample' is not defined


![image](https://user-images.githubusercontent.com/54416001/91404423-ecb49f80-e841-11ea-876c-7f241341f7d0.png)

**Comment by carlpe** [comment]
NameError: name 'SubpixelUpsample' is not defined

![image](https://user-images.githubusercontent.com/54416001/91418716-d06d2e80-e852-11ea-95f7-a56c023c4d15.png)

**Comment by carlpe** [comment]
<img width="1081" alt="Screenshot 2020-09-01 at 08 40 14" src="https://user-images.githubusercontent.com/54416001/91810939-09304d80-ec2f-11ea-9ede-303035c79108.png">

The results in this attempt are not much better using SubpixelUpsample.

Here are the parameters used for training 5000 epochs of batchsize 10. The images are 128,128,128.

<img width="447" alt="Screenshot 2020-09-01 at 08 43 40" src="https://user-images.githubusercontent.com/54416001/91811109-41d02700-ec2f-11ea-8853-4379f02df0bb.png">

**Comment by ericspod** [comment]
I assume you're actually using your own network with the replaced `_get_layer` method though your code here says `Generator`. If the `SubpixelUpsample` doesn't help I think that more training might improve the results or otherwise it's a matter of fine tuning these parameters, using possibly different optimizer values, or looking into a better generator architecture for this application area. I not sure what more to do for you here.

**Comment by carlpe** [comment]
Thanks @ericspod for all your feedback. I will keep tuning to see if it improves
