### ISSUE TITLE
can use yolo in monai ?

### ISSUE THREAD

**Issue by joe-China-zhou** [Project-MONAI/MONAI#903]

**Comment by Nic-Ma** [comment]
Hi @joe-China-zhou ,

Actually, MONAI is very flexible, you don't need to use an end-to-end pipeline of MONAI.
Instead, you can only use the transforms or other modules in your YOLO pipeline.

Thanks.

**Comment by joe-China-zhou** [comment]
Sorry, I don't quite understand what you mean. This is my first time to learn Monai and Yolo. If I don't use Yolo, how can I object detection medical images in Monai?

**Comment by Nic-Ma** [comment]
Hi @joe-China-zhou ,

I mean you can use your own YOLO code and use MONAI's transforms or some modules to simplify part of your own code.
MONAI doesn't have image detection examples so far.

Thanks.

**Comment by joe-China-zhou** [comment]
thanks

**Comment by shabanian2018** [comment]
Can you please update me about MONAI models in object detection? Thanks!
