### ISSUE TITLE
sliding_window_inference() in monai.inferers went wrong when roi_size=(M,N,1)

### ISSUE THREAD

**Issue by Can-Zhao** [Project-MONAI/MONAI#906]
**Describe the bug**
sliding_window_inference() gives NaN when roi_size=(M,N,1)

**To Reproduce**
1. Go to sliding_window_inference() in monai.inferers
2. Go to the line: run
slices = dense_patch_slices( image_size=(450, 344, 450), roi_size=(96, 96, 1), scan_interval=(72,72,0))

**Expected behavior**
You will get len(slices)=30, which should be 30*450 instead.

 - MONAI latest
 - docker monai:latest

**Comment by Nic-Ma** [comment]
Hi @Can-Zhao ,

Thanks for your feedback, the root cause is that you used `overlap = 0.25` but the ROI size of dim3 is `1`, so the interval is smaller than even `1`(`0.75`) and MONAI used `floor` to convert to int number.
I changed it to use `ceil` in PR #907 .

Thanks.

**Comment by Can-Zhao** [comment]
Thank you!
