### ISSUE TITLE
revise monai.apps.DecathlonDataset to use AWS open data

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#915]
**Is your feature request related to a problem? Please describe.**
The dataset is now made available via [AWS open data](https://registry.opendata.aws/msd/), the relevant remote data fetching should be updated accordingly.

new URL format: 
   - https://msd-for-monai.s3-us-west-2.amazonaws.com/TaskXX_YYYYYYYY.tar
   - (EU replica) https://msd-for-monai-eu.s3-eu-west-2.amazonaws.com/TaskXX_YYYYYYYY.tar

example: https://gist.github.com/wyli/1c6a568a47e1c8b2f4614a86f565c3f6

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/2397459b2923f3ce758b09656820be9014b7e804/monai/apps/datasets.py#L134-L139

may want to send a pull request to https://github.com/awslabs/open-data-registry/blob/master/datasets/msd.yaml
when we have relevant updates on new demos/examples

cc @mjorgecardoso @pdogra89

**Comment by arp95** [comment]
@wyli is this related to updating the dataset paths in the datasets.py file? Or we need to add new examples on how to download the data and use it? Thanks.

**Comment by wyli** [comment]
> @wyli is this related to updating the dataset paths in the datasets.py file? Or we need to add new examples on how to download the data and use it? Thanks.

Hi @arp95 thanks for your interest here, it'll be some enhancements on the downloading mechanism and the relevant testing pipelines, and probably removing dependencies of `gdown` in many places including the examples and tutorials.

**Comment by arp95** [comment]
@wyli just to understand properly, we were using gdown before for the data and now it is being replaced by aws? I mean can you elaborate more on the downloading mechanism and how is the data used here? Thanks.

**Comment by mjorgecardoso** [comment]
We managed to get an agreement with AWS for a free S3 bucket under their open data program. Thus, we can download data directly and without any google limitations (download limits, china firewalls, etc). Data can be downloaded from s3 directly and efficiently using standard https, so no dependencies such as gdown are not necessary.

**Comment by arp95** [comment]
thanks for clearing it up @mjorgecardoso

**Comment by Nic-Ma** [comment]
Hi @arp95 ,

Do you want to take this task? If yes, welcome to submit a PR for it.
Thanks.

**Comment by arp95** [comment]
@Nic-Ma sure working on it. I need to remove the gdown dependency and replace the data urls with the new aws urls we have right?

**Comment by Nic-Ma** [comment]
@arp95 , you can try to replace the data URLs first, then remove the down dependency.
Thanks.

**Comment by arp95** [comment]
@Nic-Ma sure. will work on that. Thanks.

**Comment by wyli** [comment]
fixed by #930 #946
