### ISSUE TITLE
Execute all the tests on A100 GPU

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#925]
**Is your feature request related to a problem? Please describe.**
In order to make sure MONAI can be compatible with A100 GPU, need to execute all the tests(unit tests and integration tests) on a A100 GPU, we can test it internally.

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

Have you got a chance to run all the CI tests on A100?

Thanks.

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

Is there any blocker or issue? Can we make it happen in the MONAI v0.4 release note?

Thanks.

**Comment by wyli** [comment]
closing in favour of https://github.com/Project-MONAI/MONAI/issues/1472
