### ISSUE TITLE
Add support to run distributed training tests in CI

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#926]
**Is your feature request related to a problem? Please describe.**
Now we already have some distributed training test cases, like: https://github.com/Project-MONAI/MONAI/blob/master/tests/test_handler_rocauc_dist.py
Need to be executed in our CI system.
We can run with **2 GPUs in 1 node** first.

**Comment by IsaacYangSLA** [comment]
This seems straightforward.  The CI job running inside the container can see all gpus.  So we can either add one item in the bash script, or run it as a separate step in CI.  I will try to include it.

**Comment by wyli** [comment]
just a follow-up on this, the CI environment already provides 2 GPUs per job, the remaining tasks are to 
- update `runtests.sh` to run commands such as https://github.com/Project-MONAI/MONAI/blob/572c3f73a5f43dece179717939c4111e5aa46c4c/tests/test_handler_rocauc_dist.py#L41-L44
if multiple gpus are detected locally
- double-check that the CI pipeline runs the updated `runtests.sh` properly
