### ISSUE TITLE
Add 2D segmentation example

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#931]
**Is your feature request related to a problem? Please describe.**
Recently, we have received request for 2D segmentation example for internal and external users, need to add it.

**Comment by bhaghighi** [comment]
Hi, 
@Nic-Ma 
Can this 2D segmentation example be in any human imaging area? for example 2D lung Chest Xray images? 
I will work on this.

**Comment by Nic-Ma** [comment]
Hi @bhaghighi ,

Sure, thanks for your interest here!
You can refer to https://github.com/Project-MONAI/MONAI/tree/master/examples/segmentation_3d and set up a 2D example.
And you can only use very few images in the lung chest x-ray dataset, like: https://github.com/Project-MONAI/MONAI/tree/master/examples/classification_3d

Thanks.

**Comment by Nic-Ma** [comment]
Hi @bhaghighi ,

Are you going to submit a PR for this 2D segmentation example?
Thanks.

**Comment by bhaghighi** [comment]
Hi @Nic-Ma 
Yes, working on that and submit a PR as soon as it is ready.
Thanks.
