### ISSUE TITLE
Add additional test cases (image tensor: 3D) for convolutions.py

### ISSUE THREAD

**Issue by arp95** [Project-MONAI/MONAI#938]
Currently test_convolutions.py consists of test cases for 2D image tensor. Add additonal test cases for convolutions.py for 3D image tensor case.

@Nic-Ma @wyli

**Comment by Nic-Ma** [comment]
Hi @arp95 ,

Thanks for your suggestion.
I mark this as a contribution wanted task.

**Comment by arp95** [comment]
sure. i am working on this task. 
Thanks.

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/MONAI/pull/947
