### ISSUE TITLE
Port deepmedic

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#94]
a subtask of #78, port deepmedic

ref:
https://niftynet.readthedocs.io/en/dev/niftynet.network.deepmedic.html

**Comment by tvercaut** [comment]
This might warrant a separate issue but it's probably worth highlignting that the deepmedic paper relies of a post-processing by a dense CRF. The dense CRF is implemented through a permutohedral lattice approach. Although deemedic itself does not rely on backpropagating through the CRF, other papers do (e.g. CRF-RNN) and they also rely on the same permutohedral lattice approach.

As such, it would be good to have a generic permutohedral lattice / CRF-RNN module in MONAI.

A pytorch implementation of the CRF-RNN can be found here but note that the permutohedral lattice does not run on GPU there:
https://github.com/sadeepj/crfasrnn_pytorch/tree/master/crfasrnn
https://github.com/sadeepj/crfasrnn_pytorch/blob/master/crfasrnn/permutohedral.cpp

The corresponding NiftyNet module is here but lacks some GPU ops and cannot back-propagate through features:
https://niftynet.readthedocs.io/en/dev/niftynet.layer.crf.html

An alternative implementation of a GPU-based backpropagatable permutohedral lattice can be found here:
https://github.com/SamuelJoutard/Permutohedral_attention_module

This might also be interesting:
https://github.com/MiguelMonteiro/permutohedral_lattice

**Comment by brosscle** [comment]
Hello,
I would like to use and play with the network BLAST (https://github.com/biomedia-mira/blast-ct) which strongly relies on the Deepmedic architecture. Since I discovered MONAI a few days ago, I would like to know if any of you advanced in the portage of Deepmedic in MONAI. I guess I can spend some time and contribute if the portage is not already completed.
Thanks !

**Comment by wyli** [comment]
Hi @brosscle currently there's no plan from the core dev team to port this architectures, please feel free to submit a PR.

for your (or anyone interested in contributing) reference, there are a few examples about using the relevant monai APIs:
- notebook: https://github.com/Project-MONAI/MONAIBootcamp2020/blob/master/day1notebooks/lab3_networks.ipynb
- basic unet example: https://github.com/Project-MONAI/MONAI/blob/master/monai/networks/nets/basic_unet.py
- a simple unit test for the network class: https://github.com/Project-MONAI/MONAI/blob/master/tests/test_basic_unet.py

also there's a generic contributing guide: https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md

**Comment by brosscle** [comment]
I will take a look at it, thanks !

**Comment by vikashg** [comment]
closed as merged @charliebudd
