### ISSUE TITLE
change 3 channel image to 1 channel

### ISSUE THREAD

**Issue by shrutishrestha** [Project-MONAI/MONAI#944]
how to change 3 channel image to one channel during transformation. I did not find any function like transforms.grayscale to change into 1 channel image

**Comment by Nic-Ma** [comment]
Hi @shrutishrestha ,

Thanks for your suggestion, I think we can try to add such a transform.

Hi @wyli ,

Do we have some similar function in NiftyNet for reference?

Thanks.

**Comment by wyli** [comment]
for RGB to grayscale, it could be implemented with the lambda transform in monai:
```py
>>> from monai.transforms import Lambdad  
>>> import numpy as np
>>> lambd = Lambdad(keys='image', func=lambda x: x[0:1]*0.2125 + x[1:2]*0.7154 + x[2:3]*0.0721)
>>> data = {'image': np.ones((3, 10, 10))}
>>> transformed = lambd(data)
>>> transformed['image'].shape
(1, 10, 10)
```

**Comment by arp95** [comment]
@wyli the mean values for the channels you have used here: [0.2125, 0.7154, 0.0721] are different to what we usually use for pytorch transforms: [0.485, 0.456, 0.406]. is there a specific reason for which values to use as the mean?

**Comment by wyli** [comment]
> @wyli the mean values for the channels you have used here: [0.2125, 0.7154, 0.0721] are different to what we usually use for pytorch transforms: [0.485, 0.456, 0.406]. is there a specific reason for which values to use as the mean?

Hi @arp95 I think the values you provided are for channelwise normalisations, that's a different thing

**Comment by shrutishrestha** [comment]
Thanks. It worked.

**Comment by Aishuvenkat09** [comment]
Is there any way to do the reverse ? change 1 channel image to 3 channel ? Some architectures accept 3 channels as input. Instead of adding an extra layer on top and change the architecture, Is it a good idea to change image itself?

**Comment by KumoLiu** [comment]
Hi @Aishuvenkat09, you could duplicate the image three times.
```
from monai.transforms import Lambdad  
from monai.transforms.utils_pytorch_numpy_unification import stack

>>> lambd = Lambdad(keys='image', func=lambda x: stack(3 * (x,), dim=0))
>>> data = {'image': np.ones((10, 10))}
>>> transformed = lambd(data)
>>> transformed['image'].shape
(3, 10, 10)
```
