### ISSUE TITLE
How to use normalization after applying to tensor?

### ISSUE THREAD

**Issue by shrutishrestha** [Project-MONAI/MONAI#956]
<img width="935" alt="normalization library" src="https://user-images.githubusercontent.com/33342277/91325937-7aad6d80-e7e3-11ea-8eda-dac5d49e8f1e.png">

in PyTorch we used to do normalization after ToTensor so it could be normalized with mean and std like of imagenet [0.485, 0.456, 0.406] and std [0.229, 0.224, 0.225]

But here in monai, image should be in array and subtrahend and divisor also should be an array. So if we use normalizationIntensity after ToTensor like this then tensor and array together produces an error as an image in is tensor and subtrahend and divisor are in array.

ToTensord(keys = ["image","label"]),
NormalizeIntensityd(keys = ["image"], subtrahend = mean, divisor = std, channel_wise=True)

**Comment by arp95** [comment]
As far as the monai examples i have seen, ToTensor is always applied in the end of the transform. Use "ScaleIntensity()" for classification tasks and "ScaleIntensityd()" for segmentation tasks before converting image to tensor.

**Comment by shrutishrestha** [comment]
Thank you. This helped.
