### ISSUE TITLE
Bug: Github repo readme says notebooks are in old examples folder.

### ISSUE THREAD

**Issue by gagandaroach** [Project-MONAI/MONAI#965]
The Github readme says tutorial notebooks are located in the old examples folder.

**Screenshot**
![image](https://user-images.githubusercontent.com/25407172/91506442-b1dd5680-e897-11ea-92f0-d47637059dcc.png)

**Comment by Nic-Ma** [comment]
Hi @gagandaroach ,

Thanks for your bug report.
I submitted PR #968 to fix it.

Thanks.
