### ISSUE TITLE
LoadImage.__call__ kwargs passthrough for reader.read()

### ISSUE THREAD

**Issue by gagandaroach** [Project-MONAI/MONAI#966]
**Is your feature request related to a problem? Please describe.**
I am trying to load a DICOM image series stored in a pixeltype that is not included in the default ITK library. To load the file, I call `itk.imread(filepath, itk.D)` to cast the pixeltype to a library supported format. This is not possible in MONAI with the current `ImageLoader` and `ITKReader()`.

**Describe the solution you'd like**
When I call `ImageLoader`, I should be able to declare kwargs that are passed into the internal reader's read function.

`LoadImaged(keys=["image"], load_kwargs={"pixel_type": itk.D}, reader=ITKReader(), dtype=np.float64)`

Something like above to support adjusting the pixel_type param in itk.imread(). 

**Describe alternatives you've considered**
Extend `ITKReader()` for my project to include this functionality.

**Comment by Nic-Ma** [comment]
I will submit a PR to change the `**kargs` to `__init__()` of the reader instead of `read()`.
Thanks.
