### ISSUE TITLE
Specify required type in LoadPNG

### ISSUE THREAD

**Issue by tugot17** [Project-MONAI/MONAI#970]
**Is your feature request related to a problem? Please describe.**
My dataset consists of a series of images  part of which are saved in RGBA format, others are saved as simple 1 channel images. All of the images are gray-scale, however not of all of then are saved in such format. This causes a problems when I use `LoadPNG` transform since some images are loaded as arrays of size [1024, 1024] and others are of size [1024, 1024, 4]. 

Would it be possible to add argument to specify the expected img format (e.g. RGB)?

**Describe the solution you'd like**
Argument of the specified transformation to change images of all types to the specified format (eg. RGB) 

**Describe alternatives you've considered**
Loading images using PIL Image gives the effect I expect, however there is a problem with smoothly adding it to the Monai pipeline. 

```python
img = Image.open(PATH)
img = img.convert('RGB')
```

**Comment by Nic-Ma** [comment]
Hi @tugot17 ,

Thanks for your feature request!
Looks like a useful extension for MONAI image readers, we may need to consider adding some `callback` API for readers.
And to solve your case immediately, maybe you can use `PIL.Image` to convert and save your images before training?

Thanks.

**Comment by tugot17** [comment]
Yeah for now I'm using the following approach with PIL and numpy, however it is neither elegant nor most efficient solution

```python
transforms( = Compose([
            # LoadPNG(image_only=True),
            # AddChannel(),
            # RepeatChannel(self.in_channels),  ## so we can use RGB trained model
            ScaleIntensity(),
            RandRotate(range_x=15, prob=0.5, keep_size=True),
            RandFlip(spatial_axis=0, prob=0.5),
            RandZoom(min_zoom=0.9, max_zoom=1.1, prob=0.5, keep_size=True),
            ToTensor()
        ])

img = Image.open(path)
img = img.convert('RGB)
img = np.asarray(img).transpose((2, 0, 1))

transforms(img)
```
