### ISSUE TITLE
unet enhancements

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#975]
**Is your feature request related to a problem? Please describe.**
would be great to have a more flexible version of `monai.networks.nets.UNet`:
- residual connections
- anisotropic kernel/strides
- deep supervision heads?

this could be implemented as a new class instead of modifying the existing 'vanilla' UNet

**Comment by Nic-Ma** [comment]
Will add @yiheng-wang-nv for deeper discussion.
Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think @yiheng-wang-nv already completed this ticket, do we still have any missing parts?
Thanks.

**Comment by wyli** [comment]
need to rectify the class name as mentioned in https://github.com/Project-MONAI/MONAI/issues/1013, I'm closing this one and reopening #1013
