### ISSUE TITLE
Minimum python version?

### ISSUE THREAD

**Issue by dzenanz** [Project-MONAI/MONAI#977]
**Is your feature request related to a problem? Please describe.**
I just tried running `examples\segmentation_3d\unet_training_dict.py`, only to run into:
```text
(pyEnv) C:\Dev\MONAI>python examples\segmentation_3d\unet_training_dict.py
  File "examples\segmentation_3d\unet_training_dict.py", line 45
    print(f"generating synthetic data to {tempdir} (this may take a while)")
                                                                          ^
SyntaxError: invalid syntax
```

If I interpret the [docs](https://docs.python.org/3.7/tutorial/inputoutput.html) correctly, Python 3.7 is the oldest one to support `f"string"` syntax.

**Describe the solution you'd like**
I would like to see written in `README.md` that minimum supported Python version is 3.7, and newest tested and working version is 3.8.x (or whatever is the case).

**Describe alternatives you've considered**
Uninstall 3.5 and try 3.7.

**Additional context**
More specialized packages frequently do not work with "newer" versions of Python, so I went with the older 3.5.

**Comment by wyli** [comment]
this piece of information is currently 'hidden' in https://github.com/Project-MONAI/MONAI/blob/master/docs/source/installation.md#installation-guide
and https://github.com/Project-MONAI/MONAI/blob/0cbc22d309d8eb1850f6021e5a0c04b42496d7ef/setup.cfg#L13

**Comment by dzenanz** [comment]
OK, thanks.
