### ISSUE TITLE
Basis UNet

### ISSUE THREAD

**Issue by kissievendor** [Project-MONAI/MONAI#980]
On what paper is your UNet based?
The original 2D seems to differ quite a lot from the 3D U-Net by Özgün Çiçek which I'd like to use. 

Thanks.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I think this is a duplicated question, could you please help share some information?
Then I can add more paper information to the doc-string of UNet.

Thanks.

**Comment by ericspod** [comment]
I did provide some description on the UNet architecture in #464. The network in a previous format was used in [here](https://kclpure.kcl.ac.uk/portal/en/publications/leftventricle-quantification-using-residual-unet(4943f364-f436-40b9-b28c-b06fa0fdc031).html) and an upcoming paper ["Left atrial ejection fraction estimation using SEGANet for fully automated segmentation of CINE MRI"](http://stacom2020.cardiacatlas.org/accepted-papers/) also uses basically the same thing. We should have a permalink shortly for the the most recent paper.

**Comment by kissievendor** [comment]
Thanks. 
But these seem to be for 2D. 
I am using 3D segmentation, but the Network architecture seems to be different from Çiçek. 
Are you planning on implementing this network as well?

**Comment by ericspod** [comment]
The architecture of the network is the same in 2D as 3D except of course for using 3D convolutions and other layers in place of 2D. The first argument of the constructor is the setting for dimensions, with this set to 3 our network is similar Çiçek with the addition of  residual blocks.

**Comment by kissievendor** [comment]
Thank you for the quick response.
What I meant was that Çiçek doubles the number of features before max-pooling.
Here you use strided convolutions, so maybe that is different already?

**Comment by ericspod** [comment]
That is different and would require slight changes in a subclass to implement, however my experience has been that strided convolutions work better than max-pooling.

**Comment by kissievendor** [comment]
Okay, I get that. 
But is there (in your experience) a difference in performance between doubling the number of features (Çiçek) or just keep the network like it is now?

**Comment by ericspod** [comment]
By experience I'd say that it's unneccesary, you can set the number of channels per layer of the UNet we have now and with large enough values I'd think it would have the same learning capacity.

**Comment by kissievendor** [comment]
Alright. Thanks for answering my questions.
