### ISSUE TITLE
Dataset with multiple nifti files per case

### ISSUE THREAD

**Issue by neuronflow** [Project-MONAI/MONAI#982]
**Is your feature request related to a problem? Please describe.**
I digged through the monai examples and tutorials for 3d Unets, some are only based on one nifti file + seg. The Brats example deals with multiple files but data is loaded via the decathlon data sets.
3D examples:
https://github.com/Project-MONAI/MONAI/tree/master/examples/segmentation_3d
BraTS 3D U-net:
https://github.com/Project-MONAI/Tutorials/blob/master/brats_segmentation_3d.ipynb

When building my own dataset should I base it on class nifti dataset like in the array example:
https://github.com/Project-MONAI/MONAI/blob/70b442a6d8801e689d9211788a6ede744bb1c27d/monai/data/nifti_reader.py#L21

or better on monai.data.Dataset like in the dict example?

**Describe the solution you'd like**
Please provide a best-practice example for example for a BraTS case with multiple modalities e.g. T1, T1c, T2, FLAIR image + segmentation

**Describe alternatives you've considered**
I will build it myself wondering whether there was a better way.

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @neuronflow ,

Thanks for your interest here.
I think you can use `NIftiDataset`, `Dataset` or `ArrayDataset` or the optimized Datasets(like `CacheDataset`).
Because the `LoadNifti` or `LoadNiftid` transforms can support multiple files per case, it's not related to Datasets.

Thanks.

**Comment by mpsampat** [comment]
@neuronflow ! I have the same issue. I was wondering if you have an example of loading "N" nifti files per subject ? 
I am working on the BRATS dataset and want to run a simple classification task

**Comment by Nic-Ma** [comment]
Hi @mpsampat ,

For Brats, you can refer to the MONAI tutorial:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/brats_segmentation_3d.ipynb

Thanks.
