### ISSUE TITLE
monai suddenly stoped importing and produced errors

### ISSUE THREAD

**Issue by shrutishrestha** [Project-MONAI/MONAI#986]
I used this:
pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI 
to import  and this issue occurred several times

<img width="1413" alt="Screen Shot 2020-09-03 at 4 13 32 PM" src="https://user-images.githubusercontent.com/33342277/92104115-9d054380-ee00-11ea-926e-6a7b3c1393f8.png">

**Comment by rijobro** [comment]
Looks like it's trying to load `itk`, which you don't have installed. Try:
```
pip install -r https://raw.githubusercontent.com/Project-MONAI/MONAI/master/requirements-dev.txt
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Seems we don't have this issue in `min dependency tests`?
Thanks.
