### ISSUE TITLE
Caching of Dataset across Multiple Trainings

### ISSUE THREAD

**Issue by lukasfolle** [Project-MONAI/MONAI#992]
**Is your feature request related to a problem? Please describe.**
I am very new to MONAI, so please correct me if I overlooked sth. here.
I noticed that the `CacheDataset` caches non-random transforms for each subsequent training individually - even if the non-random transforms stay the same.

**Describe the solution you'd like**
I think it would be possible to reuse a built cache across subsequent trainings the following way. The make sure the non-random transforms have not changed and cache can be used a hash of the first transformed image can be calculated and compared to the hash of the first cached image.

**Describe alternatives you've considered**
Alternatively, saving the used transforms and checking for changes at each new `init` of the `CacheDataset` could also be possible.

**Additional context**
Please provide me feedback on the feasibility of this idea and your thoughts on the potential performance gain!

**Comment by Nic-Ma** [comment]
Hi @lukasfolle ,

Thanks for your interest and your experiments with MONAI.
I don't quite understand your question, do you mean reuse the cached content for future training?
If so, you can use the `PersistentDataset` to cache content into files.

Thanks.

**Comment by lukasfolle** [comment]
Thank you for the hint. Seems like I overlooked that.
Could you elaborate on the difference between `CacheDataset` and `PersistentDataset`?

**Comment by rijobro** [comment]
For future reference, [this](https://github.com/Project-MONAI/Tutorials/blob/master/dataset_type_performance.ipynb) tutorial has a clear explanation of the difference between `CacheDataset` and `PersistentDataset`.
