### ISSUE TITLE
Enhance padding function and Convolution module

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#993]
I found two limitations of our Convolution module:

- strides can only be a single value. Whereas, sometimes different stride values for different dimensions is useful.
- padding method is fixed via using same padding. I think that making it more general will be more helpful.

I will release a pr to enhance these two places soon, and add some other padding methods. After implementing these places, enhance unet (#975 ) will be easier.

**Comment by wyli** [comment]
fixed by #996
