### ISSUE TITLE
how to use seed for data augmentation while using compose?

### ISSUE THREAD

**Issue by shrutishrestha** [Project-MONAI/MONAI#998]
I am using data augmentation using the compose of generic interfaces.
  train_transform = monai.transforms.Compose(
    [
        LoadPNGd(keys = ["image","label"]),
        set_random_state(seed = 0),
        AsChannelFirstd(keys = ["image","label"], channel_dim = -1), 
        Lambdad(keys=['label'], func=lambda x: x[0:1]*0.2125 + x[1:2]*0.7154 + x[2:3]*0.0721),
        Resized(["image","label"],spatial_size=(256,256)),
        ScaleIntensityd(keys = ["image","label"], minv=0.0, maxv=1.0),
        # RandGaussianSmoothd(keys=["image"]),
        # RandGaussianSharpend(keys=["image"]),
        # RandShiftIntensityd(keys=["image"], offsets=1.0),
        RandAdjustContrastd(keys = ["image"], prob = 0.3),
        RandGaussianNoised(keys = ["image"], prob = 0.5),
        RandRotate90d(keys = ["image","label"],prob = 0.5),
        RandFlipd(keys = ["image","label"], prob=0.5),
        RandRotated(keys = ["image","label"], range_x=180, range_y=180, prob=0.5),
        RandZoomd(keys = ["image","label"], prob=0.2, min_zoom=1, max_zoom=2),
        RandAffined(keys = ["image","label"], prob = 0.5),
        Rand2DElasticd(keys = ["image","label"], magnitude_range=(0,1), spacing=(0.3,0.3), prob=0.5),
        NormalizeIntensityd(keys=["image"], subtrahend=mean, divisor=std),
        # NormalizeIntensityd(keys=["label"], subtrahend=R_mean, divisor=R_std, channel_wise=True),
        ToTensord(keys = ["image","label"])
    ]
    )

how to use the seed for this. I saw set_random_state inside the compose class but could not find how to use it.
are seed different for every transpose or its set one time for a list of transpose inside compose

**Comment by Nic-Ma** [comment]
Hi @shrutishrestha ,

If you want to enable `deterministic training`, the easiest way is to call `set_determinism(seed=XXX)` at the beginning of your program, refer to:
https://github.com/Project-MONAI/Tutorials/blob/master/spleen_segmentation_3d.ipynb
If you just want to set random seed for these transforms, you can call `train_transforms.set_random_state(seed=XXX)` in your program, it sets the same seed for all transforms in the list.

Thanks.
